### ISSUE TITLE
Verses with multiple Bookmark lables are deleted altogether... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#0]
Running 509 alpha build:

1) assign a verse to a bookmark lable and a speak bookmark. 
2) go to bookmark list.
3) instead of listing all bookmarks, select speak from the drop-down list at the top.
4) select the verse that has multiple lables by tap and hold.
5) tap the trash icon.

What happens: all bookmarks for that verse are deleted.

Expected result:  only the speak bookmark should be deleted as it was in the context of the list.  it helps in deleting multiple speak bookmarks without deleting other important labeles associated to any verse.

**Comment by timbze** [comment]
Weird that this is issue #0

**Comment by bvahedy** [comment]
Don't know how that happened.

**Comment by tuomas2** [comment]
I have since added warning "Do you want to remove 1 bookmarks and their notes?" to bookmarks window. I think it works as expected.
