### ISSUE TITLE
Soft keyboard does not pan properly on some devices

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1001]
Soft keyboard goes over input area on my phone.

**Comment by bvahedy** [comment]
I can't duplicate this, do we know what devices this happens on?

**Comment by tuomas2** [comment]
Emulator (API 30 at least) and my Sony Xperia phone

**Comment by tuomas2** [comment]
You can see it even in beta video https://www.youtube.com/watch?v=ZpZ25uqR_BY

**Comment by tuomas2** [comment]
Now does not reproduce on my tablet and on emulator (API30) but does still on my xperia phone.

**Comment by tuomas2** [comment]
Also it does not ever pan in landscape mode.

**Comment by tuomas2** [comment]
Since #667, launchMode="singleTask" was removed from MainBibleActivity and after changed to singleTop. I tested with singleTask mode and it works properly with my mobile phone.

**Comment by tuomas2** [comment]
But I guess we don't want to break #667...

**Comment by tuomas2** [comment]
tested again on my mobile singleTask and it does not work either. My mobile is weird.

**Comment by tuomas2** [comment]
I don't think there's anything we can do to fix this. Hope it does not affect many users.
