### ISSUE TITLE
Automatic checking for js side translations

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1003]
Need to check that translation files have %s etc in correct places as transifex does not check them. Otherwise we will have js side errors as a result... 

Python script that is executed when doing make tx-pull will do fine.

**Comment by JJK96** [comment]
Doesn't this create an XSS vulnerability through transifex?

**Comment by tuomas2** [comment]
python script that does some analysis after tx pull exposes to xss?

**Comment by JJK96** [comment]
No, I mean, the whole blindly pulling from transifex. Or does transifex protect against JavaScript in the strings?

**Comment by tuomas2** [comment]
good point. but i think we are safe because strings are loaded from yaml files, not js directly. but worth checking.

**Comment by JJK96** [comment]
I think so too, but format string vulnerabilities maybe? I have to check how JavaScript handles that
Edit: It seems JavaScript is not vulnerable to these kind of attacks.
