### ISSUE TITLE
Allow user to choose book order and save such setting

### ISSUE THREAD

**Issue by jmarsican** [AndBible/and-bible#1013]
Very nice UI improvements! I have a few suggestions, but @tuomas2 should affirm or deny my suggestions before you make changes based on them.

- [ ] Leave the default book order the way it was (in portrait mode the books go by column, in landscape by row)
- [x] Add back (up) button in toolbar (can be done by modifying manifest file) #997
- [ ] All settings would save in Db that way the user's preference would again be used next time
- [ ] Instead of current toolbar sort button on right, add a 3-dot menu with:
  * Sort by book order [checkbox in menu group 1] << this would be default
  * Sort alphabetically [checkbox in menu group 1]
  * Separator
  * Order books by row [checkbox in menu group 2] << off by default, but when checked the books would also order by row in portrait mode the way landscape already does by default

_Originally posted by @timbze in https://github.com/AndBible/and-bible/issues/994#issuecomment-826886651_

**Comment by timbze** [comment]
Was implemented by #1122
