### ISSUE TITLE
Possible improvements to the bookmark dialog (not the popup)

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1014]
Here are a few ideas that have come to mind while getting use to the new features.

- [x] * Change the button arrangement. Clicking the ellipsis to show the additional options, and then having to click the info button to see more details seems unnecessary. 
- [x] * Just show the info button and move the delete and share buttons into the dialog itself. 
- [x] Also, can add a button there for editing the note and for assigning the labels (this duplicates the label assigning functionality because it is also accessible by clicking the label itself but there is space for an extra button and it make it a bit more obvious)
- [x] * Put the colored labels at the top above the verse. That seems tidier to me.
- [x] * Move the bookmark icon (which i think is identifying the label which is attached to the bookmark) into the colored box.
- [x] * Move the more useful info (studypad links) up 
- [x] * Add some little icons to the links to tie them more clearly to the labels. I would remove the word 'window' as well - that's not really needed... unless they can be opened somewhere else that I don't know about.
- [x] * Reduce the size of the less useful info (creation info)
- [x] * Move the less useful info to the bottom.

![AndBible Suggestions-Bookmark Dialog](https://user-images.githubusercontent.com/13920678/116839986-9a6d1f00-ac17-11eb-934f-5b7236880260.png)

**Comment by tuomas2** [comment]
Again, looks very nice! I'll (very likely) try some of these ideas. Thank you!

**Comment by agrogers** [comment]
It looks like you have done it already. You're fast. I look forward to
checking it out. And I wouldn't have guessed you are using Vue. That's cool
too.
