### ISSUE TITLE
Proposal for streamlined pre-bookmark dialog

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1015]
Hi. The image below describe the work flow that I think could be streamlined. It also maximises the use of the colors for the labels.

At present there is 
* a popup that shows a list of the bookmarks the user clicked on. 
* From that you can go to another dialog asking whether you want to assign labels or open a studypad.
* The links on the colored labels can be a little hard to click on and it is not obvious what they might do (or that they are there at all)
* The big bookmark 'button' takes you to another dialog that then has a pop out menu that can expand the dialog.

The modified dialog below could eliminate all the intermediary steps and I think is easier to understand and maybe a little prettier.

- [x] * A bookmark can be deleted directly from this screen
- [x] * The icon buttons are colored to indicate what they do. 
- [x] * The label icon is gray because it takes you to the label form which allows removal or addition of any label.
- [ ] * The edit, info and share icons are the color of the bookmark because, as I understand it, all those actions are directly linked to the bookmark label.
- [x] * The study pad icons are in the color of the label. I think accessing the study pads are the only label specific actions.
- [x] * The present links on the labels (eg 'God-Love of') could be removed
- [x] * The dialog has more space to show the text and perhaps the reference
- [x] * The cancel button is not really needed because the X in the top right corner does the same thing.

![AndBible Suggestions-boomark pre-dialog](https://user-images.githubusercontent.com/13920678/116842014-61847880-ac1e-11eb-91d8-e6cedc271623.png)

And where each button icon takes you...

![AndBible Suggestions bookmark predialog flow - old and new](https://user-images.githubusercontent.com/13920678/116842155-fbe4bc00-ac1e-11eb-9628-7fee4900e646.png)

**Comment by tuomas2** [comment]
Beautiful and nice UX&UI design, thank you! I might implement this at some point.

**Comment by agrogers** [comment]
Great. I noticed yesterday that you also have an icon indicating that a
note exists. I think that could possibly be handled by either changing the
Edit icon to a different shape or perhaps simply leave the edit icon gray
unless it has an existing note at which it would be colored.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
what is this "studypad icon", can it be found from fontawesome? https://fontawesome.com/icons?

**Comment by tuomas2** [comment]
file-alt maybe ok

**Comment by agrogers** [comment]
Hi Tuomas. I think it was this one. I have a subscription to this service. Not sure if that helps you. 

https://www.flaticon.com/premium-icon/note_4023112?term=ui%20note&page=1&position=5&page=1&position=5&related_id=4023112&origin=style

**Comment by agrogers** [comment]
I could easily remake the icon as well.

**Comment by tuomas2** [comment]
Implemented
