### ISSUE TITLE
Proposal for display of primary bookmark label

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1016]
As I understand it, a bookmark has a label and then additional labels can be added to an existing bookmark. I think this is indicated by a little bookmark icon of the correct color as seen here:
![image](https://user-images.githubusercontent.com/13920678/116842528-2b47f880-ac20-11eb-9ded-87643b3f4262.png)

It feels more intuitive to me to place the bookmark icon inside the label that is attached to the bookmark as shown below.
![image](https://user-images.githubusercontent.com/13920678/116842429-e2903f80-ac1f-11eb-905a-4355e8b6e42f.png)

So when there are labels attached to a bookmark it is very simple to see which is the bookmark label and which is an additional label.
![image](https://user-images.githubusercontent.com/13920678/116842630-7feb7380-ac20-11eb-998e-192e1c3c9718.png)

**Comment by tuomas2** [comment]
Labels are m2m-relation, and the first one in list is "primary". This we probably should change (make it possible to determine primary label).

UI looks beautiful. I might try it out.

**Comment by agrogers** [comment]
I think you have done this one Tuomas. Looks good. Although i have found a little bug with it - i think i will put it in another issue.

**Comment by tuomas2** [comment]
Yep, closing this
