### ISSUE TITLE
Proposal for whole verse highlighting

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1017]
I really like the character based highlighting and have been using it a lot. However i think there is still a place for whole verse highlighting. Perhaps it is still possible - but i have not found it. My thoughts are:
* It is nice to have bookmarks appear across translations when possible. With whole verse highlighting this was possible.
* Sometimes i want to highlight the whole verse. But this is a little tricky due to the manual text selection.
* Unlike me, I think most people probably do want to highlight the whole verse rather than words within the verse.

I have made some suggestions here for how this could be accomplished here: https://github.com/AndBible/and-bible/issues/859#issuecomment-831023656

My guess about how to do this properly would be:
* a bookmark needs to be tagged with 'whole verse' or verse reference(s) some how. You seem to have this already since my old bookmarks have carried through and do still show across all translations.
* It would be nice to be able to manipulate this 'whole verse' tag. That way an existing bookmark could be made a whole verse bookmark by simply setting that flag (a check box?).
* I would possible display whole verse bookmarks differently. The trouble with them is they cover too much. I would display them as an underlined verse rather than the setting the background of the verse. So we can see both the whole verse and the word based bookmarks.  This is how i used to highlight in my bible. What you have done in AndBible is getting very close to what i did in my paper bible 30 years ago. And i have enjoyed getting back into it!

![AndBible Suggestions-underlining](https://user-images.githubusercontent.com/13920678/116843508-82030180-ac23-11eb-9eda-272c92d1136c.png)

**Comment by Dleemuse** [comment]
Yes, I do miss being able to highlight a whole verse or a range of verses with a simple click.

Debra

**Comment by tuomas2** [comment]
What should we do if there are two bookmarks with "highlight whole verse" and they both would like to get their underline there?
We can't have multiple underlines using CSS.

**Comment by tuomas2** [comment]
Implemented otherwise, but not underline style.

**Comment by agrogers** [comment]
> Implemented otherwise, but not underline style.

Hi Tumoas. I think by 'implemented' you mean just using the current method. That's ok. But I think it can be better :)

> We can't have multiple underlines using CSS.

It's possible although it might make your code a little harder to manage. Below is what I could come up with and attached it the code I used/stole to do it.
[special_underline.html](https://github.com/AndBible/and-bible/files/6520999/special_underline.html.txt)

Again, the reason I like this approach is because:
1. I find reading a passage when the whole verse is highlighted to be a little uncomfortable. The highlight is too dominant and i feel like it breaks my focus.
2. The highlights that I really want to see clearly are the single word/phrase highlights. When the whole line is highlighted these words are then highlighted with a half height. So now the verse highlight is taking over the word highlighting. It gets worse if that word is highlighted again in a larger piece of text. Now it is down to a third height.
3. Often i want to indicate that a whole section - say five verses or more - is about a particular topic and then pick out particular words or phrases that are important to me. 
4. But I avoid highlighting whole verses because I personally don't want the verse/ passage/ chapter to be all yellow :) If i want that much color i can change the window background color ;-)

Perhaps the ultimate solution for me would be to be able to specify the type of highlight - background or underline - with whole verses by default being underlined and phrases being background highlighted. If this became possible it would mean that my old paper bible highlighting method is now completely possible in And Bible :D  

![image](https://user-images.githubusercontent.com/13920678/119101057-ef07fb00-ba5b-11eb-8c3e-50cb027f2bbe.png)
