### ISSUE TITLE
Be able to add a bookmark in any window

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1018]
For some reason I was not able to add a bookmark in one of the windows i managed to get to. I think it was the studypad view.  Short video here: https://drive.google.com/file/d/1eb9bMNhXCfhruvdA6niIbuTtY8U4J967/view?usp=sharing

Thanks

**Comment by tuomas2** [comment]
I agree that it would be nice feature. 

However, I have intentionally decided to not implement adding/showing bookmarks in my notes, multidocument and studypad views.  The reason is that it would complicate and slow down code quite a bit due to synchronizing between windows etc. 

Though if someone implements this in an efficient and nice way I'm open to PR's :-)

**Comment by agrogers** [comment]
I didn't really need to see the bookmarks. I just wanted to be able to add
one. But I suspect that one is dependent on the other....

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
It would be possible to implement "add" only, but user experience wouldn't be great (user would be left wondering where is my bookmark). Though we could tell him about it with a toast message, but still, it would be not very good UX. But, I'll open this so I can consider implementing only this.

**Comment by agrogers** [comment]
Yeah, I agree. And you may already have it bookmarked and be trying to do
it a second time. So i think i agree that it is probably better to either
have all functionality or none.

The suggestions here  https://github.com/AndBible/and-bible/issues/687
that proposed being able to copy a reference from one window and paste it
into another window would kind of solve the problem. That is, I could
fairly easily jump to the verse I want to bookmark in a standard window and
bookmark it there.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
But you can also currently click the blue verse reference link to open it in separate window?
