### ISSUE TITLE
Very helpful

### ISSUE THREAD

**Issue by tse-gratis** [AndBible/and-bible#102]
I just wanted to say thankyou.  This app has been really helpful, particularly with refugees.  It is a necessity to use multiple languages here.  You've let me put the languages I need side by side, and read them together.  There's no other app on iphone, or android that will do that

(Other apps either only display two languages, or they don't have the languages I need)

https://tse.gratis/

**Comment by cmahte** [comment]
If/when you have the need, check Out PocketSword on iphone.  It's a closely
related app which provides (nearly) the same set of texts.

**Comment by tuomas2** [comment]
Thank you for the feedback :) Closing this as there's no work related to this issue.
