### ISSUE TITLE
Ensuring that the bookmark keeps its original color

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1022]
My understanding is that the bookmark color is determined by the order of creation of the labels. This can be a problem when i add a new label that was created **before** the currently attached label. The color of this second label will now be the one used to highlight the verse. 

So in the present system i dont really have control over the color of the highlight when i have added multiple labels - it will get the color of the first created label.

My preference would be that the color of the highlighting is determined by the first label **added to the bookmark**. Thus future labels wont affect the highlight color. If i want the color to change then i simply remove all the labels except for the one with the color i want then add back in the other labels.  Make sense?

Video here:
https://drive.google.com/file/d/1eJXv3sOSzLuRw9Ok5gh9oKcUyGrQBt3b/view?usp=sharing

**Comment by tuomas2** [comment]
Idea about having first label determine the color sounds good and makes sense from UX point of view. 

I myself have thought that we should have simple "priority order" for labels, and first priority label would be used. 
Need to think about this...

**Comment by agrogers** [comment]
Would the label priority order apply to all bookmarks? If so, i think that
might have the same problem where a subsequent label changes the existing
color. I can see where that would be good at times. But i think i would
prefer the ability to control the color on a bookmark by bookmark basis.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
I guess we just need to be able to mark one label as priority label in bookmark level.

**Comment by agrogers** [comment]
Yes, perfect. That is better than adding and removing to get them in the
correct order. But also one more thing you have to code. If the user wants
to change the color frequently then your option is good. But I would
simply create a new bookmark for the same passage and give it a different
label and then hide the bookmark with the label i dont want.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Implemented
