### ISSUE TITLE
The bookmark modal should not be allowed to go off the screen

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1023]
Sometimes i thought the app was losing my clicks but it was because the dialog had scrolled off screen. So my clicking was working but i couldnt see that it was working because the window was offscreen.

Perhaps keeping the dialog from scrolling offscreen would be an option. Or closing it and opening it whenever someone clicks on a bookmark.

Video:
https://drive.google.com/file/d/14UqqUYBQPk5WkrfNhno_dsqhhHRJGdr2/view?usp=sharing

**Comment by tuomas2** [comment]
I think I'll make it re-locate itself it when scrolling.

**Comment by agrogers** [comment]
I like that solution. Thanks.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Implemented

**Comment by bvahedy** [comment]
I'm reopening this since it still happens when the bookmarks has multiple lables that go off the screen boundaries.  The modal still gets lost.

**Comment by bvahedy** [comment]
Verified fixed in 522.2 beta build.

**Comment by agrogers** [comment]
Yes. It works well. Just one comment. When I scroll up and the dialog goes
off the bottom of screen it reappears at the top of the screen. It feels
like it should stay at the bottom. Not a big issue though.
