### ISSUE TITLE
Improvements to how the labels list is ordered / grouped

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1024]
I am getting a lot of labels. And i have only been using them for a week :D  My suggestions are:
* At the top of the labels list show the current selected labels for this bookmark (orange box). I am often scrolling down trying to find the existing ones to remove or change their color.
* Under that show the three recently used bookmarks (purple box). 9 times out of 10 this list would hold the bookmark i am wanting because i usually bookmark the same idea across a few verses.
* Show the rest of the labels in alpha order below (green box)

![image](https://user-images.githubusercontent.com/13920678/116844990-f93a9480-ac27-11eb-9437-d56864a6a094.png)

And a video here:
https://drive.google.com/file/d/1aGUqnWGQnP7f2NJnp-gh0R_3lx7mnYJh/view?usp=sharing

**Comment by tuomas2** [comment]
This is good suggestion that we have already also discussed a little with developers.
Good UX design for this would help me/us in development :-)

**Comment by agrogers** [comment]
My thoughts on this were pretty simple and not a big departure from what you have already.
* Active group: can be any number of labels. If none are selected then the group could disappear altogether. Of course these are always ticked.
* Recent group:  This should read 'Recently Used Labels'. It is **not** recently created labels. Maybe limit to 3 or better still be user specified (a slide in the options somewhere from 0-10). I would be tempted to make that limit large because I'm much more likely to be adding a label that i have used recently
* Other labels: everything else. I wouldn't show any label more than once. And I wouldn't move labels between groups while the user is selecting them.
* Filter icon: does nothing at the moment. But one day it may be necessary/desirable to filter labels (as per my label category suggestion).
* All: Might be useful now when selecting which labels to show. Not that useful until filtering is implemented.
* None: Could be used to delete all bookmarks/labels. Again, more useful when filtering is implemented i think.

![AndBible Suggestions-Label dialog](https://user-images.githubusercontent.com/13920678/116864726-a70b6a80-ac4b-11eb-8164-f54855d9bd03.png)

**Comment by tuomas2** [comment]
Okay this looks good to me! Thank you! Actually I was more thinking about #1025 when I was asking for UX help.

**Comment by tuomas2** [comment]
(sorry, I have personally time to more carefully look at these approx once per week, just quickly had a glance on these... thank you for all the ideas/comments!)

**Comment by agrogers** [comment]
No problems. I am really happy with the latest version. It has exceeded my expectations! And yes, I thought this one was pretty simple too :D  Issue #1025 is much harder and I don't really understand the latest version well enough to make good suggestions yet. I will spend this week playing with it more and see if i can put something together after that. Thanks again. I love your work.

**Comment by agrogers** [comment]
[moved content to #1035]

**Comment by tuomas2** [comment]
I think this is implemented now
