### ISSUE TITLE
Show toast with active workspace name on cold start

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1030]
It would be nice for me if I knew which workspace is active without having to open workspaces window. 

I think it could be just when the app cold starts, then show a toast with workspace name, same as it does now in switching workspace. 

Also, toast should not show if user only has 1 workspace.

**Comment by agrogers** [comment]
I have colored my workspaces to make it easier to know which one I am working in. But maybe showing a toast message when the workspace is changed is also a good idea. I have personally never felt i needed it though.

**Comment by agrogers** [comment]
I suggest we delay this one to after v3.4 release
