### ISSUE TITLE
Some label colors can be hard to read

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1034]
This is less a bug and more a poor user choice. An example is shown below. Interestingly it looks better on my PC than it does on the phone.  With some colors i find the text almost ureadable on my phone. One solution is just to chose better colors. That has been my approach to date. But i wonder whether it would be better to show labels that are hard to read as black on color not white on color.

Some code to work out when to use what can be found here:
https://stackoverflow.com/questions/1855884/determine-font-color-based-on-background-color
and here:
https://stackoverflow.com/questions/3942878/how-to-decide-font-color-in-white-or-black-depending-on-background-color

Personally I like the consistency of white on color and am not sure i will like the look of black-on-color mixed in with white-on-color. Maybe usability is more important than aesthetics though.

It doesn't happen much to me - that is i rarely chose a bad color - so it seems like you might have something there to help me chose better colors.

![AndBible Suggestions - hard to read labels](https://user-images.githubusercontent.com/13920678/117521908-a845ea00-aff3-11eb-86c6-da1e2c5b9f1b.png)

**Comment by agrogers** [comment]
This has been resolved too I think. 

What are the 'tasks' mentioned above???

**Comment by tuomas2** [comment]
tasks are crosses (ticked / unticked). I mean this

- [ ] this is a task

**Comment by tuomas2** [comment]
But closing this also
