### ISSUE TITLE
Proposal for adjustments to the bookmark creation/edit dialog

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1035]
Trying to put these screen samples in the correct ticket.  The one here improves on the one above and includes the new favourite labels feature:
![AndBible Suggestions bookmark color dialog suggestions v3](https://user-images.githubusercontent.com/13920678/118394587-ecd32480-b688-11eb-8192-c62ec0a87aa4.png)

This related to #1059

- [x] * Remove the delete icon from the main list. I would rarely every use this - if i did it was probably by accident :)
- [x] * Show which labels are currently getting assigned to new bookmarks by placing the label icon on a circular colored background (eg 'Boasting'). This icon is also a checkbox control...
- [x] * Turn the label icon into a checkbox that controls the labels that are assigned to new bookmarks. ~At present this functionality exists in the WindowButton > Text Options > Assign Labels.  I find i dont go there to do this because it feels like it takes too long.~ Moving or duplicating this functionality in the label assigning process feels right to me. Putting it here means i can add a book mark label and set it as the new bookmark label for future bookmarks. 
- [ ] * A problem remains that the previously assigned labels for new bookmarks are still selected. And it might be hard to find them to uncheck them. This is partly addressed in the filter form in #1036 . But it would be better to be able to do it right here in this form. 
- [ ] * Perhaps long pressing the label icon could bring up a dialog that asks 'Make this the only label assigned for new bookmarks?'  That way i could clear all the others and set the new one in a single click.

- [x] This responds to Tuomas' video here: https://www.youtube.com/watch?v=n7qaupKMOMc

- [ ] * The heart and star columns in the video take up a lot of space but convey very little info. I am also not sure how often or easily those options need to be set or cleared.
- [ ] * With regard to setting the primary label, this could be done more logically in the bookmark dialogs (see #1059). 
- [ ] * - I think it is desirable to show which is the primary label in this list. It just doesnt need to be a button and we dont need to see all the labels that are *not* primary

With regard to the favourite labels:

- [ ] * - I am not sure how often I would use these. I dont  think i would be changing that list very often. So again, if it is not being changed frequently, I dont think it deserves an editable column.... unless there is ample space.
- [ ] * - The same goes for the delete icon. I would definitely remove the delete icon and possibly replace it with the heart. I have removed both in the sample above because I personal don't think i would need such easy access to either of them. I can simply edit the and set it there.
- [ ] * - However i could *unset* the favourite in the list view - the icons are present so clicking on them could clear it.
- [ ] * I like the use of the star icon because it makes it very clear which label is the primary one. It could also be done with underlined text or something but the star is clear. 
- [ ] * - However I am not sure that the star is the right icon to use. We are identifying a primary label by using the bookmark icon elsewhere. This should be consistent - either star or bookmark - not both.
- [ ] * Including the icons in the description in the color dialog explains to the user what those icons do. This is very helpful for new users. We dont need a manual for this.
- [ ] * - All settings should be viewable and configurable in this dialog. It is the slow way to change things but it is good for new users
- [ ] * I don't think the edit icon button is needed either. Again, if there is ample space then it is helpful. But if we need to make room, it is an icon that can disappear. We can edit just by clicking on the label entry itself.

- [ ] My sample above is starting to get busy. I am trying to identify 1) the primary label (star), 2) the favourite labels (heart) and 3) labels automatically assigned to new bookmarks (colored circle with white label color). It would be clearer if they all had their own column. But I feel like that is an unnecessary use of space. Removing both edit and delete icons would make it easier to introduce new columns.

**Comment by agrogers** [comment]
This is a response to Tuomas' video here: https://www.youtube.com/watch?v=n7qaupKMOMc
And is related to #1059
![AndBible Suggestions bookmark color dialog suggestions v3](https://user-images.githubusercontent.com/13920678/118350161-a0a8b700-b598-11eb-9d09-c6fe6df1f163.png)
* My comments in the first post are still mostly relevant I think.
* I understand this was just a first draft without much attention to UI as you said
* The heart and star columns take up a lot of space but convey very little info. I am also not sure how easily those options need to be set or cleared.
* With regard to setting the primary label, this could be done more logically in the bookmark dialogs (see #1059). 
* - I think it is desirable to show which is the primary label in this list. It just doesnt need to be a button and we dont need to see all the labels that are *not* primary
* - And I think the grouping as described here and #1024 provides more visual clarity
* With regard to the favourite labels:
* - I am not sure how often I would use these. I dont  think i would be changing that list very often. So again, if it is not being changed frequently, I dont think it deserves an editable column.... unless there is ample space.
* - The same goes for the delete icon. I would definitely remove the delete icon and possibly replace it with the heart.
* I like that the star icon because it makes it very clear which label is the primary one. It could also be done with underlined text or something but the star is clear.
* Including the icons in the color dialog explains to the user what those icons do
* - All settings should be viewable and configurable in this dialog. It is the slow way to change things but it is good for new users
* I don't think the edit icon button is needed either. Again, if there is ample space then it is helpful. But if we need to make room, it is an icon that can disappear. We can edit just by clicking on the label entry itself.

**Comment by agrogers** [comment]
This is the problem I have now with insufficient space in list to read my labels. 
![IMG_20210516_161032](https://user-images.githubusercontent.com/13920678/118387442-ee3d2680-b661-11eb-9f28-96d0159da3f6.jpg)

**Comment by tuomas2** [comment]
> This is the problem I have now with insufficient space in list to read my labels.

This should be a separate bug issue

**Comment by agrogers** [comment]
> > This is the problem I have now with insufficient space in list to read my labels.
> 
> This should be a separate bug issue

You are right. I was getting confused with this one due to first screen shot above - they are much the same because they show both the list and the dialog. I have moved the relevant comments across to #1024

**Comment by tuomas2** [comment]
removed description from here as up-to-date version is on #1024 comment. (not sure if it should be here or there, but better not both)

**Comment by tuomas2** [comment]
Moved description back here.

I implemented some of the ideas now in build 521.2


> Trying to put these screen samples in the correct ticket.  The one here improves on the one above and includes the new favourite labels feature:
> ![AndBible Suggestions bookmark color dialog suggestions v3](https://user-images.githubusercontent.com/13920678/118394587-ecd32480-b688-11eb-8192-c62ec0a87aa4.png)
> 
> This related to #1059
> 
> - [x] * Remove the delete icon from the main list. I would rarely every use this - if i did it was probably by accident :)

Done. 

> - [x] * Show which labels are currently getting assigned to new bookmarks by placing the label icon on a circular colored background (eg 'Boasting'). This icon is also a checkbox control...
> - [x] * Turn the label icon into a checkbox that controls the labels that are assigned to new bookmarks. ~At present this functionality exists in the WindowButton > Text Options > Assign Labels.  I find i dont go there to do this because it feels like it takes too long.~ Moving or duplicating this functionality in the label assigning process feels right to me. Putting it here means i can add a book mark label and set it as the new bookmark label for future bookmarks. 

Done these also. I'm not sure if I like the this though. I'm not feeling that user immediately understand how to use it (does not look like checkbox). 

>  * A problem remains that the previously assigned labels for new bookmarks are still selected. And it might be hard to find them to uncheck them. This is partly addressed in the filter form in #1036 . But it would be better to be able to do it right here in this form. 
> * Perhaps long pressing the label icon could bring up a dialog that asks 'Make this the only label assigned for new bookmarks?'  That way i could clear all the others and set the new one in a single click.

This could be considered but not yet implemented.

> 
> - [x] This responds to Tuomas' video here: https://www.youtube.com/watch?v=n7qaupKMOMc
> 
> * The heart and star columns in the video take up a lot of space but convey very little info. I am also not sure how often or easily those options need to be set or cleared.

I feel that I disagree on this at the moment. I left them there as I found it more easy to manage these settings from list view. 
It is also a bit difficult to change this implementation.... 

> - [x] * With regard to setting the primary label, this could be done more logically in the bookmark dialogs (see #1059). 

Yes. Left to #1059

> - [x] * - I think it is desirable to show which is the primary label in this list. It just doesnt need to be a button and we dont need to see all the labels that are *not* primary

I left in this version bordered stars also for quick setting of primary label. 

> With regard to the favourite labels:
> 
> - [ ] * - I am not sure how often I would use these. I dont  think i would be changing that list very often. So again, if it is not being changed frequently, I dont think it deserves an editable column.... unless there is ample space.

Not sure if this deserves column in assign labels view but I feel that it should be in workspace favourite & auto assign view.

> - [x] * - The same goes for the delete icon. I would definitely remove the delete icon and possibly replace it with the heart. I have removed both in the sample above because I personal don't think i would need such easy access to either of them. I can simply edit the and set it there.

Removed it -> removal through label edit activity.

> - [x] * - However i could *unset* the favourite in the list view - the icons are present so clicking on them could clear it.
> - [x] * I like the use of the star icon because it makes it very clear which label is the primary one. It could also be done with underlined text or something but the star is clear. 
> - [x] * - However I am not sure that the star is the right icon to use. We are identifying a primary label by using the bookmark icon elsewhere. This should be consistent - either star or bookmark - not both.

This should be considered still. What do you propose?

> - [x] * Including the icons in the description in the color dialog explains to the user what those icons do. This is very helpful for new users. We dont need a manual for this.

I agree this is good idea. Using same symbols in both views then makes list view also intuitive.

> - [x] * - All settings should be viewable and configurable in this dialog. It is the slow way to change things but it is good for new users
> - [x] * I don't think the edit icon button is needed either. Again, if there is ample space then it is helpful. But if we need to make room, it is an icon that can disappear. We can edit just by clicking on the label entry itself.
> - [x] My sample above is starting to get busy. I am trying to identify 1) the primary label (star), 2) the favourite labels (heart) and 3) labels automatically assigned to new bookmarks (colored circle with white label color). It would be clearer if they all had their own column. But I feel like that is an unnecessary use of space. Removing both edit and delete icons would make it easier to introduce new columns.

Please give it a try and let me know how it feels. Note that same activity is used in 5 different contexts:
- Assigning labels to bookmarks
- Per-workspace favourite & auto assign settings
- To select studypad to open
- To config per-window/per-workspace hidden labels
- To manage labels in general (main menu)

It works a little differntly in different contexts, and some ui elements are not displayed everywhere.

**Comment by tuomas2** [comment]
Comments are welcome also for the new strings, if they are good or not

(https://github.com/AndBible/and-bible/pull/1080/files , see strings.xml)

**Comment by tuomas2** [comment]
I believe this is now satisfactorily implemented
