### ISSUE TITLE
Dotted line with hebrew punctuation hard to read

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1037]
The dotted line for strong under the words make it really hard to read the Hebrew punctuation. Would it be possible to change the lines color to (a light) gray for example? This would make it slightly easier to distinguish between the punctuation and the line 

https://support.andbible.org/scp/tickets.php?id=503

**Comment by bvahedy** [comment]
Note to self:
To test need to use OSMHB bible and tap on the icon on the toolbar to switch Strong's no. on/off.

**Comment by tuomas2** [comment]
perhaps for hebrew modules specifically we could change style here. I wonder if there are other languages that should have the same? (probably nothing with strongs though).

**Comment by agrogers** [comment]
Can someone post a screenshot? Would a semi transparent underline help?

**Comment by tuomas2** [comment]
I think helpdesk has screenshot

**Comment by tuomas2** [comment]
![Screenshot_20210802_162230](https://user-images.githubusercontent.com/5811789/127868688-9e097612-a48c-4785-8c39-ecb2731544e9.png)

Semi-transparent solid  underline will be used hebrew (he, hbo) language texts.
