### ISSUE TITLE
Sharing an existing bookmark from the 'Migrated My notes' label via the new bookmark dialog crashes

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1039]
It was reported here: https://support.andbible.org/scp/tickets.php?id=500
I have confirmed it crashes on my device as well. Seems to only apply to migrated notes.

![image](https://user-images.githubusercontent.com/13920678/117539231-17036180-b04d-11eb-908e-dcfbcc42a36c.png)

**Comment by tuomas2** [comment]
Duplicate of #1072, which is now fixed
