### ISSUE TITLE
Color issues with the pre-bookmark dialog

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1040]
Most times i find this dialog looking really pretty - see 1 and 2 below. But occasionally i have a color that does not work at all ( see 3). So I have made up a few alternatives for consideration. My thoughts:
* The current release has gray icons except for the study pad icons (no 3). The problem is reduced if the icons retain their label color (see no 1)
* The problem is also reduced if we simply make the gray icons a darker gray (see no 8)
* I think my preference is still for colored icons (excluding the label icon). I think this gives a nice visual cue that these buttons are dealing with a specific bookmark.
* It would be good to keep icons the same color gray throughout the app

- [x] * So I am probably tending toward number 4 or number 6. But all of them are better than number 3 :)
- [x] Perhaps the Edit icon, which gets darker when it has a note attached, could be replaced with two different icons depending on its state. A couple of ideas are below number 1.

* Oh, I am assuming that the current background color is simply the color used as the highlight text in the bible documents. I think there should just be two colors - the label color and the highlight color.

Good work on this Tuomas. I didn't think you could get it to look exactly like i could make in a desktop publishing tool :)

![AndBible Suggestions-color options](https://user-images.githubusercontent.com/13920678/117540465-f76f3780-b052-11eb-961c-566c8d3b586b.png)

**Comment by tuomas2** [comment]
Is this happening still? I remember fixing it soon after this was done in the first place.

**Comment by agrogers** [comment]
Still looks like No.3 to me.

**Comment by agrogers** [comment]
The best example as to why this probably needs to be modified. The buttons on the gray background are completely invisible. 

![Screenshot_2021-06-12-19-35-12-050_net.bible.android.activity.jpg](https://user-images.githubusercontent.com/13920678/121778829-1a55b400-cbdc-11eb-810c-97277cb4a6be.jpg)

**Comment by tuomas2** [comment]
Hmm. Not sure how to fix this one. If background color can be almost anything, then there's not really any way to prevent that sometimes colors are "incompatible" (unless we use inverse colors or something similar). Perhaps there's some smart way to do this...

**Comment by tuomas2** [comment]
Oh now I see suggestions from pics. obsoleted my previous comment.

**Comment by agrogers** [comment]
Personally I quite like the way the background color is currently implemented but there have been more than a few times when the colors have clashed badly. So I think a change is warranted.

**Comment by tuomas2** [comment]
For edit icon, if you think it would be better than current darkening color, please send me SVGs :-)

**Comment by agrogers** [comment]
Well done on those changes Tuomas. I'm impressed how well you can turn a desktop publishing drawing into a living dialog :) I am still not 100% happy with the colors or icons or something. But I don't know if anything i can suggest now is better than your implementation. I might keep thinking/trying. I can make an SVG very easily if i come up with something. It would be good to hear what the other guys think. They have been very quiet about these changes - is it a good sign or not? I will give you a break on this one for a week or two ;-)

**Comment by bvahedy** [comment]
Andrew, for me usually being quite means I either agree or don't mind the
changes.

**Comment by agrogers** [comment]
I think this has been resolved now. Yes?

**Comment by tuomas2** [comment]
Yes I believe so
