### ISSUE TITLE
Issues with long labels and many labels in the pre-bookmark dialog

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1041]
* When the labels get long the new dialog gets a little confused. It's hard to see in the screenshot, but the white text in the label has wrapped around and is shown below the colored box. So '1. First' is there it has just been wrapped after the fullstop on to the next line.
* When there are many labels the line of labels gets very long and a scroll bar appears. This is not actually that bad. But it is probably better to get the labels to continue properly into a second or more lines.
* I think it would be fine to limit a label to a certain number of characters - say 25 - with an ellipsis if it gets longer than that.
* I would also stop the label from wrapping. I use the white-space property in CSS to do that usually: https://www.w3schools.com/cssref/pr_text_white-space.asp
* The study pad icons also start heading off the side of the dialog if there are too many of them. I would wrap them also.

![Screenshot_2021-05-08-11-42-18-196_net bible android activity](https://user-images.githubusercontent.com/13920678/117540894-a82a0680-b054-11eb-85de-dba0e70e9d57.jpg)

![image](https://user-images.githubusercontent.com/13920678/117541086-939a3e00-b055-11eb-8869-de4a2da8d33e.png)

**Comment by tuomas2** [comment]
Fixed in 522

**Comment by agrogers** [comment]
It looks like this one is done too. Only thing that might be good is to add the '...' to the label if it is being truncated.... which I think long labels are.... at least my long label was truncated.
