### ISSUE TITLE
It is possible to scroll a bookmark dialog off the screen which causes problems when clicking on a new bookmark

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1042]
The problem i experience is that it seems like the app has stopped responding. It is responding - it has just updated the bookmark off screen so i cant tell it did anything. 

Ben raised the same issue here: https://support.andbible.org/scp/tickets.php?id=498

I think there is another ticket with this problem as well. I can't find it unfortunately.

Tuomas knows about it and said that he would keep the dialog on screen when scrolling. I think that is a good solution.

**Comment by tuomas2** [comment]
build 521 did not fix this?

**Comment by bvahedy** [comment]
It only works for bookmarks that have three or four lakes. But if the
bookmark has lables overflowing off the screen it doesn't work. The
bookmark modal disappears off the page as you scroll up or down.

**Comment by bvahedy** [comment]
This is what it does:

https://user-images.githubusercontent.com/46405809/117554700-19929680-b00e-11eb-87ba-a8bb6caa6cea.mp4

**Comment by agrogers** [comment]
I believe this is fixed now.

**Comment by bvahedy** [comment]
Yes, I verified that this is fixed in build 522.2, I'll close this thicket.
