### ISSUE TITLE
Copy verses includes problematic footnotes (and perhaps verse numbers) plus multiple ways to execute a copy

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1044]
Description
There are two ways to copy text, once it is first selected. One way works as expected, the other has unnecessary inclusions.

See attached screenshot.

•  Result A is obtained by selecting text and then "Copy" from the pop-up menu. Notice the redundant inclusion of footnotes, and verse numbers without spaces, both of which add negative value to the process.

•  Result B is obtained by selecting text and then "Share/Copy.." from the pop-up menu. Notice the properly formatted verse numbers, and the absence of redundant footnotes which aren't even available in this extended process.

Solution
•  For the plain and simple "Copy" to yield usable results, please strip both verse numbers and footnotes. If the user wants verse numbers, they are in the "Copy/Share.." options. 

•  If footnotes are in fact deemed useful, then please provide a further switchable option for them under "Copy/Share.." But then they should be somehow distinguishable (superscripted?) from the actual text in the selection — probably easier just to leave them out entirely.

![Screenshot_20210424-105013_Clipper+](https://user-images.githubusercontent.com/13920678/117570911-b0934780-b10f-11eb-8cb3-f3a6a3720364.jpg)

**Comment by timbze** [comment]
@agrogers Thanks for creating this issue. It has been raised in support already as well: https://support.andbible.org/scp/tickets.php?id=482

Android does not have a nice way to remove the extra copy in the menu, but I have something in mind that might work in most cases. I will try it out when I get a chance.

**Comment by tuomas2** [comment]
Wont fix (though now "copy" is bit more difficult to use, under More -> ...)
