### ISSUE TITLE
Auto assigning of labels is at a window level not a workspace level 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1045]
This feels more like a bug than a feature. 
1. I set the labels that I wanted for new bookmarks in my main bible window (usually the top one). 
2. I then followed a link which opens a new bible window. 
3. I bookmarked in that window and got different labels automatically assigned

It seems to me that the automatically assigned bookmarks should be the same in all Windows in the workspace.

**Comment by tuomas2** [comment]
Fixed
