### ISSUE TITLE
Bug in displaying "open in my notes" dialog... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1046]
Create two or three bookmarks in any chapter. 
1) tap to open the first bookmark, a moda will appear.
2) tap on the "i" icon in the top right of the modal. This brings up a link to "open in my notes", tap on that link.
3) a split window appears and a list of all bookmarks for this chapter is listed. 

Expected behavior:
The list should only show the first bookmark not all bookmarks in the chapter.
If in step one above you tap on the last bookmark in the chapter. The list in step three will only display one item.

**Comment by tuomas2** [comment]
I think this works as expected. "My notes" window is supposed to show all bookmarks in the chapter, and the one user clicked to open in my notes window, should be scrolled to be first.
