### ISSUE TITLE
Double tap full screen 

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1047]
I find myself often enter fullscreen accidentally . some solution needed.

**Comment by bvahedy** [comment]
How about a triple tap to enter full screen?

**Comment by tuomas2** [comment]
I think we should have secondary way to enter and exit full screen (through menu etc) and way to disable double-tap via app preferences.

**Comment by agrogers** [comment]
I think it is always necessary to have hidden functionality also accessible via a menu option or button or something.

It would be great to have some tool tips or hints that show when a user use a slow way to do something.

For example, when a user uses the menu to go full screen the first time, show a tip explaining they can do this via double or triple click.

**Comment by tuomas2** [comment]
Implemented app pref to disable double-tap to fullscreen and added option in main window options menu
