### ISSUE TITLE
Speak aloud bookmarks ("my notes view")

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1048]
Could be possible that this verses can be read aloud
with speech system, just like any other bible verses.
 (in english, because slovenian is not yet supported)

https://support.andbible.org/scp/tickets.php?id=506

**Comment by agrogers** [comment]
Somewhat related is the ability to speak all the results of a search. That is mentioned in https://github.com/AndBible/and-bible/issues/611

**Comment by tuomas2** [comment]
Covered by #1355
