### ISSUE TITLE
Predownloaded Contents (bible)

### ISSUE THREAD

**Issue by jsonmat** [AndBible/and-bible#105]
At startup , the bible lists are downloaded. Is it possible to have 1 Bible predownloaded already when the app is installed?

**Comment by ildar** [comment]
Greetings!
Yes, but why?
If you got And Bible, you can get the text in the same way.
And if bundle text with the app then which one? E.g. would you agree a
German or Russian? Why not? 😉
Just my IMHO, Martin can have his own point of view, surely.

**Comment by ildar** [comment]
Emm, I don't quite understand but maybe
https://github.com/mjdenham/and-bible/wiki/FAQ will help: putting files in
jSword folder makes you pass the initial Bible download.

**Comment by tuomas2** [comment]
The current design choice is to allow user to select the translation(s) he desires to use, and I think this is OK. Closing this.
