### ISSUE TITLE
Speech toolbar is missing after sleep timer finishes with screen off

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1050]
When invoking sleep timer and letting the speak finish with the screen off.  Upon turning on the screen the speech tool bar is missing. 
![screenshot](https://user-images.githubusercontent.com/13920678/118219189-53efae00-b4bc-11eb-9f05-ce8a5f727423.png)

**Comment by tuomas2** [comment]
Looks like this is fixed.
