### ISSUE TITLE
Bookmark sub-window not displayed when trying to view a bookmark that also has a speak bookmark

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1053]
If there is a speak bookmark on a verse already and you try to select that verse in entirety and try to
bookmark it. The verse is highlighted with the default bookmark label color but tapping on the verse will never bring up the bookmark study window. Nothing happens when you tap on any part of the verse.
Expected behavior should be to bring up the sub-window for note  entry.

Report here: https://support.andbible.org/scp/tickets.php?id=481

**Comment by tuomas2** [comment]
I believe this is fixed now
