### ISSUE TITLE
Proposal: How to apply 'favourite labels' to bookmarks

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1059]
This issue is a response to Tuomas' video: https://www.youtube.com/watch?v=n7qaupKMOMc
The ticket https://github.com/AndBible/and-bible/issues/1035 is related to this. I have added additional info and a new screenshot to that issue that accommodates the favourite feature. Most of the comments there still apply. 

![AndBible Suggestions-label popup v2](https://user-images.githubusercontent.com/13920678/118349776-1b240780-b596-11eb-91e4-7adef350dc66.png)

Re Tuomas' video:
* I hadn't thought about favourite labels as separate to the 'auto-assign' labels. They are definitely different but there is some usage overlap i think
* My personal 'favourite' labels would probably end up being my most recently used labels.
* I think the feature has real merit.

Some general comments about labels and favourites:
* I think the labels that a user sees when opening a bookmark should *only* be the ones he or she assigned to the label.  So my sample no. 2 which shows the labels on the bookmark dialog violates that.

Comments about the screen samples above:
* Samples 3 and 4 move the labels off the main dialog which i think is good. But they now take several clicks to get to which may be something Tuomas is truing to avoid.
* Sample no.4 has a heart icon very prominent on the form. Assuming that labels are added or removed relatively infrequently, placing the icon here seems unnecessary. There are probably actions that are performed more regularly that might justify this position.
* The heart icon might be a little confusing on this form. It feels to me like this is a favourite *bookmark*, not a way to access a list of favourite labels. Maybe a different icon is helpful. Or maybe this is another reason not to include info on this dialog about labels that are *not* applied to the bookmark.
* Sample no.1 is my preference. It is accessed by clicking on a bookmark label at the top if the form. (There might be a case for it to also have a button in the main dialog as new users might not realise the labels at the top are also buttons)
* - presently this popup dialog usually just have two buttons - remove and assign labels. There is lots of space on it
* - That means we can add easy access to a lot of labels. 
* - It is only one click away from the main which i think is acceptable. 
* - It allows for many labels to be shown without messing with the main bookmark dialog
* - Only labels that are *not* already assigned to the bookmark should be shown. I don't see any point in showing labels that have already been assigned to the bookmark in this form. 
* - There is room for more label groups which i think i would use more often than the favourite labels. (see #1024 and #1035)

**Comment by tuomas2** [comment]
My usage for "favourite labels" was simple color labels, that I can use as a primary label, without other semantic meaning. (meaning, that if I have two consequent or overlapping 'devotion' bookmarks, I could mark other with other color, to distinquish them from each other)

**Comment by tuomas2** [comment]
> I think the labels that a user sees when opening a bookmark should only be the ones he or she assigned to the label. So my sample no. 2 which shows the labels on the bookmark dialog violates that.

I am not sure if I understand how it violates that. Do you mean that <3 line with bookmark info?

**Comment by tuomas2** [comment]
I like the clarity of the proposal and am planning to implement it. 
Added strings already so I don't need to hurry with this.

**Comment by tuomas2** [comment]
I believe I'd be going with proposal nro 1

**Comment by agrogers** [comment]
Wonderful. I was adding a lot of bookmarks last night and I think this would have saved me plenty of scrolling. And option one has room to grow if new features come along. I think there is a case for having this dialog popup immediately I create a new bookmark. At present I 1) create a bookmark 2) click on the bookmark 3) click on the label 4) scroll and choose the label and done. I would prefer to 1) Create a bookmark and immediately go to the dialog above 2) choose my labels and done. I might add an issue for that if you think it has merit.

**Comment by agrogers** [comment]
> > I think the labels that a user sees when opening a bookmark dialog should _only_ be the ones he or she assigned to the label. So my sample no. 2 which shows the favorite labels on the bookmark dialog violates that.
> 
> I am not sure if I understand how it violates that. Do you mean that <3 line with bookmark info?

The yet to be selected favorite labels (eg 'faith') are shown on the same form as the already selected labels (eg 'love')

**Comment by agrogers** [comment]
This one could be closed now. It is updated by #1104
