### ISSUE TITLE
Opening unlabelled bookmarks in study pad shows nothing in study pad window.

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1066]
Raised here: https://support.andbible.org/scp/tickets.php?id=484

![image](https://user-images.githubusercontent.com/13920678/118354502-b628db80-b5ae-11eb-9825-1b2c1f3d16c6.png)

**Comment by tuomas2** [comment]
Fixed (by removing "open in study pad" for unlabeleld)
