### ISSUE TITLE
The Android popup selection dialog covers the editor menu making it impossible to use

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1067]
![AndBible Suggestions-editor v2](https://user-images.githubusercontent.com/13920678/118361034-eb442680-b5cc-11eb-94fb-10bc75c44d74.png)

**Comment by bvahedy** [comment]
You should be able to tap and hold on the "selection dialog" and move it out of the way.
I don't believe this is a bug.

**Comment by tuomas2** [comment]
In some android devices it is possible, with some it is not. Confirmed it works on my tablet, but does not work on emulator (struggled with this when doing beta video)

**Comment by tuomas2** [comment]
I agree that selection popup is disturbing when trying to access buttons and something needs to be done. I believe @agrogers 's idea is worth trying, though I'm not sure if it will work out well or not (popup is not totally in our hands as it's Android's stuff).

**Comment by agrogers** [comment]
Oh, I never thought of long pressing the popup to drag it away. Just tried
it now and i could not move it.

I guess the ellipsis button doesn't need to open the android popup - it
could just open a custom menu. Although it is nice to keep as much familiar
to the user as possible.

**Comment by agrogers** [comment]
If this issue only affects a minority of users then i say leave it for later. Otherwise it feels bad enough to try to address. Unless my note is more than a few lines long then the cool edit tools are useless. (Of course not if i format before I type - there are cumbersome ways around it)

Include this feature in v3.4.

**Comment by tuomas2** [comment]
Implementation problem: we can't open selection context menu (copy etc) manually (tried this hard when trying to do #1079). It can come only as a consequence of selection text.

**Comment by tuomas2** [comment]
The thing is right now that I don't know what to do witht his. I would have fixed this months ago if it was easy to fix neatly.

**Comment by tuomas2** [comment]
Option to "hide" or "close" the context menu might work as a workaround/solution.

**Comment by agrogers** [comment]
It would. Good thinking

**Comment by tuomas2** [comment]
This is now fixed by moving toolbar to the bottom
