### ISSUE TITLE
Use the verse selector to enter a Bible reference

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1068]
At present the user has to type in a verse reference. I tried this (Jn 3:16) but it didn't recognise it as a legitimate verse. It turned it into a hyperlink but it didnt work correctly. Perhaps I typed it wrong or I misunderstand this feature. Anyhow,
1. Replace the dialog that is accessed via that button
2. With the standard verse selector dialog.
![AndBible Suggestions-editor verse selector](https://user-images.githubusercontent.com/13920678/118361195-8dfca500-b5cd-11eb-9c06-4cb3ccfdf7a6.png)

**Comment by timbze** [comment]
From what I understand this feature will improve in #981. It would then recognize a lot more different typings.

I think the current modal should stay, but it would be a good idea to add a button to it to be able to select the reference the way you mention

**Comment by agrogers** [comment]
Is there a reason why someone would want to type it over selecting it? To specify the translation?

**Comment by timbze** [comment]
For easier using in different ways. One time I want it to be John 6:61 and next time Jn 6:61.

Also probably faster in some cases

**Comment by tuomas2** [comment]
I think we could have button in input dialog to fill in text using bible ref selector. 

Why text? Text form is more flexible, it allows ranges etc.

**Comment by tuomas2** [comment]
We can see this after #981 is done

**Comment by agrogers** [comment]
Ah, yes, ranges get trickier. Adding a button to that little dialog that allows the user to either type into the box or fill the box by clicking the button which opens the verse selector would be the best of both worlds.

This would have the added advantage of telling the user the correct format for a Bible reference if they choose to use the button.

And if the button doesn't replace all text in the text input but appends or inserts at the cursor then you could use the selector to do ranges or adhoc
verses.

**Comment by JJK96** [comment]
I prefer text input, mainly because its faster for me

**Comment by tuomas2** [comment]
Maybe text input dialog could have also a button that open bible ref chooser and fill in text for the user, if he prefers to use it.

**Comment by agrogers** [comment]
Both options - text and selector - would be good. But

I suggest we delay this one to after v3.4 release
