### ISSUE TITLE
Enable Swiping up on a window button to maximise the window 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1070]
I am using the maximise window option a lot more now. It feels natural to just click and swipe up on the window button I want to maximise.

(the action I am trying to describe is the same action to bring down the workspace selector - click and swipe down in that case).

**Comment by agrogers** [comment]
Easy to implement i think but...

I suggest we delay this one to after v3.4 release

**Comment by agrogers** [comment]
Completed with https://github.com/AndBible/and-bible/pull/1888
I use this all the time now. I like it.

**Comment by tuomas2** [comment]
I also like it and have been using it.
