### ISSUE TITLE
In app help/tip/hint system 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1071]
I mentioned elsewhere that there are so many features in And Bible now that it is getting harder to know they are there and perhaps understand how they operate.

Maybe it's time to implement a tip or hint system (there isn't one is there?) that can fill in these gaps. A few thoughts
* show a single tip when the app is opened and don't make it too easy for the user to stop seeing tips. 
* the first tip explains where in the settings they can turn this off
* tips are shown during use when the user clicks on some button. For example, when they use the maximise button a tip pops up explaining they can also maximise by double clicking. I feel this is perhaps the most important aspect of the tip system. 
* The problem I find with tips is that I might read it when I first use the app but then 6 months later when I need that feature I have forgotten the tip. So showing the tip again when I use a slow way to do something is helpful. Have some way of dismissing permanently 
* Use the tips like the in app manual. So they can be launched from a menu option somewhere.
* add a help question mark button to dialogs that open the related tip
* enable links in tips so they can jump to other tips
* re enable tips when a new feature is added.
* tips should be able to display images 

I am happy to work on assembling a tip list if you want.

**Comment by tuomas2** [comment]
Anyone knows an easy-to-use framework how to include such tips into app? 
(perhaps we need even 2 frameworks: for js side, and for android native side)

**Comment by agrogers** [comment]
This is not what I had in mind but it is related and could be a nice intro. Apparently Google even use it

https://github.com/amlcurran/ShowcaseView

**Comment by agrogers** [comment]
And this as an intro but still not what I had in mind
https://developer.android.com/training/tv/playback/onboarding

**Comment by tuomas2** [comment]
Thanks, I'll try a little ShowcaseView. Then I'll let you know what I think. 

Minus side is that this might add considerable amount of translatable strings... and advanced users (like me) often hate them.

**Comment by timbze** [comment]
> and advanced users (like me) often hate them.

It might be good to have a checkbox in the new startup screen, where after a new install the user could uncheck if they don't want to see any first-time tips. If they leave it checked then they would see the tips.

**Comment by tuomas2** [comment]
> > and advanced users (like me) often hate them.
> 
> It might be good to have a checkbox in the new startup screen, where after a new install the user could uncheck if they don't want to see any first-time tips. If they leave it checked then they would see the tips.

But as @agrogers said, it should not be "too easy" to turn them off, as "grandmas" also might opt out, and then they do not know how to use AB. I would say it's better to have option to disable it on app preferences and tell user (with words) this in first tip.

**Comment by tuomas2** [comment]
though for grandmas it's often enough that they know how to read their favourite bible and that's all. For that they hopefully do not need any tips... (AB might not be the best choise for them in any case)

**Comment by Dleemuse** [comment]
Hey all,

I am 60 years old, & a grandma of 6... I use AB everyday, & can keep up with a lot of the features... I admit I am tech challenged, but some grandmas are not all that slow, I do way more in AB than you might think, Lol... Just had to tease you a bit. 

I do love the idea of it not being too easy to turn tips off.

Debra

**Comment by agrogers** [comment]
I think the 'ShowcaseView' could be a nice intro to the software. But i am not sure that it would be used more than that very first instance.

I have kept looking for a framework or library for a help system (or tips or hints or whatever - i have searched for all). But I cant find any. So I am starting to think my first idea which i haven't shared might be as good as any.

And Bible is already a very good hyperlinked document system. Why not just use the current functionality to make a 'help document' that does what we want? I have very limited experience in making OSIS documents (got a nice TSK like commentary made). But you will know if the following can be done:
* Popup the document in its only window ( it needs to sit above the And Bible docs)
* Nice formatting - headings, bolding etc
* Include images an animated gifs/pngs
* Allows hyperlinking to itself. Most docs target the link window I think.
* Be able to open to a specific topic
* Follow a link to a web page or youtube video
* Be able to write it in a nice format. Ideally we could have the master copy here https://readthedocs.org/ and then use that content to generate the document
* The book document seems to me to be able to do most of this already.
I hadn't looked at the book document types for a while - it looks great. It feels like it can do pretty much everything we would need in a help system.

**Comment by tuomas2** [comment]
> Hey all,
> 
> I am 60 years old, & a grandma of 6... I use AB everyday, & can keep up with a lot of the features... I admit I am tech challenged, but some grandmas are not all that slow, I do way more in AB than you might think, Lol... Just had to tease you a bit.
> 
> I do love the idea of it not being too easy to turn tips off.
> 
> Debra

Hehe, sorry... Those grandmas that I was talking about are not in Github reading/commenting on tickets :-D I think you definitely do not fall into the category I was talking about. Perhaps my use of word 'grandma' was a bit too generalizing =) 

My mom is more of the type I'm talking about. She's using speak aloud feature, and sometimes reads bible @ church with AB, but I doubt she knows what are workspaces, or does not care about bookmarks, and I believe she has never touched any settings (unless by accident). But fortunately, AB has not got too difficult for her to use so far anyway.

**Comment by tuomas2** [comment]
@agrogers Help doc would not be easy to translate, probably would serve english-speaking people only. And instead, it could be implemented as an online documentation @ wiki (Github or something else, if Github is not good enough). Also, updating screenshots/animated gifs would be painful, because UI is changing all the time (same issue as with promotional material, which I was thinking to tackle with #803).

**Comment by tuomas2** [comment]
Though if you would like to do that and take main responsibility of maintaining it, we can make a source repo in And Bible github org for it and include it in And Bible sword repo. 

Perhaps it's better than nothing anyway. But I'd like to have some translatable short feature descriptions in help screen as allways, so that users of any language can have at least that.

**Comment by agrogers** [comment]
Re timing of this feature, there are so many big changes to AB that it feels like this coming release is when such a feature is needed. But I understand that this is not a simple thing to do.

Maybe Include this feature in v3.4.

**Comment by tuomas2** [comment]
By this date we don't have a good plan to implement this, I think we should not delay the update too much. I think people (I think our target audience is rather smart anyway) can learn most of the features by trial and error and watching tutorial videos.

**Comment by agrogers** [comment]
Tim made me think that maybe an easy help system would be to 

- add a window - maybe maximum 10 lines high - at the top of all lists. 
- In this we show the explanation (scrollable if it is long) explaining how the list/dialog etc works. 
- The user can dismiss it somehow so it goes away forever (or until a new feature is added or something changes).
- Is it easy to add such a control to the top of these lists / dialogs?

![AndBible Suggestions-help at top of screen](https://user-images.githubusercontent.com/13920678/123430006-feee9e00-d60a-11eb-9b17-53e42719b34e.png)

**Comment by tuomas2** [comment]
What about making it same way as in workspaces view?
![Screenshot_20210626-111013_Bible Study](https://user-images.githubusercontent.com/5811789/123506893-3d1da900-d66f-11eb-9715-a266d8bf65e6.jpg)

**Comment by tuomas2** [comment]
Added string for assign label dialog help. Implementation can be desided later but I would go with (?) button and similar help dialog that we have been using earlier.

**Comment by tuomas2** [comment]
Did not push them yet to Transifex, so please review and suggest improvements if you think they are needed!  78b2b21

**Comment by tuomas2** [comment]
@agrogers could you think of a short help text for "All text settings" screens, both per-workspace and per-window, that would tell briefly how setting inheritance works? 

I.e. essentially what I tell here https://www.youtube.com/watch?v=rz0zyEK9qBk

That's something I'd like to have questionmark button because it's not completely obvious without instructions.

**Comment by agrogers** [comment]
Sure thing. Happy to help. Thanks for being specific - I was struggling a
little to know where to start.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by agrogers** [comment]
Hi Tuomas.

You can find a document here with my best effort for workspace settings. I
think i have found all of them and grouped them in a way that seems logical
to me.
https://docs.google.com/document/d/1KlhgSyLFjscep79emSN38XFrZknd3Ptrx6A1G4BaTL0/edit?usp=sharing

I have also had some more thoughts on how to do the window button menus. It
seems that my picture is pretty much impossible to make with
our multi-window format. I will do a mock up of what i have in mind
tomorrow night when i am back home.

Cheers
Andrew

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Hmm. I was thinking if you could help me to figure out short help text for the current "all text settings" menu entries, similar way as you wrote in the above for assign labels.

i.e. these: for workspace

![Screenshot_20210630-161047](https://user-images.githubusercontent.com/5811789/123966181-d45f6500-d9bd-11eb-933c-d8c604226b44.png)


for window
![Screenshot_20210630-161056](https://user-images.githubusercontent.com/5811789/123966202-db867300-d9bd-11eb-8736-8efd3006354f.png)

**Comment by tuomas2** [comment]
I'm going to freeze strings tomorrow, so I need help strings by tomorrow evening. I can write something myself too, but I'm thinking you might come up with better help texts.

**Comment by tuomas2** [comment]
Okay, here are my suggestions. How do these sound:

**Workspace text options**
These options determine the default settings for this workspace. They are in effect in all windows that do not specify overriding settings. If you are using multiple text windows, you can make overriding per-window adjustments from window menu button -> All Text Options. 

**Window text options**
These options determine the settings for this specific window. 
[grey sync icon] The value is not specified for the window, the default value comes from workspace text options that can be set up via [3 dot icon] menu -> All Text Options. 
[green unsync icon] The value is specified for the window and it overrides per-workspace default value.

**Comment by tuomas2** [comment]
Okay, here are my suggestions. How do these sound:

https://docs.google.com/document/d/1eSZct6Qe2ZFduU5T4p_N4UtMh6P-UJq6o3WKJexR228/edit

Please @AndBible/developers @agrogers comment / improve directly in docs.

**Comment by agrogers** [comment]
OK, i have made some suggestions. Maybe they are helpful.

Keep up the good work!

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
![image](https://user-images.githubusercontent.com/5811789/124098210-04ae0e80-da65-11eb-8828-4e3106b18585.png)


![image](https://user-images.githubusercontent.com/5811789/124098262-10013a00-da65-11eb-8a69-8c8c625a2cd0.png)

![image](https://user-images.githubusercontent.com/5811789/124098300-18f20b80-da65-11eb-84c5-9f89f7e6cc5b.png)

**Comment by tuomas2** [comment]
Thanks @agrogers !

**Comment by tuomas2** [comment]
Now help items are added to label selection related screens and text options screens.

**Comment by tuomas2** [comment]
Strings can still be changed UNTIL I freeeze them later today... (after that only via transifex (en_GB)

**Comment by tuomas2** [comment]
I think this is now more or less implemented as far as we want to do it now.
