### ISSUE TITLE
Missing verse in NET Bible shows [[EMPTY]] (John 5:4)

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1073]
**Describe the bug**
NET Bible John 5:4 shows only `[[EMPTY]]`. Maybe it's not a bug, I did confirm that NET Bible omits this verse, [see here](https://netbible.org/bible/John+5).

Not sure what is the best to display in this case, or if it's the SWORD module that has that text (EMPTY), for that verse.

**Bug was found on And Bible version**
Build 3.3.400 and also 3.4

**Expected result:**
Probably the verse should just be omitted? Or possibly show something like `Verse missing in this translation`

https://support.andbible.org/scp/tickets.php?id=522

**Comment by tuomas2** [comment]
must be module issue

**Comment by tuomas2** [comment]
(or jsword, though not likely)

**Comment by timbze** [comment]
> must be module issue

Do you know how jsword handles missing verse? I just thought it would need to be confirmed

**Comment by timbze** [comment]
Ok, I checked ESV and the verse is just omitted. So it is module issue then

**Comment by timbze** [comment]
Emailed eBible maintainer about the issue.
