### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1074]
Reported here: https://support.andbible.org/scp/tickets.php?id=516

Device info:
And Bible version: 3.3.400#6a52aa2ba (built 29/04/21 20:09:21)
Android version: 7.1.1
Android SDK version: 25
Manufacturer: samsung
Model: SAMSUNG-SM-T377A

--------- beginning of crash
05-15 16:55:57.783  7299  7299 E AndroidRuntime: FATAL EXCEPTION: main
05-15 16:55:57.783  7299  7299 E AndroidRuntime: Process: net.bible.android.activity, PID: 7299
05-15 16:55:57.783  7299  7299 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4, result=0, data=null} to activity {net.bible.android.activity/net.bible.android.view.activity.page.MainBibleActivity}: java.lang.NullPointerException
05-15 16:55:57.783  7299  7299 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4556)
05-15 16:55:57.783  7299  7299 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4599)
05-15 16:55:57.783  7299  7299 E AndroidRuntime: 	at android.app.ActivityThread.-wrap22(ActivityThread.java)
05-15 16:55:57.783  7299  7299 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1715)
05-15 16:55:57.783  7299  7299 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-15 16:55:57.783  7299  7299 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-15 16:55:57.783  7299  7299 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6823)
05-15 16:55:57.783  7299  7299 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-15 16:55:57.783  7299  7299 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1557)
05-15 16:55:57.783  7299  7299 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
05-15 16:55:57.783  7299  7299 E AndroidRuntime: Caused by: java.lang.NullPointerException
05-15 16:55:57.783  7299  7299 E AndroidRuntime: 	at net.bible.android.view.activity.page.MainBibleActivity.onActivityResult(MainBibleActivity.kt:1217)
05-15 16:55:57.783  7299  7299 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7322)
05-15 16:55:57.783  7299  7299 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4552)
05-15 16:55:57.783  7299  7299 E AndroidRuntime: 	... 9 more

**Comment by timbze** [comment]
The code that caused this has not changed yet in 3.4, so it could be happening in 3.4 as well... But there's only 6 instances of this crash in [Play store log](https://play.google.com/console/u/0/developers/6727655833913220393/app/4974350217168681006/vitals/crashes/0daf9722/details?days=30), and I can't figure out how to reproduce.
