### ISSUE TITLE
Add-ons in download documents show up for all languages 

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1075]
**Describe the bug**
By default the download documents show "all types". Some languages only have a few documents, and I have a feeling that users may be confused if the last 2 documents are FontPack and RefParser. 

I think we need to figure out a way to show the relevant Add-ons at the relevant places. For example, FontPack would probably be more helpful if in font selection screen there was a link/button for additional fonts. 

Same with RefParser, it would probably be more helpful to show that it may be needed when a Bible reference isn't recognized by the default parser. 

**Bug was found on And Bible version**
Build 523

**Comment by timbze** [comment]
I think the easiest solution would be to just not show add-ons in "All types"

**Comment by tuomas2** [comment]
I agree, have noticed that this is an issue.
