### ISSUE TITLE
Screen non responsive when trying to bookmark whole verse... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1081]
Build 523.1 beta:

I have two words in one verse bookmarked. (See screenshot)
When opening the first bookmark and tapping on the icon to highlight the whole verse everything works fine, however tapping on the second word while the bookmark modal is open and trying to do the same thing freezes the app. The only way to recover is to close the app and reopen it.

![SmartSelect_20210520-144552_Bible Study](https://user-images.githubusercontent.com/46405809/119053368-d247c680-b97a-11eb-91d0-0e1d61d72c3d.jpg)

**Comment by tuomas2** [comment]
Is it possible to make bug report from main menu when this happens? Tried to reproduce quickly did not succeed.

**Comment by bvahedy** [comment]
Ok, just reproduced it and reported the bug through the menu.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=526

**Comment by tuomas2** [comment]
Unfortunately I can't find anything useful from logcat. Need to think about how to get more info.

**Comment by bvahedy** [comment]
Ok, try to do this:
1) Create two bookmarks in a verse with just the words highlighted. 
2) assign multiple lables to the first bookmark.
3) assign only one lable to the second bookmark.
4) tap on the first bookmark to bring up the modal. Tap on the "i" icon to extend the modal.
5) tap on the icon to highlight the whole verse. Nice the modal so you could see the verse getting highlighted by the default label color. 
 now tap again to undo the whole verse highlight. 
(Note: everything works fine up to this point.)
6) with the modal still on the screen, tap on the second bookmark in the verse. 
7) tap on the "i" then tap on the icon to highlight the whole verse.  Do this couple of time to undo and redo the highlight verse.

At this point the app seems to highlight the verse with the default color of the first bookmark and the screen freezes to where you can not close the bookmark modal.

**Comment by RuggMatt** [comment]
I get a similar error if I try to interact with a speak bookmark. 

1. Enable speak bookmarks 
2. Create a speak bookmark 
3. Attempt to click on the speak bookmark in the window at the beginning of the verse, or try to highlight a portion of the verse with the speak bookmark. 
3. WebView freezes/accepts no further input

**Comment by tuomas2** [comment]
I found out that this simplified procedure reproduces (from @bvahedy 's version)

Do first setup steps 1-3.

Then to reproduce, this is enough:
1. Do step 4
2. Do step 6
3. Tap first bookmark again. (Notice error in js console at this point)
 -> any further action do not work (buttons, etc.)

**Comment by bvahedy** [comment]
Verified fixed in 524.1 build.
