### ISSUE TITLE
Multidocument bug, verse is not removed when opening other link

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1083]
https://support.andbible.org/scp/tickets.php?id=527

**Describe the bug**
Multi-document window is buggy with some references. See details below.

**Bug was found on And Bible version**
Build 523

**To Reproduce**
1. Open Gill commentary to Rev 3:11
2. Click "Open all references" at the bottom
3. Only Ps 87:3 opens
4. Click "Open all references" multiple times and it loads multiple times in the special window
5. Now click the link "Isa 60:1-22" in Gill commentary window.
6. It opens underneath the references to Ps 87:3 that are already open

![photo_2021-05-21_08-46-52](https://user-images.githubusercontent.com/35117769/119156558-927fee00-ba11-11eb-8732-dc08113cbb13.jpg)

**Comment by timbze** [comment]
It seems this issue always happens when one of the links is a full chapter. The OP issue is Isa 60:1-22, but that IS the full chapter.

Maybe when link is a full chapter or more, then show a link to load chapters instead of trying to load it all? Not sure what is the best thing to do.

**Comment by tuomas2** [comment]
Something is wrong, after clicking this link and scrolling up I get

![image](https://user-images.githubusercontent.com/5811789/120677636-f689c400-c49f-11eb-94d4-6dada9f09522.png)
