### ISSUE TITLE
Tapping on morph code does nothing... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1084]
Using the latest build 523:

When tapping on the morphalogy nothing happens. However if you tap and hold a window will display asking wether to open the link in a new window or current window. And if you choose one that will display the morph definitions.

Expected result:
When tapping on a morph link it should act the same as tapping on a strong's no. Which is to display the definition in a new window or the current window based on the settings in the app. preferences.

**Comment by tuomas2** [comment]
Can't reproduce.

Tried with KJV

![image](https://user-images.githubusercontent.com/5811789/120668501-313b2e80-c497-11eb-885d-cd2678c042dc.png)

**Comment by bvahedy** [comment]
It used to work with HiSB in prior builds, nothing has changed with hisb, but could it have something to do with introduction of choosing what morphology to use in the app settings.

**Comment by bvahedy** [comment]
Thank you for fixing this. Verified fixed in beta build 531.9.
