### ISSUE TITLE
Enlarge the popup window editing space

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1087]
- Same idea as #1086 but on the popup window
- Remove the red space
- Possibly remove some orange space
- Widen the window so it is about the size of the green box - maybe 7 pixels shy of the edges
![AndBible Suggestions enlarge popup editing space](https://user-images.githubusercontent.com/13920678/119214418-14ebd900-bb0a-11eb-9fa5-037acd2a31be.png)

**Comment by tuomas2** [comment]
I'm not yet sure what I think about widening modals to much, but I'll give it a try.

**Comment by agrogers** [comment]
I like the what you have done. I would be happy with it even wider 😏

**Comment by tuomas2** [comment]
Current version has the fix reverted (partially). if you want to try how the original wide version feels, install this one: https://github.com/AndBible/and-bible/releases/tag/beta-525
