### ISSUE TITLE
Grow the popup edit window more as the user types

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1088]
- The window currently grows as the user types
- But it stops growing after 4 lines (on my device)
- There is still a lot of screen space for it grow considerably more
- I would probably grow it until it takes up the most of the window - no point making the user scroll if they don't need to.

![AndBible Suggestions-growing popup edit window](https://user-images.githubusercontent.com/13920678/119214560-1ec20c00-bb0b-11eb-9235-fb14c63b1291.png)

**Comment by tuomas2** [comment]
Fixed in b8ecad463bf0ea269dae048b9eb5f6bc0e15cb04
