### ISSUE TITLE
Buttons should have a minimum width and consistent border style

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1089]
- A pet peeve of mine is different sized buttons :)
- I feel all buttons should have a minimum size - say large enough to accommodate the common labels (like 'Cancel')
- So the dialog below would have two equal sized buttons
- Also, I think the border probably should not be a different color to the button face - in this case it should be the same color (or no color). Most of the And Bible buttons do not have a border.
![AndBible Suggestions button size](https://user-images.githubusercontent.com/13920678/119214703-0ef6f780-bb0c-11eb-98ab-9a37b6ee89db.png)

**Comment by tuomas2** [comment]
Fixed
