### ISSUE TITLE
Unable to change the color of a lable... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1090]
Running build 523.2:

Under manage lables when tapping on a lable it presents you with an empty title also changing the color and tapping ok will not save any changes you made.

**Comment by tuomas2** [comment]
Oh, I think I forgot to implement that then...

It's easy to go back to build 523.1 (as version integer is same) if 523.2 is unstable.

**Comment by tuomas2** [comment]
Fixed
