### ISSUE TITLE
Re-opening app goes to default verse instead of the last verse I was on

### ISSUE THREAD

**Issue by RuggMatt** [AndBible/and-bible#1094]
1. Open app 
2. Go to a specific verse
3. Close/exit app
4. Reopen And Bible

Expected: 
And Bible opens to last verse I was on 

Actual:
And Bible defaults to John 3.16 

Device info:
And Bible version: 3.4.523-beta#3386d58 (built 22/05/21 15:55:04)
Android version: 11
Android SDK version: 30
Manufacturer: Google
Model: Pixel 4 XL
Storage Mb free: 8233
WebView version: 91.0.4472.16
SQLITE version: 3.32.2
Used heap memory in Mb: 10
Max heap memory in Mb: 256

**Comment by timbze** [comment]
This user had the same issue: https://support.andbible.org/scp/tickets.php?id=512

**Comment by tuomas2** [comment]
Should check logcat for this, or perhaps @mattschlosser  could try to debug this with his device where issue reproduces easily.

**Comment by RuggMatt** [comment]
Seems to only happen if I have one bible installed. 

Added a logcat to the ticket above.
