### ISSUE TITLE
Creating a single bookmark actually created two bookmarks

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1098]
Applies to v3.4.524 (27/5/21)

![image](https://user-images.githubusercontent.com/13920678/120054068-191b7780-c071-11eb-8164-b5f9a9ed2652.png)

I deleted one and it deleted both. I tried again and got the same result. I added a note and it displayed like this:
![image](https://user-images.githubusercontent.com/13920678/120054106-5122ba80-c071-11eb-9cef-030e124b6016.png)

It's a one off issue so far.

**Comment by tuomas2** [comment]
Have you seen this issue?

**Comment by agrogers** [comment]
I haven't seen this issue again.

**Comment by agrogers** [comment]
I haven't seen this again so I will close it.
