### ISSUE TITLE
Sometimes very slow response when adding labels

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1099]
After using AndBible for a bit I found I was getting verrrryyyy slow response. It could take 20 seconds or more for a label that I had clicked on to show as selected. This initially meant that I thought I had miss-clicked so I clicked again, and again. These clicks all queued and so it made the problem even worse.

This video shows what I mean: https://photos.app.goo.gl/5wN8rRRw6LgnDfMD6
The audio is really low when i use screen recorder - but I dont say anything helpful. You can see the clicks on screen and you can see how long it takes for that click to be applied.

A possible half-solution in #1100

**Comment by tuomas2** [comment]
Does this happen always (even after restarting app) when there are a lot of bookmarks open in the view, or does it happen after long use of And Bible only?

**Comment by agrogers** [comment]
- Restarting AndBible restores the speed back to normal. 
- It is not consistent so its hard to say under what conditions it happens.
- But it feels that the longer i use it the slower it becomes. This is not new with the latest few releases. This has been the case for weeks.
- However it had never been as bad as it was today where there was 20 second or more delays before the screen refreshed. I need to use it more to give you some better feedback.

**Comment by tuomas2** [comment]
When this slowness takes place next time (in a clear enough way), please report bug via main menu -> report bug so we get logcat. It might reveal something.

**Comment by agrogers** [comment]
I have been using andBible for an hour or two and have added maybe 10 bookmarks. Now when selecting a label from the Favourites list I have to wait about 20 seconds for the screen to update.  (https://support.andbible.org/scp/tickets.php?id=538)
[logcat (2).txt.gz](https://github.com/AndBible/and-bible/files/6573060/logcat.2.txt.gz)

**Comment by agrogers** [comment]
I just restarted And Bible and the label adding is almost instant.

**Comment by agrogers** [comment]
Adding label from full list took over 30 seconds (https://support.andbible.org/scp/tickets.php?id=542)
[logcat (3).txt.gz](https://github.com/AndBible/and-bible/files/6573063/logcat.3.txt.gz)

**Comment by agrogers** [comment]
After sending bug report, adding a label from the full list was fast. Weird. (https://support.andbible.org/scp/tickets.php?id=543)
[logcat (4).txt.gz](https://github.com/AndBible/and-bible/files/6573066/logcat.4.txt.gz)

**Comment by agrogers** [comment]
Performance has been much better for me on the 3.4.526 beta. I haven't used it as much so not a perfect test. But so far so good.

**Comment by tuomas2** [comment]
This is was easy to reproduce by adding and removing same label many times in Bookmark labels modal. Just tap same label for maybe 10-50 times and slowness appears.
