### ISSUE TITLE
Should the 'Set bookmark labels' dialog change the bookmarks only when it is closed?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1100]
I raised this slowness issue here #1099 

But I wonder whether it would be better to *not* apply any changes to the bookmark until the dialog is changed. I can currently see the verse color changing in the background as I add or remove labels. But this is really unnecessary - I don't need to see the actual verse change its highlight until the dialog is closed.  This would eliminate the slowness issue in this form I think (but not solve the bug that is causing the slowness of course)

I think it's really important that when labels are clicked on there is an immediate response of some sort - this feels like the most logical way to do that.

**Comment by tuomas2** [comment]
It is not root cause for slowness as restarting / refreshing app helps. I like to keep it reactive for now.
