### ISSUE TITLE
Weird screen redraw when it looses track of how big the document window is

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1101]
- Some examples are shown below. 
- Restarting the app solves the problem. 
- Using the latest beta.
- You can see the large white spaces where the window does not resize when windows are minimised or resized manually.
- Going fullscreen doesnt help
- Maximising doesnt help

![image](https://user-images.githubusercontent.com/13920678/120054516-b677ab00-c073-11eb-9f2f-8b5092696dfe.png)
![image](https://user-images.githubusercontent.com/13920678/120054523-bbd4f580-c073-11eb-962e-a9445eb0ebc7.png)
![image](https://user-images.githubusercontent.com/13920678/120054528-c0011300-c073-11eb-9924-8e9060e36665.png)
![image](https://user-images.githubusercontent.com/13920678/120054532-c42d3080-c073-11eb-8768-b2a91b3c5db7.png)

**Comment by agrogers** [comment]
I just got the incorrectly sized windows (whitespace at the bottom). It happened when I hid one window and then showed another quite quickly. After it happened the scroll response was quite bad.  (https://support.andbible.org/scp/tickets.php?id=540)
[logcat (5).txt.gz](https://github.com/AndBible/and-bible/files/6573070/logcat.5.txt.gz)

**Comment by agrogers** [comment]
Amazingly after submitting a bug report the windows have completely restored themselves - no white space - and scroll response is normal.  This also happened with the slow label adding https://github.com/AndBible/and-bible/issues/1099#issuecomment-851769882
(https://support.andbible.org/scp/tickets.php?id=539)
[logcat (6).txt.gz](https://github.com/AndBible/and-bible/files/6573072/logcat.6.txt.gz)

**Comment by tuomas2** [comment]
Something like this happened in the past for with some unconventional css / module. Do you remember @bvahedy ? That issue would be nice to be linked here. I think I figured out that time that the root cause was in WebView, but it was triggered by some weird html etc.

**Comment by tuomas2** [comment]
I was experiencing a lot of this with WebView version 74 (from API 29 emulator).

![image](https://user-images.githubusercontent.com/5811789/122451280-9ff8ab80-cfb0-11eb-8ee6-e50194fe21ef.png)

**Comment by bvahedy** [comment]
Yes, I remember, but don't know what you did to fix it. I haven't
experienced this issue recently.

**Comment by tuomas2** [comment]
@agrogers has this happened since then? I haven't got this at all on my devices.

**Comment by agrogers** [comment]
I haven't seen this for ages. Let's assume it is fixed. Good job!
