### ISSUE TITLE
Is the reason to limit the 'set bookmark labels' dialog to the size of the active window?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1102]
You can see some examples below where I can't see parts of the dialog without scrolling. However there is plenty of space on the screen - it is just being used to display another window(s).

Is there a technical reason you are keeping the dialog inside the active window? If not, I think making that dialog appear in the center of the entire device screen (on phones at least) would be positive. You could still darken that background of the active window. But i am not sure if that is needed or whether all windows should be darkened, or none. 

How it should work on tablets I am not  so sure.  Popping up the dialog so it tries to position itself immediately below (or as close to) the verse being bookmarked seems logical. 

![image](https://user-images.githubusercontent.com/13920678/120054590-24bc6d80-c074-11eb-9524-a64799297371.png)
![image](https://user-images.githubusercontent.com/13920678/120054596-300f9900-c074-11eb-8856-fbf9f8f04a4a.png)

**Comment by tuomas2** [comment]
Modals are implemented in javascript / webview. That's a little uggliness of this implementation. Some dialogs could be implemented as native android dialogs, but js development is often much easier and faster  than native android.
