### ISSUE TITLE
If chapter contains speak bookmark, attempting to open "My Notes"  causes Bible View UI to freeze until restart

### ISSUE THREAD

**Issue by RuggMatt** [AndBible/and-bible#1103]
1. Turn on speak bookmarking in speech settings
2. Create a speak bookmark by starting and then stopping the speech
3. Try to open My Notes document for the same chapter

Expected: My notes loads as expected. (**Note:** I don't think speech bookmarks should show here, just the regular bookmarks.)

Actual: Entire UI freezes. My notes does not load. Trying to switch to any other document does not work, and will remain on the last document before trying to open "My Notes".  

And Bible version: 3.4.524-beta#6cdf533 (built 28/05/21 16:16:19)
Android version: 11
Android SDK version: 30
Manufacturer: Google
Model: Pixel 4 XL
Storage Mb free: 7298
WebView version: 91.0.4472.16
SQLITE version: 3.32.2
Used heap memory in Mb: 50
Max heap memory in Mb: 256

**Comment by RuggMatt** [comment]
Also happens if you load a **My Notes** chapter that does not contain a speak bookmark and then  swipe to a chapter that does.

**Comment by RuggMatt** [comment]
Similar to #1053

**Comment by tuomas2** [comment]
It looks like this does not happen any more (I believe fixing #1121 closed this too)
