### ISSUE TITLE
When adding a new bookmark either the auto-assigned labels are added or the 'Bookmark labels' dialog is shown

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1105]
I can see where being able to auto-assign labels would be good - say when recording sermon notes or focusing on a particular topic. But my workflow has rarely been like that.

I always add a bookmark, then click it, then click the label, and now select the label from the new label dialog (or create a new label). I never leave a bookmark label set to 'Unlabelled'.

**What I think should happen is:**
1. If there are labels set to automatically assign to new bookmarks, those labels should be assigned and nothing else is done
2. If there are *no* labels set to automatically be assigned, then the 'Unlabelled' label is assigned and the new Bookmark Labels dialog should be displayed (see below). The user can then choose the label from the quick lists or open the full list to create a new one.

![image](https://user-images.githubusercontent.com/13920678/122638661-bfbadb80-d138-11eb-93b3-fb75d877da55.png)

**Comment by agrogers** [comment]
Hi @tuomas2 . This is probably the last thing left on my personal list of features to make the assigning of labels pretty much perfect. Did you see this one?

**Comment by tuomas2** [comment]
I can implement, but not in prio list

**Comment by agrogers** [comment]
The way this issue streamlines the bookmarking process (see #1172) makes me think we should...
Include this feature in v3.4.

**Comment by tuomas2** [comment]
Added to prio list. But does not need strings so not 'that urgent'

**Comment by tuomas2** [comment]
(those commits should have gone towards #1249 actually)

**Comment by tuomas2** [comment]
Should it be "Bookmark modal" + "Bookmark labels" both opened automatically, so that when you end, you need to close both of them? Or just "Bookmark labels", such that you need to re-open bookmark if you want to have it opened?

**Comment by agrogers** [comment]
Yay! This change will make me smile for weeks. 

Only show the one dialog - Bookmark Labels - I think.  Reopening would be needed to add a note (occasionally needed by me) or check the Info (never needed by me).

If #1169 gets implemented then the Note icon will get you back there. Possibly should also include an Info icon on that form which would do exactly what you asked about. 
![image](https://user-images.githubusercontent.com/13920678/124894189-c6918b80-e01e-11eb-8bbb-01d1b41dcb76.png)

**Comment by tuomas2** [comment]
I decided to go with my 1st option, for simplicity and perhaps bit more logical perhaps to me.

**Comment by agrogers** [comment]
OK, I look forward to trying it out.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
