### ISSUE TITLE
Enhancement to Assign Labels list and dialog

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1106]
Thanks again for the updates and improvements. There is ample space now to show my longer labels which is good.
![AndBible Suggestions label list and dialog](https://user-images.githubusercontent.com/13920678/120061103-e4beb000-c09e-11eb-88b6-287ca4b7b960.png)

A few suggestions below:
For the list...
1. The list text is not quite centered vertically. It is a little high so it doesn't align with the checkbox.
2. Change the Star icon to the bookmark icon which we use elsewhere to indicate a primary label.
3. Still hoping for the grouping of the list as described in #1024 

For the dialog...
1. The colored icon next to the label name is the auto-assign icon. It should be a normal label icon i think.
2. I like the new color picker. I think it is better suited to this app. Perhaps the color picker could be shown on this dialog as in No.3.  But i am ok with accessing it from a button as it is currently.
3. Add a check box to indicate if the label is currently selected for this bookmark. This would also allow the user to select or unselect of course.
4. Reduce the size of the label icons so they are less dominate. They should be about the height of the text.
5. Change the Star icon to the standard Bookmark icon that we use elsewhere to indicate a primary label.
6. Indent the Auto assign as primary label so it is clearer how it relates to the label above.
7. The label text is not center aligned vertically with the checkbox. It looks to be bottom aligned or even beyond the bottom.
8. The trash can icon for delete is very small. Perhaps it should just be the word 'Delete' or if possible make it larger. We need to determine a standard for all our dialogs - word or icon.

**Comment by tuomas2** [comment]
> A few suggestions below:
> For the list...
> 

- [x] > The list text is not quite centered vertically. It is a little high so it doesn't align with the checkbox.

Tried to fix this but it looks like it does not quite like to go to center. 

- [x] > Change the Star icon to the bookmark icon which we use elsewhere to indicate a primary label.

> Still hoping for the grouping of the list as described in #1024

Still TODO

> For the dialog...
> 

- [x] The colored icon next to the label name is the auto-assign icon. It should be a normal label icon i think.

> I like the new color picker. I think it is better suited to this app. Perhaps the color picker could be shown on this dialog as in No.3. But i am ok with accessing it from a button as it is currently.

It's easier to implement like this as it is designed to be used like this. 

- [x] > Add a check box to indicate if the label is currently selected for this bookmark. This would also allow the user to select or unselect of course.

- [x] > Reduce the size of the label icons so they are less dominate. They should be about the height of the text.

- [x] > Change the Star icon to the standard Bookmark icon that we use elsewhere to indicate a primary label.

- [x] > Indent the Auto assign as primary label so it is clearer how it relates to the label above.

- [ ] > The label text is not center aligned vertically with the checkbox. It looks to be bottom aligned or even beyond the bottom.

- [x] > The trash can icon for delete is very small. Perhaps it should just be the word 'Delete' or if possible make it larger. We need to determine a standard for all our dialogs - word or icon.

Changing it to "Delete" as it is what we have done elsewhere I think.
