### ISSUE TITLE
AndBible becomes unresponsive when bookmark with hidden workspace labels

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1109]
Reported here: https://support.andbible.org/scp/tickets.php?id=535

1. Highlight and bookmark verse
2. Create/Assign label to verse
3. Hide label for that workspace
4. Attempt to highlight the same verse again (I selected "bookmark verse" option in both cases). 

Expected: modal is interactive/ responsive

Actual: modal/WebView freezes and becomes unresponsive when clicking the info button on the bookmark modal.

**Comment by tuomas2** [comment]
Can't reproduce this.
@mattschlosser  is this easily reproducible for you?

**Comment by RuggMatt** [comment]
> Can't reproduce this.
> @mattschlosser  is this easily reproducible for you?

Can't reproduce this anymore in latest beta build.
