### ISSUE TITLE
White window bug

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1110]
Reported here https://support.andbible.org/scp/tickets.php?id=530

White window.

What I did:
- Opened AB
- Switched to another worskpace
- Switched to another window within workspace
-> white window

--- KIRJOITA PALAUTE TAI BUGIRAPORTTI TÄMÄN RIVIN YLÄPUOLELLE ---

Ohjeet:
Kerro lyhyesti mitä teit / mitä tapahtui kun ongelma ilmeni.

Esimerkiksi:
  1. Avasin sovelluksen
  2. Napsautin ikkunavalikkoa
  -> sovellus kaatui
 
Käytä tätä toimintoa raportoidaksesi heti kun olet havainnut ongelman ilmenevän. Voit myös käyttää tätä toimintoa sovelluksen uudelleenkäynnistämisen jälkeen, jos sovellus on kaatunut.

Liitteet:
  - logcat.txt.gz: Sovelluksen tuottama lokitiedosto. Se ei sisällä tietoa mistään muusta ohjelmasta.
  - screenshot.webp: Kuvankaappaus sovelluksesta silloin kun sovellus kaatui, tai silloin kun bugiraportti luotiin.

Näiden liitteiden lähettäminen auttaa kehittäjää paljon raportoidun bugin korjaamisessa. Joskus käsin otetut näytönkaappaukset ovat hyödyllisiä ongelman selvittämisessä.

Laitteen tiedot:
And Bible version: 3.4.523-beta#b15e3b8 (built 20/05/21 17:04:38)
Android version: 10
Android SDK version: 29
Manufacturer: samsung
Model: SM-P205
Storage Mb free: 8431
WebView version: 90.0.4430.210
SQLITE version: 3.22.0
Used heap memory in Mb: 17
Max heap memory in Mb: 192

**Comment by bvahedy** [comment]
This bug doesn't seems to be happening any more, I'm running 524.3 build. But I also did a complete fresh install.  Can someone else try to see if this is still an issue?

**Comment by tuomas2** [comment]
it is not easily reproducible. ill check logcat

**Comment by tuomas2** [comment]
but it is not fixed

**Comment by tuomas2** [comment]
Couldn't reproduce still but found something that could cause it in some weird condition.

**Comment by tuomas2** [comment]
Closing until it raises its head again

**Comment by tuomas2** [comment]
Fix caused this: https://support.andbible.org/scp/tickets.php?id=552

**Comment by tuomas2** [comment]
Similar from @bvahedy https://support.andbible.org/scp/tickets.php?id=558

**Comment by bvahedy** [comment]
Try this steps to reproduce:
make sure you have at least more than two synch windows, but only one is displayed and the rest are minimized.

1) tap and hold on the speak icon on the top menu.

2) check the sleep timer and select 1 minute.

3) tap on the play icon.

4) stop the speak by tapping the stop button. If the speak toolbar is missing, (that's another fix that needs to happen), double tap to enter the full screen and again to get out of the full screen mode, this will cause the speak took bar to appear again. Stop speak.

5) try to tap on a window icon and open another synch window. The icon darkens but  window doesn't open.

**Comment by tuomas2** [comment]
Still happens with the latest build (https://github.com/AndBible/and-bible/releases/tag/beta-525.4)?

**Comment by bvahedy** [comment]
Yes, still happens with the latest build.

**Comment by tuomas2** [comment]
Reproduced

**Comment by tuomas2** [comment]
Step 2 is not needed

**Comment by bvahedy** [comment]
Verified fixed in beta build 527.
