### ISSUE TITLE
Bookmark labels showing up for verse(s) that were NOT assigned to the verse(s) 

### ISSUE THREAD

**Issue by Dleemuse** [AndBible/and-bible#1113]
Sorry, I didn't get a screen shot. 

For exame, four labels appeared when clicking on selected verses that have been only been bookmarked with 2 different labels. 

Thanks,

Debra

**Comment by Dleemuse** [comment]
The only fix I could find for this problem was completely deleting the 2 labels that were not assigned to the verse(s).

This problem happened a couple of times on different bookmarked verse(s).

**Comment by tuomas2** [comment]
Next time this happens, please do main menu > bug report, so we get screenshot and logcat

**Comment by Dleemuse** [comment]
I will use main menu bug fix next time.

**Comment by agrogers** [comment]
Bookmarking has been very reliable for me in recent releases.

I suggest we delay this one to after v3.4 release

**Comment by tuomas2** [comment]
If this reproducese, please re-open
