### ISSUE TITLE
Screen Freezing 

### ISSUE THREAD

**Issue by Dleemuse** [AndBible/and-bible#1114]
When trying to highlight verse(s), screen freezes (and AB crashed once), no highlight appears. Hitting back button & coming back to desired verse fixed the problem several times, except when AB crashed.

Thanks,

Debra

**Comment by tuomas2** [comment]
When freezing happens, it would be helpful if you used main menu -> repprt a bug feature, so we can get logcat to be inspected.

**Comment by tuomas2** [comment]
Probably duplicate of #1099

**Comment by Dleemuse** [comment]
This is possibly related to #1099.

Debra

**Comment by tuomas2** [comment]
Closing as duplicate of #1099
