### ISSUE TITLE
Bookmark labels not in alphabetical order

### ISSUE THREAD

**Issue by Dleemuse** [AndBible/and-bible#1115]
I thought maybe it did not like lowercase 's' in satan, so I edited it with a uppercase 'S,' but it didn't make the edit, nor did it move the label into alphabetical order. 

![Screenshot_20210529-183607_Bible Study](https://user-images.githubusercontent.com/83124765/120087765-5521fd00-c0b0-11eb-877d-52be6ad789de.jpg)

Thanks,

Debra

**Comment by Dleemuse** [comment]
Tuomas, I received your email saying #1115 is closed. Does that mean it has been fixed? My bookmark labels are still not in alphabetical order 
Thanks, 
Debra

Sent from Yahoo Mail on Android 
 
  On Thu, Jun 3, 2021 at 7:51 AM, Tuomas ***@***.***> wrote:   


Closed #1115 via 7322a4f.

**Comment by tuomas2** [comment]
It's fixed in develop branch. It will be included in next beta build.
