### ISSUE TITLE
Commentary jumps to top after clicking link and adding bookmark

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1119]
https://support.andbible.org/scp/tickets.php?id=545

**Describe the bug**
Commentary jumps to top after clicking link and adding bookmark.
It can be reproduced with any commentary. 

1. Select a label to auto assign and make it primary auto assign label. 
2. Scroll down in commentary and click a Bible reference link so that special window opens
3. Add a bookmark in special window that just opened 
4. Commentary window jumps to the top

**Bug was found on And Bible version**
Build 524

**Device info:**
And Bible version: 3.4.524-beta#1e2c95004 (built 29/05/21 08:40:27)
Android version: 11
Android SDK version: 30
Manufacturer: Google
Model: Pixel 3
Storage Mb free: 24770
WebView version: 90.0.4430.210
SQLITE version: 3.28.0
Used heap memory in Mb: 28
Max heap memory in Mb: 192

**Comment by tuomas2** [comment]
Also studypad jumps
