### ISSUE TITLE
Modal close button overlaps with window button

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1120]
@agrogers 

![image](https://user-images.githubusercontent.com/5811789/120661905-5af15700-c491-11eb-9093-b4422cda76d6.png)

I fixed this by lowering the modal a little. Better ideas?

![image](https://user-images.githubusercontent.com/5811789/120662013-75c3cb80-c491-11eb-8520-99e5899c082d.png)

**Comment by agrogers** [comment]
I had noticed this too. My first thought was to change the z-index of the
modal window so that it appears above the window buttons.

**Comment by tuomas2** [comment]
> I had noticed this too. My first thought was to change the z-index of the
> modal window so that it appears above the window buttons.

Window buttons are on android side, modal js-side inside webview, so not possible...
