### ISSUE TITLE
Label picker causes freeze

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1121]
Not sure if I reported this but the label picker doesn't work. It has been happening for a while.  Haven't heard of anyone else having this issue though. Not sure why it is only me.

1. Open And Bible
2. Highlight and bookmark verse
3. Click on "Unlabelled" label to pick labels

Expected: label picker opens

Actual: Bible WebView UI freezes

Reported here: https://support.andbible.org/scp/tickets.php?id=551

**Comment by tuomas2** [comment]
@mattschlosser unfortunately logcat does not reveal anything interesting here. 
Can you reproduce this easily? 
Could you try to do some js debugging to see if you can find anything useful debug info?
Maybe also enabling app preferences -> show javascript error box and making bug report again from main menu -> bug report might give more info.

**Comment by RuggMatt** [comment]
I can reproduce this one everytime. Remote debugging also doesn't provide any useful info.

**Comment by RuggMatt** [comment]
More specific reproduction steps:
- create some bookmarks/labels, etc. to backup
- back up And Bible module
- back up And Bible database
- clear data for app
- restore And Bible module from start screen
- restore And bible database with bookmarks/labels from menu
- click on any label in the bookmark modal

Expected: label picker opens
Actual: WebView UI freezes

Oddly, if i first restore the database (from start screen on fresh install), and then import the modules, I do not have any issues.

**Comment by tuomas2** [comment]
I fixed one other freezing issue reported by @agrogers an dI'm thinking it might be same root cause as this. Can you tell if this reproduces with the latest build (just released)?

**Comment by RuggMatt** [comment]
@tuomas2 I cannot reproduce this anymore in the latest build.

**Comment by tuomas2** [comment]
it was issue with very specific label color
