### ISSUE TITLE
genbook formatting is not handled

### ISSUE THREAD

**Issue by uniqueid001** [AndBible/and-bible#1123]
**Describe the bug**
The formatting of the content of a genbook is absent when viewed in AndBible:  headings, line breaks, unordered lists, hyperlinks (and possibly more).

**Bug was found on And Bible version**
Version 3.3

**To Reproduce**
1. Download BaptistConfession1689
2. Open it

**Expected behavior**
The formatting of the text to be preserved and presented.

**Smartphone (please complete the following information):**
 - Device: Moto G5 Plus, Moto G Power
 - OS: Android
 - Version 8.1, 10

**Screenshots**
Here are two screenshots comparing the same module in AndBible and Xiphos.  Xiphos displays the text with formatting, and is far more readable/legible.
![AndBible - Comparison 1](https://user-images.githubusercontent.com/12715614/120735933-6b1d2c80-c4b9-11eb-9d18-b851c79665ac.png)
![Xiphos - Comparison 1](https://user-images.githubusercontent.com/12715614/120735940-6eb0b380-c4b9-11eb-9420-ee7965e96002.png)
![AndBible - Comparison 2](https://user-images.githubusercontent.com/12715614/120735948-71aba400-c4b9-11eb-84da-0cc7ec9f0038.png)
![Xiphos - Comparison 2](https://user-images.githubusercontent.com/12715614/120735960-740dfe00-c4b9-11eb-88c1-9df91675dea8.png)

**Comment by timbze** [comment]
See #689.

I think it's true that we need to implement more genbook features, but I think LBC 1689 is mostly module issue. See chapter 2 and 3, they seemingly don't have the issue that "Content", "Foreword", and chapter 1 have. 

It's true that xiphos handles this better, but I don't think it makes sense for us to hack bad xml to show it correctly.

It seems that crosswire may have lost the source of the osis text for the LBC 1689 module, so perhaps someone will have to start over with it again.

I made the LBC 1646 to spec last year. If someone wants to use that as an example to start over with the 1689 that would certainly be possible. The source for it is here: https://github.com/timbze/first-london-baptist-confession-1646

**Comment by tuomas2** [comment]
As @timbze mentioned, this is issue in module. Module needs to be updated.
