### ISSUE TITLE
When creating a new lable the name is blanked out... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1125]
Running latest beta build 525.4:
When creating a new lable. Type a name for the lable then tap to edit the color. Upon returning from selecting the color the name of the lable is blanked out.

**Comment by agrogers** [comment]
Oh, yes, I have seen that too.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment]
It bugged me enough that I decided to create a bug ticket for it.😁

**Comment by tuomas2** [comment]
Fixed

**Comment by bvahedy** [comment]
Verified fixed in the latest beta build 527.
