### ISSUE TITLE
Update images for app stores

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1127]
4.0 release should get updated images for the app stores:
- [x] Google Play
- [x] F-Droid
- [x] Amazon
- [x] Huawei
- [x] Samsung

We need graphics
- [x] featureGraphic.png 1,024 px by 500 px
- [x] 8 phone screenshots

Upload 2–8 phone screenshots
PNG or JPEG
16:9 or 9:16 aspect ratio
Each side between 320 px and 3,840 px
Up to 8 MB per screenshot

- [x] max 8 seven inch screenshots

Upload up to 8 7-inch tablet screenshots
PNG or JPEG
16:9 or 9:16 aspect ratio
Each side between 320 px and 3,840 px
Up to 8 MB per screenshot

- [x] max 8 10 inch screenshot

Upload up to 8 10-inch tablet screenshots
PNG or JPEG
16:9 or 9:16 aspect ratio
Each side between 320 px and 3,840 px
Up to 8 MB per screenshot

- [x] youtube banner picture 

For the best results on all devices, use an image that’s at least 2048 x 1152 pixels and 6MB or less. 

- [x] facebook banner picture

Displays at 820 pixels wide by 312 pixels tall on your Page on computers and 640 pixels wide by 360 pixels tall on smartphones.
Must be at least 400 pixels wide and 150 pixels tall.
Loads fastest as an sRGB JPG file that's 851 pixels wide, 315 pixels tall and less than 100 kilobytes.

- [ ] youtube video watermark

An image that’s 150 x 150 pixels is recommended. Use a PNG, GIF (no animations), BMP, or JPEG file that’s 1MB or less.

Play Store photos can be added directly here: `fastlane/metadata/android/en-US/images`.

**Comment by agrogers** [comment]
Yes, we can get some colourful images now. Can I help with this?

**Comment by tuomas2** [comment]
Screenshots should not be taken until very late moment because UI can still change
Screenshots and marketing images can be updated via pull request (they are under `fastlane/metadata/android/en-US/images`)

**Comment by tuomas2** [comment]
I also started this: https://github.com/AndBible/and-bible/pull/803, if someone wishes to continue, feel free! (I am not planning to do anything about it in the (near) future).

**Comment by tuomas2** [comment]
Related,

> Play has updated store listing asset guidelines for feature graphics, screenshots, videos, and short descriptions. This is to improve the quality of store listing preview assets. Make sure your assets meet these guidelines, or your app may not be eligible for promotion. We are also providing a preview of upcoming policy requirements for app title, icon, and developer name. You should review these requirements to prepare for the future policy change. We'll provide more information about these changes to you at a later date.

https://support.google.com/googleplay/android-developer/answer/9866151#zippy=%2Capp-icon%2Cshort-description%2Cfeature-graphic

https://android-developers.googleblog.com/2021/04/updated-guidance-to-improve-your-app.html

**Comment by tuomas2** [comment]
added some task list to OP

**Comment by tuomas2** [comment]
added exact parameters for each needed pic

**Comment by agrogers** [comment]
I will work on this asap.

**Comment by tuomas2** [comment]
@agrogers Can you change banner graphic to youtube channel?
Featuregraphic from Play store is not high resolution enough.

https://studio.youtube.com/channel/UCZk46q0JzDsKRVAc6x2l5Sg/editing/images

**Comment by tuomas2** [comment]
@agrogers is it intentional that the bottom of the screen is not totally visible in phone screenshot pics? Like here: 

https://github.com/AndBible/and-bible/blob/develop/fastlane/metadata/android/en-US/images/phoneScreenshots/1_en-US.jpeg

**Comment by agrogers** [comment]
Yes, creative style :D

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
@agrogers can you change this:

![Selection_202](https://user-images.githubusercontent.com/5811789/135426321-5bd35b8d-2024-4d12-9089-4e61c29a6ddc.png)

**Comment by agrogers** [comment]
Will do

**Comment by tuomas2** [comment]
I believe this is done by now. Thank you!
