### ISSUE TITLE
Order books horizontally does not work properly

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1128]
**To Reproduce**
1. Go to bible book selector
2. From options menu choose "Order books horizontally" -> order chages correctly
3. Go back from book selector
4. Open book selector again 
Actual: Books are ordered vertically although option is saved correctly in options menu
Expected: Books are ordered vertically according to the setting

**Comment by tuomas2** [comment]
@jmarsican would you like to fix this and make a pull request?

**Comment by jmarsican** [comment]
> @jmarsican would you like to fix this and make a pull request?

Oh my bad! I thought I already tested such scenario. Surely I'll try to fix it this weekend

**Comment by agrogers** [comment]
A similar issue happens for me when changing workspaces too -  the horizontal checkbox is checked by the order is wrong. 

Should this be a global setting or a workspace setting? I prefer a global setting. i think.

PS: This is a great addition. I always struggled to find the books in the vertical ordering - but didn't realise how the horizontal ordering would help me.

**Comment by agrogers** [comment]
Oh, and I meant to add that I think the setting should apply to the numbers (chapters and verses) also. I think the reason this ordering option seems to help me is that my mind always expect larger numbers should be below smaller numbers. So number 15 should be lower than number 6. But as you can see in this screenshot, that isn't the case.

I think I would stick with showing 5 buttons per row for numbers.

![image](https://user-images.githubusercontent.com/13920678/122632717-00562d00-d118-11eb-8509-f4f406c36359.png)
