### ISSUE TITLE
Can the color of the Note and Whole Verse buttons be improved?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1130]
Below is a good example where I feel the current color choice for those two buttons is a little unclear. This is somewhat related to #1040 

Basically, I dont think we should use a color other than gray for the buttons because its conveys the wrong idea. I think we should use the label color consistently - or use gray. So the blue whole-verse button and blue notes button should be changed to something else.

I am still tending towards no. 4 or 6 here #1040. 

But how to show that there is a note or it is a whole-verse bookmark? This was one suggestion:
![image](https://user-images.githubusercontent.com/13920678/121655200-c49ce100-cae1-11eb-9216-7dbd477d41f5.png)

But i think perhaps the best way is to:
1. Use no.6 from #1040 
2. Use gray icons by default except for Study Pads
3. Change them to color if there is a note or a whole verse
![image](https://user-images.githubusercontent.com/13920678/121655646-1c3b4c80-cae2-11eb-8eb7-be3eb835b80e.png)

![image](https://user-images.githubusercontent.com/13920678/121653525-22302e00-cae0-11eb-8662-b9d3c4812566.png)

**Comment by agrogers** [comment]
The same color choices should also apply on this form (ie the blue button replaced with green when the whole verse option is active) 

![Screenshot_2021-06-13-00-14-22-366_net.bible.android.activity.jpg](https://user-images.githubusercontent.com/13920678/121778907-7ddfe180-cbdc-11eb-814b-55ce46bb79d6.jpg)

**Comment by tuomas2** [comment]
As of implementing #1040 this also can be closed for now.
