### ISSUE TITLE
Title ref has got abbreviated somehow (it should not) 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1131]
See: https://support.andbible.org/scp/tickets.php?id=546

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=474

**Comment by tuomas2** [comment]
I have not seen this so I believe it was fixed by https://github.com/AndBible/and-bible/commit/e28dc54345e2a7202f0368402a97194379128369

**Comment by tuomas2** [comment]
Appeared again

**Comment by tuomas2** [comment]
Today noticed that this happened when I opened previously minimised window (that had not been opened before during the AB session, I believe).

**Comment by tuomas2** [comment]
Some logging here: https://support.andbible.org/scp/tickets.php?id=1140

**Comment by tuomas2** [comment]
maybe reproduced again: https://support.andbible.org/scp/tickets.php?id=1145

**Comment by tuomas2** [comment]
> maybe reproduced again: https://support.andbible.org/scp/tickets.php?id=1145

Perhaps not same issue. It "fixed itself" by itself without restarting app. But I did see abbreviated title once. Can't find anything in log file.
