### ISSUE TITLE
Show both KJV and engKJV2006eb in "Download documents"

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1132]
From #979 

In Download documents screen, KJV and engKJV2006eb are merged into one, probably because their abbrev. name are both "KJV". Only the highest version is shown, which in this case is "engKJV2006eb" from eBible. But Crosswire's "KJV" seems to be in better shape.

- [x] Show both in Download documents
- [x] Make KJV the preferred download (in https://github.com/AndBible/data/blob/master/recommended_documents.json)

**Comment by tuomas2** [comment]
> * Make KJV the preferred download (in https://github.com/AndBible/data/blob/master/recommended_documents.json)
