### ISSUE TITLE
Categories in the Label list have been lost 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1134]
![Screenshot_2021-06-12-22-46-07-259_net bible android activity](https://user-images.githubusercontent.com/13920678/121776458-51be6380-cbd0-11eb-822b-2e12834f6fcd.jpg)
![Screenshot_2021-06-12-22-45-47-259_com google android gm](https://user-images.githubusercontent.com/13920678/121776459-54b95400-cbd0-11eb-94ba-70b7714450a7.jpg)

**Comment by tuomas2** [comment]
I don't quite get how second pic is related to first one (I think that second pic issue was fixed already).

First pic I could reproduce.

**Comment by agrogers** [comment]
Um, they might not be related actually. But it seemed like the headings had got messed up in some way in both - although I couldn't understand the text so I was guessing. Glad to hear it is fixed.

**Comment by tuomas2** [comment]
fixed

**Comment by bvahedy** [comment]
Verified fixed in 529.1 build.
