### ISSUE TITLE
Do not update the Label list when a selection is made 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1135]
At present when a label is selected the list is immediately updated and so the newly selected label disappears and is moved to the very top into the active labels group.

This can be disconcerting - it seems either like my click did not work because there is nothing selected on screen or 'what, my label just disappeared!'

Of course one gets used to it disappearing but I think a better solution is that 
- [x] labels are not reordered or grouped when selected or perhaps even renamed.

A second issue is when a new label is created. Again, the new label can end up anywhere in the list which is often not on screen. It feels wrong not being able to see what I just added. 
- [x] Scrolling to the location of the new label I think is the right solution.

Normally that would be at the top because I always add the label to the verse when I create an entirely new label. This is why I think the "This bookmark" checkbox should be ticked by default when creating a new label.

**Comment by tuomas2** [comment]
Implemented
