### ISSUE TITLE
The small helper icons in the Label dialog go bright red sometimes 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1136]
This has happened once when creating a new label and once when editing the color of an existing label. I would also consider making those icons a little smaller.

![Screenshot_2021-06-12-23-11-12-280_net.bible.android.activity.jpg](https://user-images.githubusercontent.com/13920678/121777176-060db900-cbd4-11eb-99b9-836785ea237a.jpg)

It looks normal when going back into the dialog as shown below.
![Screenshot_2021-06-12-23-11-43-038_net.bible.android.activity.jpg](https://user-images.githubusercontent.com/13920678/121777187-1756c580-cbd4-11eb-90df-0cad6a587832.jpg)

**Comment by tuomas2** [comment]
I made them as "SpannedImages" to the end of text, but couldn't figure out how to change their size.. Android-side tuning is sometimes trickier than I would like.

Color issue: we should figure steps to reproduce.

**Comment by tuomas2** [comment]
Grey is proper color

**Comment by agrogers** [comment]
I suggest we delay this one to after v3.4 release

**Comment by tuomas2** [comment]
I believe this is fixed by now.
