### ISSUE TITLE
Strings that need to be shortened / simplified

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1138]
In order to make it possible to keep menu item titles short enough even when translating to different languages, we should shorten them. Preferrably 1-2 word titles.

- "Auto-assign & Favourite Labels" in 3dot-menu
- Share, Backup & Restore data in main menu, and it's submebu items
- Titles in Application preferences (those need to be gone through - they can be a little longer, but at least some of them are too long now)

(see also https://support.andbible.org/scp/tickets.php?id=533)

**Comment by tuomas2** [comment]
@AndBible/developers  @AndBible/contributors  Suggestions welcome to these. 
We should come up with something 1-2 word titles preferrably.

**Comment by timbze** [comment]
I've been thinking for "Backup & Restore" it would be nice to just have that, and open an activity where you can pick the options about what to do. But I have not thought up a design for that screen yet.

**Comment by tuomas2** [comment]
Maybe even alert dialog based would do

**Comment by RuggMatt** [comment]
Perhaps "Auto-assign & Favourite Labels" could be something like "Label Settings"

**Comment by tuomas2** [comment]
Opinions:
- "Active labels" -> "Selected labels"?
- "Underline style for normal bookmarks" -> Underline style for selection bookmarks" (compare to "whole verse bookmarks")?
- In selection menu, there's "Bookmark verse". Should "Bookmark" be renamed to "Bookmark selection" or "Bookmark this" or what do you think? Or maybe abbreviated versions: "Bookmark" and "Verses" (user need to make a little guess what "Verses" does), but we get more menu items displayed this way.

![image](https://user-images.githubusercontent.com/5811789/122404191-af173380-cf87-11eb-9d76-a71f50566041.png)

**Comment by agrogers** [comment]
I will have a good look at it this weekend.

**Comment by tuomas2** [comment]
Backup related: 94183afac473ae4b7c719962262bf9e5e2155c91

**Comment by tuomas2** [comment]
I'm adding "Browser actions" to selection menu which shows normal copy, share etc items. Ideas for better name? System items? Android items?

**Comment by timbze** [comment]
> I'm adding "Browser actions" to selection menu which shows normal copy, share etc items. Ideas for better name? System items? Android items?

I think 1. "System actions" or 2. "Other actions" or 3. "More actions"

**Comment by bvahedy** [comment]
I like "more actions" or just simply "more..." Or "more", it invokes the
curiosity of the user, they don't necessarily need to know it's system or
Android related.

**Comment by timbze** [comment]
> ![image](https://user-images.githubusercontent.com/5811789/122404191-af173380-cf87-11eb-9d76-a71f50566041.png)

I think "Verses" by itself is too unclear and confusing.

How about using the same functionality that you have with "More" now?
Just have "Bookmark" item. When user clicks "Bookmark", new menu pops up that has "Selection" and "Full verse" options.

**Comment by bvahedy** [comment]
I like this idea of presenting a sub menu. It also presents a thought as to
whether the user wants to bookmark the whole verse or just the selection.
Although it adds more clicks in accomplishing a task if someone is
bookmark-trigger-happy.

**Comment by tuomas2** [comment]
> How about using the same functionality that you have with "More" now?
> Just have "Bookmark" item. When user clicks "Bookmark", new menu pops up that has "Selection" and "Full verse" options.

That's an option indeed. But that would make 1-tap action 2-tap action. I'm not sure about this. What do others think?

**Comment by tuomas2** [comment]
> I like "more actions" or just simply "more..." Or "more", it invokes the curiosity of the user, they don't necessarily need to know it's system or Android related.

"More" would be nice option, for simplicity and shortness but I think "System actions" works well because it kind of "warns" user that those actions might not be optimized for And Bible usage.

**Comment by tuomas2** [comment]
What do you think if I shorten "Bookmarks & My Notes" from main menu -> "Bookmarks"?

**Comment by tuomas2** [comment]
Is "Load Documents from Zip" necessary in Main Menu? Function is available also from Backup & Restore.

**Comment by timbze** [comment]
> What do you think if I shorten "Bookmarks & My Notes" from main menu -> "Bookmarks"?

I think since notes are connected with bookmarks that much now anyway, I think that would be good.


> Is "Load Documents from Zip" necessary in Main Menu? Function is available also from Backup & Restore.

I think it can be removed.

**Comment by bvahedy** [comment]
A lot of the users are not savvy enough to differentiate between  "System
actions" and Andbible controls.
Just my experience dealing with users.

**Comment by tuomas2** [comment]
Should there be option in "App preferences" that need to be enabled in order to see "More" item, i.e. it wouldn't be shown by default? I'm thinking that some/many users might benefit from "Translate" item etc, but might be confused by "copy", "share" items etc.

**Comment by agrogers** [comment]
> Should there be option in "App preferences" that need to be enabled in order to see "More" item
I fear most users may never find that option so never benefit from it.

I have wondered whether an 'Easy' and 'Advanced' interface option would be helpful. 'Easy' would reduce the options available across the application. I downloaded YouVersion and another Bible popular on Play Store - they have so few config options in comparison. I much prefer And Bible's flexibility but suspect the average YouVersion user would not.

I think And Bible is really intended for Bible **study** while most other Bible apps are intended only for devotional reading (I would like to discuss this further at some point).

**Comment by agrogers** [comment]
> Is "Load Documents from Zip" necessary in Main Menu? Function is available also from Backup & Restore.

I have made an alternative form here: https://github.com/AndBible/and-bible/issues/1156
A lot more work then changing the title but I think is probably a bit more user friendly.
And yes, accessing from Backup & Restore is enough I think.

**Comment by agrogers** [comment]
I also didn't understand what 'Verses' meant in the latest beta. My suggestion here https://github.com/AndBible/and-bible/issues/1165 might eliminate the need for a 'Bookmark whole verse' menu option or strengthen the case for moving it into a sub-menu. It will also remove the need for a 'Compare' and a 'Share' option.

**Comment by tuomas2** [comment]
I made conf option to advanced users, but 2-tap bookmarking is now default. I think strings are now adequately abbreviated.
