### ISSUE TITLE
Issue when deleting an already assigned label

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1141]
After bookmarking a verse. Then tapping on the unlabeled bookmark and assigning it a new lable. When the lable is deleted from the "manage lables"  menu screen, the verse associated with that lable is still highlighted and it still caries the deleted lable name. If the user taps to select another lable the old lable will not be listed since it was deleted but the user may not remember that.
I can't tell if this is a feature or not, it can be, I guess. Alternatively  all the bookmarks associated with a lable can be assigned to "unlabeled"  once a lable is deleted.

Posted here: https://support.andbible.org/scp/tickets.php?id=579

**Comment by bvahedy** [comment]
Verified fixed in 529.1 build.
