### ISSUE TITLE
Unable to find message when doing a find all occurrences under particular scenario involving Strongs numbers

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1142]
When you tap on strong's no. and it opens in  a linked window that had already been opened and had other views for other Bible texts or other commentary links, then I get this unable to find message when doing a find all occurrences.

This problem has been happening for a long time now but don't know if anyone else has encountered it. Hopefully the logcat will show something.
The only way to recover is 

1. to close the link window and tap on the strong's no. 
2. To create a new linked window.
3. Then the search is able to find all occurrences.

Video of the issue on the ticket: https://support.andbible.org/scp/tickets.php?id=550

**Comment by agrogers** [comment]
Hi Ben. Does this still happen? I have never seen it before.

**Comment by bvahedy** [comment]
What I did to fix it was:
I backed up all my modules.
Then did a complete fresh install.
After the restore I have not had this issue.
So I'll close this unless I see it again. 
Thx for the check up.
