### ISSUE TITLE
Not picking up the correct morph code

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1143]
Looking at Matthew 1:2
I believe Andbible is not picking up the right morph code for kjv.
(See attached screenshot)

As I had already complained that when tapping on the HiSB morph does not automatically open a window, a function that used to work, but by tapping and holding the code and selecting to open the link in a new window it does correctly display the morph code from the dictionary.
However when using the KJV, tapping on the morph code automatically opens a new window but incorrectly displays the morph code.

Posted here: https://support.andbible.org/scp/tickets.php?id=568
![Screenshot_20210611-181249_Bible Study](https://user-images.githubusercontent.com/13920678/122207525-92c2ba80-cee5-11eb-8173-b999b81388d4.jpg)

**Comment by tuomas2** [comment]
Does this work properly for old version? @bvahedy

**Comment by bvahedy** [comment]
Which version specifically?

**Comment by bvahedy** [comment]
I normally don't use kjv, I used to be able to click on the morph in HiSB
but now I have to press and hold to open it in a new link even though the
morph code is a blue color which means it's a  link. When you told me it
works with kjv version I realized kjv is not displaying the correct morph.
That's how I found this bug.

**Comment by tuomas2** [comment]
> Which version specifically?

3.3, currrnt stable version

**Comment by bvahedy** [comment]
It works correctly in 3.3 version.
Also I verified that I can single tap on the morph in hisb version and it
opens up a new window automatically which in 3.4 I'm unable to do currently.

**Comment by tuomas2** [comment]
Tapping "Abraham" gives me this, which looks correct: 

![image](https://user-images.githubusercontent.com/5811789/123296382-43047480-d51f-11eb-969f-2bca6f749358.png)

**Comment by tuomas2** [comment]
I'm having KJVA though. I'll try with KJV

**Comment by tuomas2** [comment]
Okay, this is module issue with KJV from eBible.org. Crosswire's KJV works fine too.
