### ISSUE TITLE
Bookmark and "confirm remove bookmark" dialog too wide in tablet (wide screen)

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1144]
![image](https://user-images.githubusercontent.com/35117769/122433519-8aa16400-cf53-11eb-81ba-402f7f0428f8.png)

I think the width should have a max width that would be in this case a little less than text width. Even if I increased the max width of text the modals should not get wider than a certain width, I think.

**Bug was found on And Bible version**
Build 528

Kindle Fire HD10

**Comment by tuomas2** [comment]
Fixed 2fc21b8f1837ce0b980f77628289960a9eeefc14
