### ISSUE TITLE
Kindle Fire HD 10 (Android 5.1) can only select 1 word in text

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1145]
**Describe the bug**
I can only select one word. The marker to pull selection does not show up.

![image](https://user-images.githubusercontent.com/35117769/122434295-33e85a00-cf54-11eb-9e49-33f53a4ff1b7.png)

Aside; the bookmark feature does now work. It didn't show the highlights the very first time I tried, but later it showed up and now works.

**Bug was found on And Bible version**
Build 528

Kindle Fire HD 10

**Comment by tuomas2** [comment]
Does selection work properly for commentaries / genbooks?

**Comment by timbze** [comment]
> Does selection work properly for commentaries / genbooks?

No. Same issue with those.

**Comment by tuomas2** [comment]
Can you try again for non-bible doc? (build triggered)

**Comment by tuomas2** [comment]
Its interesting that I have also old lollipop-based samsung tablet but I don't have similar issues there.. :-/ It's having latest WebView from Google though.

**Comment by timbze** [comment]
> Can you try again for non-bible doc? (build triggered)

Genbook and commentary still both have the same issue (in 528.5)

**Comment by tuomas2** [comment]
Does it work in other apps that use Webview?

**Comment by tuomas2** [comment]
Does it work in 3.3 version of And Bible for non-bible documents?

**Comment by timbze** [comment]
> Does it work in other apps that use Webview?

Finding now that I have the same issue in some other apps. So it's probably a Kindle Fire update that is the problem, because I did not have this issue before.
