### ISSUE TITLE
Label and notes icons and no longer displayed in translations that they were NOT created in

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1147]
I am sure the icons used to display at the end of a verse even when I was reading a translation that was different to the one where i added the label.  Now only the whole verse labels are shown across translations.

The image below shows two translations - i created the labels in NASB (top) but could not see them in the God's Word (bottom)

![image](https://user-images.githubusercontent.com/13920678/122630398-984b1b00-d106-11eb-9cd0-3d0e5ebe9bf5.png)

**Comment by tuomas2** [comment]
Fixed

**Comment by bvahedy** [comment]
Verified fixed in 529.1 build.
