### ISSUE TITLE
Are these icons paragraph marks? If so, why not just have a paragraph?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1148]
I noticed these black reverse P icons (see v16, 29) for the first time today. If they are paragraph icons, wouldn't it be better just to put the verse on a new paragraph?

![image](https://user-images.githubusercontent.com/13920678/122630519-af3e3d00-d107-11eb-8646-e20e931fb1ca.png)

**Comment by tuomas2** [comment]
Paragraph markings are in KJV put manually (characters).
