### ISSUE TITLE
The keyboard is not displayed when creating a new workspace

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1149]
I added a new workspace today. The default text was automatically highlighted. But the keyboard had not displayed.

I expected that the keyboard would show so i could immediately enter the new workspace name.

![image](https://user-images.githubusercontent.com/13920678/122630552-ee6c8e00-d107-11eb-92c9-fb7d95acbc29.png)

**Comment by tuomas2** [comment]
fixed

**Comment by bvahedy** [comment]
Verified fixed in 529.1 build.
