### ISSUE TITLE
Add option to exclude the version name from the 'Share' action

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1151]
This is a nice little dialog. I think it might also be good to be able to exclude the version from the generated text. So, the text 'NASB' below would be hidden.

![image](https://user-images.githubusercontent.com/13920678/122630628-836f8700-d108-11eb-96be-f8308e604e76.png)

**Comment by tuomas2** [comment]
Added string version_name for this to be implemented

**Comment by agrogers** [comment]
Will be closed by https://github.com/AndBible/and-bible/pull/1968
