### ISSUE TITLE
Reset option for application preferences

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1155]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tuomas2** [comment]
https://stackoverflow.com/questions/22251908/reset-sharedpreferences

**Comment by timbze** [comment]
Need to keep in mind preferences that are not user configurable.

Maybe there are none that matter, but should recheck before adding an option to clear everything.

**Comment by tuomas2** [comment]
Like for example?

**Comment by tuomas2** [comment]
Okay I see.... We need to do reset only for settings indeed.
