### ISSUE TITLE
Backup and Restore dialog proposal

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1156]
1. The original 'Share or Backup' text is probably not necessary. It describes precisely what they can do but they will work that out soon enough just by clicking on the button so it probably isn't necessary
2. This form would allow backing up all three types of data in one action not three.
3. The restore option needs to act like a radio button (only one of the two can be selected at once). On my device it opens a screen that allows me to get to Drive or my phone storage. I assume it's similar on other device.
4. The Restore button text could change depending on what option is selected (eg 'Restore Documents from')

![AndBible Suggestions-Backup](https://user-images.githubusercontent.com/13920678/122638391-20e1af80-d137-11eb-8c54-aa1b91a78cf8.png)

## Additional
- Improve [backup & restore](https://github.com/AndBible/and-bible/wiki/Backup-&-Restore) wiki page (suggested on #1801)

**Comment by tuomas2** [comment]
How should combined backup / restore work?

**Comment by agrogers** [comment]
Um, what is a 'combined' backup/restore?

**Comment by tuomas2** [comment]
When you toggle multiple items and press "Share or Backup to...", what happens?
Does it create a zip file containing both files? I guess Android allows saving only one file per time with file chooser intent. I might be wrong though.

**Comment by agrogers** [comment]
Ah, i get it. The issue doesn't apply to 'restore' since i suggested you implement the checkboxes like radio buttons - only one can be true. Could possibly do that for the Backup as well.

But i thought you would do the same as you do now.
1. Ask the user where they want to save the file(s)
2. Prepare the first file
3. Upload it
4. Prepare the second file
5. Upload it
6. Tell the user they can sleep easy tonight.

That's not possible?

**Comment by tuomas2** [comment]
Well chained operation is indeed possible

**Comment by tuomas2** [comment]
I could consider implementing this after 3.4 is released (not waiting to 3.5). Could you compile list of necessary strings for this feature so we can send them to translation? (pull request that changes `values/strings.xml`  would be best :-) )

**Comment by tuomas2** [comment]
I like RadioButtons more and changed it like this:
![image](https://user-images.githubusercontent.com/5811789/191755920-7cd405fd-28ac-427e-bcfc-c363db367eea.png)

**Comment by agrogers** [comment]
Radio buttons are better for the current implementation. If we ever allow backing up multiple items then checkboxes should probably come back.
