### ISSUE TITLE
How should we refer to a label?

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1161]
### Discussed in https://github.com/AndBible/and-bible/discussions/1159

<div type='discussions-op-text'>

<sup>Originally posted by **agrogers** June 19, 2021</sup>
Should labels be called 'Bookmark labels'. Aren't they also 'Study Pad Labels' as well?</div>

**Comment by tuomas2** [comment]
I'm okay with "Bookmark labels" (and explanation that each study pad is associated with a single bookmark label)

**Comment by agrogers** [comment]
My issue with that is a study pad is not associated with a 'bookmark'. It is associated with **all** bookmarks. Or rather, it is associated with a label - that label has been applied to many verses as bookmarks. It was one of the things that confused me when i first saw the Study Pads. They felt unrelated to bookmarks - but they were actually just a summary of bookmarks :)
