### ISSUE TITLE
Proposal to implement a single click action on a verse

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1162]
I thought i would have a look at YouVersion again today. It is definitely not for me - I mainly want a study tool not a devotional tool. But it had some nice features that I think would make it attractive to new users. The main one was how a single click in the bible window acted. Of course it **only** has one window so it is a much simpler workflow for them. But I think we could do something similar.

In YouVersion (image below), a single click on the verse:
1. Selects the verse
2. Shows a slide up menu allowing the user to highlight, share and do other things
3. Additional clicks on other verses adds them to the selection. So it is possible to highlight multiple/share/compare etc multiple verses.

I think we could do the following (image below). 
A single click on a bible window that does not touch any existing hyperlink (label, strongs number, etc)
1. Shows an action dialog (see below)
2. User can share or compare the same way as she already can when she long clicks a verse
3. User can write a note. If no label has been applied then it would need to be marked as 'Unlabeled' and the note window shown.
4. Assign a label to the whole verse. If that is done then the new labels need to be shown at the top of the dialog in the same way as the existing dialog works. 
5. In fact, this dialog is very similar to the existing one only with some extra buttons and a different heading.
6. Perhaps it is not too hard to enable selecting more verses with additional clicks on the bible window.

The purpose of the dialog is:
1. Make it really easy for users to do what I suspect the average or new user wants to do - bookmark, share or copy an entire verse
2. Provide the functionality that users from other apps probably expect. 
3. Long pressing on a bible verse and selecting text is great for detailed highlighting but not immediately obvious to a user. This dialog better exposes the functionality.

What to do with this dialog once a label has already been assigned to the verse is unclear to me at the moment
1. This dialog only applies to a **whole** verse.
2. It can't be accessed once a verse already has a label because a single click on a label brings up the bookmark dialog
3. All the actions for the verse can be accessed from existing dialogs so that is not an issue
4. The new dialog could be accessed easy enough from the current bookmark dialog by adding a new button to the button list at the top of the dialog. 

PS: I added this as a discussion in Git but now the Discussion option has completely disappeared :-o

![AndBible Suggestions-Bible Click](https://user-images.githubusercontent.com/13920678/122641393-74102e00-d148-11eb-9e10-a39e0e445538.png)

![image](https://user-images.githubusercontent.com/13920678/122641398-84280d80-d148-11eb-96e1-1c5ea5d2f836.png)

**Comment by agrogers** [comment]
I think the biggest change for the next release is the awesome overhaul of the labeling system. If the feature described here is to be implemented at some point, then I think that point should be now. Also, it is such a significant change to the way the user interacts with AB that I would want to avoid making them learn both the current way and then in a future release the new way outlined in this issue. So I would...

Include this feature in v3.4.

**Comment by tuomas2** [comment]
Trying to re-think about this today if I have time.

**Comment by tuomas2** [comment]
(no promise yet :-) moving label to different category just so it jumps to my eyes)

**Comment by tuomas2** [comment]
Implementation a bit different as usual. But hope you like it :-)

**Comment by agrogers** [comment]
I'm liking it so far. Do you like it??

**Comment by tuomas2** [comment]
Yes I do but #1273 is still bugging me a lot. I'll try to resolve it today.

**Comment by bvahedy** [comment]
The single click action is nice, although now when a Bible with strong's
has the dots under each word, single tap does nothing. I thick Andrew had
mentioned something about this earlier.

**Comment by bvahedy** [comment]
Ok, I just saw that when tapping on a word with dots under it invokes the
single action and in the little dialog window I see the option to display
strong's and morph, but the grey background throw me off, is there any way
we can change that to bring more attention to it?
