### ISSUE TITLE
What should a new install of And Bible look like?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1163]
I've been thinking that a new install of And Bible should perhaps have some things setup so that a new user can see what can be done. Happy to hear other's thoughts:
1. At least two workspaces. Maybe a simple workspace with one window and a second workspace with several windows. Or perhaps you guys have ideas on popular ways to setup a workspace. I have a workspace that doesn't show any bookmarks. Perhaps another one that shows a small book like the Practice of the Presence of God.
2. The simple workspace can be nicely spaced out with a larger font and no split windows etc much like what I see most Bible applications.
3. The other workspace(s) could have smaller and different fonts, colored backgrounds etc so the user can see what is possible.
4. A default Bible, commentary and dictionary. I think at present the user has to choose what documents they want before they get started. That kind of makes it impossible to set up some default workspaces
5. A set of labels. Perhaps those labels can be called 'Blue', 'Red',' Green' etc. So when a user goes to add a bookmark there are already a number of labels they can choose from - they dont have to create any. (#1172)
6. Maybe some labels already assigned - perhaps to Genesis 1:1 so that the study pad functionality can be used. (#1172)
7. Perhaps two default Bibles so the compare options and bible sync options can be setup.

Is there a reason why no documents are included with And Bible by default? File size?

**Comment by tuomas2** [comment]
> Is there a reason why no documents are included with And Bible by default? File size?

File size is (I believe) the primary (original) reason.

**Comment by tuomas2** [comment]
Good ideas. Should we try to get this to 3.4 still? If so, we should collect new needed strings as soon as possible

**Comment by agrogers** [comment]
There are soooo many new features I think we need to spend some time trying to ensure those features are implemented really well, understood and so get used. A preloaded install I think is perhaps the best way to do that. Also, the onboarding idea in #1071 may become more important - it would work well with a preloaded database.

For an existing user, they will already have a database so we can't really mess much with that - that is we can't set it up so they can see the features in action.

It would be good to discuss exactly what we want in the next public release so we (me) can focus a bit more. I have some thoughts for reading plans and speak functionality but i dare not add them in yet when there is so much already being worked on.

And I forget sometimes that we are not selling this... so do we care that much if people struggle with the new features for a while or give up and chose something else? :)

**Comment by tuomas2** [comment]
I would like to do feature-freeze soon for 3.4. More importantly, I'd like to freeze strings so that we can hope to get translations for 3.4 finalized.

**Comment by tuomas2** [comment]
Add couple of strings af4b8ea69cad4f1aadfabdda25a4bb4fc91bcd9c

**Comment by tuomas2** [comment]
> I've been thinking that a new install of And Bible should perhaps have some things setup so that a new user can see what can be done. Happy to hear other's thoughts:
> 
> 1. At least two workspaces. Maybe a simple workspace with one window and a second workspace with several windows. Or perhaps you guys have ideas on popular ways to setup a workspace. I have a workspace that doesn't show any bookmarks. Perhaps another one that shows a small book like the Practice of the Presence of God.
> 2. The simple workspace can be nicely spaced out with a larger font and no split windows etc much like what I see most Bible applications.
> 3. The other workspace(s) could have smaller and different fonts, colored backgrounds etc so the user can see what is possible.

Idea good, but won't implement these, at least in 3.4. I'm open for PR's, though. I feel that youtube video illustrating new videos is good enough to show what is possible.  

> 4. A default Bible, commentary and dictionary. I think at present the user has to choose what documents they want before they get started. That kind of makes it impossible to set up some default workspaces
> 7. Perhaps two default Bibles so the compare options and bible sync options can be setup.
> Is there a reason why no documents are included with And Bible by default? File size?

I don't feel like adding modules to APK but we could figure out a way to implement it other way, i.e. some kind of optional function to build up a demo setup (download necessary modules and set up db)? But not for 3.4.

> 5. A set of labels. Perhaps those labels can be called 'Blue', 'Red',' Green' etc. So when a user goes to add a bookmark there are already a number of labels they can choose from - they dont have to create any.
> 6. Maybe some labels already assigned - perhaps to Genesis 1:1 so that the study pad functionality can be used.

- [ ] these we could implement in 3.4. As an example of topical label there could be "Salvation" topic and few bookmarks in it.

**Comment by tuomas2** [comment]
Created https://github.com/AndBible/and-bible/issues/1172 for labels idea (5,6)

**Comment by tuomas2** [comment]
Related #1231

**Comment by agrogers** [comment]
My nephew in law had way more troubles getting started with AB than I expected. It was a little distressing actually. 

First he couldn't find the bible he wanted amongst the 100s of documents. Then some weirdness happened downloading bibles - the cool background loading caused confusion. He did find the long - press option though! Then he was confused by the label list. Then he and his wife took minutes trying to find how to download a commentary. Then tried to do something with Strongs but didn't have what he needed. Then he couldn't work out how to get split screen. He found night mode though. 

To be fair he had not seen anything AB could do. He commented and I agree that getting the app through play store will help a lot because he would have watched a cool intro video or at least seen some screenshots and so have an idea of what to expect. But still, I don't think he would have these issues with You Version. 

Then I showed them both my install with colors and screens and workspaces and labels and commentaries and Strongs and they loved it and agreed they would so use this over You Version - which they both have.

I understand that users tend to make their decision to keep an app on the first 5 minutes. I don't think we would have kept Danny.

But the fix for most of these issues is singular - provide a default install. Make sure the new user has two bibles, some commentaries, a split screen already set up, all they need for Strongs, some labels, even some preconfigured workspaces. If Danny had that then the first 5 minutes would have been mostly positive I think.

So my feeling is stronger than ever that our next release needs an easier getting started process. I would be very sad if new users have a look at AB for the first time due to our promo of its great new features only to have them go back to the inferior alternatives because they get stuck before they even get started.

I will find some more friends to trial it on. And I will raise some tickets to address some issues I observed. AB has ALL the features - just need to make them a little easier to access.

**Comment by tuomas2** [comment]
Just keep in mind that strings for 4.0 are frozen so we can't add any new strings anywhere (only use what we have now). 

4.1 is coming too, we don't need to get all the users of the world onboard in 4.0 :-)

**Comment by agrogers** [comment]
That's true. But I would be sad if some don't make it to 4.1 because they got confused by 4.0.

If I was selling the product then I would vote that it is important enough to try and resolve before any promotion takes place. But this is volunteer driven open source so I am not sure what my position should be.

Re strings, I haven't done any multi lingual apps so I am hesitant to comment too much there. My initial feeling is that the aim should be to ensure the app is great for as many as possible and to be cautious about allowing a minority to adversely affect the majority. But I should not say anymore about areas I have no experience in.

**Comment by tuomas2** [comment]
When I say to translators that strings won't change any more before release, I want it to mean that. 
I can imagine translators get frustrated if they can't rely on what we say. If I was a "normal" translator, I would like to just do the translation in one go, and not needing to make updates all the time (which is the case if they can't trust us). I'd like to keep this app translated with good quality to as many languages as possible, and thus we need to be nice to translators. 

I do have experience about "minority" trying their best to affect majority by giving a lot of 1-star ratings.

**Comment by agrogers** [comment]
Yes, definitely don't want to annoy the translators. Multilingual apps
definitely add an extra layer of complexity to the process.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Example bookmark is the remaining missing item, but it has separate ticket #1316 so I'll close this now.
