### ISSUE TITLE
I think we might need a general single click option on bible windows

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1165]
### Discussed in https://github.com/AndBible/and-bible/discussions/1160

<div type='discussions-op-text'>

<sup>Originally posted by **agrogers** June 19, 2021</sup>
I thought i would have a look at YouVersion again today. It is definitely not for me - I mainly want a study tool not a devotional tool. But it had some nice features that I think would make it attractive to new users. The main one was how a single click in the bible window acted. Of course it **only** has one window so it is a much simpler workflow for them. But I think we could do something similar.

In YouVersion (image below), a single click on the verse:
1. Selects the verse
2. Shows a slide up menu allowing the user to highlight, share and do other things
3. Additional clicks on other verses adds them to the selection. So it is possible to highlight multiple/share/compare etc multiple verses.

I think we could do the following (image below). 
A single click on a bible window that does not touch any existing hyperlink (label, strongs number, etc)
1. Shows an action dialog (see below)
2. User can share or compare the same way as she already can when she long clicks a verse
3. User can write a note. If no label has been applied then it would need to be marked as 'Unlabeled' and the note window shown.
4. Assign a label to the whole verse. If that is done then the new labels need to be shown at the top of the dialog in the same way as the existing dialog works. 
5. In fact, this dialog is very similar to the existing one only with some extra buttons and a different heading.
6. Perhaps it is not too hard to enable selecting more verses with additional clicks on the bible window.

The purpose of the dialog is:
1. Make it really easy for users to do what I suspect the average or new user wants to do - bookmark, share or copy an entire verse
2. Provide the functionality that users from other apps probably expect. 
3. Long pressing on a bible verse and selecting text is great for detailed highlighting but not immediately obvious to a user. This dialog better exposes the functionality.

What to do with this dialog once a label has already been assigned to the verse is unclear to me at the moment
1. This dialog only applies to a **whole** verse.
2. It can't be accessed once a verse already has a label because a single click on a label brings up the bookmark dialog
3. All the actions for the verse can be accessed from existing dialogs so that is not an issue
4. The new dialog could be accessed easy enough from the current bookmark dialog by adding a new button to the button list at the top of the dialog. 

![AndBible Suggestions-Bible Click](https://user-images.githubusercontent.com/13920678/122641058-2e526600-d146-11eb-901f-c87199f5e05f.png)

![image](https://user-images.githubusercontent.com/13920678/122639835-88036200-d13f-11eb-82ce-4e5a93616e87.png)
</div>

**Comment by tuomas2** [comment]
I think we can consider these ideas at some point (I agree mostly), but I don't find it so important at the moment, so that I would be motivated to change the currently good-feeling UI.

**Comment by agrogers** [comment]
I have been thinking more about this one and feel it is possibly the most important UX change for new users. The long-press option which first selects a word but can also perform actions on verses is just not so intuitive. 

There are probably some good alternatives as well like the radial button menu below. Or even just a simple popup menu would do the job - although it adds one more (unnecessary?) step into the bookmarking process. Just need some way a user can do stuff on a verse without having to use the dark magic of long-clicking :) And how can i make gitub images smaller?!?!

![99903389-13239300-2cea-11eb-9890-7e128c2d7947](https://user-images.githubusercontent.com/13920678/124897150-5f290b00-e021-11eb-8f74-9ab42dae63d4.gif)

**Comment by tuomas2** [comment]
I think we should close this in favor of #1162
