### ISSUE TITLE
Proposal for initial target dialog when a bible window is clicked

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1169]
This is a more mature version of #1165 
Also needs #1188 

I noticed that we now have _three different dialogs_ that are displayed depending on what we click on in a bible window. They are described in the image below. I am not sure this is a good idea. I know exactly what is happening because I have helped design this :) But I am sure this could be a bit disconcerting for a user. 

I think a better option is that the user is always taken to a form that looks the same (or almost the same) wherever they click in a bible window. Further explanation is in the image.

1. The only real change to the existing form structure is the addition of the Info icon so the user can navigate to the main bookmark dialog (top left).
2. I have added a Speak icon here too. Maybe other things that are verse specific down the track.
3. What I like most about this approach is that a) the user sees pretty much the same thing whatever verse he clicks on and b) almost all the functionality which is hidden behind a long press and/or multiple menus is now really easily accessible and, more importantly, really visible.
4. The long-press option can remain as is with the exception that when a bookmark is selected it takes you directly to the 'verse-action' dialog (bottom right)
![AndBible Suggestions-click  target](https://user-images.githubusercontent.com/13920678/123415206-46b7fa00-d5f8-11eb-8c86-19378e85c565.png)

**Comment by tuomas2** [comment]
Also footnotes and crossreferences create modals.

**Comment by agrogers** [comment]
True, I don't see those much. I think they and strong's numbers and morph codes can be left just as they are.

**Comment by agrogers** [comment]
As I mentioned elsewhere, this proposal is very related to the how the new labeling system works. So if it is to be implemented, i would say included it now so that users are not having to relearn something new in the future. I also think this proposal is a fairly significant simplification of how the user interacts with labels making it a worthy inclusion.

Include this feature in v3.4.

**Comment by agrogers** [comment]
#1188 tries to address the link issue.

**Comment by tuomas2** [comment]
I believe this is also fully implemented as of #1162

**Comment by agrogers** [comment]
We seemed to have reverted back to the original target for a verse with an existing bookmark. It's shown in the first column in the first image above.

I think it was working differently a few days ago.

The issue remains the same - now I can't get to the operations I might want on a verse - share, compare etc.

Was that a deliberate change?

**Comment by tuomas2** [comment]
> We seemed to have reverted back to the original target for a verse with an existing bookmark. It's shown in the first column in the first image above.
> 
> I think it was working differently a few days ago.
> 
> The issue remains the same - now I can't get to the operations I might want on a verse - share, compare etc.
> 
> Was that a deliberate change?

If a *visible* bookmark highlight is clicked and there's only 1 bookmark, it will open the bookmark. It will work for all actions similar way. It will see all the actions, see if there's only one action with top priority, it will do the action immediately. If there are more, it will show the ambiguous selection dialog. 

I think it works as it should.

**Comment by agrogers** [comment]
OK, so what is the process now for a user to share or compare a verse when
there is a single bookmark on the verse?

**Comment by agrogers** [comment]
Sorry, not Share - that is possible. I mean
- Compare
- Speak (if we add that)
- Add a new bookmark

**Comment by tuomas2** [comment]
Perhaps we should lower the priority for whole verse bookmarks (especially underline style?)... But it was quite bugging me that I couldn't single-tap to bookmark dialog from my bookmarks.

**Comment by tuomas2** [comment]
```
export const EventPriorities = {
    HIDDEN_BOOKMARK: 0,
    VISIBLE_BOOKMARK: 5,
    FOOTNOTE: 15,
    STRONGS_DOTTED: 5,

    // "link-style"
    EXTERNAL_LINK: 10,
    REFERENCE: 10,
    STRONGS_LINK: 10,
}
```

**Comment by tuomas2** [comment]
if priority is 0 then it will show the ambiguous selection dialog even if there's only one item

**Comment by agrogers** [comment]
What do you use the bookmark dialog for? It's kind of a dialog that I like
the look of (especially the bottom few lines ;-) but I rarely need.
- It doesn't show all the labels (they fade out)
- I still have to click the notepad to make a note.
- It shows me the selected part of the verse but I could already see that
before I clicked.
- It shows me when the bookmark was created but I never need that.
- I do like seeing all the names of the labels in the study pad list. But I
can get that info from the summarised form.

So I am not sure why I would use it.

Oh, if it has a note attached it is useful. That's the only thing I can
think of. Am I missing something?

**Comment by tuomas2** [comment]
> What do you use the bookmark dialog for? It's kind of a dialog that I like the look of (especially the bottom few lines ;-) but I rarely need. - It doesn't show all the labels (they fade out) - I still have to click the notepad to make a note. - It shows me the selected part of the verse but I could already see that before I clicked. - It shows me when the bookmark was created but I never need that. - I do like seeing all the names of the labels in the study pad list. But I can get that info from the summarised form. So I am not sure why I would use it. Oh, if it has a note attached it is useful. That's the only thing I can think of. Am I missing something?

I guess it's most annoying if there's note that I want to see. If that is the case, perhaps I could try again to put bookmarks to 0 prio and only put note icon to have higher prio so that by clicking note icon directly user gets to bookmark. I'll test again and see how it feels..

**Comment by agrogers** [comment]
Yeah, I understand. Can we include a way to get back to the verse action dialog? Maybe use this button with a new icon?

![IMG_20210711_224251.jpg](https://user-images.githubusercontent.com/13920678/125195560-7bcf7800-e299-11eb-960b-102cbd167c33.jpg)

**Comment by tuomas2** [comment]
> Yeah, I understand. Can we include a way to get back to the verse action dialog? Maybe use this button with a new icon?

I'd like not to confuse bookmark modal with ambiguous selection modal.

**Comment by tuomas2** [comment]
This is anyway now changed back so that ambiguous modal is shown if bookmark is clicked (unless clicking marker icon).
