### ISSUE TITLE
Crash when trying to bookmark verse or a selection.

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1173]
https://support.andbible.org/scp/tickets.php?id=600

**Comment by bvahedy** [comment]
crashes happen in some workspaces but not all.

**Comment by tuomas2** [comment]
Logcat shows crash when trying to share selection and that crash should have been fixed (fix was done 17.6.). Can you make a new report for this if it still exists.

**Comment by bvahedy** [comment]
This seems to have  been fixed in 529.1 build.
