### ISSUE TITLE
Update recommended documents

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1175]
What to add? What to remove?

I'd suggest adding KingComments at least. 

Currently: 

```
{
  "bibles":  {
    "en": ["NASB", "KJV", "NETfree"],
    "fi": ["FinRK", "FinSTLK2017"],
    "es": ["spaRV1909eb", "NBLA", "LBLA"],
    "de": ["deu1912eb"]
  },
  "commentaries": {
    "en": ["Gill", "MHC", "TSKe"]
  },
  "dictionaries": {
    "en": ["StrongsRealGreek", "StrongsRealHebrew"]
  },
  "books": {
    "en": ["OpenHymnal"]
  },
  "maps": {
    "en": ["SmithBibleAtlas"]
  }
}
```

**Comment by timbze** [comment]
- Change `spaRV1909eb` to `spaRV1909`

**Comment by tuomas2** [comment]
Added King Comments https://github.com/AndBible/data/commit/4b6af6b1db51d27eab56cddd3cbb13c2df697982

**Comment by tuomas2** [comment]
> * Change `spaRV1909eb` to `spaRV1909`

Done https://github.com/AndBible/data/commit/67894570f303524028ef0ac4c0549d8ad7968774

**Comment by agrogers** [comment]
Do we have a recommended document for **every** language? If not, I would suggest we add at least one bible for each language.

**Comment by agrogers** [comment]
But there are a lot of languages!

**Comment by agrogers** [comment]
A easy to read language would be good for English. I don't have a strong preference there because i dont use it much - but 'God's Word' is one i have used. Others might have better suggestions.  BBE?

And maybe a Morphological Codes doc.

**Comment by agrogers** [comment]
My Burmese friend would recommend this one:
https://www.bible.com/versions/404-bcl-common-language-bible

The Judson version is like the KJV - good but hard for people today to read

**Comment by tuomas2** [comment]
If some language has only 1-2 documents, it does not make a lot of difference to have recommendations. I think the main purpose of recommendation is to find jewels among a lot of material.

**Comment by agrogers** [comment]
I agree. I think listing all recommended documents in a single list has
merit hence the Recommended filter suggestion.

But that filter won't work if there are no recommendations #1238.

Or perhaps just listing all recommended documents at the top of the list
would be perfect. Then we don't need a new filter.
