### ISSUE TITLE
It's not necessary to show the My Notes study pad icon for every bookmark

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1182]
The inclusion of the My Notes study pad icon is a good idea. But I don't think it is in the right place. It confused me a little when I saw them.

The main reason was that the icon was repeated three times (see the screenshot). As I understand it, the icon will always open to the same location - that is, to the chapter that the bookmark is found in. Multiple icons doing the same thing is probably more confusing than helpful.

I feel the following is probably a better solution. It adds an extra 'My Notes' button to the original screenshot in #1169 

![image](https://user-images.githubusercontent.com/13920678/123376410-c8466280-d5cd-11eb-8f8b-71f1763c68da.png)

![image](https://user-images.githubusercontent.com/13920678/123374924-3dfcff00-d5cb-11eb-851a-a58300ee6b84.png)

**Comment by tuomas2** [comment]
Implemented in dc18086808c3d643b567f692669f9bafb64630ad
