### ISSUE TITLE
The list of study pad icons can get too long and extend beyond the width of the dialog

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1183]
An interesting side effect is that, although i can scroll to see the extra icons, if i scroll to hard or fast it changes the chapter I am on :)

![image](https://user-images.githubusercontent.com/13920678/123381328-efa02e00-d5d3-11eb-8899-88e51499eb74.png)

**Comment by tuomas2** [comment]
Added scrollbar
