### ISSUE TITLE
Verse refs showing in the text - a problem with the NASB module?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1184]
And also notes - see: "Lit For them In their case...."
![image](https://user-images.githubusercontent.com/13920678/123381823-9258ac80-d5d4-11eb-9531-c94609941587.png)

**Comment by bvahedy** [comment]
I believe this is a module issue. Should close this ticket.

**Comment by tuomas2** [comment]
If this is reported to Crosswire bug tracker, this can be closed. 

Reported here: https://tracker.crosswire.org/browse/MOD-389
