### ISSUE TITLE
Single-click verse functions

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1187]
- [x] #1105 
- [x] #1162 
- [x] #1182 
- [x] #1169
- [x] #1188

**Comment by tuomas2** [comment]
@agrogers do you think we will manage these string additions? b2a6b6f

**Comment by tuomas2** [comment]
Everything done

**Comment by agrogers** [comment]
Great work. Thank you very much

**Comment by timbze** [comment]
Thanks @agrogers for suggesting this. I just tried this out and I think this will be a HUGE improvement for "simple" Bible users.

**Comment by agrogers** [comment]
Thanks Timmy. I hope so too. Still a few teething issues though. What seems
so simple in my mind has many unintended consequences!
