### ISSUE TITLE
New Edit icon proposal

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1190]
They dont need adjusted colors to show their state.

![Edit icons](https://user-images.githubusercontent.com/13920678/123419991-44f13500-d5fe-11eb-8414-95d5e50b174a.png)

https://fontawesome.com/v5.15/icons/edit?style=regular
https://fontawesome.com/v5.15/icons/edit?style=solid

And in context:

![edit icon in context](https://user-images.githubusercontent.com/13920678/123420012-4ae71600-d5fe-11eb-8e32-842cd8bd8b8d.png)

**Comment by tuomas2** [comment]
Also this on #1220
