### ISSUE TITLE
Make a discussion group

### ISSUE THREAD

**Issue by thebiblelover7** [AndBible/and-bible#1191]
Hello Everyone!

I was looking around the wiki and noticed that there supposedly was a discussion group. When I checked the link I saw that it was a groups.google.com link. **Google Groups is now dead.** Could we use another platform?

### Options:
*these are the best ones imo*

* Make a Matrix room (no cost)
* Make a Telegram group (no cost)
* Or something like the above
* Host forum software (server costs)

### Conclusion

I think AndBible should consider making something like a Matrix room since it doesn't take any money from the pocket.

Let me know what you think.

**Comment by tuomas2** [comment]
I have felt Github issues have been sufficient. Usually input from users are bug issues and feature requests, but issues can be used for any AB related discussion topic. And to follow discussions, one simply needs to be subscribed to the project @ github (Watch button on Github front page). I don't really want discussion about features or bug issues outside of Github issues, as it would necessitate manual collecting of information etc. and some idea sources (discussion threads) might be forgotten when implementing the feature.

We are using Microsoft Teams for development team internal discussions, but I have also thought about opening more public area for dicussion in our Microsoft Teams. What do you think, would that serve better?

**Comment by tuomas2** [comment]
Google groups emailing list is also 'alive', though not used very actively https://groups.google.com/g/and-bible

**Comment by agrogers** [comment]
Do you think Github is easy enough for the average person to use?

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
is average person willing to participate anyway?

**Comment by tuomas2** [comment]
I think gh is easy enough to most people that are interested in this kind of discussiobs

**Comment by timbze** [comment]
I think a discussion group would be beneficial for users that want a simple way to ask a question or discuss something about And Bible. Creating an issue feels like too big of a deal if someone wants to ask how to highlight, for example.

Pros
- More users would be able to help other users
- I believe more users would get more out of AB, for example, when I show my friends how I use AB they get excited about it :). I think a discussion group like Telegram, etc would work in a similar way.

Cons
- IMO, someone would have to be active in moderating the group -- not a con if someone has the time and is willing to do it :)

There's definitely more of both, but these came to my mind right away. I don't know Matrix personally, though I've heard good stuff about it. But I know Telegram pretty well, and it's very configurable for groups.

**Comment by agrogers** [comment]
Yeah, I tend to agree with Tim.

**Comment by tuomas2** [comment]
Well, we could try, but would someone promise me to collect all good ideas into corresponding Github tickets? :-) So that I don't need to stress about reading every message and doing secretary work (and can concentrate on coding :-D ).

**Comment by tuomas2** [comment]
Telegram is technology that is user-friendly but is it good for this kind of discussion? I'm still more for Microsoft Teams, but is it too difficult to get inside or use it? It's app is somewhat buggy sometimes.

**Comment by thebiblelover7** [comment]
I would personally use Matrix, but Telegram is better than nothing. We could also bridge a Telegram group to a Matrix room so everyone can use what they want.

@tuomas2 Would you like me to make the room?

**Comment by thebiblelover7** [comment]
> Well, we could try, but would someone promise me to collect all good ideas into corresponding Github tickets? :-) So that I don't need to stress about reading every message and doing secretary work (and can concentrate on coding :-D ).

**I promise**

**Comment by tuomas2** [comment]
> > Well, we could try, but would someone promise me to collect all good ideas into corresponding Github tickets? :-) So that I don't need to stress about reading every message and doing secretary work (and can concentrate on coding :-D ).
> 
> **I promise**

ok I'll think about it👍 I'll let you know later. Can you send me email? help.andbible@gmail.com

**Comment by tuomas2** [comment]
discussion still open though ☺️

**Comment by timbze** [comment]
> I would personally use Matrix

@adrielsand what benefits do you see of matrix? Genuinely curious, as I've never tried it myself.

I guess there could even be just a "Fans of And Bible" group or something like that so And Bible developers don't need to take responsibility... Just another idea @tuomas2

**Comment by thebiblelover7** [comment]
> > I would personally use Matrix
> 
> @adrielsand what benefits do you see of matrix? Genuinely curious, as I've never tried it myself.

@timbze I just like its expandability and the features tailored to bigger communities such as open source projects. I liked it a bit better than Telegram.

**Comment by thebiblelover7** [comment]
@tuomas2 I sent you an email

**Comment by agrogers** [comment]
I like the idea of not making it an official And Bible group. The top
pinned post could direct people to Github if they want to communicate
directly with the devs. But i would be happy to do my little bit to support
that community.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
How should we advertise the group? Homepage, Github? 

Should AB user interface have something that advertises this?

**Comment by agrogers** [comment]
Sure, how about at the top (or bottom) of the Help and Tips dialog? Could
add a hyperlink to the group and to Github.

Actually perhaps just to the group - best if multiple people have a chance
at answering any question before it gets to you guys.

**Comment by thebiblelover7** [comment]
@agrogers I like that idea
 
We could put it on the GitHub page and also on the Help and Tips dialog.

**Comment by agrogers** [comment]
Would it be possible to use this forum as a replacement for the OS Ticket system? At present, answers to tickets only help the person who submits them. If there is nothing personal in those ticket submissions, then I would support them going to the public forum.

Also, there is a steady flow of tickets coming into the OS Ticket system. If they went to the forum then it would at least keep the forum looking alive.

**Comment by thebiblelover7** [comment]
@agrogers that's a great idea!

@tuomas2 I sent you another email btw

**Comment by tuomas2** [comment]
Need to think about details carefully. 
1. Crash / bug reports still go to osticket (because its via email) and I guess that's ok.
2. Many people ask questions via main menu -> bug report and that goes anyway to osticket 
3. If it's mainly for Q/A / support / help desk, there are better software for that (similar to stackoverflow) than telegram etc.

**Comment by agrogers** [comment]
Crash reports going to a forum probably does not make sense since no one
but devs could answer them. But any other bug report or support issue could
go to a forum. A prerequisite would be that the forum could handle
submissions by email from non registered users I guess.

**Comment by thebiblelover7** [comment]
@tuomas2 My idea was something like this:

1. Crash/Bug Reports => to GitHub Issues
2. General Questions/Support => Discussion/Support Group

If there is any question that later seems to be a bug, the user should be told to make a bug report, etc.
In my opinion, there shouldn't be any forum, as long as there is a discussion/support group.

Most big open source projects have both a discussion/support group and a forum (Discourse). This is how I've seen that big open source projects function. If you want a fast response, you would go to the discussion/support group. If you don't mind waiting, or it's a big issue that you really think developers should take a look at, you submit it to the forum or to GitHub issues.

What do you think?

**Comment by tuomas2** [comment]
I'm thinking to make item "Questions?" under "Contact" in Main menu which directs to Github wiki page  
https://github.com/AndBible/and-bible/wiki/Support that will then guide user to write question in correct place (whatever we decide; currently only help.andbible@gmail.com). 

Is "Questions?" good and general enough title?

**Comment by tuomas2** [comment]
> Crash reports going to a forum probably does not make sense since no one but devs could answer them. But any other bug report or support issue could go to a forum. A prerequisite would be that the forum could handle submissions by email from non registered users I guess.

Sounds complicated (is there such a software) and problematic otherwise (user does not necessarily know that his message ends up in public forum).

**Comment by agrogers** [comment]
It does sound a little complicated/ The devil is always in the details.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by thebiblelover7** [comment]
> I'm thinking to make item "Questions?" under "Contact" in Main menu which directs to Github wiki page
> https://github.com/AndBible/and-bible/wiki/Support that will then guide user to write question in correct place (whatever we decide; currently only [help.andbible@gmail.com](mailto:help.andbible@gmail.com)).
> 
> Is "Questions?" good and general enough title?

@tuomas2 It does sound a bit confusing but I don't know any better

Maybe instead of redirecting the user to the github wiki, you could put it in the app directly. It makes it a bit simpler for the user.

**Comment by tuomas2** [comment]
options: Have questions? Need help?

wiki page preferrably so we can change it easily

**Comment by tuomas2** [comment]
and this is english only. in app content is translated

**Comment by thebiblelover7** [comment]
> options: Have questions? Need help?
> 
> wiki page preferrably so we can change it easily

Makes sense. I'll be waiting for an answer :).

**Comment by thebiblelover7** [comment]
@tuomas2 So, any news about this?

**Comment by tuomas2** [comment]
I'll try to make something out of this before the release. "Questions?" item already added in Beta. I'll let you know.

**Comment by thebiblelover7** [comment]
Perfect, thanks for this, @tuomas2 !

**Comment by tuomas2** [comment]
I created telegram group now. Feel free to come and test.

https://t.me/andbible

**Comment by tuomas2** [comment]
Mentioned it also here: https://github.com/AndBible/and-bible/wiki/Support (page which is linked via main menu -> questions?)

**Comment by tuomas2** [comment]
Telegram + Matrix implemented. Let's try.
