### ISSUE TITLE
Enable speaking of the 'All References' window

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1194]
I tried to 'speak' the all references window (bottom) but the Speak option in the hamburger menu was disabled.
However I could speak the TSK window (middle) which sounded particularly weird :)
Can we enable speak on windows that show all references?

![image](https://user-images.githubusercontent.com/13920678/123502301-b973b480-d68e-11eb-87dc-bd07f9b49782.png)

**Comment by tuomas2** [comment]
Can go to wishing well, but not in 3.4 :-)

**Comment by tuomas2** [comment]
Covered by #1355
