### ISSUE TITLE
What is the difference between the labels lists?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1197]
List 1: Hamburger menu > Manage Labels (called Manage Labels - missing favourite column)
List 2: ... menu (top right) > Label settings (called Auto assign & Favourites)

In List 1, it is still possible to set the Auto-assign and Favourite values by editing the label. I assume this applies just to the current workspace. Is that correct?

If it does, then it's functionality is identical to List 2 except that it is missing some columns and is called a different name.

I suspect List 1 should have the 'This workspace' settings hidden when editing a label.
Or, we can remove one of these lists - or make them identical. At present it is a little confusing.

**Comment by tuomas2** [comment]
The original semantics has been that main menu is for "global" things, and 3-dot options menu is for per-workspace things. But there are exceptions. And now it is possible to set  per-workspace things also from manage labels. But indeed we can question the existence of "Manage labels" by now.

**Comment by agrogers** [comment]
OK, i might  have a look at this and see if there is a good way to manage it. If i can think of something i will share it.
