### ISSUE TITLE
Set Bible version for multiple references window 

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1198]
~~Currently there is no way to set which Bible version should be used when clicking "Open all references"~~
EDIT: #1521 addressed this somewhat. It's still not possible to change "multiple references" version after opening (what this issue is about), but it now works to set "Link window" version, and then multiple references are always opened in the last set version.

When the links window opens a different version than what I want to see (single verse or passage), I can simply select another version and then next time it opens the version I want. 

~~Here's my use case. NASB has more cross references, but when clicking "Open all references" in the middle window, it will always open the verses in NASB. Yet I would like to open the verses in KJV. I think it should either remember the last Bible version that was open in the window and use that version, or I be able to set the version some other way.~~ [See edit above]

![Screenshot_20210626-072350.png](https://user-images.githubusercontent.com/35117769/123515469-bd82e080-d654-11eb-8fea-d5520ead7b1e.png)

**Comment by agrogers** [comment]
Yeah, I have never really understood how it determines which version to
use. Most times i get what i want. But every now and then i get something i
didnt expect.

I have thought that we might need a 'preferred' or 'default' translation
that would always be used for this purpose.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Similar logic as when you click a link. I can check the code and give the exact logic when I have time, and we can think if we could improve that somehow.

**Comment by agrogers** [comment]
Great. I'm not sure what the link logic is either 😁

**Comment by tuomas2** [comment]
Okay, current logic is as follows:
1. If link defines module to be used, use it (rarely does but can)
2. If this is a link opened in links window and if links window has bible document set (meaning, it has been used for bible doc), use that. This is the bible document that was used last time in this window. 
3. Use active window's bible document, if it is set. (similarly as (2))
4. Use first bible document

**Comment by timbze** [comment]
> Okay, current logic is as follows:

"Multiple references" windows uses this logic? Then I guess it's different from Bible version logic in links window, because tapping the single Bible link in middle window in my screenshot I can open reference in KJV if that was open last in links window, but it's impossible to open KJV when clicking "Open all references"

**Comment by tuomas2** [comment]
I was essentially explaining what `net.bible.android.control.page.window.WindowControl#defaultBibleDoc` does. 

openMulti -> getBookAndKey -> getBibleKey -> defaultBibleDoc

**Comment by agrogers** [comment]
Oh, I didn't realise I could just change the Bible used in the links window
and it would remember that :)

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by timbze** [comment]
I wish we could bump this to high priority so that someone else would do it 😄

**Comment by tuomas2** [comment]
Why higher prio? We have workaround for you, and we don't have UI planned for "better" solution yet, so I would keep it after 4.0.

**Comment by timbze** [comment]
I'm guessing NASB and ESV cross references define which module to be used (i.e. NASB and ESV respectively).

Because opening the single link or "all references" opens in the same version (ESV from ESV and NASB from NASB) every time even when I change the special window to another version.

So not sure what you mean with work around, but the only way I can see cross references in another version is to click the single links and then change version each time after clicking link. Maybe that's sufficient "work around" for now. "All references" can not be opened in another version at all
