### ISSUE TITLE
Proposal for new window and '...' menu presentation

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1199]
I was at a party tonight and was telling my mate who makes Adobe After Effects videos about And Bible. He hadn't used it for three years. So he installed it and I watched him use it... and get lost and confused. It was quite enlightening!

There were a few smaller usability problems that I will raise in other issues. But the biggest issue/surprise was that he just kept going back to the '...' button in the top right corner. That surprised me because I hardly ever use that menu. But he felt that was the most intuitive place to go to manipulate what was going on in the Bible windows. And I can see where he is coming from.

A few comments.
1. It is presently really hard to tell what options in the '...' menu affect the window, the workspace or the application. 
2. He kept trying to change window based settings through the '...' menu which does in fact affect the current window occasionally and sometimes affects new windows. He would also turn off workspace Pinning thinking he was turning off pinning for the current window
3. This mostly came from believing that the '...' menu applied to the active window - it is not clear that it doesn't.
4. Some settings are accessible even when they don't apply to the current window (ie strongs numbers on a Bible that doesn't have strongs numbers, hide footnotes when looking at a commentary etc)
5. The window button pop-out menu links to another pop-out menu which then links to other menus. I have always found the two pop out menus awkward.

And here are a few comments on the screenshot below:
1. First objective was to eliminate the double pop-out menu. Now both menus plus more can fit on the one dialog.
2. Darkening the non-active windows makes it really clear what window the changes are being applied to.
3. The ... button can now also be used to manipulate the active window. This has the added advantage that if the window buttons are hidden, the menu can still be accessed without the need of long pressing on the window button bar at the bottom.
4. It clearly describes which settings apply to which areas. I had to play with all of them to work it out myself. Still not sure that I have it right :)
5. The menus remove the options that are not relevant to that particular active window
6. It renames a few options for clarity
7. There is space to add additional actions if we wanted. 
8. Presently there are workspace settings that can only be accessed from the current '...' menu. I think they need to be added to the Workspace > Settings menu

![AndBible Suggestions-overhaul of window menus](https://user-images.githubusercontent.com/13920678/123515326-5445b080-d6da-11eb-8df0-7b95d9fd6948.png)

**Comment by agrogers** [comment]
I should have added, my feeling is that it is not a good idea to have the workspace settings accessible directly through the '...'.  These settings mirror the window settings in many ways and so it is, as my friend found, easy to get confused. Plus I think workspace settings are generally set up once and then left alone. They don't need to be so easily accessed.

The same argument could be made for the 'Font family' option. How many times do users change that? For me it is mostly never. So I don't see why it should be so easily accessible. It may be desireable to have it there if it helps the user discover what the app can do. But other than that, i think options that are rarely used should be rarely seen.

**Comment by tuomas2** [comment]
Is there some library etc to make such beautiful menus? I'm afraid this is rather difficult to implement (would be simple in js-side, but this can't be I guess). But beautiful...

**Comment by agrogers** [comment]
After using AB I just assume you guys can do anything 😏 But I did wondered if this sort of menu would be possible. Am I right in thinking that menus that can span multiple windows are not done in java but use standard android controls?

**Comment by agrogers** [comment]
Is this helpful?
https://medium.com/@prakharsrivastava_219/creating-custom-menu-in-android-part-1-3-menu-design-b51a13a7d018

**Comment by tuomas2** [comment]
> After using AB I just assume you guys can do anything  But I did wondered if this sort of menu would be possible. Am I right in thinking that menus that can span multiple windows are not done in java but use standard android controls?

Current standard android popup / options menus can span multiple windows. JS-side we can do anything fancy but it does not span windows.

> Is this helpful?

No, I'm afraid.

**Comment by tuomas2** [comment]
You could, however, wish some icons to 3-dot workspace menu (otherwise looking as now).

**Comment by tuomas2** [comment]
SVG path for those would help a great deal

**Comment by agrogers** [comment]
Thanks for the info. And Sure, I will work on some icons. But can't get to
it until Saturday.

**Comment by tuomas2** [comment]
Icons are not in a hurry, no problem :-)

**Comment by agrogers** [comment]
Hi Tuomas. Here is a revised version of the menu above that we couldn't do because of the window set up. This new one uses the same sort of drawer that you have already got on the main menu. You would know all the following much better than me but it seems like its possible to:

1. Slide the drawer from the right side.
https://stackoverflow.com/questions/18547277/how-to-set-navigation-drawer-to-be-opened-from-right-to-left

2. Configure the drawer however we like - multiple columns and icons and text
https://github.com/goodlifechris/Navigation-Drawer-Menu
https://stackoverflow.com/questions/29469041/is-it-possible-to-have-android-navigation-drawer-with-grid-view-i-e-grid-view-i
https://stackoverflow.com/questions/29448049/my-drawerlayout-gridview-display-like-list-view

Using this approach also means there is even more room to show additional settings that are hidden further down in the menus.

![AndBible Suggestions-window menu using navigation drawer](https://user-images.githubusercontent.com/13920678/124126815-6484d380-dabe-11eb-9763-c61e1e72db41.png)

**Comment by tuomas2** [comment]
In 3.4 I'm not going to revise these menus but I'll see if I can utilize icons you have selected. 
Also I'm not yet desided if I like the suggested UX. 
Current UX kind of hides "excessive" options. Now they jump to the user eyes, which might feel distractive.

**Comment by timbze** [comment]
Agree this should be after 3.4

I like the idea though, but am sure it could be tweaked. For example, possibly always show the same 6, or 9 (or whatever number of) icons, plus a "more" icon to show the rest of settings. And then there could be a "Recent settings" option under the main some icons that would show recently used settings.

I mention having the main 6 or whatever number of icons, because it can be confusing when the menu list changes every time

**Comment by agrogers** [comment]
Yeah, I agree that the number of options could be over powering. Although having pictures makes it easier to follow. Is a single menu with all the important options more usable then menus inside menus? 

I did reduce the number of workspace icons from 13 down to 6 (or 3 depending how you count :) 
My problem with those was that many of the Workspace options are identical to the Window options and so can be confused when they are accessed on the same screen. I dont think people change them very often so it shouldn't hurt. And also labelling the groups clearly in the quick access menu.

Perhaps most of these ideas can be accommodated in the present popup menus...

**Comment by tuomas2** [comment]
Icons are handled in #1220 so moving this again from away from 3.4

**Comment by agrogers** [comment]
I still like this layout. I didn't realise until recently that it is a bit like the MyBible menu. Theirs is a little too compact. But I am not sure this is one we want to pursue anymore so I might close it. If anyone disagrees, feel free to open it again.
