### ISSUE TITLE
+ (plus) icon shows in toolbar in activities where it should not

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1200]
**Describe the bug**
- [x] "+" icon shows in find results screen toolbar, but it shouldn't
- [x] also shows in book chooser for KJV 1769 with Strongs Numbers and Morphology (Crosswire)

Bug **did not exist** in 528.5 b3e3f88e

**Bug was found on And Bible version**
Build 529.1

**Screenshots**
![image](https://user-images.githubusercontent.com/35117769/123524006-cb505a00-d684-11eb-86d2-669e1133f5ed.png)

**Comment by bvahedy** [comment]
Timmy,
It seems that this only happen with the kjv 1769 module I can't dupplicate
it with other modules. But I agree that it should not be there.

Ben

**Comment by tuomas2** [comment]
Interesting. Must be very old bug. Is it related to the fact that apocrypha is toggled in bible book selector with this button? How come this button has travelled to other activities too?

**Comment by tuomas2** [comment]
This is not a bug. It shows results from apogrypha if you press "+". I think the idea has been that results from apocrypha are not wanted to be mixed up with Bible results.

**Comment by tuomas2** [comment]
Same in bible book chooser

**Comment by timbze** [comment]
KJV does not have apocrypha (KJVA does)

Also why did it just start happening after 528.5?

I'm wondering if #1122 or #1171 caused this, but have not been able to test that yet

**Comment by tuomas2** [comment]
I was trying this with KJVA. Could this be misconfiguration of the KJV module (if it does not show up with other modules)
