### ISSUE TITLE
Disabled chapter swipe when bookmark modal is active... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1201]
When a bookmark modal is open, swiping  to the right or left should not change the chapter you are in. In some cases not everything fits within the model and trying to move things inside the modal just to make them visible causes a chapter change and the modal closes.

Expected result:
Disabled chapter swipe when a modal is open and active.

**Comment by agrogers** [comment]
Good idea. This is related to #1183 also.

**Comment by timbze** [comment]
Swiping in note text has same issue, but I guess when this issue is fixed this will be fixed too. 

https://user-images.githubusercontent.com/35117769/124356889-e4ea2800-dbd5-11eb-94a5-d6915bb60327.mp4

**Comment by tuomas2** [comment]
I believe this has been fixed.
