### ISSUE TITLE
Should the focus change to the Link window when a link is pressed?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1203]
Current:

1. When I click a link (bible reference or Strongs number) the Link window is updated and it also receives focus.
2. If I immediately try and change the bible reference the Link window is changed, not the window I was using.

Expected:

1. The window that I clicked in would keep the focus.

My friend had problems with the existing functionality the other night. I have a feeling that this is why I also sometimes manipulate the wrong window.

**Comment by bvahedy** [comment]
are you proposing that a link window should not be given the option to be
manipulated from the top menu bar?

**Comment by agrogers** [comment]
No, it should function exactly as it is. Only change is to not get focus
when a link is clicked.

**Comment by bvahedy** [comment]
Ok, but if you try to scroll up in the link window it will gain the focus
which happens more often than not on devices with a smaller screen.

**Comment by agrogers** [comment]
Sorry, I wasn't very clear in my first post.

It's fine for the Link window to receive the focus if you click on it or
scroll in it.

My suggestion was that focus should not automatically transfer to the Link
window *after* a link is clicked in a normal window. I think the focus
should always stay with the particular window the user clicks/scrolls in.

Is that clearer?
___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment]
Ok, I see what you mean now.

**Comment by tuomas2** [comment]
I'm not sure. We could perhaps give it a try.

**Comment by tuomas2** [comment]
Changed the behavior. Let's see if we like it more.
