### ISSUE TITLE
Provide a button to download the Morphological document

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1206]
This dialog will appear if the document does not exist. The user then needs to go off and find the document and download it - which is a little hard for new users.

Solution:
- Ask if the user wants to download that document immediately
- If they say yes, download the document
- I would propose downloading it in the foreground - make the user wait for it - it doesnt take too long.
- Then activate it and show the results they expected to see.

![image](https://user-images.githubusercontent.com/13920678/123577732-bfe16800-d817-11eb-9b19-d6182c0b4c01.png)

**Comment by tuomas2** [comment]
Or at least button to go to download screens. "Go to downloads".. And module id should be given in addition to name.

**Comment by agrogers** [comment]
Yes, that would be a good starting point.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
done
