### ISSUE TITLE
Add a Save button to the Edit label form (and perhaps other forms)

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1207]
A new user can get confused when adding a label.
1. They push the Add button to enter the details of a new label
2. They then have the choice of deleting is (trash can) or pushing the back button (arrow)
3. The arrow doesn't feel like a save button and it is unclear whether the user should be looking for a save button to push.

Proposal:
1. Add a Save button (disk) next to the delete button
2. That button saves the record
3. Maybe the arrow works like a cancel, undoing the changes. Or it just continues doing the same it is 

Perhaps this should apply to other dialogs as well.

![image](https://user-images.githubusercontent.com/13920678/123577946-1d75b480-d818-11eb-94f5-d8f5e726b7f7.png)

**Comment by bvahedy** [comment]
May be we should put the word save like on other screens at the buttom
right hand corner. I know a few people with fat fingers who are always
complaining that their fingers pushed the wrong icon.

**Comment by agrogers** [comment]
Yeah, that would be good too. Although sometimes i cant see the buttons at
the bottom because the onscreen keyboard hides it. We should be consistent
across dialogs.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment]
That's true, a lot of times the virtual keyboard covers that portion. I
guess as long as there is a healthy gap between the trash icon and the save
icon, it would work putting them next to each other, but I still think
users will complain about hitting the wrong icon.

**Comment by tuomas2** [comment]
I kind of like the current simplistic behavior. It's simple and I think it follows the pattern used in full screen activities, that is familiar to users -- all things he does are immediately in effect. If you go to "application preferences" screen, there has never been "save" button. User quickly figures out that if there's no "save" button, it means that changes are saved immediately. 

If we add back "Save" button, we need also "Cancel" button, and should "back" button then be "save" or "cancel"?

> Yeah, that would be good too. Although sometimes i cant see the buttons at the bottom because the onscreen keyboard hides it. We should be consistent across dialogs.

Should not be a problem, as we can let Android to resize this kind of activities when on screen keyboard pops up.

**Comment by agrogers** [comment]
I tend to agree with all the points raised so far. It probably depends on
which apps people are familiar with. Google Calendar has an X and a 'Save'
button at the top. MS Outlook has an X and a tick. Google Tasks has a
'Save'. GitHub has a back and a Send button. Hmm, they all have save
buttons. But I am sure i have used apps with just a back button.

Actually, if the back arrow was simply changed to a Tick then it would be
very clear what is happening and also that there is no cancel option. But
it seems the convention is to put the Save button top right and Cancel top
left. Not sure where the Delete button is. Oh, there is no delete button
when you are creating a new record.

Anyhow, I am fine either way. Just raising the question.






___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
