### ISSUE TITLE
Add "Need help?" menu item

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1219]
Related to #1191

**Comment by agrogers** [comment]
Tuomas suggested this icon. Does it convey the idea that users can actually call us and speak in person? 

![image](https://user-images.githubusercontent.com/13920678/124911558-3b20f600-e030-11eb-8fc6-9f9c0ad08703.png)

**Comment by agrogers** [comment]
Maybe this:
![image](https://user-images.githubusercontent.com/13920678/124911795-8509dc00-e030-11eb-8065-e58eede53745.png)

**Comment by agrogers** [comment]
Or 
![image](https://user-images.githubusercontent.com/13920678/124911885-9f43ba00-e030-11eb-8ee6-2c3a6e878003.png)

**Comment by agrogers** [comment]
Or 
![image](https://user-images.githubusercontent.com/13920678/124911967-b682a780-e030-11eb-80dc-cab5d08c30af.png)

**Comment by agrogers** [comment]
Or this if we are providing email/helpdesk support?
![image](https://user-images.githubusercontent.com/13920678/124912100-e5991900-e030-11eb-9f55-847e4d6b4c96.png)

**Comment by tuomas2** [comment]
> Or
> ![image](https://user-images.githubusercontent.com/13920678/124911967-b682a780-e030-11eb-80dc-cab5d08c30af.png)

Maybe this. I'll add to #1220
