### ISSUE TITLE
Create new videos for 4.0

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1221]
Videos are created in co-operation with @agrogers 

Currently following videos are linked directly from app:

```
const val textDisplaySettingsVideo = "https://youtu.be/rz0zyEK9qBk"
const val pinningHelpVideo = "https://youtu.be/27b1g-D3ibA"
const val bookmarksMyNotesVideo = "https://www.youtube.com/watch?v=ZpZ25uqR_BY&t=90s" // beta 3.4 video
const val studyPadsVideo = "https://www.youtube.com/watch?v=ZpZ25uqR_BY&t=652s" // beta 3.4 video
const val workspacesVideo = "https://youtu.be/rz0zyEK9qBk"
const val beta34introVideo = "https://www.youtube.com/watch?v=ZpZ25uqR_BY" // For 3.4 beta intro
const val speakHelpVideo = "https://youtu.be/_wWnS-pjv2A"
const val automaticSpeakBookmarkingVideo = "https://www.youtube.com/watch?v=1HFXLeTERcs"

```

(in CommonUtils.kt)

We need
 - Intro video to all new features (short intro to each feature) (can be similar long one like beta video or series of videos)
 - Shorter promo video
 - Some longer in-depth tutorials of new features?
 - Replacement to old crappy tutorials?
 - Anything else?

It would be great if someone with greater audience would make a review video of our app update. Any ideas how to make that happen? 

This is pending several UI-related issues:

- #1220
- #1219
- #1187
- #1163

**Comment by agrogers** [comment]
Thanks for that info Tuomas. I need to get cracking on that.

Re someone with greater audience, that's a good idea but not sure where to
start.  Maybe we could find guys who review software like
https://www.youtube.com/watch?v=-wHl0MfAIBk
https://www.youtube.com/watch?v=i4JeCxH74BM
https://www.youtube.com/watch?v=qnKi7TmhomQ

Not a lot of subscribers but could get the word out to thousands more than
normal.


___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Sometimes I have also seen some high profile preachers are praising some app on their youtube channel and that makes definately also impact on their listeners. I don't know though how we get this app into their hands.. :-P

**Comment by tuomas2** [comment]
I think we are now ready for videos (ui-wise), aren't we?

**Comment by tuomas2** [comment]
Okay it would be great to get new app logo in place before recording. #1227

**Comment by agrogers** [comment]
Yes, I have been working on them. Making slow progress but hoping to speed
it up. And yes, will need the logo before I finish.

**Comment by tuomas2** [comment]
No hurry, just wanted to check if there is any blockers.

**Comment by agrogers** [comment]
Got most of these done now.
