### ISSUE TITLE
"Add on" modules to change / manipulate css to all / some installed modules.

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1222]
As a future feature request, we could actually have "add on" css modules that implement something custom to all installed modules.

_Originally posted by @tuomas2 in https://github.com/AndBible/and-bible/issues/1176#issuecomment-872418045_

**Comment by agrogers** [comment]
Yeah, that would be great. I have coveted some of the layouts I have seen you boys showing off on more than a few occasions.

I wonder if there is a case to link that to a window or workspace configuration. Are they usually connected?

Perhaps the addons should allow exporting and importing workspace configs too :)

**Comment by tuomas2** [comment]
Implemented. Try it out (earliest version 539) by installing StyleExample add-on module from beta repository.

**Comment by tuomas2** [comment]
Updated documentation https://github.com/AndBible/and-bible/wiki/Custom-CSS-for-modules-for-And-Bible

**Comment by timbze** [comment]
Does this feature apply only to documents or also to other js-side styles like modals etc? Not that it really matters to me, just wondering if this would provide a work-around for #1418 at all

**Comment by tuomas2** [comment]
With css you can style anything displayed in webview

**Comment by tuomas2** [comment]
#1418 is in-app editor that produces these modules.

**Comment by agrogers** [comment]
Wow, I look forward to trying this.
