### ISSUE TITLE
Some logo ideas

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1227]
Re #1220, here are some ideas I came up with today. My feeling about the current logo is:
- It doesn't easily convey in the Play Store what it is (see below for icons used for Bible programs in the store)
- I remember when it was changed in order to make it more safe for those installing in a persecuted region. I think that still should be considered. But maybe there are other ways for them to conceal the app?
- Most icons in the play store have text saying what the app is/does. I think that is probably something we should add.
- Gradients are out these days. Flat colors are in.
- Simple icons/logos are also in.
- Lot's of books in the Play Store. Probably a good idea since this is a Bible.
- But that doesn't make it stand out - our current icon is very different to others which I think is good.
- It's not easy (for me) to include the fish in a significantly different design and keep the design simple.
- I probably prefer a light background over a dark one. But that changes the icon too much I think.
- I quite like the abstract one below. But probably too abstract.
- I also quite like the idea of a colourful icon since it helps convey the colourful labeling system that And Bible now has.
- I also quite like including 'THE' in the name 'The Study Bible'. I do think it is the best out there - 'the' conveys that well in English.

![And Bible Logo Ideas](https://user-images.githubusercontent.com/13920678/124346292-57342a00-dc21-11eb-923c-340e1c5608de.png)

Some extra ideas...

![And Bible Logo Ideas Extra](https://user-images.githubusercontent.com/13920678/124345970-83e74200-dc1f-11eb-8db7-cbc7403717ee.png)

And many of the logos from the app store...

![Untitled-1](https://user-images.githubusercontent.com/13920678/124345973-86e23280-dc1f-11eb-9551-d8d4b0041387.png)

**Comment by tuomas2** [comment]
Very cool ideas! Maybe we could have logo with "The Study Bible" text in Play Store (and F-droid etc) but keep the app logo without the text if including the name is not a good idea in persecuted country. Although I wonder if the authorities also recognize fish symbol if they are seriously looking for religious material.

My favourites are 

![Screenshot_20210703-101443_Chrome](https://user-images.githubusercontent.com/5811789/124346450-8c238b00-dbe7-11eb-86d8-c31dde79beee.jpg)

**Comment by agrogers** [comment]
Is it possible to add an option in the app to change the icon **after** it has been installed? Then they could change the icon to a very generic book without words and also change the title of the app from 'Study Bible' to something else.

**Comment by tuomas2** [comment]
I can check, but no new strings should be added for such an option any more... I think I have seen some app doing that, but it's not anything very conventional.

**Comment by tuomas2** [comment]
those colorful rainbow versions give a bit wrong association at least to me... 🤔

**Comment by agrogers** [comment]
Yes, me too :) That's why I made some different ones. And some slight variations (improvements) on the ones you preferred.  

I just realised too that the icon shown on the play store is probably different to the icon on the desktop - the later doesn't have words - they are all under the icon. I have tried to show both below.

![And Bible Logo Ideas Refined](https://user-images.githubusercontent.com/13920678/124352000-09c7b500-dc41-11eb-8708-ed0720e8f485.png)

**Comment by tuomas2** [comment]
I'd like to hear other's opinions too. 

I'm not sure if we need to highlight the colorful highlighting feature in logo though. I guess many bible apps have some sort of highlighting anyway, so it does not make such a big difference? I think features on top of highlighting are more important (my notes, study pads etc).

**Comment by tuomas2** [comment]
Word "the" goes very small in some of the samples above

**Comment by agrogers** [comment]
Yes, I agree with those comments. Just trying to justify adding some color
to the logo😁

I installed a few on my system this evening. They look very different on
the home screen to how they look in large form above. Simple is good for
the home screen.

**Comment by bvahedy** [comment]
Since I live in a persecuted nation, I think we need to be sensitive to
what is on an icons.
For example, Picture yourself on a train in China, you are sitting down
with ten Chinese men around you standing because there are no seats
available and you are reading your Bible, all atheists and godless know all
the symbols associated with Christianity and Judaism. They know the fish is
a Christian symbol just as they know the Star of David is a Jewish symbol.
For that reason I opt for icons that are non religious.
 We could have an app settings for "persecuted nations", turning that on
will switch all icons to non religious or something to that effect.

**Comment by agrogers** [comment]
Hi Ben

Could you clarify a little where the concern lies.
- Is it someone seeing the icon on the home screen when you are casually
finding some other app?
- Or would you never use the app in a public place?
- Is it when you are actually using the app and others could see the little
Bible icons used to identify Bible translations?
- Is it someone taking and searching your phone for compromising material?
- Or perhaps during installation?
- Or something else?

**Comment by agrogers** [comment]
Tuomas, maybe this allows changing of the app icon dynamically:

https://github.com/simonchius/DynamicLauncherIcon

**Comment by bvahedy** [comment]
Andrew,

Yes, people in persecuted regions usually use vpn to download the app. So
it doesn't matter what the icon is on the Google play store.
But having a Christian fish icon on your home screen when you are in a
public place endangers their lives. Also some of the icons with the cross
or a fish in the app is an issue. I know some will say that christians need
to be bold and not afraid of what they believe, many are imprisoned and
beaten and even killed for what they believe. I know persecution can not be
avoided as believers but we are not here to tell others to put their lives
in danger because we think they should be bold, that is for God and them to
decide.

I usually provide a version of Andbible app in a separate website with all
the icons changed for those who have this issue.

Ben

**Comment by agrogers** [comment]
Thanks for the info Ben. I think I would like to add a mention in our promo video to the fact that And Bible doesn't communicate with any servers that might put users at
risk without explicit permission from the user. This is a good feature.

Perhaps one day it might be possible to have a 'Covert App' setting that
changes any sensitive data and always warns when downloading documents. The
app icon is one thing. App name is another. Bible icon in the app is a
third. Are there other icons?

**Comment by bvahedy** [comment]
True that no user information is passed to any organization through
Andbible app.

The speak feature creates the fish icon in the notification panel. Also in
the edit note the icon for creating a link has a cross icon.

**Comment by bvahedy** [comment]
Andrew,
Current users that use our app in these hostile counties:

1664  in Russia
823 in India
224 in Nigeria
181 in Indonesia
90 in Kenya
81 in Turkey
68 Egypt
66 Malaysia
40 in Pakistan
27 in Zimbabwe
24 in Uganda
22 in united Arab Emirates
18 in Saudi Arabia
17 in Iran
14 in China (I'm sure there are more from here)
7 in Kuwait
6 in Bahrain
329 known region

The Muslim nations and China are the worst offenders.

**Comment by tuomas2** [comment]
In many bad muslim countries however you can be christian as lond as you don't speak about it (try to convert others). So it might not be as bad as we think with respect to our app. 

4.0 will not be having improvement with respect to persecuted countries, but I'm in agreement that we should not make it worse either. In 4.1+ we can consider improvements too.

**Comment by tuomas2** [comment]
In summary: I'm okay with having word "bible" or christian symbols there in 4.0 logos and graphics. App icon (in app drawer) should probably be icon only in any case (because text will be too small).

**Comment by bvahedy** [comment]
Well, they have waited till 4.0, I guess they can wait a bit longer.
I don't think Christians go looking for problems in Muslim countries nor do
Jews, yet because Islam teaches world domination it causes some fanatic
Muslims to persecute people of other faith. I lived in a Muslim nation for
20 years, it only takes one idiot to cause a lot of problems.

Every day, 13 Christians worldwide are killed because of their faith.

Every day, 12 churches or Christian buildings are attacked.

And every day, 12 Christians are unjustly arrested or imprisoned, and
another 5 are abducted...

https://www.christianitytoday.com/news/2021/january/christian-persecution-2021-countries-open-doors-watch-list.html

**Comment by agrogers** [comment]
Perhaps we could provide some links/info to tools that allow users to
change the icon and name.

   - Nova launcher makes it pretty easy it seems.
   - Shortcut Maker allows you to create a shortcut and new name for any
   app. They could potentially then delete the original icon
   - I wonder whether we could add a new 1x1 widget which is just another
   icon with another name. They then hide the original app icon as best they
   can.

You guys might know some others as well...
Andrew

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by agrogers** [comment]
https://www.androidtipsandhacks.com/android/change-app-icons-android-phone/

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
If we want something a bit different, these could also be considered. (of course anything can be considered). I kind of like the fact that there's the familiar fish symbol but the logo is still completely new.

![image](https://user-images.githubusercontent.com/5811789/124799098-d9dc2280-df5c-11eb-9101-4fdc5f1cfd71.png)

**Comment by tuomas2** [comment]
> If we want something a bit different, these could also be considered. (of course anything can be considered). I kind of like the fact that there's the familiar fish symbol but the logo is still completely new.
> 
> ![image](https://user-images.githubusercontent.com/5811789/124799098-d9dc2280-df5c-11eb-9101-4fdc5f1cfd71.png)

My wife suggests the right circled one, but colors such that we have "original colors" (black background and yellowish fish) on the displayed page. That would even ephasize the effect of having something old on something new.

**Comment by tuomas2** [comment]
@agrogers what are your favourites?

**Comment by agrogers** [comment]
There are a few that I like. I actually quite like the book ones your wife chose. She has good taste :) Below are icons on an actual home screen of different darknesses. 

I think I like the one on the bottom right the most (blue book).  The transparent background is cool. But some launchers will put a background under it. 

Then I probably like the circle or square representation of the original icon. I don't like the text on it. The fish, tail to tail in a circle is cool - maybe good for persecuted regions.  Although the fish standing on its tail in the book and now much smaller is more covert.

The gray book is a bit, um, gray... and boring. The actual bible is roughly done, looks like the other bible apps and is a bit old school now.

![And Bible Logo Ideas Home Screen Dark](https://user-images.githubusercontent.com/13920678/124869814-17948600-e005-11eb-979f-a5cf6650308b.png)
![And Bible Logo Ideas Home Screen Light](https://user-images.githubusercontent.com/13920678/124869842-224f1b00-e005-11eb-96b2-3d94f9f6f629.png)
![And Bible Logo Ideas Home Screen](https://user-images.githubusercontent.com/13920678/124869855-2844fc00-e005-11eb-80e0-7ac7853b10eb.png)

**Comment by tuomas2** [comment]
This one is really nice... 
![image](https://user-images.githubusercontent.com/5811789/125280278-86335580-e31d-11eb-9912-f687661efb4a.png)
I also think this is okay also on dark background.

But on the other hand, dark pages are not very natural. Not many books have black / dark pages :-P Maybe it does not matter though.

**Comment by agrogers** [comment]
I like that one too. I like this one more. Maybe different colours? 
![IMG_20210712_220010.jpg](https://user-images.githubusercontent.com/13920678/125284506-dbdb2280-e35c-11eb-9612-53850770852e.jpg)

**Comment by tuomas2** [comment]
Can you give svg, I'd like to try a little

**Comment by timbze** [comment]
> This one is really nice...
> ![image](https://user-images.githubusercontent.com/5811789/125280278-86335580-e31d-11eb-9912-f687661efb4a.png)

That's also one of my favorites. For some reason the colored ones are not so appealing to me.

**Comment by agrogers** [comment]
You guys love gray 🤓 It's like you are developing for a kindle 😉

Re svg, sure but not till Friday sorry. I can find you the original image I
manipulated tomorrow though. You can fiddle with that.

**Comment by tuomas2** [comment]
I believe can vectorize it with inkscape if you send png

**Comment by agrogers** [comment]
You have everything I have at the moment. My computer is in another city
and I forgot to backup to one drive.

**Comment by agrogers** [comment]
Perhaps we could do a poll and see what the user like? Might be a good way to start to generate interest for the next release. Could we send an email to everyone who has contacted us through the OSticket system?

**Comment by Dleemuse** [comment]
I think it is a good idea to somehow allow users to have a logo that does NOT use any religious symbols or the word Bible.

I work for Christ's Evangelical Foundation, an International Correspondence Bible College, which offers a free, fully funded 4-year scholarship to all who meet the application requirements. I have recently been telling students who have a smart phone about AB. In some of the places where our students live, they are under daily threat of being arrested & detained for being a Christian. It would be nice for them to have the option of an ambiguous logo.

We hear from some of our students that they & their families are on the run, fleeing for their very lives & escaping with only the clothes on their back & their CEF books. I believe there may be some of them who have lost their lives, as some we do not hear from again. It is very sad, but even in the teribble persecution they live under, they are determined to study & learn God's will, & AB as one of our graduates termed it, "Bible Study Made Easy," is a great tool to help them do so. 

Just some thoughts. 

Thank you, 

Debra

**Comment by agrogers** [comment]
Hi Debra

Thanks for your thoughts. I am working on some functionality to allow the
user to choose an icon. I believe its possible - not sure that it is
possible for me though :) It wont get into the next release I dont think
but I think it could be in a minor release soon after that. So I will do
what I can to make this functionality available.

In the meantime there are some workarounds that users can implement. They
are mentioned here
https://github.com/AndBible/and-bible/issues/1227#issuecomment-873737550
Perhaps that is a good interim solution.

Andrew

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by Dleemuse** [comment]
Thank you Andrew! 

Sent from Yahoo Mail on Android 
 
  On Fri, Jul 23, 2021 at 9:11 AM, Andrew ***@***.***> wrote:   

Hi Debra

Thanks for your thoughts. I am working on some functionality to allow the
user to choose an icon. I believe its possible - not sure that it is
possible for me though :) It wont get into the next release I dont think
but I think it could be in a minor release soon after that. So I will do
what I can to make this functionality available.

In the meantime there are some workarounds that users can implement. They
are mentioned here
https://github.com/AndBible/and-bible/issues/1227#issuecomment-873737550
Perhaps that is a good interim solution.

Andrew

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
> I like that one too. I like this one more. Maybe different colours?
> ![IMG_20210712_220010.jpg](https://user-images.githubusercontent.com/13920678/125284506-dbdb2280-e35c-11eb-9612-53850770852e.jpg)

Can you send me svg of this and the colorless variant?

**Comment by Dleemuse** [comment]
I really like this one! 
Debra

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 3, 2021 at 7:34 AM, Tuomas ***@***.***> wrote:   



I like that one too. I like this one more. Maybe different colours?



Can you send me svg of this and the colorless variant?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by agrogers** [comment]
Sure. On Friday when I get back home.

**Comment by tuomas2** [comment]
New logo in use 
![Screenshot_20210812_152812](https://user-images.githubusercontent.com/5811789/129196786-25e41546-d06c-4216-97e6-932b9e952aab.png)
![Screenshot_20210812_152807](https://user-images.githubusercontent.com/5811789/129196797-c36ba706-0aaf-4db6-8ebc-2bced16150de.png)
![Screenshot_20210812_152743](https://user-images.githubusercontent.com/5811789/129196801-2235c275-eaf0-4425-b76d-c989ca45a5f8.png)

**Comment by tuomas2** [comment]
Launcher icon seem to be forced to have non-transparent background and circular shape, see https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive#additional_resources.

**Comment by tuomas2** [comment]
I did not create pngs to support older devices yet (=> they will have still old icon -- devices older than api 26 i.e. android 8.0).

**Comment by agrogers** [comment]
Good job. Re launcher, I thought it was dependent on the launcher implementation. So Samsung might force one thing and Mi another or nothing.

And there are some cool effects they can do now using background and foreground icon layers. Not sure our icon can make use of those.

**Comment by tuomas2** [comment]
I think it might be able to do some "efffects" because the layers are set up as described in android docs.

**Comment by tuomas2** [comment]
And FYI: logo.svg that I re-created using inkcape is now in repository (https://github.com/AndBible/and-bible/blob/develop/logo.svg)

Though every time we do changes, we need to import is as android vector graphics again.. (as in https://github.com/AndBible/and-bible/commit/6810e9243f50f66cdd47ef3620417908259874ec)

**Comment by tuomas2** [comment]
What would be best background color for the launcher logo?

**Comment by tuomas2** [comment]
lol

![Screenshot_20210812-211848](https://user-images.githubusercontent.com/5811789/129248430-fa861bea-e865-46b0-a4d8-00736917f6ea.png)

**Comment by tuomas2** [comment]
Though that review was a bit rough, I must agree that as launcher icon it has too many features. In contexts that allow bigger icon (like "splash screen") it looks good.

**Comment by tuomas2** [comment]
bw version 

![Screenshot_20210812_215224](https://user-images.githubusercontent.com/5811789/129252507-41ec4e2d-8117-4cfe-88d0-04b7a66c9d1e.png)

**Comment by tuomas2** [comment]
3 different options color variations (by my wife):


Autumn colors
![Selection_167](https://user-images.githubusercontent.com/5811789/129255688-bc098313-9e36-4609-8f1d-5fe2a3c1c3f0.png)
- https://github.com/AndBible/and-bible/pull/1568

BW version
![Selection_168](https://user-images.githubusercontent.com/5811789/129255757-43a8abaf-ca31-49b0-bb19-0754db9becdf.png)
- https://github.com/AndBible/and-bible/pull/1569

Orange tree
![Selection_169](https://user-images.githubusercontent.com/5811789/129255810-77d69e30-d93e-4529-bba5-714b9a385f6d.png)
- https://github.com/AndBible/and-bible/pull/1570

**Comment by tuomas2** [comment]
My favourite is autumn colors version.

**Comment by tuomas2** [comment]
(changing colors, of course, does not fix the complexity issue... but it looks like complexity issue is a real issue only on rather small screens - like my xperia x1z compact)

**Comment by agrogers** [comment]
That initial post is funny. I have a penchant for icons but it has never
dictated my choice of software 😂!


I think my original comment was that the AB icon stood out from the others
in play store because of its simplicity. I included the screen shots of
other icons. I like the fish concept. But the style felt a little dated for
2021.


The second issue was addressed with some even more simplified versions of
the original
logo. I didn't mind those.


The newly selected logo was one attempt at trying to introduce some color
and some meaning into the logo - it is a book. And it provides some room to
make a fancier play store logo which many apps do - simple icon for the
phone and fancy logo for the play store.


As for colors, that is a purely personal preference and will rarely please
everyone and sometimes anyone. I don't think the color choice was what the
OP had in mind 🤔

I haven't seen the new colors in action yet so I can't comment on those yet.

**Comment by uniqueid001** [comment]
* I like the current logo, especially in the circle shape that my launcher app applies to it
* I like how this new one looks as shown in use
* I like the greyscale scheme, and the muted colors of the Autumn colors.  
* I like the dark greens of the orangetree, but I would try it with the muted oranges of the autumn

**Comment by cmahte** [comment]
If the idea is to allow for minimum notice... Shooting for a user
configurable or random {Letter + fontchoice + background color}  that looks
similar to contacts saved to the screen...

Possibly the first letter of the name of Jesus, or the last book opened..

**Comment by Dleemuse** [comment]
Love the new logo!

Debra

**Comment by agrogers** [comment]
My preference is definitely a transparent background over a white background (see below). And my launcher shows round and square and transparent backgrounds. So there must be someway to get a transparent background on ours (if it is wanted).

![image](https://user-images.githubusercontent.com/13920678/129296184-d28e7e6a-3d7a-4778-82b5-cdc0b23e3620.png)

![image](https://user-images.githubusercontent.com/13920678/129296658-bb202a55-04e6-4762-8dfa-1f814fe579fa.png)

**Comment by tuomas2** [comment]
Transparent logo would be cool but I don't think it is an option. Google does now allow that, it's not according to their style guide (since API 26 or so). Or if I set transparent in ic_launcher.xml as background, it shows as white still.

**Comment by agrogers** [comment]
So how does Messenger make it work? And most of these....
[image: image.png]

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Also messenger has circle shape. I don't know if you can force specific shape (like circle or square).

**Comment by tuomas2** [comment]
(and remember that email attachments do not come across to GH)

**Comment by tuomas2** [comment]
https://www.androidpolice.com/2019/03/15/new-play-store-app-icon-rules-include-squircle-mandate-no-more-transparent-backgrounds/ 

> "New Play Store app icon rules include rounded square mandate, no more transparent backgrounds"

**Comment by agrogers** [comment]
Messenger is a speech bubble - so round with a tail.

Your reference is to the 'Play Store'. I believe the launcher and the play store icons are very different.

Does this help:
https://stackoverflow.com/questions/37085753/android-studio-image-asset-launcher-icon-background-color 

Set 'shape' to None.

**Comment by agrogers** [comment]
And the screenshot that went AWOL

![image](https://user-images.githubusercontent.com/13920678/129334652-a94eedc7-1694-424f-b04a-245b2cd73631.png)

**Comment by tuomas2** [comment]
Answer in above link is from 2016 which is way before new regulations. Perhaps my last linked news article was inaccurate.
Google Play content is anyway separately uploaded, not coming from APK as far as I remember correctly.

**Comment by tuomas2** [comment]
"speech bubbles" i.e. notification dots are not part of icon.

**Comment by agrogers** [comment]
:) Are we talking about the same thing???

![image](https://user-images.githubusercontent.com/13920678/129337534-4929cc56-21ca-4336-800b-995ecd260a1c.png)

**Comment by tuomas2** [comment]
![Screenshot_20210813-123903](https://user-images.githubusercontent.com/5811789/129337823-d3d1cc77-dc53-46b1-8900-39b0dd3ec6f3.png)

**Comment by tuomas2** [comment]
Google Calendar ^

I don't know which calendar app you use but it might have old legacy icon?

**Comment by tuomas2** [comment]
![Uploading Screenshot_20210813-124058.png…]()

**Comment by tuomas2** [comment]
![Screenshot_20210813-124058](https://user-images.githubusercontent.com/5811789/129338278-4723f0f6-c07e-4458-a2bf-4f984bc0ec7a.png)

**Comment by tuomas2** [comment]
Photos the same. I don't understand how you have everything transparent. Which phone / launcher do you use?

**Comment by tuomas2** [comment]
checked messenger also from wife's phone, it's the same, on a background. Not transparent.

**Comment by tuomas2** [comment]
Hmm Nova Launcher has option "prefer legacy icons", which causes old transparecy-icons to appear.

**Comment by tuomas2** [comment]
But that's legacy way, not suggested/supported.

**Comment by agrogers** [comment]
I have a xiaomi poco - use Mi enhancements to the launcher. Its kind of weird that Google's own logos are also on a transparent background though.

**Comment by tuomas2** [comment]
Android version < 8?

**Comment by agrogers** [comment]
Nope - v10 QKQ1

When I created some icons in Android Studio I always got the icon on the white background even though I had other icons on my home screen that were transparent. I assumed i created it the wrong way.

But looking at images of home screen from the last year it looks like most of them are on solid color background - round or square round.  So i think you are right.

**Comment by tuomas2** [comment]
> And the screenshot that went AWOL
> 
> ![image](https://user-images.githubusercontent.com/13920678/129334652-a94eedc7-1694-424f-b04a-245b2cd73631.png)

If this is a new one from your screen, it does not show even AB with the new logo but old legacy one.

**Comment by agrogers** [comment]
It is from my screen. I have 3 different versions of AB on my phone at the
moment.

**Comment by cmahte** [comment]
I haven't dug into the android Icons, but it appears those other apps are
using vectors instead of flat images.

That is, unlike a PNG or JPG, an SVG doesn't have to be rectangular.  it
isn't transparent in the corner, it's just not present.

**Comment by agrogers** [comment]
One of the things i dont like about the book logo on a solid color background is that it feels a little unbalanced. The book is wider than it is high so there is a largish margin at the top and bottom.  

Perhaps also it could be simplified a little.

The image below removes two pages so it is almost square. Maybe it is an improvement.

![image](https://user-images.githubusercontent.com/13920678/129468826-115eb751-f2b2-48cd-afb1-f2980f176e6f.png)

**Comment by tuomas2** [comment]
Not sure if I like. It looks like a booklet more than a book now..

**Comment by agrogers** [comment]
Three is a divine number though 😁

**Comment by bvahedy** [comment]
I kinda like the way this looks:
![Screenshot_20210815-104325_One UI Home](https://user-images.githubusercontent.com/46405809/129487589-ac9778fe-26aa-4277-9f30-76eedc469c33.jpg)

**Comment by Dleemuse** [comment]
I do too, it is pretty. Looks better than the square white background. 
D. 

Sent from Yahoo Mail on Android 
 
  On Sun, Aug 15, 2021 at 12:47 PM, ***@***.***> wrote:   


I kinda like the way this looks:


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by agrogers** [comment]
Yeah, I like the icon on that rounded background as well. Unfortunately though, I think that the background is system dependent. So sometimes it will be a circle or a squircle or a rectangle - we cant control that.

**Comment by uniqueid001** [comment]
* I like the current logo, especially in the circle shape that my launcher app applies to it
* I like how this new one looks as shown in use
* I like the greyscale scheme, and the muted colors of the Autumn colors.

**Comment by BryceSteuer** [comment]
I agree with @uniqueid001's points. At the very least the icon is better than its predecessor. Has anyone considered a nice little animation on the startup screen while loading, perhaps the Bible pages ruffling or some other clean, satisfying animation that gives the impression of loading without using the current loading circle and "initializing application" message? I think that would make the app feel a lot cleaner on startup.

(The link I provided as an example is apparently dead)

**Comment by tuomas2** [comment]
your link gives "Sorry, we can't find what you're looking for."

**Comment by tuomas2** [comment]
here's how to make some nice simple animation in Android that can be displayed in ImageViews https://developer.android.com/guide/topics/graphics/drawable-animation

**Comment by tuomas2** [comment]
Would someone like to give it a try, i.e. to make a nice animable Android drawable xml to StartupView?

**Comment by agrogers** [comment]
I will try and make an animation after i get the videos sorted. I've been wanting to try that for a while.

Attached is a slightly modified logo which addresses my complaint that there the top and bottom margins are too big. I have also fixed the spacing between the pages to make them a little more consistent. And simplified some of the paths. I think I prefer it.

This image has the logos the same width just taller.

![image](https://user-images.githubusercontent.com/13920678/130781683-644659c1-04d3-4b4a-bee4-ecb1db58d2f7.png)

[logo_autumn - square.zip](https://github.com/AndBible/and-bible/files/7046519/logo_autumn.-.square.zip)

**Comment by tuomas2** [comment]
Okay I can change.

**Comment by tuomas2** [comment]
Hmm my eyes already had got used to the previous version so I'm not sure if this is an improvement... But I'll push the changes and you can decide if you like it more than earlier.

**Comment by agrogers** [comment]
Thanks. I am not sure if I will like it more either. Have to see it in
action. It's only the Launcher that bothers me - everywhere else is sweet.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by agrogers** [comment]
Except for the spacing between the pages - that bothers me everywhere. Even
mine is not perfect 😐

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
It feels stretched. Though I'm not sure if it is just because of the fish that is now thinner... that we could still change.

**Comment by agrogers** [comment]
Fish is not really thinner - or very very marginally - i didnt stretch it.

My eyes have got used to the 'old' one also! I think the issue i now have
with the new one is that there is very little padding on the left and
right. So it all feels a little cramped. you must set that somewhere -
there was even less in the SVG.   Can you scale the whole thing down a
little?

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
I can try.

**Comment by tuomas2** [comment]
Actually we add padding manually to the one used in launcher.  `app/src/main/res/drawable/ic_logo_with_padding.xml`

**Comment by agrogers** [comment]
This one is the clear winner in my eyes :D

![image](https://user-images.githubusercontent.com/13920678/130787638-6dd968cd-7a12-427a-aaf3-a74c653b03ec.png)

**Comment by agrogers** [comment]
Feels balanced to me now.

**Comment by tuomas2** [comment]
Are you talking about old one?

**Comment by agrogers** [comment]
:) No, that is the new one with some padding on the sides which i did in InkScape

**Comment by tuomas2** [comment]
I'll add some padding to ic_logo_with_padding

**Comment by tuomas2** [comment]
Better not to add padding directly to the logo I guess

**Comment by agrogers** [comment]
It feels like I am splitting hairs now. But the new one is still clearly better (i think ;-)
![image](https://user-images.githubusercontent.com/13920678/130788223-de721f5a-c964-4f5a-bbdd-6e430a4145f5.png)

**Comment by agrogers** [comment]
> Better not to add padding directly to the logo I guess

Hmm, not sure. Probably not.

**Comment by agrogers** [comment]
Cool. Just add a little more

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
ffd0de86e7d04e7342e8faf4c25073702fcd8dd4

**Comment by agrogers** [comment]
I think I have the latest build but it feels like it needs a little more space still. I would try to match the left and right spacing of the icons I have circled in green.

![IMG_20210826_063331.jpg](https://user-images.githubusercontent.com/13920678/130861074-5742bb3d-b6f6-4349-ac6c-29c3dc8651c0.jpg)

**Comment by agrogers** [comment]
They have different spacing of course - just something around that 😏

**Comment by agrogers** [comment]
New icon looking good.
