### ISSUE TITLE
Reduce the entry requirements for new users

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1231]
I have spent a few hours looking at more 'study' Bibles on Play Store and And Bible is wayyyy better than all the ones I looked at. Plus, most of them had advertising! Yet some still managed to have 100s of thousands of downloads.

One thing I noticed again is that installation of these programs is very easy. Everything is installed automatically - Bibles, Strongs dictionary, and of course the highlighting colors (#1172) - all there after installation.

With And Bible the user is asked to download or restore, then they have 1800 documents to choose from, they select them one by one, then download, and finally they can start. I think this is unnecessarily hard.

Could we:

1. Provide a pretty intro screen after the first install with three buttons
2. Quick Setup Button: This installs two bibles (modern translation with Strongs), a commentary, dictionaries (Strongs) and adds workspaces and labels to match. Plus it also downloads or makes some search indexes. Include a note saying "Recommended for first time users! You can change these settings later on."
3. Clean Install: Current process - they have to choose what they want to download 
4. Restore Button: Allows them to restore from a backup

If they choose Quick Setup then we might also grab some extra info:
1. Their preferred language
2. Allows us to grab the right bible version
3. Maybe allow them to choose a version of the bible from the 'Recommended' list
4. Perhaps show them all documents in the recommended list and let them remove ones they don't want.  But this would mess with any preset Workspaces. And it is no longer 'Quick'.

**Comment by tuomas2** [comment]
Have you tried how fresh install looks currently? @mattschlosser made great improvement over what we had in 3.3. I think it's quite pretty. (not saying that it could not be improved still)

**Comment by agrogers** [comment]
I think so. You mean the below form? It's good. I can't recall the previous style. We just need an 'Easy Setup' button on it :)  And a little more color perhaps.

I was thinking that perhaps 'all' we need is a set of db and document files for the languages we want to provide an easy install for and the option simply downloads those files and restores them. 

![image](https://user-images.githubusercontent.com/13920678/124353363-5dd69780-dc49-11eb-9279-5b11276f2c89.png)

**Comment by tuomas2** [comment]
We can add color still before 4.0 but text changes will go to 4.1 :-)

**Comment by tuomas2** [comment]
3.3 was like this so there's quite some improvement :-)

![image](https://user-images.githubusercontent.com/5811789/124353682-98700e00-dc10-11eb-9951-4e573f86f2f4.png)

**Comment by agrogers** [comment]
Ah, yes, I remember it well now :)  Color is not so important. But the 'Easy Setup' option would be good to have for v4.  Do you think that is worth adding at some point?

**Comment by tuomas2** [comment]
4.1 earliest because we can't avoid string additions... but 4.1 don't need to wait 1 year maybe ☺️

**Comment by tuomas2** [comment]
I can't really speak for others but maybe @mattschlosser might be interested in this. 😊

**Comment by tuomas2** [comment]
> 4.1 earliest because we can't avoid string additions... but 4.1 don't need to wait 1 year maybe

Came to mind that in principle, we could enable some simple extra button for english interface only (but disable for other languages). (not that this is my opinion though... just saying)

**Comment by timbze** [comment]
IMO, we should do this after 4.0. Yes I get what @agrogers is saying, but we have already come a long way from where we were regarding first time users, and we should always seek to improve even further but I think we should set a limit on how much for 1 version so we can get it rolled out. Every feature change has more potential bugs and quirks to work out, dragging out the release even further.

**Comment by bvahedy** [comment]
I agree, besides throwing a lot of changes, even though they are
improvements, will overwhelmed the current users and may frustrated them. I
may be getting older but the learning curve for some of these changes is
high for users who are used to 3.3 setup.

**Comment by tuomas2** [comment]
Yes, intention was not to make a giant release, but it just happened like this again...

**Comment by tuomas2** [comment]
About OP: this suggestion does not take into account users of various different languages and how to handle them.

**Comment by agrogers** [comment]
Yes, I support all those comments. I am just adding things as they come to
mind. I will forget them if I don't.

**Comment by agrogers** [comment]
I stumbled onto these unfortunate 1 star reviews on Amazon. It is from 2013 so a lot has changed since then! But I think the startup experience still risks this response:

> I chose this app because it has the opportunity to compare different versions of the bible, side by side, offline. Most of the features shown in the preview wasn't their after download. I'm not sure if they weren't downloaded, was not intended in the free version, or I just couldn't find it. Either way, **I don't have the time to sit around for an hour or so to find out how to make the app work the way it's advertised**. 

> In the preview, it showed commentary ability. This not the case. There is no way to obtain commentary on a verse or a book of the bible you are reading. **You only get one version to read from**. I deleted this one. Useless.

For v4.1 I think we really need to provide an option for a 1 click install that downloads everything that a first time user might want (multiple Bibles, commentaries, dictionaries, maps, books, etc).  I dont think this is hard to do. It could even just be an automatic restore action of a package we have already made up. 

We gain or lose users in the first 5 mins after download - these are examples of people we might still lose even today because there is a lot of clicking needed to get half the things we will show in our promo videos.

Just flagging this so we don't forget it :)

**Comment by tuomas2** [comment]
We could do "simple setup" option for english users and make some way to configure some other languages too (like recommended_documents.json), but fully generic solution that works for all languages does not exist I think.

**Comment by agrogers** [comment]
Yeah, I agree with you. It's impossible for all languages because there are insufficient documents in all categories. If it only showed for English (and Finnish?) speakers then perhaps it could make it into this release. It feels like there would be very little front end stuff to do (one button perhaps) and just a matter of reusing your existing backend code. If it was a restore then I could make the default package, host it on github and and restore it from there.

**Comment by tuomas2** [comment]
> If it was a restore then I could make the default package, host it on github and and restore it from there.

This I did not understand

**Comment by tuomas2** [comment]
Though I think this is not blocking release, we can release with or without it. Implement it as soon as possible, but not block the release.

**Comment by agrogers** [comment]
> > If it was a restore then I could make the default package, host it on github and and restore it from there.
> 
> This I did not understand

I see two main ways to get documents and database onto a new phone. 1) Download each individual document and create database 2) Restore documents and database

Option 2 is very easy - AB already does that. So to implement this we need a button that says 'Default Setup (recommended)' and backed up database and documents file somewhere that we can restore from.

Does that make sense?

**Comment by tuomas2** [comment]
> Option 2 is very easy - AB already does that. So to implement this we need a button that says 'Default Setup (recommended)' and backed up database and documents file somewhere that we can restore from.

I don't like this idea. Would require maintaining default setup zip file and would burden our free GH quota unnecessarily (it will slow down if it is used too much per month). I rather implement it as a list of documents that are installed -- similarly as @mattschlosser 's quick setup button works (for those users that are having backup of db).

**Comment by agrogers** [comment]
Maintenance would be pretty easy. Maybe nill. But yes, I agree that
download and dynamic database creation is better all round. Where is the
'quick setup button'? I havent seen that.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
I guess it pops up if Android restores db when installing app. (for example, if you have a new phone, it could do that). I'm not exactly sure how to trigger that.

**Comment by Phileosopher** [comment]
I recommend one of you guys downloading and running Bible Time on their desktop. It's based on the SWORD modules as well, and has a few key UI differences during startup:

1. It brings you to the "book select" prompt first.
2. The book selection interface is grouped first by language, with checkboxes on the meta-groupings.
3. It pre-selects the Bibles if I remember correctly, and unselects everything else.

The power of And Bible comes in its vast access to many resources at once, along with the freedom to sideload other assets (researching cults? no problem!). Downloading 1 bible and Strong's automatically is almost *underselling* what it can do!

**Comment by agrogers** [comment]
Thanks for the ideas. And yes, one of the difficulties is that there are so
many documents across so many languages that getting a perfect default
install for everyone is difficult.

**Comment by tuomas2** [comment]
![Screenshot_20210824_171248](https://user-images.githubusercontent.com/5811789/130632445-6b9e4b04-def5-48a1-b9d6-62c72684b17e.png)

Does this look reasonable? "Quick redownload" is hidden if backup does not exist. "Easy start" will be hidden if device language is something else than english.

**Comment by bvahedy** [comment]
Where does it look for a backup zip file? (i.e. What directory)

**Comment by tuomas2** [comment]
> Where does it look for a backup zip file? (i.e. What directory)

Android restores it in AB's internal folder, where it is normally when it is in use.

**Comment by tuomas2** [comment]
"Easy setup" option now install all documents mentioned here: https://github.com/AndBible/data/blob/master/default_documents.json

**Comment by tuomas2** [comment]
Please test this by doing some fresh installs...

If we want to do anything in addition to what I implemented, please open new ticket.

**Comment by timbze** [comment]
> "Easy setup" option now install all documents mentioned here:

Should it also have "Robinson" morphological codes? Haven't rechecked now but I think it asks for that now as well when opening strongs link

**Comment by tuomas2** [comment]
Added Robinson there too

**Comment by bvahedy** [comment]
May be I didn't say it correctly, in order to unhide the selection to
restore from a backup, which directory does AB look at to see is there was
a backup file.

**Comment by tuomas2** [comment]
> May be I didn't say it correctly, in order to unhide the selection to restore from a backup, which directory does AB look at to see is there was a backup file.

As I said earlier. AB does not look at any other folder. Android may or may not put file there. For example when switching to new phone it should be there.

**Comment by timbze** [comment]
> May be I didn't say it correctly, in order to unhide the selection to restore from a backup, which directory does AB look at to see is there was a backup file.

It's based on Google's app backup. If your device settings are set to backup apps, then And Bible database is backed up to Google nightly (if you're on wifi/plugged in etc or your settings permit). 

Then if you install And Bible on a brand new phone where you have the same Google account, the database is automatically restored on install. And Bible will then see in the database which documents were installed before and give you the option to re-download those documents.

**Comment by tuomas2** [comment]
@timbze you are indeed better explaining this :-)

**Comment by bvahedy** [comment]
So I have to buy a new phone to test this😁

**Comment by timbze** [comment]
> So I have to buy a new phone to test this😁

😆 Or uninstall AB (after making sure Google has backed it up), and just do a new install. Google also restores when installing from apk

**Comment by timbze** [comment]
You should be able to check Google backup status for all apps in system settings (look for And Bible, when it was last backed up)

**Comment by bvahedy** [comment]
I don't use Google backup for apps only contacts. I use Samsung for backup
of apps and other things. I don't trust Google for many reasons. So
basically you can save the net.bibleactivity.net file and restore it
yourself for people who don't use cloud for their backups. That's why I
asked if there is a specific folder that AB uses to look for a zip backup
file and I still don't know the answer to that question.

**Comment by timbze** [comment]
This feature has only been built as I described, so it does not look at any folder for zips.

**Comment by bvahedy** [comment]
So if the person restores their AB app and it's data from Google cloud
backup why would there be any reason to restore anything, all Bible module
files are going to be there. And a new version of AB will only update the
app. Am I missing something?

**Comment by timbze** [comment]
Module files are not backed up. Google backup has limit of 25Mb so we had to exclude modules directory from backup.

**Comment by tuomas2** [comment]
I believe this feature probably works also with Samsung's backup tool the same way (?)

**Comment by timbze** [comment]
I have not tested with Samsung but if they restore data on install then it should

**Comment by tuomas2** [comment]
not necessarily on install but perhaps when restoring app from backup it will do just this

**Comment by agrogers** [comment]
It looks great! Looking forward to trying it out.

Only change I see now is to move Easy Install to they very top.
