### ISSUE TITLE
Identify workspaces more easily - and make things prettier

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1233]
I remember sometime ago someone raised an issue with knowing what workspace the he was currently using. I don't think there is any way of identifying that without  going into the workspace settings. I have been caught out a few times by thinking I was in one workspace when i was actually in another that looked like it.

One way to solve this problem could be to simply allow the user to specify a color for the workspace. That color could then be applied to the action bar and active window buttons as you can see below. It has the secondary advantage of allowing some minor visual customization to the user who may not like gray as much as we do.

I have also been trialing  the solid color active button at the bottom. I like how it looks. I think it is also helping me to know more easily what window is active. I probably don't need the active window indicators any more.

![image](https://user-images.githubusercontent.com/13920678/124362347-9d1bdd00-dc77-11eb-8d00-7c16289c651a.png)

**Comment by tuomas2** [comment]
It would be beautiful. But at the moment I feel like styling Android side is not my piece of cake.

**Comment by agrogers** [comment]
We can fry this fish another day 🐠

**Comment by tuomas2** [comment]
- #2007

**Comment by tuomas2** [comment]
I thinks this is implemented
