### ISSUE TITLE
Restore strongs links formatting style to be like in 3.3

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1236]
The old style which I quite liked looked like this...
![IMG_20210704_171419.jpg](https://user-images.githubusercontent.com/13920678/124379691-d0a04b00-dcfb-11eb-83eb-5d433452d360.jpg)

The new style that I see looks like this...
![IMG_20210704_191215.jpg](https://user-images.githubusercontent.com/13920678/124379697-ddbd3a00-dcfb-11eb-87e4-be2578375d76.jpg)

I preferred the old style because the numbers were much less intrusive.

**Comment by tuomas2** [comment]
Need to re-implement original css in new bibleview.js (in corresponding vue component). Your 2nd PR? :-D

**Comment by agrogers** [comment]
Sure :D  Nice to do some work rather than just making work for others!

[Maybe the below should be in another ticket]
Is this something that should be in an Add On? That is, All formatting like
this is in a separate file(s). Users could then (provide) and install
whatever format style they like.

I would also like to make the Strongs more beautiful (see below). Perhaps
that could be done through an addon config file. Our formatting of the
definitions is functional but not so beautiful.

[image: image.png]


___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
> Sure :D Nice to do some work rather than just making work for others! [Maybe the below should be in another ticket] Is this something that should be in an Add On? That is, All formatting like this is in a separate file(s). Users could then (provide) and install whatever format style they like. I would also like to make the Strongs more beautiful (see below). Perhaps that could be done through an addon config file. Our formatting of the definitions is functional but not so beautiful. [image: image.png]

Image is not visible. (GH does not support email reply attachments)

Now what I'm suggesting is that you will edit the component directly (it's W.vue, see <template> and <style> blocks)).
You look for style.css from old code (3.3), how it was styled earlier. #1222 will be making it possible to create overriding css that will customize anything displayed in And Bible's WebView.

**Comment by bvahedy** [comment]
Andrew, your image didn't come across because you used the email to reply,
please use GitHub to include the image.

**Comment by agrogers** [comment]
This is the missing image. Do you think that could be accomplished with css only? 

![Screenshot_2021-07-05-12-49-07-538_king.james.bible.study.jpg](https://user-images.githubusercontent.com/13920678/124466794-52ff3c80-ddda-11eb-9d82-df315ae96bd7.jpg)

**Comment by tuomas2** [comment]
Not css alone, need to have specially formatted strongs dictionary.

**Comment by agrogers** [comment]
Hmm, for some reason i thought the original numbers were in orange! Anyhow 'coral' numbers seems ok to me. See Pull request https://github.com/AndBible/and-bible/pull/1281

**Comment by agrogers** [comment]
Is this task complete now?
