### ISSUE TITLE
When selecting a word add Find to the selection context menu 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1237]
Add "Find" function to selection menu so that when invoked it would take you to the Find screen and pastes the selected word(s) on the Find screen.

Currently when selecting a word you would have to copy that selection then go to the Find screen, paste it, strip off all the other stuff from it and then do the search.
Please, for the love of God add this feature, it saves a lot of steps.

**Comment by tuomas2** [comment]
I believe this can be done even without new strings, so it could be implemented in 4.0+

**Comment by agrogers** [comment]
Good idea. I think I would use that much more often then Internet searching
for the selection. Perhaps the latter can be pushed into the sub menu.

**Comment by bvahedy** [comment]
That's fantastic, thanks for giving me hope.

**Comment by agrogers** [comment]
This is implemented now.

**Comment by tuomas2** [comment]
but not yet merged

**Comment by bvahedy** [comment]
Any chance this could be merged in the next build. It would greatly be
appreciated.
