### ISSUE TITLE
Highlight the link verse differently

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1247]
A minor thing, but I find the default yellow highlight of the reference link the I clicked on a little problematic. Now that verse can be hihglighted in our own colors, the yellow highlight confuses that and also changes the colors of those highlights.

I like the idea though - you can easily see which link you just clicked on.

Would it be possible to highlight it differently? 

- A box around the verse(s)? 
- Or even better for me i think, a yellow bar (green in my picture) on the left or right or both of the verse. 
- Or maybe even bold text?
- Anything but a yellow background highlight :D

![image](https://user-images.githubusercontent.com/13920678/124728760-30dcfa00-df53-11eb-99ba-aa4dd0723ab5.png)

**Comment by tuomas2** [comment]
I don't know how to implement proposed suggestions (1, 2) and I like the current highlight. Color could be changed but I think yellow is quite intuitive choise for highlighting? I don't like bold option. 

Of course customizing is possible with css when #1222 is done.

**Comment by agrogers** [comment]
Yes, no problem with the ease of understanding. It just messes with my eye
a little bit because it stomps on my existing highlighting.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by agrogers** [comment]
I believe this is done satisfactorily now.
