### ISSUE TITLE
Why did the Strongs numbers show in my bookmark dialog?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1248]
Just trying to understand this...

Why did the Strong numbers show up here? Workspace setting? There are no strongs numbers visible on screen.

Thanks
Andrew

![image](https://user-images.githubusercontent.com/13920678/124729463-ced0c480-df53-11eb-94b5-1ba4adb4c54f.png)

**Comment by timbze** [comment]
I think God's Word translation module does not have strongs numbers. The bookmark is saved in NASB which does have strongs. I think if you'd disable showing strongs from the 3dot menu then it would stop showing in the modal.

Even though that explains what I think is happening, I'm not sure if strongs numbers should even show in that modal?

**Comment by agrogers** [comment]
Good suggestions. I will see if I can reproduce it. I have to make some
tutorials at some point so would be good if I can understand it before then
😁

**Comment by tuomas2** [comment]
Just as @timbze said.

**Comment by timbze** [comment]
> Just as @timbze said. 

Should the strongs numbers show in the modal though?

**Comment by tuomas2** [comment]
Hmm I'm thinking that in some situations it might be beneficial?
