### ISSUE TITLE
The sound effects still play for chapters even when i have the setting turned off.

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1251]
I uncheck the options to play 'Chapter changes' but it still plays a jungle when the chapter start is reached.

![image](https://user-images.githubusercontent.com/13920678/124730412-a85f5900-df54-11eb-991d-aa77244c6374.png)

**Comment by bvahedy** [comment]
I can't dupplicate this, what version are you running?

**Comment by tuomas2** [comment]
I'm also wondering about these bugs. I'm using this all the time and not having this issue.

**Comment by bvahedy** [comment]
Every once in a while I have to do a fresh install, I wonder if @andrew
needs to do one and see if he can still reproduce these.
 He can just rename the net.Bible.activity folder in the Android/data/ and
uninstall and reinstall without opening Andbible, then rename that folder
back to what it was, this way he doesn't lose any of his document
downloads.
The other option is to backup all his documents.

**Comment by tuomas2** [comment]
I must say I never do fresh installs and I don't think it normally should be necessary. At least on modern devices.

**Comment by bvahedy** [comment]
Tuomas, you make it sound like I'm running a toaster here from 1920s 🙄

**Comment by agrogers** [comment]
I tried to reproduce it and couldn't. So let's close this one and I will reopen it if it happens again.
