### ISSUE TITLE
Don't speak the whole book name when the chapter changes

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1252]
When the speaking changes from rev 3 to 4 Google will say "The revelation of John chapter 4".  i think that is unnecessary.
I would propose:

- For chapter 1 read the entire book name.
- For all chapters after 1 simply say 'Chapter X'

**Comment by tuomas2** [comment]
I think this is a bug.

**Comment by tuomas2** [comment]
Though let's see if it's that easy to reproduce.

**Comment by agrogers** [comment]
I was listening to this last night and it was still saying  the book name and the chapter number for each new chapter. Speaking the chapter number is good.
