### ISSUE TITLE
Automatically maximise a window when it is too small to reasonably show the bookmark dialog

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1253]
You can see in the images below that the window is so small that the bookmark dialog is almost unusable. So...

1. If the current window is less than 400px high or wide then 
2. Auotmatically maximise the window
3. Show the bookmark dialog
4. When the dialog is close automatically restore the window back to original size

This is what i presently do manually. I think it might be good to do it automatically.

![image](https://user-images.githubusercontent.com/13920678/124730972-291e5500-df55-11eb-8065-70c69b123807.png)
![image](https://user-images.githubusercontent.com/13920678/124731316-75699500-df55-11eb-989f-1e0c0139263c.png)

**Comment by timbze** [comment]
I'm not sure if this would be a good idea to do automatically. For me, I feel that it would be intrusive if it did that.

- maybe a setting if someone always wants to maximize when window is too small
- maybe a snackbar (short duration pop-up at bottom) with a button to maximize the window.

Just ideas, maybe if it was the default and I used it I would find out it's ok.

**Comment by tuomas2** [comment]
Agreed with @timbze. I wouldn't like auto-maximize. Let's put this to the wishing well of 4.1.

**Comment by agrogers** [comment]
Sure thing.

Do you guys end up with tiny bookmark dialogs like the one I included? Or
is it just how I am using it?

**Comment by tuomas2** [comment]
I'm usually using 8" tablet in portrait mode, typically 2 windows open, so they are large enough for modals. If they get too small, I do switch window to fullscreen manually.

**Comment by agrogers** [comment]
Yeah, it is probably not so common to have really small windows. And yes, I
switch to fullscreen manually too.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by timbze** [comment]
I do come across it. Use AB mostly on my phone. I just manually resize the window, but it can be a bit frustrating.

I still think a snackbar might be a solution (easy 1 tap maximize)

**Comment by agrogers** [comment]
Snackbar could work well. Or even just adding a button to the bookmark
dialog itself?

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by agrogers** [comment]
I now use the 'swipe up' on the window button. Not quite as easy as a single tap but doesnt require an extra button and i think good enough for me. So I will close it.
