### ISSUE TITLE
Text overlaps slider in speak transport

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1255]
This seems like a bug to me. Is it meant to be there?

![image](https://user-images.githubusercontent.com/13920678/124731988-1bb59a80-df56-11eb-9ccf-5a4499ab5a57.png)

**Comment by tuomas2** [comment]
I need it 😊

**Comment by agrogers** [comment]
That is such a developer thing to do 😅 It would never have got past the UX nazis. But that is one of the perks when you're the lead developer and you work for free 😁

I will just try not to look at it 😉

**Comment by tuomas2** [comment]
Better UX for same simple feature welcome (though no promises I will do it) :-P

**Comment by tuomas2** [comment]
(though text has not yet been overlapping with the slider for me... that's a bug, should use ellipsis.)

**Comment by agrogers** [comment]
How often do you change the speak speed? I do it once and then just leave it set.

**Comment by tuomas2** [comment]
On my mobile phone not so often. But on my tablet, it really depends on which book I'm listening to. Gill I need slower speed. KingComments I can listen faster. So I can also listen finnish much faster than english.

**Comment by agrogers** [comment]
Good points. There is a very big difference between documents. And
languages for the polyglots.
