### ISSUE TITLE
The chapter number is missing from God's Word

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1256]
Is this And Bible's problem or the book creator?

![image](https://user-images.githubusercontent.com/13920678/124732141-499adf00-df56-11eb-8c9b-38a52dd17517.png)

**Comment by bvahedy** [comment]
This looks like a module problem since all other modules display it
correctly.

**Comment by tuomas2** [comment]
I believe it's a bug. How we display chapter is a bit messy. I'll take a look at this.

**Comment by tuomas2** [comment]
Fixed
