### ISSUE TITLE
Adjust the label position in the My Notes view

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1257]
- The study pad icons are all at different positions (see red line)
- I think it would be easier to follow if they were all in roughly the same position (see green line)
- Also, the label and verse jump around when you expand the verse. If they are always formatted like the verses indicated by the big green lines, then they would not jump about. (Not completely sure about that suggestion)

![image](https://user-images.githubusercontent.com/13920678/124732578-abf3df80-df56-11eb-9d6b-bcd14bf687ad.png)

![image](https://user-images.githubusercontent.com/13920678/124732933-0c831c80-df57-11eb-8173-100812e4730a.png)

**Comment by tuomas2** [comment]
So you want newline always before label list?
Should we also truncate list like we do in bookmark dialog?

**Comment by agrogers** [comment]
Yes, i think both those options would be an improvement. 

Actually, I think the label should go next to the verse number because when you expand the verse that is where it is located. So its position stays the same in both views - next to the verse number.
