### ISSUE TITLE
Not found error for ABpGk-THE

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1259]
Is this our problem?

![image](https://user-images.githubusercontent.com/13920678/124733411-84514700-df57-11eb-8813-6bb0c58da954.png)

**Comment by tuomas2** [comment]
https://github.com/STEPBible/STEPBible-Data/issues/35

**Comment by tuomas2** [comment]
Not our problem but due to STEPBible/STEPBible-Data#35

We might want to disable Step repo meanwhile if they don't fix the issue.
