### ISSUE TITLE
Somehow my keyboard was only half height

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1262]
I am not sure how this happened sorry. Just thought i would show it here so you are aware of it.

![image](https://user-images.githubusercontent.com/13920678/124734262-4b65a200-df58-11eb-8446-8e956b1c9e97.png)

**Comment by timbze** [comment]
Most likely Android hiccup and not related to AB...

**Comment by tuomas2** [comment]
I agree with @timbze, probably can't help with this one. But if it reproduces, please re-open, and maybe take logcat also with main menu / report a bug.
