### ISSUE TITLE
Custom popup text selection menu 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1263]
I was just using bitwarden and noticed that it's text selection popup menu had very tiny font. It also had icons for search and download. And this github android app has icons as well. I didn't realise that was possible. 

I think our popup menu would be better with icons or smaller text or both.

**Comment by tuomas2** [comment]
I don't think it's native Android selection context menu, because I don't think it's possible to do this natively. And I don't think I want to do this on js side either. If you find a native android lib that does this, feel free to link here & re-open.
