### ISSUE TITLE
Is it possible to get to a chapter study pad without going through a bookmark?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1266]
I was trying to look at the study pad on a chapter and i had no bookmarks visible on the screen. However I couldn't work out how to do it. Is it possible?

**Comment by tuomas2** [comment]
I'm afraid I don't understand the question.

**Comment by agrogers** [comment]
Oh, ok. How can I get to this window **without** clicking on a bookmark?

![image](https://user-images.githubusercontent.com/13920678/124873148-70feb400-e009-11eb-81da-d57cea00b9ce.png)

**Comment by tuomas2** [comment]
This is "My Notes" view, and you can get there from "Commentaries" button -> "My Notes". "Chapter Study pad" was misleading concept to me :-D

**Comment by tuomas2** [comment]
I'd keep one non-pinned window for that all the time.

**Comment by agrogers** [comment]
Ah, so you can! I have never used that before - at least not deliberately.
Thanks.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
