### ISSUE TITLE
New Strongs icon?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1277]
Do we need a different Strongs icon? I don't mind the current ones - the Greek and Hebrew symbols. But I find them a little hard to reference.

Below is a simple scroll - the best i can think of for an ancient language. It's easy to refer to - "To show the Strongs number click the  Scroll icon in the action bar."

And do we need two icons - one for Greek and one for Hebrew? I like that attention to detail but I feel it's probably not necessary and could be a little confusing. As far as I know the button does the same thing - shows the Strong's numbers.

![image](https://user-images.githubusercontent.com/13920678/125071497-ae903980-e0fc-11eb-8da2-f733a57c413f.png)

Lots of scroll options if that is preferred...
![image](https://user-images.githubusercontent.com/13920678/125071998-5b6ab680-e0fd-11eb-823f-3db224ba7ed8.png)

**Comment by tuomas2** [comment]
I think strongs icons are pretty understandable
