### ISSUE TITLE
Alternative highlighting for active verse?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1278]
The current way to highlight a target verse is a yellow background color. I don't like this when it messes with existing highlighting. (This bookmark is supposed to be blue)

![image](https://user-images.githubusercontent.com/13920678/125083337-996ed700-e10b-11eb-8162-9a7479e840c3.png)

One of the things I noticed with new and improved single click verse action process was that if the bookmark dialog was already open and you clicked on a different verse the dialog updated nicely but it could get hard to tell what verse it was that I had selected. The only indicator is the verse number.

![image](https://user-images.githubusercontent.com/13920678/125083115-557bd200-e10b-11eb-974c-38394965ca87.png)

The first idea that came to mind was to put a line down the side like this. I like this option the most but sadly the only way I can do this is to make the span a block which works great when the Bible text is shown one verse per line but messes with it when it is not. 

Another option would be to outline the verse in question. This leaves the bookmarking untouched. And it is very clear what verse  I am now working on.

![image](https://user-images.githubusercontent.com/13920678/125082143-32045780-e10a-11eb-8ee6-42e8ed6c82b2.png)

The outline could be more beautiful than the one above with a little fiddling.

![image](https://user-images.githubusercontent.com/13920678/125083895-40ec0980-e10c-11eb-85fd-a17edc048dad.png)

Is this something that could be provided as an add-on so users can choose what they want?

Verse.vue
```
.isHighlighted {
//  background-color: rgba(255, 230, 0, 0.4);

  // Shows an outline around the verse
  outline-color: rgba(255, 230, 0, 0.9);;
  outline-width: 3px;
  outline-style: solid;
  padding: .2em .4em;

//  // Show's a side border but forces verse to be on a single line
//  border-left-style: solid;
//  border-left-width: 10px;
//  border-left-color: rgb(255,230,0);
//  margin-left: -4px;
//  padding-left: -6px;
//  display: block;

  .night & {
    background-color: rgba(0, 230, 0, 0.6);
  }
}
```

**Comment by tuomas2** [comment]
Okay I'll try outline as you provided code for me :-D

**Comment by tuomas2** [comment]
Verse range highlights look ugly:

![image](https://user-images.githubusercontent.com/5811789/125091882-79bebb00-e0d9-11eb-9af1-40d6d3119604.png)

**Comment by agrogers** [comment]
Darn, I should have tried multiple verses. Not sure that can be worked
around around...

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by timbze** [comment]
Or just hightlight the verse number?

**Comment by agrogers** [comment]
Hmm, interesting suggestion. I will try it. I generally don't want or need
the highlight when clicking links - but that could be just right for me.

**Comment by timbze** [comment]
Or bold the verse number(s) or some other style

**Comment by timbze** [comment]
With the current yellow highlight, for night mode I always tap the window to remove the highlight. I like to see the highlight initially for once though.

But now since the single verse click has been implemented, it hides the highlight and shows modal at the same time. In this case I think the highlight should hide first and then show modal on next click.

**Comment by agrogers** [comment]
Here is another option I like. It simply uses the border-bottom style which is good because it doesnt mess with the highlighting at all. It is a little less intrusive too. The line is 5px there. It could be thinner.

![image](https://user-images.githubusercontent.com/13920678/125153500-768a0480-e197-11eb-864c-ff8f01b66738.png)

**Comment by agrogers** [comment]
I don't mind the verse highlighting for the links as well.  I gave it a one pixel padding on left and right to try and give it a little space. It does mean that verse moves slightly when the highlight is removed. It's kind of a feature more than a bug I think.

I think the highlight for the linked verses should be noticeably different to the highlight for the active verse (#1282) 

![image](https://user-images.githubusercontent.com/13920678/125153779-77239a80-e199-11eb-8c8b-7655b51bb5da.png)

**Comment by agrogers** [comment]
This issue was actually for the **Active Verse** (same as #1282) not the link verse. I don't know how to set the active verse colors yet. My feelings are:

1. Agree with Tuomas about highlighting the active verse.
2. The active verse and linked verse highlighting needs to be different in some way. I quite like the number highlighting. Could also be done with bottom-border of different colors - maybe green for active and yellow for link.
3. The active verse needs more than just the number highlight because sometimes the number will be under the dialog.
4. I would prefer left side highlighting for the active I think - but I don't know how to do that with <span>

Let me know if you want to go ahead with this and what we should do and i can make my third pull request.

**Comment by tuomas2** [comment]
what if verse numbers are disabled?

**Comment by agrogers** [comment]
Oh, yeah. That's why you are the boss :)

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
What if highlight color would be translucent black / white, so that it would not "change"  bookmark colors because of mixing, but make it darker/lighter

**Comment by agrogers** [comment]
Sounds interesting. I can't really imagine it. Might need to see it first.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Closing this now. Re-open if still not happy..:-)

**Comment by agrogers** [comment]
It works well. It's not very pretty but it might be just the right
solution.
