### ISSUE TITLE
Highlight

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1282]
![Screenshot_20210709-181515_Bible Study](https://user-images.githubusercontent.com/5811789/125102555-12f2cf00-e0e4-11eb-8628-c4e484ff58b5.jpg)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by agrogers** [comment]
Yes, I agree. Highlight is good. Perhaps my single verse outline highlight would work well here. I think at present it is only possible to select a single verse with our one-click option.

**Comment by agrogers** [comment]
Tuomas, can you (or direct me what file to start looking in) just add an 'active-verse' class to the verse that is currently shown in the bookmark dialog? I can add a style somewhere to highlight it. Would that work for you?

**Comment by tuomas2** [comment]
I think I'll do this one myself. Need to generalize current highlighting framework. I think highlighting should be consistant anyway, whatever style we choose.

**Comment by agrogers** [comment]
Sure thing.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment]
I like this so far, it's better than any options in the past. And it still
shows other vivid color bookmarks on the verse.

**Comment by agrogers** [comment]
It's good that it doesn't mess with the labels. And it's not too intrusive.
Only thing I don't like is that we have lost the visual cue that links the
yellow highlight for the reference and the gray highlight for link window.
I feel they should both be the same highlight.

**Comment by tuomas2** [comment]
I noticed it too, and will change it so it's consistent.
