### ISSUE TITLE
Part of speech style is not yet changed

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1283]
**Describe the bug**
Related to #1281, it looks like the style for the part of speech is not changed yet. This shows in KJV module from Crosswire. See screenshot

**Bug was found on And Bible version**
Build 531

![image](https://user-images.githubusercontent.com/35117769/125115105-1f593680-e0a8-11eb-8213-140f2901aabf.png)

**Comment by agrogers** [comment]
I was trying to test that last night but couldn't for the life of me get
the Morp codes to work in my emulator. I will try again today.

**Comment by timbze** [comment]
@agrogers Try it with KJV from Crosswire. Not all modules have the morph codes

**Comment by agrogers** [comment]
Thanks for the tip. I think you raised the bug that the Morp codes option
is always disabled in the latest version. That was my problem I believe.

**Comment by timbze** [comment]
Has been fixed somewhere from then till now cause the style is consistent in version 540
