### ISSUE TITLE
Morphological codes option always disabled

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1285]
See screenshot

AB 4.0.531-beta

![Screenshot_20210709-125102.png](https://user-images.githubusercontent.com/35117769/125123850-7402ae80-e0b4-11eb-9bfa-f8fd91491e9b.png)

_Originally posted by @timbze in https://github.com/AndBible/and-bible/issues/1284#issuecomment-877390480_

**Comment by agrogers** [comment]
My problem too.

**Comment by bvahedy** [comment]
This is a bug, it was working before, I guess Toumas is aware of it.

**Comment by agrogers** [comment]
I dont think he was aware of it last night... or perhaps didnt connect my
problem with that bug.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment]
Well, I've lost track of days and nights, my day is his night, you night is
his day, we all live in different time zones. But I thought I saw in an
email that he mentioned that he had introduced that bug in the latest beta
build. We will have to wait till he wakes up to ask him😁

**Comment by agrogers** [comment]
lol. Good point! I tend to work in the wee hours as well so that
complicates things more :)

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by agrogers** [comment]
Hi Tuomas. I thought i saw a message that this was resolved in an update you have already pushed. Is that correct?

**Comment by tuomas2** [comment]
not this one

**Comment by bvahedy** [comment]
Verified fixed in 531.15 beta build.

**Comment by agrogers** [comment]
Awesome. I will fix up the morph css as soon as I can.
