### ISSUE TITLE
Compare Icon change... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1287]
In the single click action, the icon for compare is too similar to minimize/maximize.
![Screenshot_20210709-124020_Bible Study](https://user-images.githubusercontent.com/46405809/125128634-20439580-e0b3-11eb-9f8a-6cfeae9bd6f3.jpg)

**Comment by bvahedy** [comment]
Here is another image:
![Screenshot_20210709-124354_Bible Study](https://user-images.githubusercontent.com/46405809/125128816-6a2c7b80-e0b3-11eb-966a-992c9fb6c6ce.jpg)

**Comment by tuomas2** [comment]
I think minimise and maximise icons are about to change (if I remember correctly from @agrogers plans) but I agree that compare I'm not very happy with compare icon either.

**Comment by agrogers** [comment]
Yes, I agree. Will look at it today.

**Comment by agrogers** [comment]
Closed by https://github.com/AndBible/and-bible/pull/1381/commits/0d96e617bee82eebdc6a0166c0dd5bf93613f12a
