### ISSUE TITLE
Share selection options modification... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1288]
When turning off all the selection/share options the copy function should only copy the word(s) you selected without the bible ref and the dots.
![Screenshot_20210709-124800_Bible Study](https://user-images.githubusercontent.com/46405809/125129521-6d743700-e0b4-11eb-8aa5-01efb03a0de4.jpg)

**Comment by tuomas2** [comment]
Why? I think this is expected, but explain why my logic is wrong.

**Comment by agrogers** [comment]
Wouldn't the proposed functionality be the same as simply choosing 'Copy'
from the text selection menu? Oh, there is no simple copy anymore.

I think you are both right. The present functionality works logically.

But there is no way to simply copy the bare text you have selected.

Perhaps a 'Text only' option is needed in the copy dialog that will disable
all other options and give you just the text you selected.

**Comment by bvahedy** [comment]
If you wanted to copy a name from the bible or a set of words to paste in an email or text or do Google on, you would have to strip all that extra stuff out. Even trying to paste a word to do a search in the find window is hinders in the current design.

**Comment by tuomas2** [comment]
Will be fixed by #1371
