### ISSUE TITLE
In text selection mode, tapping beside should not open modal 

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1290]
**Describe the bug**
When selecting a word or words, tap beside to cancel selection mode and it opens the verse single click modal. IMO First click should only cancel selection mode, then another click would open the verse click modal 

**Bug was found on And Bible version**
Build 531

**Comment by agrogers** [comment]
Yes, I agree.
Are these changes difficult Tuomas?

**Comment by tuomas2** [comment]
I don't think so (yet).
