### ISSUE TITLE
Style issue in label list

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1295]
![image](https://user-images.githubusercontent.com/5811789/125166326-d1295d80-e1a3-11eb-9df9-6eb6ac5e8128.png)

(in my notes view)

**Comment by agrogers** [comment]
You mean the text is at the bottom of the label? I had noticed that too. I
might be able to fix that. Assign it to me if you want to.

**Comment by tuomas2** [comment]
You can do it if it's open :-) Although this might be a bit tricky CSS issue. It's some inherited css from the context that is breaking it in my notes view. I think I had it some time, and it might not be as obvious at it seems. we are using same LabelList component in different contexts.

**Comment by agrogers** [comment]
Sure thing.
