### ISSUE TITLE
Pinning should be enabled by default on new installs 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1299]
Watching my niece and her husband use AB for the first time tonight. I feel like we need some more UI testing by new users!

They were trying to show the split window but had no idea that 'pinning' was the way to achieve it.

Propose that pinning be enabled for new installs and that new Windows default to pinned.

It was only a month ago that I discovered what unpinning did - can be quite handy at times!

**Comment by bvahedy** [comment]
That's a good idea.

**Comment by tuomas2** [comment]
Please try if this works now as expected
