### ISSUE TITLE
Can we add some descriptions to some of the bibles 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1300]
My niece's husband immediately searched the bible list for 'ESV' which resulted in nothing and then 'Message' which didn't help. If I hadn't stopped him he would have gone for 'NIV' next.

Can we add a comment to existing bible descriptions with something like 'The GNB is a natural language like the "Message" Bible'?

The purpose is to get it to appear when someone searches for common translations that we don't have.

**Comment by tuomas2** [comment]
Perhaps we could have also some "pseudo"-entries of ESV, NIV etc in download screen, that will have some description why they are not included. Some other app does this way.

**Comment by timbze** [comment]
> Perhaps we could have also some "pseudo"-entries of ESV, NIV etc in download screen, that will have some description why they are not included. Some other app does this way.

I think that is a good idea. That way the "pseudo entry" could mention which other Bible version is available that is similar

**Comment by agrogers** [comment]
Perfect.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Options for NIV and ESV? NASB for both?

**Comment by tuomas2** [comment]
![image](https://user-images.githubusercontent.com/5811789/125245354-25922180-e2f9-11eb-86c6-3cd497867b21.png)

**Comment by agrogers** [comment]
Nice, that is good. NASB for sure. Probably good replacement for the ESV.

I would try to include some easy reading versions as well like GodsWord or
BBE or PEV. I dont know which of them are good - i havent read them enough.
If no one else knows i happy to do a little research and find out.

https://godsword.org/pages/bible-translation-guide
https://www.chapter3min.org/bible-translations-comparison-charts/


Could you change it a little and allow them to download the recommended
version directly without having to search for it. Maybe it already works
like that?

So the text would be:

*NIV*
*This popular translation is not available due to the Copyright Holder not
granting us distribution permission. We recommend the 'Plain English
Version' as a good alternative. Click to download it. (PEV)*


___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
amplified is also often requested

**Comment by tuomas2** [comment]
> Nice, that is good. NASB for sure. Probably good replacement for the ESV. I would try to include some easy reading versions as well like GodsWord or BBE or PEV. I dont know which of them are good - i havent read them enough. If no one else knows i happy to do a little research and find out. https://godsword.org/pages/bible-translation-guide https://www.chapter3min.org/bible-translations-comparison-charts/ Could you change it a little and allow them to download the recommended version directly without having to search for it. Maybe it already works like that? So the text would be: *NIV* *This popular translation is not available due to the Copyright Holder not granting us distribution permission. We recommend the 'Plain English Version' as a good alternative. Click to download it. (PEV)*

Too fancy :-P 

i.e. good idea but I don't feel motivated to make such implementation due to higher complexity it adds, related to smallish overall benefit.
