### ISSUE TITLE
Modal for verse click is becoming full / congested

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1311]
I think having 6 icons on the modal is a bit congested, especially on a narrow device like mine.

My suggestion would be to have 4 icons in a row (or maybe 5), and the last icon being "More". Clicking more would show the second row with the rest of icons. 

That way perhaps we could even add a "Highlight" button. "Highlight" would simply be shortcut for 1. add bookmark, and 2. apply label that is configured for highlight. This highlight feature would probably require new strings and therefore would be in 4.1+

![image](https://user-images.githubusercontent.com/35117769/125486371-fad8988b-28c4-4cb4-b0ed-b27e62adff3d.png)

**Comment by tuomas2** [comment]
I don't really get what would be the point of "Highlight" button? Most of labels are configured for highlight.

**Comment by tuomas2** [comment]
I agree that we can't add many more buttons without doing something to the layout.

**Comment by tuomas2** [comment]
4 was more beautiful than these 6. But I think it's still acceptable.

**Comment by bvahedy** [comment]
I was hoping we could add the find icon in there too. You promised😁

**Comment by timbze** [comment]
> I don't really get what would be the point of "Highlight" button? Most of labels are configured for highlight.

It's been awhile since we discussed it, but it would just be an easier way for Bible users who are not that advanced to highlight words and verses.

**Comment by tuomas2** [comment]
But what exactly is "label configured for highlight"? What would make a label such a label? 

I'm thinking that highlighting is already easy enough because:
- users get highlighting with gray color even if they don't add labels.
- We will have pre-configured favourite labels "red", "green", "blue" that they can easily add because recently added auto-popup label adjustment dialog.

**Comment by tuomas2** [comment]
I'm not sure if Speak function here adds much value, nor Find. Those are easy to use from main menu or from toolbar if they appear there. What do you think @agrogers ?

I'm thinking I could remove Speak to make it less congested.

**Comment by timbze** [comment]
> I'm thinking that highlighting is already easy enough because:

Highlighting is easy once a user understands that it's related to bookmarks and labels. But it's not straight forward to a user who doesn't know that from what I have seen.

> But what exactly is "label configured for highlight"? What would make a label such a label?

It would work like this:
1. User clicks highlight
2. Window would pop up with "red", "green", "blue" labels
3. User could tap one of them to set that label for that bookmark (no modal would appear)
4. In the window in step 2, the list could be modified to add other labels

This would be almost the same as favorite labels are now, but specifically tailored for new users who look for a "highlight" option. Perhaps the list could be the "favorite" list.

**Comment by bvahedy** [comment]
I like the fact that the speak icon starts from the verse you tapped on, as
oppose to bringing the verse up to the top of the screen, and for smaller
devices that don't show the icon on the menu bar, they have to navigate to
the burner menu and hit speak from there. That is too many steps, when you
can just do it in one tap.

Add for the find icon, it was when you tap and hold to select a word or
words, so that it takes you to the Find screen with what you selected.
Currently there is no way to do that. May be that discussion doesn't belong
here but in case it does.  Currently there is no way to copy a word and
paste it onto the find screen. It is very helpful especially when you are
searching Hebrew or Greek words, of course it also is helpful with English
searches.

I hope I'm not rambling on here, you would tell me if I was, right.

**Comment by agrogers** [comment]
> > I don't really get what would be the point of "Highlight" button? Most of labels are configured for highlight.
> 
> It's been awhile since we discussed it, but it would just be an easier way for Bible users who are not that advanced to highlight words and verses.

I like making things easier. Once we have some default labels, the first time user will just have to select it from the list. That is almost as easy as what you described. I have another option though.

**Comment by agrogers** [comment]
I like the extra icons. And I want to add more :D  But I agree that it is getting crowded.

Some thoughts:
- The purpose i had in mind for this dialog was to bring as much functionality, especially the common stuff, to the users attention.
- Putting it behind a 'More' menu is working against that a little. But a 'More' option is still better than leaving it only in the Hamburger menu.
- My original suggestion was to always show those buttons at the top. However Tuomas located them at the bottom after a label has been applied. Although i think the top is a little more beautiful, i think the bottom is more functional. So...
- That means that you can have any number of icons appearing in rows. I would suggest go with 4 or 5 icons per row and show as many rows as needed.
- These will appear either at the bottom or on the empty dialog. Both would work well and look good i think.
- I also agree it is logical to have a Speak icon. Yes, you can get to it from the Hamburger menu. And sometimes from the action bar. But if i want to start speaking at a specific verse, then this seems like a good place for it. @bvahedy had other good ideas.

Here are some other buttons that might be good to add:
- Dictionary search based on the word clicked
- Bible search based on the word clicked
- Strongs button based on the word clicked. If the word has a Strongs link, show the button. This would mean that the user doesnt need to show the Strongs links at all.
- Bookmark which applies the most recently used label (this would basically do what Tim proposed)
- Bookmark based on a whole row of colours - like what most Bible apps provide
- Copy (a one click option to copy the verse, perhaps just using the last Share settings.)
- Commentary button. I think there might be a case to have a button that opens a new window (or reopens an existing window) that shows a commentary. Basically it eliminates the steps of i) creating a new window ii) ensuring it is synced iii) choosing the correct document from the list.

I think there are more that have crossed my mind but I can't think of them at the moment. Any, I am not really arguing for any particular button at the moment, just for the concept that there may be buttons here or in the future that would be naturally located here.

**Comment by bvahedy** [comment]
I agree with Andrew on this one. The more icons the better.

**Comment by tuomas2** [comment]
> I like the extra icons. And I want to add more :D But I agree that it is getting crowded.
> 
> Some thoughts:
> 
> * The purpose i had in mind for this dialog was to bring as much functionality, especially the common stuff, to the users attention.
> * Putting it behind a 'More' menu is working against that a little. But a 'More' option is still better than leaving it only in the Hamburger menu.
> * My original suggestion was to always show those buttons at the top. However Tuomas located them at the bottom after a label has been applied. Although i think the top is a little more beautiful, i think the bottom is more functional. So...


Lol, you guys can't catch up my changes. It's top again since few builds.


> * That means that you can have any number of icons appearing in rows. I would suggest go with 4 or 5 icons per row and show as many rows as needed.
> * These will appear either at the bottom or on the empty dialog. Both would work well and look good i think.
> * I also agree it is logical to have a Speak icon. Yes, you can get to it from the Hamburger menu. And sometimes from the action bar. But if i want to start speaking at a specific verse, then this seems like a good place for it. @bvahedy had other good ideas.
> 
> Here are some other buttons that might be good to add:
> ...

If there are more buttons coming I can make it have horizontal scrolling. Though I'm not sure if that's nice option. Perhaps we should have 3dot-button after 4 items, and then those 4 visible buttons would be last used buttons. Or that user can even choose which buttons are shown. But I'm a bit hesitating that we would have a long row of buttons because it makes confusing feeling also.

**Comment by agrogers** [comment]
That is funny :D 

If the buttons are at the top then multiple rows may not work well. Button rows at the bottom feels like the best option to me. I grew to love the ugly duckling buttons at the bottom :)  

But let me try the new format before you change it again!

**Comment by tuomas2** [comment]
if there's not enough space it should behave like this:

![image](https://user-images.githubusercontent.com/5811789/125765451-2991b313-3d29-4cd0-9f68-6d8ee151446c.png)

**Comment by agrogers** [comment]
How about two lines for text?

**Comment by tuomas2** [comment]
Hyphenation does not work for non-english languages.

**Comment by agrogers** [comment]
Ah, I see what you mean. I was just looking at the icon that had two words.
