### ISSUE TITLE
Ensure contrast between label background and text is high enough

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1314]
In the edit lable panel when we set certain background colors the font color seems to be hard to read. Can we add the ability to change the color of the text lable. This way the user can choose how readable it will be when looking at bookmark lables.

**Comment by tuomas2** [comment]
instead of configurability, we should make sure contrast between background and text is big enough. I think @agrogers suggested this somewhere (?)

**Comment by tuomas2** [comment]
Can't find ticket so modifying this a bit

**Comment by agrogers** [comment]
Yes, i posted some code at one stage. The other option would be to allow
them to set either white or black text. That is one more setting to handle.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
I think it should be automatic

**Comment by agrogers** [comment]
Automatic is best.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Let's see what this automatization does... at least fixed this issue but does it cause undesired side effects?

**Comment by bvahedy** [comment]
This works beautifully so far.
