### ISSUE TITLE
G-Droid shows app info only in finnish

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1317]
> Hi Tuomas, just wanted to let you know that I've just
> tried G-Droid (an app store alternative to F-Droid) and
> for some reason it shows And Bible as "Raamattu", with
> full info in Finnish, giving the impression that the
> app is only available in that language. I'm not sure if
> that can be fixed somehow, but I thought I'd let you
> know just in case.

**Comment by timbze** [comment]
Looks like G-Droid is just an alternative client app for F-Droid repository. Makes me think the issue should be raised with G-Droid developers.

![Screenshot_20210715-055619.png](https://user-images.githubusercontent.com/35117769/125784353-0639e67d-500d-4ee3-94fe-b78899d4152a.png)

**Comment by tuomas2** [comment]
I was thinking to check it first myself so I know if it's user error or what.

**Comment by tuomas2** [comment]
![Screenshot_20210715-151604](https://user-images.githubusercontent.com/5811789/125786556-cc0448ff-bfc8-48ae-ad0f-e7d2f1796d9c.png)

**Comment by tuomas2** [comment]
Can't reproduce on my mobile phone ^
