### ISSUE TITLE
Bookmark multiple verses with a click 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1319]
I'm sure this must be in another ticket but I couldn't find it.

Now you have got the cool single click verse action dialog working it seems almost capable of selecting multiple verses. I can see it working like
- Click a verse and the dialog shows
- click the same verse again and the dialog is hidden (as it does now)
- click empty space and the verse is deselected and the dialog hidden 
- click a different verse and all the verses between it and the first verse are selected. Applying a bookmark applies it to all selected verses.
- Maybe it is possible to also bookmark non consecutive verses?

**Comment by tuomas2** [comment]
> I'm sure this must be in another ticket but I couldn't find it.
> 
> Now you have got the cool single click verse action dialog working it seems almost capable of selecting multiple verses. I can see it working like
> 
> * Click a verse and the dialog shows
> * click the same verse again and the dialog is hidden (as it does now)
> * click empty space and the verse is deselected and the dialog hidden
> * click a different verse and all the verses between it and the first verse are selected. Applying a bookmark applies it to all selected verses.

I was thinking about this but I'm using all the time random backdrop click to close modal. I think closing modal should be easy as it's done all the time, especially now that this ambiguous selection modal easily comes up accidentally. Making multiple verses bookmark thus would require an extra button (added in ambiguous bookmark modal) that would change the mode how backdrop clicks are handled.

> * Maybe it is possible to also bookmark non consecutive verses?

It's not possible.

**Comment by agrogers** [comment]
And if the modal is big it will cover the clicked verse which means the
only way to close it would be with the close button which is a little
clumsy.

**Comment by tuomas2** [comment]
You can suggest ui with icon button.  Though I guess I can figure out something myself too...  I think this is perhaps better to implement. I was missing this feature many times in our church camp.

**Comment by agrogers** [comment]
Ah, is that where you were on the weekend?

Re multiple verses bookmarking, we can do it as you know through the text selection option. That is probably good enough for me. But single click is definitely easier.

I will think about it too.

**Comment by tuomas2** [comment]
Okay it looks like this now:

![Selection_157](https://user-images.githubusercontent.com/5811789/126632318-746c2fe0-2fd6-4e96-afee-3b9d4b044616.png)

I just added +-button to toolbar. Perhaps not best UI, suggestions welcome :-)

**Comment by agrogers** [comment]
I think I like it. Let me try it out 😊
