### ISSUE TITLE
Speaking a entry from Smith's dictionary raises an error

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1323]
Originally raised here by me: https://support.andbible.org/scp/tickets.php?id=631
The issue seems to be reproducible.

![image](https://user-images.githubusercontent.com/13920678/125901691-10a4e265-2830-43f5-b1ff-08d130a58a8a.png)

**Comment by tuomas2** [comment]
Fixed by 4983bb97929215d18665deb374f66f71d296bec9
