### ISSUE TITLE
export studypad in html, txt, even pdf if possible 

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1328]

**Comment by agrogers** [comment]
This was requested by my friend also. Once you have some notes prepared for, say, a bible study say, it is much easier to use those in a printed or modified form. Order of priority in my mind is:

1. html / rich text
2. txt
3. pdf

**Comment by tuomas2** [comment]
txt might not make much sense. pdf might need to be add on due to large lib addition.. maybe html only to begin with.

**Comment by agrogers** [comment]
Perhaps send them straight to Google document?

**Comment by tuomas2** [comment]
![Screenshot_20211028_170344](https://user-images.githubusercontent.com/5811789/139272001-21cd72ba-3030-4c33-8028-905033a075ce.png)
