### ISSUE TITLE
Bookmarking with continuous scroll reloads the current window

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#133]
Tested with current development (https://github.com/mjdenham/and-bible/commit/37f08ba4006a996536f367c5842466d4f6fce011)

- Scroll down such that two chapters are visible
- Create bookmark on 1 verse (on either visible chatper)

- Expected: bookmarking is done without current window reloading
- Actual: current window is reloaded after bookmarking.

I'm not sure if there is something in the implementation that makes this necessary, but if it can be easily avoided then this should be fixed.

**Comment by mjdenham** [comment]
It has always reloaded the screen after adding a bookmark, hasn't it?  It does this because, otherwise the bookmark icon would not be shown, or am I misunderstanding the issue?

**Comment by tuomas2** [comment]
It does not flash the screen. And even with continuous scroll, it does not seem to flash the screen when only 1 chapter is visible in the window. Do you think you can now reproduce the issue that I explained? If not I'll produce an example video.

**Comment by mjdenham** [comment]
The flash you are seeing may be the second chapter being redisplayed a split second after the current chapter.  I am not seeing a horrific flash - I have always seen a bit of a flash after creating a bookmark.  Anyway the chapter(s) will need to be redisplayed after a bookmark is created so the icon is shown.

In summary, if you still think there is a problem I will need a video or some further explanation.

**Comment by tuomas2** [comment]
https://youtu.be/Slsl7B_Si1U sorry about  terrible sound. This is just minor inconvenience.

**Comment by tuomas2** [comment]
Won't fix.
