### ISSUE TITLE
Change the label color from black to something slightly less black

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1333]
Black is just a little too harsh for my eyes and doesnt fit with the rest of the app which is mostly gray.

Changing it to "#353535" looks ok to me. 

![image](https://user-images.githubusercontent.com/13920678/126026016-d17997bf-66a2-4a97-af8d-b6e994f3d56d.png)

**Comment by tuomas2** [comment]
Hmm is this now because of "automatic" color change? Perhaps this should be still white font? Should we fine-tune it still?

**Comment by bvahedy** [comment]
If you go too lite then it may not be readable especially with yellow
background. Whatever you do test it with yellow or lighter colors for
readability.
Personally I like how it looks now.

**Comment by agrogers** [comment]
Black (or rather dark) is good and the only way I think you can get it
clearly readable. I liked all white text but this is a practical solution.
I guessed your code flips to dark text when it passes some threshold.

**Comment by tuomas2** [comment]
Yes it does but is the threshold good?

**Comment by agrogers** [comment]
I haven't used it much so not sure at the moment. Let's wait a while and
see.

**Comment by agrogers** [comment]
Let me know where the code is and I can fiddle with it. I have found a few
colors where it seems a bit weird. Your time is probably better spent on
other issues.

**Comment by agrogers** [comment]
Also, some very similar colors have both black and white text.

![image](https://user-images.githubusercontent.com/13920678/126101946-276f093c-d377-42f8-8f44-281050da5634.png)
