### ISSUE TITLE
Add a maximise button to the edit note toolbar

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1339]
I find i often want more room to type my note. There are two options:
1. Add a button to easily maximise the window. I know that i can do this from the Window button - which is what I do presently. But that is a two click action and kind of away from the workflow. A button here I think would be good.
2. Even better would be if that button would take the note to its own screen where i can only see the note and nothing else. So it looks just like a normal edit window we might find in any app. That would give maximum space for entering notes (no margins, toolbar attached to the very top of the screen, no labels, no dialog header etc etc)

![image](https://user-images.githubusercontent.com/13920678/126040889-14052df5-e7be-41ec-860c-b255d4045544.png)

![image](https://user-images.githubusercontent.com/13920678/126041182-1e2821c3-d2be-4582-819b-4265ac29761b.png)

**Comment by agrogers** [comment]
This issue is probably irrelevant for tablets - they have ample space for entering notes even with window margins and padding.

**Comment by tuomas2** [comment]
I must admit I don't understand people who use small on-screen keyboard to write notes on and bible :-P

**Comment by agrogers** [comment]
I am just a poor missionary boy ;-)

**Comment by agrogers** [comment]
I don't need this anymore - i used the swipe up on the window button to achieve it.
