### ISSUE TITLE
Intercept Bible URI-s and URL-s

### ISSUE THREAD

**Issue by ildar** [AndBible/and-bible#134]
As you (Martin) wrote yourself:
вт, 2 мая 2017 г. в 2:01, Martin:
> There are some standard Sword uris. You will find reference to these in UriAnalyzer and use in LinkControl. They are specified in https://www.crosswire.org/wiki/Frontends:URI_Standard

Actual reference is now at: http://wiki.crosswire.org/Frontends:URI_Standard

It's a common practice for Android apps to react on related URIs and URLs. This generally help a lot with integration to other apps and opens a lot of customization opportunities.
The support code shouldn't be complicated. Please consider adding. Thanks.

**Comment by ildar** [comment]
FYI this issue once was at old tracker: http://code.google.com/p/and-bible/issues/detail?id=188

**Comment by ildar** [comment]
related: https://github.com/YakushevVladimir/BibleQuote-for-Android/issues/22 (in Russian)

**Comment by tuomas2** [comment]
Related or duplicate #64

**Comment by timbze** [comment]
Closing as duplicate of #64
