### ISSUE TITLE
Create a way for notes not to highlight the whole verse.... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1343]
Currently there is no way to differentiate a bookmarked verse from a verse that has just a note since they both highlight the whole verse or selected word(s), though the pencil icon give you some indication.
 In the lable setting I tried to select the color white as a highlight so the verse only shows the pencil icon, but the icon is to dim and is hard to see. If there is a way to pick a color for the pencil without highlighting the verse that would be great.

**Comment by agrogers** [comment]
This is something I would probably use for sermon Notes. I don't really
want them to show the verse highlighting. Just showing the icon is a good
idea.

**Comment by tuomas2** [comment]
Marker-only bookmarks.  I think it might be good idea. But needs strings so 4.1+

**Comment by agrogers** [comment]
'marker-only bookmark' or 'marker-only label'? 

Adding another option like:
**[ ] No highlighting**
[ ] Use underline for selection
[ ] User underline for whole verse

If the first box is ticked then the other two are disabled (and unticked)

**Comment by bvahedy** [comment]
Do we have to wait for 4.1? Can't we use some existing words like "no label" with a checkbox where underline options are.

**Comment by tuomas2** [comment]
Phrase "No label" does not exist in strings.xml.

**Comment by timbze** [comment]
One thing to remember, AB will quite possibly never have another upgrade as big as this one, and therefore could easily have faster update cycles. So you might not need to wait a year for an update... 

Not speaking for anyone else's plans or guaranteeing anything though 😊

**Comment by tuomas2** [comment]
I agree. And beta for 4.1 is probably rather soon after 4.0 is released. This is one of the first 4.1 features that will be implemented most likely.

**Comment by tuomas2** [comment]
Implemented
