### ISSUE TITLE
problem restoring dictionary after backup... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1346]
Using AB backup, I backed up the real-strong dictionary and passed on the zip file to Andrew. He upon restoring the dictionary has all the carriage returns missing from the AB unzip restore process.
This is what he got:
![Screenshot_20210718-082113_Teams](https://user-images.githubusercontent.com/46405809/126072916-2e2eeefe-4608-4caf-9f20-cabc05ae85f2.jpg)

**Comment by bvahedy** [comment]
It should look like this:
![Screenshot_20210718-083020_Bible Study](https://user-images.githubusercontent.com/46405809/126073055-2364ec63-f7cc-4377-b5a1-d23e0990c603.jpg)

**Comment by agrogers** [comment]
A restart solved that problem as you thought it might Ben.

**Comment by bvahedy** [comment]
Ok, I'll close the ticket I opened.

**Comment by agrogers** [comment]
Maybe there is a bug there though. I dont think it should require a restart.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment]
Your call, open the ticket if you feel it needs to be looked at.
