### ISSUE TITLE
Hide on-screen navigation bar in full-screen mode

### ISSUE THREAD

**Issue by mjdenham** [AndBible/and-bible#135]
Martin, it looks like the code change for this would be pretty simple: in the call to setSystemUiVisibility() in setLightsOutMode(), replace SYSTEM_UI_FLAG_LOW_PROFILE with SYSTEM_UI_FLAG_IMMERSIVE in conjunction with SYSTEM_UI_FLAG_FULLSCREEN and SYSTEM_UI_FLAG_HIDE_NAVIGATION, i.e.,

mContentView.setSystemUiVisibility(View.SYSTEM_UI_FLAG_IMMERSIVE | View.SYSTEM_UI_FLAG_FULLSCREEN | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION);

The only catch I can see is that this flag was introduced in Android 4.4 API, so if you are holding back and wanting to maintain compatibility with pre-KitKat APIs (which seems a little overly conservative), then you couldn't switch to using immersive mode.

See uservoice: https://andbible.uservoice.com/admin/forums/100177-general/suggestions/31445623-hide-on-screen-navigation-bar-in-full-screen-mode

**Comment by tuomas2** [comment]
Full screen mode was improved in 3.0

**Comment by ericjding** [comment]
Nice! Thanks for working on this. I've got the latest update, and I see this working now, but the animation when I switch to full-screen mode is a little unexpected and unattractive. It looks like the black background for the navigation bar slides downward first, followed by the three (white) navigation icons sliding down afterward.  I am using stock Oreo 8.0, fairly close to vanilla Android, on a Sony Xperia X Compact. Is this animation sequence controlled by AndBible, or is it simply the way that Android transitions to immersive mode?

**Comment by tuomas2** [comment]
You are right it is not as nice looking as for example with Google Docs. Pull requests are welcome☺️

**Comment by ericjding** [comment]
So... I'm not at all familiar with how Android works in this regard, and I haven't looked at the code change you made to address this issue. Do you control the animation/background of the navigation bar, or is that all effectively dependent on Android once you set the UIVisibility flags? Maybe once I understand more how you implemented the change, I can give some thought about fiddling with the code.

**Comment by tuomas2** [comment]
Check out net.bible.android.view.activity.page.MainBibleActivity#toggleFullScreen

System UI (bottom navigation bar, system bar) animation is not controlled by us, but toolbar and other UI elements are.
