### ISSUE TITLE
What does the red lock icon mean on a document?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1350]
And if it is not documented, should we add it to help somewhere?

![image](https://user-images.githubusercontent.com/13920678/126100912-f281b5fa-4253-4e09-aa26-1b642cbb3b51.png)

**Comment by tuomas2** [comment]
Okay in downloads it remains mystery. but when you download the module and try to open it via "choose document", it gives you this screen:

**Comment by tuomas2** [comment]
![Screenshot_20210719-100303](https://user-images.githubusercontent.com/5811789/126117086-ed73d5b3-d0cd-4263-9cb7-1264055c2f9c.png)

**Comment by tuomas2** [comment]
And module then has responsibility to inform how to obtain unlock key in unlock info. Like this:

**Comment by tuomas2** [comment]
![Uploading Screenshot_20210719-100433.png…]()

**Comment by tuomas2** [comment]
![Screenshot_20210719-100433](https://user-images.githubusercontent.com/5811789/126117258-3452f949-3131-4930-a66c-5b09397bdd58.png)

**Comment by tuomas2** [comment]
![Screenshot_20210719-100433](https://user-images.githubusercontent.com/5811789/126117296-558ada18-960c-4904-b635-a90d7026d0b0.png)

**Comment by agrogers** [comment]
Thanks!
