### ISSUE TITLE
Ensure all help dialogs are consistent and 'helpy'

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1351]
This style is good:

![image](https://user-images.githubusercontent.com/13920678/126101281-39475da0-1ead-40ef-98b4-d8ce8f8f9fb5.png)

This style i don't like:

![image](https://user-images.githubusercontent.com/13920678/126101272-c4683e78-ca83-4a42-bdfb-2d30719aad95.png)

**Comment by tuomas2** [comment]
Solution?

**Comment by agrogers** [comment]
Oh, just make the second one like the first one. No header, no X, just a close button. That's easy, yes?
