### ISSUE TITLE
Multiple shades for the same label color - is it good?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1352]
Hi guys

Below is an example of the different blue colors for the one label. I think we have:
1. Label color
2. Study Pad color
3. Highlight color

I think the highlight color needs to be different (ie transparent)
But do the first two need to be different?

![image](https://user-images.githubusercontent.com/13920678/126101655-d98250b4-bbdc-42b5-90af-516146ccd598.png)

**Comment by tuomas2** [comment]
I believe we can manage with 2 shades (?)

**Comment by agrogers** [comment]
Yes, i think so too, especially with your new code for changing the text color
