### ISSUE TITLE
Hidden selection bookmark; icon shows in other Bible versions 

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1357]
**Describe the bug**
Make a selection bookmark (few words) in KJV with label "A" and then open the verse in NASB in a workspace with label "A" hidden. It shows the bookmark icon after the verse, but it should not. Full verse bookmark does not show. 

**Bug was found on And Bible version**
Build 534

Screenshot shows top window in KJV without bookmark, because it's hidden. Bottom window shows the bookmark icons in NASB. 
![Screenshot_20210719-070353.png](https://user-images.githubusercontent.com/35117769/126164830-eeba3ff9-d695-4b47-bbaf-96bbe8a9a640.png)

**Comment by tuomas2** [comment]
just to clarify:
expected result: because it's hidden label it should not show in either one

**Comment by tuomas2** [comment]
@timbze please test this

**Comment by bvahedy** [comment]
Can someone tell me who we would want to hide bookmarks?

**Comment by tuomas2** [comment]
It kind of works as a workaround of #1343. I'm having one "hide" label, which I add to some bookmarks that are primarily for sermon notes (for example, longer passage of text).

**Comment by tuomas2** [comment]
But someone might want to add sermon note labels as hidden labels. 

Makes me think if #1343 is necessary after all...

**Comment by timbze** [comment]
@tuomas2 this works as expected now but there's another related issue, I guess I should make a new issue for that
