### ISSUE TITLE
Remove stripe in workspace sync icon

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1359]
![image](https://user-images.githubusercontent.com/5811789/126199636-986e4553-983e-49a4-a3a3-4e45fdccac03.png)

What do you think?
It looks more like a monitor (which it is supposed to look like I guess)

**Comment by tuomas2** [comment]
Maybe monitor does not convey idea of workspace very well, and it is also inconsistent with "Workspaces" icon (which is too complex most likely for small sync icon)

**Comment by bvahedy** [comment]
How about putting multiple squares inside the monitor and remove the stand
for the monitor. This way it shows a space with multiple windows within it.

**Comment by agrogers** [comment]
I like the big workspace icon but when made small and put on a circle it
just looked unidentifiable. I was thinking of changing the big workspace
icon to match the small. But something needs to change, I agree.

**Comment by timbze** [comment]
Why the extra icon on top of the icons anyway? I probably am late to the conversation, but that's my thought.

I only see "Text options - St...". My workspace name is "Study" but if I didn't know I would have no idea what the "St" stands for.
![image](https://user-images.githubusercontent.com/35117769/126227847-e2e8f46e-9730-4cb0-87e6-83c2ec1c181a.png)

I think the toolbar could simply say "Text options". And then at the top of the window (under toolbar), have "Workspace (Study)"

**Comment by agrogers** [comment]
We are trying to differentiate between workspace settings and window
settings. My limited end user testing made clear to me that people were
getting confused as to which setting they were changing.

So the overlayed icon gives a visual cue that this setting is different to
the other setting.

There are three variations now.
1. A workplace setting that has the overlay in gray
2. A window setting that is using the workspace setting (ie in sync) - it
has the overlay icon only in green
3. The window setting which is not in sync with the workspace - it has no
overlay icon.

I feel like this is a step forward from the old sync and not in sync icons.
This is trying to make a clear link back to the Workspace. Better icon
choices might help there. But I am open to suggestions.

**Comment by timbze** [comment]
In one sense it might be better but it still leaves users guessing what the icons mean. Most probably won't even think about a special meaning behind the icon. That's why my suggestion is that it be clearly written somewhere what is affected by changing the settings.

But looking again, the easily-accessible help icon will already be a big improvement too.

**Comment by agrogers** [comment]
To start with, the overlay icon and the workspace icon need to be the same.
It is actually the same monitor just reversed. But no one would know that.
Still, it requires explanation - it is definitely not something that is
immediately obvious. I don't think it can be made obvious with icons alone.

**Comment by agrogers** [comment]
I have made a pull request which includes new workspace icons
