### ISSUE TITLE
Hidden bookmarks inconsistent in created document vs other document

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1361]
**Describe the bug**
1. Create 3 bookmarks on 1 verse with the same label in KJV document
2. Hide the label from step 1 in the workspace
3. Open KJV and tap the first part of the verse -> verse click modal opens with 1 bookmark showing
4. Open NASB and tap the first part of the verse -> verse click modal opens with all 3 bookmarks showing

Maybe this should be discussion instead of bug...
- I understand that NASB doesn't know which words are which bookmark, but should it even show the bookmarks that have only a hidden label?
- Should KJV even show the bookmark if it's a hidden label? There's no indicator on the verse that it has a bookmark

**Bug was found on And Bible version**
Build 534

Relates to issue #1357

Screenshot showing only 1 bookmark in KJV window, but 3 bookmarks in NASB window.
![image](https://user-images.githubusercontent.com/35117769/126217720-9505e1bd-3e90-4e2a-86f0-d6d75e7870a3.png)

**Comment by timbze** [comment]
Another side effect of this issue

1. Tap a verse to open the single click modal
2. Tap another verse to hide the modal, if you tap where there is a hidden bookmark it will not hide and instead just open the modal for that verse / bookmark

**Comment by agrogers** [comment]
That last interaction seems like a feature to me. But I am easy either way.

**Comment by tuomas2** [comment]
OP is a feature, not a bug, I would say. selection bookmarks work differently in the document in which they were made.

> Another side effect of this issue
> 
> 1. Tap a verse to open the single click modal
> 2. Tap another verse to hide the modal, if you tap where there is a hidden bookmark it will not hide and instead just open the modal for that verse / bookmark

This, on the other hand was a bug, and I fixed this.
