### ISSUE TITLE
Bookmarks duplicate on verse

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1363]
From https://support.andbible.org/scp/tickets.php?id=644

**Describe the bug**

**Bug was found on And Bible version**
Build 4.0.534-beta#afa284d

**To Reproduce**
1. Put app in night mode
2. Create 3 windows, KJV, NASB, NET
2. Create 2 word selection bookmarks on Romans 12:13 KJV
3. Open only KJV and NASB windows -> NASB is showing the bookmark icon and x2
4. Press home button
5. In task list remove And Bible
6. Open And Bible -> you now have KJV and NASB showing properly
7. Open NET window -> KJV and NASB windows reload
8. NASB now shows bookmark icon and x2 2 times in a row
9. Also, clicking NASB verse now shows the bookmarks 2 times in modal, so there are 4 bookmarks in total, or 2 times each

**Expected behavior**
Bookmarks should NOT duplicate.

**Screenshots**
In support desk

**Comment by tuomas2** [comment]
I did not get point 7 onwards to reproduce (windows do not reload). Sync is on.

**Comment by timbze** [comment]
Just found out it only happens in night mode, updated OP
