### ISSUE TITLE
Speak icon placement as bookmark inconsistent... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1378]
Two issues:

1) when tapping on the head set icon on the top menu bar the speak tool bar appears at the bottom of the screen but it does not start speak. You have to tap on the play icon to start to he speak. Whereas in the action tool bar tapping on the speak  icon starts speak automatically.

2) as you can see in the screenshot the bookmark icon for speak sometimes appears after the verse number and before the verse in a linked window.

![Screenshot_20210722-162919_Bible Study](https://user-images.githubusercontent.com/46405809/126721716-02bd2eaf-95fe-4a70-b83d-dfa2c0ed390b.jpg)

**Comment by tuomas2** [comment]
what would be correct solution to 1.?

**Comment by agrogers** [comment]
For me the headphone icon in the action bar shows the speak button menu at
the bottom of the screen but does not play.

It seems to be working as I would expect.

**Comment by tuomas2** [comment]
I'm a little afraid of people pressing headphones icon accidentally in sunday services etc. That's why toolbar behavior was changed recently to be what it is now.

**Comment by agrogers** [comment]
It seems right to me - both menu and button show the toolbar

**Comment by tuomas2** [comment]
then it's purely implementation issue for me.. :-P Need to look at this...

**Comment by bvahedy** [comment]
Ok, if that's how you designed it I'm ok with it, just know that it in 3.3
it played the moment they touched the icon.

As for the bookmark speak icon placement before or after the verse number,
my preference would be before the verse no. But if it cause coding issues
with copy function then do as you see fit.

**Comment by bvahedy** [comment]
it seems that the icon for speak bookmark is placed after the verse number only for verses that contain some bookmark lables. For verses that have no bookmark lables the icon appears before the verse number. Hope this helps with troubleshooting the fix.

**Comment by tuomas2** [comment]
speak icon placement: won't fix. It's because verse number placement is sometimes a little bit non-trivial because there could be section titles etc before verse number.

How speak button behaves will be fixed in separate ticket. Now speak button is hidden until that.
