### ISSUE TITLE
Is it necessary to download the list of documents every time?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1382]
I find the overlay that appears when downloading a list of documents a little annoying. But it is more annoying when i see it multiple times in a session - every time i go to download documents.

How often do these document lists change?
Can we just get the list once per session?
Or even better, once per week?

There is a refresh button in the action bar but i don't see why that would be needed at present. If we refresh the list once a week then that button becomes useful.

**Comment by tuomas2** [comment]
- #1367

**Comment by tuomas2** [comment]
I just changed it from 10 days to 1 day https://github.com/AndBible/and-bible/commit/5289cd0b53c9ce18d078d4db8cbc5c1a6716256a

**Comment by tuomas2** [comment]
Toast message could be changed to (i) button on toolbar -> info dialog. Except perhaps first time ever.

**Comment by tuomas2** [comment]
Repository content change quite often @ crosswire

**Comment by agrogers** [comment]
Really? Then it feels like it hasn't been working. Every time I go into the
document list I am sure it throws up the toast screen saying it is
downloading.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by agrogers** [comment]
OK, but I dont think their changes would ever really affect me knowingly.
That is, only very occasionally do I see a document that I have which has
an update. And it would be hard for me to know that a new document has been
added to the collection.

Actually, that would be a useful filter option - showing all the documents
that have been added since the last time I visited here. Or since the last
update.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
one useful thing is that you see if repository is down or not. But that could be implemented without downloading listings too. 
And I think it is probably possible to check the change date of file on the server before downloading it.

**Comment by agrogers** [comment]
They all sound like good ideas.

I would be perfectly happy with that list updating only once every 10 days.
That way i wouldnt have to wait the few second each time i go back to the
documents download window.

If i want to see the latest list i will push the refresh button (which i
don't think I have ever pushed :-)

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment]
It would also be nice if every so often when the user enters the repository
it would check all the bible update dates and check against the repository
and display something next to each module that says a new update is
available.

**Comment by agrogers** [comment]
I think it does show an update icon already doesn't it? I'm sure I have
seen an up arrow.

Often though I don't know that the update is available. Having that shown
at the top somehow might be helpful.

**Comment by tuomas2** [comment]
Toast message was actually wrong even if no refresh was required (nor done). 

e62bc25ca29ae6ee695dfcc52d5d8da8265aa0a7

**Comment by tuomas2** [comment]
Optimized index etc downloads.
