### ISSUE TITLE
Do not allow a new user to exit the downloads list until all the documents have downloaded

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1383]
My friend got confused by the background loading of documents. 

1. He had a slow connection so it took a while to get the docs. 
2. He started the download, closed the download list, couldn't find the Bible he was trying to get. 
3. Went back into the download list which refreshed the list
4. Tried to download it again
5. And then repeated the whole process another time 
6. Eventually the Bible doc was there and the madness stopped :)

If we made the user wait for the downloads to complete then this would not be a problem. And there is really no point in showing the app without documents. 

Issue #1384 can help here.

**Comment by timbze** [comment]
I don't think preventing user from exiting the screen is a good idea, especially after first install is complete.

In my opinion it would be better to just show the download status a bit more prominently so it's clear that documents are being downloaded.

**Comment by agrogers** [comment]
I agree that the background download is good once you know what to expect
*and* if you already have most of the documents that you need.

But if this is a brand new install and you have no documents and esp if you
have a slow link then I dont think there is any point in taking the user
into the app when much of what they expect to be there is not there yet. It
is one of those features that provides very little gain for most new users
but can cause unnecessary confusion. I dont think the gain is worth
the downside.

By preventing the user I mean there should be something they can do while
they wait for documents to download. We could show the existing help
screens as a bare minimum. That is much better for a new install than
showing an app that is incomplete I think.

I think after that initial setup it can operate much as it is now, perhaps
with a slightly more prominent download progress indicator. Not sure where
that indicator would go though.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by timbze** [comment]
Ok I see what you are saying. Also I didn't realize both this and #1384 was about "new" install.

I think for new install this may be a good idea, if there's also the option then for a user to cancel certain downloads that have not downloaded yet.

**Comment by tuomas2** [comment]
We need to allow user to come back to "startupactivity" because there are other functions he could choose instead of downloading.  But perhaps downloading indication could be improved... perhaps there could be some "total progress" element, and cancelling should be possible.

**Comment by bvahedy** [comment]
If the user is downloading in the background and is trying to bring up
anything that is not there, we should check is there are any background
downloads in progress and display a message window that says background
download in progress for the bible you are trying to view or something to
that effect.

**Comment by agrogers** [comment]
OK, i have had a look at this on a slow connection. 
1. You can't exit the downloads window if no Bible has been downloaded
2. Documents that are being downloaded are not shown in the dropdown lists (Bible or commentary)
3. Its possible to download the same document a second time even when it is up to date

I think the problem my friend had was that he downloaded a document, couldn't work out how to open the document, and then went back to try and open it by downloading it again.

Some possibilities:
1. Show documents that are downloading in the dropdown lists eg 'NASB (downloading...)'
2. Show a little progress indicator somewhere, perhaps as a line at the bottom of the header action bar
3. Use the downloading time as an opportunity to introduce the new user to the software.

I think all of those options could be implemented together to good effect.

**Comment by timbze** [comment]
> cancelling should be possible.

- #874

**Comment by tuomas2** [comment]
Implemented doc download cancelling and showing always docs being installed on top. I think this is now good to be closed. Let me know if you still want something.

**Comment by agrogers** [comment]
Great. I look forward to trying it.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
