### ISSUE TITLE
Verse Reference Only Copy Feature

### ISSUE THREAD

**Issue by Dleemuse** [AndBible/and-bible#1387]
When copying a verse(s) is it possible to have a feature where only the reference is copied? I have often, wanted to be able to copy just the reference(s) and not the verse(s) themselves.

Thanks!

Deba

**Comment by gelafin** [comment]
Would a good implementation just add a "Reference only" option at the bottom of this list of sharing options?
![Screenshot_20220430-175307_Bible Study](https://user-images.githubusercontent.com/46856925/166127557-e68c29c7-c27e-4a25-9769-4d895195f9b1.jpg)

**Comment by agrogers** [comment]
That dialog has a lot more options now. But it needs a reference only option as well. I think I would put it at the top and when selected disables or hides most of the other options. 


![Screenshot_2022-05-01-09-03-17-073_net.bible.android.activity.jpg](https://user-images.githubusercontent.com/13920678/166129711-de9153aa-4b79-4750-b227-baa3cbff6647.jpg)

**Comment by agrogers** [comment]
Maybe 'Show reference only' should be the first indented option.

**Comment by gelafin** [comment]
I see, thanks! Agree that would be a good place for it.

I'll check the development version next time :)

**Comment by agrogers** [comment]
I think that is in the beta version too. You definitely should be using
that if you aren't already 👍 It takes quite a while to get to the public
release because of string translation.

**Comment by gelafin** [comment]
Interesting, the Play store shows I'm a beta tester, but my version of the app is 4.0.643#fa0aa5137 standard release. Fine for me to just reference my emulated version in Android Studio, though!

**Comment by tuomas2** [comment]
It is in develop branch, but we have not released any beta builds yet in Play Store yet. Alpha builds are available for develop brach (version numbers still match with production ones to make switching back and forth easy, and is possible because we do not have yet any migrations in develop): https://github.com/AndBible/and-bible/releases.

**Comment by gelafin** [comment]
@agrogers On second thought, would this layout be good for these options?

- Show reference
  - Abbreviate
  - With Bible version
  - At front
- Show verse text
  - Only selected text
    - With ellipsis (...)
  - With verse numbers
  - With quotes
- Advertise app

That would making showing and hiding verse text work the same as for the reference and advertisement.

**Comment by agrogers** [comment]
I have created a draft pull request for this. You can see it here:
https://github.com/AndBible/and-bible/pull/2178

The change is minor and simply hides the text of the verse.  Let me know if you have any extra suggestions.

![image](https://user-images.githubusercontent.com/13920678/173088052-1c9eeebf-ebca-419c-b2cb-e8a40f4ad280.png)

![image](https://user-images.githubusercontent.com/13920678/173087958-bc0a3166-aaa6-41ee-915e-cf8a419d8da8.png)

**Comment by gelafin** [comment]
awesome, looks great!

**Comment by agrogers** [comment]
Thanks for the suggestion. Hopefully i can look at it soon!

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by agrogers** [comment]
this has been done now I believe.
