### ISSUE TITLE
Should the verse and chapter numbers be linked to the chosen text color?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1389]
The numbers get quite hard to see on some backgrounds. 

Would it be possible to make them a shade of either the text or background color? Perhaps you could use the new forecolor algorithm to come up with something that works well on any background?

Some suggestions:
- make the numbers a half shade of the background color (if it is white then it would produce a mid gray, if it is dark blue then it would produce a light blue).
- I only have one suggestion :)

![image](https://user-images.githubusercontent.com/13920678/126854701-4fa2094c-5215-4e05-a740-606fc3ccc576.png)

**Comment by tuomas2** [comment]
I will quickly check if it's easy to implement.
