### ISSUE TITLE
If page content does not change, do not refresh

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1394]
When reading commentaries (like KingCommments) many verses have same content.
Sync makes page refresh when verse change.

From JSword we do not know if the content changes, until we fetch it from there. But then we could easily 
calculate checksum of the page content  and compare new page content to that. If it equals, do no 
page refresh.

**Comment by agrogers** [comment]
I like it.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by timbze** [comment]
I've wanted this for a long time! 😊 Just sadly haven't had much time lately to do much myself with AB

**Comment by tuomas2** [comment]
Little testing shows that <verse> tag is coming from jsword, with osis ref, so it does not work without tweaking jsword. But I'll look at this soon more, maybe it can be implemented with small tweaking.

**Comment by tuomas2** [comment]
Commentary verse tag is indeed JSword-generated, also pre-verse title tag (which is hidden anyway). That could be changed, no need to have them in commentary. Rather produce div and then my proposed approach will work.

**Comment by tuomas2** [comment]
Jsword hacking was not needed after all

**Comment by timbze** [comment]
I am so happy! Working awesomely! 🎉

**Comment by tuomas2** [comment]
broken..
