### ISSUE TITLE
Standard underline style does not seem to work on fancy documents

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1398]
The border underline I just implemented works fine but the standard underline does not. It does work for the verse numbers. Maybe to do with the font?

![image](https://user-images.githubusercontent.com/13920678/126866215-6d7452b4-cf1a-4a76-b5a2-73dc9b65e426.png)

**Comment by tuomas2** [comment]
custom selection underlining is ok but indeed whole verse underlining does not work. But that's custom css hack anyway, so I don't think it's very high prio. Perhaps something can be done to that particular custom module to make underline appear better (?)...

**Comment by agrogers** [comment]
This would work fine with the new proposal for underlining using the same
method you are already using for background highlighting.

**Comment by tuomas2** [comment]
I know but I'm not yet 100% convinced if we want to go there (will consider and try out when I have time, but according to its prio). This ticket is not great enough motivation for that.

**Comment by agrogers** [comment]
Agreed. This ticket is low priority.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
I think this was fixed by @agrogers new underline method
