### ISSUE TITLE
Reduce the precision of the color number and save some memory

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1399]
I think the precision of these numbers could be reduced a lot. They are repeated many times so there should be some positive savings in making them smaller. 

![image](https://user-images.githubusercontent.com/13920678/126867199-80279931-eff9-4dd6-a4ef-57ede975c7fc.png)

**Comment by tuomas2** [comment]
I'm not sure if it internally saves any memory because I believe those values are stored as floating point numbers. Just shown on dev tools as long text like that.

**Comment by tuomas2** [comment]
if you can prove that reducing precision saves memory, you can re-open :-)

**Comment by agrogers** [comment]
Oh, really. You are probably right. It was numbers like those that caused
my svg exports to be much larger than they needed to be so it was in my
mind.
