### ISSUE TITLE
Reading Plan Layout

### ISSUE THREAD

**Issue by unoriginalone** [AndBible/and-bible#14]
When the reading plan is viewed with limited vertical space, (in landscape or split screen) the passage buttons cannot be accessed. The lower Done button obscures the other interface items and they are drawn beyond the bottom of the screen.
I suggest allowing the layout to scroll in such situations.

**Comment by tuomas2** [comment]
If you have still this problem, please re-open this issue and provide a screenshot illustrating the problem.
