### ISSUE TITLE
Startup Crashes

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1401]
https://support.andbible.org/scp/tickets.php?id=656
https://support.andbible.org/scp/tickets.php?id=655

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=657

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=659

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=660

**Comment by tuomas2** [comment]
I didn't check individual cases but I believe these all were because of this stupid little bug.

**Comment by agrogers** [comment]
Wonderful. It was happening enough for me to start to think there was a
real issue to resolve.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
