### ISSUE TITLE
Change plus icon behavior on single-click modal

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1406]
In the latest beta build 537.4:
When tapping on a verse and bringing up the quick toolbar, the plus icon on the top of the tool bar, when tapped turns grey but nothing happens.
This also happens on  the modal window when trying to add a note.
![Screenshot_20210724-142315_Bible Study](https://user-images.githubusercontent.com/46405809/126881423-18c95c76-2414-433e-82d6-f780fb9e0d64.jpg)

**Comment by tuomas2** [comment]
after pressing plus you can select more verses

**Comment by bvahedy** [comment]
May be a toast msg for 3sec would be a nice way to say something like "you can now select multiple verses!"
This way we can eliminate many training videos to explain what the plus sign does.

**Comment by agrogers** [comment]
Yeah, it is not immediately obvious what it does. But I love the functionality - I meant to say well done to Tuomas for adding it.


Perhaps pushing the button should automatically highlight the next verse and update the verse number showing the extra selected verse. 

![IMG_20210725_130354.jpg](https://user-images.githubusercontent.com/13920678/126886313-8489676e-e9fe-4500-a208-f55e879ffe9c.jpg)

**Comment by bvahedy** [comment]
I like the functionality of it, but didn't really know what it is suppose
to do. I suspect most people will tap and hold and expand the selection
before realizing they can use the plus sign. That's why I suggested to
display a toast msg. I know you are not crazy about toast messages but in
this case it makes a lot of sense to display it for 3 sec.

**Comment by tuomas2** [comment]
I believe Andrew's suggestion makes it more obvious than what it is now. I also think that toast could be added, but that must be postponed to 4.1.

**Comment by agrogers** [comment]
Toast message is good when used sparingly like once per session or
something.

**Comment by agrogers** [comment]
Oh, and leaving that first toast message up long enough so people can read
it.

**Comment by timbze** [comment]
> Perhaps pushing the button should automatically highlight the next verse and update the verse number showing the extra selected verse.

I think this is a great idea
