### ISSUE TITLE
 "Select all"  in the Note modal selects beyond the model window... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1408]
When tapping on the Note icon at the end of a verse to view the note for the verse(s). A modal is displayed. If you tap and hold on a word within the modal window (note you are not entering the edit mode),  the action window is displayed, tapping on  "select all" will select the whole chapter behind the middle window as well as the note within the model. We need to only copy all the words displayed within the modal.

**Comment by tuomas2** [comment]
I'm afraid there's not much we can do about webview's built-in functions, unless we hide them and make our own function implementing something similar.

**Comment by tuomas2** [comment]
but I could re-check is there something that can be done on html/css level to define the "select all" scope

**Comment by tuomas2** [comment]
Does not seem to be easy to fix.
