### ISSUE TITLE
ESV2011 section titles often displayed in wrong locations (offset by one verse)

### ISSUE THREAD

**Issue by ericjding** [AndBible/and-bible#141]
Sorry if the title isn't quite clear. In AndBible 2.11.1.246, I've downloaded and am viewing the ESV2011 (ESV with Strongs numbers) module, and am finding that non-canonical section titles are often displayed in the wrong places, offset by one verse, if they are not at the beginning of a chapter.

For example, in Matthew 18, "Who Is the Greatest?" shows up correctly before verse 1, but "Temptations to Sin" is displayed before verse 6 instead of before 7, "The Parable of the Lost Sheep" is displayed before verse 9 instead of before verse 10, etc. This issue is reproducible on both my tablet (running Android 6) and my phone (running Android 7).

Notably, I do not see this issue arise with NET or ESV2001. However, if I view the same passage in ESV2011 in Xiphos or BibleTime on my Linux system, the titles are displayed in the expected and correct locations, so I strongly suspect the issue is with AndBible, not with the module itself.

**Comment by tuomas2** [comment]
net.bible.service.sword.SwordContentFacade#readHtmlTextOptimizedZTextOsis
fails with exception:
"At line 1, column 13294: no element found"

And fall back parsing mode is used instead.

So this is ultimately due to somehow corrupt document, 
but let's see if I can do something about it.

**Comment by tuomas2** [comment]
Another JSword based app BibleDesktop 2.0-beta renders this correctly. So indeed it looks like AB specific.

**Comment by tuomas2** [comment]
Fixed in beta (version 2.12.257)
