### ISSUE TITLE
Try putting text editor toolbar under text

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1410]
That's how Google Docs seem to do it on mobile app. Solves 2 issues

1) Toolbar is not hidden behind selection context menu
2) Toolbar remains visible even if text gets long

**Comment by agrogers** [comment]
Could be a good solution. And I like how there is no unnecessary padding
around the toolbar also ;-)

**Comment by tuomas2** [comment]
After doing this, your padding removal also looked better! So it's now in again (for now...)

**Comment by agrogers** [comment]
haha. You will grow to love that ugly duckling :)
The padding does have some issues that I dont like too.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
