### ISSUE TITLE
ePub reader

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1414]
Make it possible to read user-provided ePub files as generic books.

**Comment by cmahte** [comment]
If you go that far, How including epubs as a type in the sword repository. that is, include support for the epub + the conf file in the same directory structure as other sword works. Noteably, scripture text and commentary wouldn't work. but for Genbooks it is possible.

**Comment by tuomas2** [comment]
Possible

**Comment by tuomas2** [comment]
I'm not sure which one is easier: to support ePubs natively, or to have converter from ePub to genbook.

**Comment by cmahte** [comment]
The benefit to Andbible (all sword apps) supporting epub natively is that
configuring a repository of books to be BOTH a library for plain ebook
readers, as well as sword front ends becomes possible. The epubs might
include a few extra metadata facts internally (to properly support links to
scripture,) but would be 100% epub compatible and loadable into any reader.

I love Android, but I also love e-ink devices which function for weeks on a
single charge. A library that supports desktop, Android, and ereader all in
one file... That would make publishing less complex.

**Comment by tuomas2** [comment]
I'm planning to support Android e-ink devices in the future (like Onyx Boox devices) #1126

**Comment by agrogers** [comment]
Are we talking about making AB a general eBook reader? If so, I like the idea. We already have a 'books' module. It would be great to allow more books. What I would also like is the ability to speak those books.

**Comment by tuomas2** [comment]
> Are we talking about making AB a general eBook reader? If so, I like the idea. We already have a 'books' module. It would be great to allow more books. What I would also like is the ability to speak those books.

AB is "general eBook reader" supporting only SWORD eBooks :-) We are talking about supporting ePub files in some level. 

For now, I think you can use fbreader (free and open source, btw) app to read aloud epubs.

**Comment by cmahte** [comment]
Ereader prestigio has more voices.

**Comment by tuomas2** [comment]
> Ereader prestigio has more voices.

Has its own TTS engine? Fbreader uses standard Anrdoid's TTS, like And Bible.

**Comment by cmahte** [comment]
It has it's own. I just looked, and it shows up in AndBible as "eReader
Prestigio" engine. So, the voices are available there just by installing
ereader prestigio.

**Comment by cmahte** [comment]
It shows the ereader prestigio engine in Andbible, but not the extra
voices. :-(

**Comment by tuomas2** [comment]
should at least add relevant strings before 5.0 release. Easy to implement and feeling motivated.

**Comment by cmahte** [comment]
The andbible alpha-715 crashes when I try to open it. Simple calculator does open and I am able to install epub files. 

Notes. The epub module lists the file name or something else to it as the chapter files. It works, but expected the table of contents text, not the file names. 

Also, I was hoping the epub file type would be associated with andbible. It might be and it's just because I'm using calculator, but if not.... That is when tapping on a downloaded epub, Android only lists play books and ereader prestigio as associated programs for this file type.
 
I'm using moto g 5g on Android 13.

**Comment by tuomas2** [comment]
> The andbible alpha-715 crashes when I try to open it. Simple calculator does open and I am able to install epub files.

I'll take crash reports when we pass alpha stage (-> beta) with this. 

> Notes. The epub module lists the file name or something else to it as the chapter files. It works, but expected the table of contents text, not the file names.

I might try to dig the real title from the HTML files. EPUB manifest file alone unfortunately does not give better outline.
 
> Also, I was hoping the epub file type would be associated with andbible. It might be and it's just because I'm using calculator, but if not.... That is when tapping on a downloaded epub, Android only lists play books and ereader prestigio as associated programs for this file type.

You guessed it correctly. Calculator does not associate but AndBible does.

**Comment by cmahte** [comment]
If I were to build an Epub to read in Andbible (when actually...) is there a way to form links in the Epub which AndBible will recognize as a link to scripture and pop or navigate to the related scripture using Andbible default? a specific sword module? 

Is this documented somewhere?

**Comment by tuomas2** [comment]
> If I were to build an Epub to read in Andbible (when actually...) is there a way to form links in the Epub which AndBible will recognize as a link to scripture and pop or navigate to the related scripture using Andbible default? a specific sword module?
> 
> Is this documented somewhere?

EPub format does not support links. I have implemented automatic parsing of bible links from AndBible so that properly formatted bible links should be intepreted as bible links, as long as they are contained within a single html tag. (for example, `<b>Matt</b> 1:1` would not be intepreted but `Matt 1:1` would be).

If you want to format links yourself, you better make normal Sword genbooks.
