### ISSUE TITLE
One-click behavior change proposal

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1416]
I'm thinking would it be better if when clicking a verse (anywhere), it would open in ambiguous selection modal all actions that are available in selected verse(s). So it would show all bookmarks related to that verse(s), preferrably also footnotes, and crossreferences. 

Bookmark click handlers would be removed except for markers, that would be "shortcuts" to bookmark modal. 

How does this sound like @agrogers etc?

**Comment by timbze** [comment]
I have not thought about this a lot, but I like that it's a small modal. Maybe a "more" button to see the rest? Just an idea

**Comment by agrogers** [comment]
Sounds interesting but I am not completely following. I think you are suggesting a small dialog (with a single icon for each bookmark) which takes you to a dialog just for that bookmark in which all the link icons (study pads, share, whole-verse etc) can be found. Is that correct?

**Comment by tuomas2** [comment]
I mean same modal that is now shown when you click a verse. 

At the moment when you click somewhere, it shows the actions (most importantly, bookmarks) under the click.
Instead, it would show actions (most importantly bookmarks) that are on the whole verse (any part), or multiple verses, if multiple verses are selected.

**Comment by agrogers** [comment]
OK, I think I understand now. A few thoughts...
- Suppose on the image below I want to work on a note for Justice. When I click now I get three bookmarks. Under this proposal I would get 7 - 4 shown plus blue, green,gray and purple. I'm not sure I like that. 
- It doesn't feel right to be shown things I didn't click on 
- however if they were shown in a different style then that would help. Say the three I clicked on in one group at the top and the three I didn't click on in a second group below it. 
- However I would make an exception here for cross references. I probably wouldn't show each individual reference or letter. I would add a new button below the current button row which would open all cross references for the verse(s) in the link window. 
- As to simplifying the display of individual bookmark boxes, I think that has merit. The Share buttons almost all do the same thing - I would rarely want to share an individual word. I do access the study pads via that dialog. And the labels to edit or remove. I don't really know how much more I could simplify it *and* save space. 
- I was actually wanting to go in the opposite direction. I wanted to add feature based on the specific word the user clicked. Say for example they click on 'Loving-kindness' there would be a button or link that says 'Search for loving kindnesses' and 'Lookup loving kindness in dictionary' and 'Get Hebrew definition' 
- To add in these last ideas might require reducing the amount of stuff on that dialog. I like this proposal potentially for that reason.
- I definitely think we should consider removing buttons users rarely click on.

![Screenshot_2021-07-26-17-21-41-621_net.bible.android.activity.jpg](https://user-images.githubusercontent.com/13920678/126949047-4cbbd094-3289-4fc7-a1a9-5664ceff87c1.jpg)

**Comment by tuomas2** [comment]
The motivation for the proposal comes from the impression that current highlight after one-click gives that we are seeing content for the whole verse.

We could perhaps show the content that is not due to direct click below those that are due to direct click, and perhaps even give some other visual cue (separator line etc).

**Comment by agrogers** [comment]
Yes, that is a good point. We are sending mixed messages. The buttons at
the top apply to the whole verse. But the labels apply only to what was
clicked.

I think for the average user it doesn't make any difference because they
are only ever bookmarking the whole verse. So the bookmarks that are shown
are exactly as you might expect based on the grey selection highlight.

This problem only applies to users who have selected part of the verse to
highlight. But for them it might not matter so much because they know what
they are doing.

I certainly haven't felt that it is displaying incorrectly. But I will use
AB with your comments in mind. And I will try and make a mockup of what I
think you are describing to see whether it feels better.

**Comment by tuomas2** [comment]
I don't think we need changes to UI (i.e. why make mockups?), just behavioral change. I'm thinking I'll try this out next time I have time to code (it shouldn't be huge change in code), and you can then test how it feels.

**Comment by tuomas2** [comment]
Okay this is now implemented.

**Comment by agrogers** [comment]
If it didn't require UI changes then I think I misunderstood something :)

**Comment by agrogers** [comment]
I have had a quick look at the implementation. The two images below show an example of what it did look like and what it now looks like. 

It feels a little overwhelming to me and a little harder to see the info I want when i click. Maybe it is information overload. The info i clicked on is at the top which is good. But if I really wanted to see the other bookmarks I could have just clicked on them. That process was neither hard or counter intuitive. Now I am seeing a lot of things I didn't click on.

So I am not sure this is a step forward. But I will keep using it and see how if it feels better tomorrow.

![image](https://user-images.githubusercontent.com/13920678/127089328-6e8ebd18-2e1a-4532-b550-fa92d29b4919.png)

![image](https://user-images.githubusercontent.com/13920678/127089400-d43d8050-ae4f-4525-8fd8-9f3c21bff935.png)

**Comment by tuomas2** [comment]
I don't think that will bother most users. Most users don't have separate highlighitng for every word in the verse :-)

But I'll also test and see how it feels. Let's see after a while. Now it feels more intuitive, i.e. makes more sense between highlight and what I see in modal.

**Comment by tuomas2** [comment]
4.1 suggestion might be to have "+ n items" button, which would show the remaining items. Though we do have pharse "More"  in our translated vocabulary, if we want to use it (perhaps with ellipsis, i.e. "More...") :-)

**Comment by agrogers** [comment]
> I don't think that will bother most users. Most users don't have separate highlighitng for every word in the verse :-)

lol, that was exactly my point before. For these people this change doesn't make make any difference - they probably highlight whole verses. So under the old method **or** the new one they would see *all* bookmarks.

> This problem only applies to users who have selected part of the verse to highlight. But for them it might not matter so much because they know what they are doing.

Your suggestion
> 4.1 suggestion might be to have "+ n items" button, which would show the remaining items

I think could work well too. But yes, I would like to use it for a week to see how it feels. I shouldn't make judgments about things before trying them for a bit.

**Comment by tuomas2** [comment]
> > I don't think that will bother most users. Most users don't have separate highlighitng for every word in the verse :-)
> 
> lol, that was exactly my point before. For these people this change doesn't make make any difference - they probably highlight whole verses. So under the old method **or** the new one they would see _all_ bookmarks.

I can still imagine people highlighting 1-2 words every now and then, and even making 2 such bookmarks in one verse. 
This change also makes it better for "hidden" bookmarks, they will be always under the line.

**Comment by agrogers** [comment]
Oh, i like the hidden bookmark functionality. Didn't think about that.
Maybe it is a little related to #1409 also.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by agrogers** [comment]
Hi Tuomas. I am warming to showing all the bookmarks for a verse :)  Here is a variation on what you have done that also includes an idea that I have been thinking about how to implement.

The word 'wisdom' below is the word that the user clicked on. The Hebrew lookup would be possible even without the Strongs numbers or links shown since I am guessing you know or can access that always. Possible could show all dictionaries the user has installed or just the most recently used one. The Bible would be the active or most recently used one. They could target a the current window or a window the document is already open in or some new window. I haven't really thought this through a lot. I like the more clear heading between the bookmark i clicked and the other bookmarks.

Oh, and the expanded nature could be remembered during the session. So if you like seeing all the bookmarks they would automatically open when viewing the dialog.

![image](https://user-images.githubusercontent.com/13920678/127255458-bff5f315-de47-46c2-8c39-3907da7539fc.png)

**Comment by tuomas2** [comment]
> Hi Tuomas. I am warming to showing all the bookmarks for a verse :) Here is a variation on what you have done that also includes an idea that I have been thinking about how to implement.
> 
> The word 'wisdom' below is the word that the user clicked on. The Hebrew lookup would be possible even without the Strongs numbers or links shown since I am guessing you know or can access that always. Possible could show all dictionaries the user has installed or just the most recently used one. The Bible would be the active or most recently used one. They could target a the current window or a window the document is already open in or some new window. I haven't really thought this through a lot. I like the more clear heading between the bookmark i clicked and the other bookmarks.
> 
> Oh, and the expanded nature could be remembered during the session. So if you like seeing all the bookmarks they would automatically open when viewing the dialog.

Created another issue about this proposal. I'm closing this issue now as it's implemented and it looks like we are more or less happy with it.
