### ISSUE TITLE
When playing audio on a car bluetooth device the track/author etc is not displayed

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1417]
When I play most things in the car (Audio Books, YouTube etc) it shows the title and other things on the screen. But when i was using AB to speak a passage it didnt show any details. It would be great if it showed the verse it was speaking. I have often wanted that when listening to audio books in the car.

![image](https://user-images.githubusercontent.com/13920678/126925293-ce44dc7d-c0f3-432b-91e7-39988c6b3618.png)

**Comment by tuomas2** [comment]
I tried to implement this when I implemented current tts functionality. But there were some challenges and I gave up. But it would be worth looking at it again at some point.

**Comment by tuomas2** [comment]
- #867

**Comment by tuomas2** [comment]
should be fixed
