### ISSUE TITLE
Transpose books of the bible grid to read from left to right.

### ISSUE THREAD

**Issue by steelwil** [AndBible/and-bible#142]
I think this would be easier to read. I find it difficult reading from top to bottom.

**Comment by cmahte** [comment]
I think the current order is fine, but I see value in providing the user
the ability to change the sorting, especially to alphabetical. New
believers struggle with canonical order, especially in areas that have a
mix of bible orders present.

How about a setting. A global option button to choose the sort order for
verse chooser. I don't know if it should also affect scrolling (to next
book) or not, but that might be worth considering.

Field 1: Sort Horizontal (button with an right arrow), Sort Vertical
(button with a down arrow)
Field 2: Sort a Dropdown list: (Per module versification, Protestant,
Catholic, Orthodox, Jewish, Alphabetical, Chronological. etc.)

**Comment by oxr463** [comment]
## Responsive interface

Instead of showing a grid, is it possible to have each book on its own line?

**Current**

| | | | | | |
|-|-|-|-|-|-|
| Gen | 2Ki | Isa | Nah | Rom | Tit |
| Exo | ... | ... | ... | ... | ... |

**Desired**

| |
| - |
| Genesis |
| Exodus |
| ... |

--

This would be helpful for smaller screens. I am always accidentally pressing the wrong book on my phone, (Tracfone Alcatel Pixi Eclipse w/ 4.0" display).

Resources: https://github.com/googlesamples/android-ConstraintLayoutExamples

**Comment by oxr463** [comment]
Here is the original `choose_passage_book_menu` file:

```
<?xml version="1.0" encoding="utf-8"?>
<!-- The main menu accessed via Menu key

 @author Martin Denham [mjdenham at gmail dot com]
-->
<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:appcompat="http://schemas.android.com/apk/res-auto" >


</menu>
```

Which produces the following result:

![Choose Book](https://i.stack.imgur.com/PeP9P.png)

And here is the new one with changes applied to it:

```
<?xml version="1.0" encoding="utf-8"?>
<!-- The main menu accessed via Menu key

 @author Martin Denham [mjdenham at gmail dot com]
-->
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:appcompat="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
<menu></menu>
</ScrollView>
```

Which crashed the application:

![App Crash](https://i.stack.imgur.com/UabYp.png)

Source: https://github.com/oxr463/and-bible/tree/feature-select-book

See also: [Android TableLayout does not scroll vertically](https://stackoverflow.com/q/10036476/8507637)

I submitted this to StackOverflow in December and they closed it, (See: https://stackoverflow.com/q/59350203/8507637).

**Comment by timbze** [comment]
Was implemented by #1122

**Comment by oxr463** [comment]
@timbze should I open a separate issue on using full names for the books of the Bible instead of abbreviations? e.g., Genesis instead of Gen.

**Comment by tuomas2** [comment]
Yes, please open

**Comment by timbze** [comment]
> @timbze should I open a separate issue on using full names for the books of the Bible instead of abbreviations? e.g., Genesis instead of Gen.

Yes please, if there's not an existing issue for it yet (I don't recall that there is).

Oops, didn't see Tuomas' reply

**Comment by oxr463** [comment]
Thank you both. I'll open a new issue.
