### ISSUE TITLE
Add 'the' to bookmark message

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1423]
![image](https://user-images.githubusercontent.com/13920678/126960716-9f1a4715-e01f-4df7-867a-42faed15b7cc.png)

**Comment by tuomas2** [comment]
via en_GB

**Comment by agrogers** [comment]
Yes, this one was for me to remember.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
