### ISSUE TITLE
Sort text option items in alphabetical order

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1424]
I understand that the menu options below and also in the Window menu change position based on their usage. I like the idea in principle but I feel like i am chasing the option because after I use it it moves to somewhere a little different. 

1. I think possibly a better solution might be to leave the menu options in the same place and only move them when a new option must be added. And the new option is added into the same place where the one was that was removed. It's a bit more complicated to implement but it seems a little more user friendly.
2. Or perhaps the options are always in alphabetical order. That might be better. At least then the general order is the same. 
3. Or they are in the order that is used in the settings menu. 
4. Anything except for an always changing order is probably an improvement I think.

![image](https://user-images.githubusercontent.com/13920678/126960946-57d2d0b0-ac4e-4619-9949-651db7ad3c02.png)

**Comment by tuomas2** [comment]
Perhaps just having them in alphabetical order would fix this?

**Comment by agrogers** [comment]
I think it might be an improvement.
