### ISSUE TITLE
If there's enough space, locate modal somewhere else than on top of selected verse

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1433]
Also, scrolling text might be option.

**Comment by tuomas2** [comment]
maybe empty 1 click modal could be placed on the bottom rather than top? maybe it would work as general rule too?

![Screenshot_20210727-224815_Bible Study](https://user-images.githubusercontent.com/5811789/127218557-9a98d393-33af-449e-a367-42ef65037fd4.jpg)

**Comment by timbze** [comment]
I find that on a phone I will usually tap on a verse from the middle down, so it's usually nice to have the modal at the top for that.

**Comment by tuomas2** [comment]
I'm trying now how it feels if the modal is located on the bottom.

Later I'm thinking I might try to locate it either top or bottom, based on where the user has clicked.

**Comment by tuomas2** [comment]
This makes #1001 even worse for those users that it affects.

**Comment by agrogers** [comment]
I had a problem with this just now when i try and edit a note. I see the note window popup at the bottom but then the keyboard completely covers the note window. When i scroll up to see if i can find the note window it is not there - perhaps because i have clicked off the window.

**Comment by tuomas2** [comment]
> I had a problem with this just now when i try and edit a note. I see the note window popup at the bottom but then the keyboard completely covers the note window. When i scroll up to see if i can find the note window it is not there - perhaps because i have clicked off the window.

Scrolling does not move modal because it's not with "fixed" positioning.
But what you are experiencing is #1001. Have you had #1001 issues otherwise?

**Comment by tuomas2** [comment]
This is implemented now.
