### ISSUE TITLE
Error in strings

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1444]
help_workspaces_text

>  Workspaces allow having multiple context-dependent working environments. Workspace functions
>         can be accessed via Workspaces item in options menu (top-right corner). Quick way to access workspaces is
>         by swipe-down gesture from toolbar. You may also use swipe-left and swipe-right gestures over toolbar to
>         switch to previous / next workspace.

This string is not correct. The swipe action needs to be on the verse selector part of the toolbar only.

assing_labels_help2
> Use %s to specify which label color is shown.

This string is no longer accurate. The translation is accurate.

auto_assing_labels_help1
> Here you can adjust which labels are assigned automatically to bookmarks that you create. 

The string is not appropriate for this dialog. It probably should be turned into multiple new strings for the next release I think.

**Comment by tuomas2** [comment]
@agrogers 

> assing_labels_help2
> 
> > Use %s to specify which label color is shown.
> 
> This string is no longer accurate. The translation is accurate.

What is wrong with this actually? 

> auto_assing_labels_help1
> 
> > Here you can adjust which labels are assigned automatically to bookmarks that you create.
> 
> The string is not appropriate for this dialog. It probably should be turned into multiple new strings for the next release I think.

What do you mean by multiple new strings? This is indeed part of a longer string.

**Comment by agrogers** [comment]
> Use %s to specify which label color is shown.

I think that %s showed the label icon. And the string was shown for the help in the Label list. 

The label icon changes the auto assign nature of the label. So if that string was shown in that help it was wrong.

**Comment by agrogers** [comment]
> Here you can adjust which labels are assigned automatically to bookmarks that you create.

I already 'fixed' this in Transifex. But it needs to be done properly.

![image](https://user-images.githubusercontent.com/13920678/127597722-c3055789-3bb0-4edd-8984-2076409ac9a9.png)

**Comment by agrogers** [comment]
Hi Tuomas. I am not sure of the correct procedure for changes to the strings. i dont believe the string above was correct for the location it was used. Do we create a new string (after the translation window closes)? Should i have edited this one like i did?

**Comment by tuomas2** [comment]
You can already make pull request towards dev, with changed strings. PR just can't be merged before dev is merged to current-stable.

I will check your changes (#1452 )

**Comment by agrogers** [comment]
OK. I will do that.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
auto_assing_labels_help1 is correctly fixed.

**Comment by tuomas2** [comment]
Also your correction to assing_labels_help2 looks good

**Comment by tuomas2** [comment]
help_workspaces_text is I think minor non-critical inaccuracy, but yours is good.

**Comment by tuomas2** [comment]
I don't see any task remaining here, so closing
