### ISSUE TITLE
Is an Add On a zip file?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1447]
> And Bible offers option to include custom CSS and fonts in module zip files. Place your CSS file under module directory 

'Place your CSS file' means 'Place your ZIP file that contains your CSS file' under....

Is that correct?

https://github.com/AndBible/and-bible/wiki/Custom-CSS-for-modules-for-And-Bible

**Comment by bvahedy** [comment]
No, you place the css file inside the zip file. So when you install the
module.zip it automatically places the files in the Andbible file
structure. Take a look at the Hisb.Zip in the repository as an example.

**Comment by tuomas2** [comment]
Or optionally take a look StyleExample.zip as an example for style-only module.

**Comment by agrogers** [comment]
Thank you
