### ISSUE TITLE
Bad highlight after showing strongs numbers 

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1458]
https://user-images.githubusercontent.com/35117769/127738580-0106a525-4b22-4828-90a2-5bed96ba0e34.mp4

**Bug was found on And Bible version**
Build 539

**Comment by tuomas2** [comment]
What you are seeing is what is expected if you have justify-align text option enabled

**Comment by tuomas2** [comment]
If your point was the underlining in links mode of strongs

**Comment by timbze** [comment]
> If your point was the underlining in links mode of strongs

No, after it toggles back to normal the highlight is just between words

**Comment by timbze** [comment]
![Screenshot_20210731-052756.png](https://user-images.githubusercontent.com/35117769/127738704-efa131fe-5c6e-4095-9d0d-7393012fbd1a.png)

**Comment by tuomas2** [comment]
Okay I see. I guess it's easy to reproduce then
