### ISSUE TITLE
Strongs definition crash

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1459]
In window that shows strongs definition and morphology, tap the strongs link to go to its definition alone > crash

https://support.andbible.org/scp/tickets.php?id=666

**Comment by agrogers** [comment]
Issue raised here also: https://support.andbible.org/scp/tickets.php?id=667

**Comment by timbze** [comment]
The crash has been fixed, but it seems not the underlying issue, because now clicking the link does nothing.

It should open the definition for the specific Greek word

AB version 541 (78133d0)

**Comment by tuomas2** [comment]
I am able to follow links in Strongs. Can you specify what's the issue? (Clicking links here looks like works perfectly).

![Screenshot_20210817_204233](https://user-images.githubusercontent.com/5811789/129775007-cf0079dd-33ef-402c-8510-81ce4805901b.png)

**Comment by timbze** [comment]
The "01722 (StrongsRealGreek)", and the "1722" link under it both do nothing. They should make the window switch from "multiple references" to "strongs real greek Bible dictionary". Clicking the lower links (i.e. 1519 and 1537) do that.

**Comment by tuomas2** [comment]
Why? The definition is already visible?

**Comment by timbze** [comment]
1. Main reason: so the dictionary can be switched. Doesn't work in "multiple references" mode
2. Because it's a link (could make it so it doesn't look like a link)
3. ~"Find all occurrences" does not show unless it's just the word open in dictionary~
