### ISSUE TITLE
Add a Download button to the 'Please download....' message

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1463]
It would be very helpful if the user could just click a button to download the document rather than having to try and find the document in the lists.

Some are not too hard to find... although it would need quite a few clicks to do it. Other like the 'cmnWBTC2006eb' are documents that I have no idea what it is now. Maybe it's possible to show the fullname of the document as well as its code.

![image](https://user-images.githubusercontent.com/13920678/127739288-62c7c2e2-924b-4233-8376-cd9bcf9b1132.png)

![image](https://user-images.githubusercontent.com/13920678/127739332-7686badd-3251-4b3d-98cc-ac2c5e843751.png)

**Comment by timbze** [comment]
Why do these notes show up? I thought the only way you can select a document is if it's already downloaded? Or does it show when a document gets removed?

**Comment by tuomas2** [comment]
If you reload db that uses docs that are not instaleld. Or if you remove doc that is being used in windows.

**Comment by agrogers** [comment]
Yes, the last I believe. I had not installed the docs, only the db.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
