### ISSUE TITLE
The white overlay underneath the workspace icon is partially transparent

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1464]
I think it is supposed to be solid white.

![image](https://user-images.githubusercontent.com/13920678/127739363-d8f86ded-eef2-4655-ac4e-e271a8286035.png)

**Comment by tuomas2** [comment]
That's intentional but is sit bad?

**Comment by agrogers** [comment]
'bad' might be a little harsh.
'Untidy' or 'cluttered' would be more the word I would choose :)

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
You can play with background_color_60 in colors.xml

**Comment by tuomas2** [comment]
(CommonUtils.combineIcons)

**Comment by tuomas2** [comment]
Changed it to be not transparent at all

**Comment by agrogers** [comment]
Yay, I wished I had done that before the videos 😁
