### ISSUE TITLE
Window button bar lost

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1468]
1. prepare 2 workspaces, first with more windows, second with less
2. go to first worskpace and hide window button bar
3. go to second workspace 
-> window button bar (handle) is lost (it's actually hdden, beyond user reach)

**Comment by bvahedy** [comment]
I've seen this in the past when I entered full screen mode, but I can't
dupplicate this and have not seen this in awhile.

**Comment by agrogers** [comment]
I've seen it to. My solution to get it back was to toggle fullscreen. I
could never work out what caused it though so didnt make a ticket.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Or just refresh the buttons location so it is visible...
