### ISSUE TITLE
Note keeps focus when it should go to the Bible Ref dialog

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1474]
1. Open the Enter Bible Reference dialog
2. Start typing
3. Texts appears in the note, not the dialog

![image](https://user-images.githubusercontent.com/13920678/127798542-de85746c-cf3a-4b70-8d39-a18edc0cd43a.png)

**Comment by tuomas2** [comment]
almost duplicate of #1475

**Comment by tuomas2** [comment]
I believe the root cause is the same
