### ISSUE TITLE
Should we add a Labels button to the header of the Bookmark labels dialog?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1477]
When adding labels to a bookmark in a small window the 'Select or edit labels...' button is often out of view. So i have to scroll down to find it.

Perhaps we could add the ![image](https://user-images.githubusercontent.com/13920678/127799650-4871ac6a-b021-4f42-b01e-ee5e51ee22aa.png) to the header so that we can always access the label list without scrolling.

I think I would leave the big button there... I like spelling out what it does. But it wouldnt be needed if we added the icon to the header.

![image](https://user-images.githubusercontent.com/13920678/127799564-7b9efdfb-4185-49be-ba3c-32d166212f78.png)

**Comment by bvahedy** [comment]
I like that idea.

**Comment by tuomas2** [comment]
Sounds ok to me
