### ISSUE TITLE
Scroll the workspaces list to the position of the active workspace

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1479]
I am making a lot of workspaces for the video(s) that i need to get done. When i go back to the workspaces list it always starts at the top and i have to scroll to the bottom to get to the one i am working on.

![image](https://user-images.githubusercontent.com/13920678/127799955-89cb6bd0-3bd1-44ef-80fe-fa0512bdfade.png)

**Comment by timbze** [comment]
#949 is similar (for reference). I think this is higher priority
