### ISSUE TITLE
Back up (backup) bookmarks and notes to/from Google Drive, manual via intents

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#148]
In addition, it might be possible to implement simple synchronization mechanism with google drive too.

**Comment by tuomas2** [comment]
Manual backuping is implemented in build 306. @bvahedy could you test this?

**Comment by bvahedy** [comment]
This send to be working fine in 307 beta.

**Comment by tuomas2** [comment]
Implemented in 308
