### ISSUE TITLE
Do we need a splash screen at start up?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1481]
I have noticed most of the bible apps i have checked out have a nice splash screen when they start up. Some examples below.

AB starts faster than most of the others so the splash screen wouldn't be seen for long. But it does give a nice feel.

![image](https://user-images.githubusercontent.com/13920678/127800826-e300e8bc-b9f1-45f3-b408-b95f2c7beb1f.png)

**Comment by bvahedy** [comment]
AB used to have a splash screen, I think Toumas got rid of it because a lot
of users complained about it.

**Comment by agrogers** [comment]
Ohm yeah, it did, i remember now. Was it a blue background?

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
We do have splash screen with spinner and tilte text on it that will only show up when starting app that is not in the background. That can be stylished if desired. 

But apart from that, I don't think splash screen adds any particular value.

**Comment by agrogers** [comment]
Does the existing splash screen have any text on it?

Re value, you sound like a true engineer 😊 Splash screens don't usually
add value. They add polish. Our startup just felt a little utilitarian
after using the other apps for a while.

That is probably the one difference I notice most between AB and the
alternatives. AB is like the 73 function Swiss army knife only without the
fancy red casing. It can do everything but it can take a while to find the
right tool.

The alternatives are like a leatherman. It has fewer tools but they are
easier to find. And it has that shiny stainless steel handle that feels
nice in the hand.

I love AB BECAUSE it is a Swiss army knife. Making it a little prettier and
a little simpler could result in even more people loving it. I think aiming
for Swiss army knife functionality with Leatherman ease of use is a worthy
goal.

I would love to hear what others think. What are the goals?

**Comment by tuomas2** [comment]
Current: 

![Screenshot_20210802_102203](https://user-images.githubusercontent.com/5811789/127820332-21aee0be-5233-498a-a1c0-c7dd39466c08.png)

**Comment by agrogers** [comment]
I think calling it a 'splash screen' is a little too generous :)

> A splash screen is a graphical control element consisting of a window
containing an image, a logo, and the current version of the software.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Let's add name and logo there then :-D

**Comment by agrogers** [comment]
Ben will give us a hard time again with the logo :D Maybe wait a little on
it.

Maybe a simple colored background would be a good start - radial or linear.

[image: image.png]

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment]
Ok, as long as the logo doesn't endanger people's lives 😁

**Comment by tuomas2** [comment]
Added title and logo

![Screenshot_20210802_123653](https://user-images.githubusercontent.com/5811789/127839920-4e4a9ce6-28b5-4354-97bb-eae5aa512acb.png)

**Comment by tuomas2** [comment]
When we get new svg logo we can make logo bigger

**Comment by agrogers** [comment]
Good job

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by uniqueid001** [comment]
> AB used to have a splash screen, I think Toumas got rid of it because a lot of users complained about it.

For reference, #877 is the request to remove the old, blue, splash screen.

**Comment by uniqueid001** [comment]
I like the new splash screen with the logo/launcher icon.  (I am not, yet, at risk due to the logo and content)

**Comment by agrogers** [comment]
Me too. It feels nice and polished. Only change I would make is to show it
on a dark background. It looks sweet in dark mode on my phone. [Changed my mind] I would NOT make
it look like that in dark and light mode - DONT put it on a dark gray background.

**Comment by agrogers** [comment]
Changed my mind i think - the autumn colours look good on the white background. My vote now is to leave it on white :)

**Comment by tuomas2** [comment]
I guess nothing to do here any more
