### ISSUE TITLE
Error when speaking ISBE document (reproducible)

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1482]
* Changed the current document to the ISBE dictionary 
* Pushed the play button at the bottom of window and got the error. 

Reported by me: https://support.andbible.org/scp/tickets.php?id=613

![image](https://user-images.githubusercontent.com/13920678/127802015-2d09c323-1c52-4d26-88d0-e996084204cd.png)

**Comment by timbze** [comment]
May be same or similar to issue #1413

**Comment by tuomas2** [comment]
Fixed by 4983bb97929215d18665deb374f66f71d296bec9
