### ISSUE TITLE
Is bookmark toolbar button needed?

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1497]
![image](https://user-images.githubusercontent.com/5811789/128010029-e40c618f-5d52-4135-841f-d21655f8f9b5.png)

I'm thinking should we remove it?

**Comment by timbze** [comment]
I think it can be removed. I don't think it ever shows up on my phone, but confirmed it's there when I turn to landscape.

**Comment by agrogers** [comment]
I have never used it and hardly ever seen it.

**Comment by tuomas2** [comment]
Ok I'll remove. It's seen often on portrait or larger tablet.
