### ISSUE TITLE
"Remove bookmark" confirm dialog buttons 

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1501]
It looks like the buttons would fit side by side? 

![Screenshot_20210803-060321.png](https://user-images.githubusercontent.com/35117769/128012565-1f653086-a8ef-4333-8b70-acd78c120ccc.png)

**Comment by tuomas2** [comment]
Perhaps it's ner the limit? Or there is too much padding etc.

**Comment by agrogers** [comment]
I think they are side by side for me.

**Comment by bvahedy** [comment]
I think this happens if you increase the device's system font size.

**Comment by timbze** [comment]
My font size is normal but my pixel 3 is known for a bit of a narrow screen

**Comment by bvahedy** [comment]
Can you reduce your system font size just a tad to see if the icons go to
one row?
Just to prove my theory. Pretty Please!

**Comment by tuomas2** [comment]
It happens depending on system font size and screen size. But reducing padding / button size helps.
