### ISSUE TITLE
Studypad tools 3dot button overlay need improvement

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1502]
Perhaps a little bit more transparent and with circular semitransparent border etc.

![image](https://user-images.githubusercontent.com/5811789/128012612-ea0dbfbb-e91a-47de-bdc0-9e144d4efb68.png)

**Comment by agrogers** [comment]
What if it was just shifted up a little higher?

**Comment by tuomas2** [comment]
Works

**Comment by agrogers** [comment]
Great, easy fix.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
