### ISSUE TITLE
After installing doc via clicking "Download FinRK", doc is not refreshed properly

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1505]
![Screenshot_20210803_200253](https://user-images.githubusercontent.com/5811789/128056552-579bdbcb-be72-4310-b21a-12ba009f7cc2.png)

**Comment by tuomas2** [comment]
Can't reproduce this very easily.

**Comment by timbze** [comment]
Fixing this might fix #91 as well, if that issue still exists

**Comment by tuomas2** [comment]
This is "mostly" fixed. Some corner case still raises sometimes still head.

**Comment by tuomas2** [comment]
I believe this is fixed BTW. Should check.

**Comment by tuomas2** [comment]
Tested, it is fixed
