### ISSUE TITLE
Is it possible to have the speak bookmark remember its position anywhere in the document?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1508]
I thought there was already an issue for this.

If i am speaking a book, i want it to remember the exact position i stopped. If the chapter is long than this is not a feature but a necessary function. The chapter below for example is a very long one!

![image](https://user-images.githubusercontent.com/13920678/128170542-424b2a00-d091-4830-9b81-dc9ec3ab851b.png)

**Comment by tuomas2** [comment]
No, there is not even any kind of bookmarking implemented for general books.

**Comment by agrogers** [comment]
OK, i thought so. By possible I mean is it easy enough to do? There are no
verse numbers to peg a bookmark to. So does it require a
completely different approach to bookmarks? it would be kind of neat if we
could add bookmarks to books like we can to bibles :)

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
I believe there's a ticket somewhere for adding bookmarking support for gen book documents. 
Bookmarking for genbooks would require having another table and UI integration is possibly non-trivial, so I wouldn't say it's "easy", but possible of course.

**Comment by tuomas2** [comment]
Will be implemented by #2690
