### ISSUE TITLE
Verse links within a note

### ISSUE THREAD

**Issue by BryceSteuer** [AndBible/and-bible#1518]
A feature I would like to see in AndBible is a verse reference typed in a note being displayed as a link that can be clicked to open a new window.

For instance, if I am taking a note on 2 Corinthians 10:5, and I type "Isaiah 28:15" into the note, then it would be good if that reference automatically converts to a link taking me to Isaiah 28:15. I notice a similar feature on YouTube, in which in the comments you can type 5:15 and it will convert to a hyperlink taking you to 5 min 15 sec point in the video above.

This feature might be annoying or useless to some users, but I think if an AB user is avid and active enough to even take notes on a regular basis, they would probably appreciate this feature.

**Comment by tuomas2** [comment]
Please write 1 feature request per ticket. 

If I understood correctly, this has been implemented already. 

![Screenshot_20210804_223733](https://user-images.githubusercontent.com/5811789/128244202-9cc1a056-c567-4dbe-b150-706c1a8bcb65.png)

**Comment by BryceSteuer** [comment]
Thank you, I hadn't noticed the mini Bible icon was for that purpose.

**Comment by bvahedy** [comment]
Bryce, on your second point, if you tap and hold on any words in a verse
then tap on compare on the mini toolbar. You can see that verse in other
translations you have installed, in the compare window if you tap on the
module name it will take you to that version for that verse.

**Comment by BryceSteuer** [comment]
@bvahedy 
I have used that before, but to do that to my knowledge one must open the verse link and then proceed to open another window with the new version. My proposal is to create ability to hold down link and choose the version to open the verse link in without opening an intermediate window (maybe with a "don't ask again" for users who are not so inclined).

**Comment by bvahedy** [comment]
What would the use case for this be, we all have a preferred translation we
use and we usually compare a verse to other versions. The reason I'm asking
this is if you want to switch to another version why not use the icon on
the top menu bar to change the current window to the version you want to
switch.
Or May be I'm misunderstanding your request.
