### ISSUE TITLE
Up button in bible book selector does not work

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1522]
1. Use bible book selector to go to verse selection level (For example Rom 15) 
2. Press up button -> OK (we are back to chapter selection for Rom)
3. Press up button 
-> Expected: we are in bible book selection again
-> Actual: It does shows empty screen with title "Choose book".

**Comment by timbze** [comment]
I also found this issue recently, but hadn't thought of creating issue at right time. 

I believe #1200 might be related
