### ISSUE TITLE
Duplicate bookmark in 1 click modal

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1525]
![Screenshot_20210806-103520_Bible Study](https://user-images.githubusercontent.com/5811789/128480665-5c98abf1-de18-45f1-becb-7e8a0fd50807.jpg)
**Describe the bug**

**Bug was found on And Bible version**
Build XXX.X or version X.X.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S6]
 - OS: [e.g. Android]
 - Version [e.g. 8.0]

**Additional context**

**Comment by BryceSteuer** [comment]
Ah, I noticed this error as well. And when I deleted (trash bin icon) one of the duplicates, then the remaining one seemed to no longer be in its assigned category. But there could have been other variables causing this that I am not immediately considering.

**Comment by bvahedy** [comment]
I can't dupplicate this in the latest build, could this be in the database
when the bug was fixed about three weeks ago or so?

**Comment by tuomas2** [comment]
no duplicates were ever created. some were displayed twice
