### ISSUE TITLE
What does the reset button actually reset in the workspace menu?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1528]
I pushed it but i couldnt tell what changed.
![image](https://user-images.githubusercontent.com/13920678/128597958-13619871-1b4b-4a57-b0c7-461c62f0e609.png)

**Comment by tuomas2** [comment]
everything to defaults in that view

**Comment by agrogers** [comment]
Every window in the workspace?
Or every workspace setting? If so, are they system defaults that you have
set?


___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
It does not change per-window settings BUT it changes the "workspace defaults" (i.e. if window does not have specific (non-workspace) setting set then it applies). Those "workspace defaults" are reset to "factory defaults" (you can see them TextDisplaySetting.default net/bible/android/database/WorkspaceEntities.kt:240)

**Comment by agrogers** [comment]
OK, thanks!
