### ISSUE TITLE
Long pressing the Strongs button opened the ISBE dictionary

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1529]
That didn't seem right. I expected it to open the Strongs dictionary.

![image](https://user-images.githubusercontent.com/13920678/128598008-f0d2a257-3c30-4f2b-b096-b719e40cb1ba.png)

**Comment by tuomas2** [comment]
...instead of Strongs dictionary, which would be correct behavior, right?

**Comment by agrogers** [comment]
Um, i think it should open the Strongs dictionary. Yes?

**Comment by tuomas2** [comment]
I'll disable long click alltogether for this button, I doubt it's too useful.
