### ISSUE TITLE
Is the dark mode too dark in some places?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1530]
The background of some dialogs are completely black. But the label list is dark gray. Dark gray seems better to me than black. I dont use this mode much.

![image](https://user-images.githubusercontent.com/13920678/128598042-908f0735-d9a4-4d09-9fc8-19a6df4e1134.png)

![image](https://user-images.githubusercontent.com/13920678/128598038-aabd2ab0-5f4e-4d97-897a-6fe3b1a111bf.png)

**Comment by tuomas2** [comment]
Maybe

**Comment by timbze** [comment]
I always use night mode and haven't thought of it as an issue, but maybe it could be improved, not sure
