### ISSUE TITLE
Show which window is the master sync window

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1535]
I don't really know how to tell which window is the master sync window. I think it is usually the top window. Is that correct?

Perhaps we could show a different sync icon in the window button to indicate that the window is the master sync window. It's probably not that useful - just nice for completeness :)

Icon could be an inverted sync image.

**Comment by timbze** [comment]
Is there a "master"? I think all windows operate the same if you change verse in any one of them. I think the only place where it feels unclear is when enabling sync on a window, and I think it always syncs to other synced window(s) if there are any visible.

**Comment by agrogers** [comment]
Oh, so it does :) That is a bit embarassing. I will quickly close this issue before anyone else sees it. Thanks for the clarification!
