### ISSUE TITLE
Adding studypad Bible link using the icon creates spaces in the link...

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1544]
In studypad adding revelations 12:3 as a link ref. Using the icon, Makes the link to jump to John 12:3.

I think this had to do with displaying the full name of the bible book, it only sees the last word in the book name which is John.

**Comment by bvahedy** [comment]
![Screenshot_20210807-110730_Bible Study](https://user-images.githubusercontent.com/46405809/128609985-91cff6b4-f15c-4b23-a6b2-74835cc97427.jpg)

**Comment by agrogers** [comment]
I don't think I would ever want the full name of the book inserted into my
note. And certainly not for revelation.

Perhaps that dialog should only return abbreviated names.

**Comment by bvahedy** [comment]
Yes, I agree with you, I too prefer the abbreviated book names, but I think
someone requested the full name be displayed and that's why we are here.

**Comment by tuomas2** [comment]
we can change to abbreviations

**Comment by bvahedy** [comment]
Yes please.
