### ISSUE TITLE
Place the hidden bookmarks below the line

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1545]
This is barely a bug...

- I clicked on a verse that had a hidden bookmark ('Sermon'). I was surprised when it appeared at the top of my list - I didn't realise I had bookmarked it.
- It is good that the bookmark did show in the dialog
- But I think it should be shown under the line indicating it is a bookmark that was not clicked on. I know technically it was clicked on (it was just invisible) but from the user perspective he didnt click on it.

![image](https://user-images.githubusercontent.com/13920678/128656001-31264c40-6979-40d6-8214-7df480c67450.png)

**Comment by tuomas2** [comment]
I hope I will be able to reproduce this. I agree that it should not be on top.
