### ISSUE TITLE
Should we also show the text when 'Showing all references...'

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1547]
I love how the TSK identifies references under a heading (eg 'keep', 'with all diligence...' etc) 

However when we look at all references those headings are missing. It would be nice if they were maintained so I could tell what there reference was referring to.

In some instances there is a lot of text and very few references. Perhaps it would be possible to limit the number of text words to say 10?

![image](https://user-images.githubusercontent.com/13920678/128656305-74439371-08d0-4802-a4b5-8cfa12511f7f.png)

**Comment by tuomas2** [comment]
Very cumbersome to implement. Definately wont fix (from my side) :-)
