### ISSUE TITLE
Study pads: behavior change to verse clicking

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1551]
I don't like that clicking verse minimises/maximises verse. I rather change the default to expand and add expand/shrink button to tool buttons.

![image](https://user-images.githubusercontent.com/5811789/128678037-c8b525ec-b477-4bd2-81cb-d1f0539c6817.png)

**Comment by agrogers** [comment]
What will clicking the verse do then?

**Comment by tuomas2** [comment]
Nothing particular. It's like back-clicking in general.

**Comment by tuomas2** [comment]
I'm just accidentally clicking it too often.
