### ISSUE TITLE
Make margin width adjustable in settings

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#156]
There have been users complaining about wide margin, especially when they use landscape mode.
I think solution would be to make margin adjustable in settings.

**Comment by mattzab** [comment]
This could fix the wide Chromebook  margins, as well as prevent overlay interruption.

**Comment by tuomas2** [comment]
From user: 
>  at least a handful of margin settings around the text, if not precise control at least 3 or 4 well adjusted margins for better reading experience.

**Comment by tuomas2** [comment]
Implemented in 2456d364d71e31752c28e6b70f49bd6534528f9e

Will be in next beta build > 340

**Comment by bvahedy** [comment]
Verified fixed in build 342-beta.
