### ISSUE TITLE
2 verses get highlighted when tapping a link with 1 verse 

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1560]
**Describe the bug**
In some weird cases 2 verses get the "active" highlight when it should be just 1 verse. But it's reproducible. It's an extremely minor issue for me, but thought it's possible the issue will also cause other unintended issues. 

**Bug was found on And Bible version**
Build 540

**To Reproduce**
1. In LBC 1646, appendix section 22
2. Click the multiple links as in video
3. Then the link 1Pet 2:14 opens and then highlights both v14 and 15
4. Tap in the Bible window so that the highlight goes away
5. Click the link again and only 1 verse selects, like it should. 

Seems the video is a bit too big to upload here. Here's the YT link to it. 
https://youtu.be/G3mg543Oojg

**Comment by tuomas2** [comment]
Page does not contain link to 1Pet 2:14
