### ISSUE TITLE
Update copy of Brenton Septuagint in And Bible repository

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1561]
from ebible repository.

It's public domain as far as I know.

**Comment by tuomas2** [comment]
Hmm I have already added it c1d39b0188ef736663df6546fcc806fcfaf1b705

**Comment by tuomas2** [comment]
https://github.com/AndBible/data/commit/c1d39b0188ef736663df6546fcc806fcfaf1b705

**Comment by tuomas2** [comment]
It is not the latest version though. Does anyone use it with And Bible or other apps? I don't know how important it would be to update it?

**Comment by bvahedy** [comment]
Why use septuegent when you have the original Hebrew like HiSB or Alepo or
WLC although Alepo is more accurate than WLC.

**Comment by tuomas2** [comment]
It's english translation of septuagint. I can't answer your question, but it seems to be popular.

**Comment by bvahedy** [comment]
septuagint seems to have been tampered with throughout history, so it's not
an exact copy of the original Hebrew. That's why it's better to look at the
Hebrew text instead of the Greek translation of the Hebrew text. It just
doesn't make any sense to look at a copy when you have the original.

**Comment by tuomas2** [comment]
> septuagint seems to have been tampered with throughout history, so it's not an exact copy of the original Hebrew. That's why it's better to look at the Hebrew text instead of the Greek translation of the Hebrew text. It just doesn't make any sense to look at a copy when you have the original.

I bet some users have different opinions about that. Why would they use it if they didn't?

**Comment by bvahedy** [comment]
We don't care about their opinion, Whatever their reasoning is, they are
not thinking correctly. They mostly think in Greek not in Hebrew.

**Comment by bvahedy** [comment]
Btw, I'm not opposed to making Septuagint available. Just don't think it's
of any value.

**Comment by timbze** [comment]
> It is not the latest version though. Does anyone use it with And Bible or other apps? I don't know how important it would be to update it?

It looks like AB version is 4.3MB, but eBible version is 7.6MB, probably should update in AB
