### ISSUE TITLE
Copycat on Google Play

### ISSUE THREAD

**Issue by Poussinou** [AndBible/and-bible#1564]
Hi @andbible

I found this app https://play.google.com/store/apps/details?id=com.bible.bibleofflineapp on the Google Play Store from [this developer](https://play.google.com/store/apps/developer?id=5+Star+Apps+World). This is obviously a clone of your app. This guy just took your source code, added some ads and monetization in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this copy from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPLv3 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by tuomas2** [comment]
So you checked that 

- they are not having proper attribution within app (GPL requirement)
- their source code is not (completely) publicly available in readable form (and clearly indicated within app)? 

If that is the case we can indeed file a complaint. 

Thanks for reporting. Please let me know if you find others too.

**Comment by tuomas2** [comment]
Submitted. Keeping this open to follow the situation of that app.

**Comment by tuomas2** [comment]
> Hello,
> 
> Thanks for reaching out to us.
> 
> In accordance with the Digital Millennium Copyright Act, we have completed processing your infringement notice. We are in the process of disabling access to the content in question at the following URL(s):
> 
> https://play.google.com/store/apps/details?id=com.bible.bibleofflineapp
> 
> The content will be removed shortly.
> 
> Regards,
> The Google Team
> 
>

**Comment by tuomas2** [comment]
Leaving form data here for future reference (so can copy-paste new requests):

> Identify and describe the copyrighted work
> Bible Study App, by And Bible Open Source Project.Application is published under GPL version 3 license, which the author "5 Star Apps World" is violating (he is basing his work on version 3.2 of And Bible, which looks a little different than the most recent version). I am holding copyright to the above mentioned application. This infringement was reported to me via ticket: https://github.com/AndBible/and-bible/issues/1564 .
> 
> Where can we see an authorized example of the work?
> https://github.com/AndBible/and-bible
> https://play.google.com/store/apps/details?id=net.bible.android.activity
> https://f-droid.org/en/packages/net.bible.android.activity/
> 
> Allegedly infringing URLs
> 
> https://play.google.com/store/apps/details?id=com.bible.bibleofflineapp
> 
> Attach a screenshot of the allegedly infringing material
> Screenshot_20210812_205301.png
> Screenshot_20210812_205254.png
> Screenshot_20210812_205251.png
>
