### ISSUE TITLE
What was the rationale behind making the dialogs short? 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1567]
We have the new button to allow the dialogs to be taller. What was the problem this button was trying to fix?

**Comment by tuomas2** [comment]
I was using AB to create notes during 5 solas reformation conference. There I had portrait setup that has 2 windows: first is studypad and second is bible window. Second window is used to read / browse referenced scriptures and add bookmarks to studypad. When creating bookmarks, it was disturbing when there were already few bookmarks and 1-click modal was huge. I don't want it allocate whole screen but only small portion of screen, so that it does not cover the bible text.

**Comment by tuomas2** [comment]
And this button is only in 1-click modal

**Comment by tuomas2** [comment]
Default needs to be expanded, changed in 3349cc023ddd5c768f99756b4f3b3eaef8383268

**Comment by timbze** [comment]
I like the feature

**Comment by tuomas2** [comment]
Perhaps this could/should be saved per workspace. Now it is not saved at all (just remembered per window session).

**Comment by agrogers** [comment]
OK, thanks for the extra info. A few comments

- I have never thought i needed that functionality but it could be handy. I look forward to testing it out
- Generally speaking, I dont like giving space to things that are rarely used. How often would you use the expand button? I imagine it is the sort of thing that someone either likes or dislikes and so sets it once and leaves it? If it gets used rarely then I wouldn't give it a prominent position
- The header is starting to get full (on a phone). I would like to add an extra button to maximise the window #1541 - i find myself doing that often when entering notes. How many buttons do we want in the header? Maybe an ellipsis which displays a popup would be a way of moving less used options to a less prominent place.
- Regarding how the setting should apply, perhaps there could be a default app preference that determines the behaviour for new windows and then save it on a window by window basis
- The button is kind of weird when there is only one bookmark. All it does is add a scrollbar. Perhaps hide the button when there is less than two bookmarks
- The thing I now like the least is, I think, an unintended side effect.  I have a pile of space on the screen but I have to scroll through a tiny window at the bottom to find a label I want.
- That's also the case for the edit window. I have enjoyed using the extra space we gained by removing the unnecessary padding. Now two-thirds of the screen is padding! It feels like one step forward and twenty-two steps back :D

![image](https://user-images.githubusercontent.com/13920678/129299253-fd70e580-d2c9-443c-b031-a4cf9ec05378.png)
![image](https://user-images.githubusercontent.com/13920678/129299459-efa5e9ea-50d0-4dff-9b55-91735fa3c87b.png)

**Comment by tuomas2** [comment]
I intended this for 1-click modal only. It does effect for other dialogs too and it's a bug (which I just fixed)

**Comment by agrogers** [comment]
Sweet. Thanks.
