### ISSUE TITLE
And Bible on Microsoft Store for PC

### ISSUE THREAD

**Issue by Dleemuse** [AndBible/and-bible#1578]
I looked in the Microsoft store on my PC for AB, & am assuming we cannot get AB onour PC, please correct me if I am wrong. 

Failing that, I just connected my android phone to my new PC, now my PC can see & open my phone apps.

When trying to resize AB to fit computer screen, it would not resize wider, but stayed phone screen shape dimensions. Does anyone know if it is possible to widen apps on your PC that it sees from the phone? I would really like to be able to use AB on my PC. 

Thanks!

![20210813_133019](https://user-images.githubusercontent.com/83124765/129405386-547c4f11-290c-4a72-88ff-82a476e20284.jpg)

**Comment by Dleemuse** [comment]
![20210813_135322](https://user-images.githubusercontent.com/83124765/129405816-55fe3c6f-8765-43fb-9423-e99126bd62b2.jpg)

**Comment by tuomas2** [comment]
Windows 11 (which is released upcoming autumn) will run Android Apps, and uses Amazon App Store. Then And Bible can be installed on windows too.

At the moment there's no way to run And Bible on Windows (but emulator or remote (like yours), of course).

**Comment by tuomas2** [comment]
https://developer.amazon.com/blogs/appstore/post/a7583854-9367-4480-99c4-15f91456558c/amazon-and-microsoft-create-new-opportunities-for-developers-and-increase-return-on-investment-in-the-amazon-appstore?cmp=US_2021-08_ESM_Q3-Newsletter&ch=eml&chlast=eml&pub=esm&publast=esm&type=org&typelast=org

**Comment by Dleemuse** [comment]
Thanks Tuomas for letting us know that. 

Sent from Yahoo Mail on Android 
 
  On Fri, Aug 13, 2021 at 2:42 PM, Tuomas ***@***.***> wrote:   


https://developer.amazon.com/blogs/appstore/post/a7583854-9367-4480-99c4-15f91456558c/amazon-and-microsoft-create-new-opportunities-for-developers-and-increase-return-on-investment-in-the-amazon-appstore?cmp=US_2021-08_ESM_Q3-Newsletter&ch=eml&chlast=eml&pub=esm&publast=esm&type=org&typelast=org

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
