### ISSUE TITLE
Icon suggestion for compare translations

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1592]
![Selection_173](https://user-images.githubusercontent.com/5811789/129726182-f515575d-90c4-416c-85d2-7070636e772d.png)

**Comment by bvahedy** [comment]
It looks too similar to a resize button.

**Comment by tuomas2** [comment]
Which resize button?

This icon is used in, for example, Android Studio to indicate comparison.

**Comment by bvahedy** [comment]
Arrows pointing inwards or outwards usually convey some sort of minimize or
maximize. I just don't see how this icon can mean compare multiple Bible
translations. Now is it was one arrow against multiple arrows, that would
be better.

How about this one:
![SmartSelect_20210817-134441_Samsung Internet](https://user-images.githubusercontent.com/46405809/129798184-bd37e8c2-c373-4ad2-88d3-398f7643dd10.jpg)

**Comment by agrogers** [comment]
Hi Ben. The images don't come through when including them in an email. Need
to paste images into the github Web interface

**Comment by bvahedy** [comment]
I put it on the git also, check it out.

**Comment by bvahedy** [comment]
I had edited the git msg here and placed the image inside the note, but it would not initiate another email I guess.
But, I'm adding it as an image here rather than the link like above:
![SmartSelect_20210817-134441_Samsung Internet](https://user-images.githubusercontent.com/46405809/129813183-7ef79637-7780-4ae7-b0f2-c5e4a0f8ee0a.jpg)

**Comment by tuomas2** [comment]
Tried but does not look good

![Screenshot_20210819_113729](https://user-images.githubusercontent.com/5811789/130037008-e2ccffec-a199-458f-9c1e-73c2ec15d183.png)

**Comment by bvahedy** [comment]
It looks nice but may be making the icon more vivid and slightly bigger or
May be a different color may make it's detail stand out more. Let's see
what Andrew and others think or comes up with.

**Comment by tuomas2** [comment]
![Screenshot_20210819_192500](https://user-images.githubusercontent.com/5811789/130106396-1efa7fec-c18c-4b37-b2dd-d540a84cab72.png)

I changed it to my version ^. I think it's better than earlier. Improvements are of course welcome.

**Comment by agrogers** [comment]
I think it looks fine. The original one described what the Compare window
looked like - lots of the same verse one under another. The latest ones
describe bringing two things together - which is more symbolic. Neither by
themselves would be that helpful. But with the text underneath I think they
both work fine. Probably personal preference now. Style of new one looks
good and fits with the others.
