### ISSUE TITLE
HunIMIT processing issue

### ISSUE THREAD

**Issue by krisek** [AndBible/and-bible#1594]
**Describe the bug**
When opening the HunIMIT module "Please Note null 3 was found in document HunIMIT" error message appears.

**Bug was found on And Bible version**
Build beta-541.4 or version 4.0.541-beta

**To Reproduce**
1. Download HunIMIT module
2. Open the document
3. Error message appears

**Expected behavior**
Module should be opened.

**Screenshots**
![Screenshot_20210818-000642](https://user-images.githubusercontent.com/786044/129808130-2b681cb3-c0ef-4be2-8cfd-ae8989e3d0f3.png)

**Smartphone (please complete the following information):**
 - Device: Pixel5
 - OS: Android
 - Version: 11

**Additional context**
Maybe a dormant module issue?

**Comment by tuomas2** [comment]
Error report is indeed wrong. Root cause is that the module does not contain new testament.
