### ISSUE TITLE
Check that dev team has enabled two-factor auth

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1595]
Github + Google

**Comment by tuomas2** [comment]
Github looks ok.

@AndBible/developers team can you tick yourself if you have two-factor enabled in Google (that I can't check).

- [x] @tuomas2 
- [x] @agrogers 
- [x] @timbze 
- [x] @JJK96 
- [x] @mattschlosser 
- [x] @bvahedy

**Comment by bvahedy** [comment]
Can't find the box to tick  (it's ticking me off 🙄)

**Comment by JJK96** [comment]
Is it necessary that this is public? Why not just discuss this on teams?

**Comment by bvahedy** [comment]
✓ @bvahedy

I couldn't edit this ticket, so this is the best I could do. But I agree with JJK96, this should be on a private channel.

**Comment by tuomas2** [comment]
> Is it necessary that this is public? Why not just discuss this on teams?

Sorry for this. I thought there's nothing to hide here (especially after everyone is done) :-)

**Comment by agrogers** [comment]
I'm done.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
