### ISSUE TITLE
Language list should be seekable

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#160]
Language list in Download documents is very long. It would be more convenient if there was some way to enter search search key with text input). Or some other way make it more user friendly.

- Related: Show all languages in one place #553

**Comment by LAfricain** [comment]
And the list is not sort by name then sometimes people don't know that the bible they are looking for is in the end of the list.

**Comment by tuomas2** [comment]
Implemented.

**Comment by bvahedy** [comment]
Verified feature in build 359 beta. I like it, good work!
