### ISSUE TITLE
Inconsistent handling for verse-commentary compatibility

### ISSUE THREAD

**Issue by BryceSteuer** [AndBible/and-bible#1601]
If, from Mark 8:38, I choose the Chrysostom commentary, I get the following message:
"An error has occurred. Report an error". This occurs regardless of Bible version.
However, if from John 15:15 I choose Chrysostom commentary, I get this message:
"Please note
John 15:15 was not found in document Chrysostom".

I guess I'm confused a bit by the different handlings.

**Comment by tuomas2** [comment]
Which version?

**Comment by BryceSteuer** [comment]
https://github.com/AndBible/and-bible/releases/tag/build-540-andrew-underline 
The above version.
Just installed latest.
On latest it is working fine, my mistake.
