### ISSUE TITLE
Bridge telegram group to matrix 

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1603]
> just add @tchncs_bot to this group and done

**Comment by thebiblelover7** [comment]
This would mean that messages from Telegram get sent to Matrix and vice versa.

Users can use their preferred platform. Other platforms like Slack can be connected too.

**Comment by tuomas2** [comment]
Created group #andbible on matrix... now trying to create the bridge.

**Comment by tuomas2** [comment]
tchncs_bot seems to be not the only options, but is it the best?

**Comment by tuomas2** [comment]
This is the channel I created: https://app.element.io/#/room/#andbible:matrix.org

**Comment by tuomas2** [comment]
or https://matrix.to/#/#andbible:matrix.org

**Comment by tuomas2** [comment]
I find something else from here: https://matrix.org/bridges/#telegram

**Comment by tuomas2** [comment]
I think I managed to do the bridging now.

**Comment by agrogers** [comment]
Good work. But I don't really know what this is all about :)

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Telegram is like whatsapp, a messaging app. Similarly, Matrix is a messaging app. 
We wanted to create bridge between these apps so that people can choose which they use.

**Comment by tuomas2** [comment]
Updated https://github.com/AndBible/and-bible/wiki/Support

**Comment by agrogers** [comment]
Ah, I know Telegram but not Matrix.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
