### ISSUE TITLE
Volume up / down btns - how much to scroll?

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1604]
How much to scroll? Now it scrolls full page. Maybe half page? Or maybe even just one verse?

**Comment by agrogers** [comment]
I've never used it. Didn't know it was possible :)
One page seems too much. Half to 4/5ths perhaps.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Of course you didn't use as it was implemented yesterday (#60). :-)

**Comment by agrogers** [comment]
lol

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by timbze** [comment]
I don't think more than 1/2 page. For me I think I would prefer somewhere between 1/4 and 1/2. Maybe 1/3

1 verse would be inconsistent as sometimes it would be 1 line, and sometimes many lines.

**Comment by Dleemuse** [comment]
Lol, now that was funny!

I have to follow all the things on GitHub so I can keep up with all the new features! Thanks for the tip.

**Comment by bvahedy** [comment]
How about a setting where we can choose how much to scroll using the volume
button?

**Comment by tuomas2** [comment]
We can later add setting if it is needed, but for 4.0 we need a nice default (without setting).

**Comment by BryceSteuer** [comment]
I thought it might have been an Android setting I wasn't cognizant of, because the volume scroll was also in effect on my separate PDF Reader app. But it is annoying when you want to change the volume and can't because those buttons are used as scrollers. Are there any settings at all for this?

**Comment by tuomas2** [comment]
Feature is disabled automatically when listening to bible. There's no setting for it (can can't be before 4.1). We can drop it from 4.0 if people hate it too much.

**Comment by BryceSteuer** [comment]
Ok, makes sense. I was trying to change the volume before starting the playback. I like the feature though.

**Comment by tuomas2** [comment]
- [ ] perhaps should change it so that it is disabled also when playback is paused (but not stopped)... or just when transport is visible.

**Comment by bvahedy** [comment]
Let's keep it, I think it is useful.

**Comment by agrogers** [comment]
I guess this affects people who are listening to music while using And
Bible too?

**Comment by BryceSteuer** [comment]
@agrogers The only way I see now to change volume when in the app listening to music is to exit the app (i.e. to home screen) then change volume from there. I may be missing something, but that's pretty annoying. Or inside the app you can click the search icon or another link that takes you from the document you're currently in, and then you have the option to use volume change. But if you want to read and change the volume, you may not. The document must be out of focus.

**Comment by tuomas2** [comment]
Is it usual that people listen to music while studying bible? If that's the case, we need to disable this alltogether in 4.0, because it will annoy people. I never do that myself. 

Or we might need to figure out if we can know if there's some music playing. I don't know if that's possible.

**Comment by bvahedy** [comment]
I don't personally listen while reading the Bible and I don't think Jesus
did either😁, so I vote for keeping this function.

**Comment by BryceSteuer** [comment]
Nor do I listen to music (that personally would be an extreme distraction) - but I may listen to a sermon from another app while looking up the references mentioned in the sermon in the andBible app.

**Comment by tuomas2** [comment]
It was easy to solve (#1614)

**Comment by Dleemuse** [comment]
Lol, I don't listen to music while studying the Bible either. 




Sent from Yahoo Mail on Android 
 
  On Sat, Aug 21, 2021 at 1:20 PM, Tuomas ***@***.***> wrote:   


It was easy to solve (#1614)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
