### ISSUE TITLE
Fresh new layout for homepage (andbible.github.io)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1608]

**Comment by BryceSteuer** [comment]
I was just thinking along these lines this morning, and was going to suggest this. But how providential, you have already.

**Comment by tuomas2** [comment]
PR to https://github.com/AndBible/andbible.github.io would be appreciated :-)

**Comment by tuomas2** [comment]
Oops I forgot that we use template in this main repo, see play/homepage_template.html . compile_description.py is used to compile it with latest content.

**Comment by BryceSteuer** [comment]
Are you thinking mostly changes in the css/styling without major changes in the actual content?

I'm very comfortable working with html/css, I've worked also a bit with js and C#, but I don't feel as comfortable working with those.

**Comment by tuomas2** [comment]
I'd like primarily to get new layout. 

Content is slightly updated after 4.0 is released. I think Google Play description is main content and tutorial videos and related graphics are useful content. But I'm open to improvements. 

@agrogers might have ideas for changes to content?

**Comment by agrogers** [comment]
The site content is pretty good already. Making the header more beautiful
would be good. Links to the new features video. And some compelling
screenshots is all I would add.

**Comment by tuomas2** [comment]
If you @BryceSteuer will try to make a facelift then :-) Can you estimate when you would have time to do it?

**Comment by BryceSteuer** [comment]
I should be able to do it in the next two weeks. I have a big standardized test to take next week, and after that I'll be free. It should only take 3-5 hours in my estimation anyway. Do you have a preferred time schedule you want it done by?

**Comment by tuomas2** [comment]
Well we will release as soon as we get tutorial videos from @agrogers and some translations finalize :-) If we get it before release, great, but if not, it's okay also a few weeks after too.

**Comment by BryceSteuer** [comment]
@agrogers Could you provide me with some good screenshots of AB major features for the webpage? Perhaps each category that you discuss in the promo video.

**Comment by BryceSteuer** [comment]
How exactly do I get to editing the html and css? Do I need to do a clone or something? (sorry, I haven't done really any collab on github before). Once I'm in a place where I can edit, I should be fine from there

**Comment by tuomas2** [comment]
Are you familiar with git? Clone homepage repo https://github.com/AndBible/andbible.github.io and make pull request against it.

**Comment by tuomas2** [comment]
You can do changes directly there. I can change it to template later (`play/homepage_template.html` on this repository, which is usually used to update homepage).

**Comment by BryceSteuer** [comment]
Now that I have it cloned, I can just edit from my VS, then when I'm done do a PR? Or am I missing something?

**Comment by BryceSteuer** [comment]
Or it seems right now I don't have permission to do a push to the master.

**Comment by BryceSteuer** [comment]
Ok, so from the homepage repo I can change the css, but can you specify how I ought to edit the html from the template page?
Sorry for the confusion

**Comment by agrogers** [comment]
I'm hoping to have initial videos finished this week - before Saturday. I
will share the screenshots I have been taking tomorrow.

**Comment by tuomas2** [comment]
@BryceSteuer if you want to edit template html directly, you must fork & clone main repository (this repo) and edit play/homepage_template.html . I'm using make tx-pull to fetch translations and compile descriptions from template, which also complies homepage_template.html for me in final form.

But if this is too technical, you can just edit the homepage repo, make a pull request, and I will extract new template file when you are done. As long as you don't do a lot of changes to content blocks, it will be easy task to do that.

**Comment by BryceSteuer** [comment]
I need to be able to see how the project webpage is going to look before I finish, if that's possible. I can have a rough outline of how I want the layout (and I do), but I never know if it looks good until I run it. Is there any way I can do this?

**Comment by tuomas2** [comment]
You mean you need to be able to show how page looks like locally? 

how about going with your google chrome to file:///*full_path_to*/homepage/index.html ?

**Comment by tuomas2** [comment]
![Selection_182](https://user-images.githubusercontent.com/5811789/130465766-c72e340b-cd24-42c6-9834-b8c5130d010f.png)

**Comment by BryceSteuer** [comment]
How are you getting that path homepage/index.html?
![image](https://user-images.githubusercontent.com/48736452/130469220-e6594d47-a697-4fd0-a406-47acd86e3186.png)

**Comment by BryceSteuer** [comment]
I have index.html (1 kb file) in the and-bible.io cloned repo but it just redirects me to andbible.github.io. It's not local like the screenshot.

**Comment by tuomas2** [comment]
> Are you familiar with git? Fork homepage repo https://github.com/AndBible/andbible.github.io and make pull request against it.

I was thinking that you just edit this directly.

**Comment by BryceSteuer** [comment]
Ok, I'm making progress in it. https://github.com/BryceSteuer/and-bible
Also the css. @timbze offered to teach me some Git, so that should help a lot. This is quite a learning experience, but I'm glad for it!

**Comment by BryceSteuer** [comment]
@agrogers No pressure, but do you have those screenshots yet?

**Comment by BryceSteuer** [comment]
I'm pretty much done except for some finishing touches - and the screenshots and YT video. However, I will be in another city without my computer until next Monday, so I will do PR either then or Tuesday Lord willing. The data I asked about on Telegram was for an idea to put it up on the webpage.

**Comment by agrogers** [comment]
Hi Bryce

I will try to get some screenshots together this evening.

Tuomas, where is a good place to store these? I can just email them? But
maybe it is good to have a repository of screenshots that show off the best
features. I would like you guys to add some tablet screenshots - any maybe
some videos. My sister's tablet is really low res so not so good for
screenshotting.

Thanks
Andrew
___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Maybe for now just google drive or google photos, but when it comes to google play store pics, see #1127.

Homepage repo can have more pics than play if needed.

**Comment by agrogers** [comment]
Hi Bryce

I have uploaded screenshots and videos i have been using for the videos here: https://drive.google.com/drive/folders/1YsrELQbLnjmbhFHurx5sfvVXRZaIyZNL?usp=sharing 

You should be able to get plenty of images from there.

**Comment by BryceSteuer** [comment]
Thanks a lot. those are good.

**Comment by BryceSteuer** [comment]
As for the videos, are those to be on youtube or do you think those should be embedded in the page itself (that would slow down the page significantly I think).

**Comment by tuomas2** [comment]
I don't think embedding youtube videos will slow site down (like we currently have).

**Comment by BryceSteuer** [comment]
I meant it might slow down if I embed the .mp4 via <video>. But I have to check into that a bit more. For sure, a <video> rather than a YouTube iframe would reach more people, because many don't have access to YT that I know of. So will we upload those videos from the google dropbox to a YT playlist or something?

**Comment by tuomas2** [comment]
that is bad idea to host mp4s. we use YouTube currently for that.

**Comment by BryceSteuer** [comment]
So you will put those mp4s together in a YT playlist? Should I wait for that or PR to andbible.github.io now?

**Comment by agrogers** [comment]
Hi Bryce. Yes, the videos are going up to youtube and into playlists. So
that will be fine. Finalising that today.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by BryceSteuer** [comment]
Sorry, I want to be clear (not that you were unclear, but my understanding is). So should I PR now, or wait until the playlist link is ready so I can add that as well before the PR? If I need to wait for the link, I can just PR probably tomorrow afternoon,depending on when its ready.

**Comment by agrogers** [comment]
Um, good question. Two pull requests shouldn't be a problem. Would be good
to see what you have done as soon as we can.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Yes; it might be good idea to provide even screenshots of the worked layout so that we can provide comments. But PR's are cheap and you can always improve after creating intial PR.

**Comment by BryceSteuer** [comment]
Alright, sounds good. I will be out of home for a few hours this morning, then I should be able to PR when I get back Lord willing.

**Comment by BryceSteuer** [comment]
I might be able to do it quickly now but I wouldn't be able to provide lengthy descriptions and discussions about it until later. But now I will provide a few screenshots.
![image](https://user-images.githubusercontent.com/48736452/132520153-0509e9fc-9de9-4bab-b85d-070c509174ce.png)
![image](https://user-images.githubusercontent.com/48736452/132520230-773a67d7-2fc6-41bf-afee-a3301765945c.png)
![image](https://user-images.githubusercontent.com/48736452/132520288-57e9e3f8-17a9-4239-b903-e90cfbc99e9d.png)
![image](https://user-images.githubusercontent.com/48736452/132520342-823042e8-2c45-461f-8a1a-f0d04739daea.png)
![image](https://user-images.githubusercontent.com/48736452/132520411-af54906f-0522-4258-b526-898f15ca1503.png)

There were only two major actual content changes - both of which can be reversed if they are undesirable - first the statistics counter at the page top, then adding the new features of v.4 to the features list. Apart from that (and the new screenshots) all content is pretty much the same.

**Comment by agrogers** [comment]
Great. Looking good.

**Comment by tuomas2** [comment]
How did you get the number 150000 for users?

**Comment by tuomas2** [comment]
I cleaned up the PR so that font awesome is used from CDN

This is not so urgent that we have to do it today. Basically it looks quite good, but there are some things that
we most likely want still to improve. 

https://github.com/AndBible/andbible.github.io/pull/3

If you or anyone wants to improve it, please base your work (and make your pull request) towards this branch https://github.com/AndBible/andbible.github.io/tree/improve/webpage_upgrade

**Comment by BryceSteuer** [comment]
@tuomas2 I had seen at one point about a year ago that installs from Google Play was "120,000+", and I know there are many more installs from other platforms. I think I should add a "+" after each number to indicate that is the least amount suspected.
i.e. 150,000+ users
700+ languages, etc.

**Comment by BryceSteuer** [comment]
Another minor issue is the .ico file showing up in the title. It is not transparent. View from in tab:
![image](https://user-images.githubusercontent.com/48736452/132715258-be8cda5b-cb93-4bd3-ba98-916b93e21712.png)

Then view from out of tab
![image](https://user-images.githubusercontent.com/48736452/132715339-08dbb738-9878-4bb3-a46c-c2d9bd51ebf5.png)

I tried convert ico to svg, but it ends up distorting the image because of the gradients.

**Comment by BryceSteuer** [comment]
"but there are some things that
we most likely want still to improve."

Anyone want to say what else might need improvement? Any input would be valuable.

**Comment by agrogers** [comment]
I haven't had a chance to look at it yet. Will let you know when I have.

**Comment by BryceSteuer** [comment]
Should I just pr now then? Or have you not seen it yet?

**Comment by agrogers** [comment]
Sorry Bryce. I still haven't got to it yet. I have not had much time for AB
over the last couple of weeks. I will have a look at it tonight after work.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by agrogers** [comment]
Hi Bryce. Managed to get it on my PC tonight. I am still finding my way around Github as well. A few things I noticed. I will include images below for these things. Maybe it looks different on your system?
1. The header doesn't work so well on a mobile device. Did you use the Chrome option to view it as though it is on a mobile? That is where I can see the issue. The solution is probably to make the header font smaller on different devices.  I have done a lot of Wordpress but very little raw webpage design. But it looks like you have some media css entries so you are half way there.
2. The subtitle probably needs some work as well. Too large again.
3. What happens to the 'Discover' sidebar on smaller screens? It seemed to just disappear for me.
4. It looked like the Discover sidebar has almost the same functionality as the round buttons along the bottom. I like those images - perhaps the icon inside could be a little bigger. Just add a font-size of say 20px to the icon.
5. I feel like those bottom icons could replace the rectangular buttons in the sidebar. And possibly just include the text under the circular icon.
6. When i hover over the menu options at the top something changes which causes the text to move slightly. Text shouldnt move when hovering i dont think.
7. The new videos are available now. So you could link to those.
8. Might be nice to also link directly to more than 1 video or playlist.
9. The old screenshots probably need to go. I have some new ones but not here on this computer. There are lots of videos in the Drive folder i gave you a link to. You can grab screenshots from those videos as well.
10. It would be nice if the screenshots worked like a gallery where we could click on them and see them in bigger format. I have no idea how to do that outside of Wordpress (or Joomla). I guess it would need a JS library or something. Not so important for desktop viewing but they are very small for mobile devices.
11. I would only show 3 or at most 4 of the same type of screenshot. So 3 colors, 3 fonts, 3 maps etc would be enough.
12. The official title is now "Bible Study App". I guess we should have that as the main heading.
13. The tag line i have been using is "The only study Bible you need." Might be good to include it.
14. You could reduce the "By And Bible Open Source Project" text size quite a lot. It should stay at the top though so people see it.
15. I would probably increase the line-height to 1.7em. Feels a bit better to me.
16. The black dots between the menu items might look better in white. Perhaps just as a vertical bar?
17. I like the counters at the top. Can you put a comma in the larger numbers? eg 1,800 not 1800
18. The "Study the Bible...." at the top  could be centered 

Ok, there are some thoughts for you. Well done on getting that together. Not easy building these things from scratch. Like I said, i have never done that before!

![image](https://user-images.githubusercontent.com/13920678/134336541-ae983e89-d6f4-47cc-80b4-21fbe562f3ff.png)
![image](https://user-images.githubusercontent.com/13920678/134337288-b69f0b35-30be-4f86-b204-6b7f68d32835.png)
![image](https://user-images.githubusercontent.com/13920678/134338937-a3538eef-0f3a-4172-9923-c67f2126466e.png)

**Comment by BryceSteuer** [comment]
How about this so far, applying all your suggestions (I also make sure it works for smaller screens even less than 300px and even on Chrome too).

 The sidebar in smaller screens is hidden because it would by default float to the bottom and run right next to the other round icons that display pretty much the same thing. I would however like to keep it for larger screens as I think it is a concise summary one can see without having to scroll through the whole page. 

About the image gallery enlarger (I think it's called a lightbox) - I'm not so great in JS either so I may get [some code from w3schools](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_js_lightbox) and tweak it to the page's needs.

I also have plans to fix the counter up a bit, including your appropriate suggestion in that regard.

Thanks for the compliments, but honestly and strictly this is not a from-scratch webpage; I took the original one and made my own additions and deletions to it.
![image](https://user-images.githubusercontent.com/48736452/134743470-bf572453-c39f-46d7-b001-e3ebba6e4940.png)

**Comment by agrogers** [comment]
Hi Bryce. Thanks for this. I will try and have a good look soon.

**Comment by BryceSteuer** [comment]
I hope to PR either Oct 4 or 5 (hopefully the 4th), with the last edition. It will be styled for screens 300px+ in width (the narrowest screen now is 320px, so the page will display correctly on all devices). Also I implemented AG's suggestions, including a gallery viewer for screens narrower than 800px, commas in the counter, new videos, etc. Also I plan to implement some key user reviews in a forefront position on the page before PR'ing. Just a heads up, that's my plan if the Lord wills.

**Comment by agrogers** [comment]
Great. I will try and check it today after church

**Comment by agrogers** [comment]
Hi Bryce

I couldn't find your latest changes. Have you published them into a
repository that you own?

Thanks
andrew

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by BryceSteuer** [comment]
AG Rogers, I push my changes to [this](https://github.com/BryceSteuer/andbible.github.io/tree/improve/webpage_upgrade2) (my clone of the official andbible.github.io). From there I will PR when all changes are complete, hopefully either today or tomorrow. Sorry if I was misunderstood in any way.

**Comment by bvahedy** [comment]
Bryce, it looks good but the top image is cutoff to the right:
![Screenshot_20211004-092326_Samsung Internet](https://user-images.githubusercontent.com/46405809/135888374-8c149670-8030-4fd6-8d71-30c8bdb8abd9.jpg)

**Comment by timbze** [comment]
@bvahedy that is still the original site. Bryce's changes are only on his repo, and not visible easily yet. You have to download his branch and check it on your computer for now

**Comment by tuomas2** [comment]
BTW Bryce could set up github.io hosting for his development version so that we could see it in action

**Comment by tuomas2** [comment]
how to do it: read here https://pages.github.com/

**Comment by BryceSteuer** [comment]
![image](https://user-images.githubusercontent.com/48736452/135895299-99d9b3eb-dec0-4f8a-8a5f-990e4ebc9c64.png)
What does it mean here that my changes may be overwritten? Am I on track here?

**Comment by BryceSteuer** [comment]
I guess that figured itself out, here is the link:
https://brycesteuer.github.io/andbible.github.io/

**Comment by bvahedy** [comment]
Now that looks beautiful. Great job Bryce, I like the counters up front.

**Comment by timbze** [comment]
1. Get it on "Google" should probably rather be on "Play Store" or "Google Play"
2. "For idea requests or bugs in the app" could be "For ideas, feature requests or bugs in the app"
3. "Alternatively e-mail" could be "Alternatively, contact us via email at"
4. I'm wondering if Google discussion group should be secondary after Telegram and Matrix, but I guess that doesn't matter much
5. I think for enhancements, instead of "please email And Bible Support" it might be better to change to "Please add a comment on an issue you want to work with or email And Bible support"

**Comment by tuomas2** [comment]
User count is indeed cool but we don't know how many users we have. We have some clue about Google Play users (it's bit less than 70k devices that have AB installed according to Google Play). Yes it says 100k+ downloads, but that does not equal with number of users necessarily (uninstalling users also count in downloads).

**Comment by agrogers** [comment]
Yes, looking good Bryce. Thanks

This video is an old one
[image: image.png]
And some images have got stretched out of their original ratio. Just need
to remove either the width or the height property.
[image: image.png]
___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by BryceSteuer** [comment]
@bvahedy Thank you very much. I am glad to use what skills I have to glorify God and serve others.
@timbze Those all sound like good suggestions; I plan to implement them all.
@tuomas2 Do you recommend completely removing that section of the counter, or merely changing it to something like 70k+?
@agrogers I will remove the old video, also the last image of the stretched images is not working for me to view. What screen width are you viewing it on when you encounter that issue?

**Comment by timbze** [comment]
Re: stretched (501 pixels width). It also did look a bit stretched on my regular screen with 1920px, but I wasn't 100% sure so I hadn't mentioned anything.
![Screenshot from 2021-10-05 11-52-09](https://user-images.githubusercontent.com/35117769/136076537-348a295a-fa17-429b-a6d5-b60808d65791.png)
)

**Comment by BryceSteuer** [comment]
Thanks for that. I had put checks against stretch in place, but apparently they only work for 500px or less. My laptop is only 1400px long, so if you have any insights from a 1900px screen freely let me know and I will try addressing it.

**Comment by BryceSteuer** [comment]
For some reason embedding the new playlists is fruitless, even though following the link directly leads to the newer playlist the actual embedded playlist is the older one from version 3.3 for some reason I cannot explain. So I will just embed a few individual tutorial videos unless anyone else has input on how to fix this strange issue. Hopefully can figure out issues or can PR now if you want,if not now then have to be in about 24 hours.

**Comment by agrogers** [comment]
Good point. Tuomas, can we make all new videos viewable now?

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
@BryceSteuer try this link https://www.youtube.com/embed/videoseries?list=PLD-W_Iw-N2Mn5N3KSmNsb2IuBbR1XVLke

Maybe you have tried "All Tutorials" playlist, which indeed has old tutorials in the beginning.

**Comment by tuomas2** [comment]
@agrogers all tutorials are viawable and appear in playlists. I have revealed them to "public" one by one, and I think it's good to do that way because we don't have too much "regular content" to channel audience otherwise. We could also schedule them to be released in this manner.

**Comment by tuomas2** [comment]
My comments
- Google Discuss -> Google Groups, change icon to Google Groups icon (it's now hangouts icon)
- Email us: link takes to Google Play. Should go to help.andbible@gmail.com.
- Google Play link: change to Google Play actual icon (now Chromebook or some old icon)
- F-droid also could have actual icon that F-droid uses
- "Get it on Amazon kindle" -> "Get it from Amazon App Store" (it is available to other devices too, and soon to Windows 11).
- Page coloring: pick colors from icon and use other colors that fit well. If you have trouble finding good ones, I can consult my wife, she had influenced greatly when choosing the colors to the icon :-) Especially Green background color in "Download" buttons does not look pleasing to me.
- I would try if it looks better with brown primary menu bar 100% wide. Or could try making black header as wide as brown one.
- User count: either 70,000+ or not at all. @agrogers opinion about this?
- Black background header could look better if centered (like brown menu bar is)
- Perhaps adding left padding to screenshots would make them look better under their titles (also other content that is under (sub)titles).

**Comment by agrogers** [comment]
I like the number counter. Let's just make it as accurate as possible.
70,000+ is good.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Let's put 60,000+ Because it's actually 68,567 as of today.

**Comment by BryceSteuer** [comment]
Tuomas, I have implemented all of your suggestions save one, that is the colors for the sidebar buttons. If you could consult your wife about that I think it would be much better. When reviewing the page I did think the light green especially looked a bit childish or gaudy, but I thought to leave it so unless you or another developer disagree.

**Comment by BryceSteuer** [comment]
Another thing - the last issue I am aware of - is that the tablet images (Only shown on screens wider than 900px) are low-res 
![image](https://user-images.githubusercontent.com/48736452/136435161-ecebf730-8345-40d3-b3da-08c22ce133d5.png)

**Comment by timbze** [comment]
The links toward the end under "Helping" don't open in new tab. I think they should. I checked some other links that did but have not checked the whole page.

**Comment by BryceSteuer** [comment]
Ok, I will make sure all `<a>` have target="_blank" attribute.
Edit: Now fixed.

**Comment by tuomas2** [comment]
Email link is not working. url should be mailto:help.andbible@gmail.com

Looks better now after changes!

**Comment by BryceSteuer** [comment]
Fixed email in latest commit. I think the only questionable items left are the colors on the sidebar links, and the low-res tablet images (maybe omit tablet images for now?). Unless anyone else has any more input I've overlooked.

**Comment by tuomas2** [comment]
Allright I guess I can merge this now. Improvements can be made later as separate PRs.

**Comment by tuomas2** [comment]
Thank you for doing this!

Related PR now merged: https://github.com/AndBible/andbible.github.io/pull/4

**Comment by tuomas2** [comment]
And then also this.
https://github.com/AndBible/andbible.github.io/pull/5

**Comment by BryceSteuer** [comment]
Thanks, I was glad to help. Let me know when you are ready to do some minor fixes and PR in the future.
