### ISSUE TITLE
Bible list view should by default show all installed bibles of all languages

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#161]
Preferrably with langugages as subtitles somehow. Need to investigate if there are good ways to implement this.

**Comment by mmm4m5m** [comment]
Under "Choose Document", it could be useful to select "all languages" (and eventually "all documents). Similar way, in "Compare translations" we see together all translations.

**Comment by tuomas2** [comment]
Hmm, isn't this implemented in 3.3 already?
