### ISSUE TITLE
Upgradable documents in Download screen

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1610]
When going to "download documents" screen, it should show upgradable documents always, even if they are from different languages than the one that is selected.

Opinions?

**Comment by agrogers** [comment]
I wouldn't think so.

The document selector gives me trouble often. Did I raise an issue that
said we need an 'All Languages' menu option at the top of the languages
list?

I find the language often automatically changes back to English (or
something else) when what I want is ALL.

If the ALL language choice is set the user can see all they need.

Perhaps moving the ones that need updating to the top would be good

**Comment by agrogers** [comment]
I did

https://github.com/AndBible/and-bible/issues/1510

**Comment by agrogers** [comment]
I also added this ticket a while back

https://github.com/AndBible/and-bible/issues/1330

Perhaps an additional tab could show Update documents (Available, Update,
All)

**Comment by tuomas2** [comment]
- [x] If not affecting filtering then, at least show upgradable documents on top (if filtering matches).
