### ISSUE TITLE
If music is playing, do not bind volume up / down

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1614]
Is it usual that people listen to music while studying bible? If that's the case, we need to disable this alltogether in 4.0, because it will annoy people. I never do that myself. 

Or we might need to figure out if we can know if there's some music playing. I don't know if that's possible.

_Originally posted by @tuomas2 in https://github.com/AndBible/and-bible/issues/1604#issuecomment-903152686_

**Comment by timbze** [comment]
> Or we might need to figure out if we can know if there's some music playing. I don't know if that's possible.

From some sample apps I played with when I started dev on Android, I think it's possible. See [this answer](https://stackoverflow.com/a/7792893/877453) on SO for example. System's `AudioManager` has a method `isMusicActive()` according to that answer.

**Comment by tuomas2** [comment]
Thanks! Then it's easy.

**Comment by agrogers** [comment]
I would listen to my esv audio book and read the bible sometimes. But not
music.
