### ISSUE TITLE
Implement long press menu on the Greek/Hebrew icon

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1618]
One thing that bothers me just a little is having to cycle through the three states of the Strongs links. I rarely want to show the numbers, but i have to show them to get back to the non-Strongs view. It's not a big thing but it just feels a little untidy. 

Actually, there is already a popup menu called 'Choose strongs mode'. It would essentially do that.

Perhaps adding a long press popup menu that shows the three options would be a solution. The menu could also show other Strongs related options too like going straight to the App Prefs > Dictionaries > Strongs Greek dict etc. Not sure there is much value in that.

![image](https://user-images.githubusercontent.com/13920678/130387822-e6e2fa5c-6384-47cc-905f-b7df8d5eb8d1.png)

**Comment by tuomas2** [comment]
Thank you, good suggestion and easy to implement
