### ISSUE TITLE
Make the icon to access the information page consistent

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1622]
These two icons take you to the same form. I think they probably should be the same. I think the most logical icon is the Info one.

![image](https://user-images.githubusercontent.com/13920678/130551737-25cea3a3-a865-413c-aa9b-91dac1f71e66.png)

**Comment by tuomas2** [comment]
"bookmark" icon is used, to open "bookmark modal" in general, not only from 1-click modal, but also from study pad 3dot menu. I think the idea here has been that there's bookmark icon indicating to users that this is a bookmark entry. But perhaps it is very clear without icon too, so we could try to have info icon instead.

**Comment by agrogers** [comment]
Or make both icons the bookmark icon -I could go either way. Although all
the dialogs are bookmark dialogs - we have info, edit note and summary
dialogs for the one bookmark.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by agrogers** [comment]
Does the bookmark icon only ever open this dialog in this view? 
![image](https://user-images.githubusercontent.com/13920678/130568692-2ad01ac6-dd6d-4633-9943-6675a48a2a5d.png)

**Comment by tuomas2** [comment]
It does open "edit" mode if there is something written in notes. Maybe that could/should be changed when opening from study pad (which already displays editable notes anyway).

**Comment by agrogers** [comment]
Oh, does it? The Edit button and that button then go to the same form.

Yes, I think the bookmark button should go to the info page and the edit
button to the edit page.

And whatever icon you choose it should be consistent in both locations.

**Comment by tuomas2** [comment]
What is your preference for icon?

**Comment by agrogers** [comment]
Probably the Info icon. It's a little closer to what it represents. But I
wouldn't lose sleep over the other.
