### ISSUE TITLE
Duplicate bookmarks after updating documents

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1623]
https://support.andbible.org/scp/tickets.php?id=707

**Comment by timbze** [comment]
MyNotes in window showing more than once
https://support.andbible.org/scp/tickets.php?id=988

**Comment by tuomas2** [comment]
Closing this in favor of #1965

**Comment by tuomas2** [comment]
This still happens, after installing documents (for example epubs) from a file.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2130

**Comment by tuomas2** [comment]
Also removing documents does this (just reproduced by removing multiple epub docs)
