### ISSUE TITLE
Is it possible to share entire bookmark or study pad? 

### ISSUE THREAD

**Issue by Dleemuse** [AndBible/and-bible#1625]
For exame, I have a bookmark entitled Divination, Mediums, Fortuntelling, with lots of scripture in it. Is it possible for me to share the entire bookmark/study pad? I have looked but but can't figure it out.

Thanks

**Comment by bvahedy** [comment]
Yes, in studypad window with the list of your item, tap and hold on one of
the items and select all our partial and then tap share.

**Comment by Dleemuse** [comment]
Apologizing in advance Ben, for my ignorance.

I went to upper left 3 line menu, selected Study Pads, selected Divination to open this particular Study Pad. Tried long pressing both study pad title & a couple of different scripture, both links & text. What am I doing wrong?

![Screenshot_20210824-101346_Bible Study](https://user-images.githubusercontent.com/83124765/130643358-3e2b29e5-f73f-40c1-b405-0126daaaacdd.jpg)

**Comment by Dleemuse** [comment]
Not sure why Strong's numbers are showing, they were not showing when I added any of these verses to the bookmark.

**Comment by Dleemuse** [comment]
Figured out the Strong's part, must have accidently hit the button.

**Comment by bvahedy** [comment]
You must tap and hold on a non link part of any verse to invoke the system
dialog that allows you to do a select all. Don't do it on the title either.

**Comment by Dleemuse** [comment]
Lol, thanks, figured it ojt
