### ISSUE TITLE
Bug report sent through the app on 8/19/21

### ISSUE THREAD

**Issue by Dleemuse** [AndBible/and-bible#1626]
Checking to see if you received a bug report I sent through app on 8/19/21, I didn't hear back. Screen shot below... 

![Screenshot_20210824-094207_Yahoo Mail](https://user-images.githubusercontent.com/83124765/130638277-a581b8ee-1758-4982-a593-cd986aa29df2.jpg)

**Describe the bug**

**Bug was found on And Bible version**
Build XXX.X or version X.X.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S6]
 - OS: [e.g. Android]
 - Version [e.g. 8.0]

**Additional context**

**Comment by bvahedy** [comment]
Tap on the three dots on the top right hand corner and choose a different
sort order for book display.

**Comment by tuomas2** [comment]
@Dleemuse some error reports had gone to spam folder.

I'm checking spam folder once a month so that nothing will not get lost permanently. But those in spam folder may get slow response. Now restored from spam.

**Comment by timbze** [comment]
@Dleemuse what is weird? That the books are ordered in rows instead of columns? See Bens response if it's that. There is a setting for it now in the 3-dot menu top right.

**Comment by Dleemuse** [comment]
Sorry, I wasn't more clear, Covid brain.

On above screen shot, where it says "Choose Book" it shows (Baptism saves yo... 

I don't remember this being there until recently. It really could be something I accidently did.

**Comment by timbze** [comment]
Ok, that is the workspace name that you are currently in. You can go into your workspace list and change names if you want it to change.

**Comment by Dleemuse** [comment]
Thanks
