### ISSUE TITLE
Edit note button

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1629]
"Edit note" button is not obviously enough different when there's note or not. 

![Screenshot_20210824_191246](https://user-images.githubusercontent.com/5811789/130652092-7b3aa05a-fd9e-46f5-83aa-6880152dcb96.png)

**Comment by tuomas2** [comment]
Also, edit note button should be moved a little up, IMO.

**Comment by agrogers** [comment]
Just realised I am going to have to redo those videos. I proposed a rod for
my own back 🤔

**Comment by timbze** [comment]
> Just realised I am going to have to redo those videos. I proposed a rod for my own back 🤔

I personally would not redo the videos for this change. The pace is quite fast on the videos, I don't think anybody will be confused for a single different icon in 1 state of 2 (has note or does not have note).

**Comment by agrogers** [comment]
Thanks Timmy, i have always liked you ;-)

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
I agree with @timbze. Redoing is needed only if we do very dramatic ui changes. There will be always small ui changes coming and redoing videos always would be ridiculous amount of work.

**Comment by agrogers** [comment]
![IMG_20210825_203117.jpg](https://user-images.githubusercontent.com/13920678/130775128-da8ad30b-2fb8-406e-8dc7-ddeb46f5aa7a.jpg)

**Comment by tuomas2** [comment]
Is it better that I just vectorize this with inkscape or do you have already good quality svgs available?

**Comment by agrogers** [comment]
I have good quality. In a zoom Bible study so can't get it. You like it?

**Comment by agrogers** [comment]
Attached
[Icons.zip](https://github.com/AndBible/and-bible/files/7046461/Icons.zip)

**Comment by tuomas2** [comment]
Hmm something is wrong

![Screenshot_20210825_144852](https://user-images.githubusercontent.com/5811789/130785388-e4ad3fd7-4477-43f3-84a8-db8bd825f916.png)

**Comment by tuomas2** [comment]
Oh, my bad. There are 2 paths and I just stupidly copypasted them both

**Comment by agrogers** [comment]
:) Yes, i didn't fix these - just gave you the raw svg from flaticons

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
There's pen-square icon in fontawesome that would make perhaps even clearer distinction: https://fontawesome.com/v5.15/icons/pen-square?style=solid

**Comment by agrogers** [comment]
I like them too. Bit more balanced - you wont have to move those up or down

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
![Screenshot_20210825_154851](https://user-images.githubusercontent.com/5811789/130793353-e457cec2-613b-44c0-a6eb-e8daed71c0e3.png)

**Comment by tuomas2** [comment]
Now it's inconsistent with other places referring to notes with "edit" icon. But is it ok?

**Comment by agrogers** [comment]
I think I like the look of the other one a little more. But I could get
used to this one.

In the screenshot it is shorter than the other icons. It would look better
if it was the same height.

Yes, there are quite a few places where it is used.

**Comment by tuomas2** [comment]
Tried but I like the original "edit" icon more in other contexts. Would it be bad if we keep it as it is now in other context, but change only here? Hmm.

**Comment by agrogers** [comment]
I would probably keep it consistent throughout. Or perhaps use the new icon
only for when there is an existing note.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Okay, let's try like this for now. => New icon if there is an existing note only.
