### ISSUE TITLE
Persecution security issue with "Questions?" menu option

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1630]
Clicking "Questions?" options takes you directly to the AB wiki page. The URL contains "and-bible".

I am wondering if this carries the same type of risk as connecting to SWORD repos without asking the users consent.

Related to #178

**Comment by agrogers** [comment]
Good point.

Maybe there are three states the software should know about - free,
cautious, and dangerous.

Free means there are no prompts or warnings and nothing changes.
Cautious means you are prompted whenever access to the internet is required.
Dangerous means you are prompted and all the covert features discussed have
been implemented.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment]
May be in persecution mode we should force them to use a VPN before
attempting to use the internet.

**Comment by tuomas2** [comment]
url is not revealed, only domain name is. path is delivered (by browser, that we hopefully can trust, like we must trust the OS as well) via ssl encrypted channel (it is https url)

**Comment by tuomas2** [comment]
So I believe we are safe here. If you still find reasons to disagree, please re-open.

**Comment by timbze** [comment]
Ok I think you're right. In my mind I thought the URL was sniffable over https but I guess it's just the domain. Seems like even that may have become harder after TLS 1.3. Found [this article](https://www.zdnet.com/article/china-is-now-blocking-all-encrypted-https-traffic-using-tls-1-3-and-esni/) from last year interesting.

**Comment by tuomas2** [comment]
Found this: https://stackoverflow.com/questions/499591/are-https-urls-encrypted
