### ISSUE TITLE
The OK button disappears in the backup documents dialog

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1632]
From: https://support.andbible.org/scp/tickets.php?id=691

> Hello the application has a little bug in the backup menu
> 1- Save / restore
> 2- Save documents to ...
> 3- Select all
> 4-the "OK" button to confirm the save disappears (see capture)
> 
> To save I have to manually select each document and then the OK button works.

It works fine in the latest beta in English. Goes weird in French (see my screenshot at the bottom)

![image](https://user-images.githubusercontent.com/13920678/130719007-b33266ce-13c0-436b-823f-4656864cd00f.png)

![image](https://user-images.githubusercontent.com/13920678/130719269-d7d276a6-f397-416d-9526-7ae82f933101.png)

**Comment by tuomas2** [comment]
Now this is tricky as long as we use AlertDialog for doing this. Hmm.
