### ISSUE TITLE
From which repo easy setup / redownload installs docs

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1633]
....if doc is in multiple repos like kjv?

**Comment by agrogers** [comment]
I would always take it from AndBible first. At least we can control the reliability of those.

**Comment by tuomas2** [comment]
I was thinking about the logic. Should we specify the repository in default_documents.json? Or just have priority list between repositories? Third option which has proven bad would be to take from whatever repo provides highest version number.

**Comment by timbze** [comment]
If it goes by OSIS ID then KJV will only have 1 repo (i.e. Crosswire).

I don't think the other current defaults will have an issue either, that is for now.

But yes, I guess the logic should already be set. I think for automatic install there should be a priority list (e.g. Crosswire would be higher priority IMO than eBible)

**Comment by tuomas2** [comment]
I decided to add repository info to json files so it's explicitly defined.
