### ISSUE TITLE
Multiple references window blank after switching workspace 

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1636]
**Describe the bug**
1. From NASB open footnote that has more than 1 reference and click open all references 
2. The multiple references window opens
3. Switch to another workspace, then come back
4. The window is now blank. 
Expected -> it should reload verses that were open before 

**Bug was found on And Bible version**
Build 543

**Comment by bvahedy** [comment]
Verified fixed in 543.11 build.
