### ISSUE TITLE
Embed tutorial videos in-app

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1638]
Related: #1634

**Comment by tuomas2** [comment]
Hmm... I'm afraid including ExoPlayer (which is "the way to do it right") 
is a bit overkill and will definately increase apk size...

https://github.com/google/ExoPlayer

**Comment by agrogers** [comment]
How much bigger does it make it?

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
I didn't try and didn't find info with google when I tried. Somehow this just does not feel the right thing here. We are not implementing a video player software anyway!

I think I'll stay with linking to video as it is currently. We can continue considering other platforms (#1634).

**Comment by agrogers** [comment]
One thing I have been thinking about is making a commentary module based on
the Desiring God website. I thought i could scrape the list of all the
sermons etc and create a commentary with a link directly to the DG website.
Some of the look-at-the-book videos or APJ videos would be great to embed
them. I believe it could be done without violating their usage policy.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
