### ISSUE TITLE
Fullscreen bottom nav bar is gray 

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1639]
**Describe the bug**
Earlier my entire screen was used when in fullscreen. Lately it has changed, and now there's a gray bar the height of the nav bar. 

**Bug was found on And Bible version**
Build 543

![Screenshot_20210827-061345.png](https://user-images.githubusercontent.com/35117769/131126125-7e7223b3-6d75-48d0-9eee-a218ca2cbf74.png)

**Comment by tuomas2** [comment]
My guess is that this is due to this 6be9442d1f3bc92f2310d05d4615925729bf410a

**Comment by tuomas2** [comment]
Which was to fix #1617

**Comment by timbze** [comment]
Not a high priority issue for me, but wanted to record it anyway

**Comment by tuomas2** [comment]
I think it's annoying to have nav bar space visible in fullscreen. Though perhaps less critical than #1617, if we need to choose one...

**Comment by tuomas2** [comment]
Fixed in ad0d5571687cde703a28215e79503261e7502fcb

**Comment by bvahedy** [comment]
Verified fixed in 543.11 build.
