### ISSUE TITLE
Missing item in 3 dot menu

### ISSUE THREAD

**Issue by davidhrbac** [AndBible/and-bible#1640]
Settings text:

Whether to switch to night mode automatically (if device supports), manually or via system setting (Android 10+). Manual switching can be done from the 3-dot options menu on the main screen. 

Result:
I see no menu item 3 dot. Has it been removed?

**Comment by tuomas2** [comment]
![Screenshot_20210825_145756](https://user-images.githubusercontent.com/5811789/131210909-d443b7ff-5cd2-45a4-b4f7-7df35e585090.png)

Options menu on the right-top corner has three dots^

**Comment by davidhrbac** [comment]
Yes, so where is the **night mode** referenced in the text to translate?

**Comment by tuomas2** [comment]
It is shown only if night mode switching is set to "manual". In system and automatic mode it is hidden. Though it probably would be better to show it, just not have it enabled.

**Comment by davidhrbac** [comment]
OK, closing.
