### ISSUE TITLE
Note window hidden behind keyboard... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1649]
In the latest build 543.11:
When in full screen and a bookmarked verse near the top of the window. If you tap on the verse to bring the bookmark modal up, upon tapping on the edit icon on the bookmark the keyboard is displayed and the edit modal is hidden behind the keyboard.

**Comment by tuomas2** [comment]
Duplicate #1617

**Comment by bvahedy** [comment]
#1617 <https://github.com/AndBible/and-bible/issues/1617> says the window
is too tall, but my issue is that I can't even see the edit window. But I
guess it may be the same bug in the way the window is being presented.

—

**Comment by tuomas2** [comment]
It has the same root cause
