### ISSUE TITLE
Make font, background color and other bible layout parameters configurable

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#165]
Font configuration should be per-language or per-module. 

Uservoice: https://andbible.uservoice.com/forums/100177-general/suggestions/1993701-ability-to-change-font-background-color

Related also: https://andbible.uservoice.com/forums/100177-general/suggestions/1540293-implement-pinch-to-zoom-gesture

These could go to bible view options menu (moving from #269):

- Text formatting options (submenu item)
  - [x] Text size (move from settings)
  - [x] Font (new #165 )
  - [x] Colors (font color and background color #165)

In addition, these could be configurable:
  - [x] Adjustable margin (#156)
  - [x] Adjustable line height
  - [ ] Space between paragraphs (?)
  - [ ] indented paragraphs (with no space between paragraphs)

**Comment by tuomas2** [comment]
Font suggestions by user: Bitter, Allegreya, San Serif like Avenir

**Comment by LAfricain** [comment]
In some module (Porcap KonVb) a file style.css is provided with the module. Maybe Andbible can us it as Xiphos already did.

**Comment by tuomas2** [comment]
Will be implemented in next beta version > 340

**Comment by bvahedy** [comment]
Verified working in build 342-beta.
Note: that the css file in jsword folder overrides these font settings, as it should.

Great job on this feature.
