### ISSUE TITLE
Missing stings - Strong types

### ISSUE THREAD

**Issue by davidhrbac** [AndBible/and-bible#1651]
I'm not able to find strings from Strong's settings.

![signal-2021-08-29-092946](https://user-images.githubusercontent.com/728971/131242385-c46eca34-ab4d-4697-a756-cf6da256d588.png)

**Comment by tuomas2** [comment]
Good finding. I will add.

**Comment by tuomas2** [comment]
Done. Now it is in transifex ready to be translated.
