### ISSUE TITLE
Windows button behaviour 

### ISSUE THREAD

**Issue by davidhrbac** [AndBible/and-bible#1653]
I'm trying to translate: "Window buttons that are displayed on right side of the Bible views are hidden. Window navigation bar on the bottom is still displayed and you may open window popup menu by long-clicking them."

I'm not able to translate it meaningfully it seems to me it does not work for me. Can you explain how it works?

**Comment by agrogers** [comment]
Hi David

Thanks for working on the translations. It is a really important part of the app! Let me try to put it in different words.

First the text applies to the "Hide window buttons" App Preferences settings.  It is basically saying the that orange buttons below are hidden by this setting but the green navigation bar buttons across the bottom are still visible and that the window menu can be accessed via a long press.

I think it probably should read:

>  "Window buttons that are normally displayed in the top right of a window are hidden. The window navigation bar at the bottom of the screen is still displayed. Long-press those buttons to access the window popup menu."

![image](https://user-images.githubusercontent.com/13920678/131246220-16959d05-ac7c-417f-af24-fe4ce5bc056e.png)

**Comment by davidhrbac** [comment]
@agrogers but I can see the top-right button having the setting on and off. I see no difference.

**Comment by agrogers** [comment]
Wow, you are right. I didnt check that! Seems like you have found a bug.
Thank you

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by davidhrbac** [comment]
Thanks, closing.

Can you check #1652 for me too?

**Comment by agrogers** [comment]
Hi David

Tuomas responded to #1652

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
