### ISSUE TITLE
Google Play text

### ISSUE THREAD

**Issue by davidhrbac** [AndBible/and-bible#1654]
I see lots of untranslated items in Czech version of Play Store texts. On the other hand Google Play URL is translated to Czech and I'm not able to find it within Transifex.

![image](https://user-images.githubusercontent.com/728971/131244363-79020daa-bbba-4284-a310-bc2d29d76f1f.png)

How is the Google Play text generated?

**Comment by tuomas2** [comment]
Play store texts will be updated when we do the release.

**Comment by davidhrbac** [comment]
Good to know. Closing.
