### ISSUE TITLE
Add "Add (bookmark) note" button to the end of study pad if last item is bookmark

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1656]
![image](https://user-images.githubusercontent.com/5811789/131309156-c7bbcdb6-119e-4066-bacb-78ce333b9cda.png)

**Comment by agrogers** [comment]
Will this add a bookmark to the current verse?

**Comment by tuomas2** [comment]
It will start editing note to the last bookmark (if last item is bookmark).

**Comment by agrogers** [comment]
What if it already has a note?

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Let's see. I think button can be hidden then.

**Comment by agrogers** [comment]
What if you added an edit button next to the '...' button for the verse.
There is already an edit button in the flyout menu. But it is a little
hidden there.  It does what you want i think.

**Comment by tuomas2** [comment]
Yes that's an option, but it would take some space and is used less often. I think I need it most often only in the end of document.

**Comment by tuomas2** [comment]
Let me know what you think about how I implemented this.
