### ISSUE TITLE
When creating a new window via the popup menu on an existing menu, the new window should be the same type as the selected one

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1658]
That is, if i create a new window from an 'unpinned' window popup then the new window should also be unpinned.

I think the location of the new window perhaps should be next to the window used to create the icon.

**Comment by tuomas2** [comment]
Can't reproduce. works like you described

**Comment by agrogers** [comment]
Hmm, I can't reproduce it either! I must have got confused. Sorry 🙏
