### ISSUE TITLE
Indicate visually in studypad if a note is attached to a bookmark or not

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1661]
At the moment those are easily confused. At least when editing a note, it should be made more clear, perhaps with a border outline or something...

**Comment by agrogers** [comment]
That hasn't bothered me but i agree that it is not clear. I am not a big
fan of boxes as you know. Maybe some other way?

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by agrogers** [comment]
These two lines don't help. Removing them could be good but adding it after a verse note. 

I think we added them to distinguish them from the verse itself. Maybe that is not much of an issue. 

![IMG_20210902_163453.jpg](https://user-images.githubusercontent.com/13920678/131794323-c102f9d2-a58c-4d4b-bb7e-ccdf95a7b91e.jpg)

**Comment by tuomas2** [comment]
What if the outline border was only during edit (not normally, when viewing)?

**Comment by bvahedy** [comment]
I don't think there is anyway around this. We could just explain it as
studypad notes are extra notes made in addition to bookmark notes in a
lable. My issue was/is that if you can add a note to a verse, then what is
the purpose of adding additional notes, you can just say what you want in
the bookmark note.

**Comment by tuomas2** [comment]
"stand-alone" notes in a studypad are meant for a case when a note *does not* belong to a particular bookmark, but to a topic (a sermon, for example), connecting the dots.
