### ISSUE TITLE
Change the recommended KJV to the other Crosswire one

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1662]
Can we change the recommended KJV to the other one. And perhaps improve the naming of the currently recommended one.

The currently recommended one has the Greek word included in the link. This makes the links really long (and ugly). And it is only useful to people who can read Greek which I suspect is not too many of us. The other KJV just has the numbers which is much more beautiful.

It could be good to explain that the larger sized one includes the Greek in the links so a user can understand the difference.

![image](https://user-images.githubusercontent.com/13920678/131814160-8473e20d-9fb7-43c0-a66c-c14dcb24b3a3.png)

**Comment by tuomas2** [comment]
I'm okay with that. Opinions?

**Comment by timbze** [comment]
The eBible module has some issues, that's why I recommended to switch to the Crosswire module. See #1132 and https://github.com/AndBible/and-bible/issues/979#issuecomment-853964088

Also, #1284 will address Andrew's problem (i.e. lemma can be disabled). Morphology can already be disabled (e.g. "N-NSM" or "V-ADI-3S")

**Comment by timbze** [comment]
If Andrew means making the KJVA recommended, I guess that one will not have the issues that eBible has, but I would **not** support making that one recommended.

**Comment by tuomas2** [comment]
I'm also wondering if it is wise to recommend a document containing apogryphical texts.

**Comment by tuomas2** [comment]
Maybe I could take a look at #1284...

**Comment by bvahedy** [comment]
I agree with Timmy and Toumas, we don't want to push a document that
contains Apogrypha. That is mostly related to catholicism. And I for one do
not agree with their theology or doctrine.

**Comment by agrogers** [comment]
OK, didn't take note of the Apocrypha inclusion. What I dislike are the Greek words taking up soooo much space - see below.  It just makes the text look kind of ridiculous. I never use it now because of that and just use the NASB. But I want something with morphology every now and then. NASB doesnt have that as far as I am aware. I think the KJVs are the only two English translations that have it. Is that correct?

![image](https://user-images.githubusercontent.com/13920678/131923969-f2335fe9-5ffe-467d-ac93-249c6b2ee6e2.png)

**Comment by tuomas2** [comment]
I'll fix it as discussed, on #1284
