### ISSUE TITLE
Should we provide database migration for downgrade from 4.0 to 3.3?

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1664]
It seems that there are always some people that hate app updates, especially if there's a lot of changes...

Should we provide a database migration to downgrade back to 3.3? (while I think about that, should we provide one direct migration from 3.3 to 4.0 instead of the many parts that exist now?)

**Comment by bvahedy** [comment]
Excellent point Timmy. I'm sure there will be some who will want to go back
for simplicity sake. If they lose their database and can't go back they
will be pissed.

**Comment by agrogers** [comment]
Isn't it just a matter of them backing up the database before updating?

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
we should release 3.3.401 which is able to do that. hmm.

**Comment by tuomas2** [comment]
3.3.401 would need to be downloaded from Github then. Nobody would have time to get it via Google Play (and Google Play does not provide old versions anyway to users).

**Comment by tuomas2** [comment]
> Isn't it just a matter of them backing up the database before updating?

Yes - but users often don't get a chance to do that because Google Play is set up to automatically upgrade their app.

**Comment by tuomas2** [comment]
I think Room allows writing downgrade script. But Sqlite does not provide method to delete columns, so it would essentially mean writing those tables again. Sounds like quite some work....

Other option would be that we would somehow store backup of old db somewhere in 4.0 (meaning we would "backup" it just beforee doing migrations) and then would provide some access to that old db backup. Again we would have challenges to implement this feature without new strings... (but maybe it's acceptable to have this kind of emergency feature implemented without strings translated)..

**Comment by agrogers** [comment]
I like that option. The database file is small so it shouldn't be
a problem. Just need some way in the old version to locate that backup
easily.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
And it should be automatically removed let's say after few weeks of using 4.0.

**Comment by tuomas2** [comment]
That option implies that we need to provide "Save old 3.3 backup" option to Backup & Restore menu, if old backup exists.

**Comment by tuomas2** [comment]
Actually we do have some strings that we can use! We can label it '"Export as 3.3". (We have string "Export as %s" in strings).

**Comment by agrogers** [comment]
i wouldn't ask about it personally. i would just make a backup, store it
somewhere safe, and not remove it. If  they want to roll back then somehow
you can write some magic into the old version to get that backed up
database restored.



___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by agrogers** [comment]
If they ignore that message then we are back to square one where they dont
want the new version and cant easily get back to the old

**Comment by tuomas2** [comment]
Okay there are some migrations that are too complicated in order to write a proper backwards-migration. Auto-backuping old db in 4.0 and allowing user to export it is the only option I can think of implementing.

**Comment by tuomas2** [comment]
(I'm referring to especially Bookmark / My Notes migration).

**Comment by tuomas2** [comment]
Implemented it such a way that when there's a migration, it automatically back earlier version internally for 30 days (after which it automatically removes the backup). If there are backups available, it offers them via backup dialog:

![Screenshot_20210909_095728](https://user-images.githubusercontent.com/5811789/132638247-f7960a94-2a75-4363-86e9-2b97494c1eaa.png)

I know this is not super user friendly, but at least we can give people instruction how to do it if they need it.

**Comment by agrogers** [comment]
Oo, I like the showing of existing backups. That would be helpful for me
when i have removed and reinstalled the app.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by timbze** [comment]
Thanks @tuomas2, that's definitely better than nothing
