### ISSUE TITLE
Link highlight in cross reference modal makes it illegible (night mode) 

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1669]
**Describe the bug**
![Screenshot_20210905-063711.png](https://user-images.githubusercontent.com/35117769/132127076-f6098913-0a9f-4756-b72e-0d9c088d3f70.png)

**Solution:**
Either change the link text color when it has been clicked, or change the highlight in some way. 

**Bug was found on And Bible version**
Build 544

**Comment by tuomas2** [comment]
Made clicked link text brighter
