### ISSUE TITLE
New beta Strongs libraries don't work with JSWORD

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1672]
http://tracker.crosswire.org/browse/MOD-417

Need to investigate if this is JSword issue or module issue.

**Comment by tuomas2** [comment]
Does anyone know if there is a libsword based command line app that exports osis fragment for a certain key? 

I would like to see if the result matches with what JSword gives as a result. JSword clearly gives invalid XML, as seen in the provided example. It can be JSword bug, but that I would like to verify before going forward to try to fix the bug.

**Comment by timbze** [comment]
`diatheke`? I'm not sure if that does what you mean.

**Comment by tuomas2** [comment]
does it print xml to stdout?

**Comment by tuomas2** [comment]
> diatheke -b KJV -o OSIS -k Jh 3:16

yes it does

**Comment by tuomas2** [comment]
Diatheke seem to show it nicely.

**Comment by tuomas2** [comment]
Related: #957

**Comment by tuomas2** [comment]
As a consequence, some other modules (like StrongsRealGreek and StrongsRealHebrew) have key prepended to the content.
It looks like JSWord has been built to support some earlier type of document and it assumes plain text (not xml) content and removes first line (key) from raw content text.

**Comment by tuomas2** [comment]
But I feel this is acceptable. We can also abandon our Strongs modules and suggest using modules from Crosswire.

**Comment by tuomas2** [comment]
I.e. StrongsRealGreek looks now like this.

![Screenshot_20210918_140711](https://user-images.githubusercontent.com/5811789/133886705-7501d028-82f1-4089-8523-8ded2a8b5996.png)

**Comment by tuomas2** [comment]
New StrongsGreek (in Beta repository) looks like this:

![Screenshot_20210918_140827](https://user-images.githubusercontent.com/5811789/133886742-fdf9f0ed-8ed6-489e-bc3e-e641f23a262b.png)

**Comment by tuomas2** [comment]
And current StrongsGreek from Crosswire looks like this:

![Screenshot_20210918_141021](https://user-images.githubusercontent.com/5811789/133886788-8de9944f-f303-477f-8442-9ebec4cae4b6.png)

(it indeed is plain text in the module level)
