### ISSUE TITLE
Clicking the translation name takes me to the wrong translation

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1678]
I expected to go to the PEV translation but it took me to NASB.

![image](https://user-images.githubusercontent.com/13920678/132519444-07be7d9b-dd26-41f6-9730-d0338db4b8ac.png)

**Comment by bvahedy** [comment]
This was working in previous builds.

**Comment by timbze** [comment]
Issue might have been caused by #1521

**Comment by tuomas2** [comment]
> Issue might have been caused by #1521

Surely it is caused by this :-)

**Comment by agrogers** [comment]
Haha, that was my suggestion that bit me in the butt :)

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
