### ISSUE TITLE
Unusual padding / line size issues in notes which cuts of the bottom of the characters

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1679]
![image](https://user-images.githubusercontent.com/13920678/132519642-c821ac0f-8132-4934-b1d0-a3f9214d7022.png)

**Comment by tuomas2** [comment]
Was this done with the latest version? I have memory of fixing this issue few weeks ago.

**Comment by agrogers** [comment]
Hmm, good point. I haven't updated for a week or so. So it could be an old
issue. And it seems to be fine on the today's build. So let's assume it's
fixed.
