### ISSUE TITLE
NASB - How can I help?

### ISSUE THREAD

**Issue by elimtaft** [AndBible/and-bible#168]
I've cloned the repo and I've looked through it.  It seems like the list of available books comes from remote services like crosswire.  I read online in some very old posts (like, 2006 old) that Lockman have given permission but the files hadn't yet been made available or something.  Does anyone here know how I can help move this along?  It looks like it needs to be available on one of those remote services, but I'm not sure which.

**Comment by elimtaft** [comment]
I have read a bit more from Crosswire on how to add a Bible module to their SWORD project.  It looks like the list of Bibles available in my And Bible app currently matches the list available from here: https://www.crosswire.org/sword/modules/ModDisp.jsp?modType=Bibles.    So I'm guessing this will be more of a matter of contributing to Crosswire's SWORD project, as And Bible will be able to download any Bibles available there in the correct OSIS format.  Adding this comment in case others come along with the same question wanting to add additional Bible versions.  I read some very old posts on a forum, but back around 2006, where Lockman had granted permission to add NASB to the SWORD project, but it seems no one ever made the OSIS module.  I've just now requested permission from Lockman to do this, and also asked if they already have an OSIS format available.  I'll see what they say and go from there.

**Comment by tuomas2** [comment]
NASB was available through "Andbible Addons" (by Matt Zabojnik) commercially, but Matt discontinued his application, so currently it is not available. You are right, you should communicate with sword project / Crosswire directly about module contributions (see their mailing list http://www.crosswire.org/pipermail/sword-devel/). 

BTW OSIS is the original xml document format and it is converted to Sword module (binary format), which is used by And Bible as well as other Sword/JSword based applications.

Closing this ticket as there's nothing to do in And Bible side about this.
