### ISSUE TITLE
Window button colors

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1681]
If system is in dark mode and AB is manually set to light (or vice versa), window button colors tend to go wrong.  That is confusing.

![Screenshot_20210907-093902_Bible Study](https://user-images.githubusercontent.com/5811789/132578377-3aa305a2-b87a-418d-9078-c09bbebdcfb4.jpg)

**Comment by agrogers** [comment]
I did some work on this a few months back and had something that I quite liked - not sure that you would like it so i thought i would leave it for after this release. I didn't test it in night mode though so it may not have been good there.

My thoughts on that were here: https://github.com/AndBible/and-bible/issues/1092

**Comment by tuomas2** [comment]
Somehow the colors are just messed up here. I'm happy if we get them as they are supposed to look.
But I'm looking forward to see how your suggestion looks / feels like.

**Comment by tuomas2** [comment]
Both bottom & right side buttons are somehow weird on emulator

![Screenshot_20210909_130612](https://user-images.githubusercontent.com/5811789/132666773-0ddb235a-94a8-4e44-a030-5580d2fcddaf.png)

**Comment by tuomas2** [comment]
Fixed already
