### ISSUE TITLE
Some Hebrew words don't open dictionary in strongs underline mode

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1690]
**Describe the bug**
Reported here: https://support.andbible.org/scp/tickets.php?id=504

**Bug was found on And Bible version**
Build 601

**To Reproduce**
1. Disable "One verse per line"
2. Go to Job 1 in OSHB
3. Click the words on the left from verse numbers
Actual -> On most verses it selects the verse instead of opening the word in dictionary
Expected-> the word dictionary should open

**Comment by timbze** [comment]
Tapping any of the words to the left of 5 just selected the verse instead of opening the words in dictionary at bottom.

![image](https://user-images.githubusercontent.com/35117769/132764821-01898bc2-1ae8-4920-95c4-04fb7ffd756d.png)

**Comment by tuomas2** [comment]
Somehow text direction (ltr) messes up links. I'm not sure if this is actually Google Chrome issue... hmm.

**Comment by tuomas2** [comment]
Same issue happens if 1 verse per line is enabled BTW, but only on lines where there's verse number.

**Comment by tuomas2** [comment]
It does not reproduce if I disabling verse numbers completely!

**Comment by tuomas2** [comment]
=> Something weird with verse numbers

**Comment by tuomas2** [comment]
Their direction (dir) was opposite to their surrounding text and it messed up thing somehow. Kind of Chrome bug maybe but got it fixed by defining dir for verse numbers.

**Comment by agrogers** [comment]
Good job. Tricky problems!
