### ISSUE TITLE
Can not open apocrypha books (plus button missing)

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1695]
**Describe the bug**
Use KJVA and open book selector. The + button that used to be there is missing, i.e. can not find or open apocrypha books from the book chooser/selector

Maybe related to #1200, + button still shows for me in "Search results" window when searching KJV and I don't think it should.

**Bug was found on And Bible version**
Build 601

From [Play Store review](https://play.google.com/console/u/0/developers/6727655833913220393/app/4974350217168681006/user-feedback/review-details?reviewId=gp%3AAOqpTOE57h2isxv2qafuLm0QAJ0obor_dvA7EqaZG_buoIymWp4z12bn6DaUJ1JvqLKNgQ35ZZz59WmgPuc&corpus=PUBLIC_REVIEWS)

**Comment by tuomas2** [comment]
I accidentally removed the feature when cleaning up some old code. Now reimplemented...
