### ISSUE TITLE
Append 'Message' to the PEV translation. 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1697]
Can we append to the description of the PEV document 'This translation is similar to the Message Bible.'

That way when someone searches for Message they will get our entry that says it doesn't exist and the translation that we recommend as a replacement.

At present they need to go off and do another search to get our recommendation.

![IMG_20210912_151222.jpg](https://user-images.githubusercontent.com/13920678/132973073-4e752c20-0f3d-47ba-80f5-f35a347e2fd8.jpg)

**Comment by tuomas2** [comment]
Module conf needs to be changed, and that I can't do myself. You can ask eBible maintainer to do that.

**Comment by agrogers** [comment]
OK.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
