### ISSUE TITLE
Restore from backup does not work on Android P

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#170]
Looks like it does not work. Tested only with emulator.

**Comment by rik-shaw** [comment]
I am having this trouble with a new install of LineageOS 16 (Android 9, "Pie" based). When restoring, it gives an error saying "An error has occurred". Is there any more detailed log available? It could be that I am using a sd card formatted as internal storage. I could try by re-formatting as external storage and only using the internal storage.

I hope I can restore the bookmarks: it is years worth of effort I don't want to lose. I unfortunately did not do a full backup of the app folder, I only have the andbible_backup folder :-(

**Comment by tuomas2** [comment]
Created #461
