### ISSUE TITLE
Add more fonts request

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1700]
From https://support.andbible.org/scp/tickets.php?id=739

> I can see that there are few new fonts after downloading "FontPack" but I was hoping you guys could add more fonts like - Lora, Merriweather, Literata, Bitter, Roboto slab etc. Please add those fonts if possible.

**Comment by agrogers** [comment]
Yeah, i felt that it would be nice to have a few more font choices as well.

**Comment by tuomas2** [comment]
Task here is to create update to Fontpack add on module
