### ISSUE TITLE
Reference Copy Feature

### ISSUE THREAD

**Issue by Dleemuse** [AndBible/and-bible#1706]
I apologize if I have asked about this previously, is it possible when copying a verse(s) to have an option that only copies the reference. For example I would like to copy Acts 2:37-42 but don't want to copy the verses themselves, just "Acts 2-37-42." I don't know about others, but I often want to copy just the reference. 

Thanks, 

Debra

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by agrogers** [comment]
Hi Debra

Yes, you asked it here: https://github.com/AndBible/and-bible/issues/1387
I think it is a good idea. I am sure it will get added eventually.

Cheers
Andrew

**Comment by Dleemuse** [comment]
Thank you! 

Sent from Yahoo Mail on Android 
 
  On Mon, Sep 13, 2021 at 9:17 PM, Andrew ***@***.***> wrote:   


Closed #1706.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
