### ISSUE TITLE
Share bible passage should include verse numbers

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#171]
From user:

> When you copy and paste a passage, it no longer displays the verse number. It would be really great if you could add that.

* perhaps this should be optional (settings)

Implementation details:
 - Inherit class from OsisToCanonicalTextHandler, implement verse/chapter numbers there and use it instead when sharing/copying. 
 - Remember localisation (similarly as in speaking), i.e. string "chapter" should be in the same language as the bible text (not in interface language)

**Comment by tuomas2** [comment]
This is requested quite often, so increasing priority.

**Comment by tuomas2** [comment]
Will be fixed / implemented in build 308

**Comment by bvahedy** [comment]
Verified fix in 308beta.
