### ISSUE TITLE
Add this quote from a user to our promo material

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1711]
BTW, I LOVE Andbible. Best bible app out there. I have Logos and Olive Tree as well for a few copyright resources, but Andbible is my daily bible.

Jared Hood
OT Lecturer, Academic Dean: Presbyterian Theological College
Executive Editor: Reformed Theological Review

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=757

**Comment by tuomas2** [comment]
@BryceSteuer

**Comment by BryceSteuer** [comment]
Do you want me to add the quote to the webpage?

**Comment by tuomas2** [comment]
I think that was what @agrogers had in mind. Or what do you think @agrogers ?

**Comment by agrogers** [comment]
Yes, that would be great. It would be good to include some of his
credentials as well

**Comment by BryceSteuer** [comment]
Would some light editing to it be acceptable, producing this result:
**I LOVE AndBible. It is the best Bible app out there. I have Logos and Olive Tree as well for a few copyright resources, but Andbible is my daily Bible.
Jared Hood
OT Lecturer, Academic Dean: Presbyterian Theological College
Executive Editor: Reformed Theological Review**

Another concern is it might look a bit inconsistent to have one review with the reviewer's full name and status, while the others just have initials and "AndBible user"
I agree however that it would be an invaluable review to include

**Comment by agrogers** [comment]
Hi Bryce. Is it just the capitalisation that you added?

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by BryceSteuer** [comment]
I also removed "BTW" and included proper grammar in the beginning of the second sentence

**Comment by agrogers** [comment]
I am happy with the latter but I probably wouldn't capitalise anything.

**Comment by bvahedy** [comment]
I think we should quote the user as he wrote it without any editing. This way no one can claim that we doctored up any comments.

**Comment by timbze** [comment]
> I think we should quote the user as he wrote it without any editing. This way no one can claim that we doctored up any comments.

He offered that we could tidy it up in any way we want to. "LOVE" was capitalized by Jared. Maybe there's something else I'm missing, but I think Bryce did it right.

**Comment by bvahedy** [comment]
Ok, in that case Bryce did it correctly.

**Comment by BryceSteuer** [comment]
So the consensus is to post the review as is edited with credentials? My concern is it might look incongruent with the other semi-anonymous reviews. Should this review be placed at the top or something?

**Comment by agrogers** [comment]
Good point. Yeah, place it at the top and then we can have a look at it

**Comment by BryceSteuer** [comment]
![image](https://user-images.githubusercontent.com/48736452/138928263-4ddf7bbe-c34a-4512-a609-99dc7dd4734b.png)

**Comment by tuomas2** [comment]
perhaps could be also in a separate "feature" box somewhere else on the page. Just a thought.

**Comment by BryceSteuer** [comment]
Do we have permission to pull full reviewer's names from Google Play? (To replace the initials that exist now for consistency)

**Comment by tuomas2** [comment]
> Do we have permission to pull full reviewer's names from Google Play? (To replace the initials that exist now for consistency)

Those reviews are public so in that sense yes, BUT as user can also draw their review from Google Play any time, so I would not include full name here. Anonymous is better for those (can mention 5 star review in Google Play or something. Better add stars too :-))

**Comment by BryceSteuer** [comment]
What do you all think?
![image](https://user-images.githubusercontent.com/48736452/139476000-0584a435-19ab-49d2-9c91-56c4686edd1b.png)
https://brycesteuer.github.io/andbible.github.io/

**Comment by bvahedy** [comment]
I like this horizontal format better as it gives a better global view of the counters right up front.

**Comment by agrogers** [comment]
Looks good. Thanks!

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by BryceSteuer** [comment]
It does seem a bit partial, but I guess I have exhausted the other options. Unless someone else has anything? Or is it just me that it seems partial?

**Comment by bvahedy** [comment]
Don't feel bad, I feel the same way. Mainly because I don't think seminary education makes anyone smarter. In fact most seminaries believe in theistic evolution and teach it. Which in my view goes directly against the word is God.

**Comment by tuomas2** [comment]
@BryceSteuer btw just got an idea from my past project that might work here too. What about having a corner that has couple of random 5-star reviews? Meaning, we have a collection and it just shows lets say 3-5 reviews randomly on each pageload. It could be also on side bar or something, where we put those reviews. And yellow stars need to be there also drawing attention. :-)

**Comment by BryceSteuer** [comment]
@tuomas2 In addition to the review _section_ of the page, or in replacement of it? That does sound like a good idea. Of course though I think all the reviews live now are 5 star already, unless we want to diversify to include some four star reviews...
@bvahedy Agreed, but that about seminaries wasn't my main point of objection. My main point of objection is I don't think it's right to exalt one person's opinion above another's, especially when it looks inconsistent. I agree heartily with Tuomas that we should have some diversification, even though Mr Hood is reputable I'm sure and his argument holds weight.

**Comment by tuomas2** [comment]
i would include only 5 star reviews but underline that by showing the stars

**Comment by tuomas2** [comment]
maybe replacement

**Comment by BryceSteuer** [comment]
I will PR now (as there were a few other unrelated issues I fixed already), and then add your suggested changes to the PR within a few days if the Lord wills

**Comment by BryceSteuer** [comment]
![image](https://user-images.githubusercontent.com/48736452/139739695-61e314cd-5672-4a6f-8436-66c0f82a062c.png)
[Have a look](https://brycesteuer.github.io/andbible.github.io/) and give your feedback (the new code should be integrated to that link within an hour of my posting this)

EDIT: Forgot to mention, the sidebar is hidden on mobile devices because it runs against the bottom icon row on the footer. Maybe we can work out an alternative placement for the review section I just added?

**Comment by tuomas2** [comment]
[Have a look](https://brycesteuer.github.io/andbible.github.io/) and give your feedback (the new code should be integrated to that link within an hour of my posting this)
> 
> EDIT: Forgot to mention, the sidebar is hidden on mobile devices because it runs against the bottom icon row on the footer. Maybe we can work out an alternative placement for the review section I just added?

Looks great! What about having Jared's review as a "featured review" as first always, and perhaps even with a frame?
Perhaps could also remove 5 stars from that because it was not via Google Play, but via email.

**Comment by BryceSteuer** [comment]
@tuomas2 That sounds reasonable; I will try and see how it looks. Do you think we should
a) Leave the reviews in sidebar _and_ in "testimonials" section (this is the way it is now)
b) Replace "testimonials" section with the random reviews function, removing that function from its current place in the sidebar
c) Other (please specify)

**Comment by BryceSteuer** [comment]
![image](https://user-images.githubusercontent.com/48736452/139914805-8e98f828-c5a9-49b9-86ee-98584220d72a.png)
[Demo](https://brycesteuer.github.io/andbible.github.io/)
As time goes on and we get more featured reviews potentially, we can add those to each deck. For instance, if randomNum =1, then Jared Hall review is the featured. If randomNum =2, then John Macarthur's review is featured. That way it can diversify, rather than just giving one individual the spotlight

**Comment by agrogers** [comment]
Looking good.

**Comment by tuomas2** [comment]
- Looks good indeed. 
- There's something wrong wiht user reviews as is not displayed immediately for me. 
- I think testimonials section is not really needed (or at least it should be at the bottom of the page after description), but there could be another page for them maybe, or "more...." button at the end of random review list that will show more
- I would add mention of Google Play with stars: ***** (Google Play review) (small font perhaps)

**Comment by BryceSteuer** [comment]
![image](https://user-images.githubusercontent.com/48736452/140805326-40a6b923-f4f8-4203-8e5e-bb046df4cad4.png)

What I did:

- Fix loading time from ten seconds to about one point five
- Remove testimonials and replace it with the random review function
- Add (Google Play) to GP reviews
(Demo link is in my earlier comment)
One thing: to me the review text seemed a bit (too) large, is that just me?

**Comment by tuomas2** [comment]
Looks good. PR?
You didn't like it in sidebar?

**Comment by BryceSteuer** [comment]
I think it looks good in the sidebar, just at the moment thought it would be better that upon removing Testimonials section, it is replaced with this new section. Now that I think about it again, it would look just as good and make sense in the sidebar, so I will put it there and PR unless there are any objections or extra features desired

**Comment by BryceSteuer** [comment]
https://github.com/AndBible/andbible.github.io/pull/12

**Comment by tuomas2** [comment]
Left comments to PR.

**Comment by BryceSteuer** [comment]
I guess we can close this too...
