### ISSUE TITLE
Crash on startup (toast issue)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1720]
```
09-20 17:48:21.336   480   480 E AndroidRuntime: FATAL EXCEPTION: main
09-20 17:48:21.336   480   480 E AndroidRuntime: Process: net.bible.android.activity, PID: 480
09-20 17:48:21.336   480   480 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@b989874 is not valid; is your activity running?
09-20 17:48:21.336   480   480 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
09-20 17:48:21.336   480   480 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
09-20 17:48:21.336   480   480 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
09-20 17:48:21.336   480   480 E AndroidRuntime: 	at android.widget.Toast$TN.handleShow(Toast.java:459)
09-20 17:48:21.336   480   480 E AndroidRuntime: 	at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
09-20 17:48:21.336   480   480 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-20 17:48:21.336   480   480 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-20 17:48:21.336   480   480 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6130)
09-20 17:48:21.336   480   480 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-20 17:48:21.336   480   480 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-20 17:48:21.336   480   480 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
09-20 17:48:21.336   480   480 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

```

https://play.google.com/console/u/0/developers/6727655833913220393/app/4974350217168681006/vitals/crashes/1ce895b3/details?installedFrom=PLAY_STORE&days=30

https://support.andbible.org/scp/tickets.php?id=765

**Comment by tuomas2** [comment]
Caused by toast message somehow, I think.

**Comment by tuomas2** [comment]
@agrogers does this reproduce every time on your tablet?

**Comment by agrogers** [comment]
It did do it every time
But I installed the latest version and problem fixed!

**Comment by tuomas2** [comment]
604 is latest and your crash report was done with that?

**Comment by agrogers** [comment]
It's complicated :) Yes, the crash report was done with 604 I believe. But that was actually progress - before that update it wouldn't get into the app at all. 

But after that crash it has worked flawlessly. Maybe there was something in the first run after the upgrade that caused problems. Or perhaps just my old tablet was being silly. But all is well now.

**Comment by tuomas2** [comment]
Maybe the bug is a bit 'random' then. But I don't think anything was really 'fixing' the real issue. There are still same crashes happening in production with 604.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=769

**Comment by agrogers** [comment]
Right, we should try and eliminate those before we release more broadly.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Again
https://support.andbible.org/scp/tickets.php?id=770

**Comment by ildar** [comment]
the latest crash was cured by removing
`/data/data/net.bible.android.activity/shared_prefs/net.bible.android.activity_preferences.xml`.
That's probably tabs info in that file having incompatible values of
`width`.

**Comment by tuomas2** [comment]
I see. That's weird. There are not many values that are read from there any more (almost everything is read from database).

**Comment by tuomas2** [comment]
I believe this is from #1030

**Comment by timbze** [comment]
> I believe this is from #1030

I like the feature but it's not always consistent because the loading screen takes different lengths of time to show, and the toast starts showing while the loading screen is still up.

It would be nicest to show the toast once text is fully loaded, and in that case it would probably not cause a crash... But you could also disable it for now if you don't want to spend time doing that, not highly important feature I think
