### ISSUE TITLE
Gill self-refers incorrectly

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1721]
This seems like something that should be easy to do. I think clicking the link should somehow just open the Gill commentary at the specified verse in the link window.

At present we have to rechoose the document from the drop down list which is not bad but feels like an unnecessary step. 

Perhaps we could add a long press option to the open the reference in the current document type? 

![IMG_20210920_074135.jpg](https://user-images.githubusercontent.com/13920678/133943968-c815508d-07af-43d8-a482-6c31a1a81db1.jpg)

**Comment by tuomas2** [comment]
Does Gill link specify document in the link? If not, then iẗ́s module issue.

**Comment by bvahedy** [comment]
It has to be coded in the module in the link itself. It would not make
sense to programmatically look to see what commentary you are in then parse
the link and jump to that location.

**Comment by agrogers** [comment]
Yes, I am not saying there is a bug. Just saying that it doesnt work as one
would expect - if it says it should link to Gill then that is where it
probably should go. This is the case for all commentaries that refer to
itself I think. So none of them work the way one would expect.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
No, properly formatted module works as expected. Reference OSIS tag should be `<reference osisRef="gill:Gen.1.1">Gen 1:1</reference>`

**Comment by tuomas2** [comment]
Just tested with my ESV Study Bible module, and it works properly.

**Comment by agrogers** [comment]
Are there any references that are done correctly? I can't recall ever
clicking a link that takes me to the commentary and not to a Bible.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
I just know that ESV Study Bible and MacArthur Study Bible works. Neither of them are publicly available though (only via converter https://studybibles.evankelista.net/).

**Comment by agrogers** [comment]
Not sure that there is much that can be done about this so i shall close it.
