### ISSUE TITLE
Correctly configuring custom Hebrew/Greek fonts for 4.0?

### ISSUE THREAD

**Issue by dajare** [AndBible/and-bible#1725]
I use And.Bible regularly, especially the Greek NT and Hebrew "WLC" modules. For years (since at least 2016), I have set these up with the "jsword" properties, and until the recent upgrade to v. 4.0, this worked beautifully.

However, with this **major** upgrade (impressive!), my fonts have been lost. I have [read the FAQ][1], searched the issues, watched the videos . . . but it is *still* not clear to me how I get my Hebrew and Greek fonts back!

The FAQ instructs me to add certain configuration lines, but doesn't tell me where those go. Nor do the [Custom CSS][2] instructions. If someone would be kind enough to "hold my hand" to recover my fonts, I would be deeply grateful!

[2]: https://github.com/AndBible/and-bible/wiki/Custom-CSS-for-modules-for-And-Bible
[1]: https://github.com/AndBible/and-bible/wiki/Custom-font-modules

**Comment by tuomas2** [comment]
There are 2 good fonts for hebrew / greek in FontPack which can be found from Download Documents / add-ons; their names are SBL Hebrew and SBL Greek. You can set up those fonts for the windows that you are using for hebrew  / greek documents. That's the easiest way without any 'hacking'. Does this suffice for you?

**Comment by tuomas2** [comment]
And Custom CSS should allow doing "anything", if this is not enough. But not going there yet.

**Comment by dajare** [comment]
> There are 2 good fonts for hebrew / greek in FontPack which can be found from Download Documents / add-ons; their names are SBL Hebrew and SBL Greek. You can set up those fonts for the windows that you are using for hebrew / greek documents. That's the easiest way without any 'hacking'. Does this suffice for you?

Thank you for the swift reply!

Yes, that is some help. The SBL Hebrew/Greek fonts were, in fact, the ones I have used for years. I now have them available via the Download/add-on. :)

But :/ Now I'm trying to work out how to assign them on a per-module basis (as I used to do with v.3.3). SBL Hebrew I need at around 26pt, but that's FAR too large when I switch back to my English Bible ... and that's before getting to GNT!

If you have a pointer for me on the "per module" (which is **not**, as I understand it, the same as a "window" setting), that would be a huge help. Perhaps this gets us towards the Custom CSS in the end...

Thanks again!

**Comment by tuomas2** [comment]
That is possible with Custom CSS module that you need to make and install on the device. Can you try again to follow https://github.com/AndBible/and-bible/wiki/Custom-CSS-for-modules-for-And-Bible, and then please specify what you can't understand from there? I can try to improve documentation when I have opportunity.

**Comment by dajare** [comment]
> ... Can you try again to follow https://github.com/AndBible/and-bible/wiki/Custom-CSS-for-modules-for-And-Bible, and then please specify what you can't understand from there? I can try to improve documentation when I have opportunity.

What I cannot work out is where to find the "config file" as referenced in this:

> Place your CSS file under module directory (or subdirectory), and define CSS file path in **config file**...

I'm using my file manager to search, but cannot find a good candidate. Here's a screen shot of one path/directory I've followed, which seems to have my old `xxx.conf` files in it:

![WhatsApp Image 2021-09-20 at 19 52 21](https://user-images.githubusercontent.com/40625/134058356-787e6ef0-2957-4e85-bb2e-8067bc33e2df.jpeg)

You can see the new (!) "FontPack.conf" setting there, too, so it seems to be used by 4.0...

This is my confusion, anyway! Thanks for the help - perhaps it will help others, too!

**Comment by tuomas2** [comment]
I don't have much time right now but quickly.... the idea is that you build your own module zip file and load it via main menu -> backup & restore > load document from zip. See example from StyleExample.zip (download it from https://github.com/AndBible/data/tree/master/andbible/beta/zip)
and try to apply info in https://github.com/AndBible/and-bible/wiki/Custom-CSS-for-modules-for-And-Bible.

**Comment by dajare** [comment]
> I don't have much time right now but quickly.... 

Thanks for the extra explanation and samples. I'll try that in the next day or two (also busy! 😬) and will let you know how it goes! 👍

**Comment by dajare** [comment]
Well ... I'm admitting defeat. I found an APK for 3.3.400 ... and now I can't even convince it to install (I'm on Android 9.0). Very sad for me; it feels like "customization" shouldn't be this difficult! And after all the work you've invested, @tuomas2 — you would want happier users! 🤷‍♂️ 

(It wasn't easy to find that APK, by the way! There are SO MANY tags/releases, sometimes a few in a single day, that I resorted to an off-site source, found via websearch.)

So — after quite a long time trying ... I'm stuck. If you have any advice, please do tell me! Thanks.

**Comment by dajare** [comment]
And I just saw  #1742 - so maybe this is on your radar already!

**Comment by tuomas2** [comment]
customization is meant for hackers only. but I'll make you the module you need when I have time. maybe next Thursday.

**Comment by dajare** [comment]
Thanks - I feel a bit lame. Normally I can fix things like this, even if I'm no hacker! Grateful for your help.

**Comment by bvahedy** [comment]
David, please don't admit defeat. I use the SBL font and am able to change the font size without any hacks in the new version.  (See screenshot) 
Note: this is the WLC module:

![Screenshot_20211002-092357_Bible Study](https://user-images.githubusercontent.com/46405809/135724874-b5196711-715e-47dd-85ab-6a2958629b07.jpg)
![Screenshot_20211002-092420_Bible Study](https://user-images.githubusercontent.com/46405809/135724886-f6a0642c-f29a-4f6e-bc6b-779c04e1a5ee.jpg)

**Comment by bvahedy** [comment]
You should change the font size for the window not the workspace. You don't need to do custom css. Just tap and hold on the WLC window icon at the bottom of the screen and select all text options then font size.

**Comment by dajare** [comment]
@bvahedy - Thanks for the encouragement Ben! I'm seeing this late, and will follow-up in the morning. That looks great! Hopefully we can save @tuomas2 some hassles. 😉 Will update in the next day or so.

**Comment by timbze** [comment]
Just to try to clarify. If I understand correctly, I think Ben is talking about changing a window font size, but David is talking about changing the module font size so that it will always have a different size regardless of which window it gets loaded. If I'm right about what David means that will require a custom module like Tuomas said

**Comment by bvahedy** [comment]
@dajare If what @timbze says is true then you can use this zip file to load over your existing WLC module. You can play with font size and other attributes in the style.css file.
[WLC-with-fonts.zip](https://github.com/AndBible/and-bible/files/7272294/WLC-with-fonts.zip)

**Comment by bvahedy** [comment]
@dajare Also be aware that if you put the font style in the module you will not be able to change it to a different font family in the AndBible app. Something to think about before going that route.

**Comment by dajare** [comment]
Thanks, all! My take-aways:

1. Getting to know the new features is a help: judicious use of **windows** in 4.0 pretty much (now!) gets me where I want to be.
2. It still strikes me that setting **per-module** features shouldn't be *harder* than it was in 3.3, but it seems that it is.
3. Having original language modules with "baked-in" fonts is an *excellent* idea (IMO). NO Hebraist I know wants to see the accented Tanakh in Arial (or equivalent), and there are better options for Greek, too, than the "defaults". My own suggestions would be:
    - **Hebrew**: [SBL Hebrew][1] as first choice, with [Taamey Frank][2] as alternate;
    - **Greek**: [SBL Greek][3] as first choice, with [Gentium Plus][4] as alternate.
 
Thanks for all the help and encouragement here! 

[1]: https://www.sbl-site.org/educational/BiblicalFonts_SBLHebrew.aspx
[2]: http://culmus.sourceforge.net/taamim/#TaameyFrankCLM
[3]: https://www.sbl-site.org/educational/BiblicalFonts_SBLGreek.aspx
[4]: https://software.sil.org/gentium/

**Comment by agrogers** [comment]
Thanks for the feedback David. I can't read any other languages so the fonts are more a gimmick for me :)  So I don't have any comments there. I will leave the others to decide on the best path forward there.

Re point 2, I must have missed the correspondence about setting per-module features. I didn't think anything in that regard had really changed. Can you help me understand that?

Re including what is needed with the module, I agree with that in principle. I think the next step for And Bible is to try and get an installation process that manages to install everything that is required for the users particular bent. Other apps can do so little or have access to so few modules that they can install 'everything' with the app. We can't do that so we have left that up to the user to choose. That's has created headaches for more than a few based on both my personal experiences with new users and reading past comments in the Play Stores and elsewhere. I would like to do some work on that for the next release.

**Comment by bvahedy** [comment]
Thanks David. BTW I don't know if you were aware that we already have HiSB module with SBL font embedded within it for download from the repository. Try installing that module, I thick you will be very happy with that.

**Comment by tuomas2** [comment]
I'm planning to add some css classes for module languages (like .lang-he and .lang-gk). Then based on that, we can use SBL fonts automatically for all hebrew & greek modules when FontPack is installed. Does it make sense?

**Comment by tuomas2** [comment]
> I'm planning to add some css classes for module languages (like .lang-he and .lang-gk). 

Hmm actually language is already there, so this is not needed.

**Comment by tuomas2** [comment]
I made adjustments to FontPack module. Now installing FontPack is enough to get SBL Hebrew & SBL Greek fonts (with 120% font size adjustment) for modules in hebrew or greek languages. 

Also made repository for special modules and their configs. There you can see example when creating your own mods. https://github.com/AndBible/special-modules

**Comment by tuomas2** [comment]
Let me know if this works out for you or if we need more adjustments ... 

#1742

**Comment by dajare** [comment]
> Let me know if this works out for you or if we need more adjustments ...

Hi @tuomas2 - It works _almost_ great! 😉 It certainly is usable "out of the box" ... but:

- SBL Greek really does *not* need any font scaling: its x-height is already == to that of the "latin" font. But
- SBL Hebrew could use a bit more (128% ... 130%?) to be comfortable, although +120% is a real improvement over what you get with 100% (very, _very_ tiny dots and squiggles).

So thanks for your attention to this! If you were inclined to make the adjustments to the font pack based on these comments, I reckon it would be a perfect solution.

Greatly appreciated!

**Comment by bvahedy** [comment]
David, are you using a tablet or a phone?
Because on my phone everything looks good.

**Comment by dajare** [comment]
> David, are you using a tablet or a phone? Because on my phone everything looks good.

@bvahedy - Phone (a Nokia S3, I think it is!). I tried to do a screenshot so you can see what I see. Note the Greek slightly larger than the "Latin" text (SBL), and that the Hebrew could stand to be bumped up a couple ticks. ;) For my eyes, that is! It is **certainly** usable as-is, and a real improvement on what I had when this thread began!

(That looks HUGE, though, so they all look fine!! My screen is 6.2 cm x 11.0 cm)

![Screenshot_20211008-174937](https://user-images.githubusercontent.com/40625/136594543-80c7f5d0-69d9-4944-891b-910da162e44c.png)

**Comment by bvahedy** [comment]
I read Hebrew and the vowels and consonants seem a good size, any larger then you would reduce the amount of words on the window. I don't read  Greek, but size wise it's similar but I wouldn't compare it to the Hebrew. As you said it is fairly readable.

**Comment by tuomas2** [comment]
Adjusted font sizes (version 1.6) as you suggested @dajare

**Comment by dajare** [comment]
> Adjusted font sizes (version 1.6) as you suggested @dajare

Pefection! 😄 👍 Thanks so much for persevering with this, @tuomas2 - that's a great solution.
