### ISSUE TITLE
Loading document from zip does not refresh Bible list... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1733]
After a fresh install when loading document from zip the bible list in the menu bar does not show the name of installed Bible. After closing the app and reopening it, the list is updated.

Expected result:
After a successful install from zip, update the list so the new Bible module can be viewed without the need to restart Andbible.

**Comment by timbze** [comment]
For reference, may be related to:
- #1505
- #91
- #1646
