### ISSUE TITLE
After adding a Bible ref to a Note the ok button should be on the right side... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1738]
For consistency and compliance with other apps the ok/cancel buttons should match through out the app. The ok button is usually on the right side and the cancel on the left side.
The affirmative action is usually on the right side. For example When deleting a bookmark we ask to confirm yes on the right side which is correctly positioned in AB.

**Comment by agrogers** [comment]
Yes, it should be consistent, I agree.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
