### ISSUE TITLE
Make FontPack to to adjust font size when using SBL fonts

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1742]
Probably doably by some CSS.

https://support.andbible.org/scp/tickets.php?id=779

**Comment by tuomas2** [comment]
is it reasonable to force SBL fonts to hebrew & greek languages with some adjusted font sizes? 

This means that if FontPack is installed, font customizing would not take effect in hebrew / greek modules.

**Comment by bvahedy** [comment]
We don't want to hard code that in, users should be able to change the font
size even if we force it. Or maybe I'm misunderstanding the question.

**Comment by tuomas2** [comment]
It takes effect only in Hebrew and Greek modules. Those are the only ones that require 'special font' as far as I understand. All other modules users can choose fonts. I'd say, let's see what users like and revert if we get complaints.

**Comment by tuomas2** [comment]
Created new repository for special modules that we maintain https://github.com/AndBible/special-modules

**Comment by bvahedy** [comment]
ok, let's see how it works out. But I do use the ALEPO Hebrew module and I don't have SBL font assigned to that. I don't think it should over write any Hebrew module.

**Comment by tuomas2** [comment]
Hmm. Then we need to create another special module that does only this (and nothing else).

**Comment by bvahedy** [comment]
Ok thx, will check it out and let you know.

**Comment by bvahedy** [comment]
The font loads correctly with a larger font size, but the font family name doesn't display the correct name.
![Screenshot_20211007-094235_Bible Study](https://user-images.githubusercontent.com/46405809/136428123-533d1282-a262-4c36-9dbc-03be878173a2.jpg)

**Comment by tuomas2** [comment]
CSS-manipulating addons are by nature overriding the default settings in webview side. They are kind of 'hacks' by nature. 
I think it is more about being debatable if we should provide officially css hacks in FontPack etc. But now it works as expected.
