### ISSUE TITLE
I must have a way to prevent an automatic upgrade from 3.3 to 4.0

### ISSUE THREAD

**Issue by joshuad31** [AndBible/and-bible#1745]
Hello,

It took HOURS to restore my bible this morning. I cannot have this happen ever again. I NEVER want to upgrade. I must turn upgrades off completely. Please tell me how to prevent upgrades from happening.

Thanks

Joshua

**Comment by timbze** [comment]
This is controlled by Google Play. You can disable auto-update for all apps, or just for AB specifically. See this image:
![image](https://user-images.githubusercontent.com/35117769/134390919-10eb47ae-a4f6-4f1d-b4de-ab75c4d4bfd1.png)

**Comment by joshuad31** [comment]
@timbze thanks! super helpful. I fixed my review on google play.

**Comment by timbze** [comment]
> @timbze thanks! super helpful. I fixed my review on google play.

Thank you. We hope to get the issue fixed soon, in case you'd like to try out the cool new features in the future.

Here's a YouTube playlist with the new features: https://www.youtube.com/watch?v=f2cf6-7liMo&list=PLD-W_Iw-N2MlOXgRTLQqoXZpQxkqf119a
