### ISSUE TITLE
linebreaks are lost in the migrated 'my notes' after upgrading from 3.3 to 4.0

### ISSUE THREAD

**Issue by uniqueid001** [AndBible/and-bible#1748]
**Describe the bug**
In v3.3 I created several "My Notes" with linebreaks in the text for visual formatting.  When I upgraded to v4.0, these "Migrated My Notes" are displayed without the linebreaks.  (perhaps the newline character is still present, but has no visual effect if it is now interpreted as HTML)

**Bug was found on And Bible version**
Version 4.0, when upgraded from 3.3

**To Reproduce**
1. Install v3.3
2. Create some notes containing line breaks
3. Upgrade to v4.0
4. Open the Migrated My Notes

**Expected behavior**
Linebreaks in the old plain-text data representation should be converted to linebreaks in the new rich-text data representation

**Screenshots**
Here is one example.  This was a plain-text bulleted list, but now looks like one run-on sentence.
![Screenshot_20210922-221207-380](https://user-images.githubusercontent.com/12715614/134445482-0c0dcbe9-001f-49f8-aeda-d82dec8ac061.png)

**Comment by agrogers** [comment]
Also "The notes imported from the previous AND version did not migrate with paragraphs, spacing, Caps, but just the lower case content." From: https://support.andbible.org/scp/tickets.php?id=782

**Comment by tuomas2** [comment]
I'd propose we will implement a "fix" migration that will go through all "Migrated My Notes" and add `<br>` tags, unless it finds html in notes.

**Comment by uniqueid001** [comment]
> I'd propose we will implement a "fix" migration that will go through all "Migrated My Notes" and add `<br>` tags, unless it finds html in notes.

That sounds like a good plan.

**Comment by tuomas2** [comment]
Must to do the data migration to *all* notes, because we have not any way to figure out label id for the "migrated my notes" label. Also name is translated and may have been renamed too, so can't use that either.

**Comment by tuomas2** [comment]
As far as I know from what I tested, editor does not produce any `\n`'s so I'll do just simple search & replace.

**Comment by agrogers** [comment]
Great
