### ISSUE TITLE
"Share" option for database backup might not make sense

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1753]
"Storage" option also allows storing db in Google Drive etc. But Share allows sending db with email. Is it necessary? Should we just show the dialog that comes with "Storage"?

**Comment by timbze** [comment]
The "storage" and "share" are a bit confusing, but I usually use the share because I like to save the db in my Telegram "Saved Messages"

**Comment by agrogers** [comment]
Hmm, we can get to the file system from the Share option can't we? So yes, definitely don't need both. I would like to make a few changes to that form but didn't do much because our Strings were fixed.

**Comment by bvahedy** [comment]
I think we need both, I can't access the file system from the share option
only cloud drive, email, and some other app options.
