### ISSUE TITLE
Toolbar goes completely white on certain devices

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1756]
Original ticket: #1744

**Describe the bug**
header menu has completely disappeared

**Bug was found on And Bible version**
The newest build I just upgraded to this morning... I can't get into settings so I cant tell you what build this is but its the latest

**To Reproduce**
1. Open up and bible and immediately menus are gone

**Expected behavior**
Top menu bar should be visible

**Screenshots**
![Screenshot_20210922-101317_Bible Study](https://user-images.githubusercontent.com/5976059/134371449-03ea05aa-bf65-45a5-8afe-45992c8bca3b.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Note 8
 - OS: Android
 - Version 8.0.0

**Comment by tuomas2** [comment]
I have tried to resolve this today. Some discussion about this on #1744 (though it's getting flooded by off-topic discussion).

If some other developer team member (@AndBible/developers) or contributor (@AndBible/contributors)
has time to try to fight this bug, please go ahead. At least this is pretty much something that you don't need to know much about And Bible source code to be able to help with this. Android experience might be more valuable here.

I won't have much time for this in the upcoming days. Most likely I can return to this issue on thursday 30th september.

Prayers are welcome too.

**Comment by tuomas2** [comment]
sometimes also first window goes white/black like this


![Screenshot_20210922-103611_Bible Study](https://user-images.githubusercontent.com/5976059/134375284-82116da4-2542-4b02-9a47-7e32694c532b.jpg)

**Comment by bvahedy** [comment]
Could this and the blank toolbar be related to  webview software update or lack thereof?

**Comment by tuomas2** [comment]
No, it looks like webview is functioning properly, as we can see in the screenshots. But it's good idea to take a look at logcat if there are some extra cues.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=799

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=784

**Comment by tuomas2** [comment]
Dunno but could be related https://stackoverflow.com/questions/36921623/android-navigation-drawer-toolbar-is-missing

**Comment by tuomas2** [comment]
Another incident: https://support.andbible.org/scp/tickets.php?id=806 (Androi 8.1.0, LGE phone)

**Comment by uniqueid001** [comment]
The common characteristic of these reports seems to be Android 8.

For reference, my previous description of my observations is here: https://github.com/AndBible/and-bible/issues/1744#issuecomment-925093732

I recorded a video this morning demonstrating the (re)paint artifacts that I see.  I think the cause may be identified by profiling what is causing the views to repaint.  I'm not sure how to do that, at this moment, and it appears that the documentation is focused more on the capabilities added in Android 9 and 10+.

https://user-images.githubusercontent.com/12715614/134757182-731e6ce3-5588-40b3-9019-75330bb9a1a5.mp4

**Comment by tuomas2** [comment]
Good news: My friend has a tablet that has Android 8.1 and can reproduce this. Will borrow it next week. Helps debugging :-)

**Comment by agrogers** [comment]
Wonderful!

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=816

**Comment by timbze** [comment]
I found some info: TLDR webview is the problem.

I remembered that I have an LG G6 Android 8 that I'm not using, and started AB to see if the issue was there.
- It was on 3.4.516, no issue
- I upgraded to latest 4.0.607.1, still no issue

I did a bug report to see what differences I had with others that had the issue, my webview version was on 85.0.4183.81

So I tried upgrading my webview only to find that it's disabled and there's no way to enable it. Found out this specific version (either Android or this specific phone) ONLY uses Google Chrome webview.

So I updated Google Chrome, and boom, first startup of AB and I had exact same issue, webview version 93.0.4577.82

**Comment by timbze** [comment]
Possibly related: https://stackoverflow.com/questions/48092312/web-view-desnt-load-on-oreo

**Comment by tuomas2** [comment]
Found that this works as a workaround. 

https://stackoverflow.com/questions/12806094/android-webview-flicker-bug-while-animating-view-on-device/16187551

Could affect webview performance as it disables hardware acceleration.

**Comment by tuomas2** [comment]
It feels that we can go with this workaround for now. Webview hardware acceleration is not any bottleneck for us, as our UI is pretty lightweight.

Side effects on Android 8 and 8.1:

- Smooth scrolling might not as smooth always.

**Comment by tuomas2** [comment]
It is possible to find better solution, but I guess better to publish with this for now. 
I can try to find better solution when I have more time.

**Comment by tuomas2** [comment]
Fixed by 87aa2d6

Created #1765 for improving performance on affected devices.

**Comment by timbze** [comment]
Confirmed it's fixed now

**Comment by agrogers** [comment]
That's great. Well done everyone

**Comment by tuomas2** [comment]
Also, most importantly, Praise God for answered prayer on this!

**Comment by uniqueid001** [comment]
I can confirm that this issue is resolved on my device, too.

**Comment by bvahedy** [comment]
I had a feeling it was a spiritual issue, almost everything is😁, we praise
him for giving us the knowledge and the ability to figure this out.

**Comment by timbze** [comment]
Submitted a Chrome feedback report about the issue, will see if anything comes from it. Tested on Chrome Canary where the issue still exists.

**Comment by tuomas2** [comment]
I wonder if you should report (also) to chromium issues: https://www.chromium.org/issue-tracking ?

**Comment by timbze** [comment]
Might help more, let me try

**Comment by timbze** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1265269

**Comment by timbze** [comment]
> https://bugs.chromium.org/p/chromium/issues/detail?id=1265269

If everyone could go star the issue that would be great

**Comment by tuomas2** [comment]
They asked some more details so I gave some.

**Comment by tuomas2** [comment]
Can someone check if issue still reproduces with the latest Chrome installed on Anroid 8 and version https://github.com/AndBible/and-bible/releases/tag/beta-607.1 (please comment on #1765 instead of this ticket)
