### ISSUE TITLE
AB shows error dialog loading something else than zip file (from repository)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#176]
From user
 
> Exception:
> java.util.zip.ZipException: archive is not a ZIP archive
> at org.apache.commons.compress.archivers.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(ZipFile.java:871)
> at org.apache.commons.compress.archivers.zip.ZipFile.positionAtCentralDirectory(ZipFile.java:801)
> at org.apache.commons.compress.archivers.zip.ZipFile.populateFromCentralDirectory(ZipFile.java:542)
> at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:217)
> at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:193)
> at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:154)
> at org.crosswire.common.util.IOUtil.unpackZip(IOUtil.java:84)
> at org.crosswire.jsword.book.install.sword.AbstractSwordInstaller.install(AbstractSwordInstaller.java:254)
> at net.bible.service.download.DownloadManager.installBook(DownloadManager.java:135)
> at net.bible.service.download.RepoBase.downloadDocument(RepoBase.java:46)
> at net.bible.android.control.download.DownloadQueue$1.run(DownloadQueue.java:54)
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
> at java.lang.Thread.run(Thread.java:764)

**Comment by tuomas2** [comment]
I think this is caused by some network problem.

**Comment by timbze** [comment]
Has been improved in 3.3, see #527
