### ISSUE TITLE
Restoring database was unsuccessful. Perhaps you gave invalid database file

### ISSUE THREAD

**Issue by joshuad31** [AndBible/and-bible#1761]
I was one of the users that was negatively impacted by the 4.0 upgrade. Previously I was able to downgrade back to 3.3 and I was able to save and restore my bookmarks. I only attempted to upgrade back to 4.0 at the request of @tuomas2. When the time came to go back to 3.3 I attempted to follow the same exact steps but I can no longer restore my previous bookmark files.

Here is the file that I used to backup my bookmarks:
https://drive.google.com/file/d/1UbchrUKzXmx3cpjz_8ePzTK0rXcxqwfW/view?usp=sharing

After I install and bible 3.3 from this link:
https://github.com/AndBible/and-bible/releases/tag/production-400

and then I select "backup & restore" from within the app and then select
and-bible.apk

I get the error:
Restoring database was unsuccessful. Perhaps you gave invalid database file
![Screenshot_20210924-224018_Bible Study](https://user-images.githubusercontent.com/5976059/134756794-4b1f262e-7235-4be7-b838-8a2dc9ee3813.jpg)

Why is the database file invaid? It worked previously. I'm not sure what I'm doing wrong as I believe I am following the same steps I previously took...

If I lose those bookmarks I'm losing several years worth of notes and insights I rely on every day.

I've said this several times and I still cannot escape the fact that something is being taken away from users. This does not seem right. How can the backup and restore process be this fragile.

If I knew that the and bible app and my data on the app were this fragile I never would have used this app to store my data. If I can't get my bookmarks back I have no choice but to rate this app with 1 star. The app's developers have not taken adequate measures to assist users to guard against data loss. Along with a complicated and error-prone backup and restore feature user data is lost.

Several of you have mentioned that you are unwilling to take any steps to avoid a negative upgrade experience. I have one question, why would you be unwilling to automatically back up the users data prior to upgrading the user from 3.3 to 4.0? Why do you expect the user to be able to navigate this process with the negative outcome that the user loses their own data?

Do you really want to blame your users and say that this is their fault when you make backup and restore so difficult?

This has been a terrible experience. I want my data back.

**Comment by agrogers** [comment]
Hi Josuha

The data is automatically backed up. So I am confident that your notes are safe even if you can't see them. As to why it is failing for you, perhaps it is the same reason that you had the initial issue - a very weird issue with your particular device and version of Android. I suspect if you tried both the latest version of the app and your backup file on  a different device both would work fine.

The backup option has been available for a long time. If you have spent so many hours making notes I am a little surprised that you failed to make a backup yourself. I try to do that on a semi regular basis. Blaming us for your failure to take basic precautions seems unfair.

Your attitude is really starting to annoy me. The developers (I am **not** one of them) could have said to you 'We have 20,000 users who have upgraded without this issue - we are not going to waste our very limited time trying to fix a problem that effects just a couple of people."  

But instead they have spent hours trying to fix **your** specific problem. Your threat of giving a 1 star rating is the height of ingratitude. You have been benefiting from a FREE app for years. I am sure our developers have put many more hours into the app than you have spent writing your notes. So my recommendation to the developers would be to ignore this issue, let him lose his notes, and move on to more important things. 

However, and fortunately for you, the devs are much nicer people than me and are unlikely do that. I am confident that they will either fix the problem or get your notes back or both. But if you keep badgering them like you have been with long messages lamenting how terrible your life now is, maybe they will listen to me. Then they could keep making a great app for people who do appreciate it and who really do have a terrible life - like my friends who live in Myanmar and are dying from COVID and suffering under a military dictatorship.

I think it might be time for you to reflect a little and get some perspective... and gratitude. 

`2 Timothy 3:1-3  But understand this, that in the last days there will come times of difficulty. For people will be lovers of self, lovers of money, proud, arrogant, abusive, disobedient to their parents, **ungrateful**, `

Don't be that person, Joshua.  And please, give the devs some time to find a solution. Remember, they do all this work in their spare time.

**Comment by tuomas2** [comment]
If we deserve 1 star I'm okay with that.

**Comment by joshuad31** [comment]
@agrogers @tuomas2 Good design will always be centered on putting guardrails in place that prevent users from self-inflicted wounds. Nothing that has been said will ever change that. You should never insist that your users be as technically proficient with an app as you are. You should always design for users who are of average proficiency.

The question remains, does this app allow users to destroy what is of value to them? If the answer is no then it represents good design. If the answer is maybe or yes then perhaps the users have failed to realize that what is valuable to them is not valuable to the developers. Should the users receive a warning if there is not an alignment between them and the creators of the app in which they store their data? Specifically, the developers in this case value newer models of phones. What percentage of users prefer to buy a new phone every three years to comply with software updates? If you want to blame the users for something then you can blame them for valuing something different than the developers. Or blame them for being naive to think that the developers value what they value.

And if you want to attack me with bible verses then that is definitely not the same spirit that the Lord had in these verses:

Matt. 9:36 Seeing the people, He felt compassion for them, because they were distressed and dispirited like sheep without a shepherd.

Matt. 18:12 “What do you think? If a man owns a hundred sheep, and one of them wanders away, will he not leave the ninety-nine on the hills and go to look for the one that wandered off? 
13 And if he finds it, truly I tell you, he is happier about that one sheep than about the ninety-nine that did not wander off. 
14 In the same way your Father in heaven is not willing that any of these little ones should perish.

**Comment by bvahedy** [comment]
@joshuad31,
The developers are not responsible for the mis-actions of the users of the app. I mentioned to you before you volunteered to help the developer to troubleshoot this bug to save your bookmark files and all associated files for the original version and you said your file structure are all messed up on your device. I even suggested a file manager for you to use. And as @agrogers mentioned also that the backing up of your notes and bookmarks throughout all these years was something you should have done already. How is that the developers responsibility.
Also, your Bible quotes are all out of context. I don't know the state of your spiritual journey, but one thing is for sure, you should never use a tool someone gave you to help you for free to turn around and beat him with it. That is what you are doing. If this app is too complicated for your needs then by all means find another that suits you.
These developers have given many years of themselves and of their family time to get to this point, what have you done, 30 minutes of your time trying to "help" figure out "your"  issues. And you were greatly pissed that you wasted 30 min. That's not the right attitude. I suggest more reading of the bible and less note taking and bookmarking, for if we just read without understanding it gains us nothing. I do not intend to say this to be mean but your words and actions are not inline with someone who has a personal relationship with his creator and fellow man. I have said my peace as you have and I'll let it be now. I wish you well on your journey!

Note: if the developer(s) of this app knew I would write these words he would rebuke me for saying it, because he is a kind and a godly man and cares very much about all the users of this app.

**Comment by timbze** [comment]
Maybe you figured it out by now, but the database backup has a .db extension, not .apk. According to the original post it seems you tried restoring a apk file.
