### ISSUE TITLE
Custom color not applied

### ISSUE THREAD

**Issue by dbell154** [AndBible/and-bible#1763]
**Describe the bug**
And Bible doesn't immediately apply background color after setting a custom color.

**Bug was found on And Bible version**
Version 4.0.605

**To Reproduce**
1. With window open
2. Select window text options
3. Select color Settings
4. Tap on Background color swatch to change
5. Select Custom
6. Select Color
7. Select
8. Go back and see swatch has changed
9. (bug) Go back to display and see that the change has not been changed

Note: If you then select text options, color settings, and go back without making changes the custom color is then applied.

**Expected behavior**
Custom color should update window just like preset color selections

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: Android
 - Version 8.0

**Additional context**
Custom "Text color" changes do seem to work okay.

**Comment by agrogers** [comment]
I believe I have seen this happen too.

**Comment by tuomas2** [comment]
Can't reproduce (tried on emulator with API 29)

**Comment by dbell154** [comment]
Strange. It was doing that every time. Now it doesn't happen on mine either other than a short delay sometimes before new color is applied.
