### ISSUE TITLE
Webview upgrade procedure on Amazon devices?

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1766]
We did not yet release to Amazon devices, but new And Bible requires recent webview (at least version 83). In order to help users, we need to know how to upgrade WebView on Amazon devices. Does anyone have any information?

https://support.andbible.org/scp/tickets.php?id=824

**Comment by timbze** [comment]
When we were dealing with #1139 I tried updating webview but all I found is that it's tied directly to Amazon's software and can only update through a system update.

**Comment by timbze** [comment]
Though I could recheck in developer options if the webview could change to use Google Chrome instead of the Amazon one (I doubt it). I can do that later when I'm home.

**Comment by tuomas2** [comment]
I wonder if that ruins our possibility to support Amazon devices...

maybe including gecko webview in amazon...

**Comment by tuomas2** [comment]
Or would it be possible to bundle webview to apk in amazon devices? Or even better, distribute it as a plugin module...

**Comment by tuomas2** [comment]
Second question is if Huawei distributes up-to-date WebView in their store (in devices that do not have Play). 
Also Samsung, if user has chosen not to use Play (is it possible?).

**Comment by tuomas2** [comment]
Another option: try to get it working with old browsers.. https://cli.vuejs.org/guide/browser-compatibility.html#browserslist

**Comment by timbze** [comment]
I would think Huawei and Samsung would be more up-to-date with webview since they use later versions of Android. Kindle is still on Android 5. Though my Kindle has webview 84 and does work with AB

**Comment by tuomas2** [comment]
https://en.wikipedia.org/wiki/Fire_OS shows that there are different versions (based on android 5.1, 7.1.2 and 9)

**Comment by tuomas2** [comment]
It's surprising if amazon does not keep their webview up to date.

**Comment by timbze** [comment]
> It's surprising if amazon does not keep their webview up to date.

I guess it could be quite old device. Mine is fire HD 10, I think 7th Gen

**Comment by tuomas2** [comment]
> > It's surprising if amazon does not keep their webview up to date.
> 
> I guess it could be quite old device. Mine is fire HD 10, I think 7th Gen

But I would guess they will keep it up to date like Google does their version for Play users. Android 5 devices in general still get latest webview.

**Comment by timbze** [comment]
Maybe you could check with user if he can update the device? It's quite likely that updates have been disabled if he used third party software to install Play Store. Software I've seen does that so that mods will not be cancelled with an update.

**Comment by tuomas2** [comment]
You can take over that ticket (assingn to yourself) and ask more info. You know more about these devices anyway :-)

**Comment by tuomas2** [comment]
Related https://amazon.developer.forums.answerhub.com/questions/152941/update-webview-fireos.html

**Comment by Dleemuse** [comment]
I was sweating there for a few minutes thinking that the hubby & I were not going to be able to get the new version of AB on our Kindles. I just checked, he has the 2019 & I have the 2021 (11th gen), versions so hoping we will be OK. We are very excited about updating AB on our Kindles, so hope everything gets worked out. You guys are all great thanks for all the hard work that you have put in!

**Comment by bvahedy** [comment]
We are thankful for your contributions as well.

**Comment by agrogers** [comment]
I think this confirms what you have found
https://forum.xda-developers.com/t/switch-to-android-webview-from-amazon.4177649/
