### ISSUE TITLE
Enable Strong's pop up by long pressing the word

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#177]
See https://andbible.uservoice.com/forums/100177-general/suggestions/1920541-enable-strong-s-pop-up-by-long-pressing-the-word

- Open strongs links (optionally) in a popup window instead of special window

**Comment by tuomas2** [comment]
Related: #361

**Comment by machshev** [comment]
Is this something currently being worked on by anyone?

**Comment by tuomas2** [comment]
No, would you like to work on it? This would be a nice addition to the app.

**Comment by machshev** [comment]
I can't promise anything, I've got a lot on at the moment. But yes, I think I'll have a go... unless someone else gets there first.
Kotlin is a new language to me, but it shouldn't be too difficult to learn. There are also several other additions I'd like to make, so I'm sure the learning will be a worthwhile investment.

**Comment by tuomas2** [comment]
As far as I know, this one is not the first one on anyones TODO list, so it will probably be waiting for you.
I'll be waiting for your pull request :-)

**Comment by machshev** [comment]
Here is an initial prototype to check to see if I'm going in the right direction. I've tested it on the emulator and it seems fine. As soon as I work out how I'll check it on my phone too :)

[Pull request](https://github.com/AndBible/and-bible/pull/869)

**Comment by tuomas2** [comment]
Implemented in develop
