### ISSUE TITLE
Reading plan: user unable to go back to book

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1773]
https://support.andbible.org/scp/tickets.php?id=840

> In my reading plan I am unable to go to the book as it takes me back to the beginning when I select it.

**Comment by agrogers** [comment]
Also https://support.andbible.org/scp/tickets.php?id=828

**Comment by timbze** [comment]
Asking the user for more details

**Comment by agrogers** [comment]
I have had this problem as well. If I recall correctly I chose a different
plan but pushing the button for the new plan just took me back to the old
plan. It was weird. An app restart fixed the problem. But I couldn't fix it
any other way.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by timbze** [comment]
Was able to reproduce now 

https://support.andbible.org/scp/tickets.php?id=903

**Comment by timbze** [comment]
Same underlying issue as #1719
