### ISSUE TITLE
F10 has lost strongs numbers

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1774]
https://support.andbible.org/scp/tickets.php?id=759

I have sent email to eBible maintainer.
User has sent us module that works properly, so we can consider releasing it if it speeds up things.

**Comment by notetiene** [comment]
Hi, I've been in touch with Michael Johnson from eBible.  He kindly merged the strong's number capabilities from the old source he used.

The module is now updated and supports Strong's number system on both the old and new testament.

**Comment by agrogers** [comment]
Great. Thank you.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Thanks, closing this!
