### ISSUE TITLE
Promotional video for Huawei AppGallery

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1775]
> Upload a promotion video. Format: MOV or MP4. Recommended resolution: 1600 x 1200 px or 1200 x 900 px. Aspect ratio: 4:3. Max. size: 500 MB. Length: 15 seconds to 2 minutes.

@agrogers could you edit something fulfilling these specs for Huawei?

**Comment by tuomas2** [comment]
![Selection_203](https://user-images.githubusercontent.com/5811789/135454201-96aee72e-6510-4245-b620-9c37fb584b51.png)

also intro videos should be 15sec to 2 minutes. Allows 3 intro videos...hmm. I wonder what should we put here.

**Comment by tuomas2** [comment]
I'll leave them empty for now.

**Comment by tuomas2** [comment]
I'm not sure if it's worth the trouble to make such videos .... We have cool screenshots there too. Or what do you think?

**Comment by tuomas2** [comment]
Amazon would like to have 

>Up to 5 MPEG-2, WMV, MOV, FLV, AVI, or H.264 MPEG-4, 720 - 1080px wide (4:3 or 16:9); 1200 kbps or higher

**Comment by agrogers** [comment]
I can make something short. My original plan was for a 30 sec clip. Can't
get to it until next week.

**Comment by tuomas2** [comment]
It's also okay for me if you close this as 'won't fix'. At the moment those app stores are not that improtant to us. But... you can consider about this.

**Comment by agrogers** [comment]
Leave it open. I will get to it. Don't have much free time at the moment.

**Comment by tuomas2** [comment]
https://www.youtube.com/watch?v=r9kFUD7xSNU

**Comment by tuomas2** [comment]
https://youtu.be/mJKrPEPG_Qo

**Comment by tuomas2** [comment]
releasing this in Amazon together with 4.0.620

**Comment by tuomas2** [comment]
Releasing this in Huawei together with 4.0.620
