### ISSUE TITLE
Enhancement for persecuted christians

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#178]
- [ ] Tor setting (like in F-droid)
- [ ] Proxy setting (like in F-droid)
- [ ] #1609 

See https://andbible.uservoice.com/forums/100177-general/suggestions/5067361-enhancement-for-persecuted-christians

> I'm writing some thoughts to help andbible spread across persecuted countries. I think I saw an issue long time ago about changing the icon to be less visible, but I don't find it anymore. Anyway, there are a lot of ways that we could improve andbible for the persecuted church.
> 
> First of all, we would need to change the icon of andbible. Lot of people know what it means. I don't have ideas on what it could look like. Even more and more bible's opponents know what the fish means.
> 
> Secondly, we would need to change the name. I don't think it's useful to change the name, but could we add an option to change the launcher's name in settings? The other solution would be to do a separate project edition.
> 
> Thirdly, adding a proxy option so that it could use Tor network (or similar).
> 
> Fourtly, doing something like “Hide It Pro" app¹. It hides itself as a simple app (sound manager) in launcher, but with correct tapping and secret code (you should try), as an hiding app. We could do similar (or the same) with the one with the persecuted option (or an other andbible edition)
> 
> It was just some thoughts to help the Gospel and the Bible advance in hostile places. Not all must be made, but some would be very helpful. I would really like to help, but I don't know Android's Java.
> 
> It is amazing how many mobile device there are and how accessible it is. One of the cheapest way to share christian resources is by internet. However, it is sadly not very used and I don't find much resources for persecuted Christians. May God raise good programmers for His Kingdom.

**Comment by josephjq** [comment]
i am not a programmer, but absolutely agree with you, this should be a high priority for sure.  i recommend getting in contact with these folks.

https://www.wordproject.org/bibles/

note which app stores they are available in ;)

i called them for permission to extra and mixed their audio Bibles so people i know who are trying to learn english can here one chapter in their language, and then the same chapter again in english.  they granted it provided i continue to do this free of charge which is absolutely the plan.  they may have some insights to offer as or even programming help.

**Comment by ericjding** [comment]
My two cents: though there's a significant amount of variety in situations, I would argue that ideas like changing the icon for AndBible in persecuted contexts amounts to little more than window dressing.

From a security and complexity perspective, some of the suggestions made in the original forum post aren't bad, but would be better implemented outside of AndBible in another app (like the one that the poster mentioned, Hide It Pro). For network connectivity issues, re-implementing what's already available through other apps/services (VPN, proxy, Tor, etc.) again goes outside the heart of what AndBible is and does.

Better, I think, to focus AndBible developer efforts in improving and refining AndBible's core functionalities and offer suggestions on the wiki for using/obscuring AndBible in sensitive contexts. Just my opinion, of course.

**Comment by mjdenham** [comment]
The icon was actually changed.  It was originally a cross.

**Comment by radorn** [comment]
I was going to open a separate issue with this, but first I did a search for "fish" and this one turned up, so I guess it's better to put it here.
I'd like to point out that the fish symbol is actually a pagan symbol, and IF it was ever really used by actual bible-believing christians, it was an error:
["What about the Jesus Fish?"](https://www.youtube.com/watch?v=F5TX5lCufJs)

I'm not sure what a good logo/icon would be appropriate to throw off persecutors, but I know it's certainly wise to avoid pagan symbology on the word of God.
Is it possible to make application icons user-customizable on Android?

**Comment by ericjding** [comment]
> Is it possible to make application icons user-customizable on Android?
Nova Launcher (for example) allows users to change the icon for apps on the home screen.

As far as what symbols are most appropriate, I think it'd be great if someone came up with a high-resolution, attractive AndBible icon with an image of a book/reader but with (subtle) hints that it's more than just an eReader app. Perhaps an open book on a podium? Even an icon inspired by a simply opened Bible, for that matter, like [here](https://www.publicdomainpictures.net/en/view-image.php?image=9920&picture=open-bible) or [here](https://www.shutterstock.com/image-photo/open-book-on-wood-background-246112852?id=246112852&irgwc=1&utm_medium=Affiliate&utm_campaign=Kratochvil&utm_source=39150&utm_term=), might be fine (if it's distinguishable as such at low pixel count -- that's really the hard part). As I've said before, I don't think that changing the icon likely does much as far as potential (state-sponsored) persecution, though, so I don't believe it should be a high priority.

**Comment by radorn** [comment]
What about a rock gushing out water?

**Comment by tuomas2** [comment]
Related: from 3.3 onwards, all downloads will be through HTTPS and before downloading anything, user will be warned about downloading stuff in persecuted country. (implemented in build 363)

**Comment by agrogers** [comment]
I think this can be closed now.
