### ISSUE TITLE
Proposal: Change the way the plus button on the verse action dialog works 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1781]
At present the button changes the selection mode to multiple verse select. Pushing the button a second time reverses the mode back to single verse selection.

What I think would be more helpful is that pushing the button a second time would select the next verse. And pushing the button again would select the next verse after that. So the plus button allows you to select as many verses as you want without having to touch the text itself.

To show what is happening I would add a small number to the right of the button that indicates the number of verses that have been selected. Each time you tap the button the number would increase.

The multiple selection mode can be exited by closing the dialog or perhaps by a long press action on that button.

I have wanted this because it can be quite difficult to select multiple verses for several reasons
1. If the verse has existing bookmarks the dialog can take up almost the whole window
2. So I have to try and click to the side of that dialog.
3. And as I select more verses I can include more bookmarks so the dialog can keep growing.

**Comment by Dleemuse** [comment]
This is a great idea Andrew, I love this idea! I have had the same problem.

Debra

**Comment by bvahedy** [comment]
@agrogers not to say your idea is bad, but I kinda like the way it works now. You can always move the bookmark dialog window aside by dragging the widow header and make the bible window 90% visible then with one tap select multiple verses whereas with what you are proposing you would have to tap for every verse.

**Comment by Dleemuse** [comment]
Thanks Ben, your suggestion worked beautifully, & I will be using this in future. But for those who don't know this (as I myself didn't),  they might struggle with wondering why the plus button doesn't add more verses than just two. Just a thought :)

**Comment by bvahedy** [comment]
Yes, I agree. The plus icon is a confusing icon and doesn't tell the user what it's for. That also was my initial beef with that icon. Perhaps finding an icon that conveys the message that it will now enable the user to select multiple verses would be more appropriate than changing the functionality of that icon.  
But I think we should wait for version 5.0 of AB😁 to change anything that drastic.

**Comment by Dleemuse** [comment]
Sounds good!

**Comment by agrogers** [comment]
Hi Ben

I am not proposing that the current functionality be reduced. I rarely ever
push the plus button a second time because there is never a need to change
the mode to single select. So I see this as a wasted opportunity. You could
still do what you do (and I do sometimes) - move the dialog off screen.
This proposal would just make it easier and I think also more intuitive

**Comment by bvahedy** [comment]
Oh ok, I see what you mean. You are proposing that when we tap on the plus icon for each iteration the app should select additional verses instead of stopping the selection mode.  In that case I agree with you. Thanks for the clarification.

**Comment by Dleemuse** [comment]
> Oh ok, I see what you mean. You are proposing that when we tap on the plus icon for each iteration the app should select additional verses instead of stopping the selection mode. In that case I agree with you. Thanks for the clarification.

That is the way I see it also, continued tapping of the plus button could just continue to add a verse each time you tap it. :)

**Comment by agrogers** [comment]
Yep, that's it. Good to hear your feedback. Thanks
