### ISSUE TITLE
Android System Webview

### ISSUE THREAD

**Issue by dbell154** [AndBible/and-bible#1786]
On some of my emulators I get the message that I need to update my Android Webview and provides a link to Android System Webview on Google Play. When I go to the link it says it is disabled, and when I side load it. I still get that message. 

![Screenshot_1633207402 (Phone)](https://user-images.githubusercontent.com/3357697/135731417-7a12bdca-65a4-4161-8ec1-7fca00044e13.png)

While this may work on some emulators/devices I found that this issue is easily resolved by updating Google Chrome. (https://docs.microsoft.com/en-us/power-bi/consumer/mobile/mobile-android-error-update-android-system-webview)
That might be a better recommendation.

**Comment by tuomas2** [comment]
would apply only to android 8

**Comment by agrogers** [comment]
Thanks. I got that problem too.

**Comment by dbell154** [comment]
Installing Chrome on my Android 9 emulator worked.

**Comment by tuomas2** [comment]
Hmm. on Android 9 it should be WebView again, not Chrome. At least in my Android 9 mobile phone it is so.

**Comment by tuomas2** [comment]
We should change the link to google chrome on Android 8 phones.

Android 9 should use Webview. @dbell154 's issue is still mystery to me.

**Comment by tuomas2** [comment]
I also checked now Android 9 emulator and it indeed has WebView disabled. Weird.

**Comment by tuomas2** [comment]
Got it fixed. But now this makes me wonder if we should apply #1756 to this device too, not only Android 8 & 8.1. Perhaps we should check the packageName of webview package there too...

**Comment by tuomas2** [comment]
But not changing anything unless we get white toolbar bug report from Android 9 user

**Comment by tuomas2** [comment]
Related #1765

**Comment by tuomas2** [comment]
Tested fix on android 5 emulator, and package name was there com.android.webview which can not be found in play store. So this fix is faulty.

**Comment by tuomas2** [comment]
API 25 emulator gives chrome

**Comment by tuomas2** [comment]
My Android 5 devices gives correctly com.google.android.webview. I think these issues are mainly emulator related.
