### ISSUE TITLE
Can we have a slightly different icon for the beta version?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1789]
I never know which version i am using now. If we had automatic synching of the db it probably wouldn't matter too much. But it's a pain when i add stuff in my non-preferred version and then have to copy it across to the preferred version. A different icon would help a little I think.

**Comment by uniqueid001** [comment]
What distinguishes a "beta" version, for you, from a non-beta?  Do you compile it yourself, with a different app id?  If so, then choose the "debug" build type instead of release (see #1660).

**Comment by tuomas2** [comment]
we use same bulds there. in beta period we have -beta appended to version name.

**Comment by agrogers** [comment]
Am I the only one who has had difficulties trying to remember what version
I am working in when both public release and beta are installed? Often the
only way I can tell is by going into the Help to see the name there.

**Comment by tuomas2** [comment]
they can't be even installed at the same time because they have same app id too

**Comment by agrogers** [comment]
Oh, so the two apps I have installed then must be one that I made myself???

**Comment by tuomas2** [comment]
I believe so

**Comment by agrogers** [comment]
Oops. I shall close this then :D
