### ISSUE TITLE
Verse numbers are harder to read in night mode

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1790]
Aaron wrote: I recently updated to the new app rollout.  I like it a lot   However, in night mode, I am having some difficulty reading verse numbers due to then being grey on black (adding noise only makes it worse). Could we perhaps have a way to change the color (and perhaps independently change other attributes) of verse numbers?

Thank you for a great app. I have been a user for many years.

![image](https://user-images.githubusercontent.com/13920678/135752761-d3a9b19a-95af-4168-9828-dfeacac547d2.png)

**Comment by agrogers** [comment]
Also raised here: https://support.andbible.org/scp/tickets.php?id=814

**Comment by cmahte** [comment]
I noticed this in both sepia and night mode. With darker backgrounds, verse
numbers should be heavier weight (bold) when they're superscript to
maintain visibility. It would go a long way to keeping them as visible as
the text. (But likely they'll be a bit too heavy on a white background...
either gray them on white too, or keep them regular weight.)

**Comment by tuomas2** [comment]
should make it bit lighter in night mode

**Comment by tuomas2** [comment]
Fixed in above mentioned commit
