### ISSUE TITLE
StrongsGreek links not working 

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1795]
**Bug was found on And Bible version**
Build 610

![Screenshot_20211003-123335.png](https://user-images.githubusercontent.com/35117769/135767988-87eba3a9-c722-4924-a69e-b66969338118.png)

**To Reproduce**
1. Click the "1756" link in bottom window and it opens 5624. It opens the same 5624 for every link 

This happens with the StrongsGreek module in AB repository

**Comment by bvahedy** [comment]
Timmy, does this happen with StrongRealGreek?
I'm unable to duplicate this.

**Comment by timbze** [comment]
StrongsRealGreek works

**Comment by tuomas2** [comment]
Problem unfortunately remains, but handling is moved to #1820
