### ISSUE TITLE
extend time before auto-backups are deleted, just in case

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1799]
now it's 1 month

**Comment by agrogers** [comment]
Yes, I don't see any reason why it couldn't  be a lot longer. It would be unfortunate to lose the backup before a user realised the app had been updated. Or does the update happen when the app is opened? If it is when it is opened then 30 days should be fine. But still could be longer :)

**Comment by timbze** [comment]
Yes, file is usually less than 1mb and so it shouldn't be an issue to keep it for a year or whatever.

**Comment by tuomas2** [comment]
Changed to 6 months a2d0780c850ae1b95d764fc0633f0115d9f013aa

**Comment by tuomas2** [comment]
Auto-backup happens when app is doing migrations, i.e. when it is started. I'm not sure, maybe 6 months is a bit excessive, especially in beta period, when migrations are happening all the time and there will be collected a lot of these backup files.

**Comment by tuomas2** [comment]
Changed to 3 months
