### ISSUE TITLE
Easier to use method to import/use user-defined reading plans

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#180]
- [ ] Validate files -- check for duplicate days, unparseable reading data

**Comment by timbze** [comment]
My plan was to import the user's reading plan files to internal storage. This would then be backed up in Google's automatic app backup.

However, it would not get backed up in user manual backup, and I don't like that idea.

Either I could import the reading plan file text into database, or modify the backup process to include the reading plan files.

Also keeping #570 in mind...

What's your thoughts? @tuomas2 @JJK96

**Comment by tuomas2** [comment]
I would like that reading plans would be stored in database and text file would be just input format for reading them in. Meaning that all reading plans would reside similar way in database. So on loading time AB would check if there are any built-in reading plans that have not yet been read into db and read them if there are any.

**Comment by tuomas2** [comment]
File format should be validated:
When importing the file, format would be checked and user would get an error (perhaps with option to 'skip' errors) if there is illegal syntax.

**Comment by tuomas2** [comment]
Related #938

**Comment by timbze** [comment]
@tuomas2 considering #938 do you still think the plans should be saved entirely in db? Or should we rather save them to internal storage like modules and read from there?

The reading plan status will/should be stored in db anyway, but I'm talking about the reading plan data itself.

**Comment by tuomas2** [comment]
Not necessarily as they are read-only data but then they would not be backed up with normal db backup. 

Though if reading plans would be special "modules" (like font package currently is), then would not be a problem, as modules can be backed up separately. What do you think?

**Comment by timbze** [comment]
Yes I think we could make them into special "modules", and still supply the default plans with the app. That way any custom plans by the user could be backed up and restored like modules.

I think that would be the least confusing and less duplicate for developers.

**Comment by tuomas2** [comment]
Yes, sounds good.
