### ISSUE TITLE
Suggestions for improving the UI/UX for backup and restore

### ISSUE THREAD

**Issue by joshuad31** [AndBible/and-bible#1801]
Backup and restore menu for 3.3 looks like this:
![unnamed](https://user-images.githubusercontent.com/5976059/135893027-4245c45e-7734-4a15-acc2-dde6f05bce81.png)

Backup and restore instructions for 3.3 are here:
https://github.com/AndBible/and-bible/wiki/FAQ#how-do-i-copy-my-notes-and-bookmarks-to-my-new-phone

As a designer, I see where users might end up frustrated or confused. Here are some things you might want to consider:
1. The backup and restore instructions on GitHub contain no screenshots.
2. The first item in the backup and restore menu is to backup the APK file. 
3. The last item in the backup and restore menu is to backup the database file.
4. Unless the users have knowledge outside of the FAQ they are likely to select the first option.
5. The APK file is not the DB file and does not contain the user's bookmarks
6. It is very likely that the users will be unable to restore their bookmarks later since they ended up saving the APK file and not the DB file.

Suggestions:
1. Do some user UI/UX testing to see how many of your non-technical users are able to follow the instructions in the FAQ to successfully backup and restore their database. At the time of backing up the file users are given 6 options. How many users select the right option?
2. Change the order of options given in the backup and restore menu so that backing up the DB file is listed as the very first option.
2. Add screenshots to the FAQ which show the user which button they should press in order to backup their DB file.
3. Listen to users more carefully when they tell you that backup and restore did not work for them instead of blaming them for being ungrateful or unappreciative of the work you did to make such a wonderful app that has helped hundreds of thousands of Christians enjoy and read the word of God.

**Comment by bvahedy** [comment]
@joshuad31 now we appreciate this type of constructive criticism, these are good input which we will look at, thank you for that. This is much better than threatening the developers with one star rating if they didn't listen.

**Comment by timbze** [comment]
@agrogers also had some good suggestions on #1156. The main thing lacking in improvements like these is time. Development work takes a ton of time. But thanks @joshuad31 for your suggestions. I will close this issues since we're tracking the same idea on #1156. Thank you.

**Comment by agrogers** [comment]
Hey, I did have some good suggestions there. I thought I had just thought
about those - I was going to work on a design for that in the coming weeks.
Thanks for pointing that out Timmy!

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
