### ISSUE TITLE
JSword builds fail

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1815]
https://jitpack.io/com/github/AndBible/jsword/2.3.43/build.log

@uniqueid001

**Comment by uniqueid001** [comment]
That is interesting.  It broke in build 42 with the update to the gradle version, which removed the deprecated 'maven' plugin.  I notice that the build process has some sort of "discovery" of the available tasks and chooses which ones to run.  In build 41 and previous it ran './gradlew install', but in 42 and later it ran './gradlew build publishToMavenLocal'.  I don't see that build process in the jsword git repository.  How is it configured to look for the produced artifacts?

**Comment by tuomas2** [comment]
Let's see if the latest fix fixed the build

**Comment by tuomas2** [comment]
https://jitpack.io/com/github/AndBible/jsword/2.3.44/build.log 

```
Build starting...
Start: Sat Oct 9 08:30:43 UTC 2021 e5075cd071c4
Git:
2.3.44-0-gdf2812e
commit df2812e6ccb7f3dc58c5acc29ab3aaf2de1bcc54
Merge: d312080 4ad436d
Author: Tuomas Airaksinen 
Date:   Fri Oct 8 08:12:38 2021 +0300

    Merge pull request #9 from uniqueid001/master

Found gradle
Gradle build script
Found gradle version: 7.2.
Using gradle wrapper
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Downloading https://services.gradle.org/distributions/gradle-7.2-all.zip
.10%.20%.30%.40%.50%.60%.70%.80%.90%.100%

------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          1.8.0_252 (Private Build 25.252-b09)
OS:           Linux 4.18.0-25-generic amd64

0m4.400s
Getting tasks: ./gradlew tasks --all
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Tasks: publishToMavenLocal,
Found javadoc task
Running: ./gradlew clean -Pgroup=com.github.AndBible -Pversion=2.3.44 -xtest build publishToMavenLocal
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
> Task :clean UP-TO-DATE

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :processResources
> Task :classes
> Task :jar
> Task :assemble
> Task :check
> Task :build
> Task :publishToMavenLocal UP-TO-DATE

BUILD SUCCESSFUL in 5s
4 actionable tasks: 3 executed, 1 up-to-date
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2021-10-09T08:31:22.888591098Z
Exit code: 0

ERROR: No build artifacts found
```

**Comment by tuomas2** [comment]
https://stackoverflow.com/questions/58233354/how-to-solve-the-error-of-error-no-build-artifacts-found-after-the-following

**Comment by tuomas2** [comment]
Do you want to continue investigating this @uniqueid001 ? I can also revert the changes... though it's not urgent as not very often changes are needed to JSword.

**Comment by tuomas2** [comment]
Reverted it for now in the above mentioned commit.

**Comment by uniqueid001** [comment]
> Let's see if the latest fix fixed the build

No, it wouldn't.  The invalid XML was present since March 2021 (v2.3.27) but didn't cause the build to fail.

**Comment by uniqueid001** [comment]
> Reverted it for now in the above mentioned commit.

v2.3.41 succeeded, which included the conversion to kotlin (commit 98046ea9)
It was v2.3.42 that failed (commit 9aa0ca28)

I did some reading about jitpack.io and discovered that I can initiate a build myself instead of waiting for you to try it for me : )
Apparently the old 'maven' gradle plugin automatically defined what to publish into ~/.m2/repository/ and that's where jitpack is looking for artifacts (not in ./build/libs/).  When I define a MavenPublication for the current 'maven-publish' gradle plugin, then it puts artifacts into ~/.m2/ and jitpack.io finds them.

I don't know how to create a good PR for this, since you'll need to revert the reversion to reinstate the previous changes.  I created a branch, named `bugfix-#1815/declare-maven-publication`, in my repo (git commit 0b25162e0ede020bd01023bbc401778d925384e2).  It built successfully on jitpack.io.

**Comment by tuomas2** [comment]
> > Reverted it for now in the above mentioned commit.
> 
> v2.3.41 succeeded, which included the conversion to kotlin (commit 98046ea9) It was v2.3.42 that failed (commit 9aa0ca28)
> 
> I did some reading about jitpack.io and discovered that I can initiate a build myself instead of waiting for you to try it for me : ) Apparently the old 'maven' gradle plugin automatically defined what to publish into ~/.m2/repository/ and that's where jitpack is looking for artifacts (not in ./build/libs/). When I define a MavenPublication for the current 'maven-publish' gradle plugin, then it puts artifacts into ~/.m2/ and jitpack.io finds them.
> 
> I don't know how to create a good PR for this, since you'll need to revert the reversion to reinstate the previous changes. I created a branch, named `bugfix-#1815/declare-maven-publication`, in my repo (git commit 0b25162e0ede020bd01023bbc401778d925384e2). It built successfully on jitpack.io.

You just described how to make a good PR :-) Just pull the changes from master branch, then revert revertion commit in as one commit, then make your fix commit, then make PR out of the outcome.

**Comment by uniqueid001** [comment]
> > > Reverted it for now in the above mentioned commit.
> > 
> > 
> > v2.3.41 succeeded, which included the conversion to kotlin (commit 98046ea9) It was v2.3.42 that failed (commit 9aa0ca28)
> > I did some reading about jitpack.io and discovered that I can initiate a build myself instead of waiting for you to try it for me : ) Apparently the old 'maven' gradle plugin automatically defined what to publish into ~/.m2/repository/ and that's where jitpack is looking for artifacts (not in ./build/libs/). When I define a MavenPublication for the current 'maven-publish' gradle plugin, then it puts artifacts into ~/.m2/ and jitpack.io finds them.
> > I don't know how to create a good PR for this, since you'll need to revert the reversion to reinstate the previous changes. I created a branch, named `bugfix-#1815/declare-maven-publication`, in my repo (git commit 0b25162e0ede020bd01023bbc401778d925384e2). It built successfully on jitpack.io.
> 
> You just described how to make a good PR :-) Just pull the changes from master branch, then revert revertion commit in as one commit, then make your fix commit, then make PR out of the outcome.

I'm not so sure it's a _good_ PR : )  It doesn't clearly show what I changed because it shows the revert in the diff, so it shows an accumulation of four PRs in one.

**Comment by tuomas2** [comment]
> I'm not so sure it's a _good_ PR : ) It doesn't clearly show what I changed because it shows the revert in the diff, so it shows an accumulation of four PRs in one.

I could see clearly your recent changes by looking at the particular last commit, so it was good enough for me. :-)

**Comment by tuomas2** [comment]
Seem to be fixed now. Thanks! 

https://jitpack.io/com/github/AndBible/jsword/2.3.49/build.log
