### ISSUE TITLE
Option to expand footnotes in bible text

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1823]
I have been reading Baptist confession 1689 doc lately and it feels that it would be better if footnotes were expanded to the bible text (i.e. links were available without clicking footnote icons). So that kind of option would be nice to have.

**Comment by agrogers** [comment]
I could see two options:
1. The icon remains and when it is clicked it reveals the footnotes in the text itself.
2. There is no icon - the footnotes are always visible

I think my preference for such things is that they are shown in a separate window. See https://github.com/AndBible/and-bible/issues/1021

Or like this https://github.com/AndBible/and-bible/issues/1465

**Comment by tuomas2** [comment]
I was thinking that it would be a new text option that would allow showing all footnotes inline.

**Comment by agrogers** [comment]
Could be nice. Or create a runtime commentary that allows showing footnotes in its own window. That would be cool.

**Comment by NetForce1** [comment]
> Or create a runtime commentary that allows showing footnotes in its own window. That would be cool.

I would prefer this option. I actually came here through https://tracker.crosswire.org/browse/MOD-380. They fixed the problems with the Dutch footnotes commentary DutKant in a new module that adds the footnotes to the Bible module. And looking for how integrated footnotes work in AndBible I stumbled upon this issue.

**Comment by tuomas2** [comment]
![image](https://user-images.githubusercontent.com/5811789/230416634-a710c8fb-c95f-426e-9f19-634046851e2b.png)

![image](https://user-images.githubusercontent.com/5811789/230416655-027a4e1f-30fa-4f1b-9128-4a87a2c15099.png)

Implemented only for xref type footnotes.
