### ISSUE TITLE
Use a confirm dialog before opening any link outside of app

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1825]
I think it might be a good idea to use something like image below (Telegram does that when the "create link" feature is used) for every link that opens in another app (i.e. YouTube, Github links, etc)

![image](https://user-images.githubusercontent.com/35117769/136665869-b3ee11d6-1c22-4145-a386-d45807d7549b.png)

**Comment by timbze** [comment]
Related to #1630, #1609, #178

Though not a very big security issue, it could be, and also I think it's good to give user a second chance before opening another app

**Comment by agrogers** [comment]
I'm not a big fan of that personally. Unless it can be turned off/always
accepted. Then it is fine. My preference is to indicate that it is an
external reference in the link itself with a little icon or something.

**Comment by timbze** [comment]
I know Telegram's purpose is to show you which link will be opened when it's hidden in a [link](). It could be a malicious link and you don't see it because it's hidden.

We don't have "unknown" links for us, and it's not like some third party can put unknown links (except in module "about" section I guess).

I still think it would be a good feature, it could have a checkbox "Always open links" or "Don't show again".

**Comment by agrogers** [comment]
Yep, checkbox addresses my concern well.

**Comment by tuomas2** [comment]
> I know Telegram's purpose is to show you which link will be opened when it's hidden in a link. It could be a malicious link and you don't see it because it's hidden.
> 
> We don't have "unknown" links for us, and it's not like some third party can put unknown links (except in module "about" section I guess).

We do have A tag in osis that allows opening external urls.

**Comment by tuomas2** [comment]
Hmm isn't this already implemented, already for calculator? Should check

**Comment by tuomas2** [comment]
Yep calculator does this. Fixed one more related thing in calculator.

Changed it so that it will force-ask this in non-discrete mode also if clicking link in document.

**Comment by tuomas2** [comment]
I think we can open "safe" links, i.e. our own links (github, youtube etc) without asking.
