### ISSUE TITLE
Home page images are stretched

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1827]
On my phone:

![Screenshot_20211010-050450.png](https://user-images.githubusercontent.com/35117769/136692994-673dd60d-1cbd-4b2d-829a-693ea42d4fd0.png)

**Comment by timbze** [comment]
@BryceSteuer

**Comment by BryceSteuer** [comment]
I will try to fix today or ASAP. Will I need to do a new PR or something?
Does it appear to you like it's just the last set of images?

**Comment by timbze** [comment]
Yes, just make PR when you get to it

Color images look fine, font images also look stretched like others 

![Screenshot_20211011-131006.png](https://user-images.githubusercontent.com/35117769/136843884-232ef6da-8498-4d56-972c-bacd8f602840.png)

**Comment by BryceSteuer** [comment]
How about this? (Updated with fixes)
https://brycesteuer.github.io/andbible.github.io/

**Comment by timbze** [comment]
At 800px width it looks perfect

The stretch issue is fixed

But on my phone I now have 3 + 1 (which probably is acceptable). E.g. 3 font pictures in a row and then 1 underneath. Same with map pictures.

Weirdly though, on my wide-screen monitor (1920px), it only shows 2 in a row. So the colors section shows 2 side by side, plus 1 underneath. Fonts and maps have 2 and 2, etc

**Comment by BryceSteuer** [comment]
I think I'll need to investigate a bit more tomorrow, Lord willing.

**Comment by BryceSteuer** [comment]
Ok, this now is a complete fix I believe, based on AG Roger's suggestion I had forgotten about (remove width and height properties from the images)
https://brycesteuer.github.io/andbible.github.io/
Let me know if it's OK to PR.

**Comment by timbze** [comment]
Maybe a technical thing, I notice at exactly 850px the images disappear

Above 850px the left/right margins for the pics are almost gone.

Other then that I think it's great

**Comment by BryceSteuer** [comment]
Ok, both of those are fixed to my view (check the same link above I pushed just now to). I'm not so good at checking my work I guess. But thanks for pointing those errors out.

**Comment by timbze** [comment]
Well the original issue has been well fixed :)

Don't like being picky, but another thing now is above 850px the image row width in total is less than the video width.

For example:
849px
![image](https://user-images.githubusercontent.com/35117769/137041480-c7fa12b4-8d78-4cf1-82f1-e0756c2f2363.png)

850px (and wider is the same)
![image](https://user-images.githubusercontent.com/35117769/137041509-0c7fac35-20d2-4e08-abc6-8f0749f790ea.png)

**Comment by timbze** [comment]
For my part you can make a PR, this is not a blocker for me

**Comment by BryceSteuer** [comment]
Alright, I fixed that issue and will PR upon your final approval. I realize I didn't have to fix it but I would rather do a pull request knowing there are no inconsistencies.

**Comment by timbze** [comment]
Looks good!

**Comment by BryceSteuer** [comment]
PR: https://github.com/AndBible/andbible.github.io/pull/6

**Comment by tuomas2** [comment]
Fixed by AndBible/andbible.github.io#6
