### ISSUE TITLE
update branches

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1842]
current stable etc

**Comment by tuomas2** [comment]
Merged develop to current-stable and created release/v4.0 branch

**Comment by tuomas2** [comment]
I'll continue still for a while developing and releasing 4.0 releases from develop  branch, to make it convenient to make possible fix prs towards develop. 
This need to be changed later, however.

**Comment by agrogers** [comment]
What about stuff for 4.1? Where should PRs for that go to?

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
I would say that those prs can wait couple of weeks more unmerged. those can be made towards develop branch.

**Comment by timbze** [comment]
I think this has been completed for 4.0 version
