### ISSUE TITLE
Use different signature for debug

### ISSUE THREAD

**Issue by dbell154** [AndBible/and-bible#1849]
I wonder if we can change gradle to use a different application signature for debug.
I wanted to test a version of the app on my phone, but it insisted on uninstalling the current (Google Play) version first, which means I lose all my data.
I mean, I know it's possible, but wonder if it will cause problems with other developers.

In build.gradle.kts you can add this under BuildTypes

        getByName("debug") {
            applicationIdSuffix = ".debug"
        }

In my own app I also use three flavors so I can have up to 6 versions of the app installed on one device.

**Comment by timbze** [comment]
Look at [this section](https://github.com/AndBible/and-bible/blob/b24ccced17d50b55ceb945f0416ab78b52a22eec/app/build.gradle.kts#L127-L138)

You can have another suffix for debug version by adding `APP_SUFFIX=.debug` in local.properties file. This is also documented in developer wiki section I think.

Maybe it should be that by default, not sure. But this is an option you can use now

**Comment by dbell154** [comment]
@timbze 
Yeah, I knew that but didn't want to mess with existing setting. 
If it's not changed in the main app source I know I can easily add/uncomment that for my personal use.

**Comment by tuomas2** [comment]
Just add `local.properties` to your And Bible root folder and have line

```
APP_SUFFIX=debug
```

there. That will do the trick.
