### ISSUE TITLE
Czech CSP title is not displayed, but TTS speaks it

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1850]
**Describe the bug**
For reference, in Eph 1:1, NET Bible shows Salutation as a title above v1.

In Czech translation "Český studijní překlad", Salutation is read by TTS, but it's not displayed in the text.

It's possible that it's a module issue, but the difference between TTS and display is still a bit interesting.

https://support.andbible.org/scp/tickets.php?id=919

**Bug was found on And Bible version**
Build 612

![image](https://user-images.githubusercontent.com/35117769/137219191-160b9a54-d23e-4b08-b4bf-b6c5ce83761d.png)

**Comment by tuomas2** [comment]
We hide titles with `type="chapter"` because in many translations it is just "Chapter 1", "Chapter 2" etc. In this translation it is different (in Eph 1:1 there is title "Pozdrav").

**Comment by tuomas2** [comment]
I believe it would be bad idea to display them for that reason

**Comment by tuomas2** [comment]
What do you think?

**Comment by timbze** [comment]
Oh, so in that case it would probably be better to change/fix the module
