### ISSUE TITLE
App title should be changed to something <= 30 characters

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1857]
Google is changing their policy! App title must be changed to something less than 30 charaters (in all languages).

[Google's updated guidelines can be read here.](https://android-developers.googleblog.com/2021/04/updated-guidance-to-improve-your-app.html)

Not sure, but I guess we might have enough time to do this change towards 4.1.

**Comment by tuomas2** [comment]
> > [!] Google Api Error: Invalid request - The title for the app is too long for language en-US.

Can't update metadata any more! 
So no changes to app descriptions etc until name change is done.

**Comment by tuomas2** [comment]
I think we do not have any option but drop "by And Bible Open Source Project" from our Play Store official name due to this new regulation. Feel free to start discussing ideas for new name. 

Perhaps we should keep doors open to something completely new?

**Comment by agrogers** [comment]
What about "Bible Study App, by And Bible"

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by BryceSteuer** [comment]
I always have thought "Bible Study App" was a bit generic, but I guess if it's an open source test...

**Comment by agrogers** [comment]
Yeah, I probably agree with you now. We have had a few discussions about
the name over the last year.

One of the issues is that we were trying to keep the name of the app AND
the way that name displayed on a phone the same. We wanted the name on the
phone to start with 'Bible'... hence 'Bible Study App'. That was probably
an unnecessary requirement. YouVersion just calls their app 'Bible' on the
device. We could have done the same.

The other issue was to try to identify the app as a study tool. YouVersion
for example is not really a study Bible - it is devotional bible app.

'And Bible' always bothered me because 'And' is such a common English word
and never looked right to my eyes. What does this mean: "And Bible is
great."  Am I saying in clumsy English 'and the Bible is great' or am I
saying 'the And Bible app is great'. That ambiguity bothered me. That's why
I had pushed for AndBible with no spaces - it eliminates the ambiguity.

The name 'Bible Study App' feels long to me now and so I find myself not
using it when communicating and reverting back to And Bible or AB. I could
use 'BSA'.

And yes, it is a little too generic I think... which is why we kept And
Bible in the full name.

**Comment by tuomas2** [comment]
> What about "Bible Study App, by And Bible"

Example from guidelines would suggest rather "And Bible: Bible study app".

**Comment by tuomas2** [comment]
Someone in AB user group suggested

> I'm not familiar with github, I just read about the issue. Maybe keeping it small is the go to.
> Also thinking whether something along the lines of "Bible And Modules" would hit the right note? Cuz returning old users might search And Bible, and still get the exact same result as before due to similar name. However this is just my humble opinion.

**Comment by uniqueid001** [comment]
I agree with eliminating the space in "AndBible" such that it is a proper noun, not a grammatically incorrect/incomplete phrase.  I also agree that the name should have some uniqueness in it, and I continue to think of and refer to it as simply "AndBible".  I have no disagreement with beginning the launcher's label with "Bible" so that the sorting meets expectations.

**Comment by bvahedy** [comment]
I've always preferred  "AndBible" . You can always add "Android Bible study
app" at the end of it as description. That's 31 characters in total.

**Comment by timbze** [comment]
I've seen the German translation uses "Bible+", that _could_ be a name.

I like the idea too of making AndBible the "name" of the app.

I also would like to keep the launcher name to start with the word Bible.

I've used dash (-) or the word "by" below, those could still be switched around etc.

Some ideas:
- Bible+ by AndBible
- Bible Plus by AndBible
- Bible Study+ by AndBible
- Bible Study Plus - AndBible
- Bible Study App - AndBible

**Comment by tuomas2** [comment]
Somehow I don't like "by AndBible" because "AndBible" is not a person nor organisation, but (old) app name...

**Comment by tuomas2** [comment]
Is it worth it to keep "Open Source" there? Like "Bible+ Open Source"  Though open sourceness is advertised many other ways still even if it is not mentioned in app name.

**Comment by timbze** [comment]
> Example from guidelines would suggest rather "And Bible: Bible study app".

Before we changed the launcher start letter to B with "Bible Study App" it was at A (started with And Bible). For that part maybe it wouldn't hurt to change it back... since I think the icon would stay the same.

To use this guideline, to add to my ideas above:
- AndBible: Study
- AndBible Study+
- AndBible Study Plus
- AndBible: Study+ Open Source
- AndBible - Study App
- AndBible - Bible Study App
- AndBible+
- AndBible+ Open Source

I think having "open source" in title is irrelevant for the majority of people, so I wouldn't stress that (though doesn't hurt to keep it if it has space).

**Comment by bvahedy** [comment]
I'm with Timmy on this one, this gets my vote:
![Screenshot_20220104-102515_Gmail](https://user-images.githubusercontent.com/46405809/148106132-89bf97e2-8beb-4ad5-b310-8df7d225c316.jpg)

**Comment by tuomas2** [comment]
> In 2021 we updated our policies to limit app and game titles to 30 characters.
> 
> Check your app titles (and translations) and reduce any that are still longer than 30 characters.
> 
> In July this year we'll be truncating titles that remain in violation of the new policy.
> 
> If you have fixed this within the last 24 hours, ignore this message.

**Comment by tuomas2** [comment]
If we use "AndBible: Bible Study+" (which I'm tentatively picking from the above suggestions), should we then make recommend translations to follow same form "AndBible: X"?

**Comment by tuomas2** [comment]
Then if we choose to use "AndBible" we need to change project name everywhere too.
- [x] Play Store
- [x] Samsung store
- [x] Amazon store
- [x] Huawei store
- [x] Publish new version so that 3 above stores are updated.
- [x] fdroid metadata repository
- [x] Source: app_name_long, title, header, paragraph_1_1, README
- [x] Source: copyright notice
- [x] Homepage
- [x] Github (About, both project as well as repository)
- [x] Tutorial pages
- [x] Social media: Youtube, Facebook

**Comment by tuomas2** [comment]
Leaving this still open for 1-2 weeks. Latest 23th june I will make final decision and send new name for translators. I guess we then can still finalize the change by the end of this month...

**Comment by timbze** [comment]
> If we use "AndBible: Bible Study+" (which I'm tentatively picking from the above suggestions), should we then make recommend translations to follow same form "AndBible: X"?

Sounds good to me. That way "AndBible" would stay the same across translations I assume, I think that would be good and would be recognized as the "brand".

**Comment by andyp1xe1** [comment]
I would suggest to pick a simple name.
What I mean is, I would choose "AndBible: Bible Study" over the variant with a plus at the end.

Or, maybe, to keep the B at the beginning:
Bible Study with AndBible

**Comment by tuomas2** [comment]
> I would suggest to pick a simple name. What I mean is, I would choose "AndBible: Bible Study" over the variant with a plus at the end.

Plus in the end gives idea of many tools that come with it. But I'm open to this option, if it is a popular opinion.

> Or, maybe, to keep the B at the beginning: Bible Study with AndBible

I like to follow Google's suggestion of having it like [Name: description](https://android-developers.googleblog.com/2021/04/updated-guidance-to-improve-your-app.html)

**Comment by tuomas2** [comment]
> Or, maybe, to keep the B at the beginning: Bible Study with AndBible

BTW I'm not planning to change the title shown in app launcher for now. So it will stay the same.

**Comment by tuomas2** [comment]
related: discussion about earlier name change #573

**Comment by agrogers** [comment]
I definitely support 'AndBible' over 'And Bible'.

Could it simply be 'AndBible Study'? Or 'AndBible Study App'? Or 'AndBible
Study Tools'?

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by timbze** [comment]
> I definitely support 'AndBible' over 'And Bible'. Could it simply be 'AndBible Study'? Or 'AndBible Study App'? Or 'AndBible Study Tools'?

That works for English, but for translations it would probably be good to have the word Bible after "AndBible"

I like Tuomas' suggestion of "AndBible: Bible Study+". Though I wouldn't be opposed to just ending with "Bible Study" or "Bible Study App". I think the + is kinda nice though and adds that it's a versatile app, for more than just basic study (e.g. notes and bookmarks)

**Comment by tuomas2** [comment]
I'm open with both of these:

- AndBible: Bible Study+
- AndBible: Bible Study

I think it's nice to have universal name AndBible as well as translatable descriptive name after that. And also follows Google's guideline neatly.

**Comment by tuomas2** [comment]
Plus or not plus, give your opinion (if you didn't already). Also you can still try to convince me about any other option! :-)

**Comment by agrogers** [comment]
I am fine with those too. I dont have any strong preferences.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by ildar** [comment]
IMHO plus is a modern glamour thing everybody uses that rarely meaning
anything.
I'd say: use `+` if you have also a non-`+` version. Otherwise leave it for
the future.

**Comment by tuomas2** [comment]
Clearly more votes were given to "AndBible: Bible Study" (poll in Telegram group) so let's go with that. 
I'm thinking that we can leave it up to translators to decide if they would like to use plus (like germany does now).

**Comment by tuomas2** [comment]
> Call for translators: app name change (due 29th June)
> 
> Hi,
> 
> As I noticed you on June 11, we must reduce the length of our Play Store app title (which has been until now lenghty “Bible Study app, by And Bible Open Source Project”. We have decided to change it to “AndBible: Bible Study”. 
> 
> Guideline for translators is to keep AndBible untranslated and translate words “Bible Study”. In some languages, plain “Bible” might be better option. Also, Germany is using currently “Bibel+”, which is acceptable in the new form “AndBible: Bibel+”. Similar solutions are allowed in other languages too if translators think it’s better suited to the particular language (you can always ask our opinion if hesitating). 
> 
> Google is saying that deadline is July and they will truncate app titles unless we act before, so let’s do this as soon as possible (latest 29th June). 
> 
> Please do not hesitate to ask if there is anything, either on ticket: https://github.com/AndBible/and-bible/issues/1857 or via email: help.andbible@gmail.com. 
> 
> Best regards,
> 
> Tuomas
> 
> Thank you!

**Comment by JJRcop** [comment]
I don't know if this helps but from when I was first introduced to this project years ago I've always known it as AndBible just like the "new" name writes it.

I wasn't even aware of the name being uncertain at all, but as a user I am glad it is decided to... I guess "revert" back to AndBible, it's just a nice name in my opinion.

**Comment by tuomas2** [comment]
> App name change done, please check!
> Hi,
> I just performed the name change as planned. New strings should be visible in Google Play descriptions in a short moment (maybe 24 hours max). In app, they should be a bit later (maybe one week or so). Before that, changes can be reviewed in Github pull request:
> https://github.com/AndBible/and-bible/pull/2182/files
> There were some translations still missing, which I went through with help of Google Translate. Particularly, I was changing strings 1 and 4 from Play Store texts, that are:
> 1: AndBible: Bible Study
> and
> 4: "{{ title }}" is a powerful, yet easy to use, offline Bible study application for Android. The app does not aim to be simply a Bible reader, but focuses on being an advanced tool to do in-depth personal Bible study.
> (only thing changed in this string is to have title as variable there).
> Please check these strings and fix if needed. You can also improve (1) because in most cases I just translated it like “AndBible: Bible”. 
> Best regards,
> Tuomas
>

**Comment by tuomas2** [comment]
> Then if we choose to use "AndBible" we need to change project name everywhere too.
> 
> * [x]  Samsung store
> * [x]  Amazon store
> * [x]  Huawei store

I have updated these but info will be published only when next version is released. Doing it soonish...

**Comment by agrogers** [comment]
Thanks for all the work you keep doing on this project Tuomas. You're a
saint.

**Comment by bvahedy** [comment]
I agree, I know we are all busy with work and life events but this also is the work of God. Thank you.

**Comment by tuomas2** [comment]
All done now

**Comment by ildar** [comment]
My two lepta, if you will...
1. AndBible should always be one word (no space inbetween!)
2. no dashes in the name! at least I've seen no option above with a dash
where it was correctly used. Use `:` instead.
2. I like the idea to start the app name with "Bible Study"
3. Hence my proposition: "Bible Study App a.k.a. AndBible"
4. or maybe "Bible Study App: AndBible"

**Comment by timbze** [comment]
@ildar

See 
https://github.com/AndBible/and-bible/issues/1857#issuecomment-1159514679 

1. Has been implemented
2. I don't think dash is used in the name anywhere now... Except for the github link, which I don't think will change, nor matters.
3. The name starts with "Bible Study" only in launcher. See the issue linked above for more reasoning behind the changes

**Comment by ildar** [comment]
That's great. Thanks a lot! I appreciate that.
