### ISSUE TITLE
Red letter option "ON" by default

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1863]
I think "red letter" setting should be on by default. Currently in 614 it's not (don't think it's ever been)

Maybe others have other idea...

**Comment by bvahedy** [comment]
I'm fine with it either way but for those who use modules that have red letter coded it would benefit them if it's on as they might not know that there is a way to turn on red letter.

**Comment by agrogers** [comment]
I would default it to ON

**Comment by cmahte** [comment]
When defaulting to red letters enabled, the grey tone of the 'red' should
be dark enough that it is still visible to people with vision issues
(60%-65% grey minimum).

That is, It's great as long as it tends toward a dark red. But if the
default shows up fully html red #FF0000 or lighter, I would suggest that's
not a good plan.

**Comment by tuomas2** [comment]
I do not use "red letters of christ" so much because whole bible is Word of God likewise and we should not think that "red letters" is somehow more valuable. But I can still set it on by default.

It is darkish I think, but do you think it is good @cmahte ?

**Comment by cmahte** [comment]
It looks ok in normal view, but the night mode...

**Comment by tuomas2** [comment]
Made it darker now. Let me know if it is now good when you get the update (4.0.615+)
