### ISSUE TITLE
Context menu "Remove" removes bookmarks without confirmation

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1864]
**Describe the bug**
Highlight text that includes bookmarks, a "Remove" context menu item shows up and when you press it, all bookmarks that are within that selected text get removed without confirmation 

**Bug was found on And Bible version**
Build 614

![Screenshot_20211016-135015.png](https://user-images.githubusercontent.com/35117769/137600514-b9756225-4772-4942-ad4c-5d7ca8f6ea9c.png)

**Comment by timbze** [comment]
One option would be to remove the "Remove" item

**Comment by agrogers** [comment]
I have never used the Remove option in the context menu. I didn't realise
it was there. I am not opposed to removing it.

**Comment by bvahedy** [comment]
The remove option only appears if the selection covers a bookmark, so it's functioning as expected. So if you have a few words bookmarked in a verse and your selection does not overlap those words then the remove option does not appear.
 I say we should keep it as is. We can add confirmation.

**Comment by timbze** [comment]
It's bad especially when there's hidden bookmarks

**Comment by timbze** [comment]
Minimum it should have warn confirmation the way it does from other new modal

**Comment by bvahedy** [comment]
I agree there should be a confirmation.

**Comment by tuomas2** [comment]
Removed
