### ISSUE TITLE
Impalement as add-on combined Mickelson_Strong's dictionary

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1865]
For better definitions of Hebrew and Greek word, this module will give the combined Mickelson dict and KJV Strong's definition in addition to the number of occurs. We can place this on the Andbible repository for those who would like to download it.

![Screenshot_20211017-120910_Bible Study](https://user-images.githubusercontent.com/46405809/137641423-338f2f10-038e-403c-9501-87c718fc12f2.jpg)

**Comment by agrogers** [comment]
Cool. Where did you get this from?

**Comment by bvahedy** [comment]
I came across Mickelson dict about 10 years ago, it was available publicly on a website, though I don't remember the site. Then I wrote a routine to combine Strong's and Mickelson and included the no. of occur also.
I did this over 8+ years ago. I like more of Mickelson def. But I wanted to still see KJV Strong's def. as well. That's why I combine the two together.

**Comment by agrogers** [comment]
That's great. Do you think we have permissions to put it on our repository?

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment]
I did not change any of the definitions, so as long as the content has not been changed it should be ok.

**Comment by bvahedy** [comment]
@agrogers can you check this site and see if I'm reading it right:
https://mctbible.org/main/other/museum/dictionary/mickelsons-enhanced-strongs-greek-and-hebrew-dictionaries

May be we need to ask Johnathan for permission to host it on Andbible repository.

**Comment by agrogers** [comment]
I agree - it does seem like we need to get his permission.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment]
I can't find any contact info to ask him for permission.

**Comment by agrogers** [comment]
Hmm, I can't find anything either. Makes it hard to ask for permission...

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Found him from linked in: https://www.linkedin.com/in/jonathan-k-mickelson-steward-79318549/

**Comment by bvahedy** [comment]
His LinkedIn profile directs you back to the webpage that has no contact
info. There is a message on LinkedIn but you have to have premium
membership and I don't really want to join yet another social media app.
let alone pay $70 for it.  Does anyone among you have the ability to use
the message on LinkedIn?

May be he doesn't want anyone to contact him.

**Comment by bvahedy** [comment]
I contacted Costas Stergiou who is the developer of the "The word" Bible program for windows, since he was given permission by Johnathan Mickelson to have free access of his dictionary on his server, to see if he can give us Jonathan's contact info.
He responded saying he will try to privately contact him first and will get back to me. Will let you know when I hear back from him.
Here is the Word website, I use his program on windows, it's a great software:
[https://www.theword.net/index.php?article.help&l=english](url)

**Comment by agrogers** [comment]
Great. Good job.

**Comment by bvahedy** [comment]
Costas got back to me and this is what he said:

Hello Ben
I got note from Jonathan. He is currently recovering from a neck injury and he told me that he will consider your request later,

**Comment by bvahedy** [comment]
This was Johnathan's response to our request for making his dictionary available on Andbible, I guess he has his reasons: 
-------- 
I will not be releasing the Mickelson Enhanced Strong's Dictionaries (MESD) to any other persons than Costas Sterigou. The MESD is for "theWord" Bible software only...
Jonathan K Mickelson
A Steward in the Lord and a slave of Yeshua Anointed
Bible Translator and Lexicographer (MCT)
The PlowShare Mission
