### ISSUE TITLE
Create a help documentation repository for Read the Docs

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1866]
I tried to create one but the button was disabled - I assume I don't have the power - which is probably a good thing :)

**Comment by tuomas2** [comment]
Created https://readthedocs.org/projects/and-bible/


Do I need to do something else?

**Comment by tuomas2** [comment]
Adding you as a maintainer

**Comment by tuomas2** [comment]
- [ ] could also bind this to docs.andbible.org if we want to ...

**Comment by agrogers** [comment]
Um, i think you have created a Read the Docs setup for the purpose of
documenting the code in And Bible. But what I wanted was a new git
repository in which we will place our documentation that Read the Docs help
info.

Both could be good. Having documentation helping me to understand the code
for the app would have been helpful.

Or am I missing something?

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Does documentation need to be in a separate repository, or could it be just in a subfolder within main repository?

**Comment by tuomas2** [comment]
I don't intend to create code documentation there.

**Comment by tuomas2** [comment]
But I can create separate documentation repository too if you feel it's better that way.

**Comment by agrogers** [comment]
I have no idea which is best. My guess is that people who will maintain the
help documentation will not be coders. So keeping them away from the code
seems good - it wont help them and could confuse them. Not sure how read
the docs integrates with the repository except that it seems to automate
things when changes are detected. We dont want builds of the documentation
happening with code changes. But i guess it is smart enough to work that
out.

If someone is going to work on the docs then they probably dont want the
code.

So, i have convinced myself that a separate repository is probably best


___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
https://github.com/AndBible/docs

**Comment by tuomas2** [comment]
https://readthedocs.org/projects/andbible-docs/

**Comment by agrogers** [comment]
OK, i have put the basic Read The Docs tutorial files into our repository so it now compiles and we have a working site called 'Lumache'  https://andbible-docs.readthedocs.io/en/latest/

I will start adding content at some point. Was it Dana who was also doing some docs?

**Comment by tuomas2** [comment]
Changed url to https://andbible.readthedocs.io/ (had to remove and create a new project)

**Comment by agrogers** [comment]
Great
