### ISSUE TITLE
Finnish 1689 baptist confession & 1693 baptist cathecism module

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1882]
I have source but should make osis xml.

**Comment by tuomas2** [comment]
Licence https://creativecommons.org/licenses/by-nc-nd/4.0/

**Comment by tuomas2** [comment]
Source: https://drive.google.com/file/d/13RNz8rzu04rjIcP7kM-seuitBxZZ8lZQ/view?usp=sharing

**Comment by tuomas2** [comment]
Source is missing introduction. That can be added later. Does not have many bible links.

**Comment by tuomas2** [comment]
Sent email to sword-devel http://crosswire.org/pipermail/sword-devel/2021-October/049025.html

**Comment by adyeths** [comment]
I've made a custom writer for pandoc that can help with this. It can convert anything pandoc can read to osis markup. The output would likely need some editing to clean things up but it will get you most of the way.  https://github.com/adyeths/osiswriter

**Comment by tuomas2** [comment]
what kind of markup must be used for bible references?

**Comment by adyeths** [comment]
A little more information on bible references can be found here https://wiki.crosswire.org/OSIS_Genbooks but they look like these examples:

    <reference osisRef="Gen.1.1">Genesis 1:1</reference>
    <reference osisRef="Ps.119">Psalm 119</reference>
    <reference osisRef="Prov.1-Prov.9">Proverbs 1-9</reference>
    <reference osisRef="2Cor.6.14-2Cor.7.1">

My u2o script has a list of all the specific bible book abbreviations in it if that helps.

**Comment by tuomas2** [comment]
Ah, I thought pandoc would have some specific format. I think most difficult is the conversion of the references to OSIS format.

**Comment by tuomas2** [comment]
https://github.com/AndBible/LBCF1689FIN
