### ISSUE TITLE
Allow user to disable "upgrade webview" message

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1889]
For some users the webview works partially (webview version 52 is that way). Modals don't show correctly but Bible text works and links can be clicked.

On some devices it's impossible to upgrade webview unless the OS provider updates it with OS update (e.g. Kindle and Teclast tablets)

In such case the user may want to disable the message since they know about the problem but want to use as is anyway.

I think the message should possibly only be disabled in Application preferences > advanced settings. And also the setting should only show if webview is lower then supported setting. That way the user will not mistakenly disable the message when it shows and then later complain that something is not working.

This support ticket is such a request. https://support.andbible.org/scp/tickets.php?id=966

**Comment by timbze** [comment]
For reference, this is what webview v52 does (other modals do the same thing):

![image](https://user-images.githubusercontent.com/35117769/138903421-4ec29e9b-11a1-430f-8b49-865be6d78386.png)

**Comment by tuomas2** [comment]
I kind of think that it might be good idea to remind user about webview issue, because he might forget that and wonder how things don't work as expected. It should be smaller annoyance to press "proceed" button on every startup than having all these unexpected issues.

**Comment by RepentAndBelieveTheGospel** [comment]
I would like to request a checkbox to disable this WebView notification. I have a Huawei phone which doesn't have any Google Services. From what I understand, this WebView package depends on GMS to work properly. The functionality I am using is working and I don't want to be reminded everytime about the WebView package. Please allow me to decide if I want to be notified or not.

![Screenshot_20211203_171512_net bible android activity_edit_193221332167912](https://user-images.githubusercontent.com/53478971/144626838-eecf527f-c472-41b9-81f6-8e9e9f9f4ca3.jpg)

**Comment by timbze** [comment]
@RepentAndBelieveTheGospel do you have the latest version of And Bible installed? There was a "fix" put in so that Huawei phones _should_ not show this message at all, because they have different version numbers for webview. This fix should be available in 4.0.619. Ref #1932

**Comment by tuomas2** [comment]
fix should be released to huawei app gallery already

**Comment by RepentAndBelieveTheGospel** [comment]
> fix should be released to huawei app gallery already

I have downloaded this version from APKPure. Version 4.0.621 doesn't show in AppGallery yet. The issue is still there.

![photo_2021-12-03_18-19-04](https://user-images.githubusercontent.com/53478971/144636489-3289dcfa-166d-42bd-b80e-c66eb2f9c865.jpg)

**Comment by tuomas2** [comment]
hmm maybe needs another fix then. can you do bug report  from main menu or post your logcat here

**Comment by RepentAndBelieveTheGospel** [comment]
> hmm maybe needs another fix then. can you do bug report from main menu or post your logcat here

[logcat.txt.gz](https://github.com/AndBible/and-bible/files/7651517/logcat.txt.gz)

**Comment by tuomas2** [comment]
Thank you. Got it fixed, will be released in 1 week (if not already today).

**Comment by RepentAndBelieveTheGospel** [comment]
> Thank you. Got it fixed, will be released in 1 week (if not already today).

Updated to 4.0.628 now and that annoying message is gone. Thank you!

**Comment by timbze** [comment]
Stale and I think not needed anymore.
