### ISSUE TITLE
Limit what is shown in the popup selection menu

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1904]
Is it possible to exclude things from the popup menu like 'Translate' (see below).

Raised in #1880 

![image](https://user-images.githubusercontent.com/13920678/139246948-0af43a37-8f42-4923-9b61-517fdb4a5967.png)

**Comment by tuomas2** [comment]
Hmm translate is pretty important and other text tools too (dictionary app, etc).

**Comment by tuomas2** [comment]
I really think those items are important. If it is to be disabled, it should be optional. What was the motivation for removing those entries?

**Comment by agrogers** [comment]
I think the OP found there were things in there he would never use. That
was all.

**Comment by tuomas2** [comment]
I will leave them as they can be useful for many. And one can implement apps with various (possibly useful, even bible related) functions with PROCESS_TEXT intent.
