### ISSUE TITLE
Verse numbers are shown on their own line in Arabic bible

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1905]
The numbers should be on the same line as the text.

See screenshot. Raised in #1880

![image](https://user-images.githubusercontent.com/13920678/139247163-dd8177da-297b-452e-833b-f544d7fd5006.png)

**Comment by agrogers** [comment]
Is this a document encoding issue, not our issue?

**Comment by tuomas2** [comment]
Could be our issue, need to check.

**Comment by tuomas2** [comment]
There is paragraph break after verse tag in OSIS fragment. I believe we intepret it correctly by having line break there.
`<verse osisID="Matt.5.3" verseOrdinal="24214"> <div sID="gen6631" type="paragraph" />`
