### ISSUE TITLE
Option in settings to disable confirm action of bookmark deletes. 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1914]
Add a switch in settings to disable confirm when deleting bookmarks. This way the user can delete a bookmark without the confirmation dialog popping up.

Based on user issue:
https://support.andbible.org/scp/tickets.php?id=943#reply

**Comment by tuomas2** [comment]
I am not sure if this is good idea. User might accidentally remove bookmarks and I believe most users want that kind of accidents prevented.

**Comment by timbze** [comment]
Some kind of undo would probably be better than completely removing the confirm dialog

**Comment by bvahedy** [comment]
The default would be "On"  which displays the confirm. Only users who don't want the extra dialog can turn it off.

**Comment by tuomas2** [comment]
Still it would easily cause mistakes for those that opt out confirmation messages.

**Comment by bvahedy** [comment]
We can't be responsible for their actions, if they choose to disable it manually then we can safely assume they know what they are doing. All we can do is to make it flexible enough for proper usage. 
But I get a feeling you really are worried about users complaining why their bookmarks can't be retrieved even though they purposely turned off the confirmation dialog.
Also, after awhile people just tap the "yes" confirmation button  without a thought it of habit and lose their bookmark that way anyways.

**Comment by agrogers** [comment]
I rarely delete a bookmark so it doesn't bother me. I would imagine that
is the case for others as well?

Adding additional info to the dialog so it is clear what is being deleted
is usually a good practice. That would make the dialog more useful.

**Comment by bvahedy** [comment]
I agree only if the original requestor wasn't using bookmarks as a reading markers.
He does have a point, there is no way to use a bookmark as a marker which the word "bookmark" implies .

**Comment by tuomas2** [comment]
I think that using (unsynced) windows or workspaces are way better suited for tracking specific reading positions than bookmarks. Bookmarks (despite their name) are not good solution.

**Comment by bvahedy** [comment]
I agree with you.
