### ISSUE TITLE
Reading plan toolbar day does not update when pressing done and going to next day 

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1915]
**Bug was found on And Bible version**
Build 616

**To Reproduce**
1. When behind on a reading plan, mark the days as complete and press done
2. The day # in toolbar does not update

**Comment by tuomas2** [comment]
Release-critical?
Do you think you get this fixed before next thursday?

**Comment by timbze** [comment]
I can get it fixed. Not critical though

**Comment by timbze** [comment]
I can not reproduce now. Yesterday I tried figuring out in the code why it was happening, couldn't. Today I'm trying to debug the issue from Android Studio and now it's not happening. So I'm confused... If I see it again I'll save the log

**Comment by timbze** [comment]
Can't reproduce anymore. Don't know if I was on another device with older version or what.

The functionality is anyway supposed to change with UI refresh so will close now
