### ISSUE TITLE
The Greek and Hebtew Downloads are always re-updating after downloading.

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#1917]
From ticket:
https://support.andbible.org/scp/tickets.php?id=980

The Issues are (2) issues.
download documents.
1. Strongs Greek
2. Strongs Hebrew

The documents download and install, but the issues that's wrong is that The Bible Study App isn't accepting it as an Updated download.

Every time I go back to the download documents its listed as a document found that needs to be made applied for an update. 

The Documents, Strongs Greek and Hebrew are working in the Bible Study App, the Issues are discribed as above.

**Comment by timbze** [comment]
The star is a sign for "recommended" download. The update icon is an orange up arrow.

From support ticket:
![image](https://user-images.githubusercontent.com/35117769/139875448-6092fdd0-7cc0-4924-b14b-6b9bbb2bb6f8.png)
