### ISSUE TITLE
Wiki can not be cloned in Windows because of colon (:) in file name

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1920]
Culprit is [this page](https://github.com/AndBible/and-bible/wiki/Press-release:-Bible-Study-App-version-4.0-has-been-released)

Windows can not have colon `:` in file names.

Maybe not a very big issue... if we want to fix it, it may need to be fixed where the file was first added and force pushed, but not 100% sure, maybe it would work to fix in a commit now.

First problematic commit is `814835a3` from Oct 2

**Comment by tuomas2** [comment]
I don't think it is really necessary to clone wiki anyway. 
Maybe when release note is old enough we can fix it (is it already?).

**Comment by gelafin** [comment]
After https://github.com/AndBible/and-bible/issues/2146#issuecomment-1103523801, I tried cloning and found one file that still has a colon in the name.
`error: invalid path 'Press-release:-Bible-Study-App-version-4.0-has-been-released!.md'
`

**Comment by gelafin** [comment]
But I agree it's not a big deal, because the wiki can still be edited online

**Comment by timbze** [comment]
Yes the issue still exists. I think the history will have to be rewritten and force-pushed for it to be fixed

**Comment by timbze** [comment]
Oh there were 2 files. I removed the other one now, it only had a link to the page Tuomas updated. Does it work now? (I was temporarily on Windows when I checked but not most of the time)

**Comment by gelafin** [comment]
Works now!
