### ISSUE TITLE
My notes issue

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#193]
From user (Ben): 
> Also, I noticed that some of my notes, although the list shows there is something in that note, when I select it and go to that note there is nothing there. And if I navigate to that verse there is no pencil icon on the verse indicating that there is a note on that verse. If I highlight the verse and try to create a note, then I see a duplicate in the "my note" menu. 

> Not all my notes have this issue, the are some that are displayed correctly. 

> I did restore my notes from a backup of previous version, so this may be a compatibility issue between versions. I don't know if anyone else has encountered this issue.

**Comment by tuomas2** [comment]
@bvahedy Please re-open if you think this is valid still.

**Comment by bvahedy** [comment]
This issue still exists, at least for me,  how do I reopen this ticket? 
Or if you feel this is some sort of incompatibility issue between versions, we can let it go,  your call.

**Comment by tuomas2** [comment]
Re-opened. I would like to get this fixed but to get it fixed I should be able to reproduce. 
Perhaps you can send me (via email) your bookmarks/notes database so that I can try to reproduce with that?

**Comment by bvahedy** [comment]
Here is the file:

**Comment by tuomas2** [comment]
Please send directly to my email, not to github. I did not receive the
attachment.

**Comment by bvahedy** [comment]
Where do I get your email address from?
Can you send it to me?

**Comment by bvahedy** [comment]
Ok see if
[andBibleDatabase.zip](https://github.com/AndBible/and-bible/files/2763282/andBibleDatabase.zip)
 this works:

**Comment by tuomas2** [comment]
It appears that in @bvahedy's database My Notes database has key in wrong format (for example "Exod 24:16" instead of "Exod.24.16". I could not figure out why And Bible at any time in And Bible's history would have written it like that. So this remains mystery for now.

**Comment by tuomas2** [comment]
> It appears that in @bvahedy's database My Notes database has key in wrong format (for example "Exod 24:16" instead of "Exod.24.16". I could not figure out why And Bible at any time in And Bible's history would have written it like that. So this remains mystery for now.

@mjdenham do you know possible explanation (related to the history of And Bible / JSword and how the key is saved) for this?

**Comment by bvahedy** [comment]
@tuomas2 did you see my last hangout message on this?
You can close this ticket for now.

**Comment by bvahedy** [comment]
For those who experience this same issue: I Used sqlitemanager to fix the keys in mynotes table, and all seems to be good.
Make sure after you update the db file,  to restore your notes and bookmarks in Andbible in order to see the fix.
