### ISSUE TITLE
Latest version shows links twice 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1930]
V4. 0.618

![IMG_20211107_071233.jpg](https://user-images.githubusercontent.com/13920678/140623979-56e628ff-17a2-4469-956e-60c0f820a09e.jpg)

![Screenshot_2021-11-07-07-13-38-653_net.bible.android.activity.jpg](https://user-images.githubusercontent.com/13920678/140623983-fb9b8aa9-525b-4f05-a6a3-f7c01b5cf07c.jpg)

![Screenshot_2021-11-07-07-14-03-896_net.bible.android.activity.jpg](https://user-images.githubusercontent.com/13920678/140623987-5e3c29d3-4db7-4ade-8d4d-8704bc41dbe1.jpg)

**Comment by tuomas2** [comment]
regression in 618, not before

**Comment by tuomas2** [comment]
thanks for beta testing :-) Prod users are happier.

**Comment by agrogers** [comment]
Great. Glad it is just in the beta.
