### ISSUE TITLE
'Back' no longer takes me back to the search results 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1934]
Issue in 618. Back does nothing in this instance.

**Comment by tuomas2** [comment]
also regression in 618

**Comment by timbze** [comment]
Related #1933 

Back actually no longer works at all.

https://support.andbible.org/scp/tickets.php?id=1029

**Comment by tuomas2** [comment]
Fixed in dev a7982ede62f5ed48c21691444f665eb925b251a9

**Comment by bvahedy** [comment]
Verified fixed in 619.1 build.
