### ISSUE TITLE
Weird spacing before apostrophes 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1935]
This issue seems new to me.

![IMG_20211108_083037.jpg](https://user-images.githubusercontent.com/13920678/140664222-39e60ec2-bf19-4196-a493-fd1017788bed.jpg)

![IMG_20211108_083244.jpg](https://user-images.githubusercontent.com/13920678/140664279-b66e1a47-9e89-4f7e-8797-5f75647a876f.jpg)

![IMG_20211108_083314.jpg](https://user-images.githubusercontent.com/13920678/140664284-b90ac3d0-5e23-46c1-9a0a-b9ba8e2d4db6.jpg)

![IMG_20211108_084348.jpg](https://user-images.githubusercontent.com/13920678/140664572-9e8d9bf5-6626-47f7-9fcf-830e4496c010.jpg)

**Comment by tuomas2** [comment]
Possibly due to fix to #1821

**Comment by tuomas2** [comment]
Well hmm, can't reproduce.
![Screenshot_20211111_092524](https://user-images.githubusercontent.com/5811789/141256001-89f64982-97da-4644-89dd-ac996924ea07.png)

**Comment by tuomas2** [comment]
HTML looks perfectly nice and simple.
`<h3 class="titleStyle skip-offset" data-v-5effcc10="">Israel’s Last Days</h3>`

**Comment by tuomas2** [comment]
maybe something wrong with your setup? Font? Something weird in CSS?

**Comment by agrogers** [comment]
OK, i will investigate further. I dont think i have done anything special
though.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by agrogers** [comment]
The problem seems to be the Serif font. Literata font works fine.

![Screenshot_2021-11-14-05-19-01-198_net.bible.android.activity.jpg](https://user-images.githubusercontent.com/13920678/141656526-c7c26f90-42dc-45c2-9850-55f8e2c57648.jpg)

**Comment by tuomas2** [comment]
Font issue then. I guess there's nothign we can do then

**Comment by agrogers** [comment]
The font used to be fine so it's a bit weird.

**Comment by tuomas2** [comment]
maybe webview upgraded and introduced a new bug?

**Comment by timbze** [comment]
![image](https://user-images.githubusercontent.com/35117769/141679491-2b8d0c6a-ca2a-49a6-b8d3-421353c108da.png)

**Comment by timbze** [comment]
Is Serif an Android font? It shows the same issue when copying the text into a note, so I doubt it's webview. (?)

Issue reproduces on my Android 12, but can not reproduce on Android 8 at all, tried older and newer webview, and tried version 607 and 619.

So I think it's Android bug
