### ISSUE TITLE
Error occurred install zip BookException missing data files

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#1939]
https://support.andbible.org/scp/tickets.php?id=1028

**Describe the bug**
I don't know if this is just specific to the module (non-repo module) or if it's an issue that needs to be investigated further.

**Bug was found on And Bible version**
Build 618

**To Reproduce**
1. Install module zip via intent 
2. Message says error occurred 
3. Open AB and module is installed and seems to work properly 

**Logs**
```
11-09 06:22:07.663 17537 17537 E InstallZip: Error occurred
11-09 06:22:07.663 17537 17537 E InstallZip: org.crosswire.jsword.book.BookException: The book [name omitted] is missing its data files.
11-09 06:22:07.663 17537 17537 E InstallZip: 	at org.crosswire.jsword.book.sword.SwordBookMetaData.adjustLocation(SwordBookMetaData.java:980)
11-09 06:22:07.663 17537 17537 E InstallZip: 	at org.crosswire.jsword.book.sword.SwordBookMetaData.adjustConfig(SwordBookMetaData.java:840)
11-09 06:22:07.663 17537 17537 E InstallZip: 	at org.crosswire.jsword.book.sword.SwordBookMetaData.reload(SwordBookMetaData.java:255)
11-09 06:22:07.663 17537 17537 E InstallZip: 	at org.crosswire.jsword.book.sword.SwordBookMetaData.<init>(SwordBookMetaData.java:204)
11-09 06:22:07.663 17537 17537 E InstallZip: 	at net.bible.android.view.activity.installzip.ZipHandler$installZipFile$2.invokeSuspend(InstallZip.kt:165)

```

**Comment by tuomas2** [comment]
Hmm. that particular zip file has 2 modules: 1 genbook and 1 commentary.

**Comment by tuomas2** [comment]
And your zip file seem to have missing articles. Maybe I sent you wrong zip file.

**Comment by tuomas2** [comment]
So error message was correct. sent you correct zip file
