### ISSUE TITLE
[FR] share APK for beta releases

### ISSUE THREAD

**Issue by ildar** [AndBible/and-bible#194]
for those who avoid Google Play Market and such.
Guess Github can bear those.

**Comment by tuomas2** [comment]
I could set up a folder in google drive an upload them there.

I don't know if f-droid supports "beta channel". That would be nice.
Hope we get f-droid releases fixed soon as well.

https://gitlab.com/fdroid/fdroiddata/merge_requests/4120

**Comment by ildar** [comment]
>
> I don't know if f-droid supports "beta channel". That would be nice.
>
It does. Though in a manual mode

> Hope we get f-droid releases fixed soon as well.
>
This is great!

The idea with G Drive is good too as long as non-authenticated is permitted
and apk signed with your key

**Comment by tuomas2** [comment]
Yesterday I did most of what is needed to get f-droid releases rolling. 
Beta APKs are now here: https://github.com/AndBible/and-bible/wiki/Beta-testing

**Comment by ildar** [comment]
Thanks a lot
