### ISSUE TITLE
Book, chapter and verse is wrong when the app is opened (and can't change it through menu without scrolling a bit at first when the app is opened)

### ISSUE THREAD

**Issue by peace2000** [AndBible/and-bible#1947]
**Describe the bug**
When I open the app, it opens correctly the previous book, chapter and verse I had open. But the book, chapter and verse indicator at the top claims that I have a very diffent book, chapter and verse open that I really have. The info doesn't change to correct one before I scroll at the current position a bit first.

Also, when I open the app, I cannot choose a different book, chapter and verse through the menu without scrolling a bit at the current position first.

**Bug was found on And Bible version**
3.3.400#6a52aa2ba (built 29/04/21 20:09:21)

**To Reproduce**
1. Close the app
2. Open the app again
3. Now the top indicator should show an incorrect book, chapter and verse you really have open
4. Now when you scroll, the info changes to correct one
5. Also, if you immediately (after opening the app) try to choose a different book, chapter and verse through the menu, the selection doesn't work properly if you haven't scrolled at the current position a bit first.

**Expected behavior**
The info at the top would be correct and choosing a different book, chapter and verse would work immediately after opening the app, without the need to scroll at the current position a bit at first.

**Screenshots**
In the process of opening the app...:
<details>
<summary>Details</summary>

![kuva](https://user-images.githubusercontent.com/17256841/141653560-cb942a31-f08b-40f9-9624-0e731b7dfe42.png)

</details>

Now, at the top there's wrong book, chapter and verse information:
<details>
<summary>Details</summary>

![kuva](https://user-images.githubusercontent.com/17256841/141653587-6926b25e-f75a-4e05-8874-f4bd12c74e0a.png)

</details>

But after I scroll a bit, it changes to the correct one:
<details>
<summary>Details</summary>

![kuva](https://user-images.githubusercontent.com/17256841/141653596-10bbf7d5-190b-476c-ae88-45f8936dada0.png)

</details>
Not really possible to prove through screenshots that choosing different book, chapter and verse through the menu doesn't work without scrolling at the opening position at first, but at least those screenshots show that the initial information is wrong.

**Smartphone (please complete the following information):**
 - Device: Sony Xperia X Compact
 - OS: Android
 - Version 8.0.0

**Additional context**
--

**Comment by tuomas2** [comment]
Please try if it works with the latest version (4.0.617 is the latest version in Google Play). I believe it has been fixed.

**Comment by peace2000** [comment]
Thanks, yeah it seems so though I had to reset and uninstall and then re-install the latest version.

**Comment by tuomas2** [comment]
hmm weird, normally it's enough if you simply upgrade.
