### ISSUE TITLE
Add option to Share to show the verse reference at the front of the verse

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#1974]
From https://support.andbible.org/scp/tickets.php?id=1113

> I'm curious, when I copy and paste a verse selection, the chapter and verse description shows up at the end of the selection rather than the beginning.

**Comment by agrogers** [comment]
This has been added to PR #1968 

![image](https://user-images.githubusercontent.com/13920678/145678881-fa2bc0a8-a1e0-43c8-93e7-0fffc0f1a9b3.png)

**Comment by bvahedy** [comment]
Can we fix these two issues before merge into release builds for production:

1) When turning off the "show at front of verse" in the share/copy function. It doesn't keep the setting, it always reverts back to on.
 
2) For "show selected text only" can we remove the quotes around the selection, it should just be what was selected.

**Comment by agrogers** [comment]
Sure thing. I had forgotten about these.

**Comment by agrogers** [comment]
@tuomas2, this is failing a test that has nothing to do with my code:
net.bible.android.control.page.window.WindowSynchronisationTest > testWindowSyncInMaxMode 

I think it started when I merged the latest developer code into my code. The test is failing on another pull request as well.

**Comment by tuomas2** [comment]
Yes. I'll try to fix develop tests ASAP. #1991.

**Comment by agrogers** [comment]
This can be closed now I think.
