### ISSUE TITLE
Fix inconsistency in the status bar theme and make fullscreen mode immersive

### ISSUE THREAD

**Issue by actuday6418** [AndBible/and-bible#1979]
# Issues
1. I find it inconsistent and irking that the status bar doesn't assume the same colour as the top bar of the application. In this screenshot, for example, the top bar is grey and the status bar is black. Every modern Android app, from Telegram, AOSP apps, Signal, to Youversion Bible theme the status bar accordingly.
 
![Screenshot_20211212-201932_Bible Study](https://user-images.githubusercontent.com/56124831/145717316-66637fee-ad19-4c48-9036-010ce5bde307.png)

2. Non immersive full screen mode. Removing the black bar that serves no apparent purpose in full screen mode would be a great step towards improving the UX of the app.

![Screenshot_20211212-212053_Bible Study](https://user-images.githubusercontent.com/56124831/145719291-21ce2a76-bd66-40ea-8690-a1ddc2e4e458.png)

[StackOverflow question that has a solution to the full screen bar problem (idk if it applies to AndBible)](https://stackoverflow.com/questions/56353716/how-to-remove-top-status-bar-black-background)

Lastly, It would be great if AndBible could pull colours from the Android 12 Wallpaper theme. I understand if this is undesirable for a need to maintain brand identity or something, or because it would affect backwards compatibility.

I would love to work on these issues and make a PR, but unfortunately, I have no experience with Android development, Java or Kotlin.

**Comment by tuomas2** [comment]
If you are programmer of any sort, I highly encourage you to take some steps (install Android Studio and run project there) and try to fix the issue yourself! I started that way myself, zero knowledge on Android technologies.

**Comment by timbze** [comment]
I worked with fixing some deprecated code that directly relates to this on [my branch here](https://github.com/timbze/and-bible/tree/improve/insets_fullscreen). My next issue was exactly about status bar color, if anyone wants to continue from this feel free, I just did not have more time when I worked on this a few weeks ago.

**Comment by actuday6418** [comment]
I setup android studio like @tuomas2 suggested, and am now ready to dive in.

I'm unsure whether I should start from your fork or from master, @timbze. If you made a fix disjoint from that for the status bar, wouldn't it be best for those changes to be merged first in a separate PR?

**Comment by timbze** [comment]
@actuday6418 you can just ignore my code if you wish, the code I have is not ready for PR. Just thought if you would come across same code I worked on you might benefit from my "start". I think my code was heading the right direction but needs some more testing, which I just don't have time for right now
