### ISSUE TITLE
Is it possible to create PRs towards wiki?

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1981]
https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

**Comment by thebiblelover7** [comment]
@tuomas2 Apparently we cannot unless we change the way that we have the wiki. We would have to put the wiki as `.md` files in a folder of the repo and then setup a service that makes a comprehensive repo or smth.

Should we close this?

**Comment by tuomas2** [comment]
Gave you triage perm to repo, so that you can do changes to wiki. If you do any significant changes please let us know so we cah check.

**Comment by thebiblelover7** [comment]
Perfect, thanks!
