### ISSUE TITLE
Italic Bible text not displayed in 4.0.623

### ISSUE THREAD

**Issue by msavli** [AndBible/and-bible#1983]
In version 4.0.623 9/012/21 italic text is not displayed.

![slika](https://user-images.githubusercontent.com/13658822/146225934-03893644-a995-4947-adba-54ac3b4b9704.png)

In version 
   4.0.622  2/12/21  this is OK.
   4.0.617  5/11/21  this is OK.

**Comment by timbze** [comment]
Just noticed this myself today. This is a very serious issue. Need to check if there are no tests that break for this bug.

Eph 2:8 "For by grace are ye saved through faith; and that not of yourselves: **it is** the gift of God"
![Screenshot from 2021-12-15 11-57-30](https://user-images.githubusercontent.com/35117769/146239934-a8f65017-c95d-4989-b227-a6f326727c01.png)

**Comment by tuomas2** [comment]
Thank you for doing beta testing. This would be tomorrow in production if this was not catched. Very likely due to some js side refactoring I did last week.
