### ISSUE TITLE
Bible text is missing

### ISSUE THREAD

**Issue by msavli** [AndBible/and-bible#1984]
https://support.andbible.org/scp/tickets.php?id=1130

Bible text is missing

"they that wear soft **clothing** are in kings’ houses"
![Screenshot from 2021-12-15 11-54-39](https://user-images.githubusercontent.com/35117769/146239597-0d74f78f-d8eb-4b50-add8-b489e6ed63dd.png)

**Comment by timbze** [comment]
Just noticed this myself today. This is a very serious issue. Need to check if there are no tests that break for this bug.

Eph 2:8 "For by grace are ye saved through faith; and that not of yourselves: **it is** the gift of God"
![Screenshot from 2021-12-15 11-57-30](https://user-images.githubusercontent.com/35117769/146239934-a8f65017-c95d-4989-b227-a6f326727c01.png)

**Comment by timbze** [comment]
Closed. See #1983

This was originally a question about support site. It is being taken care of, but sometimes can take longer than 1 day

**Comment by tuomas2** [comment]
Yep I'm having more serious look at the tickets only once per week. Other than that it is rather sporadic from my side. Other team members also help on that as much as they have time.

**Comment by agrogers** [comment]
I am happy to make some tests for this case... if someone can point me in
the right direction.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
There is no example of such test yet, but should be done in js side. Essentially need to feed OsisSegment (or higher level, OsisDocument or even BibleView) with some example OSIS xml content (that contains the elements that are now being hidden), render it and check resulting dom xml tree.
