### ISSUE TITLE
Sleep timer stops after 5min.

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#199]
When setting the sleep timer to anything over 5 min. and starting play, then returning to the bible view and then turning  the screen off. 

Andbible speaks for 5 min. And then it stops.
The notification showes a remaining time left but I don't know why it stops at 5min.

**Comment by tuomas2** [comment]
Weird... I'm using that feature myself quite often and did not notice this. But need to re-check.

Does it continue speaking normally when sleep timer is not activated?

**Comment by tuomas2** [comment]
With beta (only)?

**Comment by tuomas2** [comment]
Also you could give me the screenshots of both speak settings screens

**Comment by tuomas2** [comment]
Fixed in build 276

**Comment by bvahedy** [comment]
This is fixed now. Thank you.
