### ISSUE TITLE
Fix tests (still failing)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1991]
max couple of tests failing in CI

**Comment by tuomas2** [comment]
Hmm high prio because of many PRs... 
Can also skip tests if it's difficult to solve.

**Comment by tuomas2** [comment]
Ignored test as first aid now, leaving this open

**Comment by timbze** [comment]
I think the test probably fails cause of this issue.

1. Have 2 windows synced
2. Maximize window 2 and swipe to go to next verse or chapter
3. Unmaximize and you'll see window 1 did not change

**Comment by tuomas2** [comment]
I think it does not fail any more (I already reverted ignoring  test)
