### ISSUE TITLE
Custom CSS: Request verse spacing

### ISSUE THREAD

**Issue by luke-2136** [AndBible/and-bible#2003]
Hello.. new user here ..For bible viewing the line-spacing option is excellent but the verse spacing is the same as the line spacing. For me would like to have option to space the verses just a little bit more than the line. If possible could verse-spacing be added as a feature?

Did notice that custom css is possible but i do not have the skills to do that so thought i'd submit this as a feature request. Thank you.

**Comment by bvahedy** [comment]
I don't believe verse spacing can be done in CSS unless there are tags in the module that are placed for each verse.

**Comment by tuomas2** [comment]
> I don't believe verse spacing can be done in CSS unless there are tags in the module that are placed for each verse.

i would say it is possible

**Comment by luke-2136** [comment]
Thanks for the reply tuomas2 and bvahedy. So is there a chance this (verse spacing) gets ok'd as a new feature? I've got line space at 1.4x and thinking a slightly larger separation between verses would be nice for reading (my preference probably would be just 1.5x, or maybe 1.6x depending how it looked). Anyway thanks again for your consideration.

**Comment by tuomas2** [comment]
For now this is something that should be done with custom css. If someone makes PR about having it as a property we can consider inclusion. 

But to educate people about making custom CSSs, I could create a tutorial video about this, i.e. how to accomplish this particular issue with custom css module.

**Comment by agrogers** [comment]
I am happy to have a look at that custom property. I think i could work it out now.

We have info on CSS here, yes?
https://github.com/AndBible/and-bible/wiki/Custom-CSS-for-modules-for-And-Bible

**Comment by tuomas2** [comment]
Yes info about CSS is there. I was thinking that making an example video would be helpful though, to show how in practice to analyze DOM with Chrome remote inspection tool etc.

**Comment by agrogers** [comment]
> Yes info about CSS is there. I was thinking that making an example video would be helpful though, to show how in practice to analyze DOM with Chrome remote inspection tool etc.

I am happy to look at that. Your time is better spent elsewhere i think

**Comment by tuomas2** [comment]
I was thinking about making just a quick & dirty screen recording video  but feel free to contribute :-P

**Comment by agrogers** [comment]
If you  want to make a real quick one to help me then i can make a slow one :)

**Comment by tuomas2** [comment]
Okay let's see. It looks like I have quite many tickets for today... trying my best to tackle as many as possible.

**Comment by tuomas2** [comment]
Here also (like in #2548) there was scoped css so it is more difficult to make adjustments. Changed.

**Comment by tuomas2** [comment]
Here's some [quick and dirty css tutorial](https://youtu.be/HaK4Tf51mL0) that I promised long long time ago.

**Comment by tuomas2** [comment]
Add a little gap to verses when using one line per verse as I think it looks nicer.

**Comment by bvahedy** [comment]
That's great, I was able to incorporate this code:
.linebreak {
Display: block;
Height: 1em;
}
 into the style.css file and got the following result (see screenshot). Now I'm wondering if there is a way to prevent a linebreak when the verse ends with a comma or a semicolon so as to continue the flow of the verse. Rather than having a break on every verse.
![Screenshot_20230408_224117_Bible Study](https://user-images.githubusercontent.com/46405809/230756783-96054deb-e310-483c-9981-59f245ca4ab4.jpg)

**Comment by tuomas2** [comment]
not any easy way with css only, I believe.

**Comment by bvahedy** [comment]
Thanks for figuring out the linebreak. 
I noticed when speak is on that it highlights the verses like that as it reads. But I can see that you would have to programmatically read ahead to separate verses like that. 

Ok, I'll close this ticket.
