### ISSUE TITLE
Back button in reading plan list does not work

### ISSUE THREAD

**Issue by NetForce1** [AndBible/and-bible#2008]
When opening the reading plan list from the main menu, the back button in the activity title does not work. It reopens the same screen. Furthermore, the Android back button opens an empty screen, and only an extra tap on that back button brings me back to where I was before.

It is probably important to note that there is no active reading plan when this happens.

**Comment by bvahedy** [comment]
That is a regression.  something seems to be broken.

**Comment by tuomas2** [comment]
Any idea when it was working last time?

**Comment by bvahedy** [comment]
May be Timmy can answer that more accurately, but may be 6 or 7 builds back it was working.

**Comment by tuomas2** [comment]
Then I believe it is my regression, not his.

**Comment by bvahedy** [comment]
Not trying to blame anyone 🙄, just saying it was working before.

**Comment by tuomas2** [comment]
Is this still broken?

**Comment by tuomas2** [comment]
Seems to work for me

**Comment by tuomas2** [comment]
Please re-open if still occurs.

**Comment by timbze** [comment]
This issue still exists. It only happens when there is no active reading plan, like on new install
