### ISSUE TITLE
Chapter loads twice 

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2011]
Maybe related: #1998 

> I can reliably reproduce this bug under certain circumstances
> 
> Bug: The same chapter loads twice
> 
> 
> To reproduce:
> Open AndBible to a book of the Bible and go to any chapter (e.g. Revelation 1)
> Go to Reading Plans and find a day that has a passage that is in the same book, but at least two chapters ahead (e.g.1 year NT+OT Day 365 has Revelation 22)
> On the reading plan screen, click "Speak" next to the passage that is the same book as your current workspace (e.g. Click "Speak" next to Revelation 22).
> Then click "Passage" next to the same book as your current workspace (e.g. Click "Passage" next to Revelation 22).
> Scroll down to next chapter
> 
> Expected:
> 
> Chapter loads only once
> 
> Actual:
> Chapter will have loaded a second time.

https://support.andbible.org/scp/tickets.php?id=1150

Edit by TB: It's very easy to reproduce like this
1. Open 2 synced windows at 2Cor 10 for example (that's where I reproduced just now)
2. Download a document in "Download document" screen
3. Go back to Bible screen and scroll down, where chapter 11 should start it loads chapter 10 once more

**Comment by timbze** [comment]
I guess there's a possibility that #300 would fix this

**Comment by tuomas2** [comment]
Yes - or it might "hide" this bug so that it is not possible to be reproduced so easily.. 
This bug could be actually unrelated to tts / reading plans but we are lucky to have steps to reproduce this.

**Comment by timbze** [comment]
Chapter and other content is duplicated after document deletion
https://support.andbible.org/scp/tickets.php?id=1535

**Comment by timbze** [comment]
Made edit to OP, another easy way to reproduce this bug

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=1555

**Comment by tuomas2** [comment]
> Could be. I was reading and using the strong's numbers links to open the definitions. Then hiding the strong's definitions when ready.
