### ISSUE TITLE
Issue with links window content (Strongs) not updating

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2013]
https://support.andbible.org/scp/tickets.php?id=1158

**Comment by tuomas2** [comment]
> The reference panel (right side) doesn't render subsequent results. The code is transferred but the previous results remain. I've shut down the app and rebooted the device yet the problem persists. 
> 
> Of note also, this reference panel keeps track of the unseen (newly referenced) document's sections as presented in the upper left document tracker/indicator when scrolled through even though it be showing the results of the first document to be referenced.
> 
> Interestingly, dismissing the reference panel, disabling the reference markup and shutting down the app clears the problem on restart.

**Comment by tuomas2** [comment]
Another person has similar sounding issue:

> Ok some new info. when i first open the app and use strongs it works great, but when i close the strongs window and use it again it stays on my last strongs number from before closing the window and if i choose other strongs numbers it just stays on the last one chosen.

>  Im sorry Ben i need to explain better,
> here are the steps
> 
> 1 in "Application preferences", i have the "Links window" set
> 2 In "All Text Options" I have Strongs numbers  set to "Text and Links"
> 3 I have the Strongs in the numbers mode not the dots mode
> 4 When i first use the app I click on a Strongs number and it shows in a separate links window the correct number  i choose another Strongs number and it switches to that new number i can keep doing this without a problem, so  it works like it should
> 5 But once i close that linked window and go back to clicking on a Strongs number and it opens a new link window it shows the very last Strongs number i clicked in the previous session (the window i just closed) its like it won't refresh the new window no matter how many Strongs numbers i click it stays on that same number
> 6 Now i can go back to "Application preferences", and turn off the "Links window" setting then it works fine by giving me a whole new window but i have to toggle back and forth between windows instead of both on the same screen with 2 separate windows.
> 
> I have tried various combinations with "Window pinning" on/off
> and syncronization on/off, and Strongs numbers choices "Off",  "Links" "Text and Links"  it doesn't make a difference.
> 

https://support.andbible.org/scp/tickets.php?id=1162
Also here: https://support.andbible.org/scp/tickets.php?id=1167

**Comment by tuomas2** [comment]
Looks like same issue here 
https://support.andbible.org/scp/tickets.php?id=1171
https://support.andbible.org/scp/tickets.php?id=1173

> Using multiple workspaces with KJV with Strong and Robinson. Two linked windows and synced. One window for KJV, the other for commentaries. When number codes displayed the first number selection works OK, but subsequent number selections repeat the original number not the one selected in the pop up multiple window.

**Comment by RnRJohnny** [comment]
Indeed, closing the links window and selecting another reference produces the problem.
Should the links mode select icon appear in the toolbar while the links (reference panel) has focus? It's a do nothing tool.

**Comment by tuomas2** [comment]
Can't reproduce with my devices yet.

**Comment by tuomas2** [comment]
Can reproduce on android 5 tablet

**Comment by tuomas2** [comment]
Looks like regression of #1973 fix
