### ISSUE TITLE
Page too large to open

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2020]
https://support.andbible.org/scp/tickets.php?id=1172

1. Opened app
2. After a while, It all went blank with a notification that the page is too large to load

**Comment by tuomas2** [comment]
Asked some details from user

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=1175 and
https://support.andbible.org/scp/tickets.php?id=1176

**Comment by tuomas2** [comment]
issue_2020.db saved locally

**Comment by tuomas2** [comment]
> I have been working on Jonah 1 and 2. I also worked on 2 kings 22 and a few others but these 3 passages have been giving me problems with reports of page being too large to load.

**Comment by tuomas2** [comment]
Again: https://support.andbible.org/scp/tickets.php?id=1313

I guess we should increase the limit.

**Comment by tuomas2** [comment]
Or it is also possible that "page" has something it is not supposed to have. But I would first maybe double the limits.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=1445

**Comment by timbze** [comment]
Is there possibly any somewhat easy way to load smaller chunks at a time?

TDavid Ps 119 commentary can not load at all because it says "too large". (it was missing altogether but is fixed in Crosswire beta)

**Comment by tuomas2** [comment]
I can remove the limit, then it loads but it can be slow if document is big. Slowness comes from webview handling huge doc so we can't do much about it.

**Comment by tuomas2** [comment]
decided to make it larger again (4x this time).
