### ISSUE TITLE
search suggestions

### ISSUE THREAD

**Issue by luke-2136** [AndBible/and-bible#2022]
New user here again. Enjoying the app. Thank you. Just a few things regarding search might be nice thought i might put out there:

1. an 'x' to clear the last search term from the search bar would be helpful

2. perhaps an option for user preference to highlight the search word in the search results

3. also the text is very small on the search results - not the book/chapter reference which is larger - but the text of the actual verse is small. Perhaps font-size on that could be an option also.

4. Last would be if the number of search results returned could be shown somewhere as part of the search results also. That would also be nice, and very helpful.

Hope that's not too much for the new guy - thanks.

**Comment by agrogers** [comment]
Hi Luke

Thanks for contributing your thoughts:
1. Is done already and awaiting inclusion in a future release (#2004)
2. Also done in #1953 
3. Added a separate task for this #2024 
4. Also done in #1946 

There is a full list of suggestions here: https://github.com/AndBible/and-bible/issues/186

If you have more ideas, feel free to create a separate feature request for each idea and I will add it to the list.

**Comment by luke-2136** [comment]
Thanks .. 

re: more ideas - ok will do

**Comment by tuomas2** [comment]
This can be closed @agrogers ?
