### ISSUE TITLE
Floating New Window Tile

### ISSUE THREAD

**Issue by mattzab** [AndBible/and-bible#203]
The floating new window tile sometimes covers text, and seems generally in the way unnecessarily.

+Possible solution would be to change the long press action on the document selector. Instead of long press allowing a document change, it could open the document in a new window.

**Comment by tuomas2** [comment]
My idea is that fullscreen mode would be used primarily for reading. There are no interrupting overlays. I am working on an improvement to full screen mode.

**Comment by mattzab** [comment]
Is there any way it could be made into a non interrupting overlay even when not in full screen?

**Comment by tuomas2** [comment]
with right margin perhaps yes. Please let me know if you have some other ideas.

**Comment by mattzab** [comment]
Maybe instead of a long press on the document abbreviation, a gesture-based down swipe to open the window could eliminate the need for the overlay and provide a cleaner interface.

That would also allow users to open a document in a new window with one swipe gesture, rather than the 4 taps that are currently required.

**Comment by tuomas2** [comment]
Hidden gestures  and long presses can't be the main way to use this kind of important features. UI ( for most important parts) should be so intuitive that's no user manual is required to use it.

**Comment by tuomas2** [comment]
Fixed in build 275
