### ISSUE TITLE
Content not loading in Gill commentary for some verses

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2031]
https://support.andbible.org/scp/tickets.php?id=1184

**Describe the bug**
Ezekiel 28:14, 16, 18, 19 are all not loading in Gill commentary. Nothing changes in commentary window on those verses.

Tested in Xiphos and there they work

**Bug was found on And Bible version**
Build 629

```
01-02 06:57:21.793  9972  9972 I BibleView[46]: bibleview-js: ERROR Error caught Script error. on :0
01-02 06:57:21.793  9972  9972 I BibleView[46]: bibleview-js: ERROR Uncaught SyntaxError: Invalid or unexpected token
```

**Comment by timbze** [comment]
Maybe #2028 is the same bug. When initial window load is one of the verses that doesn't work it just shows the loading spinner and never stops until selecting another verse.

**Comment by tuomas2** [comment]
My guess for culprit is this 22aec403b062a6a4893f838571f81a709027b837 & ec1e521b3abff35c55960d858a2af7fbf5489b1c (#2000)

**Comment by tuomas2** [comment]
Fixed in 630
