### ISSUE TITLE
Window sync issue with max mode

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2036]
I think the test probably fails cause of this issue.

1. Have 2 windows synced
2. Maximize window 2 and swipe to go to next verse or chapter
3. Unmaximize and you'll see window 1 did not change

_Originally posted by @timbze in https://github.com/AndBible/and-bible/issues/1991#issuecomment-1006478590_

**Comment by tuomas2** [comment]
@timbze so this issue exists in build 630?

**Comment by timbze** [comment]
> @timbze so this issue exists in build 630?

Yes

**Comment by bvahedy** [comment]
I can also duplicate this in 630.

It should sync when either window is tapped to restore back to normal. Because this issue exist if either window is maximized and changed to a different verse.

**Comment by tuomas2** [comment]
Tested on build 620, and same issue exists there, so this is actually older issue.
