### ISSUE TITLE
blank screen no books can be displayed

### ISSUE THREAD

**Issue by howdev** [AndBible/and-bible#2037]
**Describe the bug**
books downloaded. cannot be displayed. all blank

**Bug was found on And Bible version**
All of 4.x starting from build 601. 601 crashes and does not open. newer builds opens but blank

**To Reproduce**
1. download production-601 from github
2. install and open
3. download documents, KJV
4. choose any book

**Expected behavior**
displays the book you chosen with verse numbers and text

**Screenshots**
![S20107-145500](https://user-images.githubusercontent.com/17158780/148478973-7085be1e-0116-42cd-bace-4ca718277a11.jpg)

**Smartphone (please complete the following information):**
 - Device: Meizu M3s
 - OS: 5.1

**Additional context**
when you choose backup module, does not backup, shows crash message "

**Comment by bvahedy** [comment]
This may be related to Android 5 OS issues.

**Comment by tuomas2** [comment]
blank screen is indication of incompatible old webview version. webview should be updated.

**Comment by tuomas2** [comment]
Can you try to update Webview? Or in some devices, you must update Google Chrome. 
If this is not possible, you can still use older (3.3) version.

**Comment by howdev** [comment]
installed the webview from playstore, now I see two webviews in the installed apps, but it still uses the system's webview. I have to go back to 3.3
