### ISSUE TITLE
Show rationale for PHONE_STATE_READ_REQUEST on android 12+

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2047]
Requires new string: "This permission is needed in order to be able to pause speaking if you receive a phone call".
Use `shouldShowRequestPermissionRationale`.

**Comment by tuomas2** [comment]
Related to: #1992

**Comment by tuomas2** [comment]
Perhaps I could add untranslated english string already there... better than nothing I guess.

**Comment by agrogers** [comment]
Yes, i think so.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
I added string and pushed it to transifex also. Most diligent translators will probably translate it soon. But not going to push them because of this.

**Comment by RuggMatt** [comment]
I think you could use audio state to avoid having to get phone permissions

See https://medium.com/google-developers/how-to-properly-handle-audio-interruptions-3a13540d18fa

> While older versions of Android required developers to rely on a PhoneStateListener as a signal for pausing playback during phone calls, this all changed in Lollipop. On Lollipop+ devices, the state of the phone is properly integrated into the audio focus state and your app will receive AUDIOFOCUS_LOSS_TRANSIENT when the call starts and AUDIOFOCUS_GAIN when it ends. One less API to get right!

> For what it’s worth, as of Android 6.0, LISTEN_CALL_STATE doesn’t require the READ_PHONE_STATE permission anymore, which is good. But several of the other telephony options do, and you don’t want to risk poorly-written code asking your user for phone permissions when all it wants is to pause some music. That’s creepy.
