### ISSUE TITLE
Errors in the Arabic Bible , SVD version

### ISSUE THREAD

**Issue by myway880** [AndBible/and-bible#2051]
I'm not sure if I'm supposed to fill this with you're app or some one else please let me know if I should do this with a deferent repo
There is multiple errors 
“وَأَمَّا أَنْتُمْ فَالْمَسْحَةُ الَّتِي أَخَذْتُمُوهَا مِنْهُ ثَابِتَةٌ فِيكُمْ، وَلاَ حَاجَةَ بِكُمْ إِلَى أَنْ يُعَلِّمَكُمْ أَحَدٌ، بَلْ كَمَا تُعَلِّمُكُمْ هذِهِ الْمَسْحَةُ عَيْنُهَا عَنْ كُلِّ شَيْءٍ، وَهِيَ حَق÷ وَلَيْسَتْ كَذِبًا. كَمَا عَلَّمَتْكُمْ تَثْبُتُونَ فِيهِ...” (يوحنا الأولى 2:27, SVD)
This "÷" characters shouldn't be there it occurred elsewhere as will I just can't remember where..
Also
“...سِمْعَانُ بُطْرُسُ عَبْدُ يَسُوعَ الْمَسِيحِ وَرَسُولُهُ، إِلَى الَّذِينَ نَالُوا مَعَنَا إِيمَانًا ثَمِينًا مُسَاوِيًا لَنَا، بِبِرِّ إِلهِنَا وَالْمُخَلِّصِ يَسُوعَ الْمَسِيحِ: P Pلِتَكْثُرْ لَكُمُ النِّعْمَةُ وَالسَّلاَمُ بِمَعْرِفَةِ اللهِ وَيَسُوعَ رَبِّنَا. P Pكَمَا...” (بطرس الثانية 1:1-3, SVD)
The P letter around the verse numbers is not supposed to be there

**Comment by agrogers** [comment]
Hi 

Thanks for contacting us. This looks like an encoding issue which we don't manage. Some info on who you could alert can be found here: https://github.com/AndBible/and-bible/wiki/FAQ#i-found-text-issue-in-one-of-the-bible--commentary-etc-modules-in-and-bible 

Thanks
Andrew

**Comment by tuomas2** [comment]
Reported this further: https://tracker.crosswire.org/browse/MOD-430. You could report further SVD issues there directly.
