### ISSUE TITLE
Marker only bookmark style option for labels

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2053]
there must be ticket for this already but could not find

**Comment by agrogers** [comment]
I think this is not a bad idea. I don't think i would use it but i can imagine others would. The functionality is already there I think, isn't it?

**Comment by tuomas2** [comment]
I would love to use this for sermon note bookmarks. They are filling my bible...

**Comment by tuomas2** [comment]
Yes this is easy to implement.

**Comment by agrogers** [comment]
Likewise for sermon Notes. I make those labels light gray and then also
hide them from the workspace.

This is related to my suggestion to categorise labels so ones like these
could be dealt with more easily at a higher level.

**Comment by tuomas2** [comment]
Implemented in fa902f2

**Comment by agrogers** [comment]
Great. I am looking forward to trying it out.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
