### ISSUE TITLE
Issues with requesting phone permission on Android 12

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2054]
**Describe the bug**
1. The permission request only shows once. If I click "Don't allow" the screen never comes up again. It's maybe good that it doesn't always show up, but if not then there needs to be an option somewhere to press to enable the permission.
- Of note, Android 12 also automatically revokes permission after some time if the feature is not used, so if state is allowed needs to be checked always
2. The permission request shows up but speak is already starting. It would be better to only start speaking after request is answered.
3. The permission request does not show the rationale that was implemented in #2047
- It only shows this: ![image](https://user-images.githubusercontent.com/35117769/149676257-44994285-5728-4f55-9fc6-c175307f32bc.png)

From #2047

**Bug was found on And Bible version**
Build 631 alpha #b16bde7

Tested on Pixel 3 with Android 12

**Comment by timbze** [comment]
Irrelevant after #2056

**Comment by tuomas2** [comment]
^ commit should be towards #2053 (typo)
