### ISSUE TITLE
Speak does not pause properly when call comes in on Android 12

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2055]
**Describe the bug**
Speak does not pause correctly when call comes in on Android 12.

Here's what it seems to be doing:
1. Speaking v1, call comes in and speak is quiet 
2. After a short time v2 starts speaking even while call is still ringing, but it's quieter now cause I guess Android is sharing the ringer volume and speak volume 

Related: #1992

https://support.andbible.org/scp/tickets.php?id=1220

**Bug was found on And Bible version**
Build 631 alpha #b16bde7

Tested on Pixel 3 with Android 12

**Comment by tuomas2** [comment]
1. are you using standard phone calls, not whatsapp etc?
2. Did it ask you to enable permission, and did you enable it?

**Comment by timbze** [comment]
1. Yes, standard calls
2. It asked once when I did not enable, but I went to system settings > Apps and enabled the permission before testing

**Comment by timbze** [comment]
Seems to work perfectly after #2056
