### ISSUE TITLE
Allow setting the label style at the bookmark level 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#2057]
At present we can choose to show either an underline or a highlight bookmark per label. Hoever sometimes i want to show an underline style most of the time but for some particular verses i would like to use the highlight style.

It would be nice to be able to override the default at the bookmark level

Adding an extra option into the Bookmark Info dialog would be where i would put it.

**Comment by tuomas2** [comment]
Not sure if I support this idea. I think it's better to create labels for this purpose and just change primary label.

**Comment by bvahedy** [comment]
I agree with Toumas on this one.

**Comment by agrogers** [comment]
Creating separate labels would definitely defeat the purpose - I want to
keep the topic together not fragment it.

It would be an underused feature - I don't even need it that much.

I shall think about it more.

**Comment by tuomas2** [comment]
I'll close this for now
