### ISSUE TITLE
Check if app works on Windows 11 

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2059]
https://support.andbible.org/scp/tickets.php?id=1219

**Comment by RuggMatt** [comment]
I managed to get it installed. 

![image](https://user-images.githubusercontent.com/8870594/150653095-088c5622-f8d4-4493-b177-f6d4a0f59df1.png)
If I made window really wide, text only goes so far across the screen. I think this is ok because it can be hard to read a long line of text across the screen, but it should at least be centred.

**Comment by agrogers** [comment]
That's great. How well did it run? Was it fast or noticeably sluggish? Any
weird glitches?

**Comment by tuomas2** [comment]
> If I made window really wide, text only goes so far across the screen. I think this is ok because it can be hard to read a long line of text across the screen, but it should at least be centred.

Oh, that is due to default margin settings that were changed due to recent PR (#1942). It will be centered if margins are set to 0 and text width is certain.

**Comment by timbze** [comment]
> I managed to get it installed.

I think multiple people have asked how to do it, would you be able to write up how it's done? I assume it won't be too hard but have not looked into how Win 11 does it yet either.

**Comment by bvahedy** [comment]
May be create a section here for instruction for win 11:
https://andbible.readthedocs.io/en/latest/documents.html#dictionaries

**Comment by agrogers** [comment]
Or send the instructions to Ben or I and he e can add them to the
documentation ourselves.

**Comment by RuggMatt** [comment]
# Any Windows 11

Still quite technical if you are outside the US or not on Windows 11 beta. It involves downloading the Windows Subsystem for Android (WSA), running a command to install it, starting Windows Subsystem for Android, enabling developer mode, downloading the apk from GitHub releases, and installing the app with adb.

1. Install WSA following these instructions https://www.xda-developers.com/how-to-run-android-apps-on-any-windows-11-pc/
2. Set up adb https://www.xda-developers.com/install-adb-windows-macos-linux/
3. Download the APK from GitHub releases https://github.com/AndBible/and-bible/releases/latest
4. How to sideload apps on WSA https://www.xda-developers.com/how-to-sideload-android-apps-on-windows-11/

# Windows 11 Beta in the US

Inside the US on Windows 11 Beta, it should be as easy as [downloading the Windows Subsystem for Android with Amazon Appstore from Microsoft Store](https://www.microsoft.com/en-ca/p/windows-subsystem-for-android/9p3395vx91nr?activetab=pivot:regionofsystemrequirementstab) and then searching for the app on the amazon app store. I am not in the US so cannot test this.

**Comment by RuggMatt** [comment]
Actually looks like only small selection of apps available on Amazon appstore to begin with
https://www.xda-developers.com/amazon-appstore-windows-11-small-selection-android-apps/

**Comment by timbze** [comment]
Thank you for the information @mattschlosser

**Comment by bvahedy** [comment]
I've added Matt's instruction here:
https://andbible.readthedocs.io/en/latest/documents.html#windows-11-setup

**Comment by agrogers** [comment]
Thanks for that.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Thank you for testing and documenting this!
