### ISSUE TITLE
Speak toolbar in landscape mode....

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#206]
When in play mode, the speak buttons toolbar is not all the way at the bottom of the screen in landscape mode.

**Comment by tuomas2** [comment]
Yep, I forgot to test landscape mode. I'll fix to next release. Thanks!

**Comment by bvahedy** [comment]
No problem, you already have a lot on your plate.

**Comment by tuomas2** [comment]
Fixed in build 275
