### ISSUE TITLE
Reading plans: can't change between current day

### ISSUE THREAD

**Issue by RuggMatt** [AndBible/and-bible#2064]
**Describe the bug**
There is no option to change between current day of reading plan. There used to be. 

**Bug was found on And Bible version**
Build 4.0.633

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Reading plans
2. select a reading plan
3. There is no option to change between the currently selected reading plan day.

**Comment by timbze** [comment]
It looks like the toolbar changed, I don't recall working on that, but will have to check where/how that happened.

Before it was the custom toolbar where you could tap to change reading plan, reading plan day, or go to Bible and/or commentary

**Comment by timbze** [comment]
Basically same issue as #2063, toolbar got changed

**Comment by timbze** [comment]
Maybe 1bbf16cb by @tuomas2?

**Comment by RuggMatt** [comment]
Reverting 1bbf16c brings back all the options. 👍.

**Comment by RuggMatt** [comment]
Closed by #2065
