### ISSUE TITLE
Add Epiphany maps and remove Smith Bible maps from recommended list 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#2066]
Epiphany has quite a good set of maps. Resolution is good and they are well laid out.

Smiths are at quite a low resolution and are fairly unreadable when zoomed in.

**Comment by tuomas2** [comment]
Should we remove Smith Bible maps from recommended list anyway (even if nobody creates Epiphany maps module?)?

**Comment by agrogers** [comment]
Yeah, i think Epiphany looks better.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
ah I thought epiphany does not yet exist as a module, sorry.

**Comment by tuomas2** [comment]
Done

**Comment by tuomas2** [comment]
Would have been done faster if I knew that Epiphany module is already there... :-P
