### ISSUE TITLE
Make it possible to jump to a certain day within a reading plan (e.g. after migrating to a new phone)

### ISSUE THREAD

**Issue by HinzundKunz** [AndBible/and-bible#2101]
I'm in the middle of a reading plan (chronologically through the Bible), and I would like to migrate to another phone (tablet in my case), but I would have to start from day one on the new phone. I would like to be able to jump to a specific day and continue from there.

**Comment by timbze** [comment]
Hi @HinzundKunz, you can do that by going to the day you want to start at; tap "Day #" on the top bar and select the day. And then tap the 3-dot menu on top right and select "Set as current day". In the same menu you can also "Set start date" if you would like for the date to match up with what you had before.

**Comment by HinzundKunz** [comment]
Awesome, thank you very much!
