### ISSUE TITLE
Cross reference suggestions

### ISSUE THREAD

**Issue by mhancock4Christ** [AndBible/and-bible#2102]
Hello, I've been using this app for some years and really enjoying it, thanks. Many print Bibles have a cross reference section. Is it possible to add this to And Bible?

Thanks!

**Comment by agrogers** [comment]
Hi 
Have you tried using the TSK commentaries? That is an excellent cross reference module.
Thanks
Andrew

**Comment by timbze** [comment]
Andrew is right, I would also add you can get a lot of cross references in the NASB module. Make sure cross references enabled and then press the letters and numbers within the text for the cross references

**Comment by mhancock4Christ** [comment]
Thank you both, I wasn't aware of this functionality!
“...For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.” (Joh 3:16, KJV)

Feb 18, 2022 9:31:05 PM Timmy Braun ***@***.***>:
