### ISSUE TITLE
Slow interface + Compare window does not sync properly

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2112]

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=1319

also weird slowness when moving from verse to verse 
https://support.andbible.org/scp/tickets.php?id=1320

and compare content was loaded twice
https://support.andbible.org/scp/tickets.php?id=1321

**Comment by tuomas2** [comment]
Log file shows that there have been some issues with closing resources. Might be related to #2114 because device has some MyBible modules installed. I have paid some attention to releasing resources, so let's see if this is fixed...

```
03-02 20:44:08.203  9426 14774 W System  : A resource failed to call close. 
03-02 20:44:08.203  9426 14774 W System  : A resource failed to call close. 
03-02 20:44:08.203  9426 14774 W System  : A resource failed to call close. 
...
```

**Comment by tuomas2** [comment]
after restarting app, sync was working OK

**Comment by BryceSteuer** [comment]
[Log for issue of commentary/Bible together in window](https://github.com/AndBible/and-bible/files/8191360/logcat.txt.gz)
Note the Bible text is displayed above the commentary text. It is the same chapter displayed over and over infinitely as you scroll up
![image](https://user-images.githubusercontent.com/48736452/156898306-2199a2b4-6abe-412a-9556-69ee987ee8af.png)

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=1705

> I think this is the same as https://github.com/AndBible/and-bible/issues/2112
> 
> It's not slow, but syncing with a compare window only works one way. If I split the window and scroll through a bible doc, the compare window refreshes but doesn't change verses. However, if I swipe left/right on the compare window, the Bible docs sync correctly.

**Comment by tuomas2** [comment]
Assuming this is duplicate of #2442 and closing
