### ISSUE TITLE
Date-based reading plan not working with zip module

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2116]
Issue exists in 640-alpha for sure, not sure which version the user was trying.

https://support.andbible.org/scp/tickets.php?id=1322

**Comment by tuomas2** [comment]
Is this related to alpha builds or production builds too?

**Comment by timbze** [comment]
My guess is production too but have not checked yet

**Comment by timbze** [comment]
Actually it's not a bug. I missed adding instructions for date-based plans for zip format to the wiki...

**Comment by timbze** [comment]
Updated wiki now
