### ISSUE TITLE
Speech stops after couple of minutes when "Speak from all windows" option is enabled

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#212]
Speech stops after couple of minutes. It's not continuous. 

Also,  when an English translation is open with a hebrew translation, the synthesizer speaks extra dots and dashes.

**Comment by tuomas2** [comment]
I could reproduce this when "speak from all windows" option is enabled.

Related / duplicate: #199

**Comment by tuomas2** [comment]
Fixed in build 276

**Comment by tuomas2** [comment]
Removed "speak from all windows" feature
