### ISSUE TITLE
Bad formatting in documentation

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2127]
Links need fixing etc: https://andbible.readthedocs.io/en/latest/getting_started.html

**Comment by tuomas2** [comment]
@AndBible/documentation

**Comment by thebiblelover7** [comment]
@tuomas2 Is that good now? I think it is now fixed by the latest commit. I suggest this be closed now. Sorry for the late fix.

**Comment by tuomas2** [comment]
Looks good now, didn't find anything worth complaining
