### ISSUE TITLE
footnotes renumber on scroll and text reflows

### ISSUE THREAD

**Issue by loosestrife** [AndBible/and-bible#2128]
**Describe the bug**
deep in Ez footnote letter change every time i scroll also because footnotes are variable width the entire text reflows so i lose my place

**Bug was found on And Bible version**
last updated march 3 2022 version and build number are hidden from the user

**To Reproduce**
touch a verse to highlight it or scroll a bit in a footnote rich chapter.  idk just decide on the footnote letter and flow of the text once and cache it for each chapter and the one before and after but i don't know how the code really works

![Screenshot_20220313-113830_Bible Study](https://user-images.githubusercontent.com/95635809/158071582-489b7060-ec67-433d-ac5e-f56cb6092cc3.jpg)
![Screenshot_20220313-113847_Bible Study](https://user-images.githubusercontent.com/95635809/158071587-20ca6545-a454-454d-a6db-921157b1bab9.jpg)

**Comment by tuomas2** [comment]
Build number is visible in Main Menu -> Help & Tips (bottom of the page)

**Comment by tuomas2** [comment]
Reproduce:
1. Open Ez 27:26 and note footnote marker: it is "q"
2. Open Ez 26:1
3. Restart app (or switch to other workspace and back)
4. Scroll down from Ez 26:1 to Ez:27:26 and note that footnote marker is "w"

**Comment by tuomas2** [comment]
This is a bit tricky because KJV module does not provide footnote marker, but we need to generate it in Note.vue. Perhaps we should "seed" it from chapter number so that it would be more deterministic.
