### ISSUE TITLE
Back arrow in book/chapter selection....

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#214]
Causes the book/chapter not to change reported by: 

Darryl Trimming	

8:18 PM (21 minutes ago)

You're in book1. Select a new book (book2). But before selecting a chapter, you realise you made a mistake. So go back to books and select the correct book (book3). Then select a chapter from this book. Instead of the chapter in book3, you end up where you started, in book1.

**Comment by tuomas2** [comment]
Fixed in 095c48d3e8b30a84b6f6d04abbd63afc87ed8b1d (removed "up button" from these views. It does not semantically make sense to use it here. Back button should be used instead).
