### ISSUE TITLE
Speak failure

### ISSUE THREAD

**Issue by Noitarud** [AndBible/and-bible#2143]
When I first used app on new tablet I did try the Speak feature, functioned. However of late I get message 'an error has occurred'.

Actions:
- (Make sure Bible window active)
- Press headphones (State: - Stopped -)
- I press play (no sound, State: Exodus 8:10 15% KJV )
- I press pause ('Pause' popup, State: Exodus 8:10 15% KJV )
- I press play (Screen dims with foreground central message 'an error has occured')

Also, I read another bug report you want a log, you say 'on the menu press bug report'
- I press as you said (screen dims with foreground central message 'Please wait…')
- Drawer appears at bottom and has text 'no apps can perform this action'
(I do have text file editors on this tablet and they do open files when I tell to in any file manager)

**Bug was found on And Bible version**
V 4.0.614

**Smartphone (please complete the following information):**
 - Device: Lenovo TB-X505F
 - OS: Android
 - Version:10

**Comment by tuomas2** [comment]
I guess this is related: https://support.andbible.org/scp/tickets.php?id=1357

**Comment by tuomas2** [comment]
Can you make a bug report also via Main menu > report a bug, after this issue takes place. I think logcat file might reveal something useful.

**Comment by Noitarud** [comment]
URL requires password (no guest access)

Mainmenu/FeedbackBugReport also fails as already described (see second group of •s), alternatively it might (rare) stay showing the irritating ring until I turn off the WiFi, but usually goes straight to the empty drawer. I have four+ text editors on tablet… reinstalling might wipe the problems (I can drop in a file if you want to patch that issue, allow me to put the log on the clipboard or something)

I cannot locate this 'logcat', can you hint where on the system I might be able to find it?

 Image of the empty drawer. NG has recorded it had an internet request to GitHub when app was disallowed in the past (however cannot repeat it), it is able to download resources.
![Screenshot_20220426-191338](https://user-images.githubusercontent.com/98794719/165266859-2ffe17ac-0273-415c-a368-2e20e71dbda9.png)

**Comment by tuomas2** [comment]
> URL requires password (no guest access)

That is ok, URL is for AB team only.

> Mainmenu/FeedbackBugReport also fails as already described (see second group of •s), alternatively it might (rare) stay showing the irritating ring until I turn off the WiFi, but usually goes straight to the empty drawer. I have four+ text editors on tablet… reinstalling might wipe the problems (I can drop in a file if you want to patch that issue, allow me to put the log on the clipboard or something)

Do you have email application like Gmail installed? Bug report feature generates report and offers user to send it via email to us.

> I cannot locate this 'logcat', can you hint where on the system I might be able to find it?

Logcat is generated via "report bug" feature and added as an attachment to email.

**Comment by Noitarud** [comment]
I'm no fan of Google. I did install k-9 mail(and I do not use it), apparently it has not alerted android or not have such association at all.

**Comment by tuomas2** [comment]
BTW can you try latest version, there are some speak-related changes https://github.com/AndBible/and-bible/releases/tag/production-648

**Comment by Noitarud** [comment]
@tuomas2 For some reason began working (I might have installed an acceptable program), I got a grey screens with two cyan title bars (save as, /storage/emulated/0) for saving. If you see the program it launched maybe you can recommend it.

GitHub does not want WEBP files.
[logcat.txt.gz](https://github.com/AndBible/and-bible/files/9109134/logcat.txt.gz)

I did not (quite) do it in the order I said above (prior: also see if you can see the error "1 Corinthians 11:20-29 was not found in document KJV.", it will display the second scripture if switching to the workspace but not if selecting from studypad, only first scripture)

(I had not updated though I tried to just previous, Fdroid gave file not found error)

**Comment by Noitarud** [comment]
@tuomas2 (so I can close this) do you see anything significant in there? Can you see how using the 'report bug' failed?

**Comment by tuomas2** [comment]
My guess is that you do not have any speech synthesis app installed (like Google Speech Services or similar from Samsung or from other vendor). 

This is what we recommend: https://play.google.com/store/apps/details?id=com.google.android.tts

**Comment by Noitarud** [comment]
Uh, it was working, now not, and still not after reinstall.
Why did you guess? I supplied the log. Did not read?

**Comment by tuomas2** [comment]
My guess was based on reading the log file: 
```
07-14 16:04:17.053 13455 13455 D Speak   : Clearing Persisted Pause state
07-14 16:04:17.053 13455 13455 D Speak   : mTts was null so initialising Tts
07-14 16:04:17.054 13455 13455 D Speak   : Tts initialised
07-14 16:04:17.054 13455 13455 D Speak   : Tts initialisation failed
07-14 16:04:17.055 13455 13455 D Dialogs : showErrorMesage message:An error has occurred
```

So you got it working at some point but it stopped working again?

**Comment by Noitarud** [comment]
I discovered i had disabled some google things (google play services/accessibility suite) which in turn caused the only option in the speech Preferred Engine list to be removed. Installing new engine (called eSpeak) fixes it.

I will leave the issue open in case you want to make the error less ambiguous, though error received may be too ambiguous to report specificly, so maybe an adequate message should be "Speech failed, check your speech engines".

**Comment by tuomas2** [comment]
Created issue about that (#2450)

**Comment by Noitarud** [comment]
This is an update to the "empty drawer" problem. The program I happened to install that gave me access to the logcat was "Primitive ftpd", apparently an accessory feature.
