### ISSUE TITLE
Make a Contributor Guide

### ISSUE THREAD

**Issue by gelafin** [AndBible/and-bible#2146]
**Is your feature request related to a problem? Please describe.**
I spent a while looking for a contributor guide and eventually found this note at the bottom of the github.io site.
![image](https://user-images.githubusercontent.com/46856925/162845102-306a17c6-b80d-4f56-bb0f-44add5ed9c87.png)

My first search followed this path: this repo's readme > found the developers section of the readme and clicked the link to the developer documentation page of the Wiki > give up when I see How to Contribute Code without seeing a contributor guide. Luckily, I'm taking a class that gives me an excuse to analyze an open source project further, so I persisted later.

**Describe the solution you'd like**
I suggest adding a contributor guide, similar to [the React contributing guide](https://github.com/facebook/react#contributing-guide), even if it only contains that one short paragraph from the github.io site. Ideally, this would be implemented as a new .md file, so it's easy to maintain, lives in this repo where the devs are, and scales better.

**Describe alternatives you've considered**
Alternatively, it could be added as a new section to [the developer page of the Wiki](https://github.com/AndBible/and-bible/wiki/Developer-documentation). This would be easier to manage while the project is small and potentially reduce file clutter (similar existing guides are being kept at the root level of the repo, so maybe a new .md file would have to be added there until a cleanup is scheduled?), at the cost of being a little less modular. 

I recommend resisting the temptation to just put the few words we have now in the developer section of the readme, because it would be easy to forget it's there and could lead to duplication and competing standards. Although, maybe a pull quote or summary of the separate contributing guide could be included, to give people a preview of what to expect (again using React as a reference).

**Additional context**
none

**Comment by gelafin** [comment]
Feel free to mention me and ask that I make the PR for this, if the idea is welcome!

**Comment by gelafin** [comment]
As it happens, I noticed another potential contributor recently looked for a contribution guide to the readthedocs repo: https://github.com/AndBible/docs/issues/3#issuecomment-1092187196. Maybe the contribution guide for this repo could include instructions related to docs and be linked to by the readthedocs readme.

**Comment by agrogers** [comment]
Thanks for the suggestions, @gelafin . Documentation and related things are usually the last thing to get done when there are limited people working on the project. I don't even have enough time to write actual code at the moment.

I wish I had written more down when i first started working on AB. Now I can't remember what I didn't know or found difficult. If you can put something together I don't see any reason why we couldnt include it.

Thanks for your support.

**Comment by gelafin** [comment]
Ok cool, I'll draft one when I have time soon, maybe in the next couple weeks.

**Comment by gelafin** [comment]
All right, here is a draft. I decided that the "How to Contribute Code" section in the Wiki is a fine place after all, since the Wiki could potentially be moved to readthedocs for publishing on the GitHub pages site, and in the meantime, it would be clear enough for slow-orienting folks like me if the readme just linked aggressively to that page.

The current guidance for new contributors has some very nice things going on but is spread across the readme of this repo, the wiki, the readme of the readthedocs repo, and the GitHub Pages site. This proposal organizes contribution guidance in one place, welcoming all types of potential contributors and also explaining the workflow to hopefully lower the barrier to entry for newbies.

I wrote the contributing.md file so it could be a drop-in replacement for https://github.com/AndBible/and-bible/wiki/How-to-contribute if it's in acceptable condition. It's ok with me if you guys decide only to use a small piece of it or nothing, but I do think it would help.

I also wrote whereIsEverything.md so you can consider adding it as a separate Wiki page nested under How to contribute. This type of thing would help people like me get onboarded faster. If both suggested files are accepted into the Wiki, I think it would also be helpful to put a link to whereIsEverything.md in the overview section.

To make things easier, I guessed your preference for some decisions. Some things to be aware of:
- The "Create media" section directs that type of contributor to introduce themselves rather than to find an Issue first. I assumed this is preferred, because it's less likely there will be a lot of Issues open that apply to a non-developer--even if there are a lot of needs, it is hard to remember to make separate well-defined Issues for them to browse, right?
- Sections are ordered by non-technical to technical, then ordered by my best guess of potential popularity.
- Some points from the current contributing guide in the Wiki have been split or merged. For example, the current "helping with documentation and tutorials" point from the Wiki is separated into a user documentation section and "Add to developer docs" for developers. (The user documentation section is titled "Make a how-to guide for a feature"--because I'm guessing all of the user documentation will be how-to feature guides)

For now, this guide would be at least a thorough greeter and a single source of truth for describing AndBible's contribution methods. Suggestions I have for making this new contribution guide even more helpful:
- Foremost, update the readme to reflect all categories of potential contributors, so the project doesn't lose people who aren't listed. I imagine these categories would be useful: "Anyone" (renamed from "Users" and replaced by an invitation to contribute via links to the "Build the community", "Report a bug", "Give feedback or request a new feature" and "Make a how-to guide for a feature" sections), "Developers" (linking to the "Develop for AndBible" and "Add to developer docs" sections), "Graphic designers/videographers", "Translators", "Teachers" (linking to the "Add modules" section). If that's too many sections, maybe at least make an "Other contributors" section linking to the contributing guide.
- Update the GitHub Pages site's Helping section to link to the new contribution guide rather than directly to the Issues and Wiki pages. 
- Move this whole contribution guide to the readthedocs repo and publish it in a new tab on the GitHub Pages site.
- Make a Wiki page with details for contributing tutorials/how-to guides
- Stop using Telegram and Matrix? Or, add consistent references to all chat groups everywhere one of them is mentioned.

If any of those suggestions takes your fancy, go ahead and make an Issue, or ask me to make one.

[contributing.md](https://github.com/AndBible/and-bible/files/8499018/contributing.md)
[whereIsEverything.md](https://github.com/AndBible/and-bible/files/8499019/whereIsEverything.md)

**Comment by agrogers** [comment]
Thanks for this info. I am flying out of Australia for Myanmar tomorrow
night so don't have anytime for a week or so to look at this. If others
haven't done anything before then i will process it. Thanks!

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
> * Stop using Telegram and Matrix? Or, add consistent references to all chat groups everywhere one of them is mentioned.

I think it is nice to have these for common users. We introduced them in 4.0 and they have become somewhat popular since then. Why do you suggest stopping using them?

Added you @gelafin to the AndBible / Documentation team in Github so you can edit WIKI and push to docs repository yourself. If you want to edit anything in [main repository](https://github.com/AndBible/and-bible) or [homepage](https://github.com/AndBible/andbible.github.io), please make a pull request.

**Comment by gelafin** [comment]
@tuomas2 
> > * Stop using Telegram and Matrix? Or, add consistent references to all chat groups everywhere one of them is mentioned.
> 
> I think it is nice to have these for common users. We introduced them in 4.0 and they have become somewhat popular since then. Why do you suggest stopping using them?

Oh, I didn't realize they were being used much! I saw a lot more Google Group links in different places but less often saw those two mentioned (Matrix isn't even in the Discover section of the GitHub Pages site), so I thought they were left over from some time before the Google Group. I couldn't check on them, because Telegram won't let me proceed past this screen (the button doesn't do anything on click):
![image](https://user-images.githubusercontent.com/46856925/163695977-92321a18-9ff5-4f39-a6ab-de36598a2a0f.png)

And Matrix wouldn't let me view the channel until I created an account, which I didn't feel like doing.

But since people are using them, it would be good to add their links to the Build the Community section. Here's the same contributing.md file from before, with those links added in that section.
[contributing.md](https://github.com/AndBible/and-bible/files/8500835/contributing.md)

**Comment by gelafin** [comment]
> Added you @gelafin to the AndBible / Documentation team in Github so you can edit WIKI and push to docs repository yourself. If you want to edit anything in [main repository](https://github.com/AndBible/and-bible) or [homepage](https://github.com/AndBible/andbible.github.io), please make a pull request.

Thanks, that's convenient! I'll implement the above Wiki changes now--is that ok? @tuomas2

**Comment by tuomas2** [comment]
It's okay! Just don't change the main titles in WIKI as they change also the URL (and couple of pages are hard-linked from the app).

**Comment by gelafin** [comment]
@tuomas2 What did you want to do with the Wiki in this repo (https://github.com/AndBible/and-bible/wiki/)? Should that all be moved to https://github.com/AndBible/docs/wiki? I ask because I now have access to edit the AndBible/docs Wiki but not the AndBible/and-bible Wiki.

**Comment by tuomas2** [comment]
@gelafin try again. Added triage permission to documentation team on main repository. Hope it works.

**Comment by gelafin** [comment]
@tuomas2 Thanks, still no luck seeing that Edit button
![image](https://user-images.githubusercontent.com/46856925/163892851-cbe6878b-111d-4d58-a19b-706dd48e1af0.png)

**Comment by tuomas2** [comment]
Okay I figured out that unfortunately triage permission is not enough to edit wiki, needs push permission. That I share a bit more carefully. 

I set up a way to edit docs in docs repository wiki, i.e. https://github.com/AndBible/docs/wiki. There you can edit freely. But please make a request to me to merge changes after you are done to the main repository wiki. You can make request using comment here or a new ticket if this is closed. I'm then doing merge then using git.

**Comment by gelafin** [comment]
@tuomas2 Thanks for setting that up! Looks like we're on the right track. I can edit the Home page at https://github.com/AndBible/docs/wiki but still can't edit other pages, because they all link back to the AndBible/and-bible/wiki pages. Cloning fails with 
<details>
  <summary>"unable to checkout" error</summary>

> $ git clone https://github.com/AndBible/docs.wiki.git andbible-wiki
> Cloning into 'andbible-wiki'...
> remote: Enumerating objects: 895, done.
> remote: Counting objects: 100% (895/895), done.
> remote: Compressing objects: 100% (333/333), done.
> remote: Total 895 (delta 557), reused 895 (delta 557), pack-reused 0
> Receiving objects: 100% (895/895), 144.49 KiB | 468.00 KiB/s, done.
> Resolving deltas: 100% (557/557), done.
> error: invalid path 'Press-release:-Bible-Study-App-version-4.0-has-been-released!.md'
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry with 'git restore --source=HEAD :/'

</details>

**Comment by timbze** [comment]
@gelafin are you on Windows? There's actually an issue with 1 filename that checkout (probably also clone) on Windows fails... #1920

**Comment by gelafin** [comment]
@timbze In fact I am and don't have access to Unix or Apple computers! 🐤 

Thanks for finding the problem with that. Might have to proceed by asking someone with access to update all the links in the AndBible/docs/wiki 

EDIT: this might be useful: https://stackoverflow.com/questions/37346481/how-do-i-find-and-replace-all-occurrences-in-all-files-in-visual-studio-code

**Comment by tuomas2** [comment]
I'm okay with renaming that file by now

**Comment by tuomas2** [comment]
Renamed the file

**Comment by tuomas2** [comment]
> I can edit the Home page at https://github.com/AndBible/docs/wiki but still can't edit other pages, because they all link back to the AndBible/and-bible/wiki pages.

I fixed absolute links so that links from sidebar should work

**Comment by gelafin** [comment]
done: https://github.com/AndBible/docs/wiki/How-to-contribute

@tuomas2 thanks for fixing the links!

**Comment by tuomas2** [comment]
> done: https://github.com/AndBible/docs/wiki/How-to-contribute
> 
> @tuomas2 thanks for fixing the links!

merged to main repo

**Comment by agrogers** [comment]
Looks good. Thank you.
