### ISSUE TITLE
Verse range repeat....

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#218]
@Tuomas2,
Please remove this option from the speak settings since it is disabled.

**Comment by tuomas2** [comment]
I don't understand, please explain.  it's highly requested and useful feature.

**Comment by tuomas2** [comment]
Ah I think now I understand what you mean. I think this 'auto-disable' function might be a bit unclear. It works so that if you start playback outside of the verse range, then it gets automatically disabled.

I think I'll remove that 'auto-disable' feature for now and add it back later in future release, and think better about the toast message.

**Comment by bvahedy** [comment]
Ok, I didn't realize that. I thought you had disabled it. 
Don't really know why anyone would want to repeat the same passage(s) over and over again. But that's just me.

**Comment by tuomas2** [comment]
But good that you raised this because as it is now it could have caused confusion. 

Fixed in 08c4c80920b9a87dc827f036d9f20230f9780e71

**Comment by bvahedy** [comment]
@Tuomas2, can you mod this so that even if you are not in that book or verse and  you setup the range and when you tap play it should jump to that book and verse and starts reading from there.
Any thoughts?

**Comment by tuomas2** [comment]
> So, the ranges you setup are kept in bookmarks if you have auto bookmarking enabled for speech?

Yes, if both auto bookmarking settings in "advanced settings" are ticked.

> @tuomas2, can you mod this so that even if you are not in that book or verse and you setup the range and when you tap play it should jump to that book and verse and starts reading from there.
Any thoughts?

That's what it will do without 'auto-disable' feature. I need to think about that 'auto-disable' one or two more times so that it does not cause confusion and would work as user expects naturally.
