### ISSUE TITLE
Get updated module for older version

### ISSUE THREAD

**Issue by PestoDefender** [AndBible/and-bible#2180]
**FAQ first**

Did you also check FAQ and not find solution there?
https://github.com/AndBible/and-bible/wiki/FAQ

**Describe your problem**
See Bug Issue #1885. I have been notified by the module source that this problem has been fixed. Unfortunately, AndBible has moved on to newer versions which are incompatible with my phone, so I can't update to get the corrected module. Is there a way to install the corrected module in my current AndBible version?

**I'm using And Bible version**
Version 3.3.399#24411f9

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Moto G Play
 - OS: Android
 - Version 6.0.1

**Additional context**

**Comment by tuomas2** [comment]
Why don't you just upgrade the app? Heretics is provided by CrossWire, not by us and they have also provided the updated module.

**Comment by PestoDefender** [comment]
As I said in the request, my phone does not support later versions of the app so I am unable to upgrade. Did I understand your point?

On June 13, 2022 9:45:52 PM PDT, Tuomas Airaksinen ***@***.***> wrote:
|Why don't you just upgrade the app? Heretics is provided by CrossWire,
|not by us and they have also provided the updated module. 
|
|-- 
|Reply to this email directly or view it on GitHub:
|https://github.com/AndBible/and-bible/issues/2180#issuecomment-1154704317
|You are receiving this because you authored the thread.
|
|Message ID: ***@***.***>


Steve Ferrier

**Comment by tuomas2** [comment]
Hmm, Android 6 is still supported. But it does not work for you for some reason?

**Comment by timbze** [comment]
Also, module updates should still be available in older AndBible versions I think? Just go to Download Documents and download the update... Unless Crosswire has not updated their repo yet, then a newer version of AB would not help either
