### ISSUE TITLE
Render <milestone type="line" /> as line or paragraph break

### ISSUE THREAD

**Issue by kpengboy** [AndBible/and-bible#2183]
**Describe the bug**
There are no paragraph breaks displayed in the NETfree or NASB texts, even though these texts originally do have paragraph breaks. When I ran `mod2imp` on the SWORD modules, I noticed that there are one or two `<milestone type="line" />` tags where I expect there to be paragraph breaks. It seems as if And Bible is ignoring all such milestones.

This issue doesn't surface on the engNET2016eb module, which has a different way of indicating paragraph breaks.

**Bug was found on And Bible version**
Version 4.0.648

**To Reproduce**
1. Download NETfree or NASB text
2. Go to Genesis 1 (for example)
3. Notice that the entire chapter is a giant wall of text

**Expected behavior**
In the NETfree, I expect to see pragraph breaks after verses 1, 5, 8, 10, 13, 19, etc. In the NASB I expect to see paragraph breaks after verses 5, 8, 13, etc.

**Screenshots**
| NETfree | NASB | NET (expected) | NASB (expected) |
|-------------|---------|-----------------------|------------------------|
| ![NETfree](https://i.fluffy.cc/tJn8PMkG4R51vTrKHTr6PXZV6HkRJQP2.png) | ![NASB](https://i.fluffy.cc/P275p7vZ81lN3LTzWkcNWggWrdL6SwxV.png) | ![NET (expected)](https://i.fluffy.cc/DwjPJl9Q1xHxLgGqwfh0r4mCZqDrKsvS.png) | ![NASB (expected)](https://i.fluffy.cc/ttRdsrzRtfRSxZ9gdNlmg1klRClPsXCS.png) |

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - OS: Android
 - Version: 12

**Comment by agrogers** [comment]
I think I have noticed that as well. Seems like a good change to me.

**Comment by kpengboy** [comment]
Some more investigation shows that the NETfree also uses `<l />` tags that don't have `sID` or `eID` attributes, so either And Bible needs to be taught how to interpret such markup or the NETfree needs to be fixed to include them (if that is practically possible).

**Comment by tuomas2** [comment]
Now this is a good bug ticket. Fix coming soon.

**Comment by agrogers** [comment]
Did that change catch the L tag as well?

**Comment by tuomas2** [comment]
no, a new ticket with an example can be created

**Comment by agrogers** [comment]
I thought you might have missed the reference to that issue which was also
in this ticket. They seemed like the same problem to me.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
> I thought you might have missed the reference to that issue which was also in this ticket. They seemed like the same problem to me.

L tag is not supposed to give paragraph breaks, right?

**Comment by agrogers** [comment]
Oh, I don't know 🙄 The original post made sense that it should but I have
not tried to confirm. I will check it when I get a chance and make another
ticket or fix it myself.
