### ISSUE TITLE
Getting time to load document when load first time

### ISSUE THREAD

**Issue by GauravCreed** [AndBible/and-bible#2185]
Hi @tuomas2

when first time installed app, it will show downloaded document list from JSword library, in this screen it will take approx. 3-4 minute to load document after we can download any bible from it,

can we reduce this loading time?
Thanks(_)

**Comment by tuomas2** [comment]
Latest upgrade (4.0.648) fixes long wait (to ~10 sec only). There's one repository (StepBible) which is down for some reason. Normally does not cause wait almost at all.
