### ISSUE TITLE
Copy multiple verses with verse numbers should not add first verse number

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2188]
Example, copy 1Cor 14:34-35 and you get this:
> 1Cor 14:34-35 34. Let your women keep silence in the churches: for it is not permitted unto them to speak; but they are commanded to be under obedience, as also saith the law. 35. And if they will learn any thing, let them ask their husbands at home: for it is a shame for women to speak in the church.

The `34.` before the verse starts is unnecessary and would be better for it not to be there IMO.

**Comment by agrogers** [comment]
Yeah, I agree. I noticed that too. I can fix that.

**Comment by agrogers** [comment]
I think this has been done. Forgotten what PR did it though sorry.
