### ISSUE TITLE
No way to access footnotes and cross references

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#220]
ESV has footnotes and ref. Now there of no way to access these.
Previously we selected a verse and then from menu we selected footnotes, now I can't find footnotes anywhere in the menu.

**Comment by tuomas2** [comment]
Is it so that you don't see "footnotes and references" at all in the menu?

**Comment by bvahedy** [comment]
Because the top right menus (three dots) change in it's context when you are in select mode, intuitively to don't think it would be there. I was looking for it in the left menu where bookmarks and notes are.

**Comment by tuomas2** [comment]
Related ticket: #224
