### ISSUE TITLE
Duplicated content bug tracker

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2203]
Thought it might be helpful to make a list of similar issues

- #1965
- #2174
- #2011
- #1998
- #1623
- #136
- https://github.com/AndBible/and-bible/issues/2650

**Comment by agrogers** [comment]
Good work

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Mayber reltaed https://support.andbible.org/scp/tickets.php?id=1806

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2045
