### ISSUE TITLE
Add export and import user data feature 

### ISSUE THREAD

**Issue by KyleBroflowski** [AndBible/and-bible#2205]
**Is your feature request related to a problem? Please describe.**
When switching phones if phone is non rooted it is impossible to transfer the app settings including userdata, user settings, bookmarks and notes

**Describe the solution you'd like**
- Add export data option

- The export should have the feature to optionally select whatever component that needs to be exported
Example to be able to select user settings alone and not the document bookmarks and notes .
_Example to be able to select user settings alone and not the document bookmarks and notes ._

Similarly,
- feature to optionally import app settings based on whatever is needed.
  _Example If i have a full backup and I only want to import notes and not appdata or bookmarks I should be able to do_

**Comment by agrogers** [comment]
Hi. You can transfer settings, notes etc already. They are all saved in the database. Just backup and restore those and you will be good. The screen shot below will look different to your backup option but it has the same options.

Re restoring some settings only, that is not possible.

![IMG_20220726_181418.jpg](https://user-images.githubusercontent.com/13920678/180998480-59392259-c6b4-4d2d-9bbe-fa443ac63fc4.jpg)

**Comment by KyleBroflowski** [comment]
Thankyou.
