### ISSUE TITLE
During speech special window (strongs) will display 'not found'  

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#221]
During speech in an English bible with Strong's numbers, if you tap on a Strong's no., the dictionary shows the definition for that no., but as speech goes to the next verse the screen then says not found.

**Comment by tuomas2** [comment]
FIxed in 94bcbe129534984fde536a9a73966cac4886f623

**Comment by tuomas2** [comment]
Fixed in 786d9cf
