### ISSUE TITLE
HFA - Brunnen Verlag no longer offers unlocking keys

### ISSUE THREAD

**Issue by isteinbach** [AndBible/and-bible#2213]
**Describe the bug**
In the past, "Brunnen Verlag Gießen" had transferred rights related to the German "Hoffnung für Alle" to "Brunnen Verlag Basel" which in turn is now Fontis Verlag Basel. In consequence, the [registration form](https://www.crosswire.org/sword/modules/registration/gerhfa2002-registration.jsp) referenced on the ["Hoffnung für Alle - Sword-Modul" page](https://www.crosswire.org/sword/modules/registration/gerhfa2002.jsp) does not work. The data transmitted via that form is apparently just discarded. The page is also referenced i the app when installing HFA.

**Bug was found on And Bible version**
net.bible.android.activity 4.0.649 via F-Droid.

**To Reproduce**
1. Install GerHfa2002
2. Popup opens requesting the the unlocking key
3. Tap on "Information"
4. "THIS MODULE IS LOCKED. TO UNLOCK VISIT: http://crosswire.org/sword/modules/registration/gerhfa2002.jsp"
5. Open that page, follow link in step 2 on that page ("Bestellung des Schlüssels...")
6. Fill out the form and submit it
7. Wait (in vain) on reply by Brunnen Verlag Gießen
8. Contact Brunnen Verlag Gießen directly
9. Get information on outdated information on the SWORD HFA module

**Additional context**
I have contacted Fontis Verlag whether they are going to offer SWORD keys to unlock HFA. No reply yet.

**Comment by tuomas2** [comment]
Document is provided by Crosswire so I propose you report this issue to their tracker
https://tracker.crosswire.org/secure/Dashboard.jspa

**Comment by isteinbach** [comment]
For the reference: https://tracker.crosswire.org/browse/MOD-436
