### ISSUE TITLE
Sharing Bookmarks

### ISSUE THREAD

**Issue by Dleemuse** [AndBible/and-bible#2214]
Is it possible to be able to share bookmarks. I have tons, which I have titled, of course, & it would be nice to be able to go to three line menu, select bookmarks, then select bookmark of choice & share those scriptures with others. 

Thank you for your continued work on this app. 

Debra

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by timbze** [comment]
Not yet. This feature request is also in #189. 

You can export study pads, which might or might not help you. See the pic in issue #1328
