### ISSUE TITLE
Red letters incorrect for NASB John 11:35-39

NASB John 11 has some red text for parts Jesus was not talking. Screenshot included.



### ISSUE THREAD

**Issue by Stevespear426** [AndBible/and-bible#2221]
![Screenshot_20220825-075917.png](https://user-images.githubusercontent.com/1293705/186658729-df390234-c492-469b-95c2-f08f4f6fc854.png)

**Comment by timbze** [comment]
Thank you for the report. This is a module issue and has been reported to the module maintainer, CrossWire: https://tracker.crosswire.org/browse/MOD-428
