### ISSUE TITLE
Special window (links window) changes Bible version after window close

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2222]
**Describe the bug**
This was reported in AB support ticket, but I wasn't able to figure out at the time (few weeks ago). Now I came across the issue and figured out what happens.

When the links (special) window is minimized, it opens new link clicks in the same Bible version, but once it's closed it resets the Bible version and will (may) open another version.

I think it would be good to persist the last open Bible version of special window in a workspace and reuse that when it opens again.

**Bug was found on And Bible version**
Build 649

**To reproduce**
1. Open commentary with Bible links
2. Click a Bible link -> opens special window in ESV
3. Change the opened window (last window/special window) to another Bible version (KJV)
4. Close the last/special window
5. Now click another Bible link
6. -> special window again opens in ESV
7. Expected -> it should open in KJV

**Comment by tuomas2** [comment]
Closing a window works like this. I don't think it's a bug. If you minimise window but not close it, it will retain the version. If you close window, next time new window will have same docs as the source window.
