### ISSUE TITLE
Dev Question: Should I update Kotlin and/or Gradle

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#2226]
I am not sure what I should do when different versions of Kotlin and the Gradle Plugin are available. I tend to only update things if I have problems. Is there a specific version that I should be on? Does it matter?

I get the error below when I switch between branches. I dont actually know what that means and havent tried very hard to understand it. I just resync and it works out ok. Any recommendations?  Thanks.

![image](https://user-images.githubusercontent.com/13920678/188256748-2e540122-a597-480d-86c3-4a9bb28ec848.png)

![image](https://user-images.githubusercontent.com/13920678/188256782-1df4e0c4-4a64-4f90-ae4a-68e06b1620f4.png)

**Comment by tuomas2** [comment]
I think I just upgraded gradle last week in 7252a5837a4c35c7ae5f472b4bb2f29bb4b813a5. If you pull my changes, it should be fine. Good to upgrade also Android Studio if you didn't already.

**Comment by tuomas2** [comment]
I'm upgrading gradle and other tools time to time, I think you don't really need to do those things.

**Comment by agrogers** [comment]
Thanks for the tips.
