### ISSUE TITLE
Remove space from "And Bible" in website

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2248]
A few main places have been changed but the main page itself still has quite a few more places that need to be changed

https://andbible.github.io/
https://github.com/AndBible/andbible.github.io

**Comment by tuomas2** [comment]
Fixed in https://github.com/AndBible/andbible.github.io/commit/fdf3182aee43caedce6bd60ed006ea3bf97e0316

**Comment by tuomas2** [comment]
Also renamed Google Play developer name "And Bible Open Source Project" -> "AndBible Open Source Project"

**Comment by timbze** [comment]
Quickly scanned the page and found this at the end: "AnnBible Support"

![image](https://user-images.githubusercontent.com/35117769/191726383-54842328-a007-4678-896a-d207fe52e9b6.png)

**Comment by tuomas2** [comment]
Fixed https://github.com/AndBible/andbible.github.io/commit/5439e2775b84de31c533387bec2dcb3d83b901ef
