### ISSUE TITLE
Samsung version should not provide Google Play link

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2249]
Samsung emailed me that app is suspended in Galaxy Store due to this issue.

> [Defect]
> It provides the link to Google Play store when sharing the app
> Test device - Android ver : 12,11,10
> 
> [Procedure]
> 1. Execute app
> 2. menu - Recommend to a friend click - Choose any app for sharing (Ex: messages...) - Check the share content: it provides the Google Play store link
> 
> [Expected Result]
> The link app from Galaxy Store should be attached on share content instead of Google Play store link
> [Test Device Info]
> Detected Device: SM-G975N, SW Version: G975NKSU7HVB7

**Comment by tuomas2** [comment]
Probably better to fix Huawei and Amazon (and why not F-droid) versions at the same time.

**Comment by timbze** [comment]
How about sharing AB website or some specific page where the different install options can be seen? I figure that when someone shares with Galaxy Store link chances are it will be useless to the person receiving it (they might not have Samsung)

**Comment by tuomas2** [comment]
Added badge to homepage and removing explicit play store link from samsung version.

**Comment by tuomas2** [comment]
Submitted 651 to galaxy store
