### ISSUE TITLE
What happens during a restore with a new install?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#2256]
Hi,

I was setting up a new phone and am fairly sure I just selected the 400Mb documents file to restore on the initial screen. I expected to then need to restore the database but when it finishing restoring my latest database was also already installed. That was good - it saved me a step - but it was unexpected. Is that what you would have expected?

Thanks
Andrew

**Comment by tuomas2** [comment]
Google's backup of database was restored?

**Comment by agrogers** [comment]
Maybe but I dont think so. Because i am using my own AB build, the app
didnt come across when i transferred from my old phone to the new one. Then
i couldnt install it without messing with Dev options. I ended up
installing it directly from Android Studio. And then selected my large
documents file.

**Comment by timbze** [comment]
When I played with Google backup I think I recall that the backup was also restored when installing from Android Studio. I was a bit surprised. That's the only thing I can think of in your situation if you only restored documents.

**Comment by timbze** [comment]
> When I played with Google backup I think I recall that the backup was also restored when installing from Android Studio. I was a bit surprised. That's the only thing I can think of in your situation if you only restored documents.

Yes. https://github.com/AndBible/and-bible/pull/385#issuecomment-498273014
This is what I had written:
> To test restore, simply uninstall the app and reinstall. Either from Play Store or Android Studio works.

**Comment by agrogers** [comment]
That could be it. Thanks.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
I think it's enough if app id is identical. Closing this.
