### ISSUE TITLE
UI for installing MyBible & MySword modules

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2258]
Not sure how this should be implemented. Ideas welcome. 

Related: #1473

**Comment by agrogers** [comment]
AB doesn't have permissions to access folders of other apps does it?

**Comment by tuomas2** [comment]
No, I'm afraid. I'm not sure if it is possible to grant such permission... Even file manager (in my samsung) does not see app data folders in Android/data. 

So I'm not sure if it can be implemented at all, unless perhaps we have co-operation with MyBible developers.

**Comment by tuomas2** [comment]
If MyBIble would have "export / backup modules" feature it would help.

**Comment by tuomas2** [comment]
Perhaps, in Download Documents, we could have menu entry "Install MyBible modules" that would show the instructions (or just link to the instructions in WikI).

**Comment by timbze** [comment]
> AB doesn't have permissions to access folders of other apps does it?

For sure not after Android 10 (or 11)+. Though if MyBible has something like #632 and we implement that feature then files could technically be shared as far as I know. With their info [here](https://mybible.zone/en/privacy/) I'm not sure if they have that feature... or the page is not up-to-date.

**Comment by agrogers** [comment]
My first thoughts:
- The hardest part for me is finding what subfolder both AB and MyBible hide things in
- So telling the user where that folder is or our best guesses as to where that folder is would be vital
- we should provide if it is possible to open the file browser directly to the AB folder that the files need to be copied into. On my phone there are two files apps. One didn't allow me to browse and one did. Is there an Intent that can open the system file viewer to a particular folder? https://stackoverflow.com/questions/18097763/how-to-open-the-my-files-folder-in-android-programatically-using-intent
- link to a video and or manual page that shows how to do this step by step
- MyBible has a setting to relocate data files to the SD card which is cool. That option also shows exactly where the files are located. So it's not too hard for the user to find.
- Are there any free backup apps that would allow the user to backup from MyBible folder into AB folder?

**Comment by agrogers** [comment]
Can AB access the Downloads folder directly? Or is there some folder that every app can access - say a media folder? If so, I think the following might work:

- MyBible allows relocating the data folder to somewhere else in order to allow synchronisation with the cloud through a 3rd party product
- So do this in MyBible moving the data into the Downloads folder
- Then AB just needs to look in the downloads folder for MyBible folder and grab whatever it can find there.

My preference would be to put the folder elsewhere - like on my SD card. But when I tried that I couldn't find the SD card in MyBible. And adding a folder to the root of the main storage said the folder was read only. I don't understand how android file system permissions work. 

I think this (being able to relocate the data folder to somewhere else) is also a good idea for AB and it would allow auto backups and synching with no extra work on our side.

![Screenshot_2022-10-05-00-20-04-319_ua.mybible.jpg](https://user-images.githubusercontent.com/13920678/193891490-b6139634-c69c-4641-818b-5505beae7c03.jpg)

**Comment by agrogers** [comment]
If I understood this correctly
https://developer.android.com/training/data-storage/shared/documents-files#grant-access-directory
it seems possible to ask the user to browse to the location that they have chosen for their MyBible data files and persist permissions for that location. The Downloads folder would not be the best option though. Some other shared folder location might work though.

**Comment by tuomas2** [comment]
I believe Downloads folder can be granted access. In as MyBible allows user to choose directory, we could use whatever folder that is generally accessible to import (or read directly) modules from.

**Comment by tuomas2** [comment]
Then we just need to instruct user to choose a specific folder in MyBible side in order to make it work.

**Comment by agrogers** [comment]
Downloads folder definitely works for MyBible. I could access it form AB
but I could only see media files.

I think in principle this should work well. Although I had a MyBible module
that crashes AB. Still need to work out which it is. There are other sqlite
files in that folder that would need to be excluded from AB as well I think.

**Comment by pepaulo** [comment]
This is a simple way to make a repository to MyBible modules and add other repositories. 

https://mybible.zone/en/extra-registries/

**Comment by tuomas2** [comment]
> This is a simple way to make a repository to MyBible modules and add other repositories.
> 
> https://mybible.zone/en/extra-registries/

Repositories will be covered in #2487

**Comment by agrogers** [comment]
That's great. An easy way is what i would like :)

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Here's some UI:

![image](https://user-images.githubusercontent.com/5811789/218265742-9cfa87db-e74e-47be-ae89-fe22e297ee95.png)

**Comment by tuomas2** [comment]
![image](https://user-images.githubusercontent.com/5811789/218263676-cd8ecb10-804e-4cd5-a7dd-11493d743ac7.png)

**Comment by tuomas2** [comment]
Now implemented.

**Comment by agrogers** [comment]
Great.
