### ISSUE TITLE
Does the backup documents option also backup Mybible documents? 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#2262]
It seems like it doesn't. But I think it should.

**Comment by tuomas2** [comment]
it would require another option in backup menu as those do not go to the sword module tree.

**Comment by agrogers** [comment]
I can add the option but you might need to add the smarts.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
It does at least now
