### ISSUE TITLE
Android 13 checklist

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2264]
https://developer.android.com/about/versions/13/migration

**Comment by timbze** [comment]
Looks like foreground services may need some work for v13. I think TTS uses foreground service right?
https://developer.android.com/about/versions/13/behavior-changes-all#fgs-manager

**Comment by tuomas2** [comment]
I went through the list now and mainly notification related changes were necessary. Notifications need now permission, with exception of media notification. So changed tts notification to media notification and asking permission for the rest.
