### ISSUE TITLE
Would this help webview problems?

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#2267]
We had/have some out of date webview problems don't we? Would this help? 
https://engineering.fb.com/2022/09/30/android/launching-a-new-chromium-based-webview-for-android/

**Comment by timbze** [comment]
I think the problem was related to Android 8 and 8.1, and the issue has to do with Chromium versions newer than around 91, which fb also bases their webview on. So IMO this won't be helpful for that issue.

**Comment by agrogers** [comment]
Oh, yeah, that's right. It was older Android systems, wasnt it.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Related: #2068 #1765
