### ISSUE TITLE
Discrete mode: replace fish icon (shown in notification etc) with something else

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2274]
In TTS notification we should not show anything biblical!

**Comment by agrogers** [comment]
Hey, how do i get past the calculator? I enabled the  second option with no PIN code but now all i get is a calculator and cant get to the Bible :)

**Comment by tuomas2** [comment]
Default pin is 1234

**Comment by agrogers** [comment]
Yeah, i just found it in the code. We probably should tell the user that that is the default when then enable that option. Or force them to choose a PIN.
