### ISSUE TITLE
Prepare discrete build and instruct users

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2276]
Even though we change icon in launcher, app itself is explicit what it is:

![image](https://user-images.githubusercontent.com/5811789/194348243-0a5c14c2-adf9-43d3-b90d-7661bea7c7c8.png)

We should add some info text in discrete settings area and info about a separate discrete build that is available via Github.

**Comment by agrogers** [comment]
That's a shame. But good solution.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by uniqueid001** [comment]
This screenshot looks like the 'standardDebug' variant, not the 'discrete' variant.  The name "Bible Study *Debug*" only occurs in the resources for standardDebug, and the logo is also different for the 'discrete' variant.  That is declared in the app's manifest when it is built, and can not be changed dynamically at runtime.

Do you want the name 'andbible' in the package of the calculator activity?  I would think it should use a more discrete package name, corresponding to the discrete application id.
Also, do you want the calculator activity in 'main', or do you want it only in the 'discrete' variant?

**Comment by tuomas2** [comment]
I have not built anything yet with discrete variant. This issue is just pointing out that we actually need discrete variant for this purpose (and this only), all other functionality can be implemented in standard build (like dynamic icon change etc).
