### ISSUE TITLE
Discrete variant

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2279]
DIscrete variant:

- [x] hide "Discrete mode" setting
- [x] ~Instruct user to setup calculator from app preferences in first run~
- [x] Nicer icon for calculator
- [x] Use same icon in standard build's discrete mode as well as in discrete build variant
- [x] #2273 
- [x] #2274 
- [x] #2276 

![image](https://user-images.githubusercontent.com/5811789/194695647-6f68dbe4-34bc-4975-adf8-5ffa8d065cf4.png)

**Comment by agrogers** [comment]
What is the reason to hide that setting?

Is there any value in allowing the user to choose from a number of
different app icons?

When I was developing I couldn't launch the app automatically after I had
changed it to the calculator I assume because the default activity had
changed. Will this cause problems when people are trying to update the app
through playstore say?

**Comment by uniqueid001** [comment]
The setting is not (should not) be applicable to the discrete variant.  The discrete variant is a different APK that is built specifically to automatically and always be discrete.

It should also be less superficial in its attempt to hide:  the application id is different, and it should not declare the standard launcher activity.

**Comment by agrogers** [comment]
Ah, I understand. Thanks for the clarification.

**Comment by tuomas2** [comment]
I've been thinking about the suggestions (@uniqueid001 's pull requests #2286, #2282) to force-enable calculator in discrete mode too. 
Maybe it kind of makes sense. In the first run, it could give popup message that forces user to choose pin and then instruct to use calculator.

**Comment by tuomas2** [comment]
Or should it not even give that instruction in app. Meaning, if the app data is deleted, it still acts like a calculator and not like a bible app? Perhaps discrete mode instructions should just be given on website distributing discrete mode build.

**Comment by uniqueid001** [comment]
I would expect that users who deliberately choose to install the discrete variant will want the app to maintain its discreteness, even or maybe especially with app data deleted (or not yet created), and not expose its true purpose.  It is contrary to the UX principle of discoverability, but this is a special use case.

**Comment by tuomas2** [comment]
Download page: https://github.com/AndBible/and-bible/wiki/Discrete-build
First alpha version of discrete version: https://github.com/AndBible/and-bible/releases/tag/alpha-657-discrete
