### ISSUE TITLE
Disabling the "show Strong's no." in the settings bug....

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#228]
When unchecking the box to not show Strong's numbers the app also turns off the morph codes.

**Comment by mjdenham** [comment]
That was the way it was designed.  It meant there was no need for 2 Strongs buttons in the toolbar.

**Comment by tuomas2** [comment]
Bug should be probably fixed then by disabling (greying out) "Show morphology" option from options menu, if strongs are not shown.
