### ISSUE TITLE
Bookmark selection offset issue

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2287]
https://support.andbible.org/scp/tickets.php?id=1624

![Screenshot_20221009-100237](https://user-images.githubusercontent.com/5811789/194874445-7cf740ac-67be-4bf5-911d-fb502b9b4b8a.png)

**Comment by tuomas2** [comment]
Reproduced

**Comment by tuomas2** [comment]
Issue was with `<q>` element

**Comment by RuggMatt** [comment]
Happened again 

![Screenshot_20221113-115332.png](https://user-images.githubusercontent.com/8870594/201539134-3b8655bd-d27c-44ab-a298-02b47ae504a5.png)

Version 4.0.661 #e335a 6f57 standard release (built 10/11/22 20:44:48)
