### ISSUE TITLE
Rewind to previous verse does not bring verse to top... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#229]
When at the top of a chapter and speak is invoked and then the previous verse button is pressed in the speak toolbar, the app reads the correct verse but does not bring the verse to the top of the screen.

**Comment by tuomas2** [comment]
Can't reproduce this. For me it is scrolling smoothly to the previous verse when I press prev verse button.

**Comment by bvahedy** [comment]
You need to be at verse one of a chapter and then tap on prev. verse
button.

**Comment by bvahedy** [comment]
I tried it with an Amazon fire 8 tablet and the first time it worked but if you stop and move to the beginning of other chapters it starts to fail. Sometimes it even displays the beginning of the previous chapter while reading the correct verse. It's behavior is

**Comment by tuomas2** [comment]
Can you still reproduce this? I was again doing some tests, but was unable to reproduce.

**Comment by bvahedy** [comment]
It's working now, you can close this ticket if you like.
