### ISSUE TITLE
Change the name of the 'Calculator' to 'Simple Calc' say 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#2290]
Like most users I have a calculator installed already which is called calculator. It looks weird when I scroll through my app list to see two identically named apps side by side.

My suggestion is to rename our app to anything other than 'Calculator'.

Even better would be to allow the user to choose a name /edit the name.

**Comment by tuomas2** [comment]
I have been thinking if our calculator should try to mimic closely some commonly used calculator app (Google etc) in everything? Other calculator app can then be disabled/removed I suppose

**Comment by agrogers** [comment]
That would be an ideal solution. But the standard calculators these days have so many extra features that I would be very unlikely to replace it with AB.

**Comment by tuomas2** [comment]
Any other opinions about this name change suggestion?

**Comment by tuomas2** [comment]
I'll close this as no supporting thoughts are coming (feel free to re-open).

**Comment by agrogers** [comment]
This is how it looks on my phone. Having two calculators visible side by side and with the same name just seems to make it less discrete. If we are trying to avoid drawing attention to the app I don't think this is the way to go about it. But I also think that it is a low risk issue so probably not that important. 

![Screenshot_2022-11-10-21-54-14-175_com.miui.home.jpg](https://user-images.githubusercontent.com/13920678/201135477-9a9d60bb-765e-41ea-9a21-db69195ebcc1.jpg)

**Comment by tuomas2** [comment]
> This is how it looks on my phone. Having two calculators visible side by side and with the same name just seems to make it less discrete. If we are trying to avoid drawing attention to the app I don't think this is the way to go about it. But I also think that it is a low risk issue so probably not that important.

I'm used to have multiple similar name apps and I don't look at app drawer so often anyway, so somehow I don't see this as a problem. But I don't have strong opinion about the name. I just have used "Calculator" so far in multiple contexts and lazy to change.. :-)

**Comment by tuomas2** [comment]
I used to have 2 existing calculators until recently because one had been transferred from old phone, and this was third one. Though when you wrote about this I noticed it and uninstalled the redundant calculator app :-P

**Comment by agrogers** [comment]
I have a strong opinion 😎 But I don't think it makes much difference so
don't have strong motivation 🙃

**Comment by tuomas2** [comment]
Which name then:
- Calculator
- Simple calculator
- Simple calc
- Basic calculator
- Basic calc

**Comment by timbze** [comment]
My preference, either:
- Calculator
- Simple calculator

Makes no difference to me which one.

**Comment by agrogers** [comment]
1. Simple Calculator
   2. Simple Calc

Basic is good as well but it puts it closer to B puts it closer to C so S
is more discrete in my mind.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
