### ISSUE TITLE
Distribution server: AndBible Extra?

### ISSUE THREAD

**Issue by josephg5** [AndBible/and-bible#2294]
Why is this a separate distribution server, and why is it not updated?

I find Berean Bible useful to me, bit it is placed in the Extra server and not kept updated.

**Comment by timbze** [comment]
We don't really do module maintenance. As the [AB Extra repo](https://github.com/AndBible/andbible-extra) describes, it's a mirror of the Xiphos repository. But I'm not even sure why it's needed. Tuomas would know.

**Comment by tuomas2** [comment]
Xiphos repository is FTP only. Just wanted to have them here too. But if some of those modules are not working properly we can remove them.

**Comment by tuomas2** [comment]
Or if they have been updated in Xiphos, PR towards https://github.com/AndBible/andbible-extra is welcome!

**Comment by josephg5** [comment]
> if some of those modules are not working properly we can remove them.

Please don't remove them. I can't find some modules anywhere else. Better to have them than not.
