### ISSUE TITLE
Calculator not displayed if returning to non-main activity

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2306]
1. Open discrete version
2. Go to (for example) Workspaces list
3. Make app go to background
4. Return to app (workspaces list)
-> returns 
should: show calculator

**Comment by timbze** [comment]
In some of my testing I saw that the task list still shows the Bible even though it's been hidden with home button.

I wonder if it would be possible to already show calculator screen when switching away from the app so that the task list would only show calculator?

**Comment by tuomas2** [comment]
I think it is at least possible to hide content. Bank application does that.

**Comment by tuomas2** [comment]
> I think it is at least possible to hide content. Bank application does that.

Created #2307

**Comment by tuomas2** [comment]
How this is done in MainBibleActivity is that in onRestart we check if lastRequest == null meaning that we did not return from another activity. I was making sure that all activites are started with startActivityWithResult, so returning from other activities should not cause calculator. This approach is not easily generalized to ActivityBase and I could not figure out easier way to implement this. So it is enough if we take care of MainBibleActivity? Or are there other activities that people might leave open? 

Hmm. Maybe need to think still about this a bit more..

**Comment by agrogers** [comment]
This feature is soo much more complicated than I expected.

**Comment by tuomas2** [comment]
https://stackoverflow.com/questions/5336493/find-out-which-activity-started-my-activity
callingActivity will not help, as it returns original calling activity even if returning from launcher.
