### ISSUE TITLE
Save browsing history when app is closed

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#231]
From user: 

Please make the browsing history persist after the app is closed, and also when navigating through the history:
► It is often the case that one wishes to revisit the last verses viewed, some time after running the app. Currently however, the history is empty when starting the app again - and the history of the previous reading session is lost.
► Also, when one currently backtracks in the history by several steps, the later verses in the history are irretrievably lost, as if permanently popped off of a stack. Instead, it would be more helpful if one could browse backwards AND forwards through the history, as if following the same train of thought. Example: we read the following verses: Mat 1:1, Mar 1:1, Luk 1:1, Joh 1:1 ... And then wish to retrace our steps from the Matthew verse; but if we go back 3 times from John, the Mark & Luke verses are lost from history and there is no way to proceed "forward" again from the Matthew verse. 

Related pull request #54

**Comment by timbze** [comment]
Just an idea, but it might be an option to have a separate history per tab (#355) and overall.
For example, have a history like Chrome's browsing history, where every Scripture change is recorded, regardless of window or tab. And have a separate history per window or per tab which controls where the back button will take the user. I think it would not work to navigate with back button to the last overall history, but would have to be specific to either the tab or window.
There already was an attempt at persistent history here #54 but seems no conclusion was reached at that time.

Could have the screen something like this (a prettier design hopefully), with a button to see all history.
![ab_history_screen](https://user-images.githubusercontent.com/35117769/56837727-a65bc480-6838-11e9-8665-7ccffde31259.png)

**Comment by tuomas2** [comment]
Will be implemented in build 308

**Comment by bvahedy** [comment]
Verified fix in 308 beta.

**Comment by gdiamant** [comment]
Thank you very much for working on this, this will be very useful.
