### ISSUE TITLE
Find verse by entering reference as a text

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#232]
► Please provide a way to locate a scripture BASED ON A REFERENCE IN THE SYSTEM CLIPBOARD. Often while reading emails, online articles, and sermons, references are made to scriptures .. references that can be copied to the clipboard with the intention of looking up the scripture in the And Bible app. But there is currently a disconnect between the clipboard and the app, because the only way to locate a verse in the app is by manually browsing to it. This feature needs the flexibility to recognise standard abbreviations besides unabbreviated references, eg: "1 Timothy 6:11", "1Tim6:11", "1 Tim 6:11", etc.

► Please provide a way to locate a scripture in the app BASED ON A SPOKEN REFERENCE. When the scripture reference cannot easily be captured to the clipboard (for the above feature to work), or when it is difficult to manually browse to the scripture, it would be helpful if the app could accept voice references that are spoken by the user, to locate the relevant scripture.

**Comment by bvahedy** [comment]
The function of the find is not to go to a chapter or a verse but to find text is in a verse. It's much easier to navigate to a chapter verse than to go to the find screen and paste a ref. From the clipboard. Just saying.

**Comment by tuomas2** [comment]
I think that this could be implemented, for example, by adding a text box on top of verse selector screen. I agree that this should not be in Search screen.

Not sure how useful it is, though.

**Comment by bvahedy** [comment]
Or you could change the current book selection on the toolbar to:
Tap once and it brings up the book list then slide on a book will bring up
chapter and slide on a chapter will bring up verses and when you land on a
verse it will go to that verse. This way we can go to any passage with one
tap and one slide.

Although I don't know how easy it would be to implement this.

**Comment by agrogers** [comment]
I just made a comment on another related task about this. Using the Share option on Android would avoid the middle step of pasting it into some user control in AndBible

**Comment by tuomas2** [comment]
Implemented
