### ISSUE TITLE
SweFolk1998 has newline after the verse number in many books

### ISSUE THREAD

**Issue by dabruh** [AndBible/and-bible#2320]
**Describe the bug**
Somehow a newline is inserted after the verse number in SweFolk1998. I've found this in:
- Psalms
- Proverbs
- Ecclesiastes
- Song of Solomon
- Isaiah
- and likely many more...

**Bug was found on AndBible version**
4.0.651

**To Reproduce**
1. Go to one of the aforementioned books in SweFolk1998
2. See error

**Expected behavior**
No newline after the verse number.

**Screenshots**
OVPL OFF
![Screenshot_20221022-125301_Bible Study](https://user-images.githubusercontent.com/57197090/197335295-02627352-07a1-4e2b-86c5-2345d9b013da.png)

OVPL ON
![Screenshot_20221022-130149_Bible Study](https://user-images.githubusercontent.com/57197090/197335636-aec47002-7173-441a-b3f3-85b170c27b91.png)

**Smartphone**
 - Device: ONEPLUS A6013
 - OS: 19-20220922-NIGHTLY-fajita
 - Android Version: 12

**Additional context**

**Comment by tuomas2** [comment]
Looks like this for me:
![image](https://user-images.githubusercontent.com/5811789/230426453-9f026ae4-6940-4e47-ac31-3f8679851be6.png)

But module seems a bit crappy. Is there some reason not using 2005 version by Crosswire which probably is better quality module?
