### ISSUE TITLE
Berean Study Bible from MyBible

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2326]
Berean Bibles please. I would really like the Berean Study Bible, if possible. Thanks.
http://berean.bible/licensing.htm

_Originally posted by @josephg5 in https://github.com/AndBible/and-bible/issues/2122#issuecomment-1288908829_

**Comment by tuomas2** [comment]
Berean seem to be included in Step Bible so perhaps sword module could be found too?

**Comment by josephg5** [comment]
There is a very old (sword?) module in AndBible-Extra.

**Comment by rjm831** [comment]
I second the idea.  Berean would be a wonderful addition and licensing is a non-issue.

**Comment by timbze** [comment]
I see Berean Study Bible from eBible in the list, and Berean Standard Bible from Crosswire. Have you checked those @rjm831 ?

**Comment by rjm831** [comment]
Yes, thank you for replying.  I do actually have the app's version of the Berean installed.  Its my understanding that the developers involved in the Berean project are constantly updating it and my thought was along the lines of new updates to it.

**Comment by timbze** [comment]
I think the eBible is recent. Many of the eBible modules do get automatically updated, the question is just what is their source... And I have not looked at their source myself.

@tuomas2 I think this issue can be closed. I think there are modules now that were not here last year.

**Comment by rjm831** [comment]
I thank you both, and blessings to you.
