### ISSUE TITLE
Contextual toolbar not always shown

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#233]
From user via email:

> I want to use the verse context menu frequently. In previous versions this was easy, just tap on the verse. Or I could write a new item as My Note, for example.
> 
> In this version it seems I can do this only once after I've launched the program. To do it again I have to restart the program afresh. 
> 
> I have a ZTE smartphone. The system menu says model number N9130 and it runs Android 4.4.4
> 
> User note, since last email: I find that after program start, I can select a verse for verse context options at least once, perhaps once or twice more. But eventually that won't work.
> 
> Then I stop the program, using Force Stop from the program's app settings. This allows a fresh restart of program and thus, 1 or maybe a few more verse selections for verse context options - until again that won't work.
> 
> This happens both in fullscreen and non-fullscreen.

**Comment by bvahedy** [comment]
I'm unable to reproduce this on a Note 8.
I would recommend backing up notes and the Bible directory and doing a fresh install.

**Comment by tuomas2** [comment]
User updated his OS and the problem disappeared. Closing this.

**Comment by bvahedy** [comment]
Nice, I like problems like this.
