### ISSUE TITLE
New language version

### ISSUE THREAD

**Issue by Bryanjoyce** [AndBible/and-bible#2337]
Could someone please contact me with information regarding how to get a new language version that we have available pushed to AndBible's list of available versions.

Thanks!  
bryanjoyce@duck.com

**Comment by tuomas2** [comment]
what do you mean precisely?

**Comment by Bryanjoyce** [comment]
Hi Tuomas,
Thanks for replying.

I am connected with a group that has produced a new translation of the entire Bible into Uzbek. This translation is in addition to the Uzbek translations that are currently available on AndBible. The ones that are currently available are being pulled from IBT, an organization in Russia that does many Bible translations for language groups across the former Soviet Union, including Uzbek.

This translation has not been done by a translation agency and therefore they do not know how to push the translation to multiple client apps like AndBible. I'm trying to help them find out how to do this. If there are certain endorsements or validations that are necessary for their translation to be added, we would like to know what they are. If there is a technical process we need to follow to get the app included in the list that AndBible generates, we need to know those as well.

I hope that clarifies. Please respond with any other questions you may have.

Bryan

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by tuomas2** [comment]
Does our FAQ answer the question satisfactorily?
https://github.com/AndBible/and-bible/wiki/FAQ#please-add-module-x-to-andbible

**Comment by Bryanjoyce** [comment]
Hi,
Yes, this is helpful. I will follow up with Crosswire.

Bryan

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
