### ISSUE TITLE
Timestamp in Bookmark list view gets too little space

### ISSUE THREAD

**Issue by didib** [AndBible/and-bible#2343]
**Describe the bug**

Under certain conditions, probably when both the reference and the
timestamp are too long and with a large-enough font, the bookmark list
view splits the space unevenly - the reference gets too much space and
the timestamp therefore needs many lines.

**Bug was found on AndBible version**
4.0.651 (from fdroid)

**To Reproduce**
Not sure. When I tried fixing it, Tried with the emulator included with Android Studio, and failed to reproduce it with all of the 3 "machines" I tried (Pixel 2, Pixel 5, Nexus 4).

My own machine is a Samsung A31, fonts configured via Settings to be the largest available there. All with the base OS stuff - no custom fonts/settings/etc.

Anyway, to reproduce:
1. Configure your phone to use a large font.
2. Create a bookmark to a long ref.
3. Perhaps this happens more/only in Hebrew. Not sure.
4. Go to the bookmarks list.

I am including two screenshots - one showing the problem and another, on the same ref, showing the behavior with my proposed fix.

I am not an android developer, and this is my first patch for an Android project. Someone more experienced might want to refine my fix before merging it. It does work for me, though, on both my own phone and the emulator (where it's merely harmless - failed to reproduce there, as noted above).

**Comment by didib** [comment]
For some reason, github does not let me attach pictures here. Says "something went really wrong". Links:

Broken: https://imgur.com/a/QdQ2rfv

Fixed: https://imgur.com/a/e8js1pK

**Comment by tuomas2** [comment]
broken: 

![image](https://user-images.githubusercontent.com/5811789/201046466-01e3ee07-8889-4789-bf6b-8196907b9be5.png)


Fixed:

![image](https://user-images.githubusercontent.com/5811789/201046454-c87c5123-ab86-4a59-a954-619a09711470.png)

**Comment by didib** [comment]
Thanks :-).
