### ISSUE TITLE
Window popup menu close button was not disabled although it should

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#235]
From user:

> Hello. I updated to the latest update today and I pressed the small square icon that appears and disappears and on the mini menu that pops up I selected close and it took all of the letters of the Bible off of the page. 

> Version 8.0 and a Sony xperia x compact.

**Comment by tuomas2** [comment]
Not trivial to reproduce. Waiting info which system was being used.

**Comment by bvahedy** [comment]
Unable to reproduce this on Note 8.
I  recommend the user to clear app cache, 
If that doesn't work then backup bookmarks and Bible data and do a fresh install.

**Comment by tuomas2** [comment]
Let's re-open this one if someone else reports. I could not find cause for this from code.
