### ISSUE TITLE
Bookmarks sorting from shorter to longer

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2359]
![16682494690832552229866551856273](https://user-images.githubusercontent.com/5811789/201470306-abc4b656-3f2b-429d-b6a4-d6e5cae0e84e.jpg)

**Comment by agrogers** [comment]
That's a good idea

**Comment by agrogers** [comment]
It should be based not just on verse count but letter count. That is, if I
click a word that has been highighted and that verse is also highlighted,
there is a good chance it is the word that I am interested in most.
