### ISSUE TITLE
Searching for certain words opens a book of the Bible instead

### ISSUE THREAD

**Issue by RuggMatt** [AndBible/and-bible#2380]
**Describe the bug**
Searching for any word that begins with "Co" goes to Colossians instead of opening the results for that word. (E.g. cousin, courage,)

**Bug was found on AndBible version**
Version 4.0.663#b2abfab7b standard release (built 19/11/22 21:48:39)

**To Reproduce**
1. Search for "courage"

**Expected behavior**
Opens result list for courage

**Comment by RuggMatt** [comment]
#2368

**Comment by tuomas2** [comment]
Also prod version in beta channel https://support.andbible.org/scp/tickets.php?id=1681
