### ISSUE TITLE
Support MyBible repositories

### ISSUE THREAD

**Issue by pepaulo** [AndBible/and-bible#2401]
The Extra Modules Registry use a Json file to describe the modules and the adress to download.  It can be hosted in a Dropbox or in other filés server as a repository.

**Comment by tuomas2** [comment]
can you provide specifications or a link to it?

**Comment by pepaulo** [comment]
> can you provide specifications or a link to it? 

The specifications is here:

 https://mybible.zone/en/extra-registries/

**Comment by agrogers** [comment]
I think this is describing a way in which MyBible can import modules via a URL supplied by a user. So essentially they would could supplement our limited list of URLs of authorised providers of modules.  We could use these links to import MyBible modules as well I guess.

https://docs.google.com/document/d/1ZxHHuw7k5BPJ2C0PDacExjfXe8Is11SoREhHGEjrTkU/edit
