### ISSUE TITLE
Show the search button in portrait mode on a phone

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#2402]
I use the search option a lot but to get to it I need to go through the hamburger menu. I would prefer to use a button at the top of the screen. There is not much room there unfortunately. I think I would prefer the search button over the Original Language button.

Request raised here:
https://support.andbible.org/scp/tickets.php?id=1692

**Comment by timbze** [comment]
#195 would probably solve this nicely. Otherwise I don't have a feeling that default buttons will be changed much, unless there's clearly improvement and not bad for existing users.

**Comment by agrogers** [comment]
I think one way to do it would be to allow the user to choose an order for
the buttons. Or perhaps add another gesture to open the search.

**Comment by tuomas2** [comment]
User was satisfied when he got to know that he can access search through main menu. Also I think it is sufficient.
