### ISSUE TITLE
TTS pronunciation issue in FreJND version 

### ISSUE THREAD

**Issue by christubuntu** [AndBible/and-bible#2404]
The word "L'Éternel" is written in all caps (L'ÉTERNEL) in FreJND (French Darby version). The Google TTS can't read it aloud correctly (it pronounces the apostrophe character). Other French versions I've tried dont have this issue since that word is written as "L'Éternel".
Ex. How it's written in FREJND 
![French Darby ](https://user-images.githubusercontent.com/55885756/205453304-c19446dd-413e-4b5b-a9a2-ca244289b87d.jpg)
Compared to the French Ostervald 
![French Ostervald ](https://user-images.githubusercontent.com/55885756/205453359-85ac0f8e-21f9-4e5f-a335-6bc9b12fdc0e.jpg)

**Comment by timbze** [comment]
This could probably be solved by #982 (if that got implemented). I don't think we'd classify this as AndBible bug, but I'll let someone else give their input too.

**Comment by christubuntu** [comment]
I was able to circumvent this issue by importing the MyBible module version of FREJND where that word is in not in all caps.

**Comment by tuomas2** [comment]
Module/tts engine issue/"feature" and as @timbze mentioned, #982 is best fix we could offer (if implemented).
