### ISSUE TITLE
help_contextmenus_text text needs improvements

### ISSUE THREAD

**Issue by didib** [AndBible/and-bible#2406]
Some comments about help_contextmenus_text:
- "Long pressing in opens context menu": What's "in", here? Where? Probably the intention was something like: "Long pressing, in several views, opens a context menu or action mode".
- "Long press on the Bible view to open the action mode for actions affecting the current verse.": IIUC This might have been correct at the time of writing, 17bafe857, but was later changed, no? Now, the menu opens up on a _short_ press, AKA "tap" (and I am still having a hard time translating this rather-new word-meaning to Hebrew - I think just "short press" will be good enough for several years to come). A long press now seems to select the word you are on, allowing changing/extending the selection, and opening a different menu of (partially different, compared to long-pressing) actions.

I am not a native English speaker - not sure about other things such as a missing "a" in e.g. "or delete bookmark".

I don't mind pushing a PR if you want - I suppose for the English texts this is done right in github, correct?

**Comment by tuomas2** [comment]
Yes english, the source language, is done in github, in  app/src/main/res/values/strings.xml

**Comment by tuomas2** [comment]
And PR is welcome, thank you!

**Comment by agrogers** [comment]
I'm happy to have a look at those. I hadn't noticed these before.

**Comment by agrogers** [comment]
I think i have resolved this here: https://github.com/AndBible/and-bible/pull/2973/files
But there are some other issues I think.

That section was relevant in v3.
