### ISSUE TITLE
Hebrew js-side strings are not translated

### ISSUE THREAD

**Issue by didib** [AndBible/and-bible#2407]
When short-pressing/tapping Bible text, a popup is opened, with various actions - Bookmark, Note, My Notes, Share, Compare. The items in this popup are not translated - they appear in English even if some other language is selected.

This is in contrast e.g. with the menu/bar opened for a Long Press, which _is_ translated.

It seems that it's a bug in the code, and not a missing translation - e.g. it seems like the translation for "Bookmark" should have been taken from the language-specific file app/bibleview-js/src/lang/$lang.yaml, item "addBookmark", but despite having this item in e.g. iw.yaml and using Hebrew, it's not translated.

Most likely this isn't specific to this popup. I do not (yet?) understand the code well, but it seems like there is "old" code (in app/src, java/kotlin) where localization does work, and "new" code (in app/bibleview-js, javascript) where it does not. E.g. the same happens if I press "My Notes" on a chapter where I do not have notes - I get the non-translated "No My Notes for this chapter" for noMyNotesTitle, despite having noMyNotesTitle in app/bibleview-js/src/lang/iw.yaml.

Feel free to close if this is a known issue - could not find it in open ones (but can't saw I did an exhaustive search).

**Comment by tuomas2** [comment]
Thanks for reporting this. Will fix this soon. Probably hebrew translation filename should be renamed to iw.yaml -> iw-IL.yaml

**Comment by tuomas2** [comment]
Other languages should work fine.

**Comment by didib** [comment]
Thanks!
