### ISSUE TITLE
Add Heb.Alt to BibleNames in fi 

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2409]
Should recognize hepr abvrev too, not just hebr.

**Comment by tuomas2** [comment]
Seems like transifex does not have at all those keys from BibleNames that are blank in english. So should fix that first somehow...

**Comment by Abde55** [comment]
There was

**Comment by tuomas2** [comment]
Need to fix for 5.0 and fast so that translators can fix this sort of issues.

**Comment by tuomas2** [comment]
Especially important because new Epub support can utilize these abbreviations.

**Comment by tuomas2** [comment]
Urgent part is now done.

**Comment by tuomas2** [comment]
This is fixed now (jsword side)
