### ISSUE TITLE
Selecting a bookmark from my notes menu jumps to my notes... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#241]
What happens:
1) From a Bible tap on menu and select m my notes.
2) select a note
3) tap on the top left menu icon
4) select bookmarks
5) you are brought back to the my note screen.

Expected behavior:
When you are in the private note window,  tapping on menu bar and selecting bookmarks brings up bookmarks. From there selecting a bookmark should take you to that passage in the Bible window.

**Comment by tuomas2** [comment]
Confirmed

**Comment by bvahedy** [comment]
Yes. The reader needs to see the verse before making any notes. We can
assume they want to go to that chapter/verse rather than trying to make a
note for it.

**Comment by tuomas2** [comment]
> Yes. The reader needs to see the verse before making any notes. We can assume they want to go to that chapter/verse rather than trying to make a note for it.

Re-opening for this.
