### ISSUE TITLE
"Find all occurrences" searches in wrong document

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2410]
**Describe the bug**
I don't know how a user can select which document should be searched when clicking "find all occurrences" in a greek/hebrew definition.

I tried doing a search in KJVA, and then press "find all occurrences", but the search again happened in KJV.

The user who reported this can't see where the search is trying to run, but opening the log it shows that it's trying to run in ABPGRK document, which is not where he tried to search.

Reported here: https://support.andbible.org/scp/tickets.php?id=1698

Similar issue #2184

Being able to see (and/or change) which version has been searched in search results screen would help.

**Bug was found on AndBible version**
Build 4.0.667-stable standard release

**Comment by tuomas2** [comment]
Is this something has been recently introduced (possibly in 667) or older bug?

**Comment by timbze** [comment]
I am not sure, I thought opening a search in another version first (like I tried) had worked before but I'm not 100% sure about that either.

**Comment by tuomas2** [comment]
Is this actually duplicate of https://github.com/AndBible/and-bible/issues/2184?

**Comment by timbze** [comment]
1. It's not exactly duplicate, but yes it is 😆 
2. I'm so forgetful 🤕, I can't believe I didn't think of changing the Bible document in links window. My problem was I had no way to make "Find all occurrences" search in another document. But changing the Bible version in links window first, then opening another strongs definition and clicking "Find all occurrences" then searches in that Bible version.
