### ISSUE TITLE
Crash when trying to open workspace selector

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2413]
https://support.andbible.org/scp/tickets.php?id=1697

**Describe the bug**
App crashes when trying to open workspace selector, either by swipe down on title bar or 3-dot menu.
I can swipe left/right on the title bar and it switches between the 2 workspaces.

This happens on a new install. I think a database was automatically restored from Google backup because it let me select "Quick re-download".

**Bug was found on AndBible version**
Build 667-alpha

**Comment by tuomas2** [comment]
Related to workspace colors stuff
```
12-06 08:45:05.024 12875 12875 E AndroidRuntime: FATAL EXCEPTION: main
12-06 08:45:05.024 12875 12875 E AndroidRuntime: Process: net.bible.android.activity.next, PID: 12875
12-06 08:45:05.024 12875 12875 E AndroidRuntime: java.lang.NullPointerException
12-06 08:45:05.024 12875 12875 E AndroidRuntime: 	at net.bible.android.view.activity.workspaces.WorkspaceAdapter.onBindViewHolder(WorkspaceSelectorActivity.kt:99)
12-06 08:45:05.024 12875 12875 E AndroidRuntime: 	at net.bible.android.view.activity.workspaces.WorkspaceAdapter.onBindViewHolder(WorkspaceSelectorActivity.kt:66)
12-06 08:45:05.024 12875 12875 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
```
