### ISSUE TITLE
Disappearing Bookmarks

### ISSUE THREAD

**Issue by Dleemuse** [AndBible/and-bible#2414]
I just noticed this problem yesterday, when looking for a particular bookmark, it had disappeared completely. This lead me to investigate further, at least 8 bookmarks that I know of have disappeared. The problem I have, is that I do not know how many bookmarks have disappeared, I have over 300, so it is hard to tell if others have done so. 

In the list of individual bookmarks, Is it possible to have a feature that shows the number of bookmarks you have?

Thanks,

Debra

**Comment by timbze** [comment]
Does the bookmark show in the dialog if you tap the verse? If you have any labels set to hidden then I think the entire bookmark where that label is on is hidden.

**Comment by Dleemuse** [comment]
Hello Timmy,
No, I do not have any hidden bookmarks, I double checked this.
Thanks,
Debra

Sent from Yahoo Mail on Android 
 
  On Fri, Dec 9, 2022 at 9:13 AM, Timmy ***@***.***> wrote:   


Does the bookmark show in the dialog if you tap the verse? If you have any labels set to hidden then I think the entire bookmark where that label is on is hidden.

**Comment by tuomas2** [comment]
which version are you using?

**Comment by Dleemuse** [comment]
Hello Tuomas,
I tried looking for the version in the AB app itself, couldn't fine it, so started a bug report from the app, this is what it said...
4.0.667#a2f974b88 standard release
Hope that helps.
Debra

Sent from Yahoo Mail on Android 
 
  On Fri, Dec 9, 2022 at 2:02 PM, Tuomas ***@***.***> wrote:   


which version are you using?

**Comment by tuomas2** [comment]
you could send us your database  and tell which bookmark is not displayed?

**Comment by Dleemuse** [comment]
Sorry, I will have to do that if it happens again. I have already replaced them, I was able to reconstruct them exactly as they were, since I had taken screen shots of them to send to a friend.
Debra

Sent from Yahoo Mail on Android 
 
  On Sat, Dec 10, 2022 at 5:00 AM, Tuomas ***@***.***> wrote:   


you could send us your database and tell which bookmark is not displayed?

**Comment by tuomas2** [comment]
Please re-open and give extra info if you happen to be able to reproduce this.
