### ISSUE TITLE
0 search results all the time

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2418]
**Describe the bug**
Search for any word -> 0 results.

**Bug was found on AndBible version**
Build 667 stable and alpha

https://support.andbible.org/scp/tickets.php?id=1721

**Comment by tuomas2** [comment]
I believe this is in alpha version only, right?

**Comment by timbze** [comment]
https://support.andbible.org/scp/tickets.php?id=1712

That is from stable but I am not sure if it is the same issue. It sounds like it opens Bible, for me it opened 0 search results, in alpha.

**Comment by tuomas2** [comment]
Was this already fixed? There was some search related bugfixing in 670.

**Comment by timbze** [comment]
Just tried in 669 alpha which I have installed now and search works... I don't know what caused the issue or if it never worked in 667, but that's where I had the issue. So I think we can close this and I'll reopen if issue comes up again.

**Comment by timbze** [comment]
I just remember that I did have this issue in 669 when I first updated. This is weird... Will see if issue comes back.

**Comment by tuomas2** [comment]
I think 93897f67ea19c3f8c59a34ffe2ecc19e9e5b8018 fixed it?

**Comment by timbze** [comment]
> I think [93897f6](https://github.com/AndBible/and-bible/commit/93897f67ea19c3f8c59a34ffe2ecc19e9e5b8018) fixed it?

It's possible but that commit is in 670. I'm still on 669 where it's working now (but wasn't before). I don't know how the issue started so don't know how to reproduce.
