### ISSUE TITLE
Allow saving logcat to file (not just share)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2421]

**Comment by Noitarud** [comment]
Mine seems to do that already.
![Screenshot_20230420-012140](https://user-images.githubusercontent.com/98794719/233124187-825ed72c-7126-4bdf-abf6-6cd1c01f8420.png)

But it didn't always do that, see empty drawer in #2143 (maybe I happened to install an app?)

**Comment by tuomas2** [comment]
I think this was implemented
