### ISSUE TITLE
Searching for the mat goes to Matt 0

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#2423]
This bug occurs in 669 alpha build and may also exist in 669 standard and previous builds:
Reported by this user:
https://support.andbible.org/scp/tickets.php?id=1723

When searching for the word matt or Matthew the result goes straight to the bible window with the whole book of Matthew selected and Bible ref displays Matthew 0.
From here pressing the back button to go back to the search window does nothing, it seems to be locked up in this mode.

**Comment by ildar** [comment]
Sounds like a feature, not a bug ;-)

**Comment by tuomas2** [comment]
Yep but also it reveals an issue: how to find occurrences of "Matthew" if user wants to?

**Comment by tuomas2** [comment]
@bvahedy suggested a workaround:

> that's a bug, try this search Matth*
> the astrix is a wild card. It should find all the words starting with matth.

 Need to think if this needs to have a fix or not. I love the ability to quickly type the reference in search window and get quickly to the passage. Perhaps we should require also at least chapter number to be mentioned?

**Comment by timbze** [comment]
> Perhaps we should require also at least chapter number to be mentioned?

That was my first thought. Probably be a good idea

**Comment by bvahedy** [comment]
It should not select the whole book of Matthew. Also when you hit the back button, it should go back to the find window.

**Comment by bvahedy** [comment]
> It should not select the whole book of 

It's there any fix to the following issues?
 
Matthew. Also when you hit the back button, it should go back to the find window.

**Comment by tuomas2** [comment]
fixed in 670.

**Comment by bvahedy** [comment]
Thank you.
