### ISSUE TITLE
Make Chapter 0 more visible/selectable

### ISSUE THREAD

**Issue by Dob4115** [AndBible/and-bible#2425]
I was searching for a word that is the same as the bookname and was taken to chapter 0 of the book. While I think this is a bug (see other issue, #2424) I would like a way to get to chapter 0 if it exists. 

Maybe, if a Bible has chapter 0 text, the chapter list could just have a chapter 0?

**Comment by tuomas2** [comment]
There are book introductions written in chapter 0 in some documents. For example ESV with strongs (old mod that we can't distribute). That content is shown above chapter 1 and it works fine.
