### ISSUE TITLE
When in my notes, speak settings has the old style settings.... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#243]
1) go to my notes and select a note.
On this window if you tap the ear icon it just reads the book name, chapter, verse.

2) if you long press on the speak ear icon, the settings are the old style settings.

*Expected* behavior:
We could either remove the ear icon when in the private note window.
Or
Tapping ear icon should read what the private note text says and fix the speak settings items.
![screenshot_20190125-202533_and bible](https://user-images.githubusercontent.com/46405809/51782658-ddf38d00-20e0-11e9-9805-b6fc23f976c2.jpg)

**Comment by tuomas2** [comment]
Confirmed
