### ISSUE TITLE
MyBible: Not found in this document

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2431]
> If I close AndBible and open it when I was last using this module, i get the "Not found in this document" error. If I select if again from the document list, it works fine. :)

https://support.andbible.org/scp/tickets.php?id=1706

**Comment by RuggMatt** [comment]
It seems for some reason the module (NASB_20) is somehow categorized as both commentary and Bible. If I open it from the commentary list, it gives the "not found in document* error. 

![Screenshot_20221228-071110.png](https://user-images.githubusercontent.com/8870594/209824911-cfab20cd-7e48-42d5-8b67-15d7ebdb8798.png)

**Comment by tuomas2** [comment]
Can you list files under your mybible folder? Could there be another file that would map into same document id?

**Comment by tuomas2** [comment]
@mattschlosser ^

**Comment by RuggMatt** [comment]
There is a separate commentary file for the NASB. I guess this is not supported by AndBible? Removing this file seems to have fixed the issue. 
```
-rw-rw-r--  1 u0_a76  ext_data_rw 57638912 2022-12-08 07:59 ESV-c.commentaries.SQLite3
-rw-rw----  1 u0_a246 ext_data_rw  1867776 2022-10-17 15:12 MIQNT.SQLite3
-rw-rw----  1 u0_a246 ext_data_rw  6317056 2022-10-17 15:12 NASB'20.SQLite3
-rw-rw----  1 u0_a246 ext_data_rw  1574912 2022-10-17 15:12 NASB'20.commentaries.SQLite3
-rw-rw----  1 u0_a246 ext_data_rw  5799936 2022-10-17 15:12 NCV.SQLite3
-rw-rw-r--  1 u0_a76  ext_data_rw  5805056 2022-12-08 07:53 NIV'11.SQLite3
-rw-rw----  1 u0_a246 ext_data_rw  5988352 2022-10-17 15:12 NLT'15.SQLite3
```

**Comment by tuomas2** [comment]
It supports commentary format too. Maybe its easier if you send me those files so I can debug.

**Comment by tuomas2** [comment]
Accidentally these changes were left out from new MySword support so better to do it there as well. 114fb954b5eb900e5fe8fedb47404320bbe3f4fc
