### ISSUE TITLE
Notify user about missing TTS engine

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2450]
I discovered i had disabled some google things (google play services/accessibility suite) which in turn caused the only option in the speech Preferred Engine list to be removed. Installing new engine (called eSpeak) fixes it.

I will leave the issue open in case you want to make the error less ambiguous, though error received may be too ambiguous to report specificly, so maybe an adequate message should be "Speech failed, check your speech engines".

_Originally posted by @Noitarud in https://github.com/AndBible/and-bible/issues/2143#issuecomment-1373009447_

**Comment by Noitarud** [comment]
Found #2043, duplicate?

**Comment by tuomas2** [comment]
agree, closing as duplicate of #2043
