### ISSUE TITLE
Export search results

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#2454]
Requested by Graham (https://support.andbible.org/scp/tickets.php?id=1752)

> An option to export the Find results to HTML (as available with open all references.)

It would be good to keep the highligted word.

**Comment by tuomas2** [comment]
If we get one day search results to bibleview window (which is planned in #611) then this is easy to implement.

**Comment by tuomas2** [comment]
Now it is possible already, through sending results to a window and exporting window content
