### ISSUE TITLE
Window button / buttons on top right disturbing some users

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#246]
Quite many people are disturbed by this. Good ideas are welcome.

Ideas:
- Perhaps a setting (default: false) that would enable alternative triggering of window button visibility: you need to swipe from left border.
- Setting that would disable window buttons alltogether (in options menu, #269)

Further to think about:
- Should we auto-hide window buttons or not in non-fullscreen mode? Should this be optional?

**Comment by tuomas2** [comment]
Quite many people are disturbed by this. Good ideas are welcome.
Perhaps a setting (default: false) that would enable alternative triggering of window button visibility: you need to swipe from left border.

**Comment by tuomas2** [comment]
Multiple windows make overlay necessary (each window need its own button). 
Toolbar has very limited space and there are many very important buttons already.

One option would be to optionally (via settings option) disable these buttons in full screen mode.

**Comment by timbze** [comment]
It might be a better idea to have the overlay button at the bottom right of the screen? The eyes usually look more to the top. It is annoying that the button keeps popping up every time the screen is scrolled.
Also, maybe it would work to have the button hide automatically the first time, but then not show up again till the user taps the screen?

**Comment by ericjding** [comment]
I think @timbze is right that positioning probably has an effect. Beyond that, why can't the overlay button only be visible when AndBible is in multiple-window mode? Sorry if I'm asking the obvious; for my part, I almost never use multiple-window mode, so I've never felt the need for the functions of the overlay button. That doesn't mean AndBible doesn't need it, but doesn't it suggest at least one use case where it's not necessary for it to be visible?

**Comment by timbze** [comment]
I think @ericjding has a good point about why is the button even needed when it's not in multi-window mode? Maybe there could be a mini version of a material UI + (plus) button at the bottom right of the screen when it's in single screen mode. Then again if the user just wants to have a full screen to read, the button should not be visible at all. Anyway, these are ideas and I hope we can come to a good solution.

**Comment by tuomas2** [comment]
Thank you guys for throwing good ideas! I implemented the + button on bottom-right as suggested. Will be in next beta.

**Comment by timbze** [comment]
Thanks for the many great changes Tuomas!
To my taste, the button on the right bottom should just have a + sign, and not the circle around it, but maybe I'm wrong.
Also, I still think it might be more user friendly if the + button (and the 3-line window option button while in multi-window view) did not pop up at all while in full screen mode.
That's just my ideas, but for my part it's fine like this.

**Comment by bvahedy** [comment]
Not clear what was changed, can't really see any problems.
