### ISSUE TITLE
Chained links windows, followup

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2469]
Followup to #942 / #2469

- If a window is not links window, open links in the same links window. Linsk window id to be stored in workspace level and window id on window level will stay null.
- If links window, then open links in another links window, that is determined by links window id stored in window level.
- In a normal window, we can also with long click decide to open link in a NEW links window. Thus making a side-chain of links windows. Then we will store links window id on window level.
- Because links windows are chains, we could indicate it somehow in UI with a number (1, 2, 3, 4 or if there are multiple chains 1.1, 1.2, 2.1, 2.2..., or A1 A2 A3, B1, B2, B3...).

**Comment by tuomas2** [comment]
Now it is like this:

W1 -> L1 -> L2 -> L3
W2 -> L4 -> L5 -> L6

Changing to this:

![20230121_102726](https://user-images.githubusercontent.com/5811789/213858791-efd937ae-6c13-40a8-a3d0-051b5fc9b17e.jpg)

Something to try out: 
- If user minimises last window of the chain (L3 here) window will be closed completely (idea is that links windows are more or less temporary and user can still click the link again to open the window... this way we will save space in links window button area).
- If user minimises not last window of the chain (L2 for example) and more windows are in chain after that (window L3 here) still open, it will be minimised, not closed.

**Comment by agrogers** [comment]
Can do a quick video of this? I think what you are aiming for is to have
any number of master windows synced to any number of child windows. Is that
right?

**Comment by tuomas2** [comment]
Hmm, this is about where links are opened, not about syncing. I can make a video when I have time. Though it's probably coming to alpha build soon as well.

**Comment by tuomas2** [comment]
Here's video https://www.youtube.com/watch?v=4I-EDxVbUlw

**Comment by tuomas2** [comment]
alpha-675 includes this too

**Comment by agrogers** [comment]
Watched it, thanks. So basically a normal window opens links in its own
links window not in a common links window.

**Comment by tuomas2** [comment]
normal windows (W1, W2,...Wn) do open links in a common links window (L1) but links window then opens links in another links window (L2) and that opens in another links window (L3) etc... creating a chain of links windows.
