### ISSUE TITLE
Default Language changes after a find or creating index...

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#2475]
Running calculator 673.4 alpha; somehow after a find, the result of the find switches language to Hebrew. So all the bible book names are in Hebrew. I have to go into app pref. to change the language back to English. This has also happened a couple of times with the regular alpha build but I don't know how to duplicate it. Hopefully the logcat will help in trying to find what causes this problem.
Here is the ticket ref#:
https://support.andbible.org/scp/tickets.php?id=1772

**Comment by bvahedy** [comment]
May have been fixed by #2460 in 675 build. These two bugs seem very similar in nature. You can close this ticket if you can't duplicate it.

**Comment by tuomas2** [comment]
This was fixed indeed.
