### ISSUE TITLE
Issue when switching from multidoc to bible 

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2478]
1. Open multidoc. One way to open multidoc is to have footnote that has multiple references and click "open all references"
2. Try to change to bible document
-> stays in multidoc.

Reproduced in prod version (674)

**Comment by tuomas2** [comment]
I'm not sure if this is reported somewhere already, if you remember please help me find possible duplicate...

**Comment by timbze** [comment]
Fixing this issue undos #1198... but maybe that's fine. #1198 is not such a big issue now since the link window remembers the last set version instead of always opening in the version from where it's opened.

**Comment by tuomas2** [comment]
Hmm good point. This really felt like a bug to me and I think it is more important to have this fixed than #1198.
