### ISSUE TITLE
Hilight current verse (by boldening verse number etc.)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#248]

**Comment by agrogers** [comment]
An option for this might be nice. But i have never really needed it. It shows the verse reference in the title. I think the verse number might also be off screen which means highlighting it (the number only) possibly not that helpful. Highlighting the whole verse might be a little intrusive. Could be an option though.

**Comment by tuomas2** [comment]
I don't think this is valid any more. I have added highlighting the verse after clicking link, perhaps this was in my mind when I created this issue.
