### ISSUE TITLE
Please add my private MyBible repository mb.igr.bible to your AndBible.

### ISSUE THREAD

**Issue by viktor-zhuromskyy** [AndBible/and-bible#2486]
Please add my private MyBible repository to your AndBible. The JSON file is in MyBible format and currently it is used for MyBible users. The modules are constantly updated, so please, if you do me and my readers a favor, do not put my modules into your repository, just grab the info from my JSON file.

My MyBible repo file is located at http://mb.igr.bible/

Also, please remove my super old module rusvzh since it is my very first Bible project and actually it is Synodal Translation with Strong's numbers. My current MyBible modules are more advanced and mature.

Thanks a log and God bless!

_Originally posted by @viktor-zhuromskyy in https://github.com/AndBible/and-bible/issues/2122#issuecomment-1409875890_

**Comment by tuomas2** [comment]
Level is "Please note that this is unsupported and experimental feature. It might or might not work. Use at your own risk!".  (https://github.com/AndBible/and-bible/wiki/MyBible-module-support). Please report bugs with screenshots and reference to particular module and chapter/verse (one ticket per bug report).

**Comment by tuomas2** [comment]
Many modules work well by now, but many might not. But also many issues are rather easy to fix, if they are just reported to us and we can reproduce them.

**Comment by tuomas2** [comment]
why closed this?
