### ISSUE TITLE
Support for MyBible & MySword repositories

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2487]
- [x] #2401 
- [ ] MySword repositories (if any)

Also related:
- #2122
- #39

**Comment by tuomas2** [comment]
MyBible repositories spec: https://mybible.zone/en/extra-registries/
Does anyone know if MySword has repositories specified somewhere somehow?

**Comment by cmahte** [comment]
Long ago I read a description of a Mysword module for developers. The
modern equivalent seems to be here:

https://www.mysword.info/modules-format

But not 'repo' for Mysword. When I looked (2005-2010), each module is a
separate download, completely self contained.

**Comment by tuomas2** [comment]
MyBible repositories are now supported in alpha version and MySword repository format is unknown.
