### ISSUE TITLE
Too easy to remove bookmark labels

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#250]
Add confirmation dialog

**Comment by timbze** [comment]
~~Obsolete in 4.0~~

**Comment by tuomas2** [comment]
Or not obsolete but implemented in 4.0. Confirmation dialog added.

**Comment by timbze** [comment]
I don't think removing "labels" has a confirmation dialog, but it's not really needed for the way it operates now.

**Comment by tuomas2** [comment]
I think it is necessary. If you remove bookmark label, it will be removed from all bookmarks and associated study pad notes will be removed. It's quite big impact.

![Screenshot_20210804_185309](https://user-images.githubusercontent.com/5811789/128213272-fecf1a62-d726-4f78-a4b5-aa1a9d10163b.png)

**Comment by timbze** [comment]
Oh, I agree. I was thinking only about removing a label from an existing bookmark. 

This is good and needed
