### ISSUE TITLE
Allow using multiple strongs dictionaries at once

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2512]
Should be easy to implement with MultiDocument.

Strongs dictionary configuration in app preferences should allow multiselection.

**Comment by tuomas2** [comment]
![image](https://user-images.githubusercontent.com/5811789/227215018-214101df-b7db-439b-899e-ed7197ba7565.png)

![image](https://user-images.githubusercontent.com/5811789/227215108-e19f8cc3-d44a-49bc-af62-b8dd7322360b.png)

**Comment by agrogers** [comment]
That's a nice feature. Good job.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
