### ISSUE TITLE
Creating links to bible verses broken in notes...

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#2515]
Affects alpha and calculator build: 
When Trying to create a note and taping on the icon to select a bible passage, it used to create a link to that passage, but now if there is any word before the passage,  it no longer makes the selected passage a link. 
You can put plain text after the link but not before.  Any attempt to place any text before the link will cause the link to become plain text.

**Comment by tuomas2** [comment]
can you explain step by step, having difficulty to understand the problem

**Comment by bvahedy** [comment]
1) Tap on verse
2) tap on the note icon
3) in the note window type test then tap on the book icon with the cross on it. 
4) in the "enter bible ref" window tap on the little hand (top right) 
5) select a chapter and verse
The selected passage briefly becomes a link then it removes the link. 
But if the link you create is at the beginning of the line then it remains a link.

**Comment by bvahedy** [comment]
Here is a screen recording: 

https://user-images.githubusercontent.com/46405809/218326605-5fce646f-7bfc-40e0-9925-eab6319b6eb2.mp4

**Comment by bvahedy** [comment]
Could be that the Samsung keyboard is taking the link out.

Ticket ref. https://support.andbible.org/scp/tickets.php?id=1786

**Comment by bvahedy** [comment]
This is not happening anymore, so I'll close this.
