### ISSUE TITLE
add more sync groups

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2516]
maybe total 6 or 8 would be ok

**Comment by agrogers** [comment]
Could be OK. I can't see needing more than 4 on a phone.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Probably rare use cases only need more groups. But if one wants to have bilingual setup with many windows, it might be needed.

**Comment by tuomas2** [comment]
Added number to 6
