### ISSUE TITLE
Advertise MySword and MyBible support in play description

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2519]
>  Vast library of documents: Bible translations, theological commentaries, dictionaries, maps, and
>  christian books, totaling over {{total_documents}} documents in over {{total_languages}} languages,
>  legally distributed by Crosswire and other SWORD repositories. 

-> 

 Vast library of documents: Bible translations, theological commentaries, dictionaries, maps, and
 christian books, totaling over {{total_documents}} documents in over {{total_languages}} languages,
 legally distributed by Crosswire and other SWORD repositories. In addition, AndBible provides support for 
 MyBible and MySword module formats for Bibles, commentaries and dictionaries.

**Comment by agrogers** [comment]
I would change 'application' to 'AndBible'

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by timbze** [comment]
Also I think the word Bibles should be capitalized

**Comment by tuomas2** [comment]
Also: epub!

Also possibly other new features!
