### ISSUE TITLE
MyBible modules restores in calculator build but are not visible in bible list...

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#2521]
Affects calculator alpha 680.4 build: 

When restoring a mybible module. It displays that the restore was successful.  But when looking in the list of bibles, they are not on the list. There is no way to view them. However, when trying to restore the same zip module, the app requests to override the files, which means they are somewhere within the app structure.

**Comment by tuomas2** [comment]
really good that you are testing calc. it was forgotten here...

**Comment by agrogers** [comment]
Yeah, good job Ben. I do very little of this testing!

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment]
I have to say you guys have done a great job in protecting the users and hiding everything to the point where the users can't even do a screenshot or video recording of AndBible screens. This is impotent in countries where they check phones for bible related files.

**Comment by agrogers** [comment]
By 'you guys' you mean 'Tuomas' ;-)  Oh, I made the icon :D

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment]
You are a developer also, it's not the size of what one does rather the fact that they do it from the heart. I'm thankful for all who contribute. So, yes, you are one of the guys.

**Comment by agrogers** [comment]
Aw, thanks :)

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment]
Verified fixed in 683.1 build.
