### ISSUE TITLE
Should links window sync be disabled on link click? 

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2522]
**Describe the bug**
When I enable sync on links window I expect sync to turn off when I click another link that opens a new reference.

Not sure if my expectations make sense...

I'm on version 680 alpha.

**Comment by tuomas2** [comment]
I found it to make sense if I make another window intentionally that is synced with links window. did it do something that felt weird?

**Comment by timbze** [comment]
Oh, that makes sense. No I didn't really put it to use, just tested and felt weird, but actually if I would use it, it would make more sense to sync with a second group of windows. Then I think it would be correct.
