### ISSUE TITLE
Cross-translation verse-per-line spacing

### ISSUE THREAD

**Issue by UnderSampled** [AndBible/and-bible#2527]
**Is your feature request related to a problem? Please describe.**
When referring to multiple translations while reading through a passage, it is helpful to to have two synced windows with different versions. Showing them in verse-per-line mode gets close to lining them up, but different trabslations, especially to different languages, may have different delineation and line length. This means that verses lower on the page will not line up, making it more difficult to compare longer passages.

**Describe the solution you'd like**
Include an option for verse-per-line reflow to add space to shorter versions of a verse so that all open synced windows will share the same vertical spacing to line up the verses across windows.

**Describe alternatives you've considered**
The comparison view is very helpful, but is less useful for quickly reading passages, especially when reading along with someone else.

**Additional context**
Screenshot of two windows which would benefit from this feature: 
![Screenshot_20230219_111144_Bible Study](https://user-images.githubusercontent.com/328009/219974274-3018068d-61e2-4604-9e35-121deac51c7c.jpg)

**Comment by tuomas2** [comment]
Should all verses be equal length (in pixels / mm's)?  What to do if a verse exceeds the length? What to do if window width is resized? 

I like the goal of this feature request but not sure how to implement it nice way. Any reference implementations in other AB-like apps?

**Comment by UnderSampled** [comment]
I haven't used any other app to know! I've been using AB for something like a decade now!

I was picturing something akin to HTML tables in terms of layout and flow: each row would be the height of the tallest cell in that row, and each cell would reflow independently within.

To impliment, one idea would be to add, per-verse, an empty spacer after each window's copy of the verse, set to the height of tallest copy of the verse minus the height of that window's copy. For the window with the tallest copy, this would come out to be zero. If you can determine the normal height of the content before adjustments, you might be able to just add the spacing to the height of the verses.

**Comment by tuomas2** [comment]
Closing this, as #2754 is feasible implementation of this
