### ISSUE TITLE
Luther 1912 | Writing error in Jesaja 13:18

### ISSUE THREAD

**Issue by FreedomIsAChoice** [AndBible/and-bible#2538]
In the Luther 1912 Bible version, in the

book of Isaiah, 
chapter 13, 
verse 18, 

the expression 
"**fear** of the body" 
is written instead of 
"**fruit** of the body" 

(in German, of course).
Please correct.
Thank you in advance.

In der Bibelversion Luther 1912, im Buch Jesaja, Kapitel 13, Vers 18 steht der Ausdruck "Furcht des Leibes" anstatt "Frucht des Leibes" (natürlich in deutscher Sprache).

**Comment by timbze** [comment]
Please see [the wiki](https://github.com/AndBible/and-bible/wiki/FAQ#i-found-text-issue-in-one-of-the-bible--commentary-etc-modules-in-andbible). I checked that both the EBible and CrossWire Luther 1912 modules have the same issue. But they (EBible and CrossWire) are the ones who will have to fix it. We are not the module maintainers.
