### ISSUE TITLE
Warning for modules that have problems

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2540]
Example: In StrongsGreek from CrossWire, the links to other strongs numbers within a definition don't work. We have received a lot of emails about links in Strong's definition not working.

Another example, the module OEB is outdated in CrossWire's repo, but eBible is up-to-date.

It would be more helpful to have a specific message if there's a problem with a module, but that would be harder to maintain for more messages. I guess it could just be in the language that the module is in though, if someone wants to use StrongsGreek that would usually mean they know English (I guess).

The module could also just be removed by us, but that removes the option from those who would like to try it. Or there could be another setting to "Show non-recommended modules".

**Comment by tuomas2** [comment]
Good idea. Similar implementation as for recommended documents.

**Comment by dbell154** [comment]
A related issue that I encountered was that some bibles have errors when looking up strongs. For example BIBdraft Gal 5:22, the word gentleness causes the strongs window to hang up. Other bible versions work okay. 
I expect that bible to have problems but it would be good if you could trap the error and display a message.

**Comment by tuomas2** [comment]
Need to have also version number specified for bad documents.

Should we just hide bad documents in download view?

**Comment by tuomas2** [comment]
Making it optional. Either hide or warn. Configurable via [bad_documents.json](https://github.com/AndBible/data/blob/master/bad_documents.json).

**Comment by tuomas2** [comment]
![image](https://user-images.githubusercontent.com/5811789/227253367-597973e2-1fc4-4972-ab8e-6ce6e44cdd54.png)

**Comment by tuomas2** [comment]
Please make pull requests in data repository towards https://github.com/AndBible/data/blob/master/bad_documents.json if changes need to be made.

**Comment by timbze** [comment]
I think just the red frown face will make people confused about what it means.

I think it would be sufficient to just have bad documents file, and hide them by default, then add setting in 3-dot menu to show also "bad documents". Then have some "not recommended" phrase or icon a bit like we have for recommended when user enables "bad documents"

The menu could be named "Show non-recommended documents" or "Show problematic documents"

**Comment by tuomas2** [comment]
Need to improve...

I was thinking if I put that warning icon and when user clicks info button, he will see warning text first there.

**Comment by dbell154** [comment]
A yellow triangle caution may look less ominous than the red face.

**Comment by tuomas2** [comment]
We have red triangle caution for download failures, so I was thinking it might be confusing.. hmm

**Comment by agrogers** [comment]
What if you just change the document icon to red?

**Comment by tuomas2** [comment]
maybe thumbs down icon? 👎

**Comment by tuomas2** [comment]
![Screenshot_20230324_092142_Chrome](https://user-images.githubusercontent.com/5811789/227452318-7236a5e5-09b6-4eb6-b923-97f7532a2e9e.jpg)

**Comment by tuomas2** [comment]
Now better?

![image](https://user-images.githubusercontent.com/5811789/228572728-7bbfff36-f063-44de-b081-9b766481f266.png)

![image](https://user-images.githubusercontent.com/5811789/228572795-b3c12ca0-9030-4e82-813a-b221b32974a7.png)
