### ISSUE TITLE
Window button color problem in dark mode

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2545]
![Screenshot_20230220-180152_Bible Study (1)](https://user-images.githubusercontent.com/5811789/225571454-a762c730-98f6-4d20-8ea9-3e34bbdb30a6.jpg)

![Screenshot_20230220-180659_Bible Study](https://user-images.githubusercontent.com/5811789/225571510-f3b91349-81a2-4027-9ad7-adb8faee6874.jpg)

![Screenshot_20230220-181152_Bible Study](https://user-images.githubusercontent.com/5811789/225571537-84d64c99-ac62-4bd5-8ed8-3f82e5c04043.jpg)

![Screenshot_20230220-181807_Bible Study](https://user-images.githubusercontent.com/5811789/225571566-a1e9649c-be0d-468f-8e18-7add56064dba.jpg)

![Screenshot_20230220-180152_Bible Study](https://user-images.githubusercontent.com/5811789/225571598-607d07d9-8571-4e3d-a10e-662cccde7ffd.jpg)

https://support.andbible.org/scp/tickets.php?id=1790

**Comment by tuomas2** [comment]
I have noticed this too Quick fix is to restart app. I have tried to fix it but not easy because it is somehow in the way Android handles night/day changes.

**Comment by agrogers** [comment]
I rarely use night mode but i seem to recall seeing this too. I will have a
look at it.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Fixed in Beta (develop branch).
