### ISSUE TITLE
Chapter number font size is too small

### ISSUE THREAD

**Issue by deeeseee** [AndBible/and-bible#2548]
**Is your feature request related to a problem? Please describe.**
When I'm scrolling through a book of the bible on the app, it's difficult to see which chapter I'm in because the chapter numbers are too small. In fact, they appear to be the same size as the verse numbers. In every paper bible the chapter number is many times larger than the verses number.

**Describe the solution you'd like**
Since a chapter number is a much larger category than a verse number, chapter numbers should be at least 4-5 font sizes larger than verse numbers, so that it's easier to see the chapter numbers when scrolling through a book.

**Describe alternatives you've considered**
The chapter and verse reference is listed at the top while scrolling, but I would much rather be able to glance at the content that is scrolling to determine when a new chapter is beginning.

**Additional context**

**Comment by tuomas2** [comment]
Could try how it looks if we make it a bit larger or make it with bold letters etc.

**Comment by agrogers** [comment]
I looked at changing the chapter style as well - not just the size - but I
dont think it was using a CSS class. I thought i could just change it in
CSS. This seems like the logical way to do it - then I think it could
become an add-on... is that correct? I wanted to try putting a larger
chapter number in a coloured circle... I remember seeing something like
that on another app somewhere.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
It's done in Chapter.vue. I agree that Chapter.vue should be changed so that styling can be done with pure css changes.

**Comment by deeeseee** [comment]
Thanks for looking at this! A larger number in a circle would also be fine, as long as it's more easily visible while scrolling.

**Comment by tuomas2** [comment]
> I looked at changing the chapter style as well - not just the size - but I dont think it was using a CSS class. I thought i could just change it in CSS. This seems like the logical way to do it - then I think it could become an add-on... is that correct? I wanted to try putting a larger chapter number in a coloured circle... I remember seeing something like that on another app somewhere.

There is css class for this, i.e. `chapter-number`. It was scoped so changing it was not easy. Removed scoping so css is now possible.

Tried quicly making font bigger but was disturbing to my eyes so maybe not making it default.

**Comment by tuomas2** [comment]
If @agrogers you would like to make an add-on css module, we can release it in AndBible repository.

**Comment by tuomas2** [comment]
Fix will be released in next stable (684+)
