### ISSUE TITLE
NETfree foot note empty (in stable) / disappear (in develop)

### ISSUE THREAD

**Issue by Adriankhl** [AndBible/and-bible#2550]
**Describe the bug**
Before https://github.com/AndBible/and-bible/pull/2503, there are footnotes in NETfree bible (tested at https://github.com/AndBible/and-bible/tree/7e347e3695032d012aa61007174c6524917064d5).
However, there footnotes are buggy. The first few footnotes at the beginning of the chapter work, but the later footnotes become a copy right statement ("The Bible.org ministry has provided the NET...") and then become completely empty.

After https://github.com/AndBible/and-bible/pull/2503, say at https://github.com/AndBible/and-bible/tree/52907256867e670316c96732f2e17148f13b3c86, the NETfree footnotes completely disappear.

**To Reproduce**
1. Choose NETfree bible
2. Check footnote

**Smartphone (please complete the following information):**
 - Device: Pixel 4a (5G)
 - OS: Android 13 (graphene os)

**Additional context**
I was trying to fix the problem since I saw the problem in the stable version, and it is funny to see that the footnotes disappear in the develop version. Seems like NETfree footnote is not handled properly in the app, I am happy to help fixing this but it would be great if someone could give me some insights on how to locate the problem :smile:

**Comment by Adriankhl** [comment]
The disappearance of the footnote is caused by the `isFootNote.value` here
https://github.com/AndBible/and-bible/blob/94bad5bb77608fdd6d73b876808736646be89d1f/app/bibleview-js/src/components/OSIS/Note.vue#L112-L114

**Comment by Adriankhl** [comment]
One of the problem is that the type is `undefined`.
The footnotes reappear again if I change this:
https://github.com/AndBible/and-bible/blob/94bad5bb77608fdd6d73b876808736646be89d1f/app/bibleview-js/src/components/OSIS/Note.vue#L81
to
```
const isFootNote = computed(() => {
        console.log("Footnote type: " + props.type);
        return ["explanation", "translation", "study", "variant", "alternative", "x-editor-correction"].includes(props.type!) || (props.type === undefined);
    }
);
```

**Comment by Adriankhl** [comment]
Ah I see the problem, the free version of NET only provides a limited amount of notes, so the empty notes in the stable branch is the correct behaviour. In this case, should we re-enable the limited notes in the current develop branch?

**Comment by tuomas2** [comment]
Thanks for investigating this! Found the bug in Note.vue and fixed it. `<note>` tag without type attribute was not shown at all. Now it is considered as a footnote.
