### ISSUE TITLE
Red Letter Bleeding

### ISSUE THREAD

**Issue by RahniJS** [AndBible/and-bible#2555]
**Describe the bug**
The red letter formatting is bleeding outside of Jesus's dialogue.

**Bug was found on AndBible version**
![Screenshot_20230331_073656_Bible Study](https://user-images.githubusercontent.com/129511712/229110131-c38b5277-b6b9-4224-ab85-937109e884d0.jpg)

**To Reproduce**
1. Go to menu
2. Click on red letter
3. Scroll down to Luke chapter 5
4:36
5. See error

**Expected behavior**
Red letter text should only be limited to Jesus' dialogue.

**Screenshots**
![Screenshot_20230331_074011_Bible Study](https://user-images.githubusercontent.com/129511712/229110776-225570c9-d07f-4464-87af-a42b7791e155.jpg)

**Smartphone (please complete the following information):**
 
![Screenshot_20230331_074133_Settings](https://user-images.githubusercontent.com/129511712/229111069-29aaa1e7-bad4-4422-a934-68fadcd0492c.jpg)

**Comment by tuomas2** [comment]
Suspecting module issue. NASB has issues... Should [report to crosswire](https://github.com/AndBible/and-bible/wiki/FAQ#i-found-text-issue-in-one-of-the-bible--commentary-etc-modules-in-andbible)

**Comment by timbze** [comment]
There's a similar issue where I have now added this screenshot.

https://tracker.crosswire.org/browse/MOD-428
