### ISSUE TITLE
Support devotional document type

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#256]
After a successful install of a devotional from a zip file,  there is no way to view the devotional.
Downloaded sme and daily zip files from below:
http://www.crosswire.org/sword/modules/ModDisp.jsp?modType=Devotionals

Installed zip file from the side menu.
After install using "choose document"  >english> drop down menu displays Bibles/books/dictionary but doesn't contain devotionals.

**Comment by tuomas2** [comment]
Related #238

**Comment by tuomas2** [comment]
I don't think this has ever been possible. 
Not sure if devotionals have something special or are they just like general books?

**Comment by bvahedy** [comment]
They are like dictionaries or general books, it loads them find, just need
a menu item to display them.
I have Josephus as a book and it reads fine.
I'm not crazy about devotionals, they are for those who don't like to read
the Bible for themselves. But who am I to judge.
It's your call wether you want to implement this option or not.

**Comment by tuomas2** [comment]
I checked this a little and seems like daily devotionals are bit more than just general books (use specific driver etc). As there are only few books, I will leave this for now, but if general interest arises, we can consider implementing this. Marking as wont fix for now.

**Comment by agrogers** [comment]
I implemented this a while back. My wife and I use Our Daily Bread and I got tired of going to the website in chrome. It works well for me. I had collected more than a few online devotionals which I thought I might include as options but haven't done that yet. The page is displayed in a panel that slides up to fill the screen. Calculator icon was a placeholder for the icon of the website.

![IMG_20230810_204247.jpg](https://github.com/AndBible/and-bible/assets/13920678/7d2b1d52-de4a-4e46-a70d-c27ccee42024)

![Screenshot_2023-08-10-20-37-25-134_net.bible.android.activity.nextagr.jpg](https://github.com/AndBible/and-bible/assets/13920678/68b6d347-de19-4ddb-a44b-852d5754a842)

**Comment by LAfricain** [comment]
>I implemented this a while back.

@agrogers I don't understand, how can I have this option? I can't see it on my Andbible. If you code it can you push an merge request?

**Comment by LAfricain** [comment]
@agrogers Please can you answer my question?

**Comment by tuomas2** [comment]
It's his own branch and not in official AndBible. This is sort of feature that is not feasible to be included in AndBible (uses 3rd party website as far as I understood it correctly). 

Support for devotional type of sword document  could in principle be implemented (or support for MySword/MyBible devotionals as well).
