### ISSUE TITLE
ReadTheDocs should redirect to stable documentation

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2567]
When going to https://andbible.readthedocs.io/, it redirects to latest: https://andbible.readthedocs.io/en/latest/

I think it should redirect to stable: https://andbible.readthedocs.io/en/stable/

I think this must be set in ReadTheDocs admin settings. According to ChatGPT (might not be 100%):
> Go to the readthedocs.org website and log in to your account.
Select the project for which you want to change the default version.
Click on the "Admin" button located on the top-right corner of the project page.
In the left-hand menu, click on "Versions".
Click on the "Edit" button next to the version you want to set as default (e.g., "stable").
Scroll down to the "Advanced Settings" section.
In the "Default Version" dropdown menu, select the version you want to set as the default (e.g., "stable").
Click on the "Save" button to save the changes.

**Comment by agrogers** [comment]
Yeah, that is a good idea. I have updated the Stable version now. I had forgotten how Read The Docs was set up and how it could be tested. It is coming back to me now. I have pulled all the changes into the Stable branch now and renamed that branch in Git from 4.0 to Stable.

**Comment by agrogers** [comment]
https://andbible.readthedocs.io/ redirects to Stable now

**Comment by agrogers** [comment]
> I have pulled all the changes into the Stable branch now and renamed that branch in Git from 4.0 to Stable.

But that has broken things which i need to fix now.

**Comment by timbze** [comment]
@agrogers The backup&restore page was updated for 4.1 in 4.0 branch, so I changed that page back now. In stable it should show docs for 4.0, and in "latest" ("main" branch) it should show updates that we're changing for next release. I fixed that now.
