### ISSUE TITLE
Alpha no longer works on my Android 5 Kindle

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2568]
https://support.andbible.org/scp/tickets.php?id=1845

Log says:
ERROR Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

**Bug was found on AndBible version**
Build 684 alpha (649 alpha works, but don't know at which version the issue begun)

**Device info**
Version: 4.0.684-alpha#e0a280b github standard release (built 06/04/23 17:36:11)
Android version: 5.1.1
Android SDK version: 22
Manufacturer: Amazon
Model: KFSUWI
Storage Mb free: 14429
WebView version: 84.ship_v84-93-Arcanine.4147.125.180
SQLITE version: 3.8.6.1
Used heap memory in Mb: 20
Max heap memory in Mb: 128

**Comment by tuomas2** [comment]
Reproduced on Android 5 tablet.

**Comment by tuomas2** [comment]
Interesting. WebViewAssetLoader.AssetsPathHandler gives wrong MIME type for js files on Android 5.

**Comment by tuomas2** [comment]
More specificly, DefaultFileNameMap:getContentTypeFor

**Comment by timbze** [comment]
Confirmed fixed in 684.3-alpha
