### ISSUE TITLE
Android 5: workspace color does not work

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2571]
toolbar background color is pale gray always (making text unreadable)

**Comment by timbze** [comment]
This was not an issue in 649-alpha which I've been using up till now on my Android 5 Kindle.

**Comment by tuomas2** [comment]
was customizable workspace colors already included?

**Comment by timbze** [comment]
> was customizable workspace colors already included?

No, looks like that was added in 662-alpha #2007

**Comment by tuomas2** [comment]
Also Android 6 has same issue

**Comment by timbze** [comment]
Confirmed fixed in 684.3-alpha
