### ISSUE TITLE
Bible ref not updated when selecting ref from search results

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2585]
After search,  tapped on one of the references, then hit the back button and tapped on another reference in the search window. The book name did not change in the Bible window for the second reference. 

https://support.andbible.org/scp/tickets.php?id=1852

**Comment by tuomas2** [comment]
@bvahedy 
I could not reproduce this

**Comment by bvahedy** [comment]
I have tried also but could not,  I was hoping the logcat would help you in figuring out what happened.

**Comment by bvahedy** [comment]
Before that happened I was listening to a passage and had set it up for 15 minutes timer reading, but it kept going for over an hour, before I manually stopped it. Then the next day the above bug happened.  I closed the app and reopened it but could not duplicate any of these issues.

**Comment by tuomas2** [comment]
Okay, I didn't look at logcat yet.

**Comment by bvahedy** [comment]
Haven't seen this issue for a while, closing it for now.
