### ISSUE TITLE
Hide TTS at the bottom?

### ISSUE THREAD

**Issue by mark-os** [AndBible/and-bible#2596]
I noticed that the app recently added TTS playback buttons at the bottom of the window. Is there any way to hide these buttons? I don't use this feature. Thanks!

**Comment by timbze** [comment]
If you're not using speak you should be able to just press the square (stop) button and it should disappear. Or do you mean the buttons bar is showing while using speak but you don't want to have the bar there?

**Comment by mark-os** [comment]
Indeed the stop button caused the row of buttons to go down. But it was strange to see the TTS buttons there in the first place as I had not used TTS in months, and it wasn't playing. It just showed up after an upgrade.

**Comment by timbze** [comment]
@mark-os Ok thanks for letting us know. If you see the issue again please reopen this issue.
