### ISSUE TITLE
Window menu -> Copy link to clipboard issues

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2598]
- [x] In bible, it should copy the particular verse. Now it copies the whole chapter.
- [ ] #2781
- [ ] #2780
- [x] Long-clicking any link should offer also "copy link to clipboard".
- [x] Also copy to clipboard should store ordinal to link for gen-book items
- [ ] #2779

**Comment by meichthys** [comment]
Would we also add the "copy link to clipboard" menu item to the three dot main menu?
This would be helpful when the window menus are disabled.

**Comment by tuomas2** [comment]
Fixed most critical ones and made tickets of the rest.
