### ISSUE TITLE
When reading a book, invoking speech causes the display of legacy settings... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#260]
When reading a book or dictionary, e.g.  Josephus, ISBE, trying to invoked speak from the menu displays the old speak settings. Pressing play doesn't do anything.

**Comment by tuomas2** [comment]
> When reading a book, e.g. Josephus, trying to invoked speak from the menu displays the old speak settings. 

Legacy settings are OK because new tts code was written specifically for bible documents, whereas old system is general. 

> Pressing play doesn't do anything.

Can't reproduce. Tried with "BabtistConfession1689" -> Foreword and it started speaking fine.

**Comment by bvahedy** [comment]
Ok, after doing a clean  install, it works as you described, but I have to
have a check in the box for "queue" in the speak settings for it to speak.
It's that normal?

**Comment by bvahedy** [comment]
I'm closing this issue, since it is supposed to behave this way.
