### ISSUE TITLE
Alpha .abmd module cannot be restored

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2604]
![image](https://github.com/AndBible/and-bible/assets/35117769/d97faa97-bf91-459d-8f23-13d45a32e6a5)

- [x] Can not restore at all
- [ ] Clicking file does not give AB as option to open with

**Bug was found on AndBible version**
Build [build-gdrive5](https://github.com/AndBible/and-bible/tree/build-gdrive5)

**Comment by tuomas2** [comment]
Can restore if it's mime type is known (drive etc), but from local filesystem can't

**Comment by tuomas2** [comment]
> Clicking file does not give AB as option to open with

Hmm Not sure if anything can be done about this?. .admd does not correspond to any known mime type.
