### ISSUE TITLE
Trying to create an index for a book causes app to crash... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#261]
Trying to do a find in a book, e.g. Josephus, asks you to create an index. When attempting to do so, causes the app to crash.

**Comment by bvahedy** [comment]
I can't recall but it would be a nice feature if it doesn't take that much
work to make it happen.

**Comment by tuomas2** [comment]
Tried and find option was disabled for general books.
I'll disable it for now for general books, but a feature issue can be made.

**Comment by tuomas2** [comment]
Now search works properly for both bible books as well as commentaries. Not for general books.
