### ISSUE TITLE
New note in study pad does not load automatically after sync

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2617]
https://support.andbible.org/scp/tickets.php?id=1906

**Bug was found on AndBible version**
Build alpha-686.5 (support ticket is for earlier version but tested bug on this latest version too)

**To Reproduce**
1. Open studypad on device 1
2. Open same studypad on device 2 and create note
3. Press home on device 2 (AB runs sync)
4. Press home on device 1 (sync runs)
5. Open AB 
6. -> note is not added
7. -> re-open studypad and the note shows

Do this with bookmark instead of note and it works.

**Comment by tuomas2** [comment]
Fixed in 4dc88e61d442ed1f956e349cd945da399171157e
