### ISSUE TITLE
When using the speak bookmark on the speak toolbar... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#263]
Current behavior:
The speak bookmarks contain the Bible version, this can only be seen when tapping on the bookmark icon on the speak toolbar at the bottom when speak is invoked. If the current Bible in view is KJV and the bookmark is from ESV. Speech reads the ESV but the current view remains in KJV.

Expected behavior:
Two options,
1) if the bookmark contains the Bible name then when that bookmark is selected the Bible window should display that translation.
2) we may not want to record the Bible name in the bookmark,  that way when the bookmark is selected whatever Bible is in view is what is read by the speech routine.

**Comment by bvahedy** [comment]
This is still behaving as before. I don't see any changes. Which option did you choose?

**Comment by tuomas2** [comment]
![screenshot_20190201-080941](https://user-images.githubusercontent.com/5811789/52105849-0c013180-25f9-11e9-95be-fd02d1962a79.png)

**Comment by bvahedy** [comment]
So, if you are reading kjv and tap on one of these bookmarks that is from a Finstlk translstion, will it switch the screen to Finstlk2017 and start reading or does the screen remain in kjv but speaks in FIN?

**Comment by tuomas2** [comment]
It starts reading FinSTLK, but does not switch the translation for the bible screen (which will remain kjv). Similar behavior as in bookmarks button in bookmarks transport (bottom-leftmost button in speak screen).

**Comment by tuomas2** [comment]
So hmm, this is not your 2nd option, but third option. Your 2nd option might be better.

**Comment by bvahedy** [comment]
I agree, let's go with second option. It will keep it easier to deal with.

**Comment by tuomas2** [comment]
Sorry, I meant 1st option actually.

**Comment by tuomas2** [comment]
This has been implemented (have forgot to close this issue)

**Comment by bvahedy** [comment]
Verified fix in 315.
