### ISSUE TITLE
Hiding label in workspace causes crash

### ISSUE THREAD

**Issue by RuggMatt** [AndBible/and-bible#2640]
**Describe the bug**
After choosing labels to hide in a workspace and then hitting back, AndBible crashes

**Bug was found on AndBible version**
Build beta-700 75aa4b7

**To Reproduce**
1. Open workspace menu > Hide specified labels
2. Choose some labels to hide
3. Use Android back button/gesture
4. Crash

**Expected behavior**
App doesn't crash

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 
 - Version 14 (Beta)

**Additional context**

**Comment by RuggMatt** [comment]
[logcat.txt.gz](https://github.com/AndBible/and-bible/files/11760732/logcat.txt.gz)

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=1916
