### ISSUE TITLE
BDBT Thayer's definition is opening wrong word

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2646]
**To Reproduce**
1. Select BDBT as Greek dictionary
2. Open "apparel" (G2689) in 1Tim 2:9 KJV
3. Dictionary opens G2690

Not sure if it's module issue, or bug. Either way, module is in AB repo, maybe we can fix

**Bug was found on AndBible version**
Build 667 production

**Comment by tuomas2** [comment]
mybible sqlite modules are pretty easy to fix compared to sword mods

**Comment by timbze** [comment]
> mybible sqlite modules are pretty easy to fix compared to sword mods

That made me go look for a MyBible version of it and I found one that works great!

I'm guessing my OP is module issue, but looking for a specific strongs number in that module does work, so I'm not sure what exactly the issue is. Since the module is in our repo, we should probably remove or mark as not good quality (if that feature was added?)

**Comment by timbze** [comment]
> or mark as not good quality

I think better remove if we can't fix because it's confusing when it opens Greek word with one number different i.e. trying to open G2689 from Bible word opens G2690

**Comment by tuomas2** [comment]
I fixed this already
