### ISSUE TITLE
Search -> verse not in the top of the window

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2654]
https://support.andbible.org/scp/tickets.php?id=1884

**Comment by tuomas2** [comment]
@bvahedy  ﻿Is 31 the last verse of that chapter? Perhaps this happens if there are not enough stuff below the selected verse.

**Comment by bvahedy** [comment]
No, it does that even if there are plenty of verses below it. 
It still happens with the latest alpha build. 
See below;  I had highlighted the word sheetim and did a find then tapped on this passage ref.  And below is the result: 
![Screenshot_20230619_111142_Bible Study](https://github.com/AndBible/and-bible/assets/46405809/e49efe2b-f0fb-4d8a-a81b-75dd6176f8ec)

**Comment by bvahedy** [comment]
Verse 13 should be at the top of the page.

**Comment by bvahedy** [comment]
This issue seems to have been fixed. Closing this ticket.
