### ISSUE TITLE
Eink version

### ISSUE THREAD

**Issue by brouty** [AndBible/and-bible#2658]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to see options for eink friendly color scheme. Interface with black text on white background. And especially the bible book, chapter, and verse selecter to also be black text on white background. No colors. Gray scale when needed in place of color.

**Describe alternatives you've considered**

**Additional context**

**Comment by ildar** [comment]
I'm always frustrated when I see the "bug reports" like this.
@brouty , can you share what kind of a device you have? The Android version
and such?

**Comment by tuomas2** [comment]
Actually this is duplicate of #1126

**Comment by tuomas2** [comment]
> I'm always frustrated when I see the "bug reports" like this. @brouty , can you share what kind of a device you have? The Android version and such?

And no need to be frustrated.... Probably this was his first ever feature request ticket in Github. :-)
