### ISSUE TITLE
Sync error if "Allow Google sign in prompts" is off

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2665]
See the error and make sure we will give better error message.
https://support.andbible.org/scp/tickets.php?id=1927

**Comment by bassmannate** [comment]
It might be worth noting that this seems to work great on devices with Play services on the system partition, it fails every time on devices without such as the FireHD tablets with no way to correct. Once there are other backends, this may not be an issue at all unless you want to use Google drive. If you do, maybe a manual sign in should be an option.

**Comment by tuomas2** [comment]
Google Drive can't be used with those devices? I wonder if it can be used with Windows 11 devices either then. This is rather critical. I probably need to disable sync for those devices if it does not work.

**Comment by tuomas2** [comment]
Created issue: https://github.com/AndBible/and-bible/issues/2748

**Comment by bassmannate** [comment]
> Google Drive can't be used with those devices? I wonder if it can be used with Windows 11 devices either then. This is rather critical. I probably need to disable sync for those devices if it does not work.

I do have Google Drive and Play Services sideloaded on the device but the sync utility can't seem to connect to it.

**Comment by tuomas2** [comment]
For the record: 

"Allow google sign in prompts" can be found in

myaccount.google.com -> security -> your connections to third party apps & services -> settings  icon -> sign-in prompts"
