### ISSUE TITLE
Web interface request

### ISSUE THREAD

**Issue by Xtoffff** [AndBible/and-bible#2669]
Hello,

Just wanted to know if you have a web interface so that I can use AndBible on my PC as well - with all my notes, highlights, workspaces etc.

Thanks for this amazing app. GBU.

**Comment by tuomas2** [comment]
Beta has sync feature, so you can use multiple devices. Waydroid is one option for installing AB on PC https://waydro.id/. Also Win11 is possible: https://andbible.readthedocs.io/en/latest/getting_started.html#windows-11-setup
