### ISSUE TITLE
Versions for Linux

### ISSUE THREAD

**Issue by KitchM** [AndBible/and-bible#2670]
Strongly suggest just making a standard Linux version.  It shouldn't be too hard to port.

Thank you.

**Comment by tuomas2** [comment]
You can use waydroid to run AB on linux.

**Comment by tuomas2** [comment]
Wrote instructions how to get started: https://github.com/AndBible/and-bible/wiki/Running-AndBible-on-Linux

**Comment by KitchM** [comment]
I'd be glad to help with the testing.  I am attempting to install now and will let you know the outcome.  I know I can help you with the documentation on this as well.  Please let me know if you'd like the help.

-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Jul 8, 2023, 20:26 by ***@***.***:

**Comment by KitchM** [comment]
Got everything installed okay.  These are the results upon activation:

sudo waydroid container start
[sudo] password for jolly: 
ERROR: WayDroid container service is already running

~$ waydroid session start
[16:22:02] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
[16:22:02] Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?

**Comment by tuomas2** [comment]
@KitchM did you eventually have success with Wayland?

**Comment by sammyj85** [comment]
It would suggest you are not running a Wayland compositor, but an X11 compositor. What distro/version are you running?
