### ISSUE TITLE
Icons needed for 5.0

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2677]
- Inline cross reference now using basic Xrefs icon
- Synchronize (Google Drive) / Backup: decide what to do about these

**Comment by agrogers** [comment]
OK, I will sort them out.

**Comment by tuomas2** [comment]
No hurry with these

**Comment by agrogers** [comment]
I think this is done now.

![image](https://github.com/AndBible/and-bible/assets/13920678/7d73d0cc-9f8a-4183-80eb-cfc181f402fe)

![image](https://github.com/AndBible/and-bible/assets/13920678/8baa53fc-08ad-4e0f-8d97-bc5225e9b92e)

**Comment by tuomas2** [comment]
Thank you! Very nice icons!
