### ISSUE TITLE
Improvement idea how to remove bookmark label filters

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2679]
> For "saved bookmark search filter"
> I notice the saved filter is removed by longpress.
> 
> When i click the saved filter, it repopulates the search and it shows the "save icon".
> 
> Maybe you can change it so that the savebutton becomes a trashcan? Because a longpress to delete something seems unconventional to me.

(from youtube comment)

**Comment by agrogers** [comment]
I think we are talking about the buttons I added to help filter labels, yes? That is one of those features I never use. It seemed useful initially but now i just search for what i want which i think is just as fast. Perhaps if the filter buttons were at the bottom of the screen where my fingers are it might feel the same. It would be interesting to know what other people think. But my vote would be to just remove them and leave the search option.

**Comment by tuomas2** [comment]
This feature adds several strings because of help dialog, so if it's useless I'm thinking maybe better to remove it indeed. I'm also using only filter by text.

**Comment by tuomas2** [comment]
Removed. Left label search functionality only.

**Comment by timbze** [comment]
I do use it regularly, but not too big of a deal

**Comment by tuomas2** [comment]
easy to restore also if there are more people voting for it
