### ISSUE TITLE
Find all occurrence returns  the verse number but not the text... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#268]
When looking up a strong's number, and initiating a find all occurrence from the dictionary, the find screen returns all occurrence but it displays an "error occurred" for verses displayed in each verse.
If you select one of the items from the list and go to it, and then hit the back button it goes back to the find screen and there are no errors this time in displaying the verses in the find widow. So, something is broken in the initial find.

**Comment by tuomas2** [comment]
Regression from #261
