### ISSUE TITLE
The back button does not return to the find window...

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#2680]
Affects beta 705.5

1) Search for a word. 
2) select from an item found. 
3) after going to the Bible window, hitting the back button does nothing. 
Expected result: 
Should return to the find window with the results that were already found.

**Comment by agrogers** [comment]
I'm using a very old build at the moment so probably ignore this comment -
when I push back after clicking a verse in the find results it takes me
back to the search form... I want to go back to the search results list to
the same scroll point that I left off.

**Comment by bvahedy** [comment]
Well, if I long press on the back button it will list the history and the second item in the history list is the find search. If I chose that it does go back to the find result list and it is at the scroll point. May be this change is by design, but it's confusing because we are used to having the back button go to the find results directly.

**Comment by agrogers** [comment]
Mine doesnt do that but i have an older version now so I would disregard my
comments. Thanks for checking.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment]
Verified fixed in beta 707 build.
