### ISSUE TITLE
Back button does not return to previously viewed verses

### ISSUE THREAD

**Issue by IHipschman** [AndBible/and-bible#2681]
**Describe the bug**
Clicking the back button does not return to the previously viewed verses - it does nothing.

**Bug was found on AndBible version**
Unable to find version in app. Bug was noted on 7/16/2023 after installing the latest beta.

**To Reproduce**
1. go to a new verse
2. Hit the back button

**Expected behavior**
Should return to the previous verse

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab A
 - OS: Android
 - Version 11

**Additional context**

**Comment by bvahedy** [comment]
Verified fixed in beta 707 build.

**Comment by IHipschman** [comment]
Thank you. Not having the back button work was a significant inconvenience.
