### ISSUE TITLE
Not able to Log-in for Device Synchronization after a user clicks cancels several times in a row

### ISSUE THREAD

**Issue by jayarathina** [AndBible/and-bible#2686]
**Describe the bug**
When using the Device Synchronization, if the user declines to sign in for several prompts in a row, the One Tap client will not prompt the user for the next 24 hours. For then on, we get "signing in to synchronization backend service failed" This error message is not helpful at all. And there is no way to get back the sign-in prompt.

**To Reproduce**
In a fresh install, enable  Device Synchronization, but click cancel several times when prompted to log-in.

**Expected behavior**
Should temporarily disable the One Tap sign-in UI, when user clicks cancel so we don't annoy our users with repeated prompts and get blocked by one tap sign-in. 

**More Info**
Some helpful links to solve this can be seen [here](https://stackoverflow.com/questions/62036642/google-identity-one-tap-sign-in-exception-caller-has-been-temporarily-blacklist) and [here](https://developers.google.com/identity/one-tap/android/get-saved-credentials#disable-one-tap).

**Attachments**
  - logcat.txt.gz: [logcat.txt.gz](https://github.com/AndBible/and-bible/files/12138465/logcat.txt.gz) Log file produced by this app. 
  - [Screenshot_2023_0723_064025](https://github.com/AndBible/and-bible/assets/1886779/65572382-43e5-4f57-ae8f-ef51dbaedec5)   Screenshot of app when this error message is displayed.

**Device info:**
Version: 5.0.706-beta#a48d27795 googleplay standard release (built 21/07/23 20:38:34)
Android version: 13
Android SDK version: 33
Manufacturer: vivo
Model: V2225
Storage Mb free: 84087
WebView version: 114.0.5735.196
SQLITE version: 3.42.0
Used heap memory in Mb: 8
Max heap memory in Mb: 256

**Comment by tuomas2** [comment]
Improved error message

**Comment by tuomas2** [comment]
Showing original error message from API in addition to what we show now.
