### ISSUE TITLE
Restructure/improve three-dots options menu a little

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#269]
I'm thinking that options (three dots) menu in bible view would be as follows:

 - Text content options (submenu item)
   - Strongs
   - Morphology
   - Footnotes
   - Red letters
   - Section titles
   - Verse numbers
   - One verse per line
   - Show bookmarks
   - Show My Note icons
- Switch to fullscreen by scrolling (see also #262 )
- Split mode (show only if not in auto mode) 
    ** After chaning, show toast message which mode was chosen
- Tilt to scroll (move from settings)
- Night mode on/off (show only if not in auto mode)

Essentially less and less stuff in settings screen, which, I think, is just good (often changed settings should be accessible easily).

- [x] remove tilt to scroll from menu if it is not available
- [x] "Vertical split mode" -> works as 'reverse split mode' but shows in portrait 'vertical split' and in landscape as 'horizontal split'
- [x] Night mode: what to do if auto is enabled?
- [x] Update help screen (doubletap to fullscreen)

**Comment by alerque** [comment]
Just today I was thinking tilt to scroll should be more accessible, I would use it more if it didn't involve so many taps to toggle on and off. Settings should be for set once to preference and forget, buttons or accessible toggles should be for features you sometimes want, sometimes don't.
