### ISSUE TITLE
Highlight Search Results

### ISSUE THREAD

**Issue by jguntrip42** [AndBible/and-bible#2696]
Your app is fantastic, love the the display options with fonts/parallel documents mode! 

I found the search/find feature a bit lacking - just thought it would be a great addition if it highlighted the relevant searched terms (the English word for usual searches, the translated word for Strong's numbers/Hebrew words. Also, would it be possible to make the search engine support looking for Strong's numbers? 

Would be keen to help on the project, however most of my coding has been in Python/C, so I would not be able to help much.

Thanks for maintaining a great app,

Joseph

**Comment by tuomas2** [comment]
Some search result highlighting is implemented already in Beta.
