### ISSUE TITLE
Don't attempt Drive sync if offline. 

### ISSUE THREAD

**Issue by RuggMatt** [AndBible/and-bible#2698]
**Describe the bug**
I get sync failed message for Google drive sync when opening the app when I am offline. Perhaps don't attempt to sync or show the message if there is no internet connection to begin with. 

**Bug was found on AndBible version**
707

**To Reproduce**
1. Enable airplane mode
2. Open app

**Expected behavior**
App does not attempt to sync if no internet available

**Comment by tuomas2** [comment]
Fixed
