### ISSUE TITLE
Android back button behavior when main menu is active.... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#270]
When the main menu is displayed, hitting the Android back button should close the menu instead it reverts back to the item previous in the history.
Note that this works correctly with the Bible menu window on the top right of the menu bar but not the menu option on the top left.

**Comment by timbze** [comment]
@bvahedy @tuomas2 

There may be a different underlying issue, but I tested that it can easily be fixed by adding override fun onBackPressed in MainBibleActivity.kt

**Comment by tuomas2** [comment]
You are right. Feel free to make a fix if you want @timbze :)
Fix will be released in 3.1

**Comment by timbze** [comment]
Fixed in PR #279

**Comment by bvahedy** [comment]
The back button correctly closes the menu now, but we need to disable long press on the back button when menu is in display. So, I'll reopen this issue as it causes the history to show but selecting any item in history doesn't do anything.
Note: that the right menu on the menu bar behaves correctly.

**Comment by tuomas2** [comment]
Good catch. I didn't even know about this long-press-back button feature :)

**Comment by timbze** [comment]
Should be a simple fix I think. I can do it tomorrow if it's not done yet by then :)

**Comment by tuomas2** [comment]
I'll leave this to you then 😊

**Comment by bvahedy** [comment]
Yes, I believe Tim is the one who implemented it. It's a nice feature.

**Comment by timbze** [comment]
Maybe Tim implemented it but not this Tim. :)
Submitting a fix now

**Comment by bvahedy** [comment]
When I was growing up and things went South, we always blamed Tim 😁
It's a great mod, just needs a bit of tweaking. Thanks for enhancing it
further.

**Comment by tuomas2** [comment]
Fix will be in 299.

Original feature was most likely by Martin (before project lead role was transferred to me).

**Comment by bvahedy** [comment]
Verified fix in build 315.
