### ISSUE TITLE
Add New Euskara Bible

### ISSUE THREAD

**Issue by chakpori** [AndBible/and-bible#2707]
Peace be with you, brothers and sisters!

Please add the following Bible translation:

Jean Pierre Duvoisin's translation of the Bible into Basque (Labourdin): 

BIBLE SAINDUA, edo Testament Zahar eta Berria, Duvoisin kapitainak latinezko Bulgatatik lehenbiziko aldiko Laphurdiko eskarara itzulia.
Luis-Luziano Bonaparte printzeak argitara emana.

https://klasikoak.armiarma.eus/cgi-bin/klasikoak/bila.pl?testua=bible&nola=hasi

It is divided in three parts.

If there be any problem, here comes the document in images:

https://gallica.bnf.fr/ark:/12148/bpt6k96656209

Thanks a lot.

**Comment by tuomas2** [comment]
Please see our FAQ https://github.com/AndBible/and-bible/wiki/FAQ#please-add-module-x-to-andbible
