### ISSUE TITLE
Epub has white background in dark mode

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2709]
https://www.monergism.com/thethreshold/sdg/owen/An%20Exposition%20of%20the%20Epistle%20to%20-%20John%20Owen2.epub

![Screenshot from 2023-08-15 07-24-45](https://github.com/AndBible/and-bible/assets/35117769/759ef861-106e-4e16-8e5e-9b5a66c51af4)

**Bug was found on AndBible version**
Build 719-beta

**Comment by tuomas2** [comment]
Some epub files change background with CSS. We can override that setting, but not sure if that can be done in such a way that it does not break other custom css.

**Comment by tuomas2** [comment]
I noticed that same thing when trying Spurgeon Sermons epub from monergism.com.

**Comment by timbze** [comment]
One problem is that text is also white then.

> We can override that setting, but not sure if that can be done in such a way that it does not break other custom css

I don't know exactly how it works, but I'm thinking it will have to be overridden for epubs. When do we need "epub set" background colors? We just want the text with html tags etc right?

**Comment by timbze** [comment]
This seems to be fixed in 721-beta
