### ISSUE TITLE
My notes view in full screen mode

### ISSUE THREAD

**Issue by dlichtistw** [AndBible/and-bible#271]
**Describe the bug**
When opening the My Notes screen from the bible view in full screen mode, the textarea's first line is covered by the navigation/toolbar.

**To Reproduce**
1. View some bible text.
2. Scroll up to enter full screen mode.
3. Select a verse by long tap.
4. Tap the pencil button to create/edit a note.
5. Write some text.

**Expected behavior**
Either the navigation/toolbar should be hidden as in full screen mode, or the textarea should be shifted down as to not hide the first line.

**Smartphone (please complete the following information):**
 - Device: Sone Xperia XZ2 Compact
 - OS: Android 9
 - Version: 3.0.288 (beta channel)

**Comment by tuomas2** [comment]
Possibly related #273 (user pointed out via email)
