### ISSUE TITLE
Epub table of contents

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2710]
> Notes. The epub module lists the file name or something else to it as the chapter files. It works, but expected the table of contents text, not the file names.

I might try to dig the real title from the HTML files. EPUB manifest file alone unfortunately does not give better outline.

_Originally posted by @tuomas2 in https://github.com/AndBible/and-bible/issues/1414#issuecomment-1666409017_

**Comment by timbze** [comment]
https://www.monergism.com/thethreshold/sdg/owen/An%20Exposition%20of%20the%20Epistle%20to%20-%20John%20Owen2.epub

AB table of contents:
![image](https://github.com/AndBible/and-bible/assets/35117769/877dcade-e3ff-44dc-9e82-b5f0931f016b)

[Calibre](https://calibre-ebook.com/) table of contents:
![image](https://github.com/AndBible/and-bible/assets/35117769/e60e6d84-edd9-4cc2-aa63-cecef121d1b0)

**Comment by timbze** [comment]
https://manual.calibre-ebook.com/conversion.html#format-specific-tips

> calibre will automatically generate a Table of Contents based on headings if you mark your headings with the Heading 1, Heading 2, etc. styles in Microsoft Word. Open the output e-book in the calibre E-book viewer and click the Table of Contents button to view the generated Table of Contents.

**Comment by tuomas2** [comment]
> > Notes. The epub module lists the file name or something else to it as the chapter files. It works, but expected the table of contents text, not the file names.
> 
> I might try to dig the real title from the HTML files. EPUB manifest file alone unfortunately does not give better outline.

this what I said is not true btw, found out toc file.

**Comment by timbze** [comment]
This is great now in 721-beta
