### ISSUE TITLE
Calc button symbol

### ISSUE THREAD

**Issue by Noitarud** [AndBible/and-bible#2713]
- I am niggled that you have used the wrong symbol for the × key and have X instead.
- if you want X, maybe you could make it more scientificy: eg specify X=X+5, then user could enter 34×X and every subsequent = press gives with X incremented once more, though not a normal calculator feature…).
- You have no documentation on the app in readthedocs, as seen in wiki, somehow I found myself there looking for what I needed to enter. But more discrete is better…
- Calc this: 123456789+.3 And keep tapping =
- Can the pin be made to include more buttons? 1+1=

**Comment by Noitarud** [comment]
Another niggle, do this:
123456789+.3
And keep tapping =.

**Comment by Noitarud** [comment]
Can the pin be made to include more buttons? 1+1=

**Comment by tuomas2** [comment]
> You have no documentation on the app in readthedocs, as seen in wiki, somehow I found myself there looking for what I needed to enter. But more discrete is better…

It's only in Beta yet. I think documentation is for stable version. And actually I haven't been writing docs, that's @agrogers  and @bvahedy and others that have been doing that.

Created ticket:https://github.com/AndBible/and-bible/issues/2741

**Comment by tuomas2** [comment]
> Can the pin be made to include more buttons? 1+1=

Why is it needed?

**Comment by tuomas2** [comment]
> I am niggled that you have used the wrong symbol for the × key and have X instead. 

fixed this

**Comment by tuomas2** [comment]
Calc this: 123456789+.3 And keep tapping =

it will keep adding .3, isn't that correct?

**Comment by Noitarud** [comment]
> Calc this: 123456789+.3 And keep tapping =
> 
> it will keep adding .3, isn't that correct?

I think I have seen similar elsewhere and its inherent in  the computer somehow. Memory suggests [THIS](https://en.wikipedia.org/wiki/Floating-point_error_mitigation).

This is what is seen after three = presses:
![Screenshot_20231012-205713](https://github.com/AndBible/and-bible/assets/98794719/5f115692-cc29-45d3-835e-d1df9fadcb95)

**Comment by Noitarud** [comment]
> > Can the pin be made to include more buttons? 1+1=
> 
> Why is it needed?

Greater diversity of input increases pin complexity, increases security. Doesn't have to be a proper calculation.
