### ISSUE TITLE
Crash when choosing study pad via "choose document"

### ISSUE THREAD

**Issue by Noitarud** [AndBible/and-bible#2715]
After restore,
•workspace with studypad has it missing (replaced with Bible)
•Load document causes crash

Backupper was perhaps 684 else 651. No restore errors so maybe just no study pad function.

**Comment by tuomas2** [comment]
please send crash report from the app

**Comment by Noitarud** [comment]
Figured a way to send using Amaze app…
[logcat.txt.gz](https://github.com/AndBible/and-bible/files/12405591/logcat.txt.gz)

**Comment by tuomas2** [comment]
Try main menu -> Study Pads -> select study pad from there.

**Comment by tuomas2** [comment]
ah nevermind, I can now reproduce. Anyway you can open study pad as I suggested.

**Comment by tuomas2** [comment]
So to reproduce:
1. Main menu -> Choose Document
2. Choose "Study Pads" document

 -> crash

**Comment by Noitarud** [comment]
That is correct for problem №2.

**Comment by tuomas2** [comment]
please 1 ticket for 1 problem 😊

**Comment by tuomas2** [comment]
> •workspace with studypad has it missing (replaced with Bible)

This is a known issue that will not be fixed. One time annoyance for everyone upgrading.

**Comment by tuomas2** [comment]
Re-opening for issue nro 2.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2047 also

**Comment by Noitarud** [comment]
The workspace that had the study pad (see top post) is exibiting a weird bug.
Normally, When you press the boundary between sections, it goes yellow and you can move them.
•It instead would move not very far^, or even not at all*, despite displacement of finger motion (used on tablet). *I suspected the changes of scale was due to width of top one…
•I removed all sections except top-most (included the section that had the study pad which changed to Genesis 1 after reload)
•I added fresh sections. Now with a tiny finger displacement the boundary of any moves massively.
•It is (now) not saving positions when switching bw workspaces (returns equally spaced).
•On app restart top section ultra narrow and slow motion to finger displacement.
•On app restart section ratio maybe 5:1:1:1 and fast displacement.
•Switch away and back to WS, equally spaced.

**Comment by tuomas2** [comment]
also https://support.andbible.org/scp/tickets.php?id=2078
