### ISSUE TITLE
Beta. Your "app crash" feature (menu option) is not serious enough

### ISSUE THREAD

**Issue by Noitarud** [AndBible/and-bible#2718]
Your "crash" appears like an app reboot. I want the crash to cancel split screen (android may say "[app name] keeps stopping"). I have found a bug in android which can make an app a little/much more useful (may be android 10 only), I'd like to see how your app responds to it (using real crash I discovered. App response is: "app opened elsewhere" error, fair enough.)

But maybe you would be keen to make the benefits of the android bug native (though your app is flexible enough to not really need it most of the time - except on results screens, and I can use calc as second instance instead), so I'll tell, after app breaks (must be primary member of split screen), run app again from home screen. Start split screen again, selecting the carcass of your crashed app as primary member. Select another app as second member for now. Use carcass. Then swap to that new instance as second. You will have two user interfaces up with one process. This can allow you to copy and move text from one to another, or use two separate functions at once. The process will service only one interface instance and this is switched by changing the interface size (true for app I discovered it with; hence instruction "use carcass" to set its content, the last to be reset will be the active one, requires some strategy to switch the right way later on), lookup requests of inactive interface will be sent to be shown on active interface.

**Comment by tuomas2** [comment]
Related: #2752

**Comment by tuomas2** [comment]
This developer feature, and only present in Alpha/Beta builds.

**Comment by tuomas2** [comment]
I'm not sure if I got what you wanted to say. Just can say that at the moment the feature is useless because of #2752.

**Comment by Noitarud** [comment]
Just copy the #2715 crash cause or the like. If is a legit crash it will bring up the message from android.
I thought the concern I would get would be possible data loss.
