### ISSUE TITLE
Fullscreen by scrolling

### ISSUE THREAD

**Issue by Noitarud** [AndBible/and-bible#2719]
When I read that (issue title) in preferences, I understood different: to temporarily hide all the other windows(panes) for best view of content during scroll, that is, if windows above/below and scroll is vertical (I do not know if you have languages that require horizontal scroll, hide L/R windows for them). I use a tablet, I won't need to fill screen, but can expand a bit.

**Comment by tuomas2** [comment]
There is maximize window feature that can be used. I don't think maximize window by scrolling would be usable.
