### ISSUE TITLE
Compare range of verses

### ISSUE THREAD

**Issue by IHipschman** [AndBible/and-bible#2721]
If memory serves me right, it used to be possible to select a range of verses and then select compare. This was a nice feature since a thought or sentence will sometimes extend over more than one verse. Is there any chance of restoring that capability?

**Comment by tuomas2** [comment]
Option has not disappeared anywhere. Just select a range of text (press + button from selection modal to select multiple verses) and then tap compare.

**Comment by IHipschman** [comment]
Tuomas,

Thank you so much. I wasn't aware of the + button on the selection modal.

Ivan Hipschman
