### ISSUE TITLE
White fonts on note creation.... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#273]
In full screen mode, either by double tap or up scroll, highlight a verse and tap on the pencil icon to create a note. When typing letters they are in white font and you can't see them but they are there.

**Comment by tuomas2** [comment]
Was automatic night mode setting being used?
I can't reproduce this now. Please test again after I release new beta today evening.

**Comment by bvahedy** [comment]
Ok, this issue is now gone but the note doesn't scroll up anymore when keyboard is active. I'll reopen the other ticket.

**Comment by bvahedy** [comment]
This is fixed but #230 reappears, so I'm reporting 230.
