### ISSUE TITLE
Possibly add NKJV document?

### ISSUE THREAD

**Issue by joshpetit** [AndBible/and-bible#2751]
**Is your feature request related to a problem? Please describe.**
NKJV is my translation of choice, and I was wondering if AndBible would ever consider adding it to the list of documents. I'd imagine it'd likely cost money though for licensing.

**Comment by tuomas2** [comment]
Please see https://github.com/AndBible/and-bible/wiki/FAQ#please-add-module-x-to-andbible

**Comment by joshpetit** [comment]
Makes sense, thanks
