### ISSUE TITLE
Bookmark not working (4.0)

### ISSUE THREAD

**Issue by petherHarb23** [AndBible/and-bible#2764]
**Describe the bug**
Long clicking on selected text brings up the context menu, but selecting Bookmark has no result.

**Bug was found on AndBible version**
4.0

**To Reproduce**
1. Navigate to a Bible verse
2. Long press on a word to get the context menu.
3. Select bookmark.

**Expected behavior**
Window to save bookmark should come up..

**Screenshots**
![Screenshot_20230827-144336-891](https://github.com/AndBible/and-bible/assets/39991792/8a320c33-7abc-4afd-a2c7-96e4d35e1559)

**Smartphone (please complete the following information):**
 - Device: Motorola Moto G Stylus 
 - OS: Android 
 - Version 11

**Additional context**

**Comment by tuomas2** [comment]
This should be tried on latest beta version, if still reproduces, as we are already preparing 5.0 with full speed.

**Comment by tuomas2** [comment]
I think this was fixed recently also for stable 4.0
