### ISSUE TITLE
Old Ottoman Turkish and Venice Mekhitarist Bible Translations + Ferrara Bible

### ISSUE THREAD

**Issue by chakpori** [AndBible/and-bible#2765]
There are some old Ottoman Turkish, and Venice Mekhitarist translations, that could be of immense value, once made part of the library or digitalised:

1. The Bagratuni Classical Armenian Bible:
https://www.arak29.org/bible/book/

1.b. Zohrabian's New Testament in Classical Armenian:
https://archive.org/details/NewTestamentInClassicalArmenian/page/n13/mode/1up

2. Helleno-Turkish (Turkish written in Greek alphabet):

https://books.google.com/books?id=lj47AAAAcAAJ
https://www.google.com/books/edition/Biblia_Turco_Greek/5Iw8AAAAcAAJ

3. Armeno-Turkish (Turkish written in Armenian alphabet):

https://books.google.com/books?id=paxBAAAAYAAJ
https://www.google.com/books/edition/Turkish_New_Testament_Written_in_Armenia/ViwwAAAAYAAJ
https://www.google.com/books/edition/The_Bible_in_Turkish_written_in_Armenian/GhuHo5BZTcoC

4. Armeno-Kurdish (Kurdish written in Armenian alphabet):

https://books.google.com/books?id=zywwAAAAYAAJ

Added to these, another very useful Jewish translation of the Pentateuch: the Ferrara Bible

https://www.larramendi.es/i18n/catalogo_imagenes/grupo.cmd?path=1001869

Please, consider adding these to the Library, as well.

Thank you, in advance.

**Comment by tuomas2** [comment]
Please read https://github.com/AndBible/and-bible/wiki/FAQ#please-add-module-x-to-andbible
