### ISSUE TITLE
Bookmark "Selection/Verses" Menu Disappears Before Selection Can Be Made

### ISSUE THREAD

**Issue by tdcourt** [AndBible/and-bible#2775]
I'm no longer able to bookmark selected portions of a verse, might be due to recent Android system update.

When I manually highlight a selection of words and select "Bookmark" from the context menu, the proceding "Selection | Verses" context menu disappears before I am able to make a selection, does not create the intended bookmark.

Versions tested: 
4.0.685
5.0.724-beta
Also tried a couple of previous 4.0 versions, but no luck.

**To Reproduce**
1. Highlight a word in the text (tap and hold down)
2. Once highlighted, select "Bookmark" from context menu
3. Watch as "Selection/Verses" context menu appears and then immediately disappears before selection can be made, no bookmark is registered.

**Expected behavior**
The proceeding context menu should stay long enough for a selection to be made, allowing for the selection to be bookmarked.

**Screenshots**
![ezgif-4-6faa8a476b](https://github.com/AndBible/and-bible/assets/143659425/58ad350d-0324-4cf6-9038-cfbf1bd7b941)

![Screenshot_20230830-171618](https://github.com/AndBible/and-bible/assets/143659425/9d847e31-3992-4dd3-901b-f2897f0ef680)

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 13
 - (see screenshot for detailed OS version details)

**Additional context**
I just got this phone, but the bookmark feature was working fine until yesterday, which I why I believe an OS/security update might be to blame... Otherwise not sure if there's a setting on the phone that could have triggered this behavior.

**Comment by tuomas2** [comment]
Can reproduce on my phone but not on emulator so I think something has changed in WebView etc. Investigating...

**Comment by tuomas2** [comment]
Got it fixed.
