### ISSUE TITLE
Bible ref. Overlay in full screen shows the wrong verse...

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#2829]
Affects the latest beta: 

When in full screen mode.  Tap on a verse in the middle of the screen.  The verse is highlighted and the Bible reference overlay shows the wrong verse that is at the top of the screen.

**Comment by bvahedy** [comment]
https://github.com/AndBible/and-bible/assets/46405809/70beee30-749f-461e-b1ee-9664868e824b

**Comment by tuomas2** [comment]
Overlay should not display anything when tapping the screen. Actual issue is #2848
