### ISSUE TITLE
Improve reading plan title texts

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#283]
Instead of codes like "y1ntpspr", human-readable string should be shown in Reading Plan listing.

**Comment by tuomas2** [comment]
Assigned this to you @timbze , feel free to unassign if not willing to implement this.

**Comment by tuomas2** [comment]
Hmm @timbze why did you unassign this if you have implemented it?

**Comment by tuomas2** [comment]
Will be implemented in build 313

**Comment by bvahedy** [comment]
Confirmed implementation in 313 build.
