### ISSUE TITLE
Don't show verses correctly in MyBible module in Daniel's Book

### ISSUE THREAD

**Issue by pepaulo** [AndBible/and-bible#2852]
Don't display the verses of Daniel 3 from 24 at 90, and the chapters 13 and 14 on MyBible module.

**Comment by tuomas2** [comment]
duplicate of https://github.com/AndBible/and-bible/issues/2747?

**Comment by pepaulo** [comment]
@tuomas2 Yes. This is part of a bigger bug concerned to use the MyBible modules in other versification, not in KJA

**Comment by tuomas2** [comment]
duplicate of https://github.com/AndBible/and-bible/issues/2747
