### ISSUE TITLE
Loading spinner keeps showing after window loads

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#2888]
Has happened a few times but don't know yet how to reproduce

**Bug was found on AndBible version**
Build 730 beta (also has happened in earlier version)

**Comment by tuomas2** [comment]
Could you take bug report logcat when this happens?

**Comment by timbze** [comment]
Happened again, this time after restoring document from backup file.
[logcat.txt.gz](https://github.com/AndBible/and-bible/files/12838319/logcat.txt.gz)

**Comment by tuomas2** [comment]
Also I had similar happening: https://support.andbible.org/scp/tickets.php?id=2127

**Comment by tuomas2** [comment]
Let's see if this still reproduces, have tried something.

**Comment by tuomas2** [comment]
let's reopen if still happens
