### ISSUE TITLE
Add an entry for the morphology dictionaries

### ISSUE THREAD

**Issue by LAfricain** [AndBible/and-bible#2889]
**Is your feature request related to a problem? Please describe.**
For now it's not possible to choose between different dictionaries for the morphology.

**Describe the solution you'd like**
Add an entry in the setting, as we have for the strong's dictionaries, for the morphology. By instance we have Robinson for the greek in English, and also the freRobinson for the French.

**Comment by tuomas2** [comment]
Hmm, there is already entry "Robinson Greek morphology" in application preferences?

**Comment by LAfricain** [comment]
Ok I missed this! I installed frerobinson right now. I choose it in the settings, but strange with TR it doesn't show it.
