### ISSUE TITLE
Slow performance on certain devices

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#289]
From user via email:

> Since the upgrade to version 3 I have noticed certain actions are slower than before - when tapping Strong's numbers (nnnn) there is a delay of a few seconds, about 3. Also when I open a new window (ie split window) and then turn off the new window's synchronisation, and navigate to a chapter/verse, the other window then goes blank. I have to either navigate to another reference or tap Strong's (nnnn) to bring it back, but again that takes time.

I'm assuming this affects mostly older devices.
We could do some profiling to check if there are somthing worth optimization.

**Comment by bvahedy** [comment]
Tuomas, this is more of an enhancement than a bug. we should downgrade this to code enhancement and reduce it's priority from major. Any thoughts?

**Comment by tuomas2** [comment]
Probably fixed in 3.2.
