### ISSUE TITLE
Change in completed tick reading plan behaviour 

### ISSUE THREAD

**Issue by steelwil** [AndBible/and-bible#2904]
**Describe the bug**
Hi, I use the y2ot1n reading plan, I often only read one chapter on a day. Reading the first chapter works as previously, but when completing the last chapter I normally close the app. The next day the last chapter is not marked as complete. Old versions worked better as then it was marked. I prefer the old behavior.

**Bug was found on AndBible version**
Release 4.0.687 but has been like this for the last few releases.

**To Reproduce**
1. Go to 'y2ot1n' reading plan
2. select first chapter
3. close AndBible
4. Open AndBible and go back to the reading plan
5. First chapter is correctly marked as completed.
6. Do the same for the last chapter.
7. When you open AndBible the last chapter is not marked as completed

**Expected behavior**
The last chapter should be marked completed even though the "Done" button was not clicked. The "Done" button should only go to the next day.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung A34, and an old Samsung tablet
 - OS: Android
 - Version last few beta releases

**Additional context**
I can live with the current behavior - but I prefer the old behavior - thanks.

**Comment by timbze** [comment]
Thank you for reporting this issue. It was known before, but I didn't know if it also was happening on v4, which you now confirmed. I will work on a fix.

**Comment by timbze** [comment]
@steelwil are you sure this is happening in v4? I tried reproducing but not able yet. In v5 it's quite easy to reproduce.

**Comment by steelwil** [comment]
Hi, I am getting the same issue with V5 - The issue started a few beta versions ago.
