### ISSUE TITLE
Change X button title to three bars or change default click action to 'close'

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#291]
From user via email:
> When trying to close a second window we used to be able to tap on the 'X' box and it would close. We now still tap on the 'X' box, but get a menu & have to identify & tap on the 4th item in the list to close the window. This is unintuitive & requires more taps and identifying than the previous method. As a minimum: The 'X' box symbol should be changed to a 'menu' symbol (like on your play store screenshots that aren't reflected in the app) and the close option should be the first option - then effectively a double tap would close the window.

**Comment by tuomas2** [comment]
To be considered.

**Comment by bvahedy** [comment]
It is very functional the way it is, users just have to get used to it. This is the best and most standardized presentation.
