### ISSUE TITLE
Empty calculator pin makes it impossible to get in

### ISSUE THREAD

**Issue by Noitarud** [AndBible/and-bible#2914]
I wanted to prevent the calculator from coming up, so I entered a null pin, now i cannot get in…

**Comment by tuomas2** [comment]
Do you mean empty string for PIN?

**Comment by Noitarud** [comment]
That's right

**Comment by Noitarud** [comment]
Just noting author's solution:
Keeps using last PIN, box is empty when user views again.

Thats alright. I didn't expect you to disable the calculator, assumed only needed =. So is a bit more private now 😉

**Comment by tuomas2** [comment]
It is true that = should be enough, but also user will definately figure out how to get into Bible view  if pin is set empty.
