### ISSUE TITLE
Date-based reading plan

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#292]
From user via email:
> The current Reading Plan feature is based on whichever day you start a plan and progress through a plan. However, we would really like to see the option for date based plans (i.e. the readings for the 9th February are:...). This would allow for the use of several very common readings plans and for friends to be able to read & discuss the same sections on the same day.
> I and several of my friends go to another app for the daily readings, but it would be great if it could all be done within this app. Please feel free to talk to me more about this feature, as we've wanted it for years and would be really keen to see it implemented.

**Comment by tuomas2** [comment]
Assigned @timbze for you, if you want to consider feature request.

**Comment by timbze** [comment]
I think it is a good idea to have that option as well. And the idea came at the right time too :)

**Comment by tcressy** [comment]
I'm the user that Tuomas is quoting above. I have a quite a few friends around the world who use And Bible, but go to other apps that use a date based reading system (have the plan we use in them already). It would be great if date based plans were an option. It wouldn't matter if you either implemented the specific plan that we use, or just allowed a way for us to add our own date based plans our-self (a more flexible approach).

To be specific, the reading's plan we use (Christadelphian plan created by Robert Roberts ~150 years ago and widely used) can be found in many places, for example: https://www.dailyreadings.org.uk/default.asp?act=monthdisplay&m=1
Here's a link to my google sheet, where the plan can be copied nicely as a table.
https://docs.google.com/spreadsheets/d/1GdEf4my3gc2vZ1KJNWm1VrdeELvmzDaMelu6DNNuqJg/edit?usp=sharing

It would be great if date based plans were an option - thanks for considering this!

**Comment by timbze** [comment]
@tcressy Thank you for the additional information! Lord willing I will work on this feature together with an entire revamp to the reading plan feature in AndBible within a few weeks.

**Comment by tcressy** [comment]
@timbze No pressure, I was just wondering if there was any progress with the reworking of the reading plans? Many thanks.

**Comment by timbze** [comment]
Yes I have been working on it. I'm not finish outlining it here #284 but that's where I will put my outline and keep track of the progress. I have already done some coding, but it's quite the project, since we wanted to do a complete reworking of how the Reading Plans operates. Also, I have been using more Java program language before, and the project is switching to Kotlin, so it takes some time to learn and get used to as well. Thanks for your patience. I think I want to see this done as much as you :) but I work with the time I have...

**Comment by tuomas2** [comment]
> I think I want to see this done as much as you :)

I guess this is the best motivator ;) Have fun with hacking!

**Comment by tcressy** [comment]
@timbze Morning :) I hope you don't mind me asking again if there's been any progress with the date based readings plans? I might be a little bit too much of an ambassador for AndBible, but I know there are quite a few of us who are in eager anticipation... :)
Many thanks for all of your work.

**Comment by tuomas2** [comment]
> @timbze Morning :) I hope you don't mind me asking again if there's been any progress with the date based readings plans? I might be a little bit too much of an ambassador for AndBible, but I know there are quite a few of us who are in eager anticipation... :)
Many thanks for all of your work.

My opinion is that we should not give time estimates to users, simply to avoid unnecessary pressure to the developers. We will let users know when new stuff is ready for beta and when they are, users can then help in improving the quality by reporting good bug tickets. Until that, this kind of questions should be relevant only if you are planning to work yourself on this or related feature.

**Comment by tcressy** [comment]
> > @timbze Morning :) I hope you don't mind me asking again if there's been any progress with the date based readings plans? I might be a little bit too much of an ambassador for AndBible, but I know there are quite a few of us who are in eager anticipation... :)
> > Many thanks for all of your work.
> 
> My opinion is that we should not give time estimates to users, simply to avoid unnecessary pressure to the developers. We will let users know when new stuff is ready for beta and when they are, users can then help in improving the quality by reporting good bug tickets. Until that, this kind of questions should be relevant only if you are planning to work yourself on this or related feature.

My apologies - sadly I don't have the skills to work on it. I'll leave you to it and won't pester again.

**Comment by timbze** [comment]
@tcressy Not a problem. I can tell you there has been progress, but doing this as a spare time project, and also being busy with other things in life makes it take time. Thanks for your understanding.

**Comment by tuomas2** [comment]
Implemented in build 319.0

**Comment by bvahedy** [comment]
How do i test this?

**Comment by tuomas2** [comment]
@timbze knows better :-)

**Comment by timbze** [comment]
@bvahedy You can test date-based reading plan with [this file](https://github.com/AndBible/and-bible/files/3851994/roberts.txt). Just add it to the folder for custom reading plans. You must change the file extension to .properties

**Comment by bvahedy** [comment]
Verified fix working in beta 319.1
