### ISSUE TITLE
Make test build for #1765 (Android 8 speed issue)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2928]
Should check if still need fix for #1765 issue on Android 8

**Comment by tuomas2** [comment]
Build will appear here soon https://github.com/AndBible/and-bible/releases/tag/build-737-android8-test

**Comment by tuomas2** [comment]
Could someone with Android 8 or Android 8.1 test this? @timbze was it so that you have such a device?

**Comment by timbze** [comment]
> Could someone with Android 8 or Android 8.1 test this? @timbze was it so that you have such a device?

Just updated to Chrome Canary 120.0.6077.0 on my Android 8.0 and still have the same issue

**Comment by tuomas2** [comment]
Thanks for the information! Let's leave the fix then.

**Comment by timbze** [comment]
Log from last try: https://support.andbible.org/scp/tickets.php?id=2155
