### ISSUE TITLE
Adding a Custom Repo is not clear

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#2929]
I thought I was supposed to click on the green tick.
I couldn't find a way to save what I had entered.
Bad URLs do not really do anything.
Bad URLs do not remove the text from a previous good URL.

Suggestions:

- [x] 1. There should be no tick when the form is opened
- [ ] 2. The URL is being checked after each keystroke (or something like that). I dont think that is necessary
- [ ] 3. Any previous text below the URL should be removed if a URL is changed.
- [x] 4. Would make more sense to me to have a button to submit the URL.
- [x] 5. If it is a good URL, show the returned text with a big green tick.
- [ ] 6. If it is bad, say it is bad "This is not a valid repository" with a red cross or no tick .

**Comment by tuomas2** [comment]
Good suggestions. Thank you for testing this! I think not many people have been testing/using this so far.

**Comment by tuomas2** [comment]
> I couldn't find a way to save what I had entered.

I copied this UX from what we have in label editor. Maybe some sort of "save"-button should be there too as it causes some confusion if there's none.

**Comment by tuomas2** [comment]
After couple of fixes that I made it is better, perhaps good enough.

![image](https://github.com/AndBible/and-bible/assets/5811789/8ed15388-41e3-44f6-956f-4609450d344e)

![image](https://github.com/AndBible/and-bible/assets/5811789/8c0bedad-e64c-4b84-9be7-f77f3de71a0f)
