### ISSUE TITLE
Incorrect description in the help? 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#2931]
Is the info about the workspace icon correct? I think it should read that the 'workspace setting WILL affect this window'. 

![Screenshot_2023-10-15-11-02-08-241_net.bible.android.activity.jpg](https://github.com/AndBible/and-bible/assets/13920678/bc6984f9-8681-4353-bd87-ab959d0ae930)

**Comment by tuomas2** [comment]
I think you are correct. Removing the last sentence.
