### ISSUE TITLE
Cannot find hide labels per workspace setting

### ISSUE THREAD

**Issue by RuggMatt** [AndBible/and-bible#2933]
**Describe the bug**
I used to be able to hide labels per workspace. The option seems to be missing now 

**Bug was found on AndBible version**
Build 5.0.736-beta

**To Reproduce**
1. Go to Workspace menu
2. Hide labels setting missing 

**Expected behavior**
Hide labels setting is there. 

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: P7Pro
 - OS: Android 
 - Version 14

**Additional context**

**Comment by RuggMatt** [comment]
I found an option to hide a label in label settings but this seems to hide it in every workspace, not just the workspace I am currently in. 

Seems removed in #2890

**Comment by tuomas2** [comment]
is it something you really miss? I felt it's unnecessary

**Comment by RuggMatt** [comment]
I do miss it. I use it every week. I had a workspace set up to only show one specific bookmark/label, which was the study pad I work with. This keeps it manageable for me when working with the related study pad. If I had an option to only show the main bookmark for a workspace, I could work with that.

**Comment by tuomas2** [comment]
hmmm i will consider restoring it then

**Comment by tuomas2** [comment]
Reverted in 26794478da135767ebabeacaf1a5badced98b915

**Comment by RuggMatt** [comment]
Thank you! 👍
