### ISSUE TITLE
F-droid metadata needs changes for AndBible 5.0

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#2945]
variant configuration and possibly node upgrade.

**Comment by tuomas2** [comment]
Added tag v5.0.740-fdroid so we will get it try to build that release candidate version. Then we can do PR to f-droid metadata to fix things there.

**Comment by linsui** [comment]
https://github.com/AndBible/and-bible/blob/5cb9cd9550e2386546677fb3a7219d9d0a781eef/app/build.gradle.kts#L356

These libs are non-free.

**Comment by tuomas2** [comment]
> https://github.com/AndBible/and-bible/blob/5cb9cd9550e2386546677fb3a7219d9d0a781eef/app/build.gradle.kts#L356
> 
> These libs are non-free.

are you sure, did you check the license?

**Comment by linsui** [comment]
Emmm, everything in GMS is non-free. Anyway, you can check it at https://maven.google.com/web/index.html#com.google.android.gms:play-services-auth:20.7.0.

**Comment by tuomas2** [comment]
Do you think F-droid does not allow such? If it does not we have to disable sync feature from f-droid builds.

**Comment by tuomas2** [comment]
License is this https://developer.android.com/studio/terms

**Comment by linsui** [comment]
As a core contributor of F-Droid I'm sure GMS libs are non-free and not allowed by F-Droid. :) I found this issue because the build failed. https://gitlab.com/linsui/fdroiddata/-/jobs/5408600494#L604

**Comment by tuomas2** [comment]
Ah, I see. Thanks for finding your way here :-) Then I will remove Google Drive support from F-droid builds. That's a pity though, do you know if there's any "allowed" way to use Google Drive API?

What also needs to be changed probably is to 
- upgrade node (not sure if it is needed but I'm using now myself node version 20) and
- change build to use standardFdroidRelease variant (instead of fdroidRelease if I remember correctly).

**Comment by tuomas2** [comment]
I will do the necessary changes (related to google drive) next week if I have time and trigger new f-droid build then.

**Comment by linsui** [comment]
> That's a pity though, do you know if there's any "allowed" way to use Google Drive API?

I thought you can sync the files to a local directory so that the user can use whatever they want to sync the data.

When the new version is ready just ping me here. :) I'll update the metadata.

**Comment by tuomas2** [comment]
Disabled Google Drive device syncing feature and pushed new tag v5.0.741-fdroid @linsui

**Comment by tuomas2** [comment]
#2615 will eventually be FOSS solution to missing sync feature.

**Comment by tuomas2** [comment]
Looks like it's buildling fine now. Thanks @linsui !
