### ISSUE TITLE
In dual-screen, if AB is lower screen, there's space reserved for system title bar and AB toolbar appears in wrong place

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#296]
Similarly, if AB is in the topmost screen and in fullscreen, it appears that title bar text (white) is written on top of AB text.

**Comment by tuomas2** [comment]
![screenshot_20190210-230134](https://user-images.githubusercontent.com/5811789/52539550-fa055880-2d87-11e9-912e-2a6b875bd379.png)

**Comment by bvahedy** [comment]
Good catch.

**Comment by tuomas2** [comment]
This looks tricky for And BIble. Android does not provide API for detecting window position (i.e. to know if we have status bar or not) in multi window mode. Things would be easy if we would have fitsSystemWindows=true, but we don't. 

Full screen mode works OK in multi window mode too.

**Comment by tuomas2** [comment]
Yep, non split screen case too.  
  


> Hi, 
> 
>   
> 
> 
> This has been reported for split screen (see <https://github.com/AndBible/and-bible/issues/296>) but can you confirm this happening in non-splitted case? Can you post a screenshot? 

  





---
*Attachments:*

1. [Screenshot_20200318-091347.png](https://firebot-prod-media.s3.amazonaws.com:443/email-attachments/ebeca94c-efa0-44f6-84b5-7a295e826d4c/Screenshot_20200318-091347.png)
  ![](https://firebot-prod-media.s3.amazonaws.com:443/email-attachments/ebeca94c-efa0-44f6-84b5-7a295e826d4c/Screenshot_20200318-091347.png)

**Comment by tuomas2** [comment]
Fixed in build 361
