### ISSUE TITLE
Crashes when changing to a specific workspace

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#2965]
Crashes when selecting a workspace named "Study 2". Other workspaces seem ok. Two tickets raised in the help system. Let me know if you need my database.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2171

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2172

**Comment by tuomas2** [comment]
Yes, I need to check the database file.

**Comment by tuomas2** [comment]
PageManager has some data in bookmarksHideLabel column. 

I have a feeling that we have not migrated that column.
Need to fix that...

**Comment by tuomas2** [comment]
Can also make it robust so that illegal data equals to no labels and then it won't crash.

**Comment by tuomas2** [comment]
Ended up not changing migration any more for this. But made it so that it does not crash.
