### ISSUE TITLE
Problem with synching

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#2974]
I think it is because the build i am using on my phone is my own build. Or is it something more serious?

![image](https://github.com/AndBible/and-bible/assets/13920678/52daf8e3-709e-4d31-b0ec-221896f2b1d9)

**Comment by tuomas2** [comment]
Google Drive works only with official builds. Though it is possible to use own API key with own Google Cloud setup. @JJK96 was doing that, and there was discussion in developers matrix group.
