### ISSUE TITLE
The inline references don't disappear when I turn off the option

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#2975]
Maybe i misunderstand something but I expected the inline references to hide when the option is turned off.

![image](https://github.com/AndBible/and-bible/assets/13920678/4849062a-70cd-48c7-b546-7363bd414466)

**Comment by agrogers** [comment]
I needed to change the workspace to remove the references.

**Comment by tuomas2** [comment]
Can't reproduce. Inline references turn on and off when switching the setting.
