### ISSUE TITLE
The calculator refuses to show

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#2976]
I know this has worked for me in the past. But I can't...it just showed... after I sent a bug report from within the app. 

I had already killed the app multiple times.

And now the calculator shows correctly. Very strange.

**Comment by tuomas2** [comment]
Can't reproduce

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2173

**Comment by tuomas2** [comment]
I did not see anything standing out in logcat.

**Comment by agrogers** [comment]
Let's assume it was a one off issue.
