### ISSUE TITLE
Is this forced space required? It messes with the link indenting.

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#2979]
Removing `"&nbsp;"` fixes the indenting problem.

![image](https://github.com/AndBible/and-bible/assets/13920678/fffc1e4c-6336-4d1c-890f-4297496c5c40)

**Comment by tuomas2** [comment]
I am afraid there was a reason for this. It's long time when I made this so I don't remember. Depending on document, links might be clued to the text without any space? Could try to remove it and see if there are issues.

**Comment by agrogers** [comment]
If you can make a test (or point me to one that exists) I can try and
duplicate that test for a few other scenarios so we can track if we break
it in the future.
