### ISSUE TITLE
With many minimized windows, use sliding / stacking to show all of them

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#298]
I created 12 windows for different translations and minimised them. In portrait mode I can not access the last two but they do show when switching to landscape mode only because there is more space. I have a feeling that even in landscape mode if we over run the width of the screen size we won't be able to access the windows that go off the page.

Expected behavior:
Use slide right or left on the minimised window area when they go off the page to show the minimised windows.

**Comment by tuomas2** [comment]
It is true that AB has never worked well with a lot of minimized windows. This should be solved one way or another.

**Comment by tuomas2** [comment]
Will be fixed in build 312

**Comment by bvahedy** [comment]
Verified fixed in 312
