### ISSUE TITLE
Put an option in the settings for auto hiding windows settings... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#299]
Currently the windows settings auto hides after 2 seconds in full screen mode only. Can we add a check box option in the sub menu to allow the windows settings to auto hide in non full screen mode.
The functionality of full screen mode should remain as is.

**Comment by tuomas2** [comment]
We could. Or we could revert to what it used to be, i.e. auto-hiding it always. Not sure.

**Comment by NotSoImportant** [comment]
Window settings button is disturbing for normal reading purpose. Please remove or make it configurable. See #321

**Comment by tuomas2** [comment]
Moving comment from #321
> This button is like a quick access to do window related actions. Hower it is very disturbing while reading.
> So please remove it, make it configurable, or at least hide it in full screen.
> Its not helpful that it hides after ~1sec (in full screen), because on scrolling it reappears.
> Thank you!

**Comment by bvahedy** [comment]
I think it's important to have them there in full screen also because if
you have multiple windows open you can easily close or open other windows.

**Comment by tuomas2** [comment]
I'm not sure yet how we implement this, this topic is open for discussion and ideas. 
But many people are complaining so I would be happy if we found some solution.

@ericjding do you have ideas? :)

**Comment by bvahedy** [comment]
We have to septate these two issues:
 the first one is related to non-full screen mode and   users want the ability to auto hide icons.

The second issue is related to full screen mode and  users want the ability to not see icons when in full screen mode.
 
I don't know what the solution is, but no matter what we do, someone will be unhappy. But we are not here to make everybody happy just the majority.
If we decide that full screen mode is just for reading one translation without any distractions then we could not display  the windows icons and have the users switch to non full screen mode when they want to add more windows or close windows. 
And for non full screen mode we could add a setting to auto hide icons or have them always show as it is currently.

**Comment by timbze** [comment]
Are we all discussing the same version right now where the full screen has the + button on the bottom right and the overlay for the reference is close to bottom center?

This version is already acceptable with me personally but I think one thing that might be an improvement is to not have the + button pop up at all when in full screen mode and it's single window. I think in that case people usually just want to read and not be bothered by things jumping on the screen.

I am not sure what people say about the overlay though. I really like it just the way it is now.

It might be good to consider adding a setting to hide all pop-ups.

**Comment by bvahedy** [comment]
Yes, we are taking about the same version. I'm with Tim on this one, I
personally like the way it is, but there are other people who don't like
the icons on full screen mode. And another group that wants it to be able
to hide them in non-full screen. It's crazy if you ask me.

**Comment by steelwil** [comment]
I never use split windows and would prefer to have an option to disable it all together.

**Comment by timbze** [comment]
I wonder how many people who have an issue with the buttons use the split window feature and how many don't. But I have been thinking, along the lines of what @steelwil says, maybe there should be a setting named "Single Window Mode"...

**Comment by mjdenham** [comment]
What about adding a Windows menu to the App Drawer and removing it from the screen totally unless it is a secondary window.  That would mean that users who rarely use a split screen would not be bothered by the 'annoying' control that keeps popping up.  Also, the top/main window should never need its own Window control.

**Comment by bvahedy** [comment]
Martin, if we remove the main/top windows settings then how do we create a
new window?
I feel one of the greatest functions of Andbible is it's ability to have
multiple windows. I don't understand these users who just want one window.

**Comment by NotSoImportant** [comment]
I remember that in the old app version there had been the possibility to split windows, but without an overlay Button.
I for myself use the app mostly for reading the bible (not only single verses), and only open different windows now and then to compare, or with Strongs. While I'm in "reading mode" I don't want something to overlay the text and also don't want any distracting animation.

**Comment by mjdenham** [comment]
Ben, that is why you need a Windows sub-menu from the main App Drawer menu.
  Like there used to be a Windows sub-menu from the main kebab menu.

**Comment by bvahedy** [comment]
Martin, I'm actually happy with the current icon overlays, and the current
functionality of the windows icons. a user had requested to have an option
to be able to auto hide icons in non-full screen mode, that's why I created
this ticket. We can not make everybody happy. It seems the more positive
functionality we add the more complains we get.
Again, I think 3.1 release if almost perfect in usage and functionality.
People just need to get used to it.

**Comment by bvahedy** [comment]
Let's close this ticket and address it when there are more user complains.

**Comment by NotSoImportant** [comment]
First of all, thank you for all contributions.
I really like a clean app without any online registration to read the bible.

I'm sad that this issue is now just closed. There has been a good conversation about alternatives. I personally dislike any overlay over the bible text. 
I would like to see the window management capability in the kebab menu like suggested by @mjdenham. If that's not likely to happen I would need a setting to get rid of any overlays (even if they could be helpful).
Those overlays are disturbing my reading experiance and would make me look for an alternative app.

**Comment by NotSoImportant** [comment]
I'm refering to 3.0.289 by the way as it's the latest available in F-Droid

**Comment by bvahedy** [comment]
Why can't you enable tilt-to-scroll and go into full screen mode, you can
read the text without any icon overlays.
The icons only appear if you interact with the screen. That's why I think
the current setup has the most functionality.

**Comment by tuomas2** [comment]
Re-opening. This still an issue I'm considering. Not highest possible priority but yet I did not do any decision about this. Feel free to have discussion here.

**Comment by tuomas2** [comment]
> I'm refering to 3.0.289 by the way as it's the latest available in F-Droid

No, f-droid is much older 
https://f-droid.org/en/packages/net.bible.android.activity/

See #313

**Comment by NotSoImportant** [comment]
@tuomas2: thank you. Ok, seems F-Droid only displays my installed version number then.
@bvahedy: don't know how this tilt so scroll works or where to configure. If overlay would be gone in full screen (or not re-appear on scrolling) that would be sufficient.

**Comment by timbze** [comment]
I have one more idea about the buttons.

How if it would follow something like this procedure:
1. When user scrolls down, it turns to automatic fullscreen. After 10-15 seconds of the current functionality, the popup label and button(s) would permanently hide. The only way they would show again is when user scrolls up that the activity bar shows again, or if they start scrolling down fast, like having scrolled down 15-20 lines within a second.
2. When user double taps to turn full screen, also wait 10-15 seconds with current functionality, then hide label and button. The only time now to show label and buttons is when user starts fast scrolling either up or down, like 15 lines within a second.

I also am thinking of swipe from right edge. Presently swiping from left edge brings up menu drawer. Swipe from right edge goes to next chapter. We could have the left/right swipe gestures to move to next chapter still, but add the swipe from right edge option, and bring up a floating action button for add new window, when in full screen mode. Or we could have the swipe from right edge bring up the window  menu options.

I think there are many who read just the Bible, and don't use the app so much for additional studies/commentaries. For those the buttons popping up are a real downside.

**Comment by NotSoImportant** [comment]
I like that idea of @timbze.
Sounds like a good compromis.
Once implemented the timing of 10-15 seconds can be tested and adapted if needed.

**Comment by bvahedy** [comment]
How about just adding an option, tick box, in the kebab menue on the menu bar (top right), that would hide all window overlays in both modes, full screen and non full screen mode,
Those having multiple windows open would then need to untick that box to operate on windows functions. This way everybody will be happy. I think Martin originally had this idea, and I may be just repeating it.

**Comment by bvahedy** [comment]
In the setting check the box for tilt to scroll. Then enter full screen
mode by double tapping on the screen. To reset the position of the tilt,
keep your device flat initially, scroll one verse up or down. Now as you
raise the top of your device up towards you, verses scroll up automatically
and all overlays go into hiding.

**Comment by bvahedy** [comment]
@timbze, a lot of users are currently confused about all the menu functions and settings that AB is capable of,  I feel adding swipe right/left capabilities for settings will create more confusion or they would never find out about it. At this point it's better to keep things simpler in my view.

**Comment by NotSoImportant** [comment]
Hi, sorry @all: I now installed latest version from github and overlay at the bottom (and not hiding and appearing again) is *not that disturbing* than it was being at the top. (however the centered overlay should be aligned wit it = please also align at the bottom).
so - don't be angry: it's fine for the window button to stay like it is.
@bvahedy: can still not find the tilt to scroll setting.

**Comment by bvahedy** [comment]
@notsoimpoertant, assuming you have the latest beta 3.1.302  the tilt to
scroll is located on the kebab icon, on the top right of the menu bar, tap
on that and it's the third item down the list, check that box.

**Comment by NotSoImportant** [comment]
Have 3.1.302 but cannot see it
![screenshot_20190225-073036](https://user-images.githubusercontent.com/35758921/53318533-e0a7f480-38cf-11e9-9d56-229ad0fc4548.png)

**Comment by bvahedy** [comment]
Do you know if your device has an accelerometer?

**Comment by NotSoImportant** [comment]
According to the specs it has accelerometer and gyro, however no compass.

**Comment by bvahedy** [comment]
According to Tuomas, the developer, if the app. Does not detect the tilt
sensor in your device then it will hide that option from the settings. What
is the device you are using?

**Comment by timbze** [comment]
I think this issue can be closed.
1. There is a setting to hide window buttons on the side since we have them at the bottom (and they can be hidden on bottom too)
2. 3.4 has a setting to disable the reference text overlay that appears in full screen

Someone can re-open if they think this specific issue needs further attention. Otherwise open a new issue.

**Comment by NotSoImportant** [comment]
Thank you. That's fair enough.
