### ISSUE TITLE
Speak copies panes

### ISSUE THREAD

**Issue by Noitarud** [AndBible/and-bible#2995]
This complaint was going to be about having speak change panes.
**Beta** (probably okay)
I noticed if I had started then pause speak, the headphone icon was missing if I changed  pane or if I changed workspace+pressed the headset key (continues last workspace speak) then after pause noticed the headphone icon was missing. Yes resolvable with Stop press but was not first thought.

**Production version**
It did close speak toolbar when I changed workspace. Initially. I had it start on dictionary and then paused, changed workspace, pressed key, it played the newly active pane (dictionary was short, ended). [Changed to Bible pane, told to start] Then if I changed pane or workspace and pressed headphone set key to begin again, it would change the active pane to show the present Bible verse - intended? I could pause, change panes, play, and repeat until all panes changed over to read same (not identical, may have Strong's numbers or not).

**Comment by tuomas2** [comment]
beta is now production since 2nd november so issue is fixed.
