### ISSUE TITLE
Idea: "Open link in current window" from context menu

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#30]
Now that there is multiple window support and links from a book/commentary are opened in a special window, in some cases it would be nice to have ability to open link in current window also. 

I think this could be implemented best by using context menu (after long press of a link), from which user could choose function "Open link in current window".

**Comment by Emet-like-AndBible** [comment]
tuomas2

If you make such a possibility, then the logical conclusion is the opposite-if AB preferences globally chosen to open all links in the same window, so that through the context menu, you can open the desired links in a special window.

**Comment by tuomas2** [comment]
This is implemented already.
