### ISSUE TITLE
TTS should follow text by default?

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#3011]
I think this changed somewhere between v4 and v5. Earlier, the text would always scroll along with TTS, but now it has to be enabled. I saw an issue about it somewhere too (in email?). I was thinking maybe scrolling with TTS should be the default but then users have the option to disable it?

**Comment by tuomas2** [comment]
I changed the default behavior but perhaps we should change it back. I don't like tts follow text (want to see earlier text etc) so I thought it would be better default. 

Also related: #2963

**Comment by timbze** [comment]
I think #2963 will improve the user experience. I think how a user likes it depends on if he carefully is reading the text, or just wants to glance at it once in a while. Maybe it's fine to leave as is

**Comment by agrogers** [comment]
I don't use it but I would expect it to follow the text.

**Comment by tuomas2** [comment]
Text follows speech could be also improved to be such that it scrolls the screen only when highlight is not any more visible completely

**Comment by timbze** [comment]
> Text follows speech could be also improved to be such that it scrolls the screen only when highlight is not any more visible completely

That would be a good idea, and good default I think
