### ISSUE TITLE
Not possible to scroll down to verse

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#303]
> The problem is that when there is one Bible view opened and filling the whole screen (not necessarily fullscreen), scrolling down does not change the current verse.
> 
> I didn't test with two windows opened, but in the basic way to use AndBible (without opening multiple views at the same time), until a very recent update (I think the one adding the native Android menu collapsing on the left side of the screen), it used to be possible to scroll down to change the current verse. This allowed us easily to select a verse to open it in a commentary (by switching to a new Window by clicking on the name of the commentary rather than by opening a second view. This does not change the underlying problem but just to clarify my use case)
> 
> Empty lines were added to the bottom of every chapter to allow us to select even the very last verse of the screen by scrolling down. Now, if a chapter fits the screen it is no longer possible to scroll down. It is only possible to scroll down to the extent that text overflows. This means that you can only "select" the first verses of a chapter by scrolling down. By selecting I mean, making the verse reach the top of the screen so that the current verse is changed. Many Bible chapters are short and therefore fit the screen without needing any scrolling, therefore it is not possible to change the current verse by scrolling at all in these verses. But even for those overflowing the screen, it is only possible to select the very first verses by scrolling. The extra empty lines that allowed us to scroll to change the current verse are no longer there.

Probably an issue with large screens (with small font). Maybe next chapter content does not load automatically in this case filling the space?

**Comment by nkosi23** [comment]
>Probably an issue with large screens (with small font)
This is indeed exactly my case. I use a Galaxy S8 phone and the font is set to the smallest possible in And Bible settings.
And indeed the next chapter does not load automatically when scrolling down

**Comment by tuomas2** [comment]
I could reproduce this with my phone. For some reason this does not happen in emulator. But this should be enough to investigate issue.

**Comment by tuomas2** [comment]
Do you remember in which version did this work properly?

**Comment by tuomas2** [comment]
Fixed in c80b35672a8a392118e35932a02e244cf3f5b9cd

**Comment by tuomas2** [comment]
Thanks you @nkosi23 for good bug report :)

**Comment by bvahedy** [comment]
I don't see the issue now, but I hadn't seen it before either. I'm assuming this is fixed for now.
