### ISSUE TITLE
Clean ALL files

### ISSUE THREAD

**Issue by pepaulo** [AndBible/and-bible#3030]
**Describe the bug**
After I updated it. The app version 5.0.754 ALL my files download was erased.

**Comment by tuomas2** [comment]
hmm which files? very strange

**Comment by tuomas2** [comment]
please be more specific what exactly happened. also your device info etc. logcat etc (main menu - report a bug) also could help.

**Comment by tuomas2** [comment]
paused release until you provide more info.

**Comment by pepaulo** [comment]
> hmm which files? very strange 

After I updated it the file wich I downloaded was erased from app. The files was ALL: bibles, fonts, epubs... 

My phone config:
![Screenshot_2023-11-10-06-42-10-637_com.android.settings.jpg](https://github.com/AndBible/and-bible/assets/7110757/dd8dc800-f696-4bbe-8a3a-1de9bf1396c9)

Informação sobre o aparelho:
Version: 5.0.754#0a2722635 googleplay standard release (built 09/11/23 16:06:19)
Android version: 13
Android SDK version: 33
Manufacturer: Xiaomi
Model: M2102J20SG
Storage Mb free: 128350
WebView version: 119.0.6045.66
SQLITE version: 3.42.0
Used heap memory in Mb: 11
Max heap memory in Mb: 256

**Comment by tuomas2** [comment]
bookmarks etc were intact?
from which version did you update?

**Comment by pepaulo** [comment]
> bookmarks etc were intact?
> from which version did you update? 

Bookmarks and etcs was erased. I updated it from 5.0.750

**Comment by tuomas2** [comment]
so like fresh install. Did you have earlier version from F-droid?

**Comment by pepaulo** [comment]
> so like fresh install. Did you have earlier version from F-droid? 

I install It from Github. Now I use the last version. I use AndBible for tests for needs, modules, modules creation and translation. I don't use F-Droid version.

**Comment by tuomas2** [comment]
> > so like fresh install. Did you have earlier version from F-droid?
> 
> I install It from Github. Now I use the last version. I use AndBible for tests for needs, modules, modules creation and translation. I don't use F-Droid version.

So you installed manually update from 750 to 754, both were from Github and Google Play was not involved?

**Comment by pepaulo** [comment]
> Google

I install it using MiPicks, an app of Xiaomi. I ever install from manually.

**Comment by tuomas2** [comment]
MiPicks installs file from Github? 
I don't know but somehow it has cleared data (kind of same result as with uninstall + reinstall). Reason for this sounds a mystery to me. I don't have access to Xiaomi phones so can't try myself. 

But could you try to reproduce the issue, i.e. uninstall AndBible, then install 750, install some mods and add bookmarks, then upgrade 754 and see if it again deletes data?

**Comment by pepaulo** [comment]
> MiPicks installs file from Github? 
> I don't know but somehow it has cleared data (kind of same result as with uninstall + reinstall). Reason for this sounds a mystery to me. I don't have access to Xiaomi phones so can't try myself. 
> 
> But could you try to reproduce the issue, i.e. uninstall AndBible, then install 750, install some mods and add bookmarks, then upgrade 754 and see if it again deletes data?

Yes. I can do this.

**Comment by pepaulo** [comment]
I have download the previous version 5.0.750 and download some mods. But when I update to 5.0.754 ALL files was erased. The user files was erased once again.

**Comment by tuomas2** [comment]
Does this happen between other versions? Is it possible to test? For example from 742 to 750? Somehow I can't see why 754 in particular would delete anything.

**Comment by pepaulo** [comment]
> Does this happen between other versions? Is it possible to test? For example from 742 to 750? Somehow I can't see why 754 in particular would delete anything. 

From 742 to 750 don't have te problem.

**Comment by tuomas2** [comment]
and 742 -> 760 and 750 -> 760? 
There's one innocent gradle plugin upgrade which I could try to revert and make a test build for you, but I can't in any way see that it could cause anything.

**Comment by tuomas2** [comment]
Here is test build without gradle plugin upgrade https://github.com/AndBible/and-bible/releases/tag/build-760-pepaulo

**Comment by tuomas2** [comment]
Can you test upgrade from 750 to [special version of 760](https://github.com/AndBible/and-bible/releases/tag/build-760-pepaulo)? (and if it works, then 750 to standard version of 760, to confirm the root cause of the issue).

I'd like to continue distribution of upgrade, but this is that sort of issue that I would not want anyone to be facing so to be sure I have still kept upgrade halted.

**Comment by pepaulo** [comment]
> Can you test upgrade from 750 to [special version of 760](https://github.com/AndBible/and-bible/releases/tag/build-760-pepaulo)? (and if it works, then 750 to standard version of 760, to confirm the root cause of the issue).
> 
> I'd like to continue distribution of upgrade, but this is that sort of issue that I would not want anyone to be facing so to be sure I have still kept upgrade halted.  

I tested and the upgrade was good of 750 to special version. Don't had problem. The bus was only on update of the 750 to 754 stable version.

**Comment by tuomas2** [comment]
did you test 750 to normal 760 version? If so, we can be sure that the issue is due to c14dbc7fe6de77c07f23faf37e9744c816c672bd . Then I will release hotfix release (will be 755) to production.

**Comment by pepaulo** [comment]
> did you test 750 to normal 760 version? If so, we can be sure that the issue is due to c14dbc7fe6de77c07f23faf37e9744c816c672bd . Then I will release hotfix release (will be 755) to production.

Yes. Before I updated to normal version and was correct. After I updated to especial version and was good.

**Comment by tuomas2** [comment]
Good. Releasing 755 soon. Thank you! Though I did not get any other report of this, it is better to be safe than sorry here.

**Comment by pepaulo** [comment]
> Good. Releasing 755 soon. Thank you! Though I did not get any other report of this, it is better to be safe than sorry here.

I'm here for test and help you for this wonderfull tool AndBible. Thank you. God blessed.
