### ISSUE TITLE
onActivityResult not called in MainBibleActivity

### ISSUE THREAD

**Issue by GauravCreed** [AndBible/and-bible#3031]
May i know why onActivityResult not called in MainBibleActivity

```
StorageManager storeManager = (StorageManager) context.getSystemService(Context.STORAGE_SERVICE);
      Intent intent = storeManager.getPrimaryStorageVolume().createOpenDocumentTreeIntent();
      intent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION
              | Intent.FLAG_GRANT_WRITE_URI_PERMISSION
              | Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);

      Uri uri = intent.getParcelableExtra("android.provider.extra.INITIAL_URI");
      String scheme = uri.toString();
      scheme = scheme.replace("/root/", "/document/");
      String finalDirectoryPath = scheme + "%3A" + startDirectory;
      uri = Uri.parse(finalDirectoryPath);
      intent.putExtra("android.provider.extra.INITIAL_URI", uri);
startActivityForResult(intent, REQCODE_audio);
```

`public void onActivityResult(int requestCode, int resultCode, Intent data) {
        Log.d(TAG, "Activity result:" + resultCode);
        printLog("==== onActivityResult : " + requestCode + "  " + resultCode);
		super.onActivityResult(requestCode, resultCode, data);
    }`

**Comment by alerque** [comment]
Please don't ping a bunch of unrelated people when opening issues.

**Comment by tuomas2** [comment]
what is the point of this issue anyway? please open some context... some copypasted java code in kotlin app makes me feel this is completely unrelated.

**Comment by GauravCreed** [comment]
> Please don't ping a bunch of unrelated people when opening issues.

I will keep a note for this

**Comment by GauravCreed** [comment]
> what is the point of this issue anyway? please open some context... some copypasted java code in kotlin app makes me feel this is completely unrelated.

I am adding "Use this folder" permission for getting access of "Music" folder in MainBibleActivity as per my question, then i am getting permission dialog then press "Allow" button from this dialog. but that result not get back.

is there any solution for this?
Thanks(_)
