### ISSUE TITLE
Bible linking from Firefox doesn't work

### ISSUE THREAD

**Issue by mcepl** [AndBible/and-bible#3033]
**Describe the bug**
When I click on this link https://read.andbible.org/1Sam.1.2?v11n=KJV in Firefox for Android from F-Droid (actually Fennec Mozilla/5.0 (Android 13; Mobile; rv:109.0) Gecko/119.0 Firefox/119.0) the blank page saying I need to install AndBible opens. When I do the same with the system Chrome, AndBible opens.

**Bug was found on AndBible version**
Build 5.0.742#39a4e4035 fdroid standard release (build 03/11/23 23:44:05)

**To Reproduce**
1. Go to https://github.com/AndBible/and-bible/wiki/Bible-links with the Fennec
2. Click on https://read.andbible.org/1Sam.1.2-1Sam1.5?v11n=KJV
3. See error

**Expected behavior**
AndBible opens on 1. samuel 1:2 or thereabout.

**Smartphone (please complete the following information):**
 - Device: Nokia TA-1334 
 - OS: Android
 - Version 13

**Comment by tuomas2** [comment]
Hmm, possibly Firefox issue? Or do links to other apps work fine?

**Comment by mcepl** [comment]
It is possible it is necessary to do something more on the Firefox side (being privacy/security concerned they are), but it is possible. All my maps links end up in OSMAnd.

**Comment by mcepl** [comment]
Actually, there is a setting: Settings/Open links in applications.
