### ISSUE TITLE
Text vanished after update 5.0 (Huawei old WebView version)

### ISSUE THREAD

**Issue by orcind** [AndBible/and-bible#3036]
Good day! Thanks for your great work. I have a problem: After update 5.0, text vanished (Android 10).

**Comment by tuomas2** [comment]
Can you also send bug report via Main Menu -> Report a bug, so we get logcat and other necessary technical information about your phone?

**Comment by orcind** [comment]
Tuomas, i sent bug report on Your email.

**Comment by tuomas2** [comment]
Key error: 
`11-11 22:41:55.096  7339  7339 I BibleView[58b26]: bibleview-js: ERROR Uncaught SyntaxError: Unexpected token '?'`

**Comment by tuomas2** [comment]
`11-11 22:43:27.835  7339  7737 I ErrorReportControl: WebView version: 10.0.0.311`

Can you try to update system webview? 
I'm reading from [here](https://www.huaweiupdate.com/huawei-webview-updated-to-12-1-1-324/) that Huawei has released version 14.0.0.331 of their webview. I believe that will solve the problem.

**Comment by tuomas2** [comment]
In AndBible 5.0 js side, we have used new [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) javascript operator `?.` that most likely is not supported by that version of webview. 

We should also check which version of Google's webview is required... (#3037)

**Comment by orcind** [comment]
After webview update, AndBible works great, thank You Tuomas!
