### ISSUE TITLE
Bible window sync issue with "reverse split mode"

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#305]
**To Reproduce**
1. Open two windows with same translation.
2. Scroll a little down. (verses matches OK)
3. Change to reverse split mode. 
4. Bibles are either not synced at all (other window does not sync), or they are synced wrongly (not matching verses in windows)

**Expected behavior**
Windows verses matches each other.

**Comment by tuomas2** [comment]
I think I have seen something similar earlier (probably bug is not directly related to reverse split mode feature), but now this is forturnately very easy to reproduce.

**Comment by tuomas2** [comment]
Will be fixed in 298.

**Comment by bvahedy** [comment]
Verified fix in build 315.
