### ISSUE TITLE
[Feature] Themed / Monochromatic App icon support

### ISSUE THREAD

**Issue by sebastien46** [AndBible/and-bible#3053]
**Is your feature request related to a problem? Please describe.**
The app's icon looks out of place when using themed icons (although it is very pretty)

**Describe the solution you'd like**
Implement a monochromatic version of the icon when it is enabled by the user.

**Describe alternatives you've considered**
Leave the app icon as-is

**Additional context**
[Developer Reference](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive)

**Comment by sebastien46** [comment]
Here is a mockup I made using Inkscape using the original vector:
![vector](https://github.com/AndBible/and-bible/assets/57289288/a3cbb579-d709-4fa6-8da4-9777923efa22)

**Comment by agrogers** [comment]
I suspect it is not too hard to do now that Tuomas has already implemented the changing of the icon for the discrete mode.  However it is probably not a feature that is widely requested. You might want to consider making it a higher priority by sponsoring development time: https://shop.andbible.org/

**Comment by tuomas2** [comment]
Related: #1126

**Comment by Noitarud** [comment]
Original: #1227
I kinda think transparent background icons are neat (SVG?) 😉
