### ISSUE TITLE
App crashes  (WebView crash, due to OOM or update)

### ISSUE THREAD

**Issue by githubrajan** [AndBible/and-bible#3077]
**Describe the bug**
No Idea AND bible app seems to be closing by itself. I though it might be something to do with Chrome Update & so tried the update and ran the App again -- and there seemed no problem yesterday. But today when I am using it again, the same story back again. Attached please find the crash report that I was able to save to my Drive. 

**Bug was found on AndBible version**
5.0.770.

**To Reproduce**
not sure - 

**Expected behavior**
not sure ... 
[logcat.txt.gz](https://github.com/AndBible/and-bible/files/13506993/logcat.txt.gz)

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S6]
 - OS: [e.g. Android]
 - Version [e.g. 8.0]

**Additional context**

**Comment by tuomas2** [comment]
Found this in logcat:

```
11-28 19:11:06.502 11470 11673 W cr_ChildProcessConn: onServiceDisconnected (crash or killed by oom): pid=11676 bindings:W  S
11-28 19:11:06.510 11470 11470 E chromium: [ERROR:aw_browser_terminator.cc(156)] Renderer process (11676) crash detected (code -1).
11-28 19:11:06.516 11470 11470 E chromium: [ERROR:aw_browser_terminator.cc(112)] Render process (11676) kill (OOM or update) wasn't handed by all associated webviews, killing application.
```

It says OOM or update. Did you have any huge document in any of the AndBible windows?

**Comment by githubrajan** [comment]
Total of 3 windows while using the app.

Two versions of bible & my User notes. Can the latter be the problem?
This i3 Lenovo Chromebook is installed with 8GB of memory mostly shows
around 1.5GB is free of the total 7.6GB available  (after upgrading from my
prior one of 4GB as it was seemed to be be slow).

**Comment by githubrajan** [comment]
Tried closing the USER windows in AND and no other apps running. Still
Crashes !!! (memory/ CPU info attached)

**Comment by tuomas2** [comment]
Attachment not visible, please reupload using github ui

**Comment by tuomas2** [comment]
This issue sounds so weird that you could try reinstallling app. Make sure you have functional backups of your database and modules first.

Maybe same thing for your system webview. Feels that something is wrong/broken in that device. Nobody else has reported anything like that.

**Comment by githubrajan** [comment]
Ok, I will try that.

**Comment by tuomas2** [comment]
Did it work?

**Comment by githubrajan** [comment]
Thanks Tuomas for the follow up.

Did a power wash followed by reinstall and so far seems to be working fine
now. I'll keep you posted of anything that warrants your attention,  if any

Warm Regards & Blessings,

**Comment by tuomas2** [comment]
Ok closing this now, please re-open if needed :-)
