### ISSUE TITLE
When in full screen mode and night mode active auto hide does not happen... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#308]
When night mode is active and in full screen mode, the windows menu and minimised windows at the bottom don't auto hide.

Expected behavior: 
These icons should hide after a few seconds as it does in non-night mode.

**Comment by tuomas2** [comment]
Can't reproduce. I think this was fixed in 297.

**Comment by bvahedy** [comment]
This is now working in 297-rc
I don't know if you did anything or not.
