### ISSUE TITLE
When a TSK ref. Link is displayed the minimised windows icons are moved up at the button... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#309]
To reproduce:
Note: Full screen by scrolling must be unchecked.

1) Go to a passage
2) tap on speak icon
3) pause speech
4) tap on tsk on menu bar
5) tap on link ref. in tsk
6) close the button window
7) tap on the stop button on speak menu bar.
8) from the menu bar switch to another translation.

All the minimised windows are 3-4 lines from the bottom of the screen.

**Comment by tuomas2** [comment]
Could you re-check this too with 297?

**Comment by bvahedy** [comment]
Same thing, it's working in 297. It may have had to do with auto hiding the
windows setting.

**Comment by bvahedy** [comment]
This is now working in 297-rc
