### ISSUE TITLE
Remap Septuagint psalm numbers

### ISSUE THREAD

**Issue by obsgolem** [AndBible/and-bible#3112]
**Is your feature request related to a problem? Please describe.**
The Septuagint text I am using, the crossway one, uses different psalm numbers from the standard English psalm numbering. This makes it difficult to do side by side greek/English psalm reading.

**Describe the solution you'd like**
Remap the Septuagint psalm numbers to match the English ones.

**Describe alternatives you've considered**

**Additional context**

**Comment by tuomas2** [comment]
If the modules were having correct versifications (V11n) there would not be this issue.
However, this falls into category of *text/module issue*, which is out of scope for AndBible developers.
See our [FAQ](https://github.com/AndBible/and-bible/wiki/FAQ#i-found-text-issue-in-one-of-the-bible--commentary-etc-modules-in-andbible) for more info.
