### ISSUE TITLE
Speech in two windows making both windows to be set with the same translation... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#312]
With two windows open do the following:

1) top window is kjv
2) bottom window is esv
If you tap on the bottom window and then tap on speak icon. esv is read and both windows synchronize correctly.

3) stop speech
4) tap on the top window
Start speech and you will notice that the bottom window is switched to kjv.

Also the synchronization is stopped, only the bottom window moves with the speech.

This used to work before.

**Comment by tuomas2** [comment]
Will be fixed in build 301
