### ISSUE TITLE
Way outdated F-droid version

### ISSUE THREAD

**Issue by new-on-github** [AndBible/and-bible#313]
The latest version on f-droid is 2.11.xxx

It would be nice to have the newest Version on fdroid.

**Comment by tuomas2** [comment]
From my side I have made what I can do. 

Now just waiting for f-droid people to do its part.

https://gitlab.com/fdroid/fdroidserver/merge_requests/606
https://gitlab.com/fdroid/fdroiddata/merge_requests/4120

**Comment by masscream** [comment]
Still no update / explanation ? Now the newest version on Gplay is 3.1.305, there is a 9 months difference. Is f-droid making its users leave or is the project being dropped....

**Comment by tuomas2** [comment]
You can try to push f-droid to get forward those merge requests. I feel that I have done what I can.

**Comment by ildar** [comment]
in https://gitlab.com/fdroid/fdroidserver/issues/512 people advise pulling
libs from jcenter or ask libs developers to publish at jcenter.
What libs do you use, Tuomas?

**Comment by tuomas2** [comment]
kotlinx-serialization-runtime from kotlinx repository https://kotlin.bintray.com/kotlinx 

See https://github.com/Kotlin/kotlinx.serialization

**Comment by tuomas2** [comment]
Update: kotlinx-serialization-runtime is now in maven central. So we probably get fdroid builds running soon. :-) 

https://gitlab.com/fdroid/fdroiddata/merge_requests/5884

**Comment by tuomas2** [comment]
Now the latest beta build 319.4 is live in F-droid. 
This beta was 'test build' for f-droid, my plan is from now on to release only stable releases there.

**Comment by ildar** [comment]
👍
thanks a lot!
