### ISSUE TITLE
Missing legacy launcher icons (Android 6)

### ISSUE THREAD

**Issue by cbrt64** [AndBible/and-bible#3131]
On my phone (LG V30 H932 Android 7.1.2), between 5.0.771 and 5.0.781 (Play Store versions), the Bible Study launcher icon was replaced by the "Green Droid" default icon (persisting in 5.0.792).

Per [the docs](https://developer.android.com/studio/write/create-app-icons#launcher), Android < 8 won't use adaptive launcher icons. Comparing APK contents, it appears the legacy icons got left out of the build, perhaps by #3061? When I downgraded the app, the correct icon reappeared; upgraded, and it reverted to green droid.

It looks like this is not unheard-of; I currently have two other apps that show the same default icon, [Google One](https://play.google.com/store/apps/details?id=com.google.android.apps.subscriptions.red) and [HeartBeat](https://github.com/berdosi/HeartBeat).
See also [1](https://www.reddit.com/r/AndroidQuestions/comments/12bhmmh/one_of_my_apps_is_showing_a_green_android_robot/) and [2](https://stackoverflow.com/questions/45141488/default-robot-icon-instead-of-app-icon-after-installation).

Thank you for all your hard work making such a useful app; and Merry Christmas!

**Comment by agrogers** [comment]
I'm guessing this is the source of the problem.

https://github.com/AndBible/and-bible/pull/3061

Perhaps you can suggest a solution that keeps that feature without breaking the old icons.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=2314

**Comment by cbrt64** [comment]
Confirmed fixed by pre-release 5.0.793. 👍

I'm neither an android dev, nor the son of one, or I'd have eagerly made a PR and saved you the work. I'll say it again: thanks for all the effort you put into this project.
