### ISSUE TITLE
11 uppercase "THE's" in the KJVPCE that should not be there.

### ISSUE THREAD

**Issue by InsufferableHexavaxxedNPC** [AndBible/and-bible#3132]
**Describe the bug**
The word "THE" (likely to be a leftover, mangled "THE END") is found 11 times at the very end of 11 different books in the King James Bible: Pure Cambridge Edition (KJVPCE module). Here's a list of the books in question:

Ezra.
Nehemiah.
Job.
Ecclesiates.
Ezekiel.

John.
Romans.
1 Corinthians.
Colossians.
1 Thessalonians.
1 Timothy.

The one complete "THE END" found in Revelation is there just as it's supposed to, but should probably be on a line by itself to reflect the stylistic choice of the printed copy.

**Bug was found on AndBible version**
Version 5.0.792#65e873836 fdroid standard release (built 19/12/23 12:53:26)

KJVPCE 2.0 (2022-09-28)

**To Reproduce**
Jump into the last chapter/verse of each of the aforementioned books and confirm. E.g. "John 21:25".

**Expected behavior**
I'd expect AndBible to show nothing where these "THE's" are.

**Screenshots**
Probably not needed, but let me know if you do.

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy J7 Prime]
 - OS: [Android]
 - Version [6.0.1]

**Additional context**
Thanks for your time and sorry for any inconvenience.

**Comment by tuomas2** [comment]
This looks likea a text/module issue. Please see [our faq](https://github.com/AndBible/and-bible/wiki/FAQ#i-found-text-issue-in-one-of-the-bible--commentary-etc-modules-in-andbible) how to proceed with those.
