### ISSUE TITLE
Repeat passage jumps to the wrong verse when invoked from bookmark... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#314]
![smartselect_20190216-075716_and bible](https://user-images.githubusercontent.com/46405809/52902166-22df8080-31c2-11e9-9057-e92c512cd789.jpg)
To reproduce:

Note: auto speak bookmarking is checked in the settings.

1) setup a repeat passage for Rev. 1:2-5 in ESV
2) play the passage and let it go through once
3) on the second pass stop it on verse 4, this creates an automatic bookmark.
~~4) from bookmark select a different passage from a different translation, doesn't matter what it is. Then stop that.~~
5) from bookmarks select the Rev. Repeat passage From ESV. Speech starts from verse 4 but it  repeats verse 3-5 instead of 2-5

**Comment by tuomas2** [comment]
Step (4) is not needed to reproduce. 

Note that verse 2 is also read aloud, but only text sync is not working properly in this case (jumps only after verse 2 is read, to verse 3).

**Comment by tuomas2** [comment]
Will be fixed in build 301
