### ISSUE TITLE
Import/Export a single (or multiple) studypad(s)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3141]

**Comment by tuomas2** [comment]
UI: 

- Export: When studypad is opened, window button menu has function "Export as Study Pad".
  - Another options: "Backup Study Pad", "Export as Backup", "Export as .abdb", "Export as ABDB".
  - Now there's already "Export as HTML" option, so it's good if it resembles that option.
  - In "Study Pads" view (as well as Label Settings / Labels view) coul have multi-select and function "Export as ABDB".
- Import: 
   - Study Pads view: add 3dot menu and there "Import studypad" option.
   - Also from
     - Restore Database (Restore from). 
     - Install document from a file
   - If studypad, label text entry, label or bookmark is already imported (UUID exists in current db), then just ignore those. 
- Fileformat will be same as Database backup format, i.e. .abdb. 
- Actual import function is implemented in #3259

**Comment by agrogers** [comment]
I sometimes feel like the title of the Study Pad should be a link to some
action. Maybe it could be used to better effect than adding more options to
the Window button.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
Implemented multi-export.

![image](https://github.com/AndBible/and-bible/assets/5811789/568931ca-015a-42a2-92a5-5bb774fe85bd)

![image](https://github.com/AndBible/and-bible/assets/5811789/aae799da-221d-4159-8c0b-6c32773b31ad)

Implemented instruction popup:
![image](https://github.com/AndBible/and-bible/assets/5811789/7af2eb0a-cac1-4264-b770-ab0dbdc7cef9)

**Comment by tuomas2** [comment]
This was implemented already.
