### ISSUE TITLE
Is it possible for you to add the Modern English Version(Mev)?

### ISSUE THREAD

**Issue by enderpirate98** [AndBible/and-bible#3144]
**Is your feature request related to a problem? Please describe.**
I have used Bible Gateway before but it is kinda jank and not Foss and I would love to switch to this but it doesn't have Mev 
**Describe the solution you'd like**
Add the Mev to the list of bibles
**Describe alternatives you've considered**
I could use a different modern English version if it exists or I could use a spyware bible app
**Additional context**

**Comment by tuomas2** [comment]
Please see our [FAQ for an answer](https://github.com/AndBible/and-bible/wiki/FAQ#please-add-module-x-to-andbible)
