### ISSUE TITLE
In full screen mode menu bar covers the verse selected... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#316]
When in full screen mode you select the top verse, app brings down the menu bar and completely coveres the selected verse. It's very annoying.

Expected behavior:
When coming out of the full screen mode move the verse at the top to below the menu bar.

**Comment by tuomas2** [comment]
I agree that in this case it would be better to scroll the highlighted verse to view.

**Comment by tuomas2** [comment]
Will be fixed in build 299

**Comment by bvahedy** [comment]
Verified fix in build 315.
