### ISSUE TITLE
Notes list position is lost when returning to the list... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#317]
When entering "my notes", a list of notes is presented.  select an item from the list and then after making a note hit the back button. Now you are returned to the top of the list instead of the place you were previously on the list.

**Comment by timbze** [comment]
Along the same lines, this same issue is also present in these places:
1. From find results, after clicking a result which opens Bible and then pressing back brings the user back to top of find list.
2. From bookmarks, opening a certain bookmark which opens Bible and then pressing back brings the user back to top of bookmarks list.
3. When looking at reading plan days and going to a certain day, when going back into the list it should open up where we last looked at.

**Comment by tuomas2** [comment]
> I have lots of bookmarks. When I am in the middle of them all I tap on one bookmark to ses whole verse. And when I press back buuton on my phone I go to Bookmarks. That's ok. But it is not ok, to put me again on first bookmark. Which bookamrk I was just reading? I have to remember and scroll to it. It should be fine if the back butoon would go back to exact bookmark where i left.

> Bookmarks also have labels. It woulb be nice when I press back on my phone to go to exact label and exact bookmar line as I was befere.

**Comment by tuomas2** [comment]
I believe this is not relevant any more if using my notes window. Please re-open if you disagree.
