### ISSUE TITLE
Merge develop to master in jsword and test changes

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3173]
Contains some major changes:
- https://github.com/AndBible/jsword/pull/13

**Comment by tuomas2** [comment]
quickly tested window sync between KJV and FinRK and it works. Ping @UnasZole, perhaps you could also test after next beta build (802) is out.

**Comment by UnasZole** [comment]
I just loaded build 802 on my phone, and I confirm it works !
Thanks a lot for helping me extend this feature !
