### ISSUE TITLE
Add support for OT quotes in NT

### ISSUE THREAD

**Issue by LAfricain** [AndBible/and-bible#3177]
**Is your feature request related to a problem? Please describe.**
If a module have Old testament quotes in the NT rendered by the tag <seg type="otPassage"> this quotes don't appear.

**Describe the solution you'd like**
Show this tag as small capitals or in an other color.

**Additional context**
An example is the FreNCL Rm 9. You can see the quotes from the OT.

**Comment by tuomas2** [comment]
I made it so that it is written in italic style. Style can be customized with [custom css](https://github.com/AndBible/and-bible/wiki/Custom-CSS-for-modules-for-And-Bible). Style should be defined for class otPassage (used with span element).

**Comment by LAfricain** [comment]
Waouh! So quick thank you! You know in which release it will work?

**Comment by tuomas2** [comment]
I'll make beta (795) later today, it will be included in that.
