### ISSUE TITLE
Calculator mode does not show on launch unless app is running in background

### ISSUE THREAD

**Issue by kj7rrv** [AndBible/and-bible#3178]
**Describe the bug**
When the calculator mode is enabled, it only opens to the calculator if the app was already open in the background. It should go to the calculator any time the app is opened.

**Bug was found on AndBible version**
`Version 5.0.781#ad34d14fc fdroid standard release`

**To Reproduce**
1. Enable "Calculator" in "Application preferences"
2. Close app
3. Remove app from recent apps (killing the process)
4. Open the app again from the home screen

**Expected behavior**
The calculator appears

**Screenshots**
The Bible app appears like it would without calculator mode

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord N200 5G
 - OS: Android
 - Version: 12

**Additional context**
I was only testing this feature, as I do not live in a persecuted country, but for those who do, this bug could be quite dangerous, as it negates the intended functionality of this safety feature.

**Comment by timbze** [comment]
Confirmed this happens also in latest version 794

**Comment by kj7rrv** [comment]
I tried with the discrete version, and it works as expected on that version. It's still not good that it doesn't work on the regular version, but at least the discrete app works properly.

**Comment by tuomas2** [comment]
I will check this but I'm wondering if it makes sense to maintain these features in main / regular version? Should we just inform user about calculator build and disable / grey out all related settings?  Created ticket: #3187
