### ISSUE TITLE
💡 Which version of the Bible are you using?

### ISSUE THREAD

**Issue by Pantyhose-X** [AndBible/and-bible#3179]
Biblical manuscript https://en.wikipedia.org/wiki/Biblical_manuscript ?

**Comment by kj7rrv** [comment]
This app doesn't use one particular version of the Bible; it allows you to download and read many different versions. Once you pick a translation, you can look up the name of that translation to see what manuscripts it is based on.

**Comment by timbze** [comment]
AndBible uses the [JSword](https://www.crosswire.org/jsword) library to access Sword modules. A large number of Bible, commentary, and dictionary modules in hundreds of languages are provided by Crosswire.
