### ISSUE TITLE
When calculator mode is enabled, notification name still says "Study Bible"

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#3180]
**Describe the bug**
I saw synchronizing is still happening in background when calculator mode is enabled, which is probably fine, but the title of the system notification says "Study Bible" (or Bible Study?). I think that should be changed.

**Bug was found on AndBible version**
Build 794

**Comment by tuomas2** [comment]
I have a feeling that app name in notification can't be changed.

**Comment by tuomas2** [comment]
as suggested in #3178 I'm not sure if we should continue maintaining & supporting discrete features in main app. Just advertising for separate calc app and those who need these features are much safer anyway. Created ticket: #3187

**Comment by tuomas2** [comment]
I close this as it looks impossible to change app name for notification (I think it's Android security feature).
