### ISSUE TITLE
Change navigation bar color to match text background color

### ISSUE THREAD

**Issue by ericjding** [AndBible/and-bible#319]
I'd like to see the navigation bar match the text background color (i.e., white in day mode, black in night mode) on versions of Android that support it. I see this behavior in other apps, including Kindle for Android, and I think it gives an elegance in appearance that's worth implementing.

I've read documentation online and played around a bit with the source as well, but haven't yet figured out how to make it work in And Bible. Maybe if i post a formal issue it'll not only make for good software development process, but put the idea in someone else's head to implement it before I can get to it. :-)

**Comment by tuomas2** [comment]
BTW it does this in Android 9 without any changes.

**Comment by ericjding** [comment]
I wasn't aware of that. That almost argues for leaving it alone, except that on any phone with manufacturer customizations to Android, esp. from Chinese manufacturers like Huawei, Xiaomi, OnePlus, etc., their default skin often overrides Android's default look. On my Xiaomi tablet running MIUI 10, for example, the default navbar color is white. In apps which customize the navbar to be transparent or colored, MIUI respects those settings, but otherwise, the navigation bar is always white (which looks garish in night mode!).

So I still think it might be a good thing to do if the effort level is minimal.

**Comment by tuomas2** [comment]
This is implemented in... if I remember, already in 340 (production)
