### ISSUE TITLE
Option to change link colour

### ISSUE THREAD

**Issue by josephg5** [AndBible/and-bible#3220]
Colour settings... is probably the best place.

Dark blue text on black background is unreadable.

I can't find option to change link colour. If this setting is already there somewhere, please let me know. Thank you.

**Comment by tuomas2** [comment]
Link color could be changed via custom CSS module https://github.com/AndBible/and-bible/wiki/Custom-CSS-for-modules-for-And-Bible. It feels overkill to add this as an option to colour settings, I haven't heard complaints about this from others.
