### ISSUE TITLE
When speaking reading plan is activated the forward and backward button don't function properly

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#323]
Part of #300 

During the speech of a reading plan the chapter forward and backward don't jump to the appropriate chapter. The verse forward/back work as they should.

**Comment by timbze** [comment]
@bvahedy Do you mean when you click Passage in Reading Plan, then speak? Also, do you mean it should jump to next chapter in reading plan? Or just next chapter in Bible?

**Comment by bvahedy** [comment]
I hit speak first then passage, the next verse button works fine, it goes
to the next verse, but the chapter forward button does the same thing as
the next verse button. It should, in my view, jump to the next chapter in
the reading plan.

I had opened another ticket for scroll while reading plan passage is
invoked. That ticket is still open.

**Comment by tuomas2** [comment]
This is because reading plan text to speech feature uses legacy way of producing text to speech. This will be fixed in #300

**Comment by tuomas2** [comment]
We can close this, as it will be handled by #300
