### ISSUE TITLE
Allows the import of files that do not have a Sword model. .txt/.EPUB/.MOBI/.PDF/.Djvu

### ISSUE THREAD

**Issue by ghost** [AndBible/and-bible#3251]
**Is your feature request related to a problem? Please describe.**
Some Bible verse commentaries are stored in the above format, and they don't have the Sword model.

**Describe the solution you'd like**
Allows the import of files that do not have a Sword model.

**Describe alternatives you've considered**

**Additional context**

**Comment by tuomas2** [comment]
Epub already supported. .mobi could be implemented but not sure about the benefit as epub is supported. PDF and djvu are unfeasible (not formatted text). .txt (as general book) could be implemented but would it be useful?

**Comment by timbze** [comment]
> Epub already supported. .mobi could be implemented but not sure about the benefit as epub is supported. PDF and djvu are unfeasible (not formatted text). .txt (as general book) could be implemented but would it be useful?

Agree with your thoughts. Supporting .mobi could be feature request but I don't see that as high priority
