### ISSUE TITLE
Option to merge database (instead of replacing)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#3259]
With new .abdb format, we can offer option to merge database instead of replacing the current one. 

UI: When restoring Database, we should give option: "Do you want to replace current database, or import entities to current database?". Buttons: "Replace", "Import"

Related: #3141

**Comment by agrogers** [comment]
Do you mean merge notes, labels etc?

**Comment by tuomas2** [comment]
Merge content of another database, so yes, notes, labels, bookmarks etc. Each entity has their UUIDs so there will be no conflicts. If there's item with same UUID, it will be skipped.

**Comment by tuomas2** [comment]
Will ask question 

Restore -> Restore or Import
![image](https://github.com/AndBible/and-bible/assets/5811789/4a258ce2-077f-4ad9-83b1-c8bfe70d2b01)

No changes
![image](https://github.com/AndBible/and-bible/assets/5811789/82b1ba23-0c6c-44e5-99e3-e7c73b665672)

Then ask this question for syncable databases (bookmarks, readingplans, workspaces):
![image](https://github.com/AndBible/and-bible/assets/5811789/c281f242-08e2-4a38-b8d0-1369646f0ec7)

**Comment by agrogers** [comment]
Got it. So merging missing records not existing records.
