### ISSUE TITLE
Tilt to scroll not functioning correctly with two windows open... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#326]
To reproduce:
1) make sure tilt to scroll is checked in settings.
2) open two windows, keep you hand steady.
3) tap on the bottom window and scroll up and down a few verses.
4) now tilt the device forward and nothing seems to happen. But the top window after a while seems to jump to the next verse.

**Comment by tuomas2** [comment]
Hmm I think I saw this issue myself at some point but now I'm unable to reproduce this. Is this still happening?

**Comment by bvahedy** [comment]
Can't reproduce it, you can close it.

**Comment by bvahedy** [comment]
Verified working in build 315.
