### ISSUE TITLE
What if we use a framework to also port the project to IOS without a lot of effort?

### ISSUE THREAD

**Issue by MemoSainz** [AndBible/and-bible#3271]
Hello
I was wondering if it could be complex to include the project into Expo Go. For it is easy to do also the same project in both iOS and android there. And for the need of  Mac OS or software from apple and so, it could be easy to use a virtual machine.

Now... doing the project again in Expo Go (React) could be like a lot of work. But, what if in the future it could be  framework or technology to port everything to iOS with Vue?

**Comment by tuomas2** [comment]
AndBible is not just Vue, it's a lot of Kotlin (native Android) code. 
Vue part can be easily run on any platform, but native Android software needs full rewrite.

**Comment by MemoSainz** [comment]
If it's not fully VUE. How possible could be to migrate from the stack is made this app to Expo or React Native for design the app for both iOS and android? Could be easily and without need to hire someone that knows swift and charges a lot of money.

**Comment by MemoSainz** [comment]
I know React with TS. Is it possible I could help in the future? (Not yet, but willing to)

**Comment by timbze** [comment]
@MemoSainz we don't know of anyway to do this without A LOT of work. https://github.com/AndBible/and-bible/wiki/FAQ#is-there-version-for-ios-apple-iphone--ipad-in-plans
