### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [AndBible/and-bible#3274]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7147511868#L3229

ref: https://github.com/AndBible/and-bible/commit/4c33e878e577b36ae07a91fc6ea6d8c07a747087

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/c37bd252b238b58d39eb6e942214f997d1c2bc3d

**Comment by tuomas2** [comment]
Thank you for letting me know! Fixed it in a0f61dbc422ef5e2a4acf9ff526978b6a5198b30 and moved tag to a working commit.
