### ISSUE TITLE
Can't import reading plan correctly - Invalid SWORD module

### ISSUE THREAD

**Issue by ManOnTheWeb** [AndBible/and-bible#3285]
**FAQ first**

Did you also check FAQ and not find solution there?
https://github.com/AndBible/and-bible/wiki/FAQ

Yes

**Describe your problem**
I cannot import a custom reading plan.

**I'm using AndBible version**
5.0.827

**To Reproduce**
1. Go to the reading plan section
2. Click on the 3 dots and choose to import a reading plan
3. Select the zip file and import

**Expected behavior**
The plan it's read correctly and imported successfully.

**Smartphone (please complete the following information):**
 - Device: POCO F3
 - OS: Android
 - Version 13

**Additional context**
When I import the zip file it tells me that the SWORD module is invalid. I have followed the steps here but it doesn't work: https://github.com/AndBible/and-bible/wiki/Reading-Plans

Here's is my zip file:
[MyBiblePlan.zip](https://github.com/user-attachments/files/16081167/MyBiblePlan.zip)

Thank you.

**Comment by timbze** [comment]
The zip file root folder is MyBiblePlan, but the root folders should be `mods.d` and `modules`. You need to zip 1 level lower, then it works.

**Comment by ManOnTheWeb** [comment]
Thank you for responding. Now it doesn't say anything about the SWORD module, but still it says that an error occurred.
[MyBiblePlan.zip](https://github.com/user-attachments/files/16090426/MyBiblePlan.zip)

**Comment by timbze** [comment]
Oh I forgot, I also changed versification in the conf file to KJVA when I tested. Wasn't sure if that's required but I noticed you have apocryphal books. Try that and let me know if it works

**Comment by ManOnTheWeb** [comment]
I tried but it still doesn't work.
[MyBiblePlan.zip](https://github.com/user-attachments/files/16090574/MyBiblePlan.zip)
