### ISSUE TITLE
.txt .epub .pdf format support

### ISSUE THREAD

**Issue by ghost** [AndBible/and-bible#3289]
**Is your feature request related to a problem? Please describe.**
and-bible is a full-featured reader, and I think people read other books besides bible. 
Not supporting .txt .epub .pdf is the only drawback of and-bible.

**Describe the solution you'd like**
Supports generic .txt .epub .pdf formats.

I tried .epub and it doesn't import, you can find a .epub and try it.

**Additional context**
[hi.txt](https://github.com/user-attachments/files/16301972/hi.txt)

**Comment by ildar** [comment]
When you see a good working app you may have a desire it would do this and
that: everything. But that is plain wrong. This way will result in just one
thing: the quality of the app will drop. You won't be happy with it anyway.

My vote for this request to be declined, sorry

**Comment by ghost** [comment]
This just imports the format support and won't let you do anything else.

**Comment by ildar** [comment]
even if that wouldn't change the UI (though I doubt that!) it requires
adding the backends that are:
1. big in size
2. subject to security issues (search: mupdf CVE)
3. require integrating and maintenance. + many usecases will require many
fixes (see this whole epub story)
So again, I object.

**Comment by tuomas2** [comment]
Epub support is implemented. If your epub file does not work (it may be a bug in app), you can send it to me to inspect: help.andbible@gmail.com. PDF support is not feasible. TXT (or copy&paste text from clipboard) import could be implemented and maybe there would be use case even.
