### ISSUE TITLE
Initial versions of Android 5 are unsupported (second post onward)

### ISSUE THREAD

**Issue by Noitarud** [AndBible/and-bible#3299]
**FAQ first**
Did see.

**Describe your problem**
Message "an error has occurred" when importing documents from zip.

**To Reproduce**
New install, Chose the 82Mb zip after pressing to load documents from files.

**Smartphone (please complete the following information):**
 - Device: ZTE T84
 - OS: Android5.0.2

**Additional context**
Gives Webview problem message (too old, v37, you need v83), but I got this last time (maybe last year) and by some freak accident did get it to go after it refused the zip many times.

Phone can load user's database and say I had these documents; offers to download. Some versions do fail on this step.

Zip file was created with an early ~650 version and is still accepted on new install devices.

Zip file can be extracted with no hastle.

Zip placed in either phone or sd.

Versions 649 to 738 tried. 735 worked once (and not again) but UI missing things due to old Webview (white areas where Bible to be), it did not allow install of older over top. 

Presume mishandling the imported zip or extracted files. It does take some time to read.

**Comment by Noitarud** [comment]
_Resolved. Had to reboot._

Presently 649 and the Bible area is white (It is black in night mode). Which is the next problem. No scriptures.

It would appear Android 5 without updates is unsupported by And Bible, even the versions recommended for previous generations run up until you add the zip, it flashes the scripture before Android says it has stopped, restarting it and there is nothing, stops.

I am not expecting a fix, I'll use another…

**Comment by bvahedy** [comment]
Android 5 OS is no longer supported, please use a device with a higher OS version.

**Comment by tuomas2** [comment]
Even though not really supported, but just saying that Github version still works on Android 5 (so recommending to upgrade: https://github.com/AndBible/and-bible/releases/tag/production-828 .

**Comment by Noitarud** [comment]
I'm not going to beg you to fix it though "not supported" has not **yet** been written on the FAQ. Your FAQ should note that AndBible (all versions, including older) is incompatible with unimproved (factory reset) versions of Android 5 (it recommends 4.0.687). 630 and all prior has the startup crash issue mentioned in last post and 640 onwards displays blanks (see image below), so there is not one that supports original Android 5. Android 5 with WV updates works but still/can shows "old Webview" warning message. Maybe you can patch the version for android v4.4 with the startup crash fix that was introduced before 640 and call android 5 "done" (maybe many fixes are required for reverse compatibility?).

Here is the result with the 828 version you suggested. 684 does not crash this way.
Last crash when I chose "All text options" from window's corner menu.

Here the screenshot shows the no content in window issue (though turns black in night mode).
![fail](https://github.com/user-attachments/assets/bb0c72f4-e828-41b3-b9ec-c533877f8ce9)
[logcat chose all text options.txt.gz](https://github.com/user-attachments/files/16503588/logcat.chose.all.text.options.txt.gz)

**Comment by Noitarud** [comment]
I will only point out that it is not a good idea to have some phones unsupported.

**Comment by Noitarud** [comment]
Appologies for undoing your decision

**Comment by tuomas2** [comment]
Github builds work on Android 5.0. There are some bugs (probably in Android libraries) that appear only on Android 5/5.1, so it is not officially supported. Google Play and other platforms require Android 6.0. I'm not planning to extend Android 5 support as it is obsolete and not supported by Google any more.

**Comment by Noitarud** [comment]
My only rebuttal is that the value of your users needs is greater than Google's.

I don't mind learning to do this but the curve may be too steep.
I only found https://github.com/BuildAPKs/buildAPKs for learning.

**Comment by Noitarud** [comment]
There is some value in this. I don't mind learning to do this but the curve may be too steep. I only found https://github.com/BuildAPKs/buildAPKs for learning.
