### ISSUE TITLE
Bookmarking / highlighting / notes for general books and commentaries

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#33]

**Comment by Emet-like-AndBible** [comment]
tuomas2
For you brave desires concerning the modules with books... Then I will toss up an idea... For the modules with books most cost-effective is possibility to leaf text not scrolling only, but by pages, but such in AB is impossible, and so books in AB reading not comfortably.

**Comment by BryceSteuer** [comment]
This is something that would help me immensely - I can barely read without the urge to record the knowledge somewhere. Bookmarks in the extrabiblical documents especially would be probably my number one desire for features on AB. Although I am glad that there is a search function in documents - that helps.

**Comment by tuomas2** [comment]
if you have plans on implementing this I can help you get started.

**Comment by BryceSteuer** [comment]
I don't know that I'm so confident in my skills to do that now. I would like to be able to, but I don't think I'm at that level yet.

**Comment by tuomas2** [comment]
you can start with something easier then 😊

**Comment by BryceSteuer** [comment]
I would love to. Thanks for the offer.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=1513

**Comment by timbze** [comment]
Duplicated (and completed) by #2683
