### ISSUE TITLE
Copy text settings over workspace fails

### ISSUE THREAD

**Issue by Noitarud** [AndBible/and-bible#3303]
**Describe the bug**
"Copy settings to…" workspace, select all. causes major mess up. Text aligned to left, noise removed (it is in night mode and so it goes blacker) text size larger but not identical across windows. There is no undo so I am not checking variants of steps (back-up recommended).

**Bug was found on AndBible version**
829 and 735 and 684

**To Reproduce**
0. Open AB
1. Change workspace to one with four or so windows
2. Select a Bible window and press on corner-menu square
3. Choose text options…
4. Copy settings to, workspace, select all. OK

Android10, lenovo

**Comment by tuomas2** [comment]
If window does not have noise set, and workspace has, "copy settings to" function removes noise, if user chooses also "color settings" to be copied. It works as it is supposed to. 

It could be that it is confusing feature though.

**Comment by Noitarud** [comment]
Huh?
Window DID have noise set (set as black but was greyer with noise, it removed noise hence "goes blacker") and caption of option says to "copy to" all, which it was not doing…

Did you try to reproduce it? Maybe step 0 was open AB…

**Comment by tuomas2** [comment]
I think in your case noise of the window was set through workspace setting, not through individual window setting. Thus when another window's settings were copied to workspace, that removed noise from all windows those windows that were using workspace's setting (and not having noise set spefically).
