### ISSUE TITLE
4626  missing

### ISSUE THREAD

**Issue by shineandre** [AndBible/and-bible#3306]
Hi there are two things.

First in the Andbible the Crosswire  strongshebrew is absent.

And the strong Greek 4624-word offense is missing. 

**Bug was found on AndBible version**
The latest is because I uninstalled and reinstalled it with no change. All the other numbers I tried worked

andrecronje13@gmail.com
I used a One plus 8T android 13 or 14.

**Comment by tuomas2** [comment]
Here's how to handle module issues: https://github.com/AndBible/and-bible/wiki/FAQ#i-found-text-issue-in-one-of-the-bible--commentary-etc-modules-in-andbible
