### ISSUE TITLE
File does not contain a valid SWORD module

### ISSUE THREAD

**Issue by Noitarud** [AndBible/and-bible#3309]
Why? I am not bothered to update all my devices to latest version but want to distribute new acquisitions to them… New 828+ backup restored to older ~730s version.

Obviously message is incorrect. Today's app needs to include method to actually look for what it can pull if given a backup from two-ten years in future. I do not know how to direct loader to specific content in zip.

i can restore 700s zip to very old editions…
i have noted it may not work first try, did try a fair number of times…

**Comment by tuomas2** [comment]
The database backup can't be loaded to older version as the database schema has been changed. Message is incorrect because currently database is divided into several sections and combined as a zip file, earlier it was one monolithic sqlite file. 

There's not much we can do about this.
