### ISSUE TITLE
Dutch Statenvertaling audio

### ISSUE THREAD

**Issue by DreadHeadstone** [AndBible/and-bible#3331]
We've got audio for the Dutch Statenvertaling available for your app.
Check www.statenvertalingluisterbijbel.com
Any questions, send an email.
Kind regards,

**Comment by timbze** [comment]
Currently AndBible only supports text-to-speech (TTS). If issue #1909 gets implemented then this might be helpful. Currently there is no way for us to use this audio. Thank you for the information though, if in the future #1909 gets implemented we can look through the `Audio (non-TTS)` label I just created and see about integrating this as well as other audios.
