### ISSUE TITLE
Back feature no longer works after Android 15

### ISSUE THREAD

**Issue by Samandamand** [AndBible/and-bible#3332]
**Describe the bug**
When using the left side back gesture the and Bible app no longer visits the previous passage but momentarily pops out tge left window panel.

**Bug was found on AndBible version**
version 5.0.832

**To Reproduce**
1. Go to a few different passages
2. Use the back gesture
3. Watch the left window pane pop out for a moment.

**Expected behavior**
Return to the previous passage.

**Smartphone (please complete the following information):**
 - Device: Pixel 8 pro
 - OS: Graphene OS 
 - Version Android 15

**Comment by tuomas2** [comment]
Did it start working or why did you close the issue?

**Comment by Samandamand** [comment]
It works without issue for me now on the same version. Perhaps Graphene OS or an upstream Android issue was causing it that has been fixed.
