### ISSUE TITLE
Mt 11:10 in your AndBible app's NASB version needs cleaning up work

### ISSUE THREAD

**Issue by nestorras** [AndBible/and-bible#3334]
**Describe the bug**
Mt 11:10 in your AndBible app's NASB version has extranneous words.

**Bug was found on AndBible version**
Build XXX.X or version X.X.

**To Reproduce**
1. Go to Gameloop on your windows 10 pc
2. Click on ME and select AndBible, then go to Mt 11 on your NASB version
3. Scroll down to verse 10

**Expected behavior**
please see attached screenshot

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: AMD ryzen 7 windows 10 pc running Gameloop to use android apps
 - OS: Windows 
 - Version 10

**Additional context**
![Screenshot (6)](https://github.com/user-attachments/assets/fa2b1578-14f0-482a-a064-21689b4847bb)
![Mt 11 10 error of your NASB version as used in your AndBible app opened on  whale running on windows 10 pc](https://github.com/user-attachments/assets/85ad4d57-b774-4756-a198-881ed1e1bd02)

**Comment by timbze** [comment]
This is a module issue and needs to be raised with module maintainer. I.e. Crosswire in this case. See https://github.com/AndBible/and-bible/wiki/FAQ#i-found-text-issue-in-one-of-the-bible--commentary-etc-modules-in-andbible
