### ISSUE TITLE
Support for apple store

### ISSUE THREAD

**Issue by mynameisORIG** [AndBible/and-bible#3338]
**Is your feature request related to a problem? Please describe.**
This feature is not related to a problem. 

**Describe the solution you'd like**
I'm an iphone user and would love to see this on the apple store. I feel like it would reach more people since there are a ton of people who have iphones. 

**Describe alternatives you've considered**
Just using a notepad and taking notes.

**Additional context**
If there is anything I can do to help, I do have some python dev experience.

**Comment by timbze** [comment]
Please see this FAQ entry: https://github.com/AndBible/and-bible/wiki/FAQ#is-there-version-for-ios-apple-iphone--ipad-in-plans
