### ISSUE TITLE
Blank screen if windows boundaries are moved beyond the screen edge... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#337]
Too recreate:
1) Open two windows.
2) close the top widow, which is the main window.
3) open a second window
4) move the split line of the lower window all the way to the bottom.
5) close the top window
6) you are presented with a blank window which the only way to recover from is to reinstall the app.

**Comment by bvahedy** [comment]
I think what is happening is that when the menu bar is hidden as is in full screen mode and if the split window line it's moved in the area where the menu bar normally is, then when menu bar appears over the split line, the split line is no longer is accessable.

**Comment by marnix** [comment]
Got hit by this just now.

Is reinstalling the app really the only way to fix this?  Perhaps there is some config file I can change/remove to trigger some kind of reset?

But if it is, does that mean I have to re-download all translations etc, or is there a way to avoid that?

Thanks!

**Comment by bvahedy** [comment]
Yes, uninstall and reinstall is the only way to get out of it. But the good
news is that you can save all your modules before uninstalling. Do the
following:

1) backup your bookmarks from within andbible settings.
2) close Andbible.
3) use file manager and go to your Local SD storage
>Android>data>net.bible.android.activity
And copy this directory to your download folder on your local or external
storage.
4) uninstall andbible
5) reinstall Andbible but do not open the app.
6) copy back the net.bible.android.activity from your download folder back
to >Android>data folder.
7) open andbible.
8) from menu restore bookmarks and notes from backup.
All your modules should be there.

**Comment by tuomas2** [comment]
You can actually also 'reset' application by going to "App info" -> "Storage" -> "Clear Data" (you can find "App info by long-clicking And Bible on your home screen / app browser). Also before this operation you need to do backup to retain bookmarks etc., and after you need to restore again from backup.

**Comment by bvahedy** [comment]
Good tip, I guess this will save you from uninstalling and reinstalling the
app, but you still need to save the Bible modules directory  in order to
save all your dictionaries and modules.

**Comment by kellnerp** [comment]
I have been hit with this several times.
No way to get back lost windows.

**Comment by timbze** [comment]
#355 gives an easy work-around by opening a new tab (this feature is not in beta yet though). Just FYI. This issue still needs to be fixed anyway.

**Comment by tuomas2** [comment]
Will be fixed in build 308

**Comment by bvahedy** [comment]
Verified fix in 308beta. The only issue is that when moving the split window line below the menu bar or the navigation button menu bar you would need to double tap and enter into full screen mode to be able to see the split line and recover the window. The fix does take care of the white screen issue which is great.

**Comment by marnix** [comment]
Verified as well, in the May 24, 2019 update I just installed (am beta tester) which presumably is 308beta.  Thanks!
