### ISSUE TITLE
Loading OT speak bookmark when NT-only document open, causes app freeze

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#338]
This issue happens if you have a speak bookmark that is from an OT book, e.g. Psalms 12:1, from a Bible that is not loaded.
I had cleared "my data" from systems settings to test some other issue. And restored my bookmarks from backup.

1) upon redstart of andbible I loaded ISV Bible, which only has NT books, from the repository.
2) I restored my bookmarks from backup
3) from speak bookmarks, I selected Psalms 12:1 ESV (which I have not loaded yet)
4) upon tapping on speak button I got a blank screen and the app freezes. The only way to recover is to force stop the app from system settings.

Expected behavior:
Present a text that says, Bible module xxx not found. Where xxx is the name of the module that is in the bookmark.

**Comment by bvahedy** [comment]
If you can't duplicate it, it may be that the bookmark is a repeat passage. Try that.

**Comment by tuomas2** [comment]
Is this issue still valid?

**Comment by bvahedy** [comment]
It seems to have been fixed.

**Comment by bvahedy** [comment]
I did a clean install of the 341 beta and this issue is still happening. Upon restoring the bookmarks the Bible ref. on the menu bar changes to Genesis 1:1 with a blank white screen. the only Bible that was installed was isv. Also if you try to read a Bookmark from OT it starts reading Matt. 1:1

I'm reopening  this issue.

**Comment by tuomas2** [comment]
Tried what you suggested, but it did not freeze. Closing, but please re-open if still occurs.

Tested with build 367.
