### ISSUE TITLE
White blank windows after restart with multiwindow

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#340]
1. Open one bible, one commentary in two different windows.
2. Close app activity properly (swipe it away in apps listing)
3. Open app again. 
Actual: Bible does have text, but commentary does not.
Expected: all windows should have their content as before closing

**Comment by tuomas2** [comment]
Will be fixed in 306

**Comment by bvahedy** [comment]
For me it didn't happen with TSK commentary, but it did happen with Josephus, which is a book.

**Comment by tuomas2** [comment]
Commentary should not have synchronize setting enabled,  Sorry I forgot to mention that

**Comment by bvahedy** [comment]
Ok, it only happens then when there is no synchronization. I had to turn off synch for TSK window to make it go white upon restart.

**Comment by bvahedy** [comment]
This is now working in build 306.
