### ISSUE TITLE
White blank screen after unminimizing nonsync commentary / gen book

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#342]
1. Open one bible, one commentary in two different windows. 
2. Uncheck "synchronize" for commentary
3. Minimize commentary
4. Close app activity properly (swipe it away in apps listing)
5. Open app again. 
6. Unminimize minimized commentary window
Actual: Bible does have text, but commentary does not.
Expected: all windows should have their content as before closing

**Comment by tuomas2** [comment]
Will be fixed in build 308

**Comment by bvahedy** [comment]
Verified fix in 308beta
