### ISSUE TITLE
Minimized windows positions are off... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#344]
**Describe the bug**
If the navigation buttons are turn off the position of the icons for minimized windows remain as if the devices navigation buttons were still there, see attached screenshot. 

**To Reproduce**
Switch the navigation buttons from the device settings>display>navigation bar to slide up rather than static buttons.

**Expected behavior**
When device's navigation buttons is in swipe up mode bring down the min. Widows icons to the bottom of the screen. 

**Smartphone (please complete the following information):**
 - Samsung Galaxy Note 8
 - Android
 - Version 9.0

![SmartSelect_20190416-202208_And Bible](https://user-images.githubusercontent.com/46405809/56258986-5fc2d900-6086-11e9-9de4-08a98189cb76.jpg)

**Comment by tuomas2** [comment]
This issue must take place only on devices that have hardware buttons (and system soft button bar is not shown).

**Comment by timbze** [comment]
This seems to be a tricky issue because of the soft navigation bar that many devices now have (my LG on Android 8.0 has same issue when hiding nav bar), and also the different ways that custom roms handle the nav bar. Putting this info here for future reference. https://stackoverflow.com/a/47382758/877453

**Comment by tuomas2** [comment]
So this does not apply only Android Pie, but older too.

**Comment by tuomas2** [comment]
https://stackoverflow.com/questions/28983621/detect-soft-navigation-bar-availability-in-android-device-progmatically/28983720

Let's try the suggested solution in this answer. It will fail for emulator but should work on real devices.

**Comment by tuomas2** [comment]
Will be fixed in build 308

**Comment by timbze** [comment]
This is not fixing the issue for me. See this video of what it does on my phone. https://photos.app.goo.gl/VfJS4pjoczyrkqMz5

**Comment by tuomas2** [comment]
Hmm, not sure if there better fixes available :-/ What was your device exactly @timbze

**Comment by timbze** [comment]
I have LG G6. I will read up on it some more too and see if I find something.
1 issue with this code now is that it only gets checked onCreate, but the nav bar can be hidden or shown while using AB

**Comment by tuomas2** [comment]
One possible solution that would fix this for many users would be to check if phone is from Samsung, and based on that assume that it has hardware buttons. Also for other manufacturers, it might be able to be done.

**Comment by timbze** [comment]
Maybe I am mistaken, but I think this issue had nothing to do with hardware buttons. The galaxy note 8 does not have hardware buttons. I think the previous code before this PR probably works for hardware buttons.

I think this only has to do with having a setting to hide the nav bar, and that way it can be shown by swiping up.

**Comment by bvahedy** [comment]
Yes, Tim is correct, there is no hardware buttons on the Note 8, the issue
is when you hide the navigation bar buttons.
Is there a way to check the state of the navigation bar buttons?

**Comment by tuomas2** [comment]
> Yes, Tim is correct, there is no hardware buttons on the Note 8, the issue is when you hide the navigation bar buttons. Is there a way to check the state of the navigation bar buttons?

I see. That's new to me. Unfortunately (and suprisingly) it seems that there is not.

**Comment by bvahedy** [comment]
Then let's just close this ticket for now, since no one else has
complained.

**Comment by tuomas2** [comment]
I would like this to be open as long as problem persists (even "forever" if we don't find a solution).

**Comment by bvahedy** [comment]
Ok, whatever you think is best.

**Comment by bvahedy** [comment]
This is still happening in 308beta, so will reopen this ticket.

**Comment by tuomas2** [comment]
I reverted the fix as it was not a good fix. It seems that the commit message auto-closed this ticket by accident.

**Comment by tuomas2** [comment]
This is fixed by now. (build 367 and some earlier too)

**Comment by bvahedy** [comment]
Yes, it seems to be fixed, verified in build 367. Thanks!
