### ISSUE TITLE
If synchronize is disabled, AB should not jump to bible passage when starting playback for speak bookmark

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#345]
**Describe the bug**

**To Reproduce**

1. Disable "synchronize text with speech" from advanced speak settings. Enable speak bookmarking. 
2. Create one or two speak bookmarks.
3. From speak bookmarks popup menu  (in speak transport) OR from speak bookmark desktop widget, start speaking one of the bookmarks.
4. As AB starts to speak, text also jumps to the bookmark location.

**Expected behavior**

If synchronize is disabled, text should not jump to the speaking location.

**Comment by tuomas2** [comment]
Will be fixed in build 306

**Comment by bvahedy** [comment]
I'm unable to reproduce this bug in build 305.

**Comment by tuomas2** [comment]
Tried again without fix and I could reproduce. Hmm. I think you should be able to reproduce.

**Comment by bvahedy** [comment]
Ok, I misunderstood, I had two windows open and thought that you were
talking about the two windows syncing.
I can see what you are talking about now, but am wondering why you would
not want the bookmark to jump to the passage. Isn't that the whole idea of
a bookmark?
I thought the advance setting was for following the reading and not any
thing to do with bookmarks.
But if you just want it to read the bookmarked passage just to hear it
without losing the passage you are at then it would make sense.

**Comment by bvahedy** [comment]
This is working now in build 306.
