### ISSUE TITLE
Do not allow page change while scrolling

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#351]
**To Reproduce**
1. Scroll down slowly (max 0.5-1cm) by your finger
2. While holding your finger down, do a quick move to left/right
3. Page changes to next / previous

**Expected behavior**
While scrolling, page should not change.

**Comment by tuomas2** [comment]
Fixed in a6ed0742c115a9833a2cde11a172d6e156e1e7f1, will be fixed in build 306

**Comment by bvahedy** [comment]
I'm unable to duplicate this in build 305.

**Comment by tuomas2** [comment]
Hmm. I can't either. Good that you tested. 
I was sure it was this way that I have been doing pagechanges unintentionally... I need to re-check my fix too.

**Comment by tuomas2** [comment]
Okay, improved bug description. Can you now verify this? (closing again as I think fix is good)

**Comment by tuomas2** [comment]
Also, the fix now ensures that if user has been holding finger for more than 1 second, it won't change page.
