### ISSUE TITLE
Improve maximize mode behavior

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#353]
In maximized mode:
- show all other windows as "minimized" windows. 
- Clicking "minimized" windows, should switch that particular window to maximized mode

That would allow easy flipping between windows if you want to work in maximized mode.

**Comment by tuomas2** [comment]
Will be implemented in build 308

**Comment by tuomas2** [comment]
@bvahedy  one more ticket to test :-)

**Comment by bvahedy** [comment]
Verified improvement working beautifully in 308beta build. Nice job.
