### ISSUE TITLE
Speak says "Sad Face"

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#356]
When using the speak feature, AB reads "sad face", probably where there should be a space in between verses.

In the below verses between 15 and 16, AB speak reads: "the Holy Ghost sad face for as yet"

(Acts 8:15-16)
 Who, when they were come down, prayed for them, that they might receive **the Holy Ghost:  16.(For as yet** he was fallen upon none of them: only they were baptized in the name of the Lord Jesus.) 

This is the text TTS outputs
![image](https://user-images.githubusercontent.com/35117769/57111404-326a6200-6cf9-11e9-90ba-f287ad4625b6.png)

**Smartphone**
 - Device: LG G6
 - Version Android 8.0

**Comment by tuomas2** [comment]
Solution could be to remove parenthesis from spoken text. They don't affect the pronounciation (though TTS engines might vary).

**Comment by tuomas2** [comment]
Which TTS engine are you using @timbze ? Google or something else?

**Comment by timbze** [comment]
Yes I use Google TTS

Probably removing the parenthesis would work, and probably it would also work to just put a space in between. Instead of having "Ghost:( For as yet", make it to be "Ghost: ( For as yet"

**Comment by tuomas2** [comment]
Logic should be as simple as possible though so that it does not cause undesired side effects.

**Comment by agrogers** [comment]
Is this fixed now? If not...
I suggest we delay this one to after v3.4 release

**Comment by tuomas2** [comment]
Won't fix
