### ISSUE TITLE
Bible reference overlay is mislocated in landscape mode if there are multiple windows

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#357]
1. Go to full screen
2. Add 2 or more windows
3. Scroll a bit bible window

Actual:
Bible reference overlay that appears when scrolling is located on the last window
Expected:
Bible reference overlay should appear centered on the screen at the lower part of the screen, like in portrait mode.

**Comment by tuomas2** [comment]
Related #310

**Comment by tuomas2** [comment]
Fixed in next beta >340

**Comment by bvahedy** [comment]
Also if you reverse the split mode and enter full screen the reference overlay disappears.
