### ISSUE TITLE
Crash on first start

### ISSUE THREAD

**Issue by dolour** [AndBible/and-bible#360]
**Describe the bug**
After installing, downloading a few files, and adjusting a bunch of settings, the App
crashes on options menu exit, taking the Launcher with it.
Same thing happens with OpenLauncher and NovaLauncher, so its most likely not
the Launchers fault.
No idea where to find any logs/dumps on Android, but if you tell me where to look
id gladly dig them up for you.

**To Reproduce**
TLDR:
download files, go to settings, toggle strongs numbers, reformat to 1 verse per line,
exit settings (i guess :p)

Havent tried any other sequence of actions, but the way described above persists
and is reproducible after every wipe/flash. Happens on stock and custom roms.
My first guess was nightmode interfering with the theming engine, but nope, its
crashing regardless of theming.
The only things persistent i could think of are reformatting to 1 verse per line and
turning off strongs numbers, because the screens simply too cluttered with them
being displayed.

**Expected behavior**
Well, not to crash. :p

**Smartphone (please complete the following information):**
 - Device: ZUK Z2 Pro
 - OS: Android / AOSP Extended
 - Version 7.0 / 8.0 / 9.0

**Additional context**
Just a minor thing, since it doesent happen after first launch.

Btw, F-Droid's got AndBible in their repo, which is missing on the homepage.

**Comment by tuomas2** [comment]
> Btw, F-Droid's got AndBible in their repo, which is missing on the homepage.

We can add F-droid if they provide more recent version (see #313).  Are you using latest version from Google Play?

**Comment by timbze** [comment]
#364 references bug (has been fixed) in which app crashes on return from "Download Documents" screen.
I'm thinking this bug may no longer be an issue. I cannot reproduce it. The settings the OP references here have been moved to 3-dot menu on top right.

**Comment by tuomas2** [comment]
@dolour if this bug still takes place with 3.2 (release ongoing), please re-open.
