### ISSUE TITLE
After window resize, window always scrolls to exact verse position

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#363]
**To Reproduce**
1. Setup screen with 2 or more Bible windows, with windows are split with horizont splitting (i.e. vertical column of windows)
2. Move one of the bible windows so that part of the current verse is not visible 
3. Resize window by moving window splitter
4. Bible window(s) scroll to the exact bible verse positions

**Expected behavior**
Scrolling should be done only if windows are split with vertical splitting, because verse positions need to be re-calculated. When with horizontal splitting this is not needed and re-scrolling to verse is not desired effect.

**Comment by tuomas2** [comment]
Will be fixed in build 308

**Comment by bvahedy** [comment]
Are you checking the reverse split mode box?
Or switching to landscape mode to get the vertical split lines. Either way resizing any window to shrink the space  still causes scrolling  to sync with the verse in other windows.

**Comment by tuomas2** [comment]
@timbze ^

**Comment by timbze** [comment]
Maybe related to #381 and #382

**Comment by tuomas2** [comment]
Will be fixed in build 312

**Comment by bvahedy** [comment]
Tuomas, unless I'm missing something this is still doing what it did before
meaning when I flip the phone to the horizontal state when the seperator
lines are vertical the verses are repositioned to the top. I have tried
several scenarios moving the seperator lines to squish the text and it
still repositioned to top verse.
I don't really see this being a big deal at this time, but it's your call
if you want to pursue it further.

**Comment by tuomas2** [comment]
@timbze was fixing this so perhaps he could comment? / reopen if needed?

**Comment by bvahedy** [comment]
Tim, can you confirm this is still happening in build 312  the way you reported it, I could be misunderstanding what it should be doing.
You can reopen this ticket if you feel it's misbehaving still.

**Comment by timbze** [comment]
If I am not mistaken, this issue is only for when the separator bars are horizontal, from left to right. That is, when you can pull the bars up or down. In that case the text should not jump.

When the bars are vertical (move left and right), the text can move so much that it becomes necessary to have it scroll after a move, though it probably wouldn't always be necessary.

Ben, if you could just reconfirm that you are testing along these lines?

**Comment by bvahedy** [comment]
Tim,
I was testing it with vertical windows which makes the windows seperator
vertical.
After testing it the way you described, the only time verse reposition
happens is when you minimize a window or maximize one.
Otherwise it seems to be working.
Thanks for your clarification.

Ben
