### ISSUE TITLE
App crash after download documents screen (Alpha)

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#364]
App crashes after returning to Bible screen from download documents. Happens only after 305 (bug was introduced here 24ed4c5496d1e0a285a2016b4262c90640eb0a1f)

From main Bible screen, open download documents
Press "up" arrow on top left to go back.
App crashes

**Comment by tuomas2** [comment]
Probably this is first introduced in build 307.

**Comment by tuomas2** [comment]
Will be fixed in build 308. Thanks @timbze !

**Comment by bvahedy** [comment]
Verified the fix.
