### ISSUE TITLE
Google app backup automatic integration

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#365]
Something to look into. And Bible is coded to allow Google to make automatic backups of the entire app. But Google only does backups when the app is up to 25mb total.

It is possible to select which folders are included in the backup. It might be a good idea to have folders with preferences and DB backed up, but not modules. That way the size limit would probably never be exceeded.

**Comment by tuomas2** [comment]
Instructions for testing in Pull Request: #385

**Comment by tuomas2** [comment]
Will be included in build 312
