### ISSUE TITLE
JSword DarbyFr versification has wrong name

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#367]
DomCox has pointed out on sword-devel that Jsword has unfortunately
named DarbyFr wrongly - DarbyFR. As a result And Bible and other Jsword
frontends will not see new texts uploaded with DarbyFr versification

**Comment by tuomas2** [comment]
Will be fixed in build 308

**Comment by tuomas2** [comment]
And this @bvahedy

**Comment by bvahedy** [comment]
Tuomas,
I'm not sure what this is and how to test it, can you describe further the
steps in verifying this fix. Thx!

Ben

**Comment by tuomas2** [comment]
Try install FreJND module. If it is found in the listing and can be used properly then it should be OK.

I already tested this in emulator and it was OK. More discussion about the topic was in sword-devel email list: http://www.crosswire.org/pipermail/sword-devel/2019-May/thread.html (see topic "[sword-devel] Module FreCJE ")

**Comment by bvahedy** [comment]
Ok, I was able to see and install it. It looks ok, but I can't read it
since it's in French.
