### ISSUE TITLE
Follow-up ideas for tabs

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#368]
From @timbze 
> A suggestion I would have is to possibly add Close X button at tabs list to easily close a tab. But more important for me would be to add a + somewhere to add another tab easily from there, instead of having to go to the menu to open new tab.

**Comment by tuomas2** [comment]
In my work flow I rarely create new tabs. I just have few (named) setups all the time.

**Comment by tuomas2** [comment]
from Darryl

> Following up on tabs, please also consider mentioning which tab is active in various contexts .. 
> • eg_1: When viewing the reading history, it would be helpful if the title were something like "History (Tab 1)" , instead of just "History". 
> • eg_2: When displaying the book selector, change "Choose Book" to "Choose Book (Tab 1)".
> • eg_3: When viewing the tab list (love the drag-down on reference title!), perhaps you could highlight the current tab with an asterisk (*,★, 🌟) or checkmark (✔️) or something.
> • eg_4: When the menu for tabs is displayed (rhs ≣ ⇨ tabs), a list of options (incl. Switch to tab, new tab, etc) currently has a heading of "Tabs" in reduced grey font .. it would help if it instead said something like "Tabs (Tab 1)".

**Comment by tuomas2** [comment]
Will be implemented in build 314

**Comment by bvahedy** [comment]
I like the changes and the improvements in build 314, you can now close the current tab from the list of tabs menu, also the implementation of the star showing current tab is very useful. I also tested the functions from the top right menu. Nice job!
