### ISSUE TITLE
Automatic bookmark backupping to Google Drive

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#370]
Periodic auto-backup of bookmarks db to google drive etc. 
Related: https://github.com/AndBible/and-bible/issues/148

**Comment by tuomas2** [comment]
Also related: #365

**Comment by agrogers** [comment]
This would be handy. I have lost stuff before because I forget to backup. Once a day when closing the app would be good for me.

**Comment by timbze** [comment]
Is this obsolete now that #2584 was implemented? I guess there could be a separate backup option yet...

**Comment by tuomas2** [comment]
It's not really "backup", but it serves as a backup if treated properly. But user can't access files by himself. But I think this will not be implemented.
