### ISSUE TITLE
Maximize mode: Window synchronization does not work

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#371]
1. Setup 2 or more windows, let them have "Synchronize" setting on
2. Set one of the windows in "Maximize" mode
3. Advance in one of the windows one or two verses
4. Switch to another maximized window 
Actual: Window is still on the previous verse
Expected: Window is moved to the same verse as the first one.

**Comment by tuomas2** [comment]
Can be reproduced with build 309. 
Will be fixed in build 310.

**Comment by tuomas2** [comment]
seems broken.

**Comment by tuomas2** [comment]
Will be fixed in build 311.

**Comment by bvahedy** [comment]
Verified the first part of this ticket is fixed.

**Comment by bvahedy** [comment]
Seems to be fixed in build 311.

**Comment by bvahedy** [comment]
Verified fixed in 312.
