### ISSUE TITLE
Maximized mode: initial top margin is not correct in commentary

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#372]
1. Open 2 windows, one of them is commentary
2. Maximize commentary window
Actual: Start of the commentary is hidden behind navigation bar
Expected: Start of the commentary is shown below the navigation bar

**Comment by tuomas2** [comment]
Can be reproduced with build 309. Will be fixed in build 310

**Comment by bvahedy** [comment]
This is still happening in build 310, reopening this ticket.

**Comment by timbze** [comment]
I think https://github.com/AndBible/and-bible/commit/da07f8c87f5cb96fca53de2ea3b3ed65e2eda9dc needs to be reverted.

I haven't figured out the best way to fix this issue yet, but I see now why it is happening. jumpToOffset() function in BibleView.kt is run when a Bible window is maximized, but not when a commentary window is maximized.

When maximizing a Bible window, you can see it's positioned exactly like the commentary, but the jumpToOffset makes it scroll to the correct position, but the commentary window is not being scrolled.

**Comment by tuomas2** [comment]
Will be fixed in build 315
