### ISSUE TITLE
Maximize mode: Minimized windows are not minimized after un-maximize

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#373]
1. Create 3 windows
2. Minimize 1 of the windows
3. Maximize one of the windows
4. Unmaximize
Actual: All of the windows are visible in split screen
Expected: Minimized window is still minimized, and 2 windows are shown

**Comment by tuomas2** [comment]
Reproducible with build 309. Will be fixed in build 310

**Comment by bvahedy** [comment]
Verified fixed in build 310.
