### ISSUE TITLE
Excuse me, how to disable the full screen? 

### ISSUE THREAD

**Issue by m0nz0n** [AndBible/and-bible#377]
Excuse me, how to disable the full screen? before there was the option to put false or true, now I do not see where in the code I could disable that option by default, I will be very grateful for your help.

**Comment by timbze** [comment]
On the top right is the 3-dot menu icon. Click it and uncheck the option "Fullscreen by scrolling"

**Comment by tuomas2** [comment]
I left wondering if @m0nz0n really wanted to do some coding related to this (referring to _where in the code_)?)

For support questions, please send email to and-bible-support@googlegroups.com (or discuss in And Bible discussion group https://groups.google.com/forum/#!forum/and-bible).

**Comment by m0nz0n** [comment]
Thank you very much! if it's related to the code, I'm learning, I want to disable the full screen option that is by default inside the code.

**Comment by tuomas2** [comment]
in MainBibleActivity there's property called fullscreen by which you can switch to fullscreen mode. Also you could check MainBibleActivity.toggleFullScreen and how it operates.

**Comment by m0nz0n** [comment]
Thank youuu! are the best!...
