### ISSUE TITLE
Maximized mode: if changing document, button letter should be updated

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#379]
1. Go to maximized mode
2. Change document
Actual: Letter in minimized button bar does is not updated
Expected: Letter in minimized button bar should be updated

Can be reproduced since build 309.

**Comment by tuomas2** [comment]
Will be fixed in build 312

**Comment by bvahedy** [comment]
Which letter?
 currently on my device it darkens the letter of the Bible I'm on at the
bottom of the screen, see attached picture:

**Comment by tuomas2** [comment]
Github does not support attaching pictures via email, so picture was not included in your comment.

If you change document (bible translation) in maximized mode, letter of the active window is not changed correctly.

**Comment by bvahedy** [comment]
The letter is correctly highlighted. Here is the image:
![SmartSelect_20190606-191039_And Bible](https://user-images.githubusercontent.com/46405809/59115437-2710e480-88fe-11e9-94e8-b93183804bce.jpg)

**Comment by bvahedy** [comment]
Ok, I see the problem, I was taping on the bottom icons as opposed to using the top menu bar to press and hold to bring up Bible list.

**Comment by bvahedy** [comment]
Verified fixed in 312.
