### ISSUE TITLE
WHNU: Doubble words in brackets

### ISSUE THREAD

**Issue by 1jr** [AndBible/and-bible#380]
**Describe the bug**
The WHNU version duplicates words whenever there are brackets. I doubt this is the desired behaviour:

Luke 12:21
[ουτως ουτως ο θησαυριζων αυτω εαυτω και μη εις θεον πλουτων] πλουτων 

Both ουτως and πλουτων are duplicated. This happens in verse 19 as well and (as far as I can tell) wherever there are brackets.

**To Reproduce**
1. Go to Greek language in the "Download books" section and download Westcott and Hort. (WHNU)
2. Go to Luke 12:21 or any verse with brackets.
3. See error.

**Expected behavior**
I expected no duplicate words in the verse.

Luke 12:21 should look like this:
[ουτως ο θησαυριζων αυτω εαυτω και μη εις θεον πλουτων]

**Smartphone:**
 - Device: Samsung Galaxy A5 (2017)
 - OS: Android
 - Version: 8.0.0

**Comment by tuomas2** [comment]
Is this a module issue? Or can you verify that this issue does not exist with other Sword / Jsword based apps?

If this is module issue, please see https://github.com/AndBible/and-bible/wiki/FAQ#i-found-text-issue-in-one-of-the-bible--commentary-etc-modules-in-and-bible and then this issue can be closed.

**Comment by 1jr** [comment]
You were right! The same thing does occur in other sword apps as well and is not an issue with AndBible!
