### ISSUE TITLE
Synchronization problem with minimized windows

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#382]
1) Open 3 Bible windows of different translation, all synchronized.
2) minimize third window.
3) on the second window go up one verse.
4) tap and hold on the win. menu of the second window to minimize it.

Actual: the first window jumps to the previous verse. 
Expected: the first window should remain on the verse in which it last was scrolled to

This is happening in build 310.

**Comment by tuomas2** [comment]
Hmm. this too seems to be not reproducing always. as #381. Bug keeps hiding me now.

**Comment by tuomas2** [comment]
Possible fix: 97fc1d3

**Comment by tuomas2** [comment]
Could you @bvahedy check if this reproduces still in build 311 (just released)?

**Comment by bvahedy** [comment]
Seems to be fixed in build 311. Closing ticket for now.
