### ISSUE TITLE
First Bible window is too small after adding new window

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#388]
**To Reproduce**
1. Open 2 windows
2. Pull the separator bar as far down as possible
3. Close window 1 (window 2 is now the only window)
4. Add a new window

**Problem** 
The separator bar is now very high, usually behind the menu bar

**Expected behavior**
The separator bar should be centered between the 2 windows

**Comment by tuomas2** [comment]
Will be fixed in build 312

**Comment by bvahedy** [comment]
Build 312 the seperator bar is still at the top under the to menu bar, I'm reopening this ticket.

**Comment by timbze** [comment]
Can you reproduce the issue with the steps I specified in the first post? I know the bar can still go behind the menu bar but that's a more complex issue/annoyance

**Comment by bvahedy** [comment]
Yes Tim, its doing exactly as the steps you you have in the ticket. I did a
complete reinstall of build 312 just to make sure I have a fresh install. I
don't see any fix for this, that's why I reopened the ticket.

**Comment by timbze** [comment]
Hmm, this is what I have and works fine. https://photos.app.goo.gl/Jy9UAhs3s5867gpf8

But I will try it on your exact build (312 without my mods) when I get a chance and try it there.

**Comment by timbze** [comment]
Ben, do you have more minimized windows when you test this? It is still happening when there are more minimized windows, and that should be fixed yet.

**Comment by bvahedy** [comment]
Yes, I had more minimized windows. So part of this ticket works. Do you
want to close this ticket and create a new one to address the multiple
minimized windows or add the second portion of this bug and keep this
ticket open?
I'm fine with it either way.

**Comment by timbze** [comment]
Just leave it open and I will close with a fix for it. Thanks for your
help.

**Comment by bvahedy** [comment]
Ok, I'll leave it open but assign me back when you are done with the mod so
I can test it.

**Comment by tuomas2** [comment]
Fix will be released in build 313

**Comment by bvahedy** [comment]
Confirms working in 313 build.
