### ISSUE TITLE
Bring back ESV to And Bible

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#390]
The publishers of the ESV have unfortunately decided it is not longer in their interest to publish towards SWORD platform (by Crosswire Bible Society) which And Bible is using. 

We need to investigate options together with Crossway to bring ESV back to And Bible.

**Comment by tuomas2** [comment]
Added mention about this in our FAQ https://github.com/AndBible/and-bible/wiki/FAQ#i-cant-find-esv-any-more-in-downloads-whats-wrong

**Comment by MasterOfTheTiger** [comment]
Where can I find more information about this?

**Comment by baijum** [comment]
> Where can I find more information about this?

Few info is here:
http://www.crosswire.org/pipermail/sword-devel/2019-June/047095.html

**Comment by wesinator** [comment]
The ESV is still listed on https://andbible.github.io/ and the app description on Google Play

**Comment by tuomas2** [comment]
@wesinator fixed that now.

**Comment by tuomas2** [comment]
Added info to FAQ how to get ESV back if you have it installed in another device.

**Comment by stevenbell** [comment]
Is there any way I might be able to help with this?  My first thought was to write some sort of adapter that would fetch the ESV text via Crossway's API, but their API conditions are pretty restrictive and I imagine we'd go way over the 5000-request-per-day limit.  I guess the other apps/websites have agreements with different terms.

**Comment by tuomas2** [comment]
Drop me email and I can tell about my plans.

**Comment by quasinormalized** [comment]
Are there any updates on this? Any confidence this will actually make v3.4?

**Comment by tuomas2** [comment]
No confidence at all. Unless miracle happens and someone negotiates a deal with crossway.

milestone just means that i/we have plans to try something if possible.

**Comment by Dockerfile256** [comment]
You can download the ESV Bible from the [Wayback Machine](https://web.archive.org/web/20170705130043/https://crosswire.org/sword/modules/ModDisp.jsp?modType=Bibles)

**Comment by samuelcmace** [comment]
The ESV Bible is avaliable for download as a SWORD module from the [Wayback Machine](https://web.archive.org/web/20160802201507/http://www.crosswire.org/ftpmirror/pub/sword/packages/rawzip/ESV.zip).

**Comment by agrogers** [comment]
I have kept a past version of the ESV Bible which I keep moving across to my new phones. Is that legal? 

I have just noticed with the latest beta version that spacing between words and punctuation has got messed up. It now joins random words and spacing after commas and fullstops is missing. See attached. 

Is this an issue that you want to address? If it is I should open a different issue for it. 
![IMG_20210426_101516](https://user-images.githubusercontent.com/13920678/116015079-6b850500-a67b-11eb-86c7-b751af3003bd.jpg)

(https://user-images.githubusercontent.com/13920678/116015057-590acb80-a67b-11eb-9d61-4296c5bed275.jpg)

**Comment by tuomas2** [comment]
> I have kept a past version of the ESV Bible which I keep moving across to my new phones. Is that legal?
> 
> I have just noticed with the latest beta version that spacing between words and punctuation has got messed up. It now joins random words and spacing after commas and fullstops is missing. See attached.

Moved this to a new issue #996

**Comment by benasocj** [comment]
A workaround would be to download the freely available [ESV Classic Reference Bible](https://www.crossway.org/books/esv-classic-reference-bible-ebook/) ebook in `EPUB` format which then could be extracted (since an `EPUB` file is just a zipped file). Someone could then write a tool which builds a SWORD module out of the extracted content.

If someone is willing to write such a tool and share it here then we could all download our own ESV ebook copy first and then build our SWORD module on our local machines. This way there shouldn't be any issues about hosting an ESV SWORD module on any servers since we would be building it on our own from the ESV ebook.

**Comment by Noitarud** [comment]
Issue #1414 on epub now addressed.

**Comment by benasocj** [comment]
> Issue #1414 on epub now addressed.

My comment on EPUB had nothing to do with reading EPUBs with AndBible. Instead, the ESV EPUB file would be used to generate a SWORD module which could then be used with AndBible.

**Comment by tuomas2** [comment]
Yep epub support enables opening epub as a generic book.

I have a feeling that we can't do anything about this any more, so closing this. 

Users need to find the module themselves if they want it. We have multiple module types supported and there are many options available with some research over the internet.
Crossway could easily fix this by re-allowing distribution of their bible module...
