### ISSUE TITLE
Romaji for Japanese versions

### ISSUE THREAD

**Issue by oxr463** [AndBible/and-bible#392]
**Is your feature request related to a problem? Please describe.**

More than one Japanese versions are available, but there is no romaji translation available.

**Describe the solution you'd like**

I really like how the strongs numbers are implemented; perhaps we could have something similar for kanji.

**Describe alternatives you've considered**

See: https://www.equipd.me/news/equipd-bible-version-3-0/japanese-romaji-and-furigana

**Comment by tuomas2** [comment]
See our FAQ https://github.com/AndBible/and-bible/wiki/FAQ#please-add-module-x-to-and-bible on how to proceed with this request.

If app needs special programming support for the module that has been put available on SWORD platform, I'm here to help.

**Comment by tuomas2** [comment]
Closing this issue as there's nothing here to be done by And Bible developers.

**Comment by oxr463** [comment]
Thanks for the information!
