### ISSUE TITLE
When special links window is open but not active, touching X button does nothing

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#394]
1. Open some Bible with Strongs numbers and show the numbers.
2. Click a Strongs number, and the dictionary definition (special links) window opens.
3. Touch and scroll in the first main Bible window to make it active
4. Try to touch the X in links window to close it, and nothing happens

**Work around:** Touch and scroll in the dictionary definition (special links) window, then touch X and it closes

**Expected behavior**
Touching the X button should always close the window, we shouldn't have to scroll in the links window first, before being able to close the window.

**Comment by tuomas2** [comment]
Will be fixed in build 312

**Comment by bvahedy** [comment]
Verified fixed in 312
