### ISSUE TITLE
Maximized mode: After adding new window, cannot change document

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#398]
**To Reproduce**
1. Have 2 open windows
2. Click maximize on 1 of them
3. Click the "unmaximize" button on bottom right and click "New window"
4. Now change document to another Bible version or to a commentary, before touching or scrolling in the Bible window

**Problem:** The previous open window document get's changed. For example, if the first button is selected when you click new window, now the last button is selected because that is a new window. But when you change document, the first button letter changes, and the open window does not change

**Workaround:** Touch and/or scroll in the Bible view, then you can change the document.

**Comment by tuomas2** [comment]
Will be fixed in build 312

**Comment by bvahedy** [comment]
Verified fixed in 312
