### ISSUE TITLE
Find does not display a count of the number of occurrences anymore. 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#400]
When searching for a word in a bible there used to be a 3 second pop up that showed the number of verses found. This no longer appears.

**Comment by timbze** [comment]
@bvahedy It does still appear for me. Can you tell which version you are using and which document you are searching? Or have you tried different documents?

**Comment by bvahedy** [comment]
I'm on 3.1.311 beta build.
What version are you on?

**Comment by bvahedy** [comment]
I've tried it with different Bible translations.

**Comment by timbze** [comment]
I also use 311 with some unrelated mods on it though. This is a strange issue.
Have you tried with night and regular mode?

**Comment by bvahedy** [comment]
Ok, I uninstalled and  reinstall AB and it's now working fine. This happens
every so often where if I just install a new version without uninstalling
completely weird things happen.
I'll close the ticket. Thanks Tim.
