### ISSUE TITLE
Assign labels: change suggestion

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#406]
Via email by Rapha

> Verse/s long press gives us a TOP MENU options and upon choosing BOOKMARK  (from Top) it's a kind of annoying the ASSIGN LABEL pops up on the bottom !!! If this benefits others also, please consider altering the top BOOKMARK icon (once selected) into ASSIGN LABEL icon from which we could go to appropriate LABELS. This also, I believe, brings consistency in our finger movements/ strokes rather than going all over the screen --

**Comment by timbze** [comment]
I think maybe it would be a good idea to have a long press on the bookmark icon take the user directly to assign labels screen. Though I'm not sure if it would really be good, cause usually a long press causes a tooltip to popup to give the name of the icon. For example, I use it when I'm not sure if that's the icon I want, I long press it, and a small tooltip that says "Add bookmark" pops up.

Maybe a long press could pop up the "Add bookmark" tooltip along with another "Assign label" link underneath it.

**Comment by timbze** [comment]
Obsolete as the way of adding bookmarks/labels has completely changed
