### ISSUE TITLE
Cannot deselect verses when last verse of chapter and first verse of following chapter are selected

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#408]
1) Find the last verse in a chapter.
2) Tap and hold on that verse.
3) single tap on the next verse (first verse of following chapter)
4) try to deselect one of the 2 by single tapping and nothing happens.

Expected behavior: should be able to deselect any verse by single tapping

**Comment by timbze** [comment]
Hi Ben, I tried it with a few verses in Psalms and I can't reproduce. Can you give me a specific example of Bible version and verse where it happens?

**Comment by bvahedy** [comment]
Try ESV Psalms 111:10 tap and hold to select this verse, then tap on the
next verse which is Psalms 112:1 to select it. Now tap once on 112:1 and
you won't be able to deselect it.

**Comment by timbze** [comment]
Ok, I could reproduce it now. It seems to not be related to ! mark, but ending of chapter. I could reproduce anywhere, selecting the last verse of 1 chapter and first verse of the following chapter.

**Comment by bvahedy** [comment]
Ok, good to know.

**Comment by tuomas2** [comment]
Reproduced

**Comment by tuomas2** [comment]
Obsolete, as of different implementation in develop
