### ISSUE TITLE
No document found is displayed when accessing bookmark from history

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#409]
Note: make sure windows sync is on

1. Create a bookmarks for Col chapter 3:1
2. Create a second window. Use ESV for this window. With the second window in view,
3. Go to bookmarks and select any passage so that a bookmark item is created in the history list for this window. (Later we will use  the device's back button to bring the history list up.
4. Tap on  the top window and from the menu bar go to Exodus 4:1, scroll a few verses down.
5. Tap on the bottom window
6. Press and hold the device's back button at the bottom of the screen  to bring up the history list.
7. From the history list select the other called bookmark, then when bookmark list comes up select Col 3:1

The top window will display "no documents found" 

The following is what a user reported:
After going to a bookmark in Exodus 34 and scrolling down to verse 34, then selecting a bookmark of mine, Colossians 3:1, it takes me there, but with the reference marked incorrectly, which many times I don't recognize until I turn off the bookmark and it leaves me staying at a blank reference for Colossians 34:1.

**Comment by timbze** [comment]
Quite possibly related to #324

I've tried solving that one but it's difficult to find the issue. Will try some more when I have some more time.

**Comment by timbze** [comment]
I'm fully convinced this is the same issue as #324. I will close this issue.
