### ISSUE TITLE
The linVB about doesn't show well the link to the source module

### ISSUE THREAD

**Issue by LAfricain** [AndBible/and-bible#412]
**Describe the bug**
The link to gitlab in the about is broken. (not show correctly), but it is not a sword issue because on Bishop and Xiphos it's good shown.

**To Reproduce**
1. Go to the about in LInvb module
2. You can see the bad link to Gitlab.

**Expected behavior**
A good link to gitlab.

**Comment by timbze** [comment]
See image below:

![Screenshot_15710675982](https://user-images.githubusercontent.com/35117769/66764479-169de700-ee67-11e9-9f97-7ce9fe409771.png)

**Comment by LAfricain** [comment]
@timbze : thank you for the picture.

**Comment by LAfricain** [comment]
The same for the Kikongo

**Comment by tuomas2** [comment]
Will be fixed in Build 367
