### ISSUE TITLE
Workspace: special links window moves to other workspace

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#413]
**To Reproduce**
1. Open more than 1 workspace (tab) 
2. In one of them show strongs link in KJV Bible and click one of the links so that the definition window pops up
3. Switch to another workspace (tab) 
4. The definition window is now also showing in that workspace 

**Expected behavior**
The links/definition window should stay in the workspace where it was opened.

**Comment by bvahedy** [comment]
This works now in build 314.
