### ISSUE TITLE
Make it possible to disable display of chapter/verse number when scrolling

### ISSUE THREAD

**Issue by gnunicode** [AndBible/and-bible#415]
I tend to scroll down continuously when reading the Bible. However, a new feature has been added which shows the chapter and verse number near the bottom of the page while scrolling, which is very distracting. It would be nice for there to be a setting which allows for this feature to be disabled - when looking through the settings I did not find an option to turn this off.

**Comment by timbze** [comment]
@gnunicode There is some related discussion [here](https://github.com/AndBible/and-bible/issues/299) and [here](https://github.com/AndBible/and-bible/issues/310)

2 work-arounds you could use for now:
- You can disable "Full screen by scrolling" option in the menu on top right. When not in full screen, the reference overlay does not popup.
- Or you can also use "Tilt to scroll" feature, also in top right menu. When using that feature, the reference overlay also doesn't come up.

**Comment by timbze** [comment]
Closing in favor of #310
