### ISSUE TITLE
User custom reading plan shows as blank line

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#418]
**To Reproduce**
1. Copy [this file](https://github.com/AndBible/and-bible/files/3709507/y1ot1nt1_chrono.txt) to your sdcard jsword/readingplan folder
2. Make sure And Bible is closed and not in apps list. Open And Bible and look for the reading plan in the reading plan list. (if it does not show up you may have to go under device settings > Apps > And Bible > Permissions and enable storage permission)
3. When trying to select a reading plan, you will see one line is blank in the reading plan list. You can click it and the reading plan opens correctly though.

**Expected behavior**
The reading plan list should at least show the plan file name if it has no Plan Name specified in the file.

**Comment by timbze** [comment]
After bugfix #419, up to the first 5 lines in properties file can be used for Plan Name and Description. The first line starting with a # symbol will be treated as plan name. The following 4 lines will be treated as description (only if starting with # symbol). This is an optional feature.

**Comment by tuomas2** [comment]
Will be fixed in build 314

**Comment by bvahedy** [comment]
I copied this file into the jsword/readingplan directory:
 y1ot1nt1_chronological.properties

When viewing the reading plan from AB it shows a description but going to that plan causes the reading not to work. I had to remove the file from that directory and do a reset of the reading plan to recover from the errors caused by this mod.
This mod seems incomplete or may be I'm doing something wrong.

**Comment by timbze** [comment]
@bvahedy I think there are 2 issues here. 1. I realize now I think it's because of the filename. That same file name is in use in the default readings, I think if you rename the file to something a bit different (you need to leave it with .properties though) then it will work

2. I think the file is not downloading correctly from the link I put in here. I'm attaching a file here you can try, you need to rename it to .properties though instead of .txt
[y1ot1nt1_chrono.txt](https://github.com/AndBible/and-bible/files/3709507/y1ot1nt1_chrono.txt)

**Comment by timbze** [comment]
Created issue #433 for duplicate file name issue

**Comment by bvahedy** [comment]
Tim,
Ok, it works now but the description and the name of the plan is the file
name, is that something that goes into the file?
You can close ticket #418 if you feel no further action is needed.

Ben

**Comment by timbze** [comment]
> Ok, it works now but the description and the name of the plan is the file name, is that something that goes into the file?

Yes, the name and description needs to be added in the file for custom user reading plans. I will add the info to the wiki yet. Thanks for your input Ben. Closing this now.
