### ISSUE TITLE
Il n'y a plus de commentaire en Français 

### ISSUE THREAD

**Issue by patheosondo** [AndBible/and-bible#421]
**Describe the bug**
La liste des commentaires en "French" est vide. En effet, quand on va dans "Telechargement de documentaire " et qu'on choisi "Commentaire" avec "French" comme langue, la liste est vide; on a une page blanche.

Google translate:

> The list of comments in "French" is empty. Indeed, when we go in "Download documentary" and we chose "Comment" with "French" as language, the list is empty; we have a blank page.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A50
 - OS: Android 
 - Version 9

**Additional context**
La version de Andbible est 3.1.305

**Comment by tuomas2** [comment]
@patheosondo what are you expecting to see?

**Comment by patheosondo** [comment]
In the past, when I rolled up the list of comments in French, there was a
comment in the list. Now this list is empty. So I would like to see some
more comments in the list so I can choose one for my biblical readings
---------------------------------------------------------
Patindé Théodore SONDO

**Comment by tuomas2** [comment]
As far as I understand you are talking about some module that has disappeared. 
We at And Bible are not controlling the distribution of modules. Please see our FAQ:
https://github.com/AndBible/and-bible/wiki/FAQ#please-add-module-x-to-and-bible

Will close this ticket as there's nothing to be done for And Bible developers.
