### ISSUE TITLE
Write workspaces into sqlite database

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#423]
Instead of storing workspaces in shared preferences, we should write them in database. This is important so that backup/restore works and in order to implement sync #154 properly to support tabs.

**Comment by bvahedy** [comment]
The name of the first work space is not restored correctly. It shows as workspace 1 which is the default name. But the other names are restored correctly.

**Comment by tuomas2** [comment]
Created bug ticket. Closing feature ticket.
