### ISSUE TITLE
Book is displayed with blank page and no data... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#425]
When you have multiple windows and want to switch the order they appear at the bottom of the screen. You bring three windows up into display, then using the windows menu, tap on "move first" and then minimize the two bottom windows. Close the app. The book that the top window was in displays no data and a white page. I tried reading a chapter and it reads it but no text is shown for that book. all the chapters in that books display no data. all other books are visible. All synchronized windows also come up with no data. I had to finally clear cache and data and restore all my books. There is no other way out of this problem.

I'm currently unable to reproduce this but I know it has something to do with reordering multiple windows using "move first" to reposition them.

**Comment by tuomas2** [comment]
Can't reproduce. 

Please try to reproduce with build 315.

**Comment by bvahedy** [comment]
It seems to be working, but I will keep an eye on it.
