### ISSUE TITLE
Initial screen in night mode disruptive

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#427]
From Jared via email:

> I like the night mode within Andbible, however the initial full-white screen which displays for a 1/2 second on launch feels disruptive. Could this be adjusted to black, or adaptive to the mode which is set in the app?

Related: #426

**Comment by timbze** [comment]
This also happens in Maximized mode when switching to another window that is not loaded yet.

For example, when in maximized mode, close AB and remove from task list. Open AB and switch to another window, white screen shows for a little bit before text gets loaded.

**Comment by tuomas2** [comment]
Will be fixed in next beta > 340

**Comment by bvahedy** [comment]
Verified fixed in build 342-beta.
