### ISSUE TITLE
Workspace: rename does not change all references right away

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#432]
**To Reproduce**
1. Have more than 1 workspace, and go rename the current workspace
2. Open the list of workspaces, the updated name is there
3. Click the 3 dot menu and you will see Workspace (old name)
4. The name before renaming also appears when going to verse picker, the title says Choose Book (old name)
5. To work around this, open a different workspace, and then come back to the one you renamed and then all references are updated to the renamed name.

**Comment by tuomas2** [comment]
Just fixed this in 694ec607c0b326a724f5653cc3059445366e7cb9

**Comment by tuomas2** [comment]
Will be fixed in build 315

**Comment by bvahedy** [comment]
Verified fixed in build 315.
