### ISSUE TITLE
User reading plan issue with same name as internal plan

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#433]
**To Reproduce**
1. See #418 and add a user plan with same file name as one of internal plans
2. Try to open it and it shows the same status as the internal plan

**Expected behavior**
Duplicate user plan name should not show up in reading plan list, and a message should pop up that the file needs to be renamed to something else in order for it to work.

**Comment by tuomas2** [comment]
Fixed in build 315

**Comment by bvahedy** [comment]
Like the addition of a pop up screen,  very helpful. This is working now in build 315.
