### ISSUE TITLE
Text to speech voice incorrect

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#438]
When using Google's TTS, changing language within Google's voices does not change it within AndBible.
Also, I'm not able to change the speech rate while it's speaking, this used to work before.

Via email
> I've configured the voice I prefer for text to speech in Android under Settings -> Accessibility -> Text to speech output and Settings->Language & input -> Text to speech output.  When I tap "Listen to an example" I get the voice I want.  But when I ask AndBible to read the scriptures to me, it switches to the Android default voice rather than the voice I have selected

**Comment by bvahedy** [comment]
This works for me. I am using Galaxy note 8 with Android 9.0.
I changed the system TTS on the phone settings and AndBible used whatever I chose in the phone settings.

**Comment by tuomas2** [comment]
I also tried and could get it play correct voice without issues. 

Need to ask user more details. Closing for now.

**Comment by bvahedy** [comment]
I noticed when using Google's text to speech changing the voice to another language within Google's TStS does not change in AndBible, may be this is what the user is complaining about.

**Comment by tuomas2** [comment]
Via email
> I have found for me, that And Bible TTS uses the phone system default language and not Accessibility TTS setting. I have set my phone's default language to English (United States), but I set my TTS language to English (Australia). Most apps on my phone talk to me with Australian accent, except And Bible which speaks to me with US accent. I would prefer it used the TTS setting. Many thanks for all the hard work you folks put into this indispensable app.
> Phone=Pixel XL Android 10, build= QP1A.191005.007.A1
> And Bible version 3.1.313 (But it had been doing this since Martin added TTS.)

**Comment by tuomas2** [comment]
#939 should fix this.
