### ISSUE TITLE
Speak bookmark not moved when changing speed

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#439]
1. Continue speaking from speak bookmark 
2. Go to speak settings and change speed
3. Let playback continue at least 1 verse more
4. Pause / stop
-> Expected: Bookmark is moved to pause/stop location
-> Actual: Bookmark is not moved

**Comment by bvahedy** [comment]
I'm not able to duplicate this, do you have automatic bookmarking checked
in the speak advance settings?

**Comment by tuomas2** [comment]
Speak settings:
- Repeat passage on (few books)
- Text follows speech off
- Automatic bookmarking on
- Save playback settings to bookmarks on

**Comment by bvahedy** [comment]
Tuomas, under the latest beta build 315,
Changing the speech rate within AndBible or from phone settings, doesn't
change the reading speed. This used to work, I don't know at what point
this stopped working. Any ideas?

**Comment by timbze** [comment]
Changing the reading speed from within the app settings does work for me.

**Comment by bvahedy** [comment]
Thanks Tim, are you running Android 9.0?
I know the latest OS update disabled calls from being recorded due to
privacy issues in some countries, could they have messed something up in
this area, I don't really know for sure. I did do a fresh install, I don't
know how else to get this to work.

**Comment by timbze** [comment]
I have Android 8.0 on LG G6. I can also test on emulator with Android 9
sometimes and see if the issue is there too.

**Comment by bvahedy** [comment]
Thanks Tim, please do if you can. Something is definitely wrong somewhere.

**Comment by bvahedy** [comment]
In 319.4 I tried this and even without changing the speed it does not move the speak bookmark when stopping at a different verse.

**Comment by tuomas2** [comment]
Fixed in 321.2

**Comment by bvahedy** [comment]
Verified fixed in build 321.3
