### ISSUE TITLE
Restoring second window doesn't jump to top window's verse... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#443]
Windows synchronization failure.

To reproduce:
1) open two windows, top window jps bottom window kjv.
2) view a passage and move couple of verses down. All is well so far.
3) now minimize the bottom window.
4) move two or three verses up.
5) restore the kjv window and you will notice the window is at the verse when it was minimized and not at the verse of the top window.

Expected behavior:
When the lower window is restored it should sync with the top window. This used to work before.

**Comment by tuomas2** [comment]
Tested with build 318.3 and seems Ok. 

Will be fixed in 318.3.

**Comment by bvahedy** [comment]
Verified fix in build 319.1.
