### ISSUE TITLE
Transifex: translation in Burmese impossible

### ISSUE THREAD

**Issue by LAfricain** [AndBible/and-bible#446]
**Describe the bug**
I want to translate in Burmese. But when I'm on [transifex](https://www.transifex.com/mjdenham/andbible/), I can't find how to do. Nothing "clickable" in the language. If I want to add me in the language group for Burmese, the Burmese in not in the list.
Please help me to know how to do. With other software I don't have this problem.

**Comment by tuomas2** [comment]
I just went to transifex and accepted pending request. You should now be able to start translating. https://www.transifex.com/mjdenham/teams/10122/my/

**Comment by LAfricain** [comment]
Ok thank you!

**Comment by LAfricain** [comment]
I have also a complete list of Myanmar book translation, not yet add to sword. If you want to add it in Andbible, you can find it in the attached file.

[my-utf8.zip](https://github.com/AndBible/and-bible/files/3864473/my-utf8.zip)

**Comment by tuomas2** [comment]
@LAfricain could you do books translation here: https://www.transifex.com/mjdenham/jsword/dashboard/

**Comment by LAfricain** [comment]
Ok but add first the Burmese (why French is not in the list?)

**Comment by tuomas2** [comment]
now you are set up. https://www.transifex.com/mjdenham/jsword/language/my/

French is already translated by upstream jsword / sword?

**Comment by LAfricain** [comment]
> French is already translated by upstream jsword / sword?

Oh Yes!

**Comment by LAfricain** [comment]
I can't see the Myanmar in the value folder (and-bible/app/src/main/res/), do you know why?

**Comment by tuomas2** [comment]
Hi @LAfricain, do you mean burmese language by Myanmar? Burmese translation is not yet done so I have not pulled it from Transifex. Once it's acceptable level (80%) I will pull the translations.

**Comment by LAfricain** [comment]
Yes i'm speaking about Myanmar. The problem is not the presence of the file in the software, but the Impossibility to translate it on transifex.

**Comment by tuomas2** [comment]
Hmm, just checked from transifex and you have translator permission to the language.

![Selection_234](https://user-images.githubusercontent.com/5811789/81476378-5f115d80-921a-11ea-9ca1-e2c00e86a7d8.png)

**Comment by LAfricain** [comment]
Can you copy the link here, I don't understand, look what I have:
![burmese](https://user-images.githubusercontent.com/19690477/81476482-76e4e380-9212-11ea-93f4-8b61c7307806.png)

**Comment by LAfricain** [comment]
Ok!!!  I'm in the wrong place... Jsword and not Andbible...

**Comment by tuomas2** [comment]
Yep jsword stuff is moved under AndBible so you can translate bible book names there too.
