### ISSUE TITLE
Blank screen when assigning bookmark labels. 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#447]
To reproduce:
With two Bible windows open
1) tap and hold a verse on the top window.
2) tap on the bookmark icon on top menu bar.
3) tap on assign labels at the popup menu at the bottom of the screen.
4) tap on an existing check box label. Tap ok.

The Bible text on the top window goes blank.

**Comment by tuomas2** [comment]
build 318?

**Comment by bvahedy** [comment]
Yes, 318 beta#2

**Comment by tuomas2** [comment]
Will be fixed in build 318.3

**Comment by bvahedy** [comment]
Verified fix in build 319.1
