### ISSUE TITLE
It is possible to scroll down too much such that window content is blank

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#448]
In build 319.1 With two windows open:
Top window is jps
Bottom window kjv

1) from the top menu go to Genesis 50
2) scroll up on top window. All the way to the end of the chapter.

Top window displays blank while the bottom window displays the last verse of the chapter.

Expected behavior:
Top window and bottom window should display the same information preferably no blank windows.

**Comment by timbze** [comment]
I think the issue here is just that it can scroll too far. It happens with any book or commentary in any window.
Unless if you're talking about a different issue than I'm seeing

**Comment by bvahedy** [comment]
When viewing two Bible windows for comparison in synchronized mode both
windows should display the same verse. It looks weird to have the top
window be blank and the bottom one showing a verse.
Even if you scroll slowly this happens.

**Comment by tuomas2** [comment]
Is this really an issue even? I think this is by design. I agree with @timbze that we could restrict scrolling a bit, but not implementing it now.
