### ISSUE TITLE
Landscape view sync etc. is broken

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#450]
Synchronization and verse display is broken after adding new windows / closing window / changing from portrait -> landcape. 

Build 319.4

**Comment by tuomas2** [comment]
Will be fixed in 321.3

**Comment by bvahedy** [comment]
This is still buggy in build 321.3. 
I tried having two windows open and just rotating the device to landscape the verses are off. Tried it also with a Bible with RTL text like WLC.

**Comment by tuomas2** [comment]
Will be fixed in 321.4

**Comment by bvahedy** [comment]
This seems to have been fixed in build 321.7
