### ISSUE TITLE
Can't exit note window

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#451]
Via email:

> Not sure whether the following issue is related or not but when I try to update an existing NOTE with a newly copied verse, the screen locks up and won't allow me to exit the NOTE widow -- 

Reported for build 319.4.

**Comment by tuomas2** [comment]
Reproduced.

**Comment by timbze** [comment]
One work around that works for now is to open another workspace and then come back to this workspace. Then note window is gone.

**Comment by tuomas2** [comment]
Will be fixed in build 320.0

**Comment by bvahedy** [comment]
In build 320.1 the back button in Notes worked once but I can't see any text I type, it's all white. Also after tapping on the back button a few times I now get the beta version splash window and can't get out of the Note screen. Reopening this ticket.

**Comment by bvahedy** [comment]
I'm closing this but opening one for an issue in the Notes window where text starts under the menu bar.
