### ISSUE TITLE
Synchronization failure when restoring a second minimized window... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#454]
Having two windows with one in minimized state. When tapping on a link in the top window that takes you to a different book and then restoring the minimized window, the bottom window still points to the previous chatter verse of the top window.

Steps to re-create:
Open two windows, top window is HCB and bottom window is kjv.
1)  navigate top window (hcb) to Matthew 2:1
2) minimize the kjv (bottom window)
3) slide up to verse 6 where there is a link to Mic 5:2 and tap on the link.
4) restore the kjv window and it displays the passage from Matthew instead of Micah.

You can get the hch.Zip from here:
https://1drv.ms/u/s!AgQrBUWnj0-jgUuLxlf4nxn15sKi

**Comment by timbze** [comment]
Hi Ben, do you have the setting "Open links in special window" on or off?

By default that setting is on and so the link that is opened in new window
is not in sync with the rest. But when I turn it off I can reproduce what
you report.

**Comment by bvahedy** [comment]
Hi Tim,
Yes the setting for open links in special window is off (unchecked), that
is why I can minimize the second window. This is a sync issue.
 Besides you can not synchronized special windows.
But I'm glad you were able to reproduce this issues.

**Comment by tuomas2** [comment]
More generally, with any 2 synced windows (even with 2 kjv etc), the bug was reproducable.
Simplified:

1. navigate top window to Matthew 2:1
2. minimize the bottom window
3. navigate top window to Matthew 3:1
4. Restore the bottom window and it displays the passage from Matthew 2 instead of Matthew 3.

**Comment by tuomas2** [comment]
Will be fixed in build 320.2.

**Comment by bvahedy** [comment]
Verified fixed in build 321.3
