### ISSUE TITLE
From a user: back button non-responsive when editing a note... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#456]
From a user:
After editing note: back button doesn't close note. No way to get back to bible.

Expected behavior:
Back button in note window should go back to bible window. Also tapping and holding the device back button should not display the history when viewing the notes.

**Comment by tuomas2** [comment]
Duplicate of #451?

**Comment by timbze** [comment]
This is duplicate of 451, but not sure about this part below, or if this is matters if it stays this way:
> Tapping and holding the device back button should not display the history when viewing the notes.

If this is something that needs to be addressed we should make a new issue out of it I think.

**Comment by bvahedy** [comment]
Sure, we could separate it into two tickets.

**Comment by timbze** [comment]
I'm thinking we could maybe leave the long press back as is for now, until we work with #188 (show / edit "my notes" as a window (like other translations))
I'm interested to hear Tuomas' thoughts on this.

**Comment by bvahedy** [comment]
Yes, I agree.

**Comment by bvahedy** [comment]
Verified fixed in build 321.2
