### ISSUE TITLE
My note window opens at wrong verse

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#459]
**Bug was found on And Bible version**
Happens only after 319.4, after Kotlinizing MyNotes I think.

**To Reproduce**
1. Scroll to Matt 1:10, so v10 is the top verse in screen
2. Select verse 12 and click the pencil icon to open MyNotes
3. The note opens on v10, but it should be the selected verse, v12

**Comment by bvahedy** [comment]
I'm unable to duplicate this issue. But I have found a lot of issues
similar to this where the header doesn't match the verse at the top of the
screen.

**Comment by timbze** [comment]
I think this does not happen in 319.4, which is probably the version you have? I made a build for myself for a later commit already.

**Comment by tuomas2** [comment]
Will be fixed in build 320.0

**Comment by tuomas2** [comment]
I think this issue still exists.

**Comment by timbze** [comment]
I can not reproduce in 321.6

**Comment by tuomas2** [comment]
1. Open my note in verse 1
2. Write "This is note for verse 1"
3. Go back to bible view
4. Open my note in verse 2 that does not yet have note
5. Actual: There is "This is note for verse 1" as content for verse 2. Expected: should be still empty.

**Comment by timbze** [comment]
Looks like that is something about note not getting cleared. After step 3 you can go to next chapter and open note on any verse and the previous note shows up

**Comment by tuomas2** [comment]
Will be fixed in build 321.9

**Comment by bvahedy** [comment]
Verified fixed in build 321.9
