### ISSUE TITLE
First workspace name not restored correctly

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#464]
Moved from #423 

The name of the first work space is not restored correctly. It shows as workspace 1 which is the default name. But the other names are restored correctly.

**Comment by bvahedy** [comment]
Verified fixed in build 321.3

**Comment by bvahedy** [comment]
For some reason this is happening again in build 321.4, so, I'm reopening the ticket.

**Comment by tuomas2** [comment]
Can you tell me more specifically how to reproduce?

**Comment by bvahedy** [comment]
After restoring the bookmarks and tabs, I changed the name of the first
tab. Then I restored the bookmarks and notes again and the first tab did
not get restored.

**Comment by timbze** [comment]
I think this has something to do with cached data. I've had similar
experience with reading plan. But I don't know exactly yet how it is
possible.

Ben, try closing AB after restore and remove from task list, then reopen
and see if the tab name is restored

**Comment by tuomas2** [comment]
No, there was clear bug. After restoring from backups, workspaces were not updated according to the restored db.

**Comment by tuomas2** [comment]
Will be fixed in 321.5
