### ISSUE TITLE
Commentary / general book position not restored correctly

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#465]
1. Open commentary page that is longer than screen height
2. Scroll down a little
3. Close app
4. Open app again
5. Expected: Scrolling position should be restored. Actual: Scrolling position is reset to top.

**Comment by tuomas2** [comment]
Reported for 320.1.

**Comment by tuomas2** [comment]
Fixed in 321.0

**Comment by bvahedy** [comment]
Verified fixed in build 321.3
