### ISSUE TITLE
Links window is not restored properly

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#466]
1. Open links window by clicking a link
2. Change bible document in links window to non-default one
3. close app and restart
4. links window will appear in default bible, not specified one.

**Comment by tuomas2** [comment]
Will be fixed in build 321.2

**Comment by bvahedy** [comment]
Tried this in build 321.3 and now can't open the app.
To reproduce:
I tapped on a link then I closed AndBible and now it crashes on reopen. Need to reinstall the app.

**Comment by tuomas2** [comment]
can't reproduce the crash, can you attach some logcat?

**Comment by tuomas2** [comment]
Could this also be fixed because of #464 fix? If you were using "restore backup" it could be.

**Comment by tuomas2** [comment]
(so might be fixed in 321.5)

**Comment by bvahedy** [comment]
This seems to have been fixed, it may have had something related to workspace fixes.
