### ISSUE TITLE
New workspace opens different version and freezes reference title 

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#468]
**Bug was found on And Bible version**
321.6

**To Reproduce**
1. From workspace with kjv Bible open, create new workspace 
2. New workspace opens in ESV, but title shows kjv
3. When scrolling, the title stays frozen at the same verse it was loaded at. 

**Expected behavior**
1. New workspace should open in same version that it was opened from.
2. Should not get frozen

**Comment by tuomas2** [comment]
Fixed in 12d9fa486731ebcdff5da61160c42d64f3b7d7ac

Will be fixed in 321.7

**Comment by bvahedy** [comment]
Initial steps did not caused this but after going back and forth a few times between the two workspaces the title of the first tab did freeze, but I don't know the exact steps that caused it. I did swipe left and right to go to different chapters in the first tab. Will reopen this for now.

**Comment by tuomas2** [comment]
Current correct behavior is:
- if current document type is changed, newly changed document type is saved as default
- When creating new workspace, new window will have default bible opened

**Comment by bvahedy** [comment]
What constitutes a default Bible and how is it set as a default?
In build 325 this again happened once where the workspace title froze, but I was not able to duplicate it again.

**Comment by tuomas2** [comment]
at the moment the definition is 'last explicitly changed document type'. I'm not sure what would be best logic for this though. 

Logic to reproduce this would be valuable. Or if it is very unexpected, it might also be helpful to study logcat report that has been obtained when this happened.

**Comment by bvahedy** [comment]
I'm ok with using  'last explicitly changed document type'
with to create a new tab. The other option would be to always use the Bible
from the first workspace as a new tab.

**Comment by timbze** [comment]
I also think 'last explicitly changed document type' is fine, but possibly only "last **Bible** document type" ?

But rather than document type from first workspace, I think it would be better to take from active workspace when creating new workspace.

**Comment by tuomas2** [comment]
> In build 325 this again happened once where the workspace title froze, but I was not able to duplicate it again.

Did you use HISB module when this happened?

**Comment by tuomas2** [comment]
> But rather than document type from first workspace, I think it would be better to take from active workspace when creating new workspace.

I changed behavior such that when creating new workspace, it sets current bible document form last active workspace active window.

**Comment by tuomas2** [comment]
> > In build 325 this again happened once where the workspace title froze, but I was not able to duplicate it again.
> 
> Did you use HISB module when this happened?

I'm thinking this is same issue as #473, if you experienced it with HISB.
If you experience freezing with any other module (i.e. such that HISB is not open), please re-open.
