### ISSUE TITLE
Wrong chapter gets loaded

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#469]
May well be related to #463 
**Bug was found on And Bible version**
321.6

**To Reproduce**
1. Open 2 workspaces
2. Open Isaiah 50 in workspace 1
3. Go to workspace 2
4. Swipe down on reference title and go to workspace 1 from there
5. Go to Eccl chapter 3
6. Scroll to go to chapter 2
7. Isaiah chapter 2 gets loaded, though it still shows Eccl 2

**Comment by tuomas2** [comment]
Will be fixed in build 321.7

**Comment by bvahedy** [comment]
Verified fixed in build 321.7
