### ISSUE TITLE
Unique And-Bible user agent

### ISSUE THREAD

**Issue by JohnAustinDev** [AndBible/and-bible#47]
And-Bible uses HTTP to download zip modules, and the useragent it uses is: "Apache-HttpClient/UNAVAILABLE (java 1.5)". Maybe this is default for JSword. It would be nice if And-Bible could stick "andbible" or "and-bible" somewhere in its user agent headers.

**Comment by tuomas2** [comment]
Hmm, why is this necessary? 

Closing this now as it is old ticket. Re-open if needed.
