### ISSUE TITLE
Screen does not update during speak after being turned on... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#471]
Beta build 321.7

When speak is on and the screen is turned off, speech continues. Upon turning the screen back on, the screen doesn't move with the speak verse but the title menu updates correctly as well as the bottom menu for speak verse and percentage.
Even if the screen is moved one or more verses by hand and speech continues the screen still maintains the screen were it was originally turned off.
This used to work before don't know what changed.

To reproduce you may have to let it speak a few chapters before turning on the screen. I know it's a pain to duplicate.

**Comment by tuomas2** [comment]
Tried with 321.8 and could not reproduce. Maybe fixed?

**Comment by bvahedy** [comment]
Verified working in build 340.
