### ISSUE TITLE
Release notes for 3.2

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#474]
Version 3.2 is planned to be released on 2nd January 2020. This is **draft** for release note.

3.2.x (major release)

- Tabs / workspaces for different window setups (#245)
- History is now persisted (#231)
- Improved maximize mode behavior (#353)
- User can backup to & restore from selected target, such as Google Drive (#148)
- Reading plans (status etc.) stored in database (will be backed up) (#55)
- Date based reading plans (#292)
- Improved performance
- Bugfixes

Please report bugs either directly to Github (https://github.com/AndBible/and-bible/issues) or via email and-bible-support@googlegroups.com .

**Comment by yapper-git** [comment]
Good news! :+1: 
For me, the main "feature" is the fix for DarbyFr translation (FreJND and FreCJE will finally be again available). Thanks for all the work!

**Comment by tuomas2** [comment]
From now on I'm aiming to make hotfixes to production if urgent issues arise.
