### ISSUE TITLE
When returning to commentary with back button, y-offset wrong

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#477]
1. Load commentary page.
2. Scroll down somewhat such that there is a link
3. Long-click link and choose "open link here" 
4. Press back button
5. Expected: returning to the commentary page at same location where we left when we clicked link
   Actual: Commentary page is shown from the beginning

Can be reproduced with build 326

**Comment by tuomas2** [comment]
Will be fixed in build 327

**Comment by bvahedy** [comment]
Verified working correctly in beta build 327.
