### ISSUE TITLE
Opening links in special window uses another Bible translation... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#479]
When opening links in special window it uses another translation.
Expected result:
It should use the same Bible book as the main window.

**Comment by tuomas2** [comment]
Special window is like other windows: it has it's own bible translation. 

When you first time click a link, it will open it with the current 'default tarnslation', unless link
itself specifies the translation (some commentaries etc. might do that).

You can then change the translation.

What translation should you use, if you are clicking link within commentary for example, if not 'current default one'?

Though if opening link from a bible, it might be reasonable to use the same bible for that kind of links.

**Comment by tuomas2** [comment]
Okay now when clicking link from bible document, link is opened in special window with same bible document as active one.

**Comment by tuomas2** [comment]
will be fixed in build 328

**Comment by bvahedy** [comment]
Verified fix in beta 328
