### ISSUE TITLE
When selecting Speak bookmarks the screen shows the wrong Bible book... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#482]
1) Create speak bookmarks for different translations.
2) From the speak tool bar menu at the bottom of the speak screen, tap on bookmark icon and select a bookmark to read.
3) repeat step two for a different Bible translation.

What happens:
 the screen still shows the previous Bible book and doesn't update the screen or it may show document not found.

Expected result:
The screen should switch to the appropriate Bible book when selecting the speak bookmark.

**Comment by tuomas2** [comment]
I was investigating this and know now the root cause. I might postpone fixing this after release as it's not huge impact for users. (Probably there will be bugfix / translation update release(s) after main release anyway).

**Comment by bvahedy** [comment]
Verified fix in build 3.2.333
