### ISSUE TITLE
RC with updated translations from Transiflex

### ISSUE THREAD

**Issue by domcorbex** [AndBible/and-bible#483]
Hi!
In order to check their work, translators will be pleased to have a new release candidate with updated translations from Transiflex.

**Comment by tuomas2** [comment]
I'll make new RC this evening with latest translation. Last RC release includes most of the recent translations though. If something particular is missing, please let me know.

**Comment by tuomas2** [comment]
3.2.329 release candidate:
- Update translations (major updates to indonesian and polish)
