### ISSUE TITLE
Maximize mode: closing links window does not change active window

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#484]
**Bug was found on And Bible version**
Build 328

**To Reproduce**
1. Have more than one window in workspace
2. Open maximize mode
3. Click a link from window, so that links window opens
4. Scroll in links window, then press X to close
5. Look at reference title bar, it does not update to active window until you touch and scroll in the remaining screen
6. If you try to navigate to another passage from book/chapter chooser before active window gets changed, nothing happens

**Expected behavior**
As soon as the links window is closed, the current remaining window should be the active window.

**Comment by tuomas2** [comment]
Will be fixed in build 331
