### ISSUE TITLE
Tilt to scroll causes verse update... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#486]
In build 328, if the tilt to scroll is turned on or off, the screen moves to the nearest verse.

Expected behavior:
Active screen should not move from where it is at. The screen update flash is very disturbing on the eye and causes the user to lose where they were at on the verse.

**Comment by tuomas2** [comment]
I think it has been always like this. 
I believe this is more disturbing with the modules that you are using, than for average normal user. I will fix it separately, but not in 3.2.

**Comment by bvahedy** [comment]
I could be wrong but I have been using the same modules to test and it
wasn't doing this before. But if you are fine with it you can leave it this
way until someone else complains about it.

**Comment by tuomas2** [comment]
Fixed in build 367

**Comment by bvahedy** [comment]
Verified fix in build 369 beta.
