### ISSUE TITLE
Improve Play Store descriptions

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#489]
Play store descriptions should be updated (maybe rewritten).

**Comment by tuomas2** [comment]
English grammar corrections and fixes can be done in Transifex, in en_GB language. en_GB language is used as a placeholder for language corrections (app does not aim to support different english variants).

**Comment by tuomas2** [comment]
Please offer to contribute such modifications in https://www.transifex.com/mjdenham/andbible/

**Comment by tuomas2** [comment]
And yes, I applied already all the fixes from the Google Docs file that was displayed here. :-) Thank you for the contributions.

**Comment by dbirks** [comment]
Nice, thanks!

**Comment by tuomas2** [comment]
This was done a while ago
