### ISSUE TITLE
Is it possible to run and-bible on chromebook?

### ISSUE THREAD

**Issue by ipstone** [AndBible/and-bible#49]
I really love and-bible on my android, somehow on chrome, there hasn't been one google offline bible, really hope if it can run on chrome. Not sure if the run android app on chromebook experiment would work for and-bible though:
https://support.google.com/chromebook/answer/6088175?hl=en

If this route wouldn't work, is there another way to get a full featured chrome/Bible apps similar to and-bible?

**Comment by mattzab** [comment]
Try the directions found here:
https://github.com/mjdenham/and-bible/wiki/Running-And-Bible-in-Chrome

Please report back if it works or doesn't. The more information, the better.
