### ISSUE TITLE
The version splash screen doesn't show anymore... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#490]
I did a fresh install of build 333 and noticed this.
 I think it stopped working a couple of builds back but thought nothing of it till now.

**Comment by tuomas2** [comment]
Do you mean 'This is beta version!" notice? If so, that is not visible unless there is '-beta' appendix in the version number. Or do you mean blue startup background? I have it splashing at least on my tablet when I first time run the app. But with faster devices it might not show up (like on my phone it does not).

**Comment by bvahedy** [comment]
Ok my bad, I now remember that you added that for beta releases only. I'll
close this ticket.
