### ISSUE TITLE
Bring back manual night mode setting in Android 10

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#492]
From user via email

> With Android 10, night mode only works when Android systems is on Dark mode. Don't want my whole system to be dark, but only Andbible. Blease fix it so Andbible can be on Night Mode while Android System is in normal mode.

**Comment by kahu5** [comment]
I have Android 10, and would like to have the Settings page respond to the dark mode. As I set either System or Automatic the Settings page background is always white. Thanks

**Comment by tuomas2** [comment]
implemented in betas >340

**Comment by bvahedy** [comment]
Don't have Android 10 yet, so I can't test this.

**Comment by tuomas2** [comment]
System mode is available in some earlier androids too, for example in my Samsung Tab A it is implemented, though it has Android 9.

**Comment by bvahedy** [comment]
It's working in build 341-beta using Android 9.0
