### ISSUE TITLE
Unable to open manually installed documents on SD Card

### ISSUE THREAD

**Issue by swflint** [AndBible/and-bible#496]
**Describe the bug**
With a `jSword` or `jsword` folder at top level of my SD Card, I am unable to read/open the documents found there (note, it's a normal sword tree copied from my computer).

**Bug was found on And Bible version**
3.2.333#b7356210

**To Reproduce**
1. Install SD card with `jSword` folder as copy of .sword from machine.
2. Enable manually installed documents.
3. Allow Storage Access and force restart.

**Expected behavior**
Access to documents installed on SD card.

**Smartphone (please complete the following information):**
 - Device: Motorola g7 Play
 - OS: Android
 - Version: 9

**Additional context**
Note: Directory is a clone of a git repository.

**Comment by tuomas2** [comment]
@swflint Did you try copying jsword folder to phone's internal storage instead of sdcard? 
I'm suspecting that we are calling internal storage as 'sd card' for historical reasons.

**Comment by swflint** [comment]
Ah.  Good to know.  You might want to clear that up then, as many people wouldn't realize that.
