### ISSUE TITLE
And Bible very slow on some users

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#510]
Via email

>Thank you for you almost immediate reply!  I've always used the app with three windows open - Bible and two commentaries. The problems I'm having are extremely slow window response time.  Or the windows will go blank and stay that way.  Or the app will just freeze.  I'm using Android 6.0 on an RCA Galileo Pro.  Three of them, in fact.  All three do the same thing.  I've uninstalled and reinstalled two of them with no change.

>As I said, I'm sure it's the age of my tablets and the older Android version causing my problems.  But there are probably others out there encountering the same issues and maybe you can fix for all of us.  I don't expect you to backtrack as you keep pace with advancing technology.  Maybe you can just put an older version for older devices on Play Store as well.

>Thank you again for the years And Bible has blessed myself and my family.  And thanks for your amazing response time.

@bvahedy @timbze do you have devices with Android 6 so that we could reproduce this? There are 2 people that seem to have had bad performance (and giving low rating in Google play).

I can't reproduce this with emulator.

Reported for version 3.2.333.

**Comment by JohnArms99** [comment]
Hi Tuomas. This is my first post to Github, so I hope it is added ok. I've been a software developer for more years than I care to mention on line, but have always used our private company repositories. AndBible is great, and I really appreciate your work.

I just started using the new version and I too find it very sluggish at times. I'm using a Samsung Note 4 on Android 6.0.1. At times it is ok, but at times it seems to hang. For example, I have the option enabled to open Strongs references in a new window. If I load a new document into a window - for example, a new Bible version - and try to open a Strongs link, it won't work. Nothing happens. However, if I keep retrying after about 10 to 15 seconds it does work and the new window opens with the content shown. It is as if the window initialisation is taking that long, during whuch time the click action is being ignored.

**Comment by tuomas2** [comment]
@JohnArms99 
Perhaps you could obtain logcat for me when the hanging takes place?

Have you done any android development? If so, help on this bug would be greatly 
appreciated, as I can't reproduce this with my devices. 

Profiling results also might be helpful. Either Android (java/kotlin) side or WebView side (javascript). Probably problem is on Android side.

**Comment by JohnArms99** [comment]
I'm afraid I've not done any Android development - it's all been Windows, most recently. Net. However, I'm happy to help. I'll check how to obtain logcat first.

**Comment by tuomas2** [comment]
Good news. I got this reproduced with emulator if I'm having ARM image.

**Comment by tuomas2** [comment]
Another user reports:

> I am a frequent user of AND Bible app and I have enjoyed using it till the last update. The app is broken after the last update. I have attached a screenshot of the bug herewith. The app no longer shows certain verses and it just shows white spaces (as shown in the screenshot). I tried wiping the app data/cache and reinstalling the app but it did not help. I am looking forward to receiving a fix. I hope my feedback was helpful and kudos to your great work.

**Comment by tuomas2** [comment]
I need testing help. Could you @JohnArms99 (or anyone else with this problem) install attached APK (probably need to uninstall first, but you can try without) and say if the problem is still here.

https://drive.google.com/open?id=1x64iac2o3PHHuK-r2QbFC3LtFv6GDa78

**Comment by tuomas2** [comment]
Please let me know if this works. I also released test release on Beta channel. (334, will be available shortly... Google Play rollout releases take always few hours).

**Comment by tuomas2** [comment]
Original reported tested the fix and confirmed that it is working.

**Comment by tuomas2** [comment]
> Another user reports:
> 
> > I am a frequent user of AND Bible app and I have enjoyed using it till the last update. The app is broken after the last update. I have attached a screenshot of the bug herewith. The app no longer shows certain verses and it just shows white spaces (as shown in the screenshot). I tried wiping the app data/cache and reinstalling the app but it did not help. I am looking forward to receiving a fix. I hope my feedback was helpful and kudos to your great work.

This needs another ticket. Moving.

**Comment by tuomas2** [comment]
Now user with Android 7 reporting the same thing (via beta review):

> Why have you changed this app? It's is so slow and unresponsive since the last update. All I want to do is roll back 2 or 3 updates ago when all was simple and working well. Please give an option for no updating. I love this app until it was last updated. Why change what is not broken. When I try to get a book and chapter now it just stays on the last book chapter and verse.

**Comment by tuomas2** [comment]
Another user that reported that fix did not work: 

![Selection_124](https://user-images.githubusercontent.com/5811789/72080234-19dd2d80-3305-11ea-8b42-c6249c12088d.png)

**Comment by tuomas2** [comment]
https://play.google.com/apps/publish/?account=6727655833913220393#PreLaunchReportPlace:p=net.bible.android.activity&plrtab=PERFORMANCE&plrvc=334 possible incident.

**Comment by tuomas2** [comment]
Also slow on my old Galaxy S2 (with Android 4.4). So maybe I can start debugging with that.

**Comment by tuomas2** [comment]
This might at least partially fix this 1010c771098b7d8b4c7d9cafbda1dfad28c9d0a5

**Comment by tuomas2** [comment]
Again some performance improvement in 00f37c9f2fa2a864451a16571ba60b166282b0ad which surely helps somewhat, but still not as fast as 2.13.

**Comment by tuomas2** [comment]
User reports now improvement in 339.

> Wow yes what a difference awesome thank you so much I got my favourite bible app back. Blessings and thank You!!!! I will use the bug fix to report any issues. What a blessing!!!

**Comment by tuomas2** [comment]
I believe this is sufficiently fixed in 339. Let's re-open this if there are still issues arising from users.

**Comment by tuomas2** [comment]
User reports again slow behavior. Logcat is available in email.

Please use this function to report as soon as you have noticed it taking place.

> Tell us briefly what did you do / what happened when issue took place:
> 
> Device info:
> And Bible version: 3.2.340#31297c25 (built 20/01/20 22:13:48)
> Android version: 7.0
> Android SDK version: 24
> Manufacturer: samsung
> Model: SM-G928F
> 
> SD card Mb free: 1712
> 
> Used heap memory in Mb: 17
> Max heap memory in Mb: 256
> 
> Hi the app has become sluggish again. When I select a strong number it works fine until I return to the bible and then it hangs for about 29 to 30 seconds. When I first open the app it also freezes for about 29 to 30 seconds.

**Comment by tuomas2** [comment]
Haven't heard of this for ages, and 3.3 is released, so closing.
