### ISSUE TITLE
Fast swiping between chapters fails to load last chapter swiped to

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#511]
**Bug was found on And Bible version**
Build 333

**To Reproduce**
1. Go to Matt 3
2. Swipe left/right on screen to go to chapter 4, then 5 in rapid succession
3. The chapter loaded stays on Matt 4, but reference title shows Matt 5

**Comment by bvahedy** [comment]
Tim, when I swipe up fast I get a white screen at the end of a chapter. I
created a ticket for this. Can you swipe down one verse to see if the tile
corrects itself?

**Comment by timbze** [comment]
@bvahedy Sorry for not being clear. I'm talking about swiping left/right to go to previous/next chapter. Actually when this happens the title bar stays frozen even when scrolling up or down.

**Comment by bvahedy** [comment]
I can not duplicate this When I swipe left or right.

**Comment by timbze** [comment]
@bvahedy What phone do you have? It may not happen as easy with a faster phone than I have. I have LG G6

**Comment by bvahedy** [comment]
I'm using a Galaxy Note 8.

**Comment by timbze** [comment]
On a slower device (LG G4) this same issue also happens with multiple windows open. Window 1 has KJV and window 2 and 3 have different commentaries. Scroll from verse 5 to 7, 6 might get loaded in the commentary windows but then 7 doesn't get loaded, and when scrolling to next verse it get's loaded again.

I think when the original issue here is fixed, this issue will probably also go away.

**Comment by tuomas2** [comment]
Could reproduce with my slower tablet. Will be fixed in > 314
