### ISSUE TITLE
Maximized mode: Closing window leaves white screen

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#512]
**Bug was found on And Bible version**
Build 333, Android 8.0

**To Reproduce**
1. Open more than one window and open maximized mode
2. Click the menu button on bottom right and click "Close window"
3. Another window get's selected but does not load, leaving blank white screen

**Comment by tuomas2** [comment]
Couldn't reprduce.

**Comment by timbze** [comment]
This seems to have to do with if window has just been loaded or not.
Try it like this:
1. Open more than one window and open maximized mode
2. Select first window and then close And Bible and remove from tasks
3. Open AB and click add new window. This inserts a new window in between window 1 and 3
4. Close window 2 which is currently active
5. Window 3, which is now window 2 is selected, but not loaded, leaving white background

**Comment by bvahedy** [comment]
Tim, I was able to duplicate this with the steps you provided.
It's good to know you  can recover from this by switching to the first
window.

**Comment by tuomas2** [comment]
With these steps I could reproduce this.

**Comment by tuomas2** [comment]
Will be fixed in > 314 (next version after 314)
