### ISSUE TITLE
Do not force-load window content if view already contains chapter

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#517]
This has been current accepted behavior for long time, but now it's going to change (thus feature flag). But it could also be considered bug:

1. Open two windows, which are synced.
2. Scroll first window until first verse of next chapter. Before next chapter appears, first verses
    are already visible after current chapter ending.
->
 Actual: On first chapter, second window content is reloaded, you notice it from
   1) flicker of screen
   2) sudden jump of screen to first verse

Expected: Synced window should smoothly scroll to first verse.

Can be reproduced with 334.

**Comment by tuomas2** [comment]
Fixed in 335

**Comment by bvahedy** [comment]
Looks like it's working correctly in build 336.
