### ISSUE TITLE
Maximizing special links window causes unexpected problems

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#519]
**Bug was found on And Bible version**
Build 335

**To Reproduce**
1. Open document that has links and make sure setting to open links in special windows is enabled from settings
2. Click link -> special window is opened
3. Long-click x-button -> Window menu is opened
4. Choose "Maximize"

Special links window is not designed to be maximizable and weird behavior
follows. Thus, either step 3 should simply close link window, or step 4 maximize item
should not be selectable.

**Comment by bvahedy** [comment]
build 333 does the same thing, may be we could greyout the max option for the special windows in this case.

**Comment by timbze** [comment]
I think long-click x-button should do nothing. 

We also don't want new window option from X-button (it also gives weird issues in max mode anyway), and pressing the X is for close, so we don't need Close in the menu either.

**Comment by bvahedy** [comment]
I like this idea better. There shouldn't be any menu options for special
windows. It also keeps things simpler.

**Comment by tuomas2** [comment]
> I like this idea better. There shouldn't be any menu options for special windows. It also keeps things simpler.

This is how I fixed it in 336.

**Comment by bvahedy** [comment]
Verified fix in build 3.2.336
