### ISSUE TITLE
Fast scrolling leaves other windows on wrong verse

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#521]
**Bug was found on And Bible version**
Build 335 (Tested on Android 8.0 and 7.1)

**To Reproduce**
1. Open 3 windows, 1 Bible and 2 commentaries with all in sync
2. Scroll down fast in Bible window (let's say from verse 5 to 12)
3. Bible window is on verse 12, commentary windows may have loaded any verse from 5 to 12

**Expected behavior**
The commentary windows need to end up with the same verse as the scrolled window. Not sure what's the best way to do it, cause it's not necessary for commentary windows to load each verse from 5 to 12, but should load the verse where Bible window stops at.

**Comment by tuomas2** [comment]
will be fixed > 336

**Comment by timbze** [comment]
Verified fix in 337
