### ISSUE TITLE
Automatic night mode does not work after changing settings

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#523]
... but does work correctly after app restart. 

Build 335

**Comment by bvahedy** [comment]
In build 338 the behaviour of night more is more unpredictable. 
![Screenshot_20200113-230022_And Bible](https://user-images.githubusercontent.com/46405809/72321822-b8e18c80-3659-11ea-80b3-33e5225f86a2.jpg)

**Comment by tuomas2** [comment]
Will be fixed in build >338

**Comment by bvahedy** [comment]
Verified fixed in build 340.
