### ISSUE TITLE
Navigation bar icons white (on white) in Settings

### ISSUE THREAD

**Issue by ericjding** [AndBible/and-bible#524]
In version 3.2.336#224a1f6c on Android 8.0 on my Sony Xperia X Compact, the navigation bar icons are white (on a white background) in the Settings window. This is not affected by the navbar icon colors in the main text window, which are correct: dark gray on white in regular/daytime mode, and white on black in night mode. Screenshot below:

![Screenshot_20200112-194223](https://user-images.githubusercontent.com/10482921/72219183-c6bde180-3575-11ea-9026-19f1d43c9f8d.png)

**Comment by timbze** [comment]
Does not reproduce on my LG G6 Android 8.0

**Comment by bvahedy** [comment]
Yes, I noticed that on my Note 8 also. It's only in the Setting's window.

**Comment by tuomas2** [comment]
Fixed in master branch (next beta build will have this)

**Comment by bvahedy** [comment]
Verified fixed in build 342-beta.
