### ISSUE TITLE
Unmaximizing non-synchronized window causes white windows

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#529]
**Bug was found on And Bible version**
build 337

**To Reproduce**
1. Create 2 or more windows
2. Switch off synchronization of first window
3. Maximize first window
4. Close app and start again (full restart of app needed)
5. Unmaximize window
6. Second (and others) windows are white.

**Expected behavior**

6. Second and other windows show their content as before step 3.

**Comment by tuomas2** [comment]
Will be fixed > 337

**Comment by bvahedy** [comment]
Do you mean this will be fixed in 338 and above? Because it's still happening in build 337.

**Comment by tuomas2** [comment]
I mean that it is fixed in version numbers that are greater than 337, i.e. this time 338 is next. I'm writing > 337 because sometimes I'm not sure if next will be 337.1 or 338 (depends on if I publish release in Play or not).

**Comment by bvahedy** [comment]
Verified fixed in build 340
