### ISSUE TITLE
Commentary page does not return to previous offset

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#532]
**Bug was found on And Bible version**
Build 339

**To Reproduce**
1. Open commentary
2. Scroll down some content
3. Close app
4. Open app again. Commentary opens, but at the beginning of the document

**Expected behavior**
Commentary should open in the last scrolled position

**Comment by tuomas2** [comment]
Also when returning back in history to commentary page, page offset is not restored correctly.

**Comment by tuomas2** [comment]
Will be fixed in > 339

**Comment by tuomas2** [comment]
when returnging back in history was not fixed yet.

**Comment by tuomas2** [comment]
Still one more.

1. Have 2 windows maximized, second with un-synced commentary that is scrolled down somewhat, night mode on.
2. Go to first window. 
3. Close app
4. Open app again
5. Switch off night mode
6. Go to other window
-> offset is zero
Expected: it should be still scrolled down like in step 1.

**Comment by tuomas2** [comment]
Will be fixed in > 339

**Comment by bvahedy** [comment]
Verified fixed in build 340
