### ISSUE TITLE
Bookmark color doesn't appear when speak bookmark is on a verse... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#535]
When a verse contains a speak bookmark (the red ear icon) setting a bookmark on a verse doesn't show the default bookmark color until the speak bookmark is removed from that verse.
To duplicate:
1) Set the default bookmark color to yellow.
2) set speak automatic bookmarking. (From the speak setting menu)
3) speak a verse and stop the speak.
4) tap and hold on the verse to select it.
5) from the top menu tap on the bookmark icon to color the verse.

What happens: 
the verse is not colored with the default bookmark color due to an ear icon.

Expected result:
Regardless of a speak bookmark on a verse the verse should show the bookmark color.

**Comment by tuomas2** [comment]
Default bookmark color is shown if the bookmark is not assigned to any label (group). 
Now it is assigned to Speak group. 

With the current implementation, this is not possible to be fixed neatly. One solution would be to create real 'default group' that will be assigned really to each bookmark by default.

I think this will be solved by #111 one way or another. Closing.
