### ISSUE TITLE
Sync issue in maximized mode

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#536]
**Bug was found on And Bible version**
Build 339

**To Reproduce**
1. Create 3 bible windows. first sync, second non-sync, third sync
2. Maximize 1st window
3. Scroll down
4. Go to 2nd window
5. Go to 3rd window
 -> window is not in sync with 1st window

**Expected behavior**
 -> Window is in sync with 1st window

**Comment by bvahedy** [comment]
Which two windows are non sync?
If it's the bottom two, then when you tap on them they should not sync, I must be missing something.

**Comment by tuomas2** [comment]
clarified description. 3 windows total, first sync, second non-sync, third sync.

**Comment by bvahedy** [comment]
Ok, I can duplicate the issue.

**Comment by tuomas2** [comment]
Will be fixed in next beta release (>340)

**Comment by bvahedy** [comment]
In build 342-beta, Upon restoring the first window, the third window is not syncing with the first window.
I'm reopening this ticket.

**Comment by tuomas2** [comment]
Tested and can't reproduce. If you can reproduce, logcat (via Main Menu -> Report bug) might be helpful.

**Comment by bvahedy** [comment]
It's now working in build 352 beta.

**Comment by tuomas2** [comment]
Okay, closing now until it is found again.. :-P
