### ISSUE TITLE
Selecting words in commentary/general text fails

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#537]
**Bug was found on And Bible version**
Build 339

**To Reproduce**
1. Open application
2. Change to commentary document (such as Gill)
3. Long-press some word (which is not a link)
4. From popup-menu click "Translate"
  -> Whole document is selected and view is scrolled to the top
       Expected: Google translate is opened and word translation is displayed.
**Expected behavior**

**Comment by tuomas2** [comment]
This appears to be fixed when fixing #532, thus will be fixed in > 339.

**Comment by bvahedy** [comment]
Verified fixed in build 340.
