### ISSUE TITLE
The introductions of the bible books are not displayed

### ISSUE THREAD

**Issue by LAfricain** [AndBible/and-bible#545]
**Describe the bug**
The introduction of the bible books are not displayed. Exemple KonVb and LinVb modules. The intro are before the chapter 1 of most of the books.

**Bug was found on And Bible version**
Version 3.1.319.4-beta

**To Reproduce**
1. Go to 'KonVb module.'
2. Click on 'Gn 1'
3. Scroll down
4. See error (no intro)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S6]
 - OS: [e.g. Android]
 - Version [e.g. 8.0]

**Additional context**

**Comment by tuomas2** [comment]
I could not find KonVb module, but with LinVb module, should there be intro?

**Comment by LAfricain** [comment]
Correct, the module change name, now it's ktuvb

**Comment by tuomas2** [comment]
Will be fixed in build 367

**Comment by tuomas2** [comment]
Implemented such that intros are shown if non-canonical titles are shown. Later we could add sepearate option for this, if needed.
