### ISSUE TITLE
Search in Vandyke does not work

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#547]
I CAN NOT MAKE SEARCH FOR ANY WORD, IN ARABIC TRANSLATION VANDYKE. IT ALWAYS TELLS ME THAT NO ITEMS TO DISPLAY. 

Device info:
And Bible version: 3.2.340#31297c25 (built 20/01/20 22:13:48)
Android version: 9
Android SDK version: 28
Manufacturer: HUAWEI
Model: FLA-LX1

SD card Mb free: 13467

Used heap memory in Mb: 5
Max heap memory in Mb: 384

(logcat is available)

**Comment by tuomas2** [comment]
Tried but could not reproduce this.

**Comment by bvahedy** [comment]
Unable to duplicate also. Perhaps the user needs to do a fresh install.

**Comment by tuomas2** [comment]
User reported that re-installing helped.
