### ISSUE TITLE
Allow backup and restore of reading plan progress

### ISSUE THREAD

**Issue by abramovkg** [AndBible/and-bible#55]
When moving to a new phone, I can copy all of the modules from the Android/data folder, and can also restore my notes and bookmarks, but I am not able to restore my reading plan progress. It would be very helpful if the built-in backup option would backup the reading plan progress as well. Thank you

**Comment by timbze** [comment]
I would be interested to try and implement this. I see that the bookmarks and notes are just backed up and restored via the DB file. 
I'm not sure what would be the best way to backup the reading plan progress. My idea is that we can do 1 out of 2 things, either
1. Add another text file with same name as DB file name + suffix, and add the reading plan info there, or
2. Make a way to add the reading plan info to the DB before backing it up

Any input is appreciated.

**Comment by timbze** [comment]
I will not be working on this too quick, as I have other things that are keeping me busy too, but probably within a few weeks.

The basic of it is the current day you're reading on is stored in SharedPreferences as a serialized string to store which chapters from this day are read and which ones are not. I didn't look into all the details of how it is being done, but I know that it does not store for previous days. The app does not let you progress till the day is complete, so then it knows that all previous days are complete, therefore no extra storage needed for previous days.

I think it is a good idea to just bundle it into DB. 

Since the option is there to use one of the bundled reading plans or add your own customized plan, I would have to figure out how to store which plans are being used, and the progress for each. And make sure that the customized plans also would be available after the restore. But it shouldn't be too much work.

**Comment by tuomas2** [comment]
Actually it would be nice if shared preferences were persisted into that database too. Not sure if it is easily done, but might be.

**Comment by timbze** [comment]
After taking some time to think of this and other reading plan features in the requests (and in my head :) ), it seems to me that there is a significant amount of work that could be done on the reading plans, and it's probably the easiest to do quite a bit of it at the same time.
1. For this request #55, my idea is to add 2 db tables to store the info, and not store anything from the reading plans in shared prefs.
My idea is to store in table 1 (some name like readingplan_metainfo) these columns (ID, PlanName (which would be the name in use now), ShortDescription (maybe 30 char desc that would show in reading plan list), ShortCode (6 chars max, that would be shown on left, 3 chars on top and 3 on bottom), DateStart, DaysInPlan, CurrentDay)
Table 2 (some name like readingplan_dayinfo) with these columns (readingplan_metainfoID, DayNumber, PlanChapters (which would show e.g. Matt.1,Mark.1,Luke.1,John.1), DaysRead (String of bits to show which chapters in the day are already read))
This would require some UX changes (To edit plan descriptions, and start date, and I think the reading plan main screen and also the 3-dot menu on top right need some improvements), we can discuss those further but I would first like to hear back if you @tuomas2 or others can give me input on if I'm almost on the right path. Also, if this is a good place to discuss these details?

In the open issues about reading plans we also have #180, which could be done after this. And we have #50, which I think goes right together with my plans here. And your comment on shared prefs to db could also be done afterward.

Looking forward to further discussion, and other's input on my ideas here.

**Comment by tuomas2** [comment]
Sounds good to me @timbze

**Comment by timbze** [comment]
In v312 (not in beta yet) those who have Android 6.0+ can enable Google automatic backup, and also have the option Automatic restore set to "On", then on app reinstall from same account should get reading plan progress, notes, and bookmarks automatically restored.

**Comment by tuomas2** [comment]
Implemented in build 319.0

**Comment by bvahedy** [comment]
Is this back up done automatically  or does the user has to manually back
up and restore the database. If so which directory is the backup file
stored in?

**Comment by tuomas2** [comment]
Backup file is the same .db file that is used for bookmarks.

**Comment by bvahedy** [comment]
I started a reading plan and did a backed up, then I uninstalled and reinstalled installed AndBibl. I then restored the notes and bookmarks. But when I looked at the reading plan non had been started.
Can someone else try this and see if it works for them.

**Comment by timbze** [comment]
@bvahedy I should have given a bit more detail, but the only thing that is not backed up is which was your current reading plan. Once you select the plan you were on, the progress should be there. The plan start date should be restored, along with the reading day you were on, and the chapters you had already read.

**Comment by bvahedy** [comment]
So your current reading plan is not backed up?
If not can you give an example of a case where a plan is backed up. Thx!

Ben

**Comment by timbze** [comment]
And Bible stores which plan you have last been reading (what I called the current reading plan)
When you restore a backup, And Bible does not know which is the plan you have last been using, so you have to select it. When you select the plan, your progress in the plan will be there.

**Comment by timbze** [comment]
All the plan progress is backed up. Only which plan you were last on is not backed up, and that's why when you go into reading plans the first time after a re-install, it asks you which plan you want to open. As you open it, it should be exactly as it was when backed up.

**Comment by bvahedy** [comment]
Does it do this for self install plans like the one you gave me?
I tried it with that and it starts with the current date. Can you test
that?

**Comment by timbze** [comment]
The date-based plans will always load today's date by default. That's how
those are supposed to work. In that type of plan, it will have stored which
chapters you have read in the past.

**Comment by bvahedy** [comment]
Ok, I'll test it at next re-install. Thx!

**Comment by bvahedy** [comment]
Verified this feature working in build 319.4
