### ISSUE TITLE
New bookmark and bookmark labels

### ISSUE THREAD

**Issue by mmm4m5m** [AndBible/and-bible#555]
I would like more easy way to create new bookmark and assign a label to it.

**Is your feature request related to a problem? Please describe.**
1. I select a verse and "Bookmark labels" is not available.
2. I tap "bookmark" button to add bookmark and screen is refreshed - the selection is lost.
3. I select the verse again and here is "Bookmark labels". Now I am able to assign a label to my new bookmark.

**Describe the solution you'd like**
1. "Bookmark labels" menu could be visible always

2.1. Under "Bookmark labels", I would like sub menu with labels plus "Manage bookmark labels" (which will open "Bookmark labels" screen). 

2.2. Alternatively, long press the bookmark button could show popup menu with labels. 
Right now, long press will show hint/description - "Add bookmark". The popup menu could include this hint/description. 

3. Probably the menu must show only the top 5-10 most recently used bookmark labels. 
Example, if you start learning a new subject, then for your first bookmark you go to "Bookmark labels" screen and add a new label. For your next bookmark you will be able to use the bookmarks menu.

There could be different and better ways for this.

**Comment by tuomas2** [comment]
Hi @mmm4m5m thank you for comments and ideas! Just curious, are you developer? If you are, please let me know if you would like to contribute. I'm willing to give some help to get you started if you are.

**Comment by mmm4m5m** [comment]
I find annoying the "ok" button in "bookmark labels". The expectation is all changes to apply immediately. Also "back" button does not show any warning - "do you want to cancel. there are unsaved changes".

**Comment by mmm4m5m** [comment]
@tuomas2 I am not java developer. My java experience is small and not professional. My recent android efforts ended with - "I need 64bit debian to use android studio" (my debian is 32bit).
I would be glad to help you. Is there "private message" in github? Do you use IRC or similar?

**Comment by mmm4m5m** [comment]
@tuomas2 Now I have 64bit debian, android-studio and bible sources :)

**Comment by tuomas2** [comment]
Hi! Sounds good! Could you send me email to tuomas.airaksinen@gmail.com!

**Comment by kesarsauce** [comment]
> Hi @mmm4m5m thank you for comments and ideas! Just curious, are you developer? If you are, please let me know if you would like to contribute. I'm willing to give some help to get you started if you are.

Hello I would like to contribute, but I don't know where to start.

**Comment by tuomas2** [comment]
> > Hi @mmm4m5m thank you for comments and ideas! Just curious, are you developer? If you are, please let me know if you would like to contribute. I'm willing to give some help to get you started if you are.
> 
> Hello I would like to contribute, but I don't know where to start.

hi, please email me, tell me your background as a developer and i will help you get started. help.andbible@gmail.com

**Comment by tuomas2** [comment]
Current implementation should address this better.
