### ISSUE TITLE
Pin mode for windows

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#565]
- Pinned windows stay on screen
- There can be only one unpinned window in addition

- When no pinned window, corresponds with old "maximized mode"
- When "auto-pin windows" option set, corresponds with old "non-maximized / normal mode"

**Comment by tuomas2** [comment]
Will be implemented in next beta > 340

**Comment by bvahedy** [comment]
This is a bit buggy.
With thtee windows all pinned, the third window line separator froze and I could not expand it until I minimized the second window.
I'll reopen for now.

**Comment by tuomas2** [comment]
I like it more so that feature ticket is closed as soon as feature is implemented. After that, there should be created new bug tickets that refer the feature ticket (moved to #567).
