### ISSUE TITLE
Lower part of the bible screen (where buttons are) does not respond to touches

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#567]
With three windows all pinned, the third window line separator froze and I could not expand it until I minimized the second window.

_Originally posted by @bvahedy in https://github.com/AndBible/and-bible/issues/565#issuecomment-596911798_

**Comment by tuomas2** [comment]
Can't reproduce. Can you specify more details @bvahedy

**Comment by bvahedy** [comment]
If the window boundary of the third window is pushed all the way down to the bottom of the screen. Then the only way to move it up is to minimize the second window.

**Comment by tuomas2** [comment]
Then you are actually experiencing #509?

**Comment by bvahedy** [comment]
No, I can actually see the bar but I can't move it.

**Comment by tuomas2** [comment]
okay, now I can reproduce

**Comment by tuomas2** [comment]
I think this bug issue (via email) has the same issue
> When I slide from bootom of the screen to top, I noticed that the lower part of screen (picture) is not sensibile to touch.

**Comment by bvahedy** [comment]
Yes, it seems the portion of the bottom of the screen where the window
income are have been blocked from touch.

**Comment by tuomas2** [comment]
Will be fixed in build 359.

**Comment by bvahedy** [comment]
Verified fixed in build 359 beta.
