### ISSUE TITLE
Translation context for And Bible version 3.3

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#573]
# Call for translators for upcoming And Bible release 3.3 release
_[message via transifex]_
New And Bible release 3.3 is planned for Wednesday 20th May, about one month from the time of writing this (26th April). There are still quite many open bugs to be fixed, but featurewise, I believe we have now reached the status that there should not be coming any more new features that require translations. So I think it is good time to start updating translations. 

There are quite many cool new things in this release that require translation work. To see context for the new texts, please take a look at screenshots on translation context issue, see https://github.com/AndBible/and-bible/issues/573 . I have also tried to add context help in Transifex for cases that are not obvious.

App name is about to change, please see more info about that in Translation Context issue too.

As usually, after official release, there will be also bugfix release(s), at least one that comes approximately one week after the release, which gives also opportunity to fix translation issues, if they were not noticed during beta testing. 

Please let me know if there are difficulties in translating anything. I will add more context texts in Transifex if needed.

Thank you for the valuable work you are doing!

Best regards,
Tuomas
And Bible Lead Developer
_[/message via transifex]_

## App name change

App name will also change in this release. I have wanted to change the name mainly so that it would be translatable to local languages, which should help non-english-speaking people to easier find it from Google Play. Similar renaming to more localizable names has been seen in other bible applications too. There are three versions of the name:

 - short version "Bible Study"
 - medium-length version "Bible Study (And Bible)"
 - long version: "Bible Study app, by And Bible Open Source Project"

In Android launcher and app drawer, we will call it briefly by short version. This could be translated also as "Bible" if "Bible Study" sounds cumbersome in your language. I wanted to add word "Study" to indicate to users that this is powerful bible study tool, not just bible reading app. 

Middle-length version is used in several places within the app, where long version would be too long to be practical, but where short version would be too generic. 

In Play Store, we will call it with the longest version. Inside app, this should be translated as accurately as possible. In Play Store (title.txt resource), maximum length is 50 characters. If all does not fit in your language, feel free to consider something of the following:

 - Bible Study, by And Bible Open Source Project
 - Bible, by And Bible Open Source Project
 - Bible Study (And Bible) Open Source Project
 - Bible Study (And Bible)
 - ... feel free to ask me via transifex message / email / github comment if you have idea but you hesitate.

Nevertheless, name "And Bible" is not going anywhere. It is still used within the app in the long version of the app, and in website address etc. It will remain nickname for the app.

## Google Play description text

I am planning to rewrite Google Play description text probably after this release. So if you haven't yet updated Google Play description text translation until now, it might be wiser to wait until the rewrite.

# Context

Just in case you have missed earlier updates, translator context for earlier versions are as follows:
 - #472 for version 3.2
 - #159 for version 2.13

# Screenshots

## Options menu contents have changed
![Screenshot_1587663575](https://user-images.githubusercontent.com/5811789/80131265-a359f800-85a2-11ea-9c8e-b56898c5cbb3.png)

## Application-wide settings are now called "Application Preferences"

![Screenshot_1587663656](https://user-images.githubusercontent.com/5811789/80131388-d56b5a00-85a2-11ea-827a-8e9b94eaa3e7.png)

## Workspaces selector has been improved. Workspace items have 3-dot options menu.

![Screenshot_1583854745](https://user-images.githubusercontent.com/5811789/76330384-71dce400-62f6-11ea-9df2-2731a725d491.png)

## Workspace and Windows settings can be customized. Dialog looks like this:

![Screenshot_1583854748](https://user-images.githubusercontent.com/5811789/76330388-730e1100-62f6-11ea-9319-2ba8d88f7745.png)
![Screenshot_1583854753](https://user-images.githubusercontent.com/5811789/76330389-73a6a780-62f6-11ea-9185-4c1c81f2cd73.png)
![Screenshot_1583854757](https://user-images.githubusercontent.com/5811789/76330391-743f3e00-62f6-11ea-8953-bb63c98366de.png)
![Screenshot_1583854759](https://user-images.githubusercontent.com/5811789/76330393-74d7d480-62f6-11ea-9262-65b8b45f0357.png)

## Colors customization dialog looks like this. 

![Screenshot_1583854765](https://user-images.githubusercontent.com/5811789/76330395-75706b00-62f6-11ea-8b8f-1259dcb987cc.png)

## Font preferences customization dialog looks like this. 

![Screenshot_1583854772](https://user-images.githubusercontent.com/5811789/76330396-76090180-62f6-11ea-8065-e78ec6e234c9.png)

## Margin size preferences customization dialog looks like this. 

![Screenshot_1587822605](https://user-images.githubusercontent.com/5811789/80281584-de7c3880-8714-11ea-8a4a-9266ab876a3b.png)

## Line spacing customization dialog looks like this. 

![Screenshot_1583854783](https://user-images.githubusercontent.com/5811789/76330401-773a2e80-62f6-11ea-89ef-89d7f4ab42c4.png)

## Workspace settings can be copied from one to another

![Screenshot_1587670703](https://user-images.githubusercontent.com/5811789/80142116-503c7100-85b3-11ea-9b40-05b3c19cbce9.png)

![Screenshot_1587670708](https://user-images.githubusercontent.com/5811789/80142113-4f0b4400-85b3-11ea-8dc1-57dc9d7b9493.png)

## In main menu, settings has been changed to "Application Preferences"

![Screenshot_1583854815](https://user-images.githubusercontent.com/5811789/76330403-77d2c500-62f6-11ea-8650-4ddaac71chttps://github.com/AndBible/and-bible/issues/5736e7.png)

## If window pinning is enabled, user can pin windows from windows menu. If pinning is enabled, pinned windows stay open and only 1 unpinned window can be opened in addition. 

![Screenshot_1583856044](https://user-images.githubusercontent.com/5811789/76332520-26780500-62f9-11ea-953f-c0c61a37f51b.png)

## When clicking "Move window" from window menu, new popup will open, which allows moving window to new position:

![Screenshot_1583856226](https://user-images.githubusercontent.com/5811789/76332959-a2724d00-62f9-11ea-959e-b36f6d32c46c.png)

## There are new items in Help screen documenting workspaces and some hidden shortcuts:

![Screenshot_1583857101](https://user-images.githubusercontent.com/5811789/76334394-abfcb480-62fb-11ea-8edf-d9058d8320d7.png)

## Download screen has been improved

![Screenshot_1587663849](https://user-images.githubusercontent.com/5811789/80131671-401c9580-85a3-11ea-988c-c67e47a96bfe.png)

## If there are errors in download, they are reported as follows

![Screenshot_1587822441](https://user-images.githubusercontent.com/5811789/80281552-95c47f80-8714-11ea-90f5-39427a30b8bc.png)

## New feature: backup documents 

![Screenshot_1587663994](https://user-images.githubusercontent.com/5811789/80131957-ae615800-85a3-11ea-9b33-c7e25e3e767e.png)

![Screenshot_1587663997](https://user-images.githubusercontent.com/5811789/80132002-b9b48380-85a3-11ea-89bf-489ab75ea7ea.png)

![Screenshot_1587664019](https://user-images.githubusercontent.com/5811789/80132015-bde0a100-85a3-11ea-8b16-8c000ff91eb4.png)

**Comment by alerque** [comment]
I just started working through some of the new strings translating into Turkish and one things that's immediately evident is there seems to be a _lot_ of duplication in strings. There are lots of cases of "string" and "string..." where there seems to be no difference except the ellipsis on the end. Also there are other straight up duplicates with no differences at all and it is not clear whether the context would ever indicate a difference in translation.

Are these intentional or some kind of oversight? Is there a transition between old and new strings going on? It's a lot of extra work on translators this way.

**Comment by tuomas2** [comment]
If there is "String" and "String...", I could of course add ellipsis programmatically, but couldn't it be that in right-to-left languages, ellipsis would appear in wrong place?

**Comment by alerque** [comment]
@tuomas2 Yes, but that makes me wonder what where in the UI these variants actually show up that a version with and without the elipsis is actually meaningful and whether the UI at those points would account for RTL differences anyway. E.g. is the alignment flipped? Are there other context clues like button design that would be better suited as indicators than different text translations?

**Comment by tuomas2** [comment]
Ellipsis is normally appended in menu items if clicking menu item opens a dialog.

**Comment by alerque** [comment]
@tuomas2 Does the UI toolkit not have any comprehension of LTL vs. RTL? Even if concatenating '...' onto the string (which should actually work, but not recommended because ellipsis may not be the right thing to show in all languages) messing it up because it doesn't have BiDi support, just drawing two string objects back to back should work. Still neither of those seem like the right solution, shouldn't the UI widget itself have some indicator of what will happen?

And baring all that even if the ellipsis still ends up being the string to translate, why are there also versions _without_ it?

**Comment by tuomas2** [comment]
> @tuomas2 Does the UI toolkit not have any comprehension of LTL vs. RTL? Even if concatenating '...' onto the string (which should actually work, but not recommended because ellipsis may not be the right thing to show in all languages) messing it up because it doesn't have BiDi support, just drawing two string objects back to back should work. Still neither of those seem like the right solution, shouldn't the UI widget itself have some indicator of what will happen?

I will look for solutions to this next week when I have more time to work on AB. 
 
> And baring all that even if the ellipsis still ends up being the string to translate, why are there also versions _without_ it?

The versions without it are displayed in text display settings dialog (settings titles).

**Comment by tuomas2** [comment]
Ellipsis is found in the following string definitions:

- all_text_options_window_menutitle
- all_text_options_window_menutitle_alone (*)
- move_window 
- extracting_zip_file
- checking_zip_file
- rdg_plan_set_start_date
- share_verse
- backup_modules
- backup_app_database
- restore_app_database
- loading_backup
- restore_modules
- please_wait
- switch_to_workspace (*) 
- workspace_settings 
- copy_workspace_settings

I found two clear duplication in the current strings definitions that are marked with *. Am I mistaken? For 2 cases I don't know if I want to make things more compicated. Because of different contexts, some repetition is needed anyway.

**Comment by tuomas2** [comment]
Updated translation sources and context. Mentioned issues should have been fixed now.

**Comment by tuomas2** [comment]
Announcement via transifex

> Hi,
> 
> Release of And Bible 3.3 has been postponed because there are still some open bugs to be tacked and also because we are still waiting for some translators to finish translations. I'm aiming at releasing within next 2 weeks, as soon as possible.
> 
> Many translations are already now in very good condition, thank you a lot! Translations are very important for this app to get into the hands of common people that don't speak english. Special thanks for new Serbian translator team that finished their work from 0 to 100% in couple of days!
> 
> However, there are still quite a few languages that need work.
> 
> * If your translation work is not yet done, please let me know if you can finish the work within 2 weeks (until June 12).
> * If you can't do it, please let me know when you might have time to do it.
> * Or if you are not planning to continue translating And Bible, let me know also that.
> 
> You can send me private message via transifex or contact me directly via email: help.andbible@gmail.com.
> Please also let me know if something is not clear. I'll try my best to help you.
> 
> As always, translation context with screenshots can be found here: https://github.com/AndBible/and-bible/issues/573
> 
> Best regards,
> Tuomas
