### ISSUE TITLE
"Keep screen on" does not apply to other activities

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#581]
Via email

> 1. I have "Keep screen on"   to ON position.
And this works for me. Phone doesn-t lock after one minute.
BUT when I am reading Bookmarks, my screen locked after 1 minute as the settings are on my Android.

Affects many old versions already.

**Comment by msavli** [comment]
Same behaving in Menu/Settings

**Comment by agrogers** [comment]
I suggest we delay this one to after v3.4 release
