### ISSUE TITLE
Bookmarks view should remember current scroll location

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#582]
2. I have lots of bookmarks. When I am in the middle of them all I tap on one bookmark to ses whole verse. And when I press back buuton on my phone I go to Bookmarks. That's ok. But it is not ok, to put me again on first bookmark. Which bookamrk I was just reading? I have to remember and scroll to it. It should be fine if the back butoon would go back to exact bookmark where i left.
Bookmarks also have labels. It woulb be nice when I press back on my phone to go to exact label and exact bookmar line as I was befere.

**Comment by timbze** [comment]
Almost duplicate of #317

**Comment by tuomas2** [comment]
moved to #317
