### ISSUE TITLE
Bookmarks view should show entire verse (long verses)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#583]
Via email

> 3. I have verses about healing as Bookmarks  I bookmarked them and I read them often.
Some lines in the Bible are extremely long  (some longest are on page https://www.gotquestions.org/longest-verse-in-the-Bible.html)
But available place on screen doesn't show entire verse.
It should be fine if the whole verse can be visible on the screen regardles of longitude of verse..

**Comment by timbze** [comment]
One idea would be to have a ... button on bookmark item to display entire verse. Else click on bookmark item anywhere else and Bible would open to that verse.

I think it would be more user friendly if all bookmark items were consistent in height by default, but a press on ... could show the entire verse.

**Comment by tuomas2** [comment]
This probably is not relevant any more with current implementation.
