### ISSUE TITLE
Search again function / go back if no results 

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#585]
> After i completed a search
> -when it found the verse, it pops up the result in a box, and when clicking on it, it jumps to the page. Nice!
> -when no results found, it says 'close', but i want to search again until i find what i search for. Id like an option to ga back to search instead of canceling the whoke search.

Build 350

**Comment by bvahedy** [comment]
If you hit the back button it will do exactly what you are asking.

**Comment by tuomas2** [comment]
Hmm, that's true.

**Comment by tuomas2** [comment]
Non-issue then...
