### ISSUE TITLE
Use kotlin coroutines for database access

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#587]

**Comment by timbze** [comment]
To consider: https://stackoverflow.com/a/56603632/877453

**Comment by tuomas2** [comment]
> To consider: https://stackoverflow.com/a/56603632/877453

Note that (at least yet) we don't use LiveData.

**Comment by tuomas2** [comment]
Database access can be probably improved in certain cases, but I'll close this for now as this has not caused performance issues currently. Many queries are also super fast and it's ok to do them in main thread.
