### ISSUE TITLE
Fastlane metadata disappeared accidentally

### ISSUE THREAD

**Issue by verdulo** [AndBible/and-bible#589]
EO
Bonvolu realdoni F-Droid-metadatumojn por la internacia lingvo Esperanto forigitajn en la enmeto https://github.com/AndBible/and-bible/commit/784a4fb9f29e89177af25d72c16d59bc1f70efc2.

EN
Please re-add the F-Droid matadata for the international Esperanto language removed in the commit https://github.com/AndBible/and-bible/commit/784a4fb9f29e89177af25d72c16d59bc1f70efc2.

**Comment by tuomas2** [comment]
It was not removed, but moved to es-ES, as fastlane / google play requires. Please correct if I'm wrong.

**Comment by verdulo** [comment]
es-ES estas por hispana (Hispanujo) lingvo, mi parolas pri Esperanto.

es-ES is for Spanish (Spain) language, I speak Esperanto.

**Comment by tuomas2** [comment]
Thank you for the pull request #591 and reporting this. I agree this is valid issue. I will fix it, but it need to be done automatically from Transifex (tx pull), thus I can't accept pull request.

**Comment by tuomas2** [comment]
Fixed in 3c282a3de78c635d1988747bb905fef7cea0fad6

**Comment by verdulo** [comment]
Again not working:
https://github.com/AndBible/and-bible/commit/79cbb2719bb97d6eb6ee167c9698e59ab63931d5

**Comment by tuomas2** [comment]
I'll fix next week
