### ISSUE TITLE
fullstop after tetragrammaton on the left

### ISSUE THREAD

**Issue by michimartini** [AndBible/and-bible#59]
In the bible text "The Scriptures (ISR)" (TS1998) the tetragrammaton (יהוה) is rendered in Hebrew, which is read left to right. If the Name יהוה then ends up at the end of a verse, and thus is followed by a fullstop, that fullstop ends up to the left of the Name. This is not the way it is rendered for example in other SWORD apps (i checked Eloquent and MacSword).
Is this a bug or a feature?
Version of AndBible: 2.6.0
Version of TS1998 module: 1.5

**Comment by mjdenham** [comment]
Which version of android are you using.

Martin

**Comment by michimartini** [comment]
Android version 6.0.1 on an Xperia Compact Z3 - sorry for the omission.

**Comment by tuomas2** [comment]
@mjdenham  or @michimartini can you help me find this module? I could not find it at crosswire repository and don't know now where to look.

**Comment by michimartini** [comment]
I had a look too, it disappeared from the list at crosswire. And the Institute for Scripture Research also does not mention the sword module anymore( https://isr-messianic.org/downloads/free-scriptures-downloads.html). Someone would have to step up and renegotiate distribution by crosswire.org. 
So I suggest you close this bug as it is no longer reproducible since the module is no longer installable.

**Comment by tuomas2** [comment]
Allright. Thanks for information!
