### ISSUE TITLE
Bring back the 'quick switch between documents' option 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#597]
First, andBible is fantastic. Thank you. 

Second, I have missed the ability to simply click the Commentary (or Bible) buttons at the top to move to the next Commentary in the list. Now when I click I need to choose what I want from the drop down list. 

The old method was great because I could very quickly peruse all the commentaries.

The new method has made that process much slower (click, scan list, identify the next item, click). The scan and identify part for me makes the process at least three+ times slower. 

The attached image shows why. I have chosen a commentary that has no entry. In the old version to move to the next commentary I just push the button again. But now I have to work out which commentary is next in the list. But the displayed name in the header and the name in the list is not the same. So I need to remember what the short name is for the current commentary, find where it would be in the list (not so easy because it's been removed from the list) then select the next entry after this. I find I make mistakes in this process by selecting a previous commentary or I skip a commentary or I come to the end of the list I need to remember to go back to the top. All this takes a lot more mental energy than the old method. And often the end result is 'Not found in document' :-) It is that mental energy and clicking energy that bothers me more than the time. 

I used to do it for Bible verses as well to quickly see if any showed notable differences. I don't do that anymore because the effort doesn't justify the reward. I will probably use the Parallel Passages option if I really need it. But that doesn't give quick access to the context which I found helpful. 

I appreciate though that the new method is more intuitive for new users. However the previous long press method to get the list if you wanted it was perfect I thought.

Proposal:
Is it possible to 
1. Bring back the long click on the Commentary (and other) buttons which cycles through the commentaries like the old way did. 
Or 
2. Add an option in settings to configure how the changing takes place - either the new method or the old method. 

Thanks! 
![Screenshot_2020-03-28-09-08-13-301_net bible android activity](https://user-images.githubusercontent.com/13920678/77807506-c2648780-70d3-11ea-867a-4785213ede12.jpg)

**Comment by timbze** [comment]
@agrogers Somewhat of a work-around would be to add multiple windows with different versions as unpinned, and when you select another button from the bottom the window will switch to that version.

I see Tuomas added to 3.3 milestone though so it looks like he has plans to do something with this.

Blessings

**Comment by tuomas2** [comment]
I added milestone so that this will be considered/decided before 3.3.

**Comment by agrogers** [comment]
Interesting suggestion. I might experiment with that. I don't think it will
solve my initial complaint but it is a good idea - there are a few
commentaries I always go to.

Re another possible implementation of the quick switch, maybe a swipe down
action on the Commentary button could change to the next commentary in the
list.

**Comment by tuomas2** [comment]
> Interesting suggestion. I might experiment with that. I don't think it will solve my initial complaint but it is a good idea - there are a few commentaries I always go to. Re another possible implementation of the quick switch, maybe a swipe down action on the Commentary button could change to the next commentary in the list.

Yep suggested workflow is to work with multiple non-pinned windows to do such quick switching. For general use, I believe that bible & commentary buttons are now much more usable than before. 

Closing this.

**Comment by agrogers** [comment]
Yep I agree. Much quicker now to select the document you want. Sometimes
you have to rob Peter to pay Paul.

**Comment by agrogers** [comment]
Back to this one again :-)

Trying to understand who Mat 12:36 "I tell you, on the day of judgment
people will give account for every careless word they speak," applies to
and so really want to look at what every Commentary I have says about it.

It seemed that a possible location for an option is on the window button
that fades. A 'Next document' option would do what I want - quickly get to
whatever the next document is in the list. It would work for commentaries
and bibles.

That pop up menu is getting long though. I think you can remove the top
Create New window button now you have just added the create window button
to the bottom row of buttons (I like it there - good job). So there is
space 😁

**Comment by agrogers** [comment]
Oh, and off topic, I think I prefer the icon for the new window found in
the pop up menu on the fade button more than the new icon in the bottom row
of buttons. I wondered what the 'world' button did initially 😏

**Comment by tuomas2** [comment]
> Back to this one again :-) Trying to understand who Mat 12:36 "I tell you, on the day of judgment people will give account for every careless word they speak," applies toband so really want to look at what every Commentary I have says about it. It seemed that a possible location for an option is on the window button that fades. A 'Next document' option would do what I want - quickly get to whatever the next document is in the list. It would work for commentaries and bibles. That pop up menu is getting long though. I think you can remove the top Create New window button now you have just added the create window button to the bottom row of buttons (I like it there - good job). So there is space 

You can also create copies of window by "new window" from window popup menu, which you can access also by long-clicking window button bar (on the bottom) items. So suggested workflow would be like this:

1. Have pinned bible view, and unpinned commentary view
2. Create new window from commentary view, many times
3. Choose desired commentary for each
4. Switch between (non-pinned) commentaries by clicking window button bar items.

**Comment by agrogers** [comment]
Hi again. I had another thought this morning which I thought was cool. Video attached explaining it. In brief, what do you think of adding new menu options to the window button that allows the user to copy a verse reference and then paste the reference. That way I could copy the reference in one window and paste it to any window of my choice. It's basically just a quick way of selecting a verse.

Hmm, adding two menu options to that popup menu would clutter it up a bit. You already have the long click option and then 'Copy Verse' from the menu. I use that a lot. That handles the copying.

So just need to find a way to to paste the verse reference into a window. It seems intuitive to attach that option to the window button. But another place would be a paste button in the verse selector itself. There is not much space in that selector so that might be hard.

Anyhow, I think this suggestion is better than my previous suggestions 😁 It is more flexible. 

And the video which I can't turn into a link 
https://drive.google.com/file/d/17NOqE4WzDxm5Is9jg7ZAddSJPttLV8x6/view?usp=drivesdk

**Comment by timbze** [comment]
Maybe it would be an option to implement a "double-tap" to quick-switch, if that would be possible.
Edit: From some checking on how the menu operates etc, I don't think that double tap would be a feasible solution at all

**Comment by dwaynedauzat** [comment]
> 
> 
> First, andBible is fantastic. Thank you.
> 
> Second, I have missed the ability to simply click the Commentary (or Bible) buttons at the top to move to the next Commentary in the list. Now when I click I need to choose what I want from the drop down list.
> 
> The old method was great because I could very quickly peruse all the commentaries.
> 
> The new method has made that process much slower (click, scan list, identify the next item, click). The scan and identify part for me makes the process at least three+ times slower.
> 
> The attached image shows why. I have chosen a commentary that has no entry. In the old version to move to the next commentary I just push the button again. But now I have to work out which commentary is next in the list. But the displayed name in the header and the name in the list is not the same. So I need to remember what the short name is for the current commentary, find where it would be in the list (not so easy because it's been removed from the list) then select the next entry after this. I find I make mistakes in this process by selecting a previous commentary or I skip a commentary or I come to the end of the list I need to remember to go back to the top. All this takes a lot more mental energy than the old method. And often the end result is 'Not found in document' :-) It is that mental energy and clicking energy that bothers me more than the time.
> 
> I used to do it for Bible verses as well to quickly see if any showed notable differences. I don't do that anymore because the effort doesn't justify the reward. I will probably use the Parallel Passages option if I really need it. But that doesn't give quick access to the context which I found helpful.
> 
> I appreciate though that the new method is more intuitive for new users. However the previous long press method to get the list if you wanted it was perfect I thought.
> 
> Proposal:
> Is it possible to
> 
>     1. Bring back the long click on the Commentary (and other) buttons which cycles through the commentaries like the old way did.
>        Or
> 
>     2. Add an option in settings to configure how the changing takes place - either the new method or the old method.
> 
> 
> Thanks!

Hello.  I just want to say that everything agrogers has said in his first post above is exactly how I feel.  I love andBible and have used it for years.  I joined GitHub solely to respond to this issue.

I'm not sure why the feature has changed or was taken away but it was perfect beforehand.  I propose to simply bring back the previous functionality of the buttons so that they work as follows:

1. Single tap to quickly switch to the next document and long press to display the list.
or
2. Include an option in the settings to select how the buttons work (single tap to quickly switch documents or single tap to display the list).

This is basically what agrogers has already suggested.  I just wanted to reiterate it because it has made a big change in the way I use andBible, in a negative way.

I have tried the new pinned windows feature.  It is a neat functionality but, the way that I use andBible, it is not something that I will be using.

Thank you for a wonderful app and for taking the time to hear my issue.

**Comment by timbze** [comment]
In my opinion the current behavior is good for default.

I think it may be a good idea to add "swipe down" on button to do "quick switching" (@agrogers idea above).

And to take it one step further, there could be a setting to swap button press and swipe down. E.g. to press for quick switch, and swipe down for document list menu, or vice versa which can be configured with a setting.

**Comment by timbze** [comment]
Developer info:
Idea to change came partially from #578
First change away from switching documents with single click: fb5d2efc - March 10, 2020
Another change: 225a550c - Apr 2, 2020
Further change for long press: 1e8f1908 - Apr 10, 2020
