### ISSUE TITLE
Highlight active window better

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#598]
# Use the background color feature to highlight the selected panel 

I like the new color options and the background noise. Good job. 

My problem is that I often don't realise which window/panel is the active one. I think the commentary panel is active when it's the Bible panel. So I go and change to the next commentary only to lose my bible and now have two commentaries. 

I know there are some very subtle differences to the buttons in the corners. 

But I think what I would like is to have the option to set the background color of the active panel and the background color of the inactive panels. If my active panel was yellow and the others were gray (see pic) then my mistakes would be solved. 

I appreciate that such a change is tricky because at present colors are tied to panels not common across all panels. My secondary panels come and go a lot so I would never take the time to change the color of those as the selection is not remembered.

**Comment by agrogers** [comment]
Example screenshot. 
![Screenshot_2020-03-28-09-49-47-936_net bible android activity](https://user-images.githubusercontent.com/13920678/77809057-c85d6700-70d9-11ea-8e39-eedf1564f9d5.jpg)

**Comment by tuomas2** [comment]
Background color is configurable so I wouldn't like to mess up with it...though maybe some darkening/lightening effect might work and can be considered. But changed button highlight color from gray to blue, would it make it more clear? Is it still 'beautiful'?

![Screenshot_1589460409](https://user-images.githubusercontent.com/5811789/81936211-8ee5aa00-95fa-11ea-9609-5309e0f01ace.png)

**Comment by agrogers** [comment]
It's a little bit ugly :) But a good solution to the problem. Actually, it
might look better at normal size - the picture I am looking at is about
1300 pixels wide on my screen :)

Maybe one problem with that approach is that the buttons automatically fade
- would the highlight outline still be visible on the faded button? If it
is visible at full strength then i think that might be a bit ugly.

Changing the background color of the panel is a lot more work. Plus only
some people would find the option and use it so not much bang for buck.
This approach will work for all.

What if you changed the whole color of the button - maybe to blue.  Then it
can fade and as long as the tint is maintained it might still be visible.
It is when it is faded that it is needed most - that is after reading for a
bit i can forget which panel i last clicked on.

thanks!

**Comment by agrogers** [comment]
Just got the update and it looks great. The blue line isn't ugly at all to
my eye now.

Also, although the blue highlight around the window's own button is almost
indistinguishable when the button has faded, it doesn't matter that much
because on the phone it seems easy enough to glance at that bottom row of
buttons (assuming they are expanded) and see the highlight there.

Perhaps one slight modification might be to make the blue highlight line
around the button that fades thicker - maybe double or triple. That would
make it more visible but not too much more intrusive when faded. But that
could be a bit ugly.

I will try and report back in a few weeks if my original usage problem has
been solved by this change. Its looking positive. Thanks again!

**Comment by tuomas2** [comment]
This is easy to implement on bibleview-js side now. Just tell window when it's active / inactive and add necessary decorations for active window.

**Comment by tuomas2** [comment]
Implemented in develop

**Comment by timbze** [comment]
Active window corner indicators added in aefe259f
