### ISSUE TITLE
add HW keyboard navigation

### ISSUE THREAD

**Issue by ildar** [AndBible/and-bible#60]
I use app on my notebook (with Remix OS).
I miss hardware keyboard navigation shortcuts, e.g. next/prev chapter. Could you please add it?

**Comment by timbze** [comment]
Hardware buttons are not so common now, but some book reader apps also use volume up/down for prev/next page. It might be good to add that option in settings (would need to be for next verse or maybe even better to just do certain number of lines (smooth scroll preferrably)).

**Comment by tuomas2** [comment]
I'm also kind of missing some shortcut keys when using tablet with bluetooth keyboard.

**Comment by tuomas2** [comment]
> Hi support team, 
> How could I request a consideration to add a feature to AB?   For those still using the legacy way of a computer with a keyboard (like Chromebook Spin), it seems very easy to access menu items by HOT KEY combinations instead of touch - 

I agree that keyboard navigation would be nice. I'm using bluetooth keyboard with my tablet often to write notes.  

But we should document keys somewhere. And perhaps keys should be configurable. And what should these keys (by default) be?

**Comment by timbze** [comment]
Closing in favor of #1878 and/or #2622
