### ISSUE TITLE
Fonts are no longer loaded from jsword/fonts directory.. 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#608]
In build 3.2.359 beta fonts are no longer loaded from the jsword/fonts directory on the device. For Greek and Hebrew text fonts in this library was used to display the Bible text.

Also it would be nice if AndBible could look for font files in the following location for alternative text options for each window:
Android\Data\net.bible.android.activity\files\fonts
Currently only a limited list of system fonts are displayed in the text option menu for fonts.

**Comment by tuomas2** [comment]
Rather than having custom locations for fonts, I think it would be better to add UI way to install fonts for And Bible, see #558. 

But I'll try to figure out what has broken current system.

**Comment by tuomas2** [comment]
Will be fixed in 360
