### ISSUE TITLE
After copying a workspace as new and deleting it synchronization fails... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#610]
Using 359 build:
1. Create three windows with all windows synchronized.
2. Then copy this workspace "As new" from the workspace menu.
3. Save the workspace and scroll up a few verses in the new copy.
4. Switch to the original workspace you should still have synchronization.
5. From the workspace menu, delete the copy of the workspace and save the settings.
6. Go back to the original workspace. 
-> if you scroll up in any of the windows, there is no synchronization.

But if you swipe on the middle window to go to the next chapter, synchronization will return.

**Comment by tuomas2** [comment]
Also:

1. Create three windows with all windows synchronized.
2. Then copy this workspace "As new" from the workspace menu.
3. Press "Save" button to return to workspace

-> if you scroll up in any of the windows, there is no synchronization.

**Comment by tuomas2** [comment]
Will be fixed in build 368

**Comment by bvahedy** [comment]
Verified fix in build 369 beta.
