### ISSUE TITLE
An option to set the verse reference to the verse shown in the 'special window' 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#613]
I often want to start reading the context of the verse shown in the special window which I get to from the TSK (my favourite :) 

But alas there is no easy way that I know about. I have to select the top bible window and manually locate the verse in the verse chooser. 

It would be great to have an option in the popup menu attached to the X button that allowed sending the verse reference direct to a bible window. For me I always want it to go to the top most window but I do most of my study on the phone. I guess it's possible that there is no bible window open at all. 

Maybe it would be good for that 'special window' to magically turn into a real window. Then I can move it wherever I want. That could be perfect.

![IMG_20200414_072040](https://user-images.githubusercontent.com/13920678/79163058-a9710b80-7e21-11ea-8b42-c6f6463a4e7c.jpg)

**Comment by tuomas2** [comment]
How about 
- long click link you want to investigate
- select "Open in a new window" from context menu that appears

Then the link opens in normal window instead of special window.

**Comment by agrogers** [comment]
Do you mean this menu?
![Screenshot_2020-04-14-18-01-32-547_net bible android activity](https://user-images.githubusercontent.com/13920678/79200981-a9e9c080-7e7a-11ea-8019-69fe8e16203f.jpg)
That would work fine.

However this menu feels to me like it might be more intuitive. 
![IMG_20200414_180424](https://user-images.githubusercontent.com/13920678/79201051-ca197f80-7e7a-11ea-8f82-933515f6c3f1.jpg)

But either would be great.

**Comment by tuomas2** [comment]
No.

1. Long click link (for example "Genesis 32:26") in the latest screenshot
2. Select "Open in a new window" from context menu that appears after long-clicking.

Then the link opens in normal window instead of special window.

**Comment by agrogers** [comment]
Oh, I didn't know that was possible! That works fine for my needs. Thanks
for the tip.

**Comment by agrogers** [comment]
Hi again (can we comment on Closed tickets i wonder?)

I have been using the long click option for a bit now but it is not really working as easily as i thought it could have.  What i think could just be a two click action is quite a bit longer and messier. I made a [short video here ](https://drive.google.com/file/d/15fi2vrMCOmSPNPiKy7CDHCidap-rjFJY/view) to try and show how my process goes.

So, i still think it would be a great feature to be able to set the first displayed window's verse reference to the active verse in the 'special window' where links are shown.

This would make it really easy to follow the links trail from verse to verse. And it would also allow us to go backward through that same trail.

Thanks.
