### ISSUE TITLE
Misleading message when backing up database to phone storage... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#618]
When backing up the database to phone storage the message should not say restored rather backed up, see screenshot. 

![Screenshot_20200418-202937_And Bible](https://user-images.githubusercontent.com/46405809/79678827-387c7b80-81b4-11ea-8605-20a9a123d210.jpg)

**Comment by tuomas2** [comment]
Will be fixed in build 363

**Comment by bvahedy** [comment]
Verified fix in build 369 beta.
