### ISSUE TITLE
System night mode switching broken

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#621]
Night mode: "System" does not work (Android 10 feature, though some Samsung Android 9 also impelment it).

**Comment by JJK96** [comment]
I'm working on integrating Android 10 night mode better. 

See https://github.com/JJK96/and-bible/tree/nighttheme for my progress.

**Comment by JJK96** [comment]
If I set night mode to system and restart the app, it is started correctly in night mode.
On current master (6a575916b)

**Comment by tuomas2** [comment]
Not sure what has changed, but now this seem to work (as of build 370)

**Comment by JJK96** [comment]
For me this does not work with the latest build (370).

See the behaviour on the current master https://imgur.com/a/0CCW45L
It also shows the corrected behaviour on my nighttheme branch.

**Comment by tuomas2** [comment]
What I tested earlier was

1. set system night mode off, and and bible in system mode
2. set system night mode on
-> night mode is changed in And Bible

and that seem to work.

**Comment by tuomas2** [comment]
FIxed in build 371
