### ISSUE TITLE
Do not execute search again when going back to the window

### ISSUE THREAD

**Issue by JJK96** [AndBible/and-bible#629]
Going back to the search window after jumping to a match takes a long time for a search with a lot of matches. 
It seems like the search is executed again for every time you jump back to it.

Build: 317d872db90f8c2ae292058bad0591c8a7675f40

**To Reproduce**

Steps:

- Execute a search (one with a lot of matches)
- Click on one of the matches
- Click the back button to go back to the search view.

**Expected behavior**
Quickly open the window again, loading the results of the search that has already been executed.

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: Android
 - Version 10

**Comment by JJK96** [comment]
Also, a search with 1000+ matches takes very long to load (about 23 seconds on my device).

**Comment by tuomas2** [comment]
> Also, a search with 1000+ matches takes very long to load (about 23 seconds on my device).
> 
> Edit: Fixed in #634

@JJK96 can we close this? Or is #630 the only thing remaining to be fixed?

**Comment by JJK96** [comment]
The effect of this issue is less severe since search is a lot faster now, but the search is still executed again when going back to the search window, instead of keeping the previous state.

**Comment by JJK96** [comment]
After some investigation I have found the root cause of this problem:

The search activity is started using `startActivityForResult()` when the user selects a verse the activity result is set to the verse and the activity is `finish()`ed. 
This means that the activity is destroyed, and when the user presses back, the activity has to be created again.

I think the best solution is to make the search activity a separate task, this means that it maintains a set of activities and a state independently of the main task. So the task does not have to be closed when the user selects a verse.
The tricky part here is to make the `MainBibleView` jump to the selected verse without using `startActivityForResult()`.

**Comment by timbze** [comment]
@JJK96 You can see how reading plan does it here: https://github.com/AndBible/and-bible/blob/0b30f1d13644cb4e54338975c5c145d5b786ac64/app/src/main/java/net/bible/android/control/readingplan/ReadingPlanControl.kt#L274
