### ISSUE TITLE
More flexible bookmark labels

### ISSUE THREAD

**Issue by JJK96** [AndBible/and-bible#638]
There are currently only 5 bookmark styles of which only 4 are colors. I would like to use more colors for my bookmarks. 

**Describe the solution you'd like**

A first step would be adding more colors to the styles.
A better solution would be to have the user choose an arbitrary color for a bookmark label.

**Comment by tuomas2** [comment]
I have plans to improve bookmarks in many ways (some documented in tickets, some not) after 3.3, and it is priority to me as well. If you want to do the first step quick fix it's fine, but there will be bigger revamp to bookmarks coming later for sure.

See #189  #111 #430  etc...

**Comment by tuomas2** [comment]
Via support (https://support.andbible.org/scp/tickets.php?id=83)
> May I add another idea too.. being able to Verse marking (and/or underlining) in different colours would be another "bon bon" (candy).. but surely not urgent.

**Comment by tuomas2** [comment]
Implemented in develop
