### ISSUE TITLE
Single tap for selecting a verse

### ISSUE THREAD

**Issue by JJK96** [AndBible/and-bible#639]
I could not find if this has been brought up before, so I create a new issue.
Currently the way to select a vers is to do a long tap, while a single tap does nothing.

**Describe the solution you'd like**
Use single tap to select a verse.

**Comment by tuomas2** [comment]
Single tap is used to

1) switch between windows 
2) go back from fullscreen mode 

Thus I'm not sure if it is good idea to switch from long-tap to single tap. Moreover switching to activity mode in Android apps is often done through long-tapping, so it's consistent UX.

**Comment by tuomas2** [comment]
Of course we can try it and if it gives good feeling of UX, maybe we can consider.

**Comment by timbze** [comment]
Related: #236 and #361

**Comment by JJK96** [comment]
How about:

- Single tap in active window selects verse
- Single tap in non-active window activates it.

I think that would be intuitive, it's the same way with application windows on a PC.

**Comment by tuomas2** [comment]
As we have now ambiguous selection modal for bibleview clicks, it's in principal possible to implement this as another action. Moving to 3.5, but feel free to try it out and make PR.

**Comment by timbze** [comment]
Done in #1162
