### ISSUE TITLE
Missing Latin language

### ISSUE THREAD

**Issue by lmarcetic** [AndBible/and-bible#640]
I would like to download the Vulgate, but I can't find the Latin language in the Documents tab's languages drop-down. Sorry if this is the wrong place to report this, I would appreciate an explanation. Thank you in advance and peace be with you!

**Comment by tuomas2** [comment]
Hi,

search lingua latina from language list.

next and bible 3.3 has major improvement to download selector so it is
easier to find.

**Comment by lmarcetic** [comment]
There is no "Lingua Latina"; language "Limbu" is followed by "Lole"

**Comment by tuomas2** [comment]
Oh. Interesting. But version 3.3 is planned to be released in couple of weeks, so it will be found there. You could try it already now if you want, from Beta channel or from https://drive.google.com/drive/folders/1LpUarFDZG8niDVC7JJufs0odV33s1z8D
