### ISSUE TITLE
Window can be partly behind toolbar

### ISSUE THREAD

**Issue by JJK96** [AndBible/and-bible#641]
https://imgur.com/gxFvMpZ

Both windows have the same content and are scrolled all the way up.
It is clear that there is more space between the toolbar and the title in the lower window.

The window size is probably calculated wrongly.

**Bug was found on And Bible version**
Build 42b6db8152c8a68c81c5c3835b1bc848efdfe736

**To Reproduce**
1. Open two windows
2. Scroll them to the top
3. Observe the difference

**Expected behavior**
Both windows should behave the same.

**Smartphone (please complete the following information):**
 - Device: Oneplus 6
 - OS: Android
 - Version 10

**Additional context**
I ran into this issue while working on #188, I can display the notes, but the top part of the text can be hidden behind the toolbar.

**Comment by JJK96** [comment]
This seems to be intentional in order to have nice transitions to fullscreen.

**Comment by tuomas2** [comment]
I think it still would be good to prevent split bar from going under toolbar / system bars.

**Comment by tuomas2** [comment]
Indeed this is practically duplicate of #509

**Comment by JJK96** [comment]
Maybe there's a better way to have smooth transition to fullscreen while the main window is not underneath the toolbar.

That would solve this problem, and also #509.
