### ISSUE TITLE
Hide window buttons when single window 

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#642]
**Describe the bug**
When there's only 1 window in workspace and I enable Hide window buttons in application preferences, it changes the + button in bottom right to restore button. 

**Bug was found on And Bible version**
Build 366

**Expected behavior**
I think if it's single window then there should be no buttons visible with the setting enabled.

**Comment by bvahedy** [comment]
Tim, I'm not able to duplicate this in build 366, can you try a fresh install, and check again.

**Comment by tuomas2** [comment]
I could reproduce. Instead of restore button I think there should be '+' button visible.

**Comment by bvahedy** [comment]
Ok, I see what you are talking about Tim. The issue would be if we remove that icon with the hide icon option then the ability to add a window would go away until the option to show window is activated again. 
If the user doesn't want to see any icons they can just double tap and enter the full screen mode. with both hide icon options in the setting they won't see any icons.

**Comment by tuomas2** [comment]
Fixed in build 368
