### ISSUE TITLE
Share option does not appear

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#644]
**Describe the bug**

Via email:
> It seems the option to SHARE doesn't appear at times when we long press on verse/s. I have to go back and do it multiple times to get that SHARE icon highlighted... 
> 
> While reading a chapter, did a FIND on something and went to that find result (to another book) & when tried to long press on the verse there, SHARE icon is no more available. ...   

**Bug was found on And Bible version**
Build 366

**Comment by bvahedy** [comment]
I need more specific steps, thus far I have not been able to duplicate this.

**Comment by tuomas2** [comment]
From the screenshot user provided (on and-bible mailing list), it looks like there indeed is a bug which hides the three-dot menu under the bar.  User says he is using Chromebook (Acer R11). I will try this on Chromebook emulator next time.

**Comment by tuomas2** [comment]
from same user:

> Just like the SHARE option is unavailable (no 3 dots when text is highlighted, as the screenshot shows that was sent previously), the FOOTNOTES option is acting the same way also

**Comment by tuomas2** [comment]
Hmm Chrome OS emulator image does not work... (crashes currently when trying to start in ADV).

**Comment by timbze** [comment]
Chrome OS emulator issue addressed here: https://issuetracker.google.com/issues/147557436

Works with older emulator version: https://stackoverflow.com/a/60819386/877453
