### ISSUE TITLE
Chapters show verse 0

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#647]
**Describe the bug**
Title shows verse 0. I know sword has verse 0, but I think it would be more user friendly to always show verse 1 instead. I don't know how long it's been showing verse 0 but I know quite a while back it did not. 
![Screenshot_2020-05-09-05-21-28~2](https://user-images.githubusercontent.com/35117769/81472450-5dfa1500-91b5-11ea-92d5-b7889e9f9ccc.png)

**Bug was found on And Bible version**
Build 367

**Comment by tuomas2** [comment]
This is a side-effect of fix to #545 (I was aware of this when I made it). Need to think about it if we can avoid this somehow.

**Comment by bvahedy** [comment]
It only does that is there is a chapter description. If you move below the
chapter descr  then it displays verse 1 on the menu title.

**Comment by tuomas2** [comment]
Will be fixed in build 368

**Comment by bvahedy** [comment]
Verified fixed in 368 beta build. I used ESV Bible since it has chapter titles.
