### ISSUE TITLE
Sync groups

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#648]
Allow setting sync group for windows. 

Suppose we have 4 windows. Sometimes it is desirable that first 2 windows are synced with each other, while 2 other windows are synced.

I think most user-intuitive way of implementing such a synchronization is to implement sync groups, to which windows can be assigned to. This would be adjustable in window menu, instead of single 'synchronize', there would be submenu, in which there would be "Sync group 1", "Sync group 2" etc (starting from 2 groups, and number increases if all of the groups are being used).

I'm not sure if this feature would be confusing to users. If it is confusing, it could be a feature that is optionally enabled from application preferences. But I think it might be possible to implement it such a way that it's pretty intuitive.

**Comment by agrogers** [comment]
I like the idea. And if it is not too hard i reckon there would be people who would use it.

My concern for AndBible is that as it gets so much more feature rich it does run into the problem you were concerned about - it gets too complicated for people.  I like the idea of hiding features for new users.  If AndBible continues to get features at the same rate it has been, i might definitely need it.
