### ISSUE TITLE
Notes for next chapter cannot be displayed

### ISSUE THREAD

**Issue by JJK96** [AndBible/and-bible#650]
Opening the "Notes and references" view in the next chapter opens a window stating:
"No notes exist for this verse".

Scrolling down so that the current chapter is the chapter with the note will show the note when the "Notes and references" view is opened.

**Bug was found on And Bible version**
dba4ff2c8c2fa552b16e5cb49854d7579544068e

**To Reproduce**
1. Find a verse at the start of a chapter with a reference
2. Navigate to the chapter before the one with the previously found verse
3. Scroll down until the previously found verse is visible, but the current verse is still in the previous chapter  
4. Open the "Notes and references" view.

**Expected behavior**
The reference is found

**Smartphone (please complete the following information):**
 - Device: Oneplus 6
 - OS: Android
 - Version 10

**Comment by bvahedy** [comment]
So when I highlight a verse and using the three dot menu to go to the footnotes and ref. I get different results when the verse is at the top of the screen verses if the verse is in the middle of the screen. I don't know if this has something to do with chapter titles. I used ESV Bible going to Micah chapter 5:1.
Is that what you are experiencing?
What Bible translation are you using? 
What I'm describing could be a different bug.

**Comment by JJK96** [comment]
Sounds like a different, but possibly related issue.

Screenshots:
https://imgur.com/a/aViY7Ip

Try reproducing with KJVA, 

- move to genesis 1
- scroll down until you can see Gen 2:3
- Select and open notes/references for Gen 2:3
- Observe that no notes are found.
- Scroll down until Gen 2:x is the current verse
- Select and open notes/references for Gen 2:3 again
- Observe that there is a note.

**Comment by bvahedy** [comment]
You are right they may be related.

**Comment by tuomas2** [comment]
Will be fixed in 369

@JJK96 can you quickly review my fix 91d4f68?

**Comment by JJK96** [comment]
It's indeed fixed

**Comment by tuomas2** [comment]
> It's indeed fixed
> 
> Edit: I just noticed, the reference labels are wrong.
> I view a verse with reference label `g` and I see the correct reference but with label `a`.

Investigated this, and looks like
- If source text has marked explicitly letters for each reference, then they are shown correctly
- If not, then it shows autogenerated 'a' always.

I'll try to find some way to get around this. Earlier solution has been to footnotes for whole chapter always, thus autogenerated letters are always correct.

**Comment by tuomas2** [comment]
Hmm. We could change autogenerated reference letter generation to be based on verse number:
11a 11b etc. How does it sound like?

**Comment by tuomas2** [comment]
Looks like this

![Screenshot_1590127990](https://user-images.githubusercontent.com/5811789/82637005-8f8acb80-9c0c-11ea-9f32-832fd93f95f5.png)
![Screenshot_1590127985](https://user-images.githubusercontent.com/5811789/82637007-90236200-9c0c-11ea-9767-b2ee6cf5dbd0.png)

**Comment by tuomas2** [comment]
ESV and those that have hardcoded letters will look the same as earlier

**Comment by tuomas2** [comment]
I think this is acceptable solution (for now at least). Running letters (earlier) look nicer, but this is technically robust solution for this problem.

**Comment by JJK96** [comment]
It's acceptible, though the disruption in the text is greater than before. Also, this will break the tests I think. Make sure to check that.

**Comment by tuomas2** [comment]
Noticed (thanks to CI) and fixed tests.

**Comment by tuomas2** [comment]
There could be other options too. 
verse 1 => a, verse 2 => b, if there are two references in verse 3, then they would be c1 and c2, and when we run out of letters, we would have aa, ab, ac1, ac2 etc.

**Comment by JJK96** [comment]
In that case the `a` would always correspond to verse 1 and the number would be indicating the number of the note. Then I think the current situation makes more sense, where a number refers to the verse number.
