### ISSUE TITLE
Clicking on a crossreference in the first chapter of a book opens notes view of verse 1

### ISSUE THREAD

**Issue by JJK96** [AndBible/and-bible#652]
Clicking on a crossreference in the first chapter of a book opens notes view of the first verse.

This is because the osisID in the note link refers to chapter 0.

The first commit which changed the basisRef to chapter 0 is  4531fbe4ef344d071fedcf677d53c708b1092739

**To Reproduce**
1. Go to the first chapter of a book
2. Click on a note/xref in another verse than the first
3. Observe that the resulting notes/xrefs window is for verse 1.

**Comment by JJK96** [comment]
@bvahedy This issue does not happen on build 367

**Comment by bvahedy** [comment]
I'm running build 367 and if the verse with the ref. is not at the top of
the screen selecting that verse and trying to lookup references for that
verse will result in "no notes exist for this verse" even though there is
one. See screen shots below:

**Comment by bvahedy** [comment]
When using the ESV Bible and selecting a verse from the middle of the screen, the footnotes that is picked is from somewhere else. For the ESV you don't get the message that there is no footnote for this verse, it's just a bogus footnotes.  Whereas for KJVA Bible you get that message.

**Comment by JJK96** [comment]
You picked a verse from the next chapter, thereby reproducing #650.

This issue is specifically about *clicking* notes using the new clickable notes feature, the problem is caused by an incorrectly generated link.

**Comment by bvahedy** [comment]
Ok, I see what you mean. You are correct, it doesn't do this when you are
within a chapter.

Is the clickable notes feature in build 367, if so, how do you activate it?

**Comment by JJK96** [comment]
It is not in 367, see https://github.com/AndBible/and-bible/pull/637#issuecomment-626182647
