### ISSUE TITLE
Idea for better workflow with TSK crossreferences

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#654]
I have been using the long click option for a bit now but it is not really working as easily as i thought it could have.  What i think could just be a two click action is quite a bit longer and messier. I made a [short video here ](https://drive.google.com/file/d/15fi2vrMCOmSPNPiKy7CDHCidap-rjFJY/view) to try and show how my process goes.

So, i still think it would be a great feature to be able to set the first displayed window's verse reference to the active verse in the 'special window' where links are shown.

This would make it really easy to follow the links trail from verse to verse. And it would also allow us to go backward through that same trail.

Thanks.

_Originally posted by @agrogers in https://github.com/AndBible/and-bible/issues/613#issuecomment-625579757_

**Comment by tuomas2** [comment]
@agrogers, I copied this idea as a new issue so that it is not forgotten on closed issue. Idea you gave in the video is nice. Though I have some related ideas that might also give you better user experience, like #648, #374, #655

But this is a good UX case, we should try to find a better way (either the one you suggested, or something else).

**Comment by tuomas2** [comment]
Hopefully the video does not disappear until this ticket is closed :-)

**Comment by agrogers** [comment]
Thanks for the reply Tuomas. I appreciate it. I will check out those links
too. I would love to contribute more to AndBible than just ideas that
require someone to work. Not sure what there is that i can do though :(

AndBible has really developed a lot over the last year or so. It's been
great to see its progress!

**Comment by tuomas2** [comment]
3.4 will include some features that might allow new workflows. #655 will be fixed also. Sync groups #648 is probably the most essential fix for this, but it might be postponed to 3.5. I'll close this for now, as it will be fixed by other tickets.
