### ISSUE TITLE
When jumping to new location due to sync, history item is not made

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#655]
**Describe the bug**

**Bug was found on And Bible version**
Build 367

**To Reproduce**
1. 2 windows, 1 with bible, second with tsk, and sync them.
2. long-click link on tsk, open in new window
3. Sync third window -> first and second window also jump
-> analyze the history of windows 1 and 2. They should have created history item of the
   previous location, but did not.

**Comment by agrogers** [comment]
Thanks for adding this. I didn't think it was a bug - i thought it was the design :)

**Comment by agrogers** [comment]
I suggest we delay this one to after v3.4 release
