### ISSUE TITLE
Hebrew Fonts reset to system fonts style upon closing and reopening AB

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#658]
In build 368 beta:

window is HISB Bible.
Close AB and reopen
(See screenshots)

This is the correct font:
![Screenshot_20200514-195537_Bible Study](https://user-images.githubusercontent.com/46405809/82022837-20c4d580-9642-11ea-8ec5-a3b8b1e84721.jpg)

This is what it reverts to:
![Screenshot_20200514-195454_Bible Study](https://user-images.githubusercontent.com/46405809/82022965-5b2e7280-9642-11ea-8f23-4e9b7a830bdb.jpg)

**Comment by timbze** [comment]
Maybe related to #576?

**Comment by bvahedy** [comment]
Don't really know but it wasn't happening in build 367. Is there a way to
compare build codes to see what mod could have caused it?

**Comment by tuomas2** [comment]
> Maybe related to #576?

It looks indeed similar, but maybe not directly related because 367 was OK.

**Comment by tuomas2** [comment]
Will be fixed in build 370
