### ISSUE TITLE
Create new window is missing from the list in kabab menu... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#659]
Running build 368 beta:

In the app setting turned on hide window icons.
 create a new workspace and choose a Bible, we only have one  window.
There are no visible icons to create a new window, that's understandable because we turned on hide window icons, but there should be an item in the three dots menu (kebab menu) on the top right to create a new window when there is only one window in the workspace.

**Comment by tuomas2** [comment]
I think I fixed this issue by making "add new button" visible in this case.

**Comment by tuomas2** [comment]
No, I didn't fix this, but correct fix to this issue is as I noted in my comment.

**Comment by tuomas2** [comment]
Will be fixed in build 369

**Comment by bvahedy** [comment]
Verified fixed in build 369 beta.
