### ISSUE TITLE
Small font sizes don't work properly

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#660]
# Bird's eye view to comments

Hi 

I was highlighting the other day all through Romans and thought it would be good to see where across the book each of these passages fell. So I reduced the font size down to 1 to try and get a bird's eye view. 

However, although the interface let's me choose 1pt (and 0pt!) it displayed it in the Bible window as 4 or 5 or something.

I appreciate that 1 px sized font is unreadable. But I was not trying to read - I was interested in seeing how concepts were spread through a book. I only wanted to see the highlighting. 

This is made practical because I just set up a Workspace called 'Tiny Text' and I switch to that to see this view.

As for the 0 pt font size I can select in the font size selector, that is probably a mild bug. However, it would be way cool if, after choosing 0 pt, it turns the Bible text into a single line and simply shows the line in the highlight color (maybe delineated by chapter numbers). I could possibly see all of Romans on a single phone screen!

See 
![Screenshot_2020-05-16-10-42-33-848_net bible android activity](https://user-images.githubusercontent.com/13920678/82106061-2ca7b900-9762-11ea-9193-0cc53cbe5fa7.jpg)
 for the smallest text I can get.

**Comment by tuomas2** [comment]
- [x] Need to set font size on bibleview-js side. Then it works. 
- [x] Min font size should be 1pt, not 0pt

**Comment by tuomas2** [comment]
Implemented in develop

**Comment by agrogers** [comment]
Excellent work on this. Thank you. It is a very cool feature I think and one that is almost accidental due to some smart programming. Just a couple of minor bugs that you might be interested in... And one enhancement. 

1. When first viewing the window, not all the verses that should be visible are rendered. If I slowly scroll the missing verses are rendered and eventually I can see them all. They stay visible until I move to a new window.
2. The orange Cross reference labels remain visible even though I believe I have turned them off correctly.
3. It seems the text is being rendered slightly larger and over the top of itself - which is perfectly fine by me - it gives a groovy look to the screen and to the bookmarks. But maybe there is some easy tweak to get it even smaller. 
4. It would be great to be able to see multiple books. At present only one book can be shown on the screen. We need to swipe to get through to the next book. If it showed multiple books we could view all the letters of John and more on the one screen.

https://drive.google.com/file/d/10NizPJjIre61V_UAYqDDB8ZzmBwONpRR/view?usp=drivesdk

Video explanation above. Couldn't turn it into a real link on my phone. 

Thanks again for your hard work!
