### ISSUE TITLE
Multiple windows icons don't move to base bottom after speak is stopped... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#661]
Running build 368 beta:

With multiple windows icon minimized. Initiate speak. Now the speak control icons is at the bottom of the screen and windows icons are resting above it.
If speak is stopped, the speak icons disappear and the windows icon should move down. 
The minimized windows icons are not visible initially, I don't know if that's a big or not, but to make them visible, double tap to enter full screen mode and then go back.

See screenshot:
![Screenshot_20200519-120357_Bible Study](https://user-images.githubusercontent.com/46405809/82371646-63363b80-99cf-11ea-98fc-bd1a927957ea.jpg)

**Comment by timbze** [comment]
I can't reproduce on Android 8.0 neither on emulator with 9.0

**Comment by bvahedy** [comment]
Tim, Did you try entering full screen mode with speak paused and then go
out of full screen mode and then stop speak, otherwise you won't see the
minimized windows icons.

**Comment by timbze** [comment]
Hmm the buttons show up correctly for me every time. And the window buttons don't disappear for me either except when I go into fullscreen (which should be like that)

**Comment by bvahedy** [comment]
I think what is happening is that the windows icons get overlapped by the speak toolbar. They get reset when I come out of full screen.
![Screenshot_20200522-172206_Bible Study](https://user-images.githubusercontent.com/46405809/82717490-46a93600-9c51-11ea-8037-ce3593b93f27.jpg)

**Comment by tuomas2** [comment]
I can reproduce this on my Samsung Tab A 8" tablet. But not on my phone.

**Comment by tuomas2** [comment]
Weird. 
On my tablet: When I compile in debug mode, I can't reproduce. But when I compile in release mode, I can reproduce.

**Comment by timbze** [comment]
> Weird.
> On my tablet: When I compile in debug mode, I can't reproduce. But when I compile in release mode, I can reproduce.

That must most likely have to do with minify option turned on then. How exactly I don't know. I don't think it's an option we should turn off, but maybe that's a hint to find what the issue is.

**Comment by tuomas2** [comment]
Interesting. Looks like Kotlin bytecode produces different result and proguard removes unused function. See f262d3b

**Comment by tuomas2** [comment]
Will be fixed in build 370

**Comment by timbze** [comment]
Very interesting, I thought you missed the actual fix in the commit :smile:

**Comment by bvahedy** [comment]
Verified fix in build 370 beta.
