### ISSUE TITLE
Make underline label visible in label activity

### ISSUE THREAD

**Issue by JJK96** [AndBible/and-bible#664]
**Describe the bug**
Currently it's white text on white background

**Comment by bvahedy** [comment]
I don't see this bug in build 368, if it was fix in this build it's working.

**Comment by JJK96** [comment]
It was introduced very recently, a couple of commits ago.
I specifically unassigned you so you wouldn't have to look at it. I'm sorry to waste your time with this.

**Comment by tuomas2** [comment]
Fix will be in build 369

**Comment by bvahedy** [comment]
Not s problem, it seems to be working now.
