### ISSUE TITLE
Translations don't appear properly on Android 5 etc (API levels 21-25)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#668]
On Samsung Note 10.1, running Android 5.1.1 I can reproduce the following:

1. Set system language to English
2. Set And Bible language to Finnish
3. Go to Choose Document, Download Document or Speak Settings screen (or almost anything else but main bible view)
 -> Notice that translations are not shown properly (english text instead of finnish)

I have noticed this on my Android 9 tablet (Samsung Tab A 8" with pen) but it does not reproduce there consistently.

If system language is finnish, then all translations are shown properly.

**Comment by bvahedy** [comment]
On the Note 8 running Android 9, it's a mix of both English and the other language selected, not everything on any menu is translated to the new language.

**Comment by tuomas2** [comment]
just want to make sure: did you use some fully translated language selected, such as finnish?

**Comment by bvahedy** [comment]
I can't tell what is fully translated, I used Hebrew. I assume it wasn't
fully translated since most of the menus were in English.

**Comment by tuomas2** [comment]
Can you try finnish?

**Comment by tuomas2** [comment]
Tested 3.2.340 on the same device that this problem affects. On that version, translations were OK, so it's clearly regression.

**Comment by tuomas2** [comment]
This is annoying bug for those that it affects, but it could be that it's not very common issue. 

On the other hand, people that really need translated version, usually have also translations enabled system-wide, and those this issue does not affect.

**Comment by tuomas2** [comment]
Tested with Lollipop emulator and can reproduce this (with production apk)

**Comment by tuomas2** [comment]
Bisected this to this commit:

> 6f8d4389b1c90055d95e73ec6660edfe6edd0055 is the first bad commit
> commit 6f8d4389b1c90055d95e73ec6660edfe6edd0055
> Author: Tuomas Airaksinen <tuomas.airaksinen@gmail.com>
> Date:   Thu Jan 16 15:25:41 2020 +0200
> 
>     Text size and bookmark color selection
> 
> :040000 040000 82ea482a9ce7123d0c88b4e29847b218be56c061 49c2ca3c5c2e320c534e051066afec48f0cfd186 M	app
>

**Comment by tuomas2** [comment]
Culprit is introduction of these dependencies:

    implementation 'androidx.preference:preference:1.1.0'
    implementation 'androidx.preference:preference-ktx:1.1.0'

**Comment by tuomas2** [comment]
I believe the issue is due to some transitive dependency of androidx preference, like appcompat.

https://mvnrepository.com/artifact/androidx.preference/preference/1.1.1

**Comment by tuomas2** [comment]
I believe this will be fixed by future updates to androidx libraries. Not putting more effort on this right now.

**Comment by tuomas2** [comment]
This was fixed in 4.0 by some library updates.
