### ISSUE TITLE
Commentary flicker(sync) when not needed

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#670]
1. have pinned bible and unpinned minimized commentary, after restart 
2. scroll down bible 1 verse
3. tap commentary open, scroll down a bit
4. tap link from comment 
5. In links window scroll down 1 verse
→ commentary window goes to top ( should not)

**Comment by tuomas2** [comment]
Will be fixed in 370

**Comment by tuomas2** [comment]
Reproducible in 369

**Comment by bvahedy** [comment]
Verified fix in build 370 beta.
