### ISSUE TITLE
Window button bar button does not scroll properly

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#676]
1. Create many windows, so that window button bar is longer than window width
2. Minimise all windows but first and last
3. Activate first window by tapping it (not button but window itself)
4. Scroll window button bar such that last window button is only partially visible
5. Activate last window (not button but window itself)
Expected: window button bar is scrolled so that button is completely visible
Actual: it does not scroll at all.

**Comment by tuomas2** [comment]
Will be fixed in build 371

**Comment by bvahedy** [comment]
Verified fix in build 371.
