### ISSUE TITLE
When selecting verse, it does not scroll properly to be visible

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#677]
1. Go to full screen
2. Scroll verse up partially so that only part of it is visible
3. Long-tap partially visible verse
Expected: tapped verse should be scrolled so that it is visible completely
Actual: it is partially hidden

**Comment by tuomas2** [comment]
Reproducible on build 369, fixed in build 370.

**Comment by bvahedy** [comment]
Verified fix in build 370 beta.
