### ISSUE TITLE
After restarting app, window button bar is not hidden

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#678]
1. Have multiple windows
2. Hide window button bar from arrow button
3. Restart app
Expected: Window button bar is still hidden
Actual: it is shown, although arrow points to wrong direction and button bar can't be scrolled.

**Comment by tuomas2** [comment]
Reproducible in build 369. Fixed in build 370.

**Comment by bvahedy** [comment]
Verified fix in build 370 beta.

**Comment by tuomas2** [comment]
again in 371

**Comment by tuomas2** [comment]
Will be fixed in build 372

**Comment by bvahedy** [comment]
Verified fix in build 372.
