### ISSUE TITLE
Sometimes opening quote (") is substituted with question mark (?)

### ISSUE THREAD

**Issue by nyotov** [AndBible/and-bible#68]
E.g. see the attached screenshot of the Bulgarian (Veren) translation of Mathew 11:10. On the second line the text is "писано: **?**Ето..." but the question mark should be an opening quote mark.
This is not always the case, sometimes the opening quote is there.
![screenshot_20170114-080929](https://cloud.githubusercontent.com/assets/7946520/21952947/e5c7588c-da32-11e6-8709-a3a95d80c584.png)

**Comment by ildar** [comment]
1. when some characters are seen as "?" it means the current font lacks the
char.
2. You should be aware that there are several block-quote characters:
straight, left and right. Hence some of them absent in the font of your
device.
Bottom line: your Bible module is not fully compatible with the font you
use. So to fix it you either change the module or change the font in use.
For the latter see
https://andbible.uservoice.com/forums/100177-general/suggestions/1993701-ability-to-change-font-background-color
>
> --
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by tuomas2** [comment]
Character that is found in this string is indeed questionmark (63) https://www.fileformat.info/info/unicode/char/003f/index.htm so this is not an font issue.

**Comment by tuomas2** [comment]
I can see this issue also with Xiphos. Assuming it is module issue.

**Comment by tuomas2** [comment]
Created ticket to Crosswire bug tracker https://tracker.crosswire.org/browse/MOD-342. Closing this.

**Comment by tuomas2** [comment]
Upstream ticket was closed so issue should be now fixed by updating the module.
