### ISSUE TITLE
Allow only morph codes to be displayed without Strongs

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#682]
Running build 370:

Open a Bible like kjv that has both Strong's and morph codes.
In the text option check the boxes for showing Strong's numbers and morph codes.
With both codes visible tap on the dictionary icon on the top menu bar. This will turn off both Strong's no. and morph codes.
Tap on the dictionary icon again and the Strong's numbers appear but the morph codes don't display.  you now have to go to the text options and check the box for morph codes in order for them to show up.
Expected result: when Strong's numbers are turned off morph codes should still display or if they are linked on the same tag at least they both should appear and disappear when the dictionary icon is tapped.

**Comment by tuomas2** [comment]
This is how this has been implemented always, but this could / should be changed. Changing into feature ticket.

**Comment by bvahedy** [comment]
It looks more like a bug since turning off dictionary completely turns off morph display in the settings and never turns them on when dictionary is turned back on.

**Comment by bvahedy** [comment]
I'm closing this issue since ticket #733 fixed the appearing if the morphs.
