### ISSUE TITLE
Commentary opens first chapter and verse 

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#683]
**Bug was found on And Bible version**
Build 370

**To Reproduce**
1. Open 2 windows, kjv and Gill, with sync on
2. Go to Eph 6
3. While it's shows Eph 6 without the verse number (just above verse 1), Gill opens commentary for Eph 1:1

**Expected behavior**
Gill should either show chapter 6:0 or 6:1, not sure exactly which verses all have commentary attached.

**Comment by tuomas2** [comment]
I would be surprised if commentary would have something on verse 0. Verse 0 in bibles, as far as I know, has only some book introductions etc.

**Comment by tuomas2** [comment]
Actually I'm not sure if some modules might have something that relates to whole chapter in verse 0.

**Comment by tuomas2** [comment]
Actually this seems to be module issue on Gill: it contains Ef 1:1 on Ef 6:0. 
I'm fixing bible location indicator so that it shows Eph 6:0 for commentary window.

BTW We could try to improve Gill module on our own, since it's public domain.

**Comment by timbze** [comment]
> I'm fixing bible location indicator so that it shows Eph 6:0 for commentary window.

@tuomas2 I don't know if this is a good idea. Most regular Bible users wouldn't know what 6:0 is, and would be confusing. I personally think it would be better the way it was just showing chapter when it's for v0.

**Comment by bvahedy** [comment]
I agree with Tim, it shouldn't be displaying verse 0 in any situation.

**Comment by tuomas2** [comment]
Okay, reverthing that.

**Comment by bvahedy** [comment]
Verified fix in build 372.
