### ISSUE TITLE
Window menu opens in wrong place in full screen

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#684]
**Bug was found on And Bible version**
Build 370

**To Reproduce**
1. Switch to full screen, having multiple windows 
2. Unhide restore buttons bar
3. Long press restore button and the menu jumps to top left of screen (probably because the navbar also pops up, it was hidden before long-press) 
4. See screenshot 
![Screenshot_2020-05-28-05-43-46](https://user-images.githubusercontent.com/35117769/83137599-aadf5600-a0a6-11ea-8d3f-9433e3a9a030.png)

**Comment by tuomas2** [comment]
Does not reproduce on my xperia

**Comment by bvahedy** [comment]
I was also unable to reproduce this on a Note 8.

**Comment by timbze** [comment]
I found one more condition for me to reproduce. There must be more windows
buttons than fit on screen. Than scroll to the right, so that hide arrow is
further left than screen. Than long press one of the buttons and it
reproduces for me

**Comment by bvahedy** [comment]
I'm still not able to reproduce this, I have tried every combination.

**Comment by timbze** [comment]
Seems to not be an issue that will affect many, could change the milestone to either bugfix or 3.4 for my part

**Comment by timbze** [comment]
Can not reproduce anymore
