### ISSUE TITLE
After a find search the top window ends up in the wrong verse... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#685]
Running build 370 beta:

Have two windows. The top window is any English Bible, the bottom window is a Bible with Strong's no. in display.
On top window go to Luke 3:3
Tap on the bottom window and do a find using the following:
strong:h1325
The search finds one item. Tap on it.
The top window is incorrectly synched with the bottom window (see screenshot)
![Screenshot_20200528-084200_Bible Study](https://user-images.githubusercontent.com/46405809/83173924-77182680-a0ce-11ea-95b0-54a7e7574684.jpg)

**Comment by tuomas2** [comment]
Can't reproduce, I got into Ezra 7:22 correctly.

![Screenshot_1591274607](https://user-images.githubusercontent.com/5811789/83758122-31cd9900-a67a-11ea-930b-89d27d43bb86.png)

**Comment by bvahedy** [comment]
This seems to be working in build 377, will close this ticket.
