### ISSUE TITLE
Make Travis build APK for testers

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#688]
It could be nice and beneficial if Travis could build and upload somewhere APKs of successfull pull request builds, for beta testers.

Maybe not yet worth it but if we get a lot of pull requests, it could be helpful.

**Comment by timbze** [comment]
Kind of separate idea, I know some platforms have a separate branch that they set up to auto-build. So for example, when ready to release beta, merge to beta branch, and there can be pipelines set up to build apk and add to beta tag under releases.

But this would be different from building together with PRs.

**Comment by tuomas2** [comment]
Actually it would be possible to experiment with Github Actions too as CI replacement.

CI could be employed more for various tasks, but I'm not sure if it's worth the trouble yet. But of course, pull requests (for configuring something more fancy) are welcome :-)

**Comment by timbze** [comment]
@tuomas2 Github does not allow apk attachments, but zipped yes. But I guess that would be fine?

**Comment by tuomas2** [comment]
Less inconvenient than clicking apk directly, but I guess better than nothing. We can try.

**Comment by tuomas2** [comment]
It is possible to upload apk somewhere (repository for example) and put a link to it.

**Comment by timbze** [comment]
> It is possible to upload apk somewhere (repository for example) and put a link to it.

I think we may need to do that. It seems that it's impossible to attach files to pr or issue comment programmatically. I contacted github about it to see if I'm missing something. 

Edit: Github confirmed my thoughts and said this:
> There's currently no API for comment file attachments at the moment unfortunately so it's not possible to do this programatically. Sorry I don't have better news but if you have questions, please let me know.

[See this issue](https://github.com/isaacs/github/issues/1133) in a Github staff repo

**Comment by timbze** [comment]
Closing in favor of #730
