### ISSUE TITLE
Genbook improvement: display footnotes

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#689]
It seems that Genbook does not display footnote `<note>` tags.

For example, Xiphos shows *n1, *n2, etc in Chapter 1 of 1689 London Baptist Confession genbook. But AB does not show anything where those footnotes are.
Xiphos:
![image](https://user-images.githubusercontent.com/35117769/83438354-88c73a00-a3fe-11ea-92d7-5f1b36ee3aff.png)

Chapter 1 *n1 code in genbook .bdt file looks like this:
```
<note>
    <reference osisRef="2Tim.3.15-2Tim.3.17">2 Tim. 3,15-17</reference>; 
    <reference osisRef="Isa.8.20">Isa. 8,20</reference>; 
    <reference osisRef="Luke.16.29">Luke 16,29</reference>\.
    <reference osisRef="Luke.16.31">31</reference>; 
    <reference osisRef="Eph.2.20">Eph. 2,20</reference>
</note>
```

**Comment by tuomas2** [comment]
I believe this is fixed by now. @timbze you can confirm and re-open if not.

**Comment by timbze** [comment]
The note is added in the text in this specific case, but I think it should be some kind of note link, and the references are plain text, not links![Screenshot_20210304-053911.png](https://user-images.githubusercontent.com/35117769/109958914-63789c80-7cac-11eb-9050-600481464f78.png)

**Comment by timbze** [comment]
Also, first Baptist confession 1646 has x-editor-correction tags which are notes that have not been implemented. E.g. See section 40

**Comment by tuomas2** [comment]
I don't know what magic Xiphos does, but osis XML fragment does not mark these in any way so what can we do?

It's like this there:
```
<div> Chapter 1  OF THE HOLY SCRIPTURES 
  Paragraph 1  The Holy Scripture is the only sufficient, certain, and infallible rule of all saving knowledge, faith, and obedience,  2 Tim. 3,15-17 ;  Isa. 8,20 ;  Luke 16,29 . 31 ;  Eph. 2,20   although the light of nature, and the works of creation and providence do so far manifest the goodness, wisdom, and power of God, as to leave men inexcusable; yet they are not sufficient to give that knowledge of God and His will which is necessary unto salvation.  Rom. 1,19-21 .  2,14 . 15 ;  Psalm 19,1-3   Therefore it pleased the Lord at sundry times and in diversified manners to reveal Himself, and to declare (that) His will unto His church;  Heb. 1,1   and afterward for the better preserving and propagating of the truth, and for the more sure establishment and comfort of the church against the corruption of the flesh, and the malice of Satan, and of the world, to commit the same wholly unto writing; which makes the Holy Scriptures to be most necessary, those former ways of God's revealing His will unto His people being now completed.  Prov. 22,19-21 ;  Rom. 15,4 ;  2 Pet. 1,19 . 20   
....
</div>"
```

**Comment by timbze** [comment]
I'm guessing jsword doesn't handle the case correctly. My OP shows what the source file has, so probably libsword handles it better.

**Comment by tuomas2** [comment]
I believe it's not OSIS source and we don't support non-OSIS sources very well.

**Comment by tuomas2** [comment]
Fixed footnote issue 9e1c20140370cbf48c9853e3eb7dd5ebadd7d835 (x-editor-correction)

**Comment by tuomas2** [comment]
Need to modify jsword to give fragments of (whatever-xml) and render it in js side (should be easy now)

**Comment by tuomas2** [comment]
Hmm, it has SourceType OSIS

**Comment by tuomas2** [comment]
Chapter 1 seem to be invalid XML

org.jdom2.input.JDOMParseException: Error on line 77: At line 77, column 2: mismatched tag

**Comment by tuomas2** [comment]
Invalid OSIS there...

`<item>Galatians<item>`

**Comment by tuomas2** [comment]
Module issue it is then.

**Comment by DavidHaslam** [comment]
There are also 6 other XML errors that match the regexp pattern `<p>[^<>]+<p>` 
i.e. Paragraph start tag `<p>` with no corresponding paragraph end tag `</p>`.

**Comment by tuomas2** [comment]
Could you @timbze or @DavidHaslam report this module issue to Crosswire tracker.

I guess it's practice @ crosswire these days to check osis xml through lint?

`xmllint --noout --schema osisCore.2.1.1.xsd osis.xml`

**Comment by DavidHaslam** [comment]
CrossWire probably doesn't have the original OSIS XML file that the module was made from.
It was probably one that Chris Little made before he went AWOL from CrossWire.

cf. My only tweaks in 2020 were just to the .conf file.

**Comment by DavidHaslam** [comment]
See https://tracker.crosswire.org/browse/MOD-405
