### ISSUE TITLE
Show more of the Note in the Notes List 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#690]
I have just started using the Notes feature. I am wondering whether it is a better option for me than Evernote for bible study. 

One thing that might be an issue for me is finding something that I wrote. A search option could be cool. 

But what I think I would like is simply to show more text in the Notes List. On my phone there is space left on the line that is not used. 

But also there is a lot of space wasted I think beside the verse reference. If the start of the Note was moved to beside the the verse reference we would double the amount of the Note visible and use no more space on the screen. 

Last giving the user a choice on the number of characters of the Note to show could be nice too. 

![IMG_20200602_092208](https://user-images.githubusercontent.com/13920678/83465029-eec2c880-a4b5-11ea-982f-573e61f559a0.jpg)

**Comment by tuomas2** [comment]
I believe this is not any more relevant with the current my notes implementation.
