### ISSUE TITLE
How does Ben make this really cool interlinear window? 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#691]
Can someone point me to some info on how to create a window like Ben @bvahedy has here. That looks so cool. 
![Screenshot_2020-06-02-09-56-23-765_com android chrome](https://user-images.githubusercontent.com/13920678/83465510-88d74080-a4b7-11ea-9f1c-7761ec2226eb.jpg)

I had no idea that was remotely possible in AndBible.

**Comment by bvahedy** [comment]
You can assign boxes and formatting of text for a specific Bible in a file called fonts.properties that is located in the folder under
 internal storage/jsword/fonts
You can also assign specific fonts for that Bible translation by putting the font file in this same directory.
The style.css file should go in this directory:
internal storage/jsword/css

**Comment by agrogers** [comment]
Cool. I will check it out. Thanks!

**Comment by tuomas2** [comment]
As the module is public domain (as far as I have understood), It's in my plans to support module-specific fonts within module zip file and publish the module via AB repository.
