### ISSUE TITLE
Where can I find info on making translations for AndBible? 

### ISSUE THREAD

**Issue by agrogers** [AndBible/and-bible#692]
I don't have the ability but I employ people who I could give the task of working on a Myanmar translation of the interface if one doesn't already exist.

**Comment by tuomas2** [comment]
Info can be found:
https://andbible.github.io/
https://github.com/AndBible/and-bible

and here:

https://github.com/AndBible/and-bible/wiki/Translating-User-Interface

**Comment by agrogers** [comment]
OK, thanks. I see Burmese is only 22% done. I will try and push that along a bit.
