### ISSUE TITLE
Crosswire Wycliffe repository missing

### ISSUE THREAD

**Issue by LAfricain** [AndBible/and-bible#693]
**Describe the bug**
The modules present in the wycliffe repository are missing

**To Reproduce**
1. Update the module list, look for the Orya NT module Ury_WBTI_2005
2. Nothing is present

**Expected behavior**
Installing all the modules present in the Wycliffe repo.

**Comment by timbze** [comment]
I think this has just recently been added to master and not in beta yet: 11382a96

**Comment by tuomas2** [comment]
Yes I added it recently as I noticed new modules being published there and that it was not enabled yet.

**Comment by tuomas2** [comment]
will be fixed in build 371

**Comment by LAfricain** [comment]
I just noticed that the crosswire beta is not present in the list.

**Comment by tuomas2** [comment]
Not sure if it should be, if the modules are beta quality. Perhaps in Beta channel it could be.
