### ISSUE TITLE
Find shows results and also "no results found" 

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#694]
**Describe the bug**
When there's a short list of find results it also shows at the end, no items to display. See screenshot below. 

**Bug was found on And Bible version**
Build 370

**To Reproduce**
1. Open proverbs in KJV 
2. Find the word innocent in just Proverbs 
3. See the find results with "no items to display" at bottom

![Screenshot_2020-06-02-17-33-30](https://user-images.githubusercontent.com/35117769/83631566-f12b2e00-a55a-11ea-9850-fba2add2dd7c.png)

**Smartphone (please complete the following information):**
 - Device: LG G6 
 - OS: Android 8.0

**Comment by bvahedy** [comment]
Tim, I saw that but I thought it meant there are no more pages to display. Otherwise you know to page up for more items on the display.

**Comment by tuomas2** [comment]
Will be fixed in build 371

**Comment by bvahedy** [comment]
Verified fix in build 372.
