### ISSUE TITLE
Submenu does not show up in full screen

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#696]
1. In mobile phone, portrait mode, create (at least) two windows
2. Go to fullscreen
3. Long-click window button bar button to open window menu
4. Click "Move window to"
Expected: submenu is displayed
Actual: it is not displayed at all.

Possibly related: #684

**Comment by bvahedy** [comment]
In build 377 the submenu is appearing now but the system navigation buttons are showing still.

**Comment by timbze** [comment]
I am unable to reproduce

**Comment by tuomas2** [comment]
I also can't reproduce this anymore. Perhaps some lib upgrade has fixed this.
