### ISSUE TITLE
When in a note invoking find and creating search index crashes the app... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#703]
It would be nice to be able to search notes, but if that feature is not available yet then invoking find should not be allowed or the app crash be prevented somehow.

**Comment by tuomas2** [comment]
will be fixed in 374

**Comment by bvahedy** [comment]
In build 377, if you see the magnifying icon on the top tool bar, and you are in a note, tapping on that icon will ask you if you want to create index. If you click ok, the app will crash.
I'm will reopen this ticket for this reason.

**Comment by tuomas2** [comment]
Magnifying class on toolbar disappears when going to my notes. I think fix to #704 fixed this. Will be fixed in build 385

**Comment by bvahedy** [comment]
Verified fix in build 385 beta.
