### ISSUE TITLE
There is no way to jump to the passage when going into a note from the menu...

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#704]
Go to the menu and select My Notes.
From the list select a note to view.
From here there is no easy way to jump to the actual Bible passage. If you tap on the icon for the list of Bibles on the top menu bar, the list does not contain the Bible that was in view  before you entered the note. 
Expected result: include all Bible books in the list on the icon at top menu bar.

**Comment by timbze** [comment]
I think this has been somewhat similar from 3.2 and before, though it is functionality that needs to be fixed. Possibly can wait for 3.4 in my opinion

**Comment by tuomas2** [comment]
Fix was simple enough to go to 3.3. Will be fixed in build 385

**Comment by bvahedy** [comment]
Thanks for the fix, this fix saves me a lot of steps in viewing the passage
from the note.

Verified fix in 385 beta build.
