### ISSUE TITLE
Exit a note editing without saving changes

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#705]
Via email 

> I believe all that remains in this regard is the request for a way to exit from a note without applying any changes to it. At the moment, the only option is a very unforgiving save-and-close. I'm hoping for a further option to cancel-and-close. Possibly a feature request for a new github number.

**Comment by timbze** [comment]
Original context is obsolete, but might still be a feature request (some type of undo) for current notes?

**Comment by tuomas2** [comment]
Let's see if anyone requests such a thing. I don't feel it's very much needed.

**Comment by agrogers** [comment]
An undo button in the note toolbar could be useful although I have never
needed it.

Accidentally selecting all and then typing could be a problem to some.
