### ISSUE TITLE
Increasing size of a window, then closing it breaks AB

### ISSUE THREAD

**Issue by mjdenham** [AndBible/and-bible#71]
From email (Geza):
I finally managed to track down the issue (see below). It was simpler than I thought (and not very serious either):

I reported that the main Bible window disappears. It turned out that it happens in a reproducible way when you first open a secondary window (e.g. by tapping a Strong-code), then maximize that by lifting its top to the top of the page, and then close that secondary window. Then no Bible text is visible any more. (Recovering is not very hard either: You need to create a new window, then reduce its size - and the main window appears from under it.)

It is a small bug, nevertheless it would be great if you fix that as well.

**Comment by ildar** [comment]
Is this WebView-caused?

**Comment by tuomas2** [comment]
I think this has been fixed already. Please re-open if not.
