### ISSUE TITLE
Missing translation updates for 3.3

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#712]
- [x] Russian (!)
- [ ] Arabic
- [x] Italian @LAfricain
- [ ] South Korea (!)
- [x] India (Hindi) (!) @kesarsauce 
- [ ] Czech (!) 
- [x] Hungarian(!) @krisek
- [x] Portuguese
- [x] Afrikaans
- [x] Slovenian
- [x] Spanish @timbze 
- [x] Chinese (CN&TW)
- [x] Ukrainian
- [x] Lithuanian
- [x] Serbian (latin & rs)
- [x] Kazakh
- [x] German
- [x] French
- [x] Polish
- [x] Esperanto @verdulo 
- [x] Finnish @tuomas2 
- [ ] Norweigian (translator promised to make this soon)
- [ ] Turkish @alerque 
- [ ] Estonian
- [ ] Azerbaijani 
- [ ] Dutch 
- [ ] Slovak
- [ ] Uzbek

Missing translations are pretty critical for this update, and some users are now confused. 
This might lead into 1-star ratings and/or lost users.

**Comment by tuomas2** [comment]
Translations can be contributed at https://www.transifex.com/mjdenham/andbible/

**Comment by tuomas2** [comment]
Contexts: #573

**Comment by LAfricain** [comment]
Almost done.

**Comment by tuomas2** [comment]
Awesome! Praying for Arabic translation next.

**Comment by tuomas2** [comment]
Had to remove bunch of languages with very low translation percent recently 1f73a5c4df154e4a6f073b92dcaede277d66dce0.

**Comment by tuomas2** [comment]
@alerque are you planning to update Turkish translations soon?

**Comment by alerque** [comment]
@tuomas2 I don't have time to bring the app up to 1000%, but I thought I'd already address the most critical string additions/changes. If not I'm happy to spend a little bit of time to take care of that, and certainly to review if anybody else contributes.

Also, the entire project seems to be locked in Transifex so I can't even look at it right now. It wants you to upgrade plans or some such nonsense.

**Comment by tuomas2** [comment]
> @tuomas2 I don't have time to bring the app up to 1000%, but I thought I'd already addressed the most critical string additions/changes a week or two ago. If not I'm happy to spend a little bit of time to take care of that, and certainly to review if anybody else contributes.

Okay, I'll check if there's something important missing and notify you again.

> Also, the entire project seems to be locked in Transifex so I can't even look at it right now. It wants you to upgrade plans or some such nonsense.

Can you send screenshot of what happens on transifex for you? It's working perfectly for me and nobody else has complained. I believe it's some issue on transifex, and I would like to send them a notice about that.

**Comment by alerque** [comment]
Sorry, I was in the wrong Bible project entirely on Transifex! It's the Youversion org that's locked out.

**Comment by LAfricain** [comment]
Try to ask @krisek

**Comment by krisek** [comment]
Hi, I'm here... what is the current contribution process? Did the user leave a comment as well? I can check with him/her the issue.

**Comment by LAfricain** [comment]
Welcome Kris! I would like to take this opportunity to let you know that the Hungarian module has just been updated in the beta repository ;)
For the translation just go on [transifex](https://www.transifex.com/mjdenham/andbible) ask to joint the Hungarian team. And when you are approved, translate.

**Comment by tuomas2** [comment]
@krisek I just accepted you transifex request! 
@LAfricain thank you for letting @krisek know about the need :-) 

User just left this message:
"Megváltozott az alkalmazás nyelve, magyarról angolra.A tájékoztató szöveget sem tudom másolni és fordítani. Mire jó ez???" ("The language of the application has changed, from Hungarian to English. I can't copy or translate the information text either. What is this good for???")

**Comment by krisek** [comment]
There are ~250 items to translate, this gonna be a longer journey. WRT this comment: is he/she a contributor? I wonder what is the problem with not being able to copy the info text.

**Comment by tuomas2** [comment]
For translation work, @krisek see #573 for context and prioritize strings.xml first.

I'm not sure what he/she means either. No she is not contributor.

**Comment by tuomas2** [comment]
and you might want to do short strings first.

**Comment by tuomas2** [comment]
Also second 1-star review from Hungarian user. Looks like our Hungarian user group is significant too.

**Comment by krisek** [comment]
Yes, this is clearly about the missing translation. You can write him asking for patience. I'll try to prioritize the work, but this it will definitely take time.

**Comment by tuomas2** [comment]
Third 1-start review from hungarian user which I believe is due to missing translation:

"Mindent lerontottak, ami csak kiválósága volt a régebbi verziónak!"
They ruined everything that was just the excellence of the older version!

**Comment by tuomas2** [comment]
User sent email:

> "Sikerült megújítani az alkalmszást, egyben azt az érdemét, ami volt megszüntetni. Nem is értem, hogy magyar nyelvű Bibliához angol nyelvű menü van rendelve. Már csak abban reménykedem, hogy az angol nyelvűhöz cseh nyelven van menü és így tovább (etc)! 
> Tisztelettel felhasználójuk: 
> ***
> 
> Ui: A betűméret beállítása funkciót sehogyan nem találtam, még sz applikáció ujratelepítésekor sem. Szóval ami jól működött sikeresen lerontották! 
> Mégegyszer köszönet, hogy a Vizsolyi Biblia magyar nyelven van, ez viszont fantasztikus!!!"
> 
> He managed to renew the occasion, as well as the merit of what was to be eliminated. I don't even understand that the Hungarian Bible has an English menu assigned to it. I can only hope that there is a menu for the English language in Czech and so on (etc)!
> 
> Ui: The font size adjustment function was not found in any way, even when reinstalling the sz application. So what worked well was successfully demolished!
> 

I tried to explain the font adjustment feature to him.

**Comment by krisek** [comment]
Mentioning the Vizsolyi Biblia being in Hungarian is fun. It could be even meant ironic/sarcastc. The Vizsolyi Biblia is by definition in Hungarian...  

Otherwise he is only moaning about the translation. Anyway I did 119 items / remaining 164, I hope I can do this in the near future. Is Árpád available to review, or shall I try to find somebody?

**Comment by tuomas2** [comment]
@krisek Great, that's already such a coverage that I guess it's better to include in today's update.

In the upcoming weeks I will keep posting updates to 3.3 as long as there will be updates needed (bugfixes or translations).

Can you PM other team members or do you wish I will do that?

**Comment by tuomas2** [comment]
BTW I just updated translator wiki page: https://github.com/AndBible/and-bible/wiki/Translating-User-Interface

**Comment by krisek** [comment]
33% reviewed
100% translated
0% untranslated 

It will definitely need a few review cycles, but the first iteration is there.

**Comment by tuomas2** [comment]
That's wonderful!
