### ISSUE TITLE
AndBible crashes if a colon space is in the search.... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#717]
Running build 378:
Attempting to find the following caused the app to crash:
strong: h3341

Note that there is a space after the colon.

**Comment by tuomas2** [comment]
please obtain logcat with main menu - > report a bug

**Comment by bvahedy** [comment]
Here is a logcat from the app after the
 crash.

**Comment by bvahedy** [comment]
Here is a logcat from matlog app:
[AB-bug.zip](https://github.com/AndBible/and-bible/files/4767671/AB-bug.zip)

Hopefully one of these logs shows the problem.

**Comment by tuomas2** [comment]
What should be the expected result? Empty result?

**Comment by tuomas2** [comment]
Will be fixed in 379

**Comment by tuomas2** [comment]
will give empty result, because query is invalid according to Lucene search engine.

**Comment by bvahedy** [comment]
How about for all Strong's searches strip all spaces from the entered
string in the background before search is executed.

So "strong:  h3120" becomes "strong:h3120"
Or  "strong:h  3120" -->  strong:h3120"

**Comment by tuomas2** [comment]
Could be, though I would be surprised if any users even know that such a syntax for strong searches is possible (I didn't know).

**Comment by tuomas2** [comment]
I created issue feature request #726 that will make people be aware that such searching is possible and addresses this issue too.
