### ISSUE TITLE
extra text in 2. Tim 4:22 KJV

### ISSUE THREAD

**Issue by timsoftgit** [AndBible/and-bible#72]
There is an extra comment text paragraph at the end of 2. Tim. 4:22 which should not be in the KJV version. (I have seen it in the akjv, but it is not in other sword based KJV bible programs, or in the print version of kjv). The extra text is "the second letter to Timotheus, ordained the first bishop of the church of the ephesians,was written from Rome, when Paul was brought before Nero the second time". 

Section titles, footnotes and xrefs are turned off.

**Comment by tuomas2** [comment]
Screenshot indicates that there indeed is extra text: 

![screenshot_1543655706](https://user-images.githubusercontent.com/5811789/49326400-6549d780-f55a-11e8-915d-b8cb30fe2298.png)

**Comment by tuomas2** [comment]
Re-reported this issue to Crosswire bug tracker: https://tracker.crosswire.org/browse/MOD-340
Closing this one as this is not And Bible code issue.
