### ISSUE TITLE
Enabling morphological codes does not work properly

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#733]
1. Open KJV (that has strongs and morphological codes) from NT location.
2. Enable strongs and morphological codes from workspace options -> all text options. -> Strongs and morph codes are displayed [ok]
3. Disable strongs from toolbar -> both codes disappear [ok]
4. Re-enable strongs codes from toolbar 
 -> only strongs appear [nok]
  Also morph codes should appear
5. Observe that in in workspace options menu quick option for morph code is enabled, though they are not visible. Also in "all text options". [nok]
 Expected: settings should reflect to what is shown in reality

**Comment by bvahedy** [comment]
Tuomas, I created a ticket #682 for this issue awhile back.

**Comment by tuomas2** [comment]
Ah, I think I have then misunderstood #682.

**Comment by tuomas2** [comment]
Will be fixed in build 382

**Comment by bvahedy** [comment]
Verified fix in build 382.
