### ISSUE TITLE
Backing up modules or application db via intent crashes in Android 11

### ISSUE THREAD

**Issue by mattschlosser** [AndBible/and-bible#739]
When a user goes to select the backup option, and then back up either the database or the modules, the 
app immediately crashes

**Bug was found on And Bible version**
Version 3.3.381

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to menu
2. Click on Backup & Restore
3. Click `Backup Documents to...`
4. Select 1 or more modules
5 .Press OK
6. Crash

**Expected behaviour**
No crash

**Smartphone (please complete the following information):**
 - Device: Pixel 4 XL
 - OS: Android 11 
 - Version  11 (RPB1.200504.020)

**Additional context**
.

**Comment by tuomas2** [comment]
Maybe related: #636
