### ISSUE TITLE
Crash in WindowRepository (from Play Store)

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#743]
![Selection_270](https://user-images.githubusercontent.com/5811789/85830038-96b97200-b794-11ea-998d-02648809a598.png)

**Comment by tuomas2** [comment]
Will be (possibly) fixed in build 382

**Comment by tuomas2** [comment]
Will be fixed in build 384.

Reproduce:
- Have 2 windows.
- Maximise one
- Long-press unmaximise button and click "close"
 -> crash

**Comment by bvahedy** [comment]
This crash is nasty, I can't even recover from it because it keeps going to
the previous window state in AndBible. It requires a complete reinstall.

**Comment by tuomas2** [comment]
Yep. But you'll get a fixed build very soon :-)

**Comment by bvahedy** [comment]
Thanks for a quick fix. Verified fixed in build 384.
