### ISSUE TITLE
Make easier access to remove modules

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#744]
Users rarely find "remove module" feature by now.

Make it possible to remove modules  from download screen (similarly as from "choose document" screen). I think that's the most obvious place people try to find it.

**Comment by agrogers** [comment]
Has this been done already - long press the document in the list? If not,

I suggest we delay this one to after v3.4 release

**Comment by tuomas2** [comment]
Implemented removing documents in download screen
