### ISSUE TITLE
Reading plan "current day" gets reset

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#751]
**Bug was found on And Bible version**
Build 382

**To Reproduce**
1. Start from new And Bible install
2. Open a reading plan and set to another day (e.g. go to Day 4 > Menu > Done > Click Done button, -> Reading plan window closes and day 5 has been set as current day)
3. Open reading plans again and it will open at day 5
4. Select and open another reading plan
5. Come back to the first reading plan you opened
6. It now opens on Day 1, but should have opened day 5

**Comment by tuomas2** [comment]
Fixed in build 383
