### ISSUE TITLE
Increase syncing top clearance/margin

### ISSUE THREAD

**Issue by yawnoc** [AndBible/and-bible#762]
Top line in synced windows gets cut off due to insufficient clearance. Especially noticeable for Chinese characters, which are taller.

**And Bible version**
3.3.381

**To Reproduce**
1. Add new synced window
2. Scroll old window to some other verse

**Expected behavior**
Top line in synced windows should not be cut off, and there should be an aesthetically comfortable clearance/margin.

**Screenshots**
![signal-2020-07-05-031701](https://user-images.githubusercontent.com/48375680/86519774-cb9e8680-be70-11ea-9739-e6b2f6105c1b.jpg)

**Smartphone**
 - Device: Samsung Galaxy J2 Pro
 - OS: Android
 - Version: 7.1.1

---
Sorry for the revisions, accidentally submitted before finishing (by hitting return instead of backspace whilst focused on the title field)!

**Comment by bvahedy** [comment]
I tried ChiUn translation and it looks fine, but I'm on version 3.3.385,
can you update to this version and see if the problem goes away.

**Comment by tuomas2** [comment]
I think 381 and 385 should be same with this respect (just small bugfixes). I'll take  a look at it when I have time.

**Comment by yawnoc** [comment]
Yes, the insufficient clearance persists for me in 385.

**Comment by bvahedy** [comment]
Which Chinese Bible book do you see this issue with?

**Comment by yawnoc** [comment]
The screenshot above was for ChiUnL "聖經 (文理和合)", and I get the same behaviour on any of the Chinese versions.

Perhaps this is a system/font-dependent thing? Let me hook up an element inspector later and I'll see what fonts are being used on my end.

**Comment by bvahedy** [comment]
This is what I am seeing:
![Screenshot_20200705-005613_Bible Study](https://user-images.githubusercontent.com/46405809/86528196-9c7d1a80-be5a-11ea-8875-b8207f0c17f5.jpg)

**Comment by yawnoc** [comment]
My Chinese font is Noto Sans CJK, while my default English sans-serif font is Roboto.

![conway fonts](https://user-images.githubusercontent.com/48375680/86529088-57033080-bee0-11ea-8318-5b84f6557c36.png)

From your screenshot you also have Noto Sans CJK for Chinese, but your English sans-serif font is different. Your English glyphs are smaller (using the Chinese characters as a base reference).

![ben fonts](https://user-images.githubusercontent.com/48375680/86529095-62eef280-bee0-11ea-9e91-e375b693005d.png)

So maybe the sync is based on a certain height for English glyphs:
* In my case the English glyphs are a bit tall, and there is no gap above the English. Since my Chinese glyphs are even taller than the English glyphs, they get cut off.
* In @bvahedy's case the English glyphs are just the right size and there is a comfortable top clearance for the English. Since the Chinese glyphs are the same size as the English glyphs, the clearance for the Chinese is also sufficient.

**Comment by tuomas2** [comment]
I think there's some line height -related issue (a bug, I mean). You might be able to overcome it by adjusting line height setting from "all text settings" (per-workspace or per-window settings).

**Comment by yawnoc** [comment]
It's interesting, for the very first verse of any chapter, the sync clearance is *perfect*. Is this due to extra margin/padding introduced by the heading element preceding?

![20200706_220134](https://user-images.githubusercontent.com/48375680/86602141-d2dea500-bfd4-11ea-8ccb-40f518900d3d.jpg)

Also I found some screenshots I made at the start of June (so build 370-ish), and the sync clearance was good on my device for all verses. So something must have changed between then and now.

**Comment by tuomas2** [comment]
@yawnoc can you try this build if it works better for you? 
https://github.com/AndBible/and-bible/releases/tag/build-385-clearance-test

**Comment by tuomas2** [comment]
I could not really reproduce the actual issue, but I think I like a little gap to be there anyway.

**Comment by yawnoc** [comment]
Yes, that's much better. If the gap was 1px bigger, would it start to look too big for you?

![Screenshot_20200710-103122](https://user-images.githubusercontent.com/48375680/87111851-f2a7ee80-c29c-11ea-8d1e-f3d2dbc8be82.jpg)

**Comment by tuomas2** [comment]
I made it relative to line height (0.15 x lineheight). I will try with 0.2 and install also on my devices. If it looks ok then we could go with that.

**Comment by tuomas2** [comment]
Test build with 0.2: https://github.com/AndBible/and-bible/releases/tag/build-385-clearance-test2

**Comment by tuomas2** [comment]
If someone uses linespacing 1.0 it will show already previous line. Perhaps this coefficient (0.2) should be relative to linespacing.

**Comment by tuomas2** [comment]
Yet another test build where coefficient is relative to linespacing: https://github.com/AndBible/and-bible/releases/tag/build-385-clearance-test4

I tested with my devices and this was working pretty nicely.

**Comment by yawnoc** [comment]
Looks good to me, thank you!

**Comment by tuomas2** [comment]
If you didn't already, can you try with different linespacing settings (all text settings -> line spacing)?

**Comment by yawnoc** [comment]
For me, the text touches the top divider at line spacing equal to 1.2x. Anything less than that and the text gets cut off.

At the default 1.6x the clearance is comfortable, and still looks good when dialed up to the maximum 3.0x.

**Comment by tuomas2** [comment]
Can you confirm also that font size does not affect these results?

**Comment by yawnoc** [comment]
Yes, touching the top divider occurs when line spacing is around 1.2x, independent of the font size.

**Comment by tuomas2** [comment]
Will be fixed in build 386
