### ISSUE TITLE
Bookmark history item is delete when tapping the back button... 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#767]
Running build 385;
The items in the history are deleted when hitting the device back button. I don't know if that is intentional or if this is a transparent feature. But once you go to that history item it no longer exists in the list so there is no way to go forward in history.
Also, there needs to be a way to clear the whole history or individual items or selected items from the history, but that sounds more like an added feature.

**Comment by timbze** [comment]
First part is addressed in #386 
#374 also addresses your second point

**Comment by timbze** [comment]
My suggestion is yes. Really it's all duplicate

**Comment by bvahedy** [comment]
Ok, closing this ticket since it's duplicate of the tickets Tim mentioned above.
