### ISSUE TITLE
Arabic RTL, headings not properly displayed

### ISSUE THREAD

**Issue by samuel1** [AndBible/and-bible#78]
Dear guys, thanks for fantastic work

1. In Arabic:  chapter headings are sometimes in the wrong chapter -- so where Galatians chapter 2 has its title at the top;  in Arabic, the same title comes just before the bottom of chapter 1.  This is happens in Galatians chapters 1-5, and in other books.  And only happens when a heading would begin a chapter.  This kind of thing is very common in texts that mix ltr and rtl.  And so is possibly a little related to bug #59???

The font choice for Arabic though is good and clear to read

Android version 4.4.2

**Comment by tuomas2** [comment]
@samuel1 Could you provide screenshots about this problem for reference?

**Comment by tuomas2** [comment]
With AraNav translation, Galatians 2 chapter heading looks like this and indeed it seems to be in wrong place: 

![screenshot_1543653311](https://user-images.githubusercontent.com/5811789/49326045-d4bcc880-f554-11e8-992d-ecba961c3f61.png)

**Comment by tuomas2** [comment]
Xiphos renders the text the same way as And Bible. I'm thinking this most likely is a module issue. I'll report this (1) to sword-devel.

**Comment by tuomas2** [comment]
Split the ticket as there were multiple issues raported: #163 and #164 .

**Comment by tuomas2** [comment]
Closing this issue as it does not look like And Bible code issue, but rather problem in AraNAV module (which I reported to sword-devel mailing list).
