### ISSUE TITLE
Bible selector dropdown behavior improvement suggestion

### ISSUE THREAD

**Issue by treemannul** [AndBible/and-bible#782]
The "quick" pulldown (little cross icon) for selecting Bible or Dictionary is confusing. It would seem more useful to put a check mark by the bible or dictionary you are currently using in the quick list (or highlight it), instead of removing it when selected and also rearranging the list, which is confusing.

If I select "Aleppo" for example, it removes "Aleppo" from the quick pulldown the next time I touch it. I realize it shows the current selection in tiny little letters at the top, but that's the "expanded" name; and, removing it from the list is obscuring the usefulness of a "list" that should not change -- imagine if when you went into the more detailed list (or to "Choose Document"), it removed the one you are currently using.

Alternative: By accident I found that I could long-press on it to get a more detailed selection. Alternatively to the above suggestion, perhaps clicking the little cross icon should just go straight to the detail view?

Thanks for your consideration! Love using this Bible software.

- m

**Comment by tuomas2** [comment]
Good suggestion. We'll try this out for 3.4

**Comment by timbze** [comment]
Somewhat related to #597

**Comment by agrogers** [comment]
I like this suggestion too. I think leaving the current document (Bibles and Commentaries and ??) in the list but highlighting would work fine. Underline, bold, tick beside it perhaps. But

I suggest we delay this one to after v3.4 release

**Comment by agrogers** [comment]
Perhaps we could improve it in a few ways
- Make the list more like the Window popup shown below
- The top of the list could show 
- - preferred versions 
- - at least one recently used version
- Show a checked tick box next to the active version
- Add a pop out list for ALL bibles. It shows what we currently have.
- Add a pop out list for _each_ language which shows another menu with all translations in that language
- The same menu structure could possibly be used for Commentaries although there are way fewer languages so language popouts are probably not needed.

So it might look like this:

KJV
NASB    [x]
............
PEV
YLT
............
ALL Bibles >
Burmese >
English > 
Korean >




------------


![image](https://user-images.githubusercontent.com/13920678/130731845-09f50a38-6f8f-4820-9868-3f839bf5aba7.png)

**Comment by timbze** [comment]
I found that it seems this has been implemented, by "graying out" the currently selected document.
![image](https://github.com/AndBible/and-bible/assets/35117769/ff42bde6-2664-4c21-923c-babdb94d1fb5)

I love this new feature, thanks @tuomas2
