### ISSUE TITLE
Can't backup to Google Drive etc.

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#792]
> At first when I backed up I could choose a number of option eg phone, Google drive, dropbox, onedrive etc. Then suddenly dropbox and onedrive disappeared, sometimes reappearing. Now the only option I get is to thr phone.

Device info:
And Bible version: 3.3.386#ff426cf41 (built 10/07/20 17:42:43)
Android version: 10
Android SDK version: 29
Manufacturer: samsung
Model: SM-A705MN

Storage Mb free: 87665

Used heap memory in Mb: 8
Max heap memory in Mb: 512

**Comment by tuomas2** [comment]
@mattschlosser

**Comment by RuggMatt** [comment]
This was an issue in 3.3.385. I can't reproduce in 3.3.386 but can in 3.3.385. Perhaps the user experienced the issue in that version but didn't get around to reporting it until version 3.3.386. or maybe another device is still on 385? I just tested both versions on my Android 11 phone and all seems fine in 386

 I can test to be sure later today on an Android 10 device, as I don't have access to one at the moment.

**Comment by RuggMatt** [comment]
Ok I tested again in 386 and it seems that there is an issue. 

Strange. 

I will investigate tonight.

**Comment by RuggMatt** [comment]
#775 fixed this but it looks like it hasn't been released, only in beta.

**Comment by tuomas2** [comment]
Then we can close this. I'll say the user that it will be fixed in next (3.3-bugfix) release.

**Comment by bvahedy** [comment]
verified working correctly in 387beta build, It was also working in 386 build, but don't know about 385.
