### ISSUE TITLE
AB doesn't see the other sword folders

### ISSUE THREAD

**Issue by LAfricain** [AndBible/and-bible#794]
**Describe the bug**
I have a other folder with sword modules (root → sword) and Andbible doesn't detect it.
(I'm sorry I think it was already a bug on this but I couldn't find it)

**Bug was found on And Bible version**
version 3.3.386

**To Reproduce**
1. Go to 'Andbible.'
2. Click on 'Open a document.'
3. Bible present in Bishop are missing on Andbible

**Expected behavior**
Find all the folders with modules on the phone.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Wiko lenny3]
 - OS: [Android]
 - Version [6.0]

**Additional context**

**Comment by tuomas2** [comment]
Have you enabled "Manually installed documents exist" option from main menu -> application preferences? That is needed, otherwise And Bible does not see those docs.

**Comment by LAfricain** [comment]
Hello,
I just installed, Andbible 4 on android 11 and I can't find this option... Can help me again please. thank you.

**Comment by timbze** [comment]
Hi @LAfricain I think the jsword folder no longer works after Android 10 because of storage permission changes in Android framework. This will be addressed by #632 if/when someone gets to that. Also see #1762 for reference.
