### ISSUE TITLE
Improve cold start experience

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#797]
When And Bible is closed (removed from task list), it can easily take from 3 to 6 seconds to load.
On my one phone (night mode), it takes about 3 seconds and goes like this:
1. .5 second full white screen
2. 1.5 seconds full black screen
3. Quick flash of startup screen
4. Bible screen comes up with brief black background while text loads
5. Fully loaded

In non-night mode (white mode), steps 2 and 3 are not happening but step 1 seems to take that much longer
Also, with #663 theme improvement, steps 2 and 3 are not happening for either night or non-night mode, but start up time is still the same, with step 1 taking longer.

**My suggestion:**
Build a splash screen with loading indicator to show on cold start. When app is in background and re-opening or switching back to it, splash screen should never show.

**Comment by tuomas2** [comment]
Loading indicator would be just spinner or would you like to have a progress bar? If progress bar, I'm not sure how we could get loading progress status info.

**Comment by timbze** [comment]
> Loading indicator would be just spinner or would you like to have a progress bar? If progress bar, I'm not sure how we could get loading progress status info.

I was thinking just a spinner. If there's a spinner then 3 seconds doesn't feel long, but a blank screen and no movement it can tend to feel long.

**Comment by tuomas2** [comment]
I agree
