### ISSUE TITLE
Improve new user start experience

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#798]
Currently when starting And Bible for the first time, it shows the splash screen on the background with a dialog that says:
> Download a Bible from the Internet?
> clickable link "Load Document From Zip"
> Options to click Cancel or OK (Cancel exits app)

**My suggestion**
- Build a new first-time startup screen, possibly could integrate with same new splash screen mentioned in #797.
  - Show something like "Welcome to the Bible Study app, by And Bible Open Source Project"
  - To continue, would you like to:
    - Load documents from zip file
    - Or download documents from the internet
    - Select existing And Bible backup to restore
      - Show documents that And Bible backup had, but not currently installed and ask user if he/she wants to re-download those documents from the internet (i.e. checklist where user can choose to uncheck any modules or accept all checked) (related #384)
  - Allow user to select night mode if desired
  - Give option to skip or go through a quick (between 3-6 step) tutorial on the basics of how to use And Bible

**Comment by tuomas2** [comment]
Good ideas!

**Comment by timbze** [comment]
I think most of this issue has been addressed, except for these items below. Since I think the most important aspects have been addressed, I will close this issue. If someone wants to continue work on any of these points then a new issue could be made.

> * Select existing And Bible backup to restore
> * Allow user to select night mode if desired
> * Give option to skip or go through a quick (between 3-6 step) tutorial on the basics of how to use And Bible

**Comment by tuomas2** [comment]
> * Select existing And Bible backup to restore

this was a mistake? There's "Restore database file" button in startup screen.

**Comment by timbze** [comment]
> > * Select existing And Bible backup to restore
> 
> this was a mistake? There's "Restore database file" button in startup screen.

You are correct. I only looked at layout file, but now see it's set programmatically on existing button. (StartupActivity.kt L#209)
