### ISSUE TITLE
Window button bar sometimes hidden completely

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#799]
1. Create 2 workspaces with different number of windows
2. Go to the workspace which has larger number of windows
3. Hide window button bar from its hide button
4. Switch to the another workspace that has less windows
  -> window button bar is completely hidden

**Comment by bvahedy** [comment]
I was able to duplicate this. For now if you double tap on the window to go
to full screen mode will cause the window button to display.

**Comment by timbze** [comment]
I can not reproduce this in 4.0-beta now

**Comment by tuomas2** [comment]
Was fixed in 42c8a2a98956280caf1f6e373d36b17ea38f1230 (this is duplicate of #1468)
