### ISSUE TITLE
Handle InstallExceptions better

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#805]

**Comment by tuomas2** [comment]
also 

org.crosswire.jsword.book.install.InstallException: Unable to find: http://ebible.org/sword/zip/engwebster1833eb.zip

**Comment by timbze** [comment]
Another bug report with log file attached: https://support.andbible.org/scp/tickets.php?id=50
```
Exception:
org.crosswire.jsword.book.install.InstallException: Unable to find: https://www.crosswire.org/ftpmirror/pub/sword/packages/rawzip/Hitchcock.zip
```

**Comment by tuomas2** [comment]
I think these are due to downtime of Crosswire server. Looks like it works for me.

**Comment by timbze** [comment]
That's possible but why do we keep getting these bug reports? Is it a crash? Or a message saying error occurred? Maybe the handling of this issue needs improvement

**Comment by tuomas2** [comment]
Hmm. That's true. I think it should already handle gracefully situation when server is down and not give this kind of error. Though, it does handle it nicely in initial repository listing downloading, but maybe not when user tries to download a module.

![handling](https://user-images.githubusercontent.com/5811789/80281552-95c47f80-8714-11ea-90f5-39427a30b8bc.png)

**Comment by tuomas2** [comment]
This probably can't be done without introducing new strings, so I would like to implement this rather in 3.4.

**Comment by tuomas2** [comment]
Again here: https://support.andbible.org/scp/tickets.php?id=132

I was simulating the error by adding throw Exception() to net.bible.android.control.download.DownloadQueue#addDocumentToDownloadQueue (line 47 in DownloadQueue.kt),
but I got only this:
![Screenshot_1602341497](https://user-images.githubusercontent.com/5811789/95658193-48e92f80-0b21-11eb-8f45-14f0c0fe8a71.png)

I can't understand yet how user has got suggestion for error reporting.

**Comment by timbze** [comment]
The issue is here, this `instance.showErrorMsg` has "Send email" option. It should probably be changed to `throw ex`, that way the `try catch` you were looking at would catch it.
https://github.com/AndBible/and-bible/blob/f101f39a4a62e4c436e3ab8e62ac334434d84720/app/src/main/java/net/bible/service/download/DownloadManager.kt#L123

**Comment by tuomas2** [comment]
Hmm okay, if we remove that try-catch from installBook, then it catches exception in addDocumentToDownloadQueue, giving the error of the screenshot, which is better.

**Comment by tuomas2** [comment]
Is there anything we could still make better?

**Comment by tuomas2** [comment]
Perhaps in addDocumentToDownloadQueue we could give even better error message, if InstallException is caught.

**Comment by tuomas2** [comment]
like: "Downloading module X failed. It might be due to module being removed from the repository server, or misconfiguration of the repository. Please try again and if error does not disappear, please report". 
Buttons:
[ok] -> refreshes lists
[report] -> takes to bug report

**Comment by tuomas2** [comment]
I improved handling this in dev. I think this can be closed now.
