### ISSUE TITLE
RTL align issue

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#806]
When justify text is disabled, arabic text is aligned to the left side of the screen.
It should be aligned to the right side of the screen.

**Comment by bvahedy** [comment]
So, for RTL Bibles justify text option should work the opposite?

**Comment by tuomas2** [comment]
I think with justify disabled, it should be aligned to the right side of the screen?

**Comment by tuomas2** [comment]
This might be even a regression, I'm thinking it might work properly in 3.2.

**Comment by bvahedy** [comment]
I agree.

**Comment by tuomas2** [comment]
Will be fixed in 389

**Comment by bvahedy** [comment]
Verified fix in 389 beta build.
