### ISSUE TITLE
map module backup not complete

### ISSUE THREAD

**Issue by luweitest** [AndBible/and-bible#810]
**Describe the bug**
Backup|export modules like "SmithBibleAtlas", "HistMidEast" not complete: only mods.d file present in the result zip file, nothing else.

**Bug was found on And Bible version**
3.3.388

**To Reproduce**
1. Go to 'Backup and restore'
2. Click on 'Backup documents to...'
3. Scroll down to 'Smith bible atlas'
4. Click "OK"
5. Chose "File manager +"
6. Select a folder and save.
7. Open modules.zip and check.

**Expected behavior**
There should be other module files besides "mods.d" file.

**Smartphone (please complete the following information):**
 - Device: vivo z5x
 - OS: Android
 - Version 9

**Comment by tuomas2** [comment]
Will be fixed in 389
