### ISSUE TITLE
CI Protected branch prevents automatic merging

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#812]
**Auto merge from current-stable to master and release/ branches**
PR #804 is not working because of protected branches. Reference #730
See the run failing here: https://github.com/AndBible/and-bible/runs/974922197

See [this](https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/29) and [this](https://github.community/t/allowing-github-actions-bot-to-push-to-protected-branch/16536/6)

**Comment by tuomas2** [comment]
#829 closed this
