### ISSUE TITLE
Speak: text jumps to the beginning of chapter

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#820]
In my Bible reading, while using speak, I scroll down to follow the text and after ten to fifteen verses, the screen jumps to the beginning of the chapter, causing me to scroll down again to find which verse the app is speaking. This annoys me. Please check. 

--- WRITE BUG REPORT ABOVE THIS LINE ---
Instructions:
Tell us briefly what did you do / what happened when the issue took place. Example:

1. Opened app
2. Clicked window menu
-> Crash

Sometimes screenshot also is beneficial in resolving issues. Please use this function to report as soon as you have noticed it taking place. You can also use this function after opening the app, after the crash has taken place.

Device info:
And Bible version: 3.3.389#56bab7d (built 20/08/20 11:35:18)
Android version: 9
Android SDK version: 28
Manufacturer: samsung
Model: SM-J730G

Storage Mb free: 1424

Used heap memory in Mb: 19
Max heap memory in Mb: 192

More info and logcat: https://support.andbible.org/scp/tickets.php?id=78

**Comment by timbze** [comment]
This has to do with Reading Plans, probably related to #323 and #300. Though I don't know if it's an issue that would happen without reading plan too.

**Comment by tuomas2** [comment]
Similar issue:

> While reading Mat 17:20, the text scrolling jumps to Mat 16:1 but it continues reading Mat 17:22. The scrolling reunites with the voice at Mat 17:23. This occurs in two translations which omit the verse Mat 17:21.

https://support.andbible.org/scp/tickets.php?id=380
(ticket includes video demonstrating the issue)

**Comment by timbze** [comment]
Will be fixed when #300 is addressed
