### ISSUE TITLE
And Bible does not download properly from Crosswire

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#823]
Related:
https://support.andbible.org/scp/tickets.php?id=66
https://support.andbible.org/scp/tickets.php?id=81

**Comment by tuomas2** [comment]
Crosswire seem to have switched to use Let's encrypt certificates.
That does not work with older Android versions now.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=66#note

-> API 27 should work though (tested on emulator).

**Comment by tuomas2** [comment]
Seem to be affecting only APIs 21 to 22. (I.e. lollipop).

**Comment by tuomas2** [comment]
Though for APIs 21 and 22 it does seem to handle error nicely. User probably did not receive this error because AB did not refresh the sources, but user started downloading based on old listings (?).

![Screenshot_1599125239](https://user-images.githubusercontent.com/5811789/92097536-daf26f80-ede0-11ea-9d7f-f58395cd07fa.png)

**Comment by timbze** [comment]
Should we retry with http on those older apis when https does not work?

1. Try download/retrieve https
2. If it fails and api is lower than (23?), then try http

**Comment by tuomas2** [comment]
I'm trying something else right now. I'll tell more later.

**Comment by tuomas2** [comment]
Actually, got it just working. 

Will make exception for old phones that does not verify hostnames.

Something like this.

```
        client = HttpClientBuilder.create()
                .setDefaultRequestConfig(builder.build())
                .setConnectionManager(
                        PoolingHttpClientConnectionManagerBuilder.create()
                                .setSSLSocketFactory(
                                        SSLConnectionSocketFactoryBuilder.create()
                                                .setHostnameVerifier(new HostnameVerifier() {
                                                    @Override
                                                    public boolean verify(String s, SSLSession sslSession) {
                                                        return true;
                                                    }
                                                })
                                                .build()
                                ).build())
                .build();
```

**Comment by tuomas2** [comment]
Upgrading httpclient at the same time to 5.0.1 (jsword side).

**Comment by tuomas2** [comment]
Will be fixed in build 390. 

Please review the commits listed above (jsword and And Bible).

**Comment by timbze** [comment]
> Will be fixed in build 390.
> 
> Please review the commits listed above (jsword and And Bible).

Looks good

**Comment by tuomas2** [comment]
Still getting this (or similar) issue. Not lollipop though.  https://support.andbible.org/scp/tickets.php?id=85

**Comment by timbze** [comment]
SSL proxies, or VPNs, could possibly cause this.
Work-around would be to switch to http, either automatically or ask the user if that's OK.

[Here's some info](https://stackoverflow.com/a/6378872/877453) about SSL exceptions

**Comment by tuomas2** [comment]
If we go with HTTP fallback then we need to allow http-only for AB repo too. 

Now we promise HTTPS to users, so this need new strings. 
Instead of HTTP we could possibly also do what we did for Android 5 as a fallback, but asking permission from user.

**Comment by timbze** [comment]
Good idea. Something like

"There is an issue with downloading the module securely via HTTPS. Do you want to download anyway?
[link] See more
On click show:
The security certificate for [andbible.org] could not be verified. This could happen if you are using a proxy, or if an attacker is trying to intercept the connection. You can continue to download at your own risk with the unverified connection."

**Comment by tuomas2** [comment]
Trying something else (like suggested in https://stackoverflow.com/a/6378872/877453); extracting lets encrypt cert and storing it into another keystore.

`keytool -import -v -trustcacerts -alias 0 -file letsencrypt.pem -keystore andbible.bks -storetype BKS -provider org.bouncycastle.jce.provider.BouncyCastleProvider -providerpath /home/tairaksinen/android-studio/lib/bcprov-jdk15on-1.64.jar -storepass andbible
`
https://stackoverflow.com/questions/11117486/wrong-version-of-keystore-on-android-call

let's see.

**Comment by timbze** [comment]
I don't know if or how many of these issues are caused by ssl proxy, but I don't think this solution will help for that.

If internet connection goes through ssl proxy, then every ssl connection is untrusted. In such cases the client does not receive the server certificate, but some man-in-the-middle cert, hence untrusted.

**Comment by tuomas2** [comment]
One more instance https://support.andbible.org/scp/tickets.php?id=95

Non-lollipop instances of this error seem to be a bit different actually.

Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by tuomas2** [comment]
Probably does not help to CertPathValidatorException if it is caused by VPN / proxy as @timbze suggested. But helps for Lollipop. 

As bonus, we got rid of one dependency, resulting even smaller APK.

**Comment by tuomas2** [comment]
Reviewing above commits welcome :-) (especially https://github.com/AndBible/jsword/commit/1d640140f4d480ef725118715692ff27d351df70)
