### ISSUE TITLE
Find should automatically open the keyboard

### ISSUE THREAD

**Issue by RuggMatt** [AndBible/and-bible#825]
**Is your feature request related to a problem? Please describe.**
I find it annoying to have to click twice when opening the find pane. Once to click on the find button and then again on the search field. 

**Describe the solution you'd like**
The search field should automatically focus and the keyboard automatically open. 

**Describe alternatives you've considered**

**Additional context**
🙂
I think I'll fix this myself

**Comment by tuomas2** [comment]
Let's mark this to 3.4, but perhaps you could do this against current-stable as I might re-consider having it in 3.3 too.
