### ISSUE TITLE
3-dot menu not updating "Night mode" setting after changing application preferences

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#833]
**Describe the bug**
1. Change Application Preferences "Night mode switching" setting from System to Manual or vice versa
2. 3-dot menu should show check box for "Night mode", when it's not on "System", but be hidden when on "System"
3. The setting visibility does not update till app has been restarted or some other screen update like workspace change

**Bug was found on And Bible version**
390.1 (beta)

Android 10 Pixel 3

**Comment by tuomas2** [comment]
I think this is not affecting 3.3, right?

**Comment by bvahedy** [comment]
It has worked correctly in builds up to  389 beta. I will check the latest 390.1 build tomorrow but it may be only happening on certain devices.

**Comment by timbze** [comment]
> I think this is not affecting 3.3, right?

You're right, just double checked

**Comment by tuomas2** [comment]
Should be fixed
