### ISSUE TITLE
Adding CSB to the collection

### ISSUE THREAD

**Issue by DonaldTsang** [AndBible/and-bible#837]
There has been this bible that claims to be as easy to read as possible while maintaining meaning

https://csbible.com is the main page and https://read.csbible.com/ is the site.
There are also reading plans in the website https://csbible.com/read-the-csb/reading-plans/

The only issue is whether the copyright can be obtained or not.
They have an app that is made by https://tecartabible.com/ (with even more versions).
They did say in https://csbible.com/about-the-csb/faqs/#faq/is-the-csb-available-on-my-favorite-bible-apps-and-digital-platforms
> We are working diligently with many partners to ensure that you will be able to access the Christian Standard Bible everywhere Bible translations appear.

**Comment by tuomas2** [comment]
Hi, as this is copyrighted work, please see https://github.com/AndBible/and-bible/wiki/FAQ#i-found-text-issue-in-one-of-the-bible--commentary-etc-modules-in-and-bible and try primarily to get it to Crosswire's module repository.
