### ISSUE TITLE
Notes: Clicking find while in a note does nothing. 

### ISSUE THREAD

**Issue by RuggMatt** [AndBible/and-bible#841]
**Describe the bug**
Trying to open **Find** from the menu when a note is open  doesn't open Find. 

**Bug was found on And Bible version**
3.389

**To Reproduce**
1. Open any note
2. Open Menu and select Find

**Expected behavior**
Search opens .

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 4XL
 - OS: Android 11 Beta 3

**Additional context**

**Comment by timbze** [comment]
It was disabled in #703 to prevent crash, but in my opinion a proper fix would be to fix find so that it would search in last active window.

**Comment by RuggMatt** [comment]
Or replace the menu button with just a back button?

**Comment by timbze** [comment]
That might be a good option. Some of the flow and logic might change with #188 but until then, maybe the back button would be good.

**Comment by tuomas2** [comment]
Tested with current version and searching in my note window is disabled, which is correct behavior until searching is properly implemented (#862). Closing.
