### ISSUE TITLE
Window buttons not displayed when opened in split screen

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#847]
1. Open some other app in upper screen
2. Open And Bible in lower screen
 -> window button bar will go under system nav bar

This is reproduced with my samsung tablet @ android 10. 3d0df998, dev branch (build 390.1 or so).
Probably does not reproduce with 3.3.

**Comment by tuomas2** [comment]
@mattschlosser this might be related to the changes you have made recently

**Comment by RuggMatt** [comment]
I can also reproduce. :+1:

**Comment by RuggMatt** [comment]
Also can reproduce on 3.3.390 (Play store)

**Comment by tuomas2** [comment]
Seem to be only on Android 10 (and probably on more recent as well).
