### ISSUE TITLE
Acra error emails are empty

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#853]
tested with build 392 (develop). not releasing 392 to play store before this is fixed.

**Comment by tuomas2** [comment]
in emulator i didn't have this problem

**Comment by timbze** [comment]
https://github.com/ACRA/acra/issues/744
https://github.com/ACRA/acra/issues/807

Very weird issue. Gmail has the same problem for me, but other mail app works.

**Comment by tuomas2** [comment]
But on the other hand our old email sender did not have this issue.

**Comment by timbze** [comment]
@tuomas2 do we still want to investigate more to use ACRA or leave it now that it's implemented differently? (8c5c8d96a150b64eea290f33d53b640932de6d8d)

Also #855 can be closed if we don't want to use ACRA anyway

**Comment by tuomas2** [comment]
I'm quite satisfied with the current implementation that also reports crashes when next time starting app. So I'm okay with closing these.
