### ISSUE TITLE
Bluetooth headphone button support for speak

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#867]

**Comment by tuomas2** [comment]
Figured out that bibleview grabs media keys when main activity is up (thus it does not make its way to onKeyDown).

**Comment by tuomas2** [comment]
I think this post explains why I have been struggling on getting this working (I did already back in 2020 when implementing the current TTS system): https://stackoverflow.com/questions/45960265/android-o-oreo-8-and-higher-media-buttons-issue

**Comment by agrogers** [comment]
Easy solution once you know what it is
