### ISSUE TITLE
"Not found in document" and jumping to not-existing verse after opening minimised window

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#868]
From @timbze https://support.andbible.org/scp/tickets.php?id=138

> Had a similar issue as 741 again (on development branch)
> 
> 1. With multiple pinned and unpinned windows, only have pinned window 1 visible (KJV at Luke 7:28)
> 2. Go to Colossians 3 and scroll down to verse 11
> 3. Click pinned window 2 (NASB)
> 4. Pinned window 2 opens at Col 3:11, but window 1 jumps to "Not found in document" and title shows (Col 7:28)
> 
> These are the exact steps I did, but I was unable to reproduce it with trying the steps again.
> 
> Device info:
> And Bible version: 3.3.392#e7d10d0 (built 09/10/20 13:02:53)
> Android version: 11
> Android SDK version: 30
> Manufacturer: Google
> Model: Pixel 3
> 
> Storage Mb free: 26008
> 
> Used heap memory in Mb: 14
> Max heap memory in Mb: 192

**Comment by tuomas2** [comment]
Screenshot and logcat in support desk

**Comment by timbze** [comment]
Don't think this needs fixing for 3.3 and have never had the issue in 4.0-beta
