### ISSUE TITLE
Shortcut to edit bookmark labels

### ISSUE THREAD

**Issue by mjdenham** [AndBible/and-bible#88]
Currently you can only view and edit an existing bookmark's labels by finding the verse in a long list of bookmarks and then long-pressing the bookmark.  However, I think you wanted a way to go directly to the labels page from the chapter, a bit like the way you can delete a bookmark if you highlight a bookmarked verse, I think you also wish to be able to edit the labels for the currently highlighted verse.

**Comment by tuomas2** [comment]
This is implemented.
