### ISSUE TITLE
Crash when closing window

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#881]
1. Set up one normal and links window
2. minimise links window
3. Close first window.
-> crash

https://support.andbible.org/scp/tickets.php?id=160

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=166

**Comment by tuomas2** [comment]
Adding more logging to windowRepository etc.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=177

**Comment by tuomas2** [comment]
Will be fixed in build 399

**Comment by bvahedy** [comment]
Verified fixed in 399 build.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=180 (using 3.3.397)
