### ISSUE TITLE
Gill missing some text

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#882]
Gill's commentary on Judges, Jonah, and Philemon is not available. I've attached a screenshot of the books of the Bible available when I'm in a window connected to Gill's commentary. The other screenshot showing the "not found in document" message.

https://support.andbible.org/scp/tickets.php?id=161

**Comment by tuomas2** [comment]
Should check if Xiphos shows these chapters

**Comment by timbze** [comment]
I confirmed in diatheke that those 3 books have no content in the module

**Comment by tuomas2** [comment]
Gill is not released in Crosswire repository. Should figure out who is maintaining it (Xiphos developer?) and where is the source text.

**Comment by timbze** [comment]
Closing as duplicate of #2166
