### ISSUE TITLE
Use CSS from module zip file

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#883]

**Comment by tuomas2** [comment]
Implemented in e6777b20d3f69e72e8875283cf49196253912388

**Comment by LAfricain** [comment]
Hi,
I'm curious how we can use this feature? By instance I have a css with ktuVB, but I can't see it?

**Comment by tuomas2** [comment]
Here is documentation for CSS modules: 

https://github.com/AndBible/and-bible/wiki/Custom-CSS-for-modules-for-And-Bible

**Comment by LAfricain** [comment]
Thank you for the link. But why not using the default setting in the conf, as provided by sword?
`PreferredCSSXHTML=style.css`
I did many modules with a custon css, but I can't explain to all the user how to change the entry. Or may I ask Dom to build the conf with a new entry for Andbible?

**Comment by tuomas2** [comment]
As seen in examples, CSS that is written for AndBible requires namespacing CSS attributes for the module (because one BibleView renderer DOM may have multiple documents with different CSS). Also different frontends render OSIS XML fragments differently, so same CSS would not necessarily work with different frontends anyway.

**Comment by tuomas2** [comment]
Also, AndBible's renderer has a lot of UI stuff in it, and non-namespaced CSS could mess up the UI (dialogs etc inside BibleView).
