### ISSUE TITLE
Text left Alignment 

### ISSUE THREAD

**Issue by philip707** [AndBible/and-bible#884]
Now the Bible text is in Justify alignment, Pls make it optional from left, right and justify

**Comment by tuomas2** [comment]
it is already optional: window menu (or workplace menu, i.e. right-corner menu) -> all text options -> justify-align text.

**Comment by philip707** [comment]
Thank you Brother...

**Comment by alerque** [comment]
Wow how long has this been there? Even I didn't know about it and I've wanted it ;-) Also I see the setting string is not localized into Turkish, which is partly my fault. Apparently I'm behind — and this must be relatively new.

Great to see so much progress in this app recently by the way!

**Comment by tuomas2** [comment]
This new option came with 3.3 release in June.
