### ISSUE TITLE
KJV does not show crossreferences / footnotes

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#891]
KJV does not show crossreferences / footnotes, although it does have those.

https://support.andbible.org/scp/tickets.php?id=151

**Comment by bvahedy** [comment]
Unable to duplicate. 
![SmartSelect_20201115-102346_Bible Study](https://user-images.githubusercontent.com/46405809/99193251-af6afa00-272c-11eb-8bb2-9d52b4e96d76.jpg)

**Comment by timbze** [comment]
I believe this is simply that KJV doesn't have a lot of footnotes. The user who reported it probably has a KJV paper Bible by some publisher with a lot of notes, but the Sword version is not from such publisher.
