### ISSUE TITLE
Horizontal overflow: no spaces between Hebrew Qere and Ketiv

### ISSUE THREAD

**Issue by yawnoc** [AndBible/and-bible#894]
Westminster Leningrad Codex (WLC) is formatted without spaces between [Qere and Ketiv](https://en.wikipedia.org/wiki/Qere_and_Ketiv), which are "read" and "written" versions respectively. This results in a very long run of Hebrew letters which does not break, and causes all verses of the chapter to overflow horizontally. Attempting to horizontally scroll the verse back into view causes the chapter to increment (see #501).

Version 3.3.399

To reproduce:
1. Switch to WLC
2. Navigate to Daniel 5:23
3. Increase Font size to 24pt

![24pt Hebrew causes horizontal overflow](https://user-images.githubusercontent.com/48375680/99215075-e9abc880-280c-11eb-8ab9-29ace355d0d8.jpg)

I think this can be fixed by adding spaces and deciding on a good way to mark the Qere and Ketiv.

* [Bible Hub](https://biblehub.com/texts/daniel/5-23.htm) uses plaintext bracketing with a suffix, `(<qere> ק)` and `[<ketiv> כ]`:
  
  ![Bible Hub Qere and Ketiv](https://user-images.githubusercontent.com/48375680/99216860-b4ee4000-2811-11eb-8699-3febb2620be6.png)
* [tanach.us](https://www.tanach.us/) formats with classes:
  
  ![tanach.us Qere and Ketiv](https://user-images.githubusercontent.com/48375680/99217159-60979000-2812-11eb-82f2-54de6aed358c.png)

**Comment by bvahedy** [comment]
I'm unable to duplicate this. Try using a different font in the jsword folder on the local storage on your device and see if that will fix the issue:
![Screenshot_20201116-080649_Bible Study](https://user-images.githubusercontent.com/46405809/99277828-2793f700-27e3-11eb-91c8-673e92eb3330.jpg)

**Comment by yawnoc** [comment]
Is it possible that we have different versions of WLC installed? I have Version&nbsp;1.9 (2013-10-11).

This exact issue was reported to Crosswire in 2014, in [API-181](https://tracker.crosswire.org/browse/API-181) (still open):
> The Hebrew WLC module contains:
> - 1265 x-ketiv
> - 1277 x-qere
>
> These are both type attribute values for the element `w`.
> [...]
> [...] Qere/Ketiv words are joined without any spaces to the preceding text.

The only other related mention of Qere and Ketiv in Crosswire occurs in [comment 53525 in MOD-350](https://tracker.crosswire.org/browse/MOD-350?focusedCommentId=53525&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-53525). It seems to imply the existence of an experimental version of the WLC module in which the runs are fixed (but with different delimiters to @bvahedy's screenshot):
> SwordVersionDate=2014-12-18
> Version=2.2
> [...]
> History_2.0=2014-04-06 Experimental test version [...]. Also supplied the missing space before each Ketiv & Qere. Joined nearly all the consecutive doubles for Ketiv & Qere pairs. As expected for the Hebrew Bible, there are some unpaired Qere & Ketiv. Delimited Ketiv & Qere. Ketiv words are delimited using `[ ... /` while Qere words are delimited using `/ ... ]`. Thus a Ketiv Qere pair looks like `[ ... / / ... ]`. The space after each 'word' is now systematically placed before its trailing `</w>`.

**Comment by bvahedy** [comment]
My version is 1.4:
![Screenshot_20201119-090456_Bible Study](https://user-images.githubusercontent.com/46405809/99699138-79888700-2a46-11eb-9f90-8e9a50de9a75.jpg)

**Comment by yawnoc** [comment]
Closing because the issue has been fixed as of 'Westminster Leningrad Codex' Version&nbsp;2.0 (2022-09-17), distributed by CrossWire.

Alternatively one can use 'Westminster Leningrad Codex Hebrew OT' Version&nbsp;3.85 (2023-03-03), distributed by eBible.
