### ISSUE TITLE
Show Red Letters option only for modules that support it

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#895]
Red letters cause confusion as not all modules support it. Better to hide option if it's not doing anything.

**Comment by timbze** [comment]
I believe the option should be shown disabled with note (Not available for this module). That way people won't come to the conclusion that And Bible does not have red letter if they have a wrong module installed.

**Comment by onomou** [comment]
What about just adding a parenthetical note, like `Show words of Christ in red (if module supports it)` and save some work? It would save a lot of work, allow the user to toggle the setting regardless of whether the module has red letter support, and doesn't send the wrong message that AndBible doesn't support red lettering.

**Comment by agrogers** [comment]
I suggest we delay this one to after v3.4 release

**Comment by tuomas2** [comment]
"Not available for this module" text is not in strings, so that we must leave to 4.1

**Comment by tuomas2** [comment]
#1600
