### ISSUE TITLE
choose one dictionary as default strongs search module but failed

### ISSUE THREAD

**Issue by JacobZy** [AndBible/and-bible#897]
**Describe the bug**
choose diffrent dictionary module as default strongs search module but app always auto switch to the StrongsRealGreek/StrongsRealHebrew module

**Bug was found on And Bible version**
version 3.3.399#24411f9

**To Reproduce**
1. Go to kjv module
2. Click on any strong number,such as '07225'
3. a new window show up, it is StrongsRealHebrew and show content of strongs 07225 entry
4. Click on 'choose document menu',choose AbbottSmithStrongs and open it. so the panel switch frome module StrongsRealHebrew to AbbottSmithStrongs
5. in bible main window click on another strong number,such as '0430'
6. the dictionary panel just auto switch to StrongsRealHebrew and show 0430 entry. but AbbottSmithStrongs module which user choose should remain show in the window.

**Expected behavior**
1. dictionary module user chosen should not auto switch to other module
2. also it will be more convenient  if the app has a top right button used for switching dictionary module as commentary button

**Smartphone (please complete the following information):**
 - Device: [motorola]
 - OS: [Android]
 - Version [10.0]

**Comment by timbze** [comment]
I'm closing in favor of #946 

I have not confirmed, but think this may have worked in 3.2, based on some commits I researched in this comment: https://github.com/AndBible/and-bible/issues/597#issuecomment-808419435

More specifically, a method something like `SuggestedDictionaries()` was removed for version 3.3.
