### ISSUE TITLE
Cross-reference window show as a normal window / commentary window

### ISSUE THREAD

**Issue by JacobZy** [AndBible/and-bible#898]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when click crossref link in ESV2011 module. Pop up an new window and after click one ref will change main bible window location. and no way back to the crossref window to click another link,assume one crossref entry has many ref items

**Describe the solution you'd like**
when click crossref link in bible, the ref list result can show in a normal window and the bible window remain show up, when click each ref item show the according bible in one not pined window

**Describe alternatives you've considered**
when click crossref link, the ref list result can show in the commentary window, when click each item show the according bible context in one not pined window

**Comment by tuomas2** [comment]
Some related changes are in upcoming #888, that I need to still test if they provide good UX.

**Comment by JacobZy** [comment]
Your guys are amazing! The AndBible is such a great app.very easy to use and neat with new tech implemented. Appreciate your work, thank you all guys!

**Comment by tuomas2** [comment]
UX is different now for x-refs, so closing this.
