### ISSUE TITLE
How can i start?

### ISSUE THREAD

**Issue by GauravCreed** [AndBible/and-bible#90]
HI @qmx 

i just configure this repository  as instruction , and work well, but how can i configure in different project ,like i want only bible list, and only dictionary in a separate, as per my requirement, 

so how can i start..?

is there any developer  documentation for basic start...?  then please guide me.

Thanks.(_)

**Comment by GauravCreed** [comment]
Hi @qmx 

Is there is any start up document for the api to getting only bible data and download for it.then please suggest me.

Thanks (_)

**Comment by lramage94** [comment]
You might want to take a look at this,

https://www.crosswire.org/sword/develop/index.jsp

**Comment by tuomas2** [comment]
@GauravCreed did you find the information you needed? If not, please re-open this issue.

I'll go through And Bible development documentation at some point in the future and see if it is good enough.
