### ISSUE TITLE
Allow pinch to zoom on compare screen. 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#907]
When selecting a verse and then tapping on the icon on tool bar at the top to compare and view with all Bible translation in the library. The font size is a bit small for many users. If pinch to zoom can be used it eliminates any individual font adjustments.

**Comment by tuomas2** [comment]
Was this your own idea or is it coming from users?

**Comment by bvahedy** [comment]
It came from a user I was responding to yesterday on a ticket.

**Comment by tuomas2** [comment]
I see. Please add ticket link as a reference. Thanks!

**Comment by bvahedy** [comment]
I did, it's on the ticket to the user who requested it. And the ticket is
still open. Here is the link:

https://support.andbible.org/scp/tickets.php?id=211#reply

**Comment by tuomas2** [comment]
Thank you! This is what I meant, I need also link to support desk ticket from  here, to find the original support desk issue.
So both side linking is needed:
- Link from github to support desk
- Link from support desk to github

**Comment by bvahedy** [comment]
Got it.

**Comment by tuomas2** [comment]
Compare screen is now in bible view, where font size can be adjusted, thus closing.
