### ISSUE TITLE
jsword folder is not seen in build 305 under Android 10 OS

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#908]
Using build 399 in Android 10 the jsword folder is not read when though storage permissions is given.
I tried build 3.1.305 and it seems to read the folder correctly. So the big exists in build 399.
This is what it should look like: (305 build)
![Screenshot_20201129-173002_And Bible](https://user-images.githubusercontent.com/46405809/100560651-55f5e580-326b-11eb-9794-d6bbba96c06f.jpg)

This is the wrong format: (399 build)
![Screenshot_20201129-173701_Bible Study](https://user-images.githubusercontent.com/46405809/100560724-8fc6ec00-326b-11eb-9c75-03098445ad6a.jpg)

**Comment by tuomas2** [comment]
Android 10, If I remember correctly, does not allow any more free access to any folder. So we need to stick to our app folder in Android/ subfolder.

**Comment by bvahedy** [comment]
But build 305 under Android 10 works as you can see in the first screenshot above. It may be the way build 399 is reading the storage directory path.

**Comment by bvahedy** [comment]
It could also be looking for an exact case sensitive folder name. I noticed that it does that with module names in the Android/data/... Subfolders.
I remember this issue happening in older builds and you fixed it, somehow the bug came back.

**Comment by tuomas2** [comment]
It is possible that still in Android 10 apps with target sdk < 29 work. But not any more as we target to 29.

https://developer.android.com/about/versions/10/privacy/changes

**Comment by bvahedy** [comment]
I do not think that is the case, since the app is already reading/writing to local storage for database backup/restore.
Also there is nothing in the sdk 29 that prevents reading and recognizing local storage files, it talks about external storage.

**Comment by tuomas2** [comment]
Ping @AndBible/developers ^

**Comment by JJK96** [comment]
I can confirm this issue on my device.

**Comment by tuomas2** [comment]
Also https://support.andbible.org/scp/tickets.php?id=249 (custom reading plans) @timbze

**Comment by ildar** [comment]
Authentication Required

**Comment by tuomas2** [comment]
> Authentication Required

That area is for developer team only. But original messages are (sometimes) useful for tracking down the issue so we always give reference to those tickets here.

**Comment by timbze** [comment]
Related: #632

**Comment by tuomas2** [comment]
This feature is disabled for Android 10+. #632 will fix this for Android 10+. This feature is mostly obsolete due to other improvements in develop. Closing this now.
