### ISSUE TITLE
"Rate & Review in Google Play" in F-Droid and standalone builds

### ISSUE THREAD

**Issue by oxr463** [AndBible/and-bible#919]
**Describe the bug**

**Bug was found on And Bible version**
version 3.3.399

**To Reproduce**
1. Download APK from GitHub Releases or F-Droid.
2. Open the all.
3. Open the side menu.

**Expected behavior**
I would not expect to see that entry in the menu for non-google-play releaaes.

**Screenshots**

![IMG_20210117_101131](https://user-images.githubusercontent.com/43783393/104847151-69f1b700-58ac-11eb-93ed-9c057d13e48b.jpg)

**Smartphone (please complete the following information):**
 - Device: Motorola G7
 - OS: Android
 - Version 10

**Additional context**
N/A

**Comment by timbze** [comment]
I don't think it's necessarily a problem. I don't think F-Droid users are lost about what Google play store is. They can ignore it if they don't have Google Play or don't want to rate (like other users do too who don't want to rate it)

**Comment by tuomas2** [comment]
> I don't think it's necessarily a problem. I don't think F-Droid users are lost about what Google play store is. They can ignore it if they don't have Google Play or don't want to rate (like other users do too who don't want to rate it)

Closing based on these thoughts.
