### ISSUE TITLE
Fix bug ":app:npmUpgrade"

### ISSUE THREAD

**Issue by Arclud** [AndBible/and-bible#921]
## Description

I follow below link for build project
https://github.com/AndBible/and-bible/wiki/Developer-documentation

I can not install .apk because I have problem

## Operation system

Windows 10

## Note

I do not use emulator

## Error code

`npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code EPERM
npm ERR! syscall unlink
npm ERR! path C:\Users\rustam\mydevdir\and-bible\app\bibleview-js\node_modules\.staging\util-e77eeffc\README.md
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\ArHanGeL\mydevdir\and-bible\app\bibleview-js\node_modules\.staging\util-e77eeffc\README.md'
npm ERR!  [Error: EPERM: operation not permitted, unlink 'C:\Users\ArHanGeL\mydevdir\and-bible\app\bibleview-js\node_modules\.staging\util-e77eeffc\README.md'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\rustam\\mydevdir\\and-bible\\app\\bibleview-js\\node_modules\\.staging\\util-e77eeffc\\README.md'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rustam\AppData\Local\npm-cache\_logs\2021-01-19T18_27_17_334Z-debug.log
npm ERR! code 4294963248
npm ERR! path C:\Users\rustam\mydevdir\and-bible\app\bibleview-js
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm install --save-dev npm@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rustam\AppData\Local\npm-cache\_logs\2021-01-19T18_27_36_052Z-debug.log

> Task :app:npmUpgrade FAILED

Execution failed for task ':app:npmUpgrade'.
> Process 'command 'npx.cmd'' finished with non-zero exit value -4048`

**Comment by Arclud** [comment]
@tuomas2 Could you help me ?

**Comment by timbze** [comment]
Did you run Android Studio as Administrator? Maybe you could try that

**Comment by Arclud** [comment]
> Did you run Android Studio as Administrator? Maybe you could try that

Thank you , I will try after work in my home 🏠... Arigato Gozaimas 🙇🏻‍♂️

**Comment by Arclud** [comment]
@timbze I try run with android studio how administrator

`gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if the py launcher can be used to find Python
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:302:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:200:18)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:266:16)
gyp ERR! stack     at exithandler (node:child_process:340:5)
gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:352:5)
gyp ERR! stack     at ChildProcess.emit (node:events:379:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:283:12)
gyp ERR! stack     at onErrorNT (node:internal/child_process:477:16)
gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:81:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\ArHanGeL\mydevdir\and-bible\app\bibleview-js\node_modules\fibers
gyp ERR! node -v v15.6.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
node-gyp exited with code: 1


Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
"nodejs" ?? ????? ???????? ??? ?????
????????, ??????? ?????? ??? ?????? ????.


npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@4.0.3 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@4.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ArHanGeL\AppData\Local\npm-cache\_logs\2021-01-20T12_43_16_393Z-debug.log
npm ERR! code 1
npm ERR! path C:\Users\ArHanGeL\mydevdir\and-bible\app\bibleview-js
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm install --save-dev npm@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ArHanGeL\AppData\Local\npm-cache\_logs\2021-01-20T12_43_16_435Z-debug.log

> Task :app:npmUpgrade FAILED

Execution failed for task ':app:npmUpgrade'.
> Process 'command 'npx.cmd'' finished with non-zero exit value 1
`

**Comment by timbze** [comment]
@Arclud Ok it looks like running as admin solved your first issue. By the log you have here it looks like you need to install python yet on your computer.

Scroll down to windows installer file here: https://www.python.org/downloads/release/python-391/

**Comment by Arclud** [comment]
Thank you. Next error was imagine below

`gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2017 (15.9.28307.1342) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - missing any VC++ toolset
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:340:5)
gyp ERR! stack     at ChildProcess.emit (node:events:379:20)
gyp ERR! stack     at maybeClose (node:internal/child_process:1065:16)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\ArHanGeL\mydevdir\and-bible\app\bibleview-js\node_modules\fibers
gyp ERR! node -v v15.6.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
"nodejs" ?? ????? ???????? ??? ?????
????????, ??????? ?????? ??? ?????? ????.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@4.0.3 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@4.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ArHanGeL\AppData\Local\npm-cache\_logs\2021-01-23T18_01_20_827Z-debug.log
npm ERR! code 1
npm ERR! path C:\Users\ArHanGeL\mydevdir\and-bible\app\bibleview-js
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm install --save-dev npm@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ArHanGeL\AppData\Local\npm-cache\_logs\2021-01-23T18_01_20_892Z-debug.log

> Task :app:npmUpgrade FAILED
Execution failed for task ':app:npmUpgrade'.
> Process 'command 'npx.cmd'' finished with non-zero exit value 1`



**I used Android Studio for develop**

**Comment by timbze** [comment]
Looks like you may need to follow these instructions to get node-gyp properly installed
https://github.com/nodejs/node-gyp#on-windows

**Comment by Arclud** [comment]
@timbze Finally I installed , Thanks a lot , could I or you update documentation for buld project ?

**Comment by timbze** [comment]
> @timbze Finally I installed , Thanks a lot , could I or you update documentation for buld project ?

I think the wiki is editable. If you can do it that would be wonderful!

**Comment by Arclud** [comment]
@timbze 
I'll be happy , yes I do 

We can close this issue
