### ISSUE TITLE
Incorrect chapter translation

### ISSUE THREAD

**Issue by Arclud** [AndBible/and-bible#926]
## The problem

For example when I dowload bible in Kyrgyz language the chapters labels was incorrect, the chapter labels language was Russian

## Scenario

1. Open bible
2. Open tab for download modules
3. Write in search "Кыргызча" (use Russiam keyboard)
4. Then click just first item because we have double "Кыргызча" lines
5. Then open tab which can helped choose chapters(Ephesians and other)

If the chapters lanugage was in Russion it is incrorrect

Normally the language must will be like below(I found other bible and download our bible module)
![photo_2021-01-24_14-09-41](https://user-images.githubusercontent.com/46858397/105624694-f1f83380-5e4d-11eb-9d93-be696fbe5cbd.jpg)

## Could I Fix ?

Yeah , I build project success just yesterday and I do not know about this project and how is working 
I think in next week or after two weeks I can fix) it is enough time for learn ( of course I will learn this project after my job)

## Test

I install application with Android Studio and from Play Market the problem was

**Comment by timbze** [comment]
I think #404 also addresses this issue.

The way the app works now, the chapter labels in the Bible book chooser are always in the language that the application is set to, regardless of what translation of Bible you download.

I think there could be some kind of setting added to the Bible book chooser window to switch language to Bible language, but leave the default setting the way it is now.

**Comment by Arclud** [comment]
@timbze I think it is not good idea to use application language for example  I am Kyrgyz and my national language is Kyrgyz but so I wanna improve my English and I have to change my application language when I want to see correct language chapter

So it is just my idea and may be your position is better then My

**Comment by timbze** [comment]
I want to make sure I understand.
You have application language in English, Bible in Kyrgyz, but books show Russian names? Or is the Russian names when you have that as your application language?

**Comment by Arclud** [comment]
My application language is checked as default , my phone language is Russian , the Bible module whose was downloaded is Kyrgyz , the chapter language are Russian , I did not change and-bible language

**Comment by timbze** [comment]
Ok, got it. Then it is same issue as #404.

Instead of creating an option in Bible chooser screen, it sounds like for you it would be better if there was an option to always show Bible book labels in their own language. In that case it would probably be better to add an option in application preferences to enable that setting. The setting would say something like "Show Bible book labels in own language".

I still don't think it should be enabled by default. I would want the application language in my own language (including book labels), even though I would use other Bible languages as well. I am thinking this would be the most user friendly option, but maybe @tuomas2 can weigh in yet and say what he thinks

**Comment by Arclud** [comment]
In your case for example if I read some books and her language is English but the contest is Russian in my opinion it is incorrect... So What I want say : If books is English the chapter must be English so why ? Because If I read Bible in English and the chapters was Russian and in some day's i wanna talk about Bible with my friend but I don't know chapters name in English because I read chapters name in Russian

**Comment by tuomas2** [comment]
@timbze I agree, in general I think it's consistent to show bible books in the language of application language, but I see the point of creating application preference for this. 

What app was the screenshot taken with?

**Comment by Arclud** [comment]
> @timbze I agree, in general I think it's consistent to show bible books in the language of application language, but I see the point of creating application preference for this.
> 
> What app was the screenshot taken with?

Of course just [click](https://play.google.com/store/apps/details?id=ua.mybible&hl=ru&gl=US) , but the application is not open source , above application is most popular in Russian , Kazahstan , Kyrgyzstan , Uzbekistan and may be we can take her some featues

**Comment by timbze** [comment]
Hi @Arclud just to confirm that you understand my thoughts on this thread.

You are very welcome to implement the feature you are requesting here, and link it to a new application preference.

If you are not sure how you would link it to an application preference I can help with that if you implement the feature itself.
