### ISSUE TITLE
Allow custom reading plan

### ISSUE THREAD

**Issue by pinstall** [AndBible/and-bible#933]
Please let me create and edit my own reading plan. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by timbze** [comment]
Hi @pinstall, you can create your own reading plan. Please see the help information about it [here](https://github.com/AndBible/and-bible/wiki/Reading-Plans#custom-reading-plans)
