### ISSUE TITLE
Discipleship Journal Bible Reading Plan © Navigators for AndBible

### ISSUE THREAD

**Issue by mavink** [AndBible/and-bible#935]
Please find attached the Discipleship Journal Bible Reading Plan for AndBible. Available from the Navigators - https://www.navigators.org/wp-content/uploads/2017/04/Discipleship-Journal-Bible-Reading-Plan-9781617479083.pdf

Create a folder called **jsword** in your internal storage. Create a folder inside this called **readingplan**

Paste the attached file with the exact filename **DiscipleshipJournalBibleReadingPlan©Navigators.properties** in the **readingplan** folder.

In AndBible click on **Men**u on the top left, click on **Application preferences**. Scroll to the bottom. In the **Advanced setting**s section toggle the **Manually installed documents ex..** to **ON**.

Close and open AndBible and you should see the plan in your Menu->Readingplans

[DiscipleshipJournalBibleReadingPlan©Navigators.zip](https://github.com/AndBible/and-bible/files/6021836/DiscipleshipJournalBibleReadingPlan.Navigators.zip)

**Comment by timbze** [comment]
This reading plan is copyright. We can only consider distributing a reading plan in And Bible if permission is granted by the copyright holder.
