### ISSUE TITLE
Links window improvements / per-window links windows

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#942]
## New "special links window" logic

When clicking links in a window, a special "links" window is created that is linked to this particular linking window. 

Then again, clicking links from this "links" window will create another "links window" to that window, in a similar manner. 

Links window icon is drawn next to it's "parent" window, and linking is marked with some icon/symbol there (perhaps arrow from one to another). 

Links window can be changed to normal window. Actually, it might be possible to have it as "normal" (unsynced) window, as long as linking is marked in a clear way. 

## Set target window for clicked links

Links window target could be changed from window options menu.

## Video explanation 

https://www.youtube.com/watch?v=S54jbmMTkR0

**Comment by tuomas2** [comment]
Related: #648

**Comment by agrogers** [comment]
Related: #2447

**Comment by tuomas2** [comment]
Not that this is ready / complete, but I now implemented basic functionality allowing multiple (chained) links windows.

UI needs still thinking.  I'd like to open this for feedback which can as comments to this ticket. Feature is included in alpha-674.

**Comment by agrogers** [comment]
Sounds interesting. I will check it
