### ISSUE TITLE
Strongs dictionary to be user-selectable

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#946]
If many dictionaries are installed, user should be able to choose which he is using in Application Preferences.

**Comment by LAfricain** [comment]
This is exactly what I need. For now we have 4 strongs languages but only english is displayed when we click on a strong number. It would be interesting to have this option which gives us the opportunity to choose the dictionary.

**Comment by tuomas2** [comment]
developer: could be implemented as per workspace / per window text display settings or just application preference.

**Comment by timbze** [comment]
> developer: could be implemented as per workspace / per window text display settings or just application preference.

Also, perhaps a long-press on the strongs link could give options for which dictionary to use

**Comment by timbze** [comment]
Based on #897, the first step would be to simply remember the last dictionary the user has used, and use that again on next link press.

**Comment by tuomas2** [comment]
> Also, perhaps a long-press on the strongs link could give options for which dictionary to use

Long-pressing dot-underlined words does not open context menu but allows selection (for bookmarking etc). Long-pressing popup menu would be available only when using links mode for strongs.

**Comment by tuomas2** [comment]
I implemented now simple selection in app preferences. Further improvements welcome later on... (@timbze you can create issue if you like :-) )
