### ISSUE TITLE
Strong's root word ref. Are not showing as links. 

### ISSUE THREAD

**Issue by bvahedy** [AndBible/and-bible#957]
Using the latest alpha build 3.3.509:

When displaying a Strong's no. In the dictionary the root references are not showing up as links. 

e.g.   bring up the Strong's definition for 06966 which is the Hebrew H6966.
Within the definition is a root reference to H6965. This no. should be a link and should be clickable.

**Comment by tuomas2** [comment]
same as this? https://support.andbible.org/scp/tickets.php?id=422

**Comment by bvahedy** [comment]
Yes, after verifying that in the previous versions those showed as links I
created #957. Should I not have created that ticket?

**Comment by tuomas2** [comment]
creating ticket was right thing, just wanted to confirm and cross link as there is screenshot too.

**Comment by bvahedy** [comment]
![Screenshot_20210329-175343_Bible Study](https://user-images.githubusercontent.com/46405809/113057617-1e883e80-9162-11eb-97d9-6997f383f98e.jpg)

**Comment by agrogers** [comment]
I suggest we delay this one to after v3.4 release

**Comment by bvahedy** [comment]
This functionality worked correctly on 3.3. depending on how many people
use this feature, it could cause a lot of users to complain.

**Comment by tuomas2** [comment]
Works perfectly for me. I guess we have different version of RealGreekStrongs. My module says 1.5-150704 (2015-07-04), what does yours? And I think this is the one version that is available via downloads.

**Comment by tuomas2** [comment]
![image](https://user-images.githubusercontent.com/5811789/123386452-5e16c900-d59f-11eb-86d9-e5b319e22be0.png)

**Comment by bvahedy** [comment]
Ok, I see. I had created a combine Mickelson with kjv strong's dictionary which gives you a better comparisons of each words from both dictionaries in one place. However I don't know why the links are not working now in 3.4, is there any way you can tell me what AB is now looking for to display the links. I have not changed anything in this dictionary module and it does work in 3.3 version. If it's not too much trouble to point out I can modify my dictionary and implement it again. I'll send you my dictionary on Teams and you can install it over to your current dictionaries and test it out.

**Comment by tuomas2** [comment]
Possibly related https://tracker.crosswire.org/browse/MOD-417

**Comment by bvahedy** [comment]
It seems the parser is not looking at any other dictionaries, I am ref Mickelson and it's not looking for it for some reason. Hope this helps you in fixing this.
I looked at the xml code and it looks like this:

</entryFree><entryFree n="H5058"><title>H5058</title><orth> נְגִינָה נְגִינַת ngiynah (neg-ee-naw') (or ngiynath (Psa. 61) </orth> occurs: 14<def><lb/> 

1. (properly) instrumental music

<lb/>2. (by implication) a stringed instrument

<lb/>3. (by extension) a poem set to music

<lb/>4. (specifically) an epigram

[from <ref target="Mickelson:H5059">H5059</ref>]

<lb/>KJV: stringed instrument, musick, Neginoth (plural), song. 

Root(s): <ref target="Mickelson:H5059">H5059</ref> 

</def></entryFree>

**Comment by bvahedy** [comment]
I don't know what code was changed but the Strong's numbers now show as links in the dictionary but tapping on them does nothing. I guess we are getting closer. 
![Screenshot_20210717-160156_Bible Study](https://user-images.githubusercontent.com/46405809/126051188-d8336096-c48d-469c-9ce1-84dfe848fd79.jpg)

**Comment by agrogers** [comment]
The links all work for me. 

Although when I search for a dictionary word it shows twice in the window. 

![IMG_20210718_091942.jpg](https://user-images.githubusercontent.com/13920678/126051360-1fe726ec-54cf-45c2-afc9-0e7140f56610.jpg)

**Comment by bvahedy** [comment]
That's because you are using Strong's real Greek and teal Hebrew and not
the Mickelson dictionary.
I attached a copy of the Mickelson zip file on the Teams area. Install that
and see if the links click.
It seems AB doesn't look at any other dictionaries except Strong's real
Hebrew& Greek.
The Mickelson will give you both dictionary ref in one place.
Anyways, Toumas said he will look at this when he has time.

**Comment by tuomas2** [comment]
Can you try this again with build 604? It should be fixed now by #1672

**Comment by bvahedy** [comment]
Yes, this works now. The root links within the dictionary definitions are
linkable.

Thanks for this fix, I was starting to lose sleep over this issue.
