### ISSUE TITLE
Window separator line issue

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#958]
https://support.andbible.org/scp/tickets.php?id=395

I was trying to resize this window I made from clicking on a Strong's number. It works smoothly until I go fullscreen; then the separator barely moves when I try it in this state.

1. Open a Strong's number, which should open a new window
2. Double-tap to fullscreen the app (or scroll for my case)
3. Try to drag the separator so that the new window is 25% of the screen, instead of 50%.
  - When in fullscreen, the separator should stop following your finger after moving a little bit, and does not reach to the 25% mark right away.
  - When not in fullscreen, the separator should keep following your finger until you let go at the 25% mark.

**Comment by bvahedy** [comment]
I could not duplicate this in 509 alpha build.

**Comment by bvahedy** [comment]
Still could not duplicate in 512.1 build.

**Comment by tuomas2** [comment]
Could be fixed in 3.4 then. Leaving open still, as it's 3.3 bug (until 3.4 or 3.3 bugfix is released).

**Comment by tuomas2** [comment]
Let's ask the user after 4.0 is released
