### ISSUE TITLE
Clicking app preference "Strongs Hebrew dictionary" or "Robinson Greek morphology" causes crash

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#963]
Clicking app preference "Strongs Hebrew dictionary" or "Robinson Greek morphology" causes crash
Log is here: https://support.andbible.org/scp/tickets.php?id=439

**Bug was found on And Bible version**
Build 512-alpha c5bd0f7f

**Comment by bvahedy** [comment]
This was working in last 511 build.
