### ISSUE TITLE
Pressing back from "Download documents" while installing/updating modules causes crash

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#964]
**Describe the bug**
Pressing back from "Download documents" while updating modules causes crash

https://support.andbible.org/scp/tickets.php?id=426

**To Reproduce**
1. Open app
2. Open download documents. 
3. Select several documents to download which are updates. 
4. Click the back button on the Android system bar to return to the Bible screen. 
5. And Bible crashes. 

**Device info:**
And Bible version: 3.3.399#24411f9 (built 05/11/20 10:40:43)
Android version: 11
Android SDK version: 30
Manufacturer: Google
Model: Pixel 3 XL

**Comment by timbze** [comment]
Similar to #1372, might be fixed in 4.0

**Comment by tuomas2** [comment]
Does not crash any more

**Comment by timbze** [comment]
Happened again in 630

https://support.andbible.org/scp/tickets.php?id=1235

1. I downloaded new documents (English Bible commentaries)
- ![Screenshot from 2022-01-26 06-50-24](https://user-images.githubusercontent.com/35117769/151165951-a8116d8b-5c0a-47dd-a0dc-7b898ce88648.png)
2. For each document, a green check mark appeared to be successfully downloaded, but at the same time a "error occurred while downloading" window always popped up
3. Pressed back button in the upper left corner
4. Application crashed

**Comment by tuomas2** [comment]
reproducible?

**Comment by timbze** [comment]
> reproducible?

I have not been able to reproduce it, the message is from the user bug report

**Comment by timbze** [comment]
Haven't seen this issue in a long time
