### ISSUE TITLE
Reference title freezes after switching between workspaces quickly

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#965]
* Don't know exactly how to reproduce, but I was switching between 2 workspaces a few times and then the verse in title froze. 
* It shows Romans 9:1, I scroll down but title verse does not change. 
* I swipe to go to next chapter then it shows Romans 10:1 but scrolling down still keeps verse in title frozen. 

Keeping as low priority because not easily reproducible and probably not happening very easily.

https://support.andbible.org/scp/tickets.php?id=349

**Device info:**
And Bible version: 3.3.503#57ee8552 (built 15/02/21 16:33:12)
Android version: 11
Android SDK version: 30
Manufacturer: Google
Model: Pixel 3

**Comment by agrogers** [comment]
I suggest we delay this one to after v3.4 release

**Comment by tuomas2** [comment]
This is a bug so I will look at it before release with low prio. All bugs should be fixed, but we don't need to postpone releasing because of low prio bugs.

**Comment by timbze** [comment]
Have not seen this issue in a very long time
