### ISSUE TITLE
High contrast indicator for currently selected book in book chooser menu

### ISSUE THREAD

**Issue by ghost** [AndBible/and-bible#97]
When a passage is already open and you tap to jump to another book/Ch./verse, the currently selected book / verse is shown in bold. 1 bold, 3 character symbol out of 66 is difficult to find and serves little purpose. I would like to see a more obvious / high contrast button instead. Such as larger text, a differently coloured background button, an underline, or a white border on the edges of the button.  

_Sent from my Motorola XT1039 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by timbze** [comment]
Was fixed by #988
