### ISSUE TITLE
RTL UI

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#970]
Can use appSettings.rightToLeft variable to detect.
Easier to implement when we have some rtl language translated.

https://material.io/design/usability/bidirectionality.html#mirroring-layout

**Comment by agrogers** [comment]
I suggest we delay this one to after v3.4 release

**Comment by tuomas2** [comment]
This absolutely needs to be done before release, otherwise arabic & chinese have broken UI.

**Comment by tuomas2** [comment]
I'm not quite sure what elements we should mirror and what not. Because I just noticed that we are not quite following RTL guidelines in Android side either.

see for example https://medium.com/@giladalmosnino/ux-best-practices-for-bi-directional-languages-9bd7b96dc8c2

Perhaps good starting point is to ensure that all text elements are aligned to right correctly.

**Comment by tuomas2** [comment]
Hmm JS side seems to flip quite completely and quite automatically. Just one dir=ltr and bookmarks modal looks like this:

![image](https://user-images.githubusercontent.com/5811789/124638475-abdedb80-de93-11eb-9204-ada113706e10.png)

**Comment by tuomas2** [comment]
And a little more tweaking and it looks like this:

![image](https://user-images.githubusercontent.com/5811789/124639249-9e762100-de94-11eb-94f5-2c4a363098fc.png)

**Comment by tuomas2** [comment]
Android also flipped nicely. Though there could be some bugs lying around in RTL world.

**Comment by tuomas2** [comment]
8b68a776b1d4db81b6bad23b008f9d6b07e659a3

**Comment by tuomas2** [comment]
Still TODO
- [x] window button location
- [x] window button bar behavior
- [x] scrollX in isPageNExtOkay / ...
- [x] study pads
- [x] text editor close button in bookmark modal

**Comment by tuomas2** [comment]
BTW, this can be tested by changing "Force RTL layout direction" to true from "Developer options"

![image](https://user-images.githubusercontent.com/5811789/124704750-3c9dd180-defd-11eb-8ee4-32e4b45117eb.png)

**Comment by tuomas2** [comment]
I believe this is more or less fixed now. It would be nice if someone tests a little RTL too...

**Comment by tuomas2** [comment]
Hmm, crap, I just realized that we don't support any RTL language (via translations). I thought chinese is RTL but apparently it is not (in these modern times at least).

But anyway, at least we have now RTL support if we get arabic, hebrew or other interesting translations for the UI. 

(just noticed that at least hebrew support seems to be getting better, though not yet complete)

**Comment by agrogers** [comment]
lol

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)
