### ISSUE TITLE
Share / copy verse(s) / selection  

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#971]
As of new bibleview-js, old share function was gone. Need to implement something...

**Comment by tuomas2** [comment]
Although I'm not sure if it's necessary, as user can use default share / copy functions now. What do you think?

**Comment by timbze** [comment]
I think it is necessary so that Bible reference gets copied together with the text.

Also, now footnote letters are being copied which isn't ideal. And there is no space between verse number and following character.
