### ISSUE TITLE
Share/Copy issues

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#975]
- [x] Extra double-quote

With new share/copy feature, select a word from middle of verse up to middle of next verse, and then an extra double-quote is added from where selection starts.

Example, copy Acts 1:1-2. Select the word "treatise", and then up to somewhere in verse 2. See the extra double-quote before the word "treatise".

> “The former “treatise have I made, O Theophilus, of all that Jesus began both to do and teach, Until the day in which he was taken up, after that he through the Holy Ghost had given commandments unto the apostles whom he had chosen: ” (Acts 1:1-2, KJV)

- [x] Space before last (closing) double-quote

Also, it seems there's always a space before the last (closing) double-quote. I think it would usually be nicer to trim the space.

AB Version 513-alpha

**Comment by tuomas2** [comment]
Should make make unit tests for this (SwordContentFacade:getSelectionText).

**Comment by timbze** [comment]
- [x] Also, when copying with verse numbers, the last verse number is not included. Copying v1-3, it will only show the numbers 1 and 2 in the text, the number 3 is omitted even though the verse is copied. When it's 2 verses then the number 2 is omitted

**Comment by tuomas2** [comment]
- [x] maybe also better to use abbreviated version for the reference

**Comment by tuomas2** [comment]
- [x] "Show reference" is maybe not needed/useful option? User wants always reference?

**Comment by tuomas2** [comment]
Fixed
