### ISSUE TITLE
End of chapter footer/verse number issue

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#979]
- [ ] Hebrews 13:25 footer issue. The number 25 should be at the line above it.

![image](https://user-images.githubusercontent.com/35117769/106155452-506f2b80-6146-11eb-88f9-156ff3780dab.png)

_Originally posted by @timbze in https://github.com/AndBible/and-bible/issues/922#issuecomment-769141106_

**Comment by timbze** [comment]
Also happens at the end of more books, e.g.:
Romans
1Cor
2Cor
Galatians
Ephesians
Philippians
Colossians

**Comment by bvahedy** [comment]
Timmy, I believe this is an issue with the KJV module.
it doesn't happen with any other modules.

**Comment by timbze** [comment]
> Timmy, I believe this is an issue with the KJV module.
> it doesn't happen with any other modules. 

Though there is something odd with the module, AB 3.3 shows it correct, as does Xiphos.

**Comment by tuomas2** [comment]
We can investigate that but I don't think it's good idea to try to workaround module oddnessess unless they are something super significant (and module itself can't be fixed). KJV module could be revised if we can indicate what's wrong with it.

**Comment by timbze** [comment]
The odd part is with the eBible module. AB only shows eBible module for KJV, and I'm guessing it is because of a higher version number.

I imported the KJV zip from Crosswire, and the verse number is correct on that one, but the "Written from..." text at the end looks like it is part of the last verse. But that's a separate issue that could/should be fixed with how AB renders it.

So I think we need a way to make it possible to install Crosswire's KJV module, and make that the preferred (recommended) module instead of eBible.

This is the diatheke output for Col 4:18 for Crosswire's module (so it should definitely be possible to separate the ending text at least how it looks to me).

```
Colossians 4:18: <w lemma="strong:G3588 strong:G783" morph="robinson:T-NSM robinson:N-NSM" savlm="strong:G3588 strong:G783 lemma.TR:ο lemma.TR:ασπασμος" src="1 2">The salutation</w> <w lemma="strong:G5495" morph="robinson:N-DSF" savlm="strong:G5495 lemma.TR:χειρι" src="5">by the hand</w> <w lemma="strong:G3588 strong:G1699" morph="robinson:T-DSF robinson:S-1DSF" savlm="strong:G3588 strong:G1699 lemma.TR:τη lemma.TR:εμη" src="3 4">of me</w> <w lemma="strong:G3972" morph="robinson:N-GSM" savlm="strong:G3972 lemma.TR:παυλου" src="6">Paul</w>. <w lemma="strong:G3421" morph="robinson:V-PAM-2P" savlm="strong:G3421 lemma.TR:μνημονευετε" src="7">Remember</w> <w lemma="strong:G3450" morph="robinson:P-1GS" savlm="strong:G3450 lemma.TR:μου" src="8">my</w> <w lemma="strong:G3588 strong:G1199" morph="robinson:T-GPM robinson:N-GPM" savlm="strong:G3588 strong:G1199 lemma.TR:των lemma.TR:δεσμων" src="9 10">bonds</w>. <w lemma="strong:G3588 strong:G5485" morph="robinson:T-NSF robinson:N-NSF" savlm="strong:G3588 strong:G5485 lemma.TR:η lemma.TR:χαρις" src="11 12">Grace</w> <transChange type="added">be</transChange> <w lemma="strong:G3326" morph="robinson:PREP" savlm="strong:G3326 lemma.TR:μεθ" src="13">with</w> <w lemma="strong:G5216" morph="robinson:P-2GP" savlm="strong:G5216 lemma.TR:υμων" src="14">you</w>. <w lemma="strong:G281" morph="robinson:HEB" savlm="strong:G281 lemma.TR:αμην" src="15">Amen</w>. <chapter chapterTitle="CHAPTER 4." eID="gen1809" osisID="Col.4"/> <div osisID="Col.c" sID="gen1810" type="colophon"/><w lemma="strong:G1125" morph="robinson:V-2API-3S" savlm="strong:G1125 lemma.TR:εγραφη" src="18">Written</w> <w lemma="strong:G575" morph="robinson:PREP" savlm="strong:G575 lemma.TR:απο" src="19">from</w> <w lemma="strong:G4516" morph="robinson:N-GSF" savlm="strong:G4516 lemma.TR:ρωμης" src="20">Rome</w> <w lemma="strong:G4314" morph="robinson:PREP" savlm="strong:G4314 lemma.TR:προς" src="16">to</w> <w lemma="strong:G2858" morph="robinson:N-APM" savlm="strong:G2858 lemma.TR:κολασσαεις" src="17">the Colossians</w> <w lemma="strong:G1223" morph="robinson:PREP" savlm="strong:G1223 lemma.TR:δια" src="21">by</w> <w lemma="strong:G5190" morph="robinson:N-GSM" savlm="strong:G5190 lemma.TR:τυχικου" src="22">Tychicus</w> <w lemma="strong:G2532" morph="robinson:CONJ" savlm="strong:G2532 lemma.TR:και" src="23">and</w> <w lemma="strong:G3682" morph="robinson:N-GSM" savlm="strong:G3682 lemma.TR:ονησιμου" src="24">Onesimus</w>.<div eID="gen1810" osisID="Col.c" type="colophon"/> <div canonical="true" eID="gen1805" osisID="Col" type="book"/>
```

Interestingly, I find that Github renders the xml too, like this:
> Colossians 4:18: <w lemma="strong:G3588 strong:G783" morph="robinson:T-NSM robinson:N-NSM" savlm="strong:G3588 strong:G783 lemma.TR:ο lemma.TR:ασπασμος" src="1 2">The salutation</w> <w lemma="strong:G5495" morph="robinson:N-DSF" savlm="strong:G5495 lemma.TR:χειρι" src="5">by the hand</w> <w lemma="strong:G3588 strong:G1699" morph="robinson:T-DSF robinson:S-1DSF" savlm="strong:G3588 strong:G1699 lemma.TR:τη lemma.TR:εμη" src="3 4">of me</w> <w lemma="strong:G3972" morph="robinson:N-GSM" savlm="strong:G3972 lemma.TR:παυλου" src="6">Paul</w>. <w lemma="strong:G3421" morph="robinson:V-PAM-2P" savlm="strong:G3421 lemma.TR:μνημονευετε" src="7">Remember</w> <w lemma="strong:G3450" morph="robinson:P-1GS" savlm="strong:G3450 lemma.TR:μου" src="8">my</w> <w lemma="strong:G3588 strong:G1199" morph="robinson:T-GPM robinson:N-GPM" savlm="strong:G3588 strong:G1199 lemma.TR:των lemma.TR:δεσμων" src="9 10">bonds</w>. <w lemma="strong:G3588 strong:G5485" morph="robinson:T-NSF robinson:N-NSF" savlm="strong:G3588 strong:G5485 lemma.TR:η lemma.TR:χαρις" src="11 12">Grace</w> <transChange type="added">be</transChange> <w lemma="strong:G3326" morph="robinson:PREP" savlm="strong:G3326 lemma.TR:μεθ" src="13">with</w> <w lemma="strong:G5216" morph="robinson:P-2GP" savlm="strong:G5216 lemma.TR:υμων" src="14">you</w>. <w lemma="strong:G281" morph="robinson:HEB" savlm="strong:G281 lemma.TR:αμην" src="15">Amen</w>. <chapter chapterTitle="CHAPTER 4." eID="gen1809" osisID="Col.4"/> <div osisID="Col.c" sID="gen1810" type="colophon"/><w lemma="strong:G1125" morph="robinson:V-2API-3S" savlm="strong:G1125 lemma.TR:εγραφη" src="18">Written</w> <w lemma="strong:G575" morph="robinson:PREP" savlm="strong:G575 lemma.TR:απο" src="19">from</w> <w lemma="strong:G4516" morph="robinson:N-GSF" savlm="strong:G4516 lemma.TR:ρωμης" src="20">Rome</w> <w lemma="strong:G4314" morph="robinson:PREP" savlm="strong:G4314 lemma.TR:προς" src="16">to</w> <w lemma="strong:G2858" morph="robinson:N-APM" savlm="strong:G2858 lemma.TR:κολασσαεις" src="17">the Colossians</w> <w lemma="strong:G1223" morph="robinson:PREP" savlm="strong:G1223 lemma.TR:δια" src="21">by</w> <w lemma="strong:G5190" morph="robinson:N-GSM" savlm="strong:G5190 lemma.TR:τυχικου" src="22">Tychicus</w> <w lemma="strong:G2532" morph="robinson:CONJ" savlm="strong:G2532 lemma.TR:και" src="23">and</w> <w lemma="strong:G3682" morph="robinson:N-GSM" savlm="strong:G3682 lemma.TR:ονησιμου" src="24">Onesimus</w>.<div eID="gen1810" osisID="Col.c" type="colophon"/> <div canonical="true" eID="gen1805" osisID="Col" type="book"/>
>

**Comment by tuomas2** [comment]
> The odd part is with the eBible module. AB only shows eBible module for KJV, and I'm guessing it is because of a higher version number.

I wonder if the module with same id exists in multiple repositories, should we show them all to users or somehow allow them to choose from where to download? Bit confusing...

**Comment by timbze** [comment]
> I wonder if the module with same id exists in multiple repositories, should we show them all to users or somehow allow them to choose from where to download? Bit confusing...

The "id" is different, but short name KJV is the same

**Comment by tuomas2** [comment]
if id is different but only abbreviation is same I guess we could have them both shown in download screen

**Comment by timbze** [comment]
Closing this in favor of the 2 replacement issues that came out of this
