### ISSUE TITLE
Font size change when multiple windows

### ISSUE THREAD

**Issue by mjdenham** [AndBible/and-bible#98]
I'm a user of your great bible app from Germany. I use the split window function and would like to be able to use different font sizes for each window. I noticed when I changed the size, only one window was updated, the other one stayed the same. After closing the app and opening it again, both windows had the same font size.

**Comment by tuomas2** [comment]
Implemented in next beta > 340

**Comment by bvahedy** [comment]
Verified working in build 341 beta.
