### ISSUE TITLE
Backup / share APK with a friend

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#980]
Idea is that together with "backup modules" feature, user could share apk to a friend without need for him/her to obtain apk first to be able to read bible.

Some in-app guidance to be able to "clone" installation completely to another device should probably be provided too.

**Comment by LAfricain** [comment]
The first question is How to make the app available in a store in an official way?

**Comment by tuomas2** [comment]
> The first question is How to make the app available in a store in an official way?

What do you mean exactly? You don't find And Bible in Play Store?

**Comment by LAfricain** [comment]
I do, but the Play store doesn't exist in some country (discussed yesterday). We have to find a way to propose the app in their own store.

**Comment by tuomas2** [comment]
Chinese stores require that someone from china uploads app, if I have udnerstood correctly. 
I am in the progress to upload to samsung and huawei stores, but they also don't allow me to publish in china.

**Comment by timbze** [comment]
How to share apk file:
https://stackoverflow.com/questions/39485995/how-can-i-share-apk-file-in-my-app-send-app-itself
https://stackoverflow.com/questions/40941709/how-to-share-current-apps-apk-or-of-other-installed-apps-using-the-new-filepr

Another note, Google is phasing out being able to use .apk files, though they don't have a deadline for current apps yet. New apps [will no longer be able to upload apk](https://developer.android.com/guide/app-bundle) to Play Store from Aug 2021.
Generating apk from aab [uses a tool (`bundletool`)](https://stackoverflow.com/questions/53040047/generate-apk-file-from-aab-file-android-app-bundle)

**Comment by tuomas2** [comment]
but store generated apk is found on device still after install if aab is used or what?

**Comment by timbze** [comment]
> but store generated apk is found on device still after install if aab is used or what?

I'm not sure, I think I've seen a bunch of smaller apks generated from the aab but don't know exactly how it works.

**Comment by tuomas2** [comment]
We will see how apk backup works for aab's after we release first beta (using aab)

**Comment by tuomas2** [comment]
Seem to work well with aab too, after disabling splits. db9a099e97eed2f0ae565bf8de91e4acef3801b8

https://developer.android.com/guide/app-bundle/configure-base
