### ISSUE TITLE
Night mode upgrade 3.3 to 3.4-beta causes text to not show

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#989]
https://support.andbible.org/scp/tickets.php?id=459

**Describe the bug**
Upgrade 3.3 stable when it's on night mode, to 3.4-beta and the Bible text does not display.

**Bug was found on And Bible version**
Build 3.4.515-beta

**To Reproduce**
1. App is on 3.3.399 and has night-mode enabled
2. Upgrade app to beta (3.4.515-beta) from Play Store
3. Regular text is not being displayed, though red letter is showing

**Workaround:**
Go to text color settings and click "Reset". Now text shows up.

**Comment by tuomas2** [comment]
https://support.andbible.org/scp/tickets.php?id=465

**Comment by tuomas2** [comment]
Fix: 83aa736a13b235adf08e003cf471c976a19d0c39

**Comment by tuomas2** [comment]
Fixed in build 516
