### ISSUE TITLE
org.crosswire.jsword.passage.NoSuchVerseException

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#990]
org.crosswire.jsword.passage.NoSuchVerseException

https://play.google.com/console/u/0/developers/6727655833913220393/app/4974350217168681006/vitals/crashes/d301a5c8/details?installedFrom=PLAY_STORE&days=30

I think same as this:
https://support.andbible.org/scp/tickets.php?id=460
> The app keeps crashing since the last update today, when I put the lexicon on it will crash.

**Bug was found on And Bible version**
Build 514-beta

**Comment by tuomas2** [comment]
Should be fixed now (35e6e88a63fb4ca64afd9ea0a4c5cce763214b1d)
