### ISSUE TITLE
Problem with Scripture link in bookmark notes section

### ISSUE THREAD

**Issue by Dleemuse** [AndBible/and-bible#995]
I am using the very latest beta version on my Samsung galaxy note 10.

When bookmarking a scripture passage then making a note and then attaching a Bible reference link, the link will not open. A window pops open that says... Please download "1 Cor. 9' for exame when the scripture reference I input is 1 Cor. 9:13-14. Or when I have used the little Bible icon in the notes section to add the reference 1 Tim. 5:17-18, when clicking on this reference link a window pops open & says... Please download '1 Tim. 5'

I love that we can bookmark sections, words, or phrases of verses now instead of just the whole verse now. I was just trying to select a chapter & a half which was quite long on my phone, & for some reason it had difficulty selecting the longer passage. It would stop part way down & the actual colored selection part would jump back up to an earlier spot in the selection process & I would have to scroll back up & start over again. This continued to happen for about 5-7 minutes. 

Thank you, 

Debra

**Comment by Dleemuse** [comment]
![Screenshot_20210425-204102_Bible Study](https://user-images.githubusercontent.com/83124765/116018015-b44ea680-a606-11eb-99ef-7f8b8d183c4d.jpg)
![Screenshot_20210425-204111_Bible Study](https://user-images.githubusercontent.com/83124765/116018019-b4e73d00-a606-11eb-885e-bbbe2fab9e53.jpg)

**Comment by bvahedy** [comment]
Try putting "1cor2 9" without the quotes as the link ref.

**Comment by bvahedy** [comment]
Use  1cor2 9-11   for multiple verses.

![Screenshot_20210425-205710_Bible Study](https://user-images.githubusercontent.com/46405809/116027225-23c59580-a609-11eb-9c42-d9b17a9072f8.jpg)

**Comment by Dleemuse** [comment]
Hello guys,
I figured out this morning that you cannot open the scripture reference link in the edit notes section, you have to jump to study pad to open the scripture link. As I have said several times before when posting to AndBible forums I am tech challenged.
Thanks, 
Debra

**Comment by Dleemuse** [comment]
![Screenshot_20210426-064949_Bible Study](https://user-images.githubusercontent.com/83124765/116078010-bbec6a80-a65b-11eb-8d06-ca83ca0ad183.jpg)

**Comment by Dleemuse** [comment]
1. Above screen shot is a Pic of the study pad. It shows each of the scripture references that I linked with the Bible icon in the notes section with the first several words of that Bible verse, I can open this verse(s). It also has my note with my scripture references which I cannot open. 

2. When tapping on a bookmark & then edit, the links I input will not open. I still get the window that says please download chapter like the pics I sent earlier.

Is this how it is supposed to work? Are none of the actual links I input in the notes section actually supposed to open & it is only the ones that are generated by the program in the Study Pad that have the partial verse that are the ones that actually open.
Thanks,
Debra

**Comment by bvahedy** [comment]
The bible can have links in it but they must be incorporated by the translator within the passage. The study note links allow the reader to create their own links for the purpose of their own study. In order to jump to a link within the bookmark you tap on the bookmark to open the study note then all you have to do is to tap on the link within the study note.

**Comment by bvahedy** [comment]
This type of link is embedded in the bible module and the user can not create it by Andbible:
![Screenshot_20210426-075726_AndBible](https://user-images.githubusercontent.com/46405809/116104741-89e00600-a665-11eb-8eb1-70c8f871e350.jpg)

**Comment by tuomas2** [comment]
You can open links also from bookmark modal window. 

![Screenshot_20210426-182128](https://user-images.githubusercontent.com/5811789/116108106-4795e380-a6bc-11eb-9844-bf0dae220603.png)

**Comment by tuomas2** [comment]
Reference handling is still about to be changed in #981, so after that also references such as "1 Cor 1:3" should work.

**Comment by Dleemuse** [comment]
OK, that is my problem then. After I have made a bookmark, I tap to make a note, then I tap the little Bible icon to add a linked scripture reference, it is blue text, so shows as a link, but when I tap on it in the notes it will not open the verse.

**Comment by bvahedy** [comment]
That is because you need to give it a valid link.
Tap the word to select it in the bookmark window then tap on the icon with the cross. Now type joh2 as test link see if that works. 
![Screenshot_20210427-081246_AndBible](https://user-images.githubusercontent.com/46405809/116267189-0a1f6d80-a731-11eb-936a-2b21ce104f66.jpg)
![Screenshot_20210427-081424_AndBible](https://user-images.githubusercontent.com/46405809/116267200-0b509a80-a731-11eb-86db-aa55e6c01638.jpg)

**Comment by timbze** [comment]
Hello @Dleemuse and @bvahedy,

I think the root issue has not been described. Currently the only references that are understood are such as what is called OSIS format. That is, the references have to be very specific (e.g. these should work John1.1 Rev2.1 -- colon between chapter and verse will not currently work).

Later in beta when further improvements are done, then any normal references should work.

**Comment by bvahedy** [comment]
Yes, that is true, thank you Timmy for the clarification.

**Comment by timbze** [comment]
This should be resolved after merging #981. Closing.
