### ISSUE TITLE
rendering issue

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#996]
> I have kept a past version of the ESV Bible which I keep moving across to my new phones. Is that legal? 
> 
> I have just noticed with the latest beta version that spacing between words and punctuation has got messed up. It now joins random words and spacing after commas and fullstops is missing. See attached. 
> 
> Is this an issue that you want to address? If it is I should open a different issue for it. 
> ![IMG_20210426_101516](https://user-images.githubusercontent.com/13920678/116015079-6b850500-a67b-11eb-86c7-b751af3003bd.jpg)

(https://user-images.githubusercontent.com/13920678/116015057-590acb80-a67b-11eb-9d61-4296c5bed275.jpg)

_Originally posted by @agrogers in https://github.com/AndBible/and-bible/issues/390#issuecomment-826421795_

**Comment by tuomas2** [comment]
@agrogers it is only illegal to distribute that module as we do not have permission for it. To keep and use once legally distributed module is legal.

What we see in screenshot looks like a bug, will need to check it.

**Comment by tuomas2** [comment]
Could it be module issue with older version of module? My ESVS module renders correctly.
Did older version of And Bible render it correctly?

Here's how I see it:

![image](https://user-images.githubusercontent.com/5811789/116569703-507ff280-a912-11eb-9352-3ea487acfdf0.png)

**Comment by agrogers** [comment]
It is quite old. So you might be right. Is it possible to find that version
that you have anywhere? Or is it now legally unavailable?

Thanks for the other work you have done on the latest version of AndBible.
I have been using the new features and like them a lot. Well done.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by microbearsmb** [comment]
Is it legal to use the Wayback Machine link in the previous issue thread? As I understand it, it is an old mirror of the ESV module from before it was taken down.

**Comment by tuomas2** [comment]
> Is it legal to use the Wayback Machine link in the previous issue thread? As I understand it, it is an old mirror of the ESV module from before it was taken down.

What I know is that we can't distribute it, it would be illegal.
I am not lawyer so I don't now precisely if it is legal to use. 
If it is ethical to use, I would say that if one had earlier legally obtained ESV module and now has lost it, I would say it feels ethical to me to use it as a backup.
