### ISSUE TITLE
Link click highlight color - make it unhighlighted on click changeable

### ISSUE THREAD

**Issue by timbze** [AndBible/and-bible#999]
When clicking a link for a Bible reference, it opens in new window with a highlight.

[User here](https://support.andbible.org/scp/tickets.php?id=478) is asking to change highlight color because text is not very legible especially in night mode.

As discussed with @tuomas2, if highlight could be removed from clicking it that would be good for me, and probably would fix the user above's issue as well.

**Comment by tuomas2** [comment]
Fixed
